### ISSUE TITLE
fetchAuthSession: NotAuthorizedException: Unauthenticated access is not supported for this identity pool.

### ISSUE THREAD

**Issue by rallona** [aws-amplify/amplify-js#12648] opened 2023-11-29 10:44 UTC
### Describe the bug

It seems like the function doesnt authenticate well because I get **NotAuthorizedException: Unauthenticated access is not supported for this identity pool.**

```
import { createServerRunner } from '@aws-amplify/adapter-nextjs';
import config from '@/amplifyconfiguration.json';


export const { runWithAmplifyServerContext } = createServerRunner({
  config
});
```

I use in a Server Nextjs page:

```
import { fetchAuthSession,fetchUserAttributes } from 'aws-amplify/auth/server';

const currentUser = await runWithAmplifyServerContext({
      nextServerContext: { cookies },
      operation: async (contextSpec) => {
        try {
          const session = await fetchAuthSession(contextSpec, {});
```

But it generate the error:

 **NotAuthorizedException: Unauthenticated access is not supported for this identity pool.**

I have created the middleware.ts like in this example:

https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/#manage-auth-session-with-the-nextjs-middleware

and always redirect me to /login page, even just after login with google...

In console it gives me the same error: [NotAuthorizedException: Unauthenticated access is not supported for this identity pool.]

It seems like runWithAmplifyServerContext doesnt get the session after login???

Thanks for your help!!

The code is the same that in the documentation: [https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/#with-nextjs-app-router](https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/#with-nextjs-app-router)

### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

My amplifyconfiguration.json (Generated by amplify cli)

{
  "aws_project_region": "eu-west-1",
  "aws_cognito_identity_pool_id": "eu-west-XXXXXXXXXXXXXXbd3",
  "aws_cognito_region": "eu-west-1",
  "aws_user_pools_id": "eu-west-1_XXXXXXXXXX”,
  "aws_user_pools_web_client_id": "10XXXXXXXXX”,
  "oauth": {
    "domain": "XXXXXXXXXXX-develop.auth.eu-west-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "http://localhost:3000/dashboard/",
    "redirectSignOut": "http://localhost:3000/",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [
    "FACEBOOK",
    "GOOGLE"
  ],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ]
}

 aws-amplify: ^6.0.5 => 6.0.5
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
# Put output below this line

 npmGlobalPackages:
    @aws-amplify/cli: 12.8.2

```

</details>




### Expected behavior

No error

### Reproduction steps

Configure this: https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/#with-nextjs-app-router

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by rallona** [comment] 2023-11-29 11:47
I have created the middleware.ts like in this example:  

[https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/#manage-auth-session-with-the-nextjs-middleware](https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/#manage-auth-session-with-the-nextjs-middleware)

and always redirect me to /login page, even just after login with google... 

In console it gives me the same error: [NotAuthorizedException: Unauthenticated access is not supported for this identity pool.]

It seems like runWithAmplifyServerContext doesnt get the session after login???

**Comment by nadetastic** [comment] 2023-11-29 22:07
Hi @rallona thank you for opening this issue. I took a look at this an im unable to reproduce the issue, where i get the expected response on a server page. 
- [Here is a sample of server page.](https://github.com/nadetastic/next-js-amplified/blob/v6/12648/src/app/server/page.tsx)
- [Configuring Amplify at the root/layout of my app](https://github.com/nadetastic/next-js-amplified/blob/v6/12648/src/app/layout.tsx#L22)

Im curious how the rest of the Amplify configuration is done:
- how and where are you setting `Amplify.configure(config, {ssr: true})`
- Do you get expected response on a client side page? `use client`

**Comment by rallona** [comment] 2023-11-29 22:26
Hi @nadetastic 

I have set this only in client pages, not in server ones. But I can't neither access to the user data

```
Amplify.configure(config, {ssr: true})
```

The error surge in this line:

`const session = await fetchAuthSession(contextSpec`

The amplify login UI works well, it generate the user in cognito, but the page after login (the redirect page) doesn't get the user info...

**Comment by nadetastic** [comment] 2023-11-30 15:57
@rallona glad it worked! 😃 Will keep this open a bit longer so do let me know if you have any related questions!

**Comment by rallona** [comment] 2023-11-30 23:08
@nadetastic I dont understand nothing. Again fails, without any change....

**Comment by rallona** [comment] 2023-12-02 12:18
How can I check if contextSpec is correct?

```
const currentInfo = await runWithAmplifyServerContext({
      nextServerContext: { cookies },
      operation: async (contextSpec) => {
        try {
          const session = await fetchAuthSession(contextSpec, {});

```

**Comment by HuiSF** [comment] 2023-12-07 00:49
From this description:

>If I change my code to redirect after login to a client page all works and if I change the code to redirect to a server page, the browser keeps the session.

I think you are facing the same issue as https://github.com/aws-amplify/amplify-js/issues/12589

This is a known issue regarding the `signWithRedirect` API required side effect is not attached if redirect to a server render route other than the route where you called `signWithRedirect` API.

Current work around:

1. redirect back to the route (presumably `/sign-in`) where you call the `signWithRedirect` API, polling the session via calling `fetchAuthSession`, redirect to other route when returned `AuthSession` contains valid token

OR

2. force to bundle the `signInWithRedirect` side effect as mentioned in this comment: https://github.com/aws-amplify/amplify-js/issues/12589#issuecomment-1833666664

We are implementing a solution for this specific use case. Please stay tuned.

**Comment by nadetastic** [comment] 2024-02-13 04:15
This issue should now be resolved with the latest version of `aws-amplify`, so I will go ahead and mark it as closed. If you are still facing this problem please let me know.

**Closed by nadetastic** 2024-02-13 04:15 UTC
Labels: investigating, Auth, Next.js
