### ISSUE TITLE
Storage API doesn't throw error even if the CORS error

### ISSUE THREAD

**Issue by sasssssssa** [aws-amplify/amplify-js#9252] opened 2021-11-19 00:15 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

Chrome

### Describe the bug

Hi

We found a point for improvement in Storage API.
Storage API can't catch error even if CORS error occurs, the Promise is resolved.
I think it is better Storage API throw error.

#### StorageAPI-sample-code
```
async function put_s3() {
  // Specify a bucket that does not exist
  await Storage.put("test.txt", "Hello", { bucket: "XXXXX" }).then(
    (result) => {
      console.log("result!!!!");
      console.log(result)
    }
  ).catch(
    (error) => {
      console.log("error!!!!");
      console.log(error)
    }
  )
}
```

#### Browsers console log(Chrome)
```
Access to XMLHttpRequest at 'https://XXXXX.s3.ap-northeast-1.amazonaws.com/public/test.txt?x-id=PutObject' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index.js:1 [ERROR] 39:07.605 axios-http-handler - Network Error
...
App.js:48 result!!!!
App.js:49 {key: 'test.txt'}
```

I think this behavior is a little strange.
I checked the behavior of [axios](https://github.com/axios/axios), they throwed error.

#### axios-sample-code
```
  axios.post('/items')
    .then((response) => {
      console.log(response);
    })
    .catch((error) => {
      console.log("error!!!");
      console.log(error);
    });
```

Browsers console log
```
localhost/:1 Access to XMLHttpRequest at 'https://XXXXX/items' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
App.js:40 error!!!
App.js:41 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:99)
xhr.js:187 POST https://XXXXX/items net::ERR_FAILED 200
```

I checked Similar this issues
https://github.com/aws-amplify/amplify-js/issues/3419

But this issues seems to be fixed.

Thanks

**Comment by deepak-agarwal** [comment] 2022-02-01 08:32
Facing the same issue.

Even if you go offline in between an upload, the Storage.put promise is resolved. Should throw an error.

**Comment by gvankeerberghen** [comment] 2022-02-09 11:54
> Facing the same issue.
> 
> Even if you go offline in between an upload, the Storage.put promise is resolved. Should throw an error.

I think I'm observing the same very problematic issue here: Storage.put sometimes resolving though there is no file on S3.

My users mentioned a flaky connection when it happened.

It seems it only appeared in a recent version of `amplify-js` as I've just published with an upgrade from `3.3` to `4.3` and never had this issue before.

Need a solution fast, got hundreds of users who might get annoyed! Can't go back to version 3.3 given other dependencies.

## More explanation and code
I'm investigating an annoying bug in my react-native app which leads to thinking that Storage.put sometimes resolves even though the file has not been successfully uploaded to S3.

My impacted users tell me they had a flaky connection at the moment of upload.

I'm using Storage.put in a react-native app.
The piece of code that was running has been running fine for 2 years and still runs fine in the happy upload case.

I started to get this (3 times in 3 days now) since I published an updated version of my app which went from using `aws-amplify` version `3.3.27` to `4.3.12`.

```js
// concerned piece of code
...
  return Promise.resolve()
     // Pushes to S3 using Storage.put, implementation below
    .then(() => pushImageBase64Data(
        pictureData,
        `proofs/${offerId}__${Date.now()}.jpeg`,
     )
    // Writes in my db, which did happen though I have no file on S3
    .then(pictureKey =>
          pushProof({ shopId, offerId, pictureKey, latitude, longitude }),
     )
    .then(() => {
         // tell user success, which they saw
    })
    .catch(error => {
        // tell user failure, which they did not see
    });


// Call to Storage.put, not catch here so a throw here should prevent from writing in my db
const pushImageBase64Data = (data, key) => {
  return Promise.resolve(data)
    .then(data => new Buffer(data, 'base64'))
    .then(buffer => Storage.put(key, buffer, { contentType: 'image/jpeg' }))
    .then(get('key'));
};

**Comment by jamesaucode** [comment] 2022-02-10 03:58
Thanks for reporting. Looking into this issue now

**Comment by jamesaucode** [comment] 2022-02-10 17:02
I was able to reproduce the issue and identified the problem. I will do some more testing locally and get a PR up 😄

**Comment by gvankeerberghen** [comment] 2022-02-11 08:43
> I was able to reproduce the issue and identified the problem. I will do some more testing locally and get a PR up 😄

Great, thanks already for the work and the update on your progress!

Could you reproduce the CORS issue, the going offline during upload issue or both?
I haven't had the time to devise a setup involving a flaky connection for reproduction (solo-dev and busy times in my business), but maybe I could over the weekend if needed.

Looking forward to getting this fixed thanks to your PR!

**Comment by jamesaucode** [comment] 2022-02-14 22:18
Hey @gvankeerberghen, I have a draft PR out that fixes the CORS issue, and I'm pretty sure this will fix the flaky connection scenario too. Will do some testing on the flaky connection scenario and some code cleanup. Once those are ready I will send it to the team for review 😄

**Comment by gvankeerberghen** [comment] 2022-02-16 13:44
Hello @jamesaucode, great! Really looking forward to getting it. I got 3 more annoyed users since Monday already.

Would you have an estimate on the time to having this patch released?
Is it more like 1 day or 2, or 1 week or 2, or a month ? If it's too long I'll have to consider patching the package locally and publishing a patch of my app.

**Comment by jamesaucode** [comment] 2022-02-17 22:20
Hey @gvankeerberghen , we can't give you an exact date for when the patch is gonna ship. I would recommend using an older version that works for you (e.g 4.3.0 shouldn't have the change to `axios-http-handler` yet) for now. Or as you say you can also patch it locally for your app.

**Closed** 2022-03-23 19:19 UTC
Labels: Storage, pending-triage
