### ISSUE TITLE
After disabling the user still the user is in the app. It not shows the error not authenticated immediately

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6269] opened 2020-07-09 03:15 UTC
After disabling the user still the user is in the app. It not shows the error not authenticated immediately in aws-amplify-react-native

**Comment by mauerbac** [comment] 2020-07-09 13:40
Looks like a duplicate of your previous question. Closing.

**Closed by mauerbac** 2020-07-09 13:40 UTC
Labels: to-be-reproduced
