### ISSUE TITLE
Analytics.updateEndpoint() ignores channelType

### ISSUE THREAD

**Issue by tanner-west** [aws-amplify/amplify-js#6571] opened 2020-08-13 18:54 UTC
**Describe the bug**
In a React Native app, I am generating a push notification token and registering it to a Pinpoint endpoint using the following code. Since this project is in development, I need the channel type to be "APNS_SANDBOX"

```javascript
  Analytics.updateEndpoint({
    address: token,
    channelType: "APNS_SANDBOX"
  })
```

This registers the endpoint, but the endpoint is registered with an "APNS" channel type. I can see this when I export segments containing the endpoints.

**To Reproduce**
 Run the above code in a React Native project with a valid push notification token.

**Expected behavior**
I expect the resulting endpoint to be registered with channel type "APNS_SANDBOX" instead of "APNS"

**Code Snippet**
See above

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
I used the Amplify CLI to add Auth, Analytics, and Notifications
* Which resources do you have configured?
Auth, Analytics, and Notifications

  * If applicable, please provide your `aws-exports` file:
```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:redacted",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_redacted",
    "aws_user_pools_web_client_id": "redacted",
    "oauth": {},
    "aws_mobile_analytics_app_id": "redacted",
    "aws_mobile_analytics_app_region": "us-east-1"
};
   ```
   
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
 System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.79 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 78.0.1
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/pushnotification: ^3.1.9 => 3.1.9 
    @babel/core: ^7.0.0 => 7.8.4 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: 5.9.2 => 5.9.2 
    @react-native-community/push-notification-ios: ^1.4.0 => 1.4.0 
    @react-navigation/native: ^5.0.7 => 5.0.7 
    @react-navigation/stack: ^5.0.9 => 5.0.9 
    @types/react: ~16.9.41 => 16.9.41 
    @types/react-native: ~0.62.13 => 0.62.13 
    amazon-cognito-identity-js: ^4.3.3 => 4.3.3 
    aws-amplify: ^3.0.23 => 3.0.23 
    aws-amplify-react-native: ^4.2.0 => 4.2.0 
    axios: ^0.19.2 => 0.19.2 
    babel-jest: ~25.2.6 => 25.2.6 
    babel-preset-expo: ^8.2.3 => 8.2.3 
    date-fns: ^2.14.0 => 2.14.0 
    expo: ^38.0.0 => 38.0.3 
    expo-av: ~8.2.1 => 8.2.1 
    expo-file-system: ~9.0.1 => 9.0.1 
    expo-notifications: ~0.3.3 => 0.3.3 
    expo-splash-screen: ~0.3.1 => 0.3.1 
    expo-sqlite: ~8.2.1 => 8.2.1 
    expo-status-bar: ^1.0.0 => 1.0.2 
    expo-updates: ~0.2.10 => 0.2.11 
    expo-web-browser: ^8.3.1 => 8.3.1 
    fast-xml-parser: ^3.17.4 => 3.17.4 
    formik: ^2.1.4 => 2.1.4 
    html-entities: ^1.2.1 => 1.2.1 
    jest: ~25.2.6 => 25.2.7 
    lodash: ^4.17.19 => 4.17.19 
    react: ~16.11.0 => 16.11.0 
    react-dom: 16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
    react-native-elements: ^2.0.2 => 2.0.2 
    react-native-gesture-handler: ~1.6.0 => 1.6.1 
    react-native-keyboard-aware-scroll-view: ^0.9.1 => 0.9.1 
    react-native-modal: ^11.5.6 => 11.5.6 
    react-native-reanimated: ~1.9.0 => 1.9.0 
    react-native-render-html: ^4.2.0 => 4.2.0 
    react-native-safe-area-context: 3.0.2 => 3.0.2 
    react-native-screens: ~2.9.0 => 2.9.0 
    react-native-unimodules: ~0.10.1 => 0.10.1 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-native-video: ^4.4.5 => 4.4.5 
    react-native-web: ~0.11.7 => 0.11.7 
    react-native-webview: ^10.3.2 => 10.3.2 
    react-redux: ^7.2.0 => 7.2.0 
    react-test-renderer: ~16.11.0 => 16.11.0 
    redux: ^4.0.5 => 4.0.5 
    redux-axios-middleware: ^4.0.1 => 4.0.1 
    redux-saga: ^1.1.3 => 1.1.3 
    typescript: ~3.9.5 => 3.9.5 
    yup: ^0.28.3 => 0.28.5 
  npmGlobalPackages:
    @aws-amplify/cli: 4.27.0
    appium-doctor: 1.13.0
    appium: 1.16.0
    browser-sync: 2.26.7
    canvas-sketch-cli: 1.11.1
    cpy-cli: 3.0.0
    detox-cli: 10.0.7
    eslint: 6.8.0
    expo-cli: 3.23.1
    express-generator: 4.16.1
    gatsby-cli: 2.8.3
    grunt: 1.0.4
    lighthouse: 6.1.1
    ncp: 2.0.0
    nodemon: 1.19.1
    npm: 6.9.0
    qrcode: 1.4.4
```

</details>

**Smartphone (please complete the following information):**

- Device: [iPhone X]
- OS: [iOS13.6]
- Browser [n/a]
- Version [n/a]

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by iartemiev** [comment] 2021-04-04 12:47
Hey @tanner-west, I was unable to reproduce this. When inspecting the network request for an endpoint update, I see the specified `channelType` value being sent. 
Can you please check if the library is sending `APNS_SANDBOX` or `APNS` in the request?

**Comment by iartemiev** [comment] 2021-04-12 18:15
@tanner-west,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:15 UTC
Labels: Analytics, Can't reproduce, React Native, pending-close-response-required
