### ISSUE TITLE
Amazon lex suddenly started to give me this error

### ISSUE THREAD

**Issue by zandvakiliramin** [aws-amplify/amplify-js#10893] opened 2023-01-23 04:04 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Interactions

### Amplify Categories

interactions

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.7.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 2.34 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2022.12.19.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @aws-sdk/protocol-http: ^3.254.0 => 3.254.0 (3.6.1, 3.186.0)
    @aws-sdk/querystring-builder: ^3.53.0 => 3.53.0 (3.6.1, 3.186.0)
    @babel/core: ^7.12.9 => 7.20.12 
    @expo-google-fonts/inter: ^0.2.0 => 0.2.2 
    @expo/metro-config: ^0.3.9 => 0.3.22 (0.3.19)
    @expo/react-native-action-sheet: ^3.13.0 => 3.14.0 
    @expo/vector-icons: ^13.0.0 => 13.0.0 
    @flyerhq/react-native-chat-ui: ^1.4.3 => 1.4.3 
    @flyerhq/react-native-link-preview: ^1.6.0 => 1.6.0 
    @gorhom/bottom-sheet: ^4.2.2 => 4.4.5 
    @react-native-async-storage/async-storage: ~1.17.3 => 1.17.11 
    @react-native-community/netinfo: 8.2.0 => 8.2.0 
    @react-native-picker/picker: 2.4.0 => 2.4.0 
    @react-navigation/bottom-tabs: ^6.0.9 => 6.5.3 
    @react-navigation/native: ^6.0.6 => 6.1.2 
    @react-navigation/native-stack: ^6.2.5 => 6.9.8 
    @types/react: ~17.0.21 => 17.0.53 
    @types/react-native: ~0.67.6 => 0.67.17 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.8 => 5.2.14 
    aws-amplify: ^4.3.8 => 4.3.45 
    aws-amplify-react-native: ^6.0.1 => 6.0.8 
    expo: ^45.0.0 => 45.0.8 
    expo-asset: ~8.5.0 => 8.5.0 
    expo-constants: ~13.1.1 => 13.1.1 
    expo-device: ~4.2.0 => 4.2.0 
    expo-font: ~10.1.0 => 10.1.0 
    expo-image-manipulator: ~10.3.1 => 10.3.1 
    expo-image-picker: ~13.1.1 => 13.1.1 
    expo-linking: ~3.1.0 => 3.1.0 
    expo-notifications: ~0.15.4 => 0.15.4 
    expo-permissions: ~13.2.0 => 13.2.0 
    expo-secure-store: ~11.2.0 => 11.2.0 
    expo-server-sdk: ^3.6.0 => 3.7.0 
    expo-splash-screen: ~0.15.1 => 0.15.1 
    expo-status-bar: ~1.3.0 => 1.3.0 
    expo-task-manager: ~10.2.1 => 10.2.1 
    expo-updates: ~0.13.4 => 0.13.4 
    expo-web-browser: ~10.2.1 => 10.2.1 
    graphql-tag: ^2.12.6 => 2.12.6 
    hermes-inspector-msggen:  1.0.0 
    jest-expo: ^45.0.0 => 45.0.1 
    jq: ^1.7.2 => 1.7.2 
    moment: ^2.29.3 => 2.29.4 
    openai: ^3.1.0 => 3.1.0 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    react-hook-form: ^7.27.1 => 7.42.1 
    react-native: 0.68.2 => 0.68.2 
    react-native-alert-async: ^1.0.5 => 1.0.5 
    react-native-chart-kit: ^6.12.0 => 6.12.0 
    react-native-gesture-handler: ~2.2.1 => 2.2.1 
    react-native-reanimated: ~2.8.0 => 2.8.0 
    react-native-safe-area-context: 4.2.4 => 4.2.4 
    react-native-screens: ~3.11.1 => 3.11.1 
    react-native-svg: 12.3.0 => 12.3.0 
    react-native-url-polyfill: ^1.3.0 => 1.3.0 
    react-native-uuid: ^2.0.1 => 2.0.1 
    react-native-web: 0.17.7 => 0.17.7 
    react-native-webview: 11.18.1 => 11.18.1 
    react-native-youtube-iframe: ^2.2.2 => 2.2.2 
    typescript: ~4.3.5 => 4.3.5 
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.2
    @expo/ngrok: 4.1.0
    eas-cli: 3.3.2
    expo-cli: 6.1.0
    live-server: 1.2.1
    nodeman: 1.1.2
    nodemon: 2.0.15
    npm: 9.2.0
    pod-install: 0.1.38
    serverless: 3.26.0
    yarn: 1.22.19

```

</details>

### Describe the bug

When I try to use the `Interactions.send("MyBot", text)` I get an error telling me Error: URL.hostname is not implemented. The same snippet of code used to work perfectly before. I have just no idea what might have gone wrong.

 

### Expected behavior

I expect it to give me the intent like it used to do before.

### Reproduction steps

I have no idea how this has happened. I might have installed some packages, and didn't notice they messed up things.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment] 2023-01-23 15:11
Hi @zandvakiliramin 
Did you upgrade any of the aws/amplify packages or the react-native package in your project?

**Comment by zandvakiliramin** [comment] 2023-01-25 19:49
Hi @tannerabread 
I installed AWS pinpoint node SDK to see if it works on React Native.  I think this started to happen when I uninstalled it using `npm uninstall @aws-sdk/client-pinpoint`.

Also, when I add the following lines to my code, it starts to work again:

```{javascript}
import "react-native-url-polyfill/auto";
import "react-native-get-random-values";
```
But the problem is that I am using Exp and use `eas build` to build applications for Android and IOS. When I get a build, the stand-alone stops working and gives me an error that the module doesn't have Java implementation.

**Comment by tannerabread** [comment] 2023-01-25 21:21
Unfortunately we do not currently support EAS builds. It's possible it might seem like it is working for the most part but there could be problems that we would not be able to help with. See #9605 for more details and to track. 

For the other problem, have you tried on a new branch of your project deleting the node_modules folder and the package_lock.json and trying to reinstall? I'm not sure if deleting the sdk in the way you did might have deleted some necessary dependencies for other packages

**Comment by tannerabread** [comment] 2023-02-01 17:05
@zandvakiliramin I may have been mistaken about the EAS support, someone on my team was able to get an EAS build working and it may just be UI packages that do not work as expected.

To return to the original issue, I was able to reproduce this just following the basic setup in our docs for Interactions while using amplify v5.0.11.

I will try to do some more investigating to see if I can figure out what version the problem starts to happen on

**Comment by tannerabread** [comment] 2023-02-01 21:23
It seems to break on version 4.3.38+, I will have someone look deeper into this to find the root cause

**Comment by tannerabread** [comment] 2023-02-02 22:06
@zandvakiliramin the polyfill was the way to go. There were some updates to the sdk that removed polyfills and so we now ask that you install them manually, like you have done. 

We show this [here in the in-app messaging docs](https://docs.amplify.aws/lib/in-app-messaging/integrate-your-application/q/platform/react-native/#install-amplify-and-its-dependencies) and I will be adding it either to the project setup for react native docs or to the individual category itself

**Comment by tannerabread** [comment] 2023-02-10 18:18
@zandvakiliramin this has been fixed with the above PR.

You can see the changes [here in the docs](https://docs.amplify.aws/lib/interactions/getting-started/q/platform/react-native/#install-amplify-and-its-dependencies)

Thank you for bringing this to our attention!

**Closed by tannerabread** 2023-02-10 18:18 UTC
Labels: documentation, Interactions, React Native

**Comment by zandvakiliramin** [comment] 2023-02-10 20:16
@tannerabread Thank you
