### ISSUE TITLE
Inconsistent Translation Behaviour for Amplify UI Components

### ISSUE THREAD

**Issue by liamaws** [aws-amplify/amplify-js#6115] opened 2020-06-18 18:42 UTC
**Describe the bug**
When providing translations for amplify UI components only some fields update with the provided translation.

**To Reproduce**

1. Clone https://github.com/xavierraffin/fizz-demo
2. Checkout branch noformfields
3. npm install
4. npm start
5. amplify init 
6. toggle the lang using the top button

**Expected behavior**
The language of all fields that have a provided translation should update.

**Code Snippet**
Using https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/common/Translations.ts as reference for labels

String file https://github.com/xavierraffin/fizz-demo/blob/noformfields/src/strings.js

```
export const strings = {
    en: {
        signInHeader: "Sign in your Fizz account",
        signUpHeader: "Create your fizz account",
        forgotPasswordHeader: "Custom Header Reset Password",
    },
    fr: {
        signInHeader: "Sign in your Fizz account FR",
        signUpHeader: "Create your fizz account FR",
        forgotPasswordHeader: "Custom Header Reset Password FR",
        [Translations.NO_ACCOUNT_TEXT]: 'No account? FR',
        [Translations.CREATE_ACCOUNT_TEXT]: 'Create account FR',
        [Translations.SIGN_IN_ACTION]: 'Sign In FR',
        [Translations.SIGN_IN_HEADER_TEXT]: 'Sign in to your account FR',
        [Translations.SIGN_IN_TEXT]: 'Sign in FR',
        [Translations.SIGN_UP_EMAIL_PLACEHOLDER]: 'Email FR',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? FR',
        [Translations.SIGN_UP_HEADER_TEXT]: 'Create a new account FR',
        [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: 'Password FR',
        [Translations.SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Create Account FR',
        [Translations.SIGN_UP_USERNAME_PLACEHOLDER]: 'Username FR',
        [Translations.SEND_CODE]: 'Send Code FR',
        [Translations.BACK_TO_SIGN_IN]: 'Back to Sign In FR',
        [Translations.EMAIL_LABEL]: 'Email Address * FR',
        [Translations.EMAIL_PLACEHOLDER]: 'Enter your email address FR',
        [Translations.FORGOT_PASSWORD_TEXT]: 'Forgot your password? FR',
        [Translations.RESET_PASSWORD_TEXT]: 'Reset password FR',
        [Translations.PASSWORD_LABEL]: 'Password * FR',
        [Translations.PASSWORD_PLACEHOLDER]: 'Enter your password FR',
        [Translations.PHONE_LABEL]: 'Phone Number *' FR,
    },
};
```

App.js @ https://github.com/xavierraffin/fizz-demo/blob/noformfields/src/App.js

**Screenshots**

![image](https://user-images.githubusercontent.com/67014943/85058479-2dbc7380-b170-11ea-9d85-0df86201a9df.png)

Some fields change to French (No account? FR , Create Account FR) but others don't even though translation was provided in the strings file.

![image](https://user-images.githubusercontent.com/67014943/85059043-fd290980-b170-11ea-8d39-4cbd3968802e.png)

Another example from the password reset page. "Email address" and "Enter your email address" don't change to FR but other fields do.

**What is Configured?**
aws-exports file

```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lS7n2f1Qc",
    "aws_user_pools_web_client_id": "47e3b0vaomk2fdoe0juk568bh0",
    "oauth": {},
    "aws_content_delivery_bucket": "fizz-20200504180301-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d305j9em31fpv1.cloudfront.net"
};
```

https://github.com/xavierraffin/fizz-demo/blob/noformfields/package.json

 

<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 989.57 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Firefox: 68.8.0
    Safari: 13.1
  npmPackages:
    @aws-amplify/ui-react: ^0.2.8 => 0.2.8 
    @testing-library/jest-dom: ^5.9.0 => 5.9.0 
    @testing-library/react: ^10.2.0 => 10.2.0 
    @testing-library/user-event: ^11.2.1 => 11.2.1 
    aws-amplify: ^3.0.16 => 3.0.16 
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-scripts: 3.4.1 => 3.4.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.3
    npm: 6.14.4

```

</details>

**Comment by liamaws** [comment] 2020-06-18 19:01
Somewhat related to https://github.com/aws-amplify/amplify-js/issues/5679

**Comment by xavierraffin** [comment] 2020-07-14 18:46
I am working with Liam
You can live test here to see the problem (the field that doen's translate): https://d23vbzcww6xd16.cloudfront.net

**Comment by amhinson** [comment] 2020-07-14 22:29
@liamaws @xavierraffin When I run the sample app you provided, I am seeing all of the fields specified in `strings.js` change correctly. I only needed to add French translations for the forgot & reset password texts:

```js
[Translations.FORGOT_PASSWORD_TEXT]: "Mot de passe oublié?",
[Translations.RESET_PASSWORD_TEXT]: "Réinitialiser le mot de passe",
```

![Kapture 2020-07-14 at 15 20 10](https://user-images.githubusercontent.com/17091790/87482076-894e1580-c5e5-11ea-873e-b391e6240c36.gif)

Are you still having issues?

**Comment by xavierraffin** [comment] 2020-07-14 22:49
checking

**Comment by xavierraffin** [comment] 2020-07-14 23:15
@amhinson I checked we still have the problem.
I deployed here with only the Amplify translation strings: https://d3khcqcz8fq6p9.cloudfront.net/

(see [my changes](https://github.com/xavierraffin/amplify-identity-broker/commit/b358155a693b8041abc000f0f071dd329bf1cfa3))

Many field are not translating.

My String file is https://github.com/xavierraffin/amplify-identity-broker/blob/master/src/strings.js

Project is available here if you like: https://github.com/xavierraffin/amplify-identity-broker (master branch)

**Comment by amhinson** [comment] 2020-07-15 00:05
Ah ok, I was working with `fizz-demo` instead of `amplify-identity-broker`. I am now able to replicate the issue you're seeing!

If I change the browser default language to French, I am able to see **all** the initial translations showing in French as expected, but toggling the button produces the same behavior as it does when it is in English where only 2 fields are updating.

This makes me think that some of the Amplify UI components are not getting re-rendered when `state.lang` changes or the `I18n` language is updated, meaning they are not showing the new translations. I'll continue digging into this.

With that said, if you need a quick fix for this, you can use the custom text properties for each component (i.e. `headerText` and `submitButtonText` for [AmplifySignIn](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#sign-in)) as well as the `label` property for the `formFields` and be explicit about their values like you have in the [fizz-demo](https://github.com/xavierraffin/fizz-demo) example. Setting these values will make the Amplify UI components re-render, as expected.

```js
<AmplifySignIn
  usernameAlias="email"
  headerText={I18n.get(Translations.SIGN_IN_HEADER_TEXT)}
  slot="sign-in"
  submitButtonText={I18n.get(Translations.SIGN_IN_ACTION)}
  formFields={[
    {
      type: "email",
      label: I18n.get(Translations.EMAIL_LABEL),
      placeholder: I18n.get(Translations.EMAIL_PLACEHOLDER),
      required: true,
    },
    {
      type: "password",
      label: I18n.get(Translations.PASSWORD_LABEL),
      placeholder: I18n.get(Translations.PASSWORD_PLACEHOLDER),
      required: true,
    }
  ]}>
```

**Comment by jordanranz** [comment] 2020-07-16 17:19
Thanks for the the workaround @amhinson. 

I was able to reproduce this locally and I believe I found the root cause of the issue we are seeing. It seems `I18n.get` for the strings in question will be translated on mount of the component but when rerendered `I18n.get` is not called again and uses the initial string value.

I may have a fix, I'll ping this issue when I have an update.

**Comment by jordanranz** [comment] 2020-07-22 20:27
I have just merged a change for this and tested my branch against the sample repo. Please try and test that the functionality is correct by installing the `@unstable` version.

**Comment by liamaws** [comment] 2020-07-24 14:09
Yes the translations are now all changing properly

**Comment by jordanranz** [comment] 2020-07-30 20:10
This should be published to `@latest`. Please open a new issue if you run into any similar problems.

**Closed by jordanranz** 2020-07-30 20:10 UTC
Labels: Amplify UI Components, awaiting-lib-publish
