### ISSUE TITLE
Federated sign in

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#4375] opened 2019-11-11 12:45 UTC
When using Facebook and Google federated sign in on my Angular/Ionic project it seems that some state/session information is being saved and causing errors:

This error does not occur on incognito mode within chrome, only one device and normal browser.

1. sign in using federated sign in (this.amplify.auth().federatedSignIn({provider: 'Facebook'}))
2. Delete the newly created cognito user from the console
3. Sign in again with the same function

With the user deleted, it then starts to error and wont create the new cognito user.:

> Unhandled Promise rejection: undefined is not an object (evaluating 'i.accessToken') 

If I repeat the process but open a new incognito window, the error does not occur.

Note: This error also occurs after i wipe all session and local storage and do a hard reset of the browser.

**Comment by ericclemmons** [comment] 2019-12-30 17:11
Your scenario makes sense: starting an incognito window is like starting a new session, while in a normal browser there's data in local storage being persisted.

Thanks for your thorough description!  I'll replicate this locally and see if there's a small fix to our logic paths (`i.accessToken` shouldn't have been evaluated), or if we should clear storage entirely when `federatedSignIn` is being called.

**Comment by ericclemmons** [comment] 2019-12-31 17:30
I was able to reproduce this:

1. Open up sample app with federated sign in.
1. Login with Facebook/Google/whatever.
1. `amplify console auth` (open Both, 'cause why not?).
1. Disable the user:

	> <img width="498" alt="Screen Shot 2019-12-31 at 9 28 17 AM" src="https://user-images.githubusercontent.com/15182/71629019-ee916a80-2baf-11ea-8435-c0d8fb61ee5a.png">
1. Delete the user:

	> <img width="592" alt="Screen Shot 2019-12-31 at 9 28 23 AM" src="https://user-images.githubusercontent.com/15182/71629031-ffda7700-2baf-11ea-8bb5-fec6d4e8b893.png">

1. Refresh the app (user is signed in because that's how tokens work).
1. Sign Out.
1. Login with the same social provider as before.
	1. Oddly enough, I had to refresh for the code to finally "stick". Couldn't reproduce this though, so moving on...
1. Refresh, then 💥

	> <img width="1208" alt="Screen Shot 2019-12-31 at 9 27 36 AM" src="https://user-images.githubusercontent.com/15182/71629074-331d0600-2bb0-11ea-8bc1-a8d3f73d31b6.png">

**Comment by ericclemmons** [comment] 2019-12-31 17:52
However, it's worth noting that this is a similar bug for a _different reason_ than what @oliverandersencox is likely experiencing.

**Comment by ericclemmons** [comment] 2019-12-31 18:04
@oliverandersencox Can you clarify something for me? When you sign in after deleting the Cognito user, **are you signing out first** or not?

Thanks!

**Comment by ericclemmons** [comment] 2020-01-02 17:01
One fix that should could be made for this is throwing here:
https://github.com/aws-amplify/amplify-js/blob/510f86ef39bae3fba9a17deb630237a64c9dc7dc/packages/auth/src/OAuth/OAuth.ts#L225-L227

Calls to this function aren't expecting `undefined`, so throwing makes sense for `invalid_grant` errors (which is usually do to an older `code`).

Still need to figure out what error is happening specific to @oliverandersencox's scenario though...

**Comment by ericclemmons** [comment] 2020-01-08 00:28
I opened #4679 that will prevent the destructuring of `undefined`.  Once that's merged & released, we can get visibility into what error is happening specific to your use-case.

**Comment by ericclemmons** [comment] 2020-01-13 18:55
Once #4679 is tagged & released this week, let's follow-up to see which error still occurs...

**Comment by oliverandersencox** [comment] 2020-01-13 18:58
Hi @ericclemmons, sorry for the late response!

So i've tried both scenarios, that being I am still signed in when deleting and when I'm signed out. Both yielded the same result.

**Comment by ericclemmons** [comment] 2020-01-13 19:08
Let's await this tagged release & see what happens.  I think the error you're seeing may be the same as what I reproduced here: https://github.com/aws-amplify/amplify-js/issues/4375#issuecomment-569963165

We'll know for sure once the tag is out 👀

**Comment by ashika01** [comment] 2020-06-05 22:03
@oliverandersencox Is this still an issue? Looks like the fix was out a long time ago?

**Comment by ashika01** [comment] 2020-06-05 23:19
I am closing this issue. If you still continue have this issue, let us know and we can reopen this ticket for you.

**Closed by ashika01** 2020-06-05 23:19 UTC
Labels: Auth, bug, pending-close-response-required
