### ISSUE TITLE
[Feedback] ability to disable sign up on sign in component

### ISSUE THREAD

**Issue by srchulo** [aws-amplify/amplify-js#6091] opened 2020-06-14 20:35 UTC
**Page**: [`/ui/auth/authenticator/q/framework/vue`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue)

**Feedback**:

It looks like in the latest version of the Vue UI components, there's no way to hide "Create account" on the sign in component. It would be great to have this!

**Comment by mauerbac** [comment] 2020-06-15 13:50
@srchulo - curious what the use case for hiding create new account is? To not confuse users?

**Comment by srchulo** [comment] 2020-06-15 16:26
Most of the apps that I build are invite only and don't usually support a sign up flow. Or it's a more complicated sign up flow that they don't do on the site, but we handle together in a meeting before they can actually login.

**Comment by srchulo** [comment] 2020-06-15 16:27
And yes, to not confuse users. I actually have sign ups turned off in the user pool, so you can go through the create account flow, but then you get an 400 error.

**Comment by amhinson** [comment] 2020-06-15 20:16
This looks to be a duplicate of another recent feature request. I'm going to close this in favor of the (slightly) older issue: https://github.com/aws-amplify/amplify-js/issues/6089

**Closed by amhinson** 2020-06-15 20:16 UTC
Labels: Vue, feature-request

**Comment by srchulo** [comment] 2020-06-17 00:55
@amhinson thanks for linking that issue. That actually had a solution for me!

    <amplify-authenticator>
        <amplify-sign-in slot="sign-in">
            
            <div slot="secondary-footer-content"></div>
        </amplify-sign-in>

        <nuxt />
        <amplify-sign-out></amplify-sign-out>
    </amplify-authenticator>

**Comment by jordanranz** [comment] 2020-06-22 17:36
I have just added a prop to the sign-in component to handle this more intuitively if you'd like to use it instead:
```
<amplify-sign-in slot="sign-in" hide-sign-up></amplify-sign-in>
```

**Comment by srchulo** [comment] 2020-06-23 00:23
@jordanranz That works great, thanks!
