### ISSUE TITLE
doesn't work with angular 8 

### ISSUE THREAD

**Issue by henrysachs** [aws-amplify/amplify-js#3193] opened 2019-04-29 18:16 UTC
**Describe the bug**
develop your application run ng build and see the error below. It only fails when compiling. I migrated from angular 7 to 8. 

**Screenshots**

**Desktop (please complete the following information):**
Angular 8

**Additional context**
```
:8080/vendor-es2015.js:180795 Uncaught ReferenceError: process is not defined
    at Object../node_modules/aws-sdk/lib/browser_loader.js (:8080/vendor-es2015.js:180795)
    at __webpack_require__ (:8080/runtime-es2015.js:79)
    at Object../node_modules/aws-sdk/browser.js (:8080/vendor-es2015.js:179691)
    at __webpack_require__ (:8080/runtime-es2015.js:79)
    at Object../node_modules/@aws-amplify/core/lib/Facet.js (:8080/vendor-es2015.js:160462)
    at __webpack_require__ (:8080/runtime-es2015.js:79)
    at Object../node_modules/@aws-amplify/core/lib/index.js (:8080/vendor-es2015.js:162463)
    at __webpack_require__ (:8080/runtime-es2015.js:79)
    at Object../node_modules/@aws-amplify/auth/lib/Auth.js (:8080/vendor-es2015.js:156332)
    at __webpack_require__ (:8080/runtime-es2015.js:79)
```

**Comment by henrysachs** [comment] 2019-04-29 18:56
this seems to be somehow related to the build target in the tsconfig.json.

**Comment by henrysachs** [comment] 2019-05-09 16:16
any update on this?

**Comment by dssantana** [comment] 2019-05-30 12:40
same issue here, any updates?

**Comment by gerrytsui** [comment] 2019-05-30 19:23
I have no problem upgrading my project to Angular 8.0.0 ( released yesterday) . No problem with ng [ serve | test | e2e | build --prod --aot]
with enableIvy set to false.
Applied the patch to Auth.js ( the JS.isEmpty of this._config.storage)

My project uses {  Auth, API, Analytics, ServiceWorker, Logger, Hub} from 'aws-amplify';
Here is my tsconfig.json:

> {
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  //"angularCompilerOptions": {
  //  "enableIvy": true
  //},
  "files": [
    "src/aws-exports.ts"
  ]
}

**Comment by dssantana** [comment] 2019-05-30 21:04
@gerrytsui have you published your build and opened it in a browser? There are no problems serving or building, the problem is using the build

**Comment by dssantana** [comment] 2019-05-30 21:08
@hernysachs I can build with the version released yesterday but I can’t use the build when published.

**Comment by pl4yradam** [comment] 2019-05-31 07:05
@dssantana I have also been investigating this, you will see online there are things to do (window process). All this does is masks the error. im the same, dev does not work with angular 8 and amplify js.

My project uses { Auth, API, Analytics, ServiceWorker, Logger, Hub} from 'aws-amplify';

Do you think its worth getting a simple repo implemented showcasing the failure? NG Serve works fine, its to do with when it compiles the js through es and es2015 and by the looks of things how it uses 2015.

I wouldn't expect AWS to be behind with this

**Comment by gerrytsui** [comment] 2019-05-31 11:20
OK. I have problem with the build too getting something about process in the console.
This fixes it: Change from es2015 to es5
    //"target": "es2015",
    "target": "es5",

**Comment by dssantana** [comment] 2019-05-31 11:28
> This fixes it: Change from es2015 to es5
//"target": "es2015",
"target": "es5",

Not really, it's a workaround but you missed using es2015, one of the big changes in angular 8.

**Comment by pl4yradam** [comment] 2019-05-31 11:41
Guys to help best assist the situation:
 - Put down your package versions for amplify
 - Send the tsconfig
 - If you are using ivy or not

**Comment by dssantana** [comment] 2019-05-31 13:17
`"aws-amplify": "1.1.28",
 "aws-amplify-angular": "3.0.3",`

`"compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./src",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018",
            "dom"
        ],`

I'm not using Ivy

**Comment by gerrytsui** [comment] 2019-05-31 13:45
The "uncaught ReferenceError: process is not defined" is similar to the "global" we got back when we upgraded to angular 6. If you recall we were instructed per Amplify angular doc to add the following into the polyfills.ts

> (window as any).global = window; 

As a test I also inserted the following

> (window as any).process = {
    env: { DEBUG: undefined },
  };

and it is fine now with target: es2015

My customer service_worker.js is still working.. I have to research further.


    "aws-amplify": "^1.1.28",
    "aws-amplify-angular": "^3.0.3",
angular-cli 8.0.1
all other NPM are up-to-date except Typescript is 3.4.5 ( not 3.5.x)

**Comment by gerrytsui** [comment] 2019-05-31 13:58
By defined a dummy "process" my webapp works 100% excepts the Pinout/Analytics recording calls are failing.

Ideally amplify/analytics should be upgraded to use the new Angular 8 Web Worker.

In the mean time I will be using  target es5. Angular 8 is just a preview/transition to Ivy/Angular 9 ( in Oct/Nov)

**Comment by gerrytsui** [comment] 2019-05-31 14:08
OK. I found a way to properly Polyfill the "process is not defined"

 npm install -S process

the add the following to your polyfills.ts

> import * as process from 'process';
window['process'] = process;

and set tsconfig.json

>     "target": "es2015",

**Comment by pl4yradam** [comment] 2019-05-31 15:27
I am not sold yet on putting the process flag in as it seems like a bandage
rather than something more solid. I can understand the window global though.

**Comment by henrysachs** [comment] 2019-07-03 19:35
i agree with @pl4yradam and just commenting to not mark this as stale.

**Comment by cfarfan** [comment] 2019-07-10 16:30
I'm having this issue too, solved using process polyfill (thanks @gerrytsui ) but I'm not sure if this approach is the best.

**Comment by miiihi** [comment] 2019-07-12 11:42
Solved with adding following to polyfills.ts
```
// window.process needed by aws-amplify
(window as any).process = { browser: true };
```
as this is the same definition as aws browser loader tries to apply but fails because of undefined process. 
see aws-sdk/lib/browser_loader.js:L35
```
if (typeof process === 'undefined') {
  process = {
    browser: true
  };
}
```

**Comment by anhnguyen72** [comment] 2019-07-16 04:33
"angularCompilerOptions": {
    "enableIvy": false
  }
Set enableIvy=false at tsconfig.app.json. This work for me

**Comment by serekgrecki** [comment] 2019-07-17 14:52
my solution, it works for me with angular 8: 
 1. yarn add process, yarn add @types/node
 2. in polyfills.ts add:
`import * as process from 'process'; `
`window['process'] = process;`
3. in tsconfig.app.json add:
`  "compilerOptions": {`
  `  ...`
   ` "types": ["node"]`
 ` }`
4. tsconfig.json
`"target": "es2015"`

**Comment by damogallagher** [comment] 2019-07-22 18:13
Hi

Just wondering is this the correct solution?
I am currently upgrading an app from Angular 6 to Angular 8 and part of the app functionality is not working.
We are loading application properties as follows - process.env.APPLICATION_API_URL but all these properties are null now.
I was wondering is it a case that angular have removed support for the process or is it related to using Amplify?
I am upgrading to version 8.1.2 of angular , 1.1.32 of aws-amplify and 3.0.7 of aws-amplify-angular.
We are not using Ivy.

Any help here is greatly appreciated

**Comment by sammartinez** [comment] 2019-07-30 20:05
We do call this out in our documentation that we let people know to use [polyfills](https://aws-amplify.github.io/docs/js/angular#angular-6-support) in order to resolve this issue. The Compiler Options are also called out in the next section of the link, [Setup](https://aws-amplify.github.io/docs/js/angular#setup). Resolving issue as the the above links as well as the above solutions is what we would do as well.

**Closed by sammartinez** 2019-07-30 20:05 UTC
Labels: Angular, TypeScript

**Comment by henrysachs** [comment] 2019-07-30 21:03
Then add it to your documentation for angular 8 support.

**Comment by Prinsn** [comment] 2019-08-12 15:08
Migrating from Angular 7 to 8 and this popped up.

The documentation would suggest that if it worked for 6 it would work for 7 and 8, so this is pretty perplexing.

**Comment by fishermr** [comment] 2019-08-19 10:34
This solution worked for my AWS Angular project  written up in the current Amplify doc:
Angular 8.0.1
Amplify 1.1.29
polyfills:
import 'zone.js/dist/zone';  // Included with Angular CLI.
(window as any).global = window;
(window as any).process = {
  env: { DEBUG: undefined },
};

**Comment by Crisp3333** [comment] 2019-08-19 21:28
@fishermr thanks a lot! Problem solved.

**Comment by brandon-twitty** [comment] 2020-05-11 23:24
This is garbage two times I have followed this to the T https://docs.amplify.aws/start/q/integration/angular and it doesnt work . Ive tried every single one of these suggestions too.. This is Amazon this seems simple but apparently not my errors 

 node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:73:38 - error TS2304: Cannot find name 'Omit'.

73     function getJSType(scalar: keyof Omit<typeof GraphQLScalarType, 'getJSType'>): 'string' | 'number' | 'boolean';
                                        ~~~~
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:83:69 - error TS2304: Cannot find name 'Omit'.

83 export declare function isGraphQLScalarType(obj: any): obj is keyof Omit<typeof GraphQLScalarType, 'getJSType'>;
                                                                       ~~~~
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:98:17 - error TS2304: Cannot find name 'Omit'.

98     type: keyof Omit<typeof GraphQLScalarType, 'getJSType'> | ModelFieldType | NonModelFieldType | EnumFieldType;
                   ~~~~
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:115:36 - error TS2304: Cannot find name 'Omit'.

115 export declare type ModelInit<T> = Omit<T, 'id'>;
                                       ~~~~
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:119:39 - error TS2304: Cannot find name 'Omit'.

119 export declare type MutableModel<T> = Omit<DeepWritable<T>, 'id'>;

I dont understand this has been a lot of time wasted

**Comment by snieves-mh** [comment] 2021-02-11 02:07
> This is garbage two times I have followed this to the T https://docs.amplify.aws/start/q/integration/angular and it doesnt work . Ive tried every single one of these suggestions too.. This is Amazon this seems simple but apparently not, my errors:
> 
> node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:73:38 - error TS2304: Cannot find name 'Omit'.
> 
> 73 function getJSType(scalar: keyof Omit<typeof GraphQLScalarType, 'getJSType'>): 'string' | 'number' | 'boolean';
> ~~~~
> node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:83:69 - error TS2304: Cannot find name 'Omit'.
> 
> 83 export declare function isGraphQLScalarType(obj: any): obj is keyof Omit<typeof GraphQLScalarType, 'getJSType'>;
> ~~~~
> node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:98:17 - error TS2304: Cannot find name 'Omit'.
> 
> 98 type: keyof Omit<typeof GraphQLScalarType, 'getJSType'> | ModelFieldType | NonModelFieldType | EnumFieldType;
> ~~~~
> node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:115:36 - error TS2304: Cannot find name 'Omit'.
> 
> 115 export declare type ModelInit = Omit<T, 'id'>;
> ~~~~
> node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:119:39 - error TS2304: Cannot find name 'Omit'.
> 
> 119 export declare type MutableModel = Omit<DeepWritable, 'id'>;
> 
> I dont understand this has been a lot of time wasted about ot just go back to spring security

Did you ever figure out which way to go? Just tried this myself and getting the exact same errors you are. What did you end up doing?

**Comment by angusho1** [comment] 2021-05-07 16:45
> Did you ever figure out which way to go? Just tried this myself and getting the exact same errors you are. What did you end up doing?

@snieves-mh Can I ask you the same question? Where you able to figure this out?
