### ISSUE TITLE
Can't use "code" as a query parameter

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3494] opened 2019-06-20 04:05 UTC
Using the query parameter name "code" causes "invalid_grant" error due to the Amplify listener attempting to validate the parameter as an OAuth code. Might make sense to namespace the code parameter to "awscode" or even validate that the code value looks like an OAuth response code before throwing an error.... took a few hours to debug this.

**Comment by jessedoyle** [comment] 2019-06-26 15:29
I can absolutely second this - Amplify completely highjacks the `code` parameter if present via form post or URL queries. 

This caught us off guard a while back and required significant troubleshooting as the error message is vague and seems unrelated.

**Comment by jaimeburnap-fts** [comment] 2020-02-17 19:39
Any updates on this?

**Comment by danielblignaut** [comment] 2020-03-10 16:09
+1

**Comment by jonmifsud** [comment] 2020-06-08 12:25
Does anyone have a workaround? We need to use some oAuth 2.0 third party verification and this really messes up the experience :(

**Comment by clethrill** [comment] 2020-10-06 03:25
This is extremely irritating, implementing third party oAuth2 integration and when it redirects back to my site it errors out assuming it's the SSO code

**Comment by sw-yx** [comment] 2020-10-06 07:49
@clethrill good suggestion and I think we should take a PR for this. deep sympathies for the frustration caused.

**Comment by clethrill** [comment] 2020-10-08 23:38
I created a PR #6939 to try and help speed things along.

**Comment by SandonAhoy** [comment] 2021-02-02 06:31
Pr doesn't look like it's fixed the issue, I also get the issue using the query string 'error' as well as the original issue with 'code' if I go anywhere on my site like `mysite.com/path/to/somewhere?error` aws-amplify will log me out with a console message saying I've had an OAuth error. This seems like a pretty major issue, I don't know how no one else has run into this? Surely someone using aws-amplify has at some point tried to put ?error into their website?

**Comment by harryrein3** [comment] 2021-02-18 16:23
I saw this specifically with the Instagram Basic Display API where they attempt to use the code parameter and amplify steals it and throws an invalid user pool error. I can catch it beforehand and change the URL to use insta_code instead of code, but that requires another page load. Could we just allow this URL param to be configured?

**Comment by DevNM21** [comment] 2021-05-23 07:37
A workaround for this would to be add rewrites in your amplify's settings.
Something like this perhaps: 
![Screenshot_2021-05-23_12-34-42](https://user-images.githubusercontent.com/46824652/119252069-c1d85b80-bbc7-11eb-8a2d-1189b4de6ec9.png)
Mine was next.js application and it worked fine.

**Comment by AG-Labs** [comment] 2022-01-11 15:37
I have had a look through the code and it seems like the change made in https://github.com/aws-amplify/amplify-js/pull/7306 was the right check but it happened too low down the chain of calls.
would making a change here solve the issue? 
https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L2053

could be changed to
```
if ((hasCodeOrError || hasTokenOrError) &&
	(this._config.oauth as AwsCognitoOAuthOpts).redirectSignIn !==
	parse(currentUrl).pathname ) {
```

**Comment by tills13** [comment] 2022-04-27 16:02
If anyone is still waiting for the fix for this to land, I have a solution in the interim. This works for tools and hosting platforms that allow multiple HTML entrypoints. In my case, I'm using Vite + CloudFlare pages. I will add some tool-specific code here... be warned 😆 

Create another html entrypoint in your app. I chose `oauth_callback.html`. The contents of this file are 

```html
<html>
    <head>
        <script>
            const queryParams = new URLSearchParams(location.search);
            // I handle my oauth at http://example.com/oauth/callback
            const realOAuthCallbackUrl =
                window.location.protocol +
                "//" +
                window.location.host +
                "/" +
                "oauth/callback";

            // capture the code and state from the URL
            const code = queryParams.get("code");
            const state = queryParams.get("state");

            // make a URLSearchParams for formatting convenience
            // renaming code and state in the process
            const newParams = new URLSearchParams({
                // code becomes oauth_code
                oauth_code: code,
                // state become oauth_state
                oauth_state: state,
            });

            // redirect to your actual callback 
            window.location = realOAuthCallbackUrl + "?" + newParams.toString();
        </script>
    </head>
</html>
```

In GCP, I've added `https://example.com/oauth_callback.html` as an allowed callback and I use this as the `redirect_uri` in the original request to the federation endpoint.

Remember to read these values from their mapped params not the old params. 

For Vite, I added this page to the build (+ dev server) by adding the following to my `vite.config.ts`

```js
export default defineConfig({
    build: {
        rollupOptions: {
            input: {
                main: path.resolve(__dirname, "index.html"),
                oauth_callback: path.resolve(__dirname, "oauth_callback.html"),
            },
        },
    },
});
```

**Comment by tannerabread** [comment] 2022-10-21 20:36
Closing this as a duplicate of #10415. We will be tracking the progress on the more recent issue

**Closed by tannerabread** 2022-10-21 20:36 UTC
Labels: good first issue, feature-request, Auth, Cognito

**Comment by tannerabread** [comment] 2022-12-09 15:42
Update: there were 2 duplicates, tracking progress on #9208 as it has the most context and attached PRs
