### ISSUE TITLE
Bug: AWSCloudWatchProvider sending duplicate events with slower networks

### ISSUE THREAD

**Issue by dapriett** [aws-amplify/amplify-js#10172] opened 2022-08-08 19:02 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

REST API, Not applicable

### Amplify Categories

Not applicable

### Environment information

N/A

### Describe the bug

Hello,

There appears to be a bug in the `AWSCloudWatchProvider`, I believe somewhere in the `_initiateLogPushInterval` and `_safeUploadLogEvents` logic, and the cloudwatch log network calls are not responding fast enough (i.e. other resources in browser loading, or behind a slow proxy, etc..).  Anyways what seems to happen is the timer interval will start sending the same events multiple times, and then gets in a constant loop of exceptions due to using the same sequence token: 

`failure during log push: DataAlreadyAcceptedException: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: xxxxxxxxxxxxxxxxxxx`

The first call does go through though.

### Expected behavior

To not resend the same log events unless failure

### Reproduction steps

1. Add a really log delay to `_getNextSequenceToken` to simulate slow calls to create log groups, stream, get token, etc...
2. immediately log an event

### Code Snippet

```javascript
// Simulate slow call validating group exists 
const origValGroup =
  AWSCloudWatchProvider.prototype['_validateLogGroupExistsAndCreate'];
AWSCloudWatchProvider.prototype['_validateLogGroupExistsAndCreate'] =
  async function () {
    const result = await origValGroup.apply(this, arguments);
    await new Promise((resolve) => setTimeout(resolve, 5000));
    return result;
  };

const logger = new Logger('test', 'INFO');
Amplify.register(logger);
const cwProvider = new AWSCloudWatchProvider({
  region: 'us-east-1',
  logGroupName: 'test-group',
  logStreamName: 'test-stream',
});
logger.addPluggable(cwProvider);

logger.error('This will cause multiple log events and DataAlreadyAcceptedException');

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by abdallahshaban557** [comment] 2022-08-08 21:59
Closing this issue as a duplicate of #9575

**Closed by abdallahshaban557** 2022-08-08 21:59 UTC
