### ISSUE TITLE
Transcribe Streaming (Predictions) Support for React Native

### ISSUE THREAD

**Issue by stavros-zavrakas** [aws-amplify/amplify-js#4163] opened 2019-10-10 13:28 UTC
**Is your feature request related to a problem? Please describe.**
The documentation for Predictions that is under the React Native section they are not for React Native but just for ReactJS. Specifically, AWS Transcribe and streaming by using React Native and Expo are not documented at all. The documentation specifies that you have to provide bytes which are the bytes that you collect from the microphone. The problem is that is not specified what exactly type are these bytes. By doing an implementation on the browser it seems that the bytes array is an array which consists of Float32Array and this is what I've tried to reproduce on React Native.

**Describe the solution you'd like**
Ideally, I'd like the documentation to be a bit more descriptive. Does it even work for React Native? This is something that I've tried on React Native after playing doing multiple tries and failing with every try I've done. The application is able to establish a connection through a WebSocket. I'm able to load a static file and convert it either to blob/base64/Uint8Array/Float32Array with all those failing. This is my implementation up till now:

```
import React, { useEffect, useState } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import { Asset } from 'expo-asset';
import { Predictions } from 'aws-amplify';
import AudioAsset from 'assets/audio/speech.mp3';
import { ConfirmSignUp } from 'aws-amplify-react-native';
import base64Arraybuffer from 'base64-arraybuffer';

global.Buffer = global.Buffer || require('buffer').Buffer

// @see:
// https://github.com/aws-amplify/amplify-js/issues/3958
async function fileToRNArrayBuffer(uri) {
return new Promise((res, reject) => {
    var request = new XMLHttpRequest();
    request.open("GET", uri, true);
    request.responseType = 'arraybuffer';
    request.onload = _event => { res(request.response) }      
    request.onerror = err => { reject(err); };
    request.send(null);
});
}

// @see:
// https://stackoverflow.com/questions/34669537/javascript-uint8array-to-float32array
function convertBlock(buffer) { // incoming data is an ArrayBuffer
    var incomingData = new Uint8Array(buffer); // create a uint8 view on the ArrayBuffer
    var i, l = incomingData.length; // length, we need this for the loop
    var outputData = new Float32Array(incomingData.length); // create the Float32Array for output
    for (i = 0; i < l; i++) {
        outputData[i] = (incomingData[i] - 128) / 128.0; // convert audio to float
    }
    return outputData; // return the Float32Array
}

const Voice = () => {
    const audioFile = Asset.fromModule(AudioAsset)

    const [soundError, setSoundError] = useState(false);

    const sendSoundObject = async () => {
       // Convert the file to an arrayBuffer
        const arrayBuffer = await fileToRNArrayBuffer(audioFile.uri);
       // Convert arrayBuffer to byte blocks
        const bytes = convertBlock(arrayBuffer);

        Predictions.convert({
            transcription: {
                source: {
                    bytes
                }
            }
        })
        .then(result => console.log(JSON.stringify(result, null, 2)))
        .catch(err => console.log(JSON.stringify(err, null, 2)));

        // const response = await fetch(audioFile.uri);

        // const blob = await response.blob();

        // const reader = new FileReader();

        // reader.readAsDataURL(blob);
        
        // reader.onloadend = () => {
        //     let base64 = reader.result;

        //     const arrayBuffer = base64Arraybuffer.decode(base64);

        //     const bytes = Buffer.from(arrayBuffer);
            
        //     Predictions.convert({
        //         transcription: {
        //             source: {
        //                 bytes: arrayBuffer
        //             }
        //         }
        //     })
        //     .then(result => console.log(JSON.stringify(result, null, 2)))
        //     .catch(err => console.log(JSON.stringify(err, null, 2)))
        // };
    };

    useEffect(() => {
        sendSoundObject();
    }, []);

    if (soundError) {
        return <Text>Error loading Sounds</Text>;
    }

    return (
        <View style={styles.container}>
            <Text style={styles.text}>SOUNDS</Text>
        </View>
    )
}

const styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1
    },
    text: {
        fontSize: 24,
        fontWeight: '100',
        textTransform: 'uppercase',
        letterSpacing: 12,
        padding: 32
    },
});

export default Voice;
```
I've checked the `AmazonAIConvertPredictionsProvider convertSpeechToText` function and I've tried to understand if something can/need to be modified in ther. Sometimes I had to modify the iteration in the `sendDataToTranscribe` function because it wouldn't always succeed the `Array.isArray` condition. The communication is successful but I always get back empty results from transcoder.

What I've realised is that the send function of WebSocket's implementation for react native is converting the ArrayBuffer to base64. Is it finally just a restriction of the WebSocket implementation for react native which is not able to stream binary data?

These are the dependencies I'm using:
```
"aws-amplify": "1.1.40"
"aws-amplify-react-native": "2.1.19"
"base64-arraybuffer": "0.2.0"
"buffer": "5.4.3"
"expo": "^33.0.0"
```

**Comment by jabirbarber-elder** [comment] 2019-12-21 11:07
Any updates on this? Were you able to get it to work with static audio files?

**Comment by RandallStanhope** [comment] 2020-07-20 20:40
Were you ever able to get this working? Does live streaming audio to Transcribe even work for React Native?

**Comment by nadetastic** [comment] 2022-10-21 17:18
This is a duplicate of #4046. Will close this and track this feature request on #4046

**Closed by nadetastic** 2022-10-21 17:18 UTC
Labels: feature-request, documentation, React Native, Predictions

**Comment by ashirkhan94** [comment] 2023-05-23 11:09
Hi Any Update?
