### ISSUE TITLE
ES6 arrow function syntax breaking Internet Explorer 11 (IE11)

### ISSUE THREAD

**Issue by sawyerh** [aws-amplify/amplify-js#5582] opened 2020-04-27 17:43 UTC
**Describe the bug**

Amplify does not work in Internet Explorer 11. It's possible this was broken by a dependency like `@aws-sdk`. It's unclear how to restore IE11 support to an application implementing Amplify.

**To Reproduce**

Repro available here: https://github.com/sawyerh/amplify-nextjs-ssr

**Expected behavior**
It's unclear what the official browser support is for Amplify, however the Amplify SDK previously worked in IE 11, and according to [this comment](https://github.com/aws-amplify/amplify-js/issues/1195#issuecomment-502847380) AWS is still supporting IE11. 

**Screenshots**
![image](https://user-images.githubusercontent.com/371943/80402763-6769b000-888c-11ea-9e0b-160bca41e905.png)

**What is Configured?**

```
"dependencies": {
    "aws-amplify": "3.0.9",
    "aws-amplify-react": "4.1.8",
    "next": "9.3.5",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
```

**Comment by Amplifiyer** [comment] 2020-04-28 00:47
Same as https://github.com/aws-amplify/amplify-js/issues/5405
The issue is with an upgrade of underlying aws-sdk that is exporting the package with ES2016 syntax https://github.com/aws/aws-sdk-js-v3/blob/v1.0.0-beta.5/packages/middleware-serde/tsconfig.json#L3 and there is an open issue related to this https://github.com/aws/aws-sdk-js-v3/issues/1099

**Comment by ericclemmons** [comment] 2020-05-01 16:27
Awaiting a version bump for https://www.npmjs.com/package/@aws-sdk/eventstream-serde-browser

**Comment by slavco86** [comment] 2020-05-10 12:45
Having same issue.
@ericclemmons 
How long till the version bump?

**Comment by jonasduever** [comment] 2020-05-26 11:36
Still an issue, I think. :/

```
  "dependencies": {
    ...
    "aws-amplify": "~3.0.12",
    "aws-amplify-angular": "~5.0.12",
    ...
  }
```

![image](https://user-images.githubusercontent.com/5775325/82896209-d999e700-9f55-11ea-9e15-1ec6f1c84e2d.png)

**Comment by Amplifiyer** [comment] 2020-05-27 18:03
it seems there is one more package that got missed which targets ES2016 output https://github.com/aws/aws-sdk-js-v3/blob/v1.0.0-gamma.2/packages/middleware-serde/tsconfig.json#L3
I'll create an issue with aws-sdk to get this prioritized.

**Comment by jonasduever** [comment] 2020-06-07 20:12
https://github.com/aws/aws-sdk-js-v3/pull/1245 has been merged - looks like this problem will be solved soon 👍

**Comment by simmbiote** [comment] 2020-06-23 15:08
I bumped aws-amplify version up to 3.0.18, but still getting the same error.

![image](https://user-images.githubusercontent.com/11704483/85420676-cfc6cc00-b573-11ea-9dcc-74006e702c4d.png)

I've also tried a variety of polyfills:
```
import "babel-polyfill"; 
import "promise-polyfill";
import "core-js/es/typed-array/uint32-array";
import "core-js/es/array/find";
import "core-js/es/object/assign";
import "core-js/es/object/entries";
```

Still not working. Any help would be appreciated!

**Comment by KwFung7** [comment] 2020-07-09 06:07
https://github.com/aws/aws-sdk-js-v3/issues/1319
The issue should be fixed in latest aws sdk v1.0.0-gamma.3 release (https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.3

**Comment by simmbiote** [comment] 2020-07-16 15:09
I ended up removing this package and using a different solution for logging in AWS Cognito users 
- Amazon Cognito Auth (https://www.npmjs.com/package/amazon-cognito-auth-js)
It works in IE 11.

**Comment by wataruoguchi** [comment] 2020-07-20 21:47
"Amazon Cognito Auth" ^ is already archived. The module doesn't support PKCE, so I'd stick with amplify-js.

As it's mentioned, the latest aws sdk v1.0.0-gamma.3 release has the bugfix. It is now tagged to [gamma](https://www.npmjs.com/package/@aws-sdk/middleware-serde). I resolved this issue by installing `@aws-sdk/middleware-serde@gamma`.

**Comment by sammartinez** [comment] 2020-08-06 17:18
Resolving as this issue is in our latest release, 3.0.22

**Closed by sammartinez** 2020-08-06 17:18 UTC
Labels: aws-sdk-js, bug

**Comment by wataruoguchi** [comment] 2020-08-06 18:02
Awesome! Thank you!
