### ISSUE TITLE
AuthError - Error: Amplify has not been configured correctly. (aws-amplify 3.4.0, auth 3.4.31, ui-react 1.1.0)

### ISSUE THREAD

**Issue by rickygalliani** [aws-amplify/amplify-js#8258] opened 2021-05-11 16:10 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dj8d92h79lafk

### Region

us-west-2

### Amplify Console feature

Not applicable

### Describe the bug

I'm seeing this `AuthError` error which has been reported several times before but none of the recommended solutions in those tickets have worked for me yet. I'm under the impression that some of the dependencies specified in my `package.json` file are incompatible with each other but I haven't been able to get it sorted.

Here's the console error:

```
AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
```

Here's my `package.json` file: 

```
{
  "name": "dummyappname",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/auth": "^3.4.31",
    "@aws-amplify/ui-react": "^1.1.0",
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "aws-amplify": "^3.4.0",
    "aws-sdk": "^2.903.0",
    "bootstrap": "^3.4.1",
    "node-sass": "^5.0.0",
    "react": "^17.0.2",
    "react-bootstrap": "^1.5.2",
    "react-bootstrap-validation": "^0.1.11",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-vis": "^1.11.7",
    "web-vitals": "^1.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

And here's the app entry point code: 

```
import Amplify, { Auth } from 'aws-amplify';
import awsmobile from './aws-exports';
import './App.css';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom'
import React from "react";
import { withAuthenticator } from '@aws-amplify/ui-react';

function App() {

    Amplify.configure(awsmobile);
    Auth.configure(awsmobile);

    return (
        <Router>
            <Switch>
                <div className="app">

                    <Route exact path={["/", "/home"]}>
                        <div>Hello, World</div>
                    </Route>

                </div>
            </Switch>
        </Router>
    )
}

export default withAuthenticator(App);
```

### Expected behavior

The basic authentication functionality as described in this tutorial: https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#enable-sign-up-sign-in-and-sign-out

### Reproduction steps

1. Use the package.json
2. Run the app entry code

**Comment by rickygalliani** [comment] 2021-05-11 19:45
> Hi 👋, thanks for raising. I'm going to transfer to the Amplify JS repo to get some more eyes on it.
> 
> In the meantime, do you mind checking if this solution helps - [#7619 (comment)](https://github.com/aws-amplify/amplify-js/issues/7619#issuecomment-767710379)?





Thanks for the response. 

I see this error when I remove the module level `dependencies` in `package.json`. 

```
./src/App.js
Module not found: Can't resolve '@aws-amplify/ui-react'
```

This is what I tested:

```
  "dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "aws-amplify": "^3.4.0",
    "aws-sdk": "^2.903.0",
    "bootstrap": "^3.4.1",
    "node-sass": "^5.0.0",
    "react": "^17.0.2",
    "react-bootstrap": "^1.5.2",
    "react-bootstrap-validation": "^0.1.11",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-vis": "^1.11.7",
    "web-vitals": "^1.1.2"
  },
```

**Comment by rickygalliani** [comment] 2021-05-11 19:54
> Looks like you're using aws-exports to configure both Amplify and Auth (both of which are being imported from aws-amplify). I think you'd only need to call `Amplify.configure` and it should set up your Auth correctly as well. Also, you have `@aws-amplify/auth` but you're not importing Auth from there so you can probably remove that dependency.

Got it. I tried removing the `@aws-amplify/auth` from `package.json` dependency and the `Auth.configure()` call in the app code but still see the same error

**Comment by apoorvmote** [comment] 2021-05-12 10:14
Should I open another issue? Because I am also have same exact error.

Before `package.json` Here everything is working
```json
{
  "dependencies":  {
    "@aws-amplify/api": "^3.3.0",
    "@aws-amplify/auth": "^3.4.31",
    "@aws-amplify/core": "^3.8.23",
  }
}
```
After update `package.json` Here I get error `Amplify has not been configured correctly`
```json
{
  "dependencies":  {
    "@aws-amplify/api": "^3.3.1",
    "@aws-amplify/auth": "^3.4.32",
    "@aws-amplify/core": "^4.0.0",
  }
}
```
There is literally no other difference. So in meantime I have pinned down version by removing `^` prefix until you fix the problem.

**Comment by myfairshare** [comment] 2021-05-12 10:44
This has stopped me in my trax as well.  Have not had any Auth issues at all until this week, now I'm getting this error saying Auth not configured.  I updated to latest Amplify package, I notice in my @aws-amplify folder in node packages there is no Auth???  I notice there is no Cache either.  Should I roll back to a previous version?  I have configured as below from day 1 with no issues..

```
import Amplify from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)
```

**Comment by apoorvmote** [comment] 2021-05-12 10:47
> Should I roll back to a previous version? 

Yes see if you get error with older version. If not then its issue with new update.

**Comment by myfairshare** [comment] 2021-05-12 11:07
> > Should I roll back to a previous version?
> 
> Yes see if you get error with older version. If not then its issue with new update.

Thanks mate, I have rolled back to 3.3.27 and my problem is resolved.  This version also seems to have all the core packages as expected, in the latest version 4.0.0 I was missing Auth, Cache and one or two others.

**Comment by houmark** [comment] 2021-05-12 23:13
We are also seeing an Auth error with the most recent versions of the libraries, so something broke in this minor release.

Specifically compiling with following error:

```
./node_modules/@aws-amplify/api/lib-esm/API.js
Module not found: Can't resolve '@aws-amplify/core' in '/Site/folder/node_modules/@aws-amplify/api/lib-esm'
```

We were on: 
`"aws-amplify": "^3.4.0"`, `"@aws-amplify/api-graphql": "^1.3.0"`, `"@aws-amplify/api-rest": "^1.2.31"`

And upgraded to:
`"aws-amplify": "^4.0.0"`, `"@aws-amplify/api-graphql": "^1.3.1"`, `"@aws-amplify/api-rest": "^1.2.32"`

**Comment by healthpraxone** [comment] 2021-05-13 13:15
Same error when I upgrade to latest aws-amplify 4.0.0
./node_modules/@aws-amplify/api/lib-esm/API.js Module not found: Can't resolve '@aws-amplify/core' in 'node_modules/@aws-amplify/api/lib-esm'

**Comment by davidrekow** [comment] 2021-05-14 19:22
Seeing the same console error as in the original report after micro update from `@aws-amplify/auth` `3.4.31` to `3.4.32`. That changeset updates the version of `@aws-amplify/core` required by the auth module to latest `4.0.0`, which when installed seems to override the version of `@aws-amplify/core` my project uses (`3.8.23`).

Auth configuration code that is by-the-docs and has been working for months just stopped working with a micro update...not sure that qualifies as micro.

**Comment by houmark** [comment] 2021-05-14 19:46
At best this is SemVer violations. But more likely it's broken code or missing documentation on changes. And AWS devs are silent :/

**Comment by chrisbonifacio** [comment] 2021-05-19 21:09
Sorry for the delay. We are currently looking into this and have not yet identified what the cause of the issue is. 

In the meantime, I would just like to ask that if you are experiencing this error and you are using scoped packages and configuring them separately, please try using `aws-amplify` on its own and configure your categories from within `Amplify.configure` in the meantime. You should still be able to tree-shake any other amplify dependencies that aren't being used.

Let me know if that helps with the Auth issue while we continue to work on fixing this.

**Comment by houmark** [comment] 2021-05-19 21:18
I am confused. We are using the aws-amplify package and scoped packages. The reason for this is that aws-amplify has features that are needed but you also introduced `@aws-amplify` where the rest and graphql client is scoped and used by us. 

The reason for this is that the aws-amplify packages (for some weird unknown to us reason) does not have cancelations on either rest or graphql, so to use that feature we are forced to pick packages like this. This is non-documented also, and aws-amplify silently swallows any attempt to cancel without throwing an error so it actually took us close to a year to realize this.

AWS, you have some really funky mono repos and a lack of documentation of how things are changing. It's almost impossible for anyone to keep up with how things should be used correctly.

See #5753 and specifically https://github.com/aws-amplify/amplify-js/pull/5753#issuecomment-633728124

**Comment by chrisbonifacio** [comment] 2021-05-19 21:40
You should not be using both `aws-amplify` and scoped packages (unless they're for UI components). The scoped packages (other than UI) are already included in and can be imported from `aws-amplify`. This kind of issue is usually resolved by sticking to either scoped `@aws-amplify` packages or `aws-amplify`, because Amplify is designed as a singleton, meaning there should only be one instance.

**Comment by houmark** [comment] 2021-05-19 21:46
Yeah, well that didn't work. It's been some time since we played with this, but using one package didn't work and splitting it up was the only option if we wanted to use cancellations. I know that is hard to understand and shows little evidence on the issues we encountered, but can you start out by explaining me what is the difference on the `@aws-amplify` package and `aws-amplify` package? 

I can tell you that if you try to use the cancellation feature implemented in #5753 with aws-amplify by using the included rest and graphql libraries, then cancellation does not work.

It should be trivial to replicate for your team.

**Comment by chrisbonifacio** [comment] 2021-05-19 22:03
@houmark I understand what you're saying but that's not the issue I'm trying to help fix here. If you're having issues with REST/GraphQL cancellations, please open another issue so that we can track that issue separately and prevent distraction from the original issue regarding Auth configuration.

What I've commented earlier is to help those who are experiencing the AuthError - "Amplify has not been configured correctly" which is more than likely caused by a known issue with combining scoped and non-scoped packages. We are recommending using only `aws-amplify` to avoid this issue.

**Comment by houmark** [comment] 2021-05-19 23:53
I understand and I will open another issue, but your recommendation of not using multiple libraries is not a solution because it will break rest and graphql cancellation and potentially several other things that are different between those two almost same-named libraries. I'll await feedback, like the rest, on the original issue.

**Comment by wlee221** [comment] 2021-05-20 01:12
I agree with @chrisbonifacio that you should use the global `aws-amplify` package instead of installing each modular packages. If there's issue where global `aws-amplify` doesn't work but modular packages do, that's a new issue that we will look at. 

That being said, having modular packages should still work, as long as the versions are matching. It's just a little bit more harder to maintain semantic versioning across them. So for this issue, let's focus on getting that Auth error resolved, with modular packages or not. I installed the following packages but could not reproduce the error:

```
"dependencies": {
  "@aws-amplify/api-graphql": "^2.0.0",
  "@aws-amplify/api-rest": "^2.0.0",
  "aws-amplify": "^4.0.2"
}
``` 

I had no duplicated packages after running `yarn install` or `npm i`. Note that `api-graphql` and `api-rest` have been recently major bumped in https://github.com/aws-amplify/amplify-js/commit/f3c5a14a9ad6855e4bc99fbf363e71bcca993bf0, so maybe this will help package managers disambiguate the packages.

**Comment by wlee221** [comment] 2021-05-20 01:16
Though you probably tried this, it's possible that the lock files are interfering with the version matching. Can you try a fresh install with these [upgrade commands](https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js#upgrade-amplify-packages) and see the error still exists. Make sure the versions are pointing to the latest major versions (aws-amplify@4.0.2, @aws-amplify/auth@4.0.0, @aws-amplify/api-graphql@2.0.0`, etc).

If the error persists, we would need more info to investigate. Please send us a minimal reproducible repo with `package.json`. Since the issue seems to be duplication issue, this shouldn't be very big -- just doing `Auth.signIn` would be enough to trigger Auth error.

**Comment by apoorvmote** [comment] 2021-05-20 12:04
After all this chatter I tried it and now it seems to be resolved. Also this new update v4 has increased at least 100Kb of extra javascript than v3 version. Here are my dependancies.

```json
{
  "dependencies": {
    "@aws-amplify/api": "^4.0.0",
    "@aws-amplify/auth": "^4.0.0",
    "@aws-amplify/core": "^4.0.2",
}
```

My mistake was I only had core on v4 and others were on v3 so it was not working. Now I got all of them to v4 and now they are working.

**Comment by chrisbonifacio** [comment] 2021-05-20 17:24
@rickygalliani could you try @apoorvmote's fix (making sure your versions match) or @wlee221's suggestions and let us know if either of these resolves the issue for you?

**Comment by johandui** [comment] 2021-05-24 07:47
Hello there I currently use only aws-amplify.  Running Create React App in development mode, I worked fine, but after exporting it and running that in a webserver, I got the No Auth module registered in Amplify error. I also tried last versions but still got this issue.
` "aws-amplify": "^3.3.27",`

**Comment by apoorvmote** [comment] 2021-05-31 03:07
Just FYI I am getting weird error that my graphql api variable `date` is null. The interesting part is this only happens in my US and Canada customers. I have tested with my UK, UAE and India customers and same exact code is working perfectly. I bet it has something to do with this auth error that everyone else is having. 

I will create seprate issue for my problem. I just wanted to let everyone know that its not 100% resolved for me either.

**Comment by chrisbonifacio** [comment] 2021-06-02 17:26
Going to close this for now as we have not heard back from the original poster in nearly two weeks and some folks have been able to fix it/find a workaround. If you're still experiencing this issue or something similar, please open a separate issue and provide us the details of your environment so we can better identify the cause and find a solution for you.

**Closed by chrisbonifacio** 2021-06-02 17:26 UTC
Labels: Auth
