### ISSUE TITLE
AWSPinpointProvider - Initial endpoint update failed.

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#4838] opened 2020-02-04 10:39 UTC
**Describe the bug**
*Sometimes* when the app starts I get an error saying that the initial endpoint update for AWSPinpoint failed. the screen says AWSPinpointProvider - Initial endpoint update failed. But there is console.warn in the console saying that the endpoint update failed after 5 retries

**Expected behavior**
If there are already 10 endpoint choose one that is not used and delete it. If all are used then log a clear error that says something like `there are already 10 endpoints in use, please remove one`. I don't know how I got to 10 endpoints when I only use the application from 2 devices (the simulator and my own phone).

**Screenshots**
![image](https://user-images.githubusercontent.com/28350511/73736953-5d7f5780-474a-11ea-9ea5-ef9cab72cea6.png)

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 947.68 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.5
  npmPackages:
    @aws-amplify/analytics: ^2.2.2 => 2.2.2
    @aws-amplify/pushnotification: ^2.1.3 => 2.1.3
    aws-amplify: ^2.2.2 => 2.2.2
```

**Smartphone (please complete the following information):**

- Device: [e.g. All devices]
- OS: [e.g. All]

**Additional context**
I think the reason this happens is because there are already 10 endpoints for the specific users and if I'm not wrong the maximum for a user is 10.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**
```
 LOG  [DEBUG] 29:39.390 AWSPinpointProvider - updateEndpoint failed [BadRequestException: Exceeded maximum endpoint per user count: 10]
LOG  [DEBUG] 29:39.502 AWSPinpointProvider - get endpoints associated with the userId
```
(here is lists all my endpoints)
```
 LOG  [DEBUG] 29:39.627 AWSPinpointProvider - The old endpoint is updated with an empty string for user id
 LOG  [DEBUG] 29:39.628 AWSPinpointProvider - Removed unused endpoints successfully
 LOG  [DEBUG] 29:39.628 AWSPinpointProvider - _retryEndpointUpdate {"handlers": {"reject": [Function anonymous], "resolve": [Function anonymous]}, "params": {"config": {"appId": "xxxx", "bufferSize": 1000, "credentials": [Object], "disabled": undefined, "endpointId": "xxxx", "flushInterval": 5000, "flushSize": 100, "region": "eu-central-1", "resendLimit": 5}, "event": {"eventId": "xxxx", "immediate": true, "name": "_update_endpoint", "session": [Object]}, "provider": undefined, "timestamp": 1580812178975}}
 WARN  [WARN] 29:39.629 AWSPinpointProvider - resending endpoint update xxxx failed after 5 attempts

```

**Comment by ashika01** [comment] 2020-02-04 17:25
There is already an issue open for this and we are investigating on this. #4815

**Comment by ashika01** [comment] 2020-02-04 18:17
Closing this issue as Duplicate of #4815 . Please monitor updates on the issue mentioned. We are currently investigating this and will pool in this information to our investigastion. Thank you for reporting this.

**Closed by ashika01** 2020-02-04 18:17 UTC
Labels: to-be-reproduced
