### ISSUE TITLE
aws amplify Auth.SignIn() not working on production but works on local react native

### ISSUE THREAD

**Issue by dev1gestionhb** [aws-amplify/amplify-js#11401] opened 2023-05-23 15:01 UTC
JavaScript Framework : React native
Amplify APIs : Authentication
Amplify Categories: auth

Describe the bug
Auth.signIn() is not getting triggered on production : expo test (eas build --profile preview --platform android)  but works perfectly on local env. Contrariwise Auth.signUp() works perfectly and the user saved in dynamodb
all the packages up-to-date.

**Comment by cwomack** [comment] 2023-05-23 17:56
Hello, @dev1gestionhb 👋.  Are you able to clarify some details about your local environment such as Amplify version, dependencies, etc?  Also are you seeing any errors or exceptions being thrown when the `Auth.signIn()` method is called?

**Comment by dev1gestionhb** [comment] 2023-05-23 19:17
Hello @cwomack , thanks for ur answer , 
here :
    "aws-amplify": "^5.2.0",
and i have no errors on or exceptions

**Comment by cwomack** [comment] 2023-05-23 19:31
@dev1gestionhb, appreciate the quick reply! Since this issue was transferred from another repo, I don't think you had an opportunity to describe the reproduction steps.  Can you run through what the basic/minimum steps would be to reproduce this?  Can it just be reliably reproduced by simply calling the `Auth.signIn()` method on the production app side?

**Comment by cwomack** [comment] 2023-05-23 19:43
@dev1gestionhb, can you also confirm if you're just using the default AsyncStorage or if you've implemented a customer storage solution?

**Comment by dev1gestionhb** [comment] 2023-05-23 19:45
yes AsyncStorage  , when running expo start and working fine .. but the problem only when deploy to expo ..

**Comment by dev1gestionhb** [comment] 2023-05-23 20:06
no i dont use scoped package
i have AmplifyService : 
  SignIn =async (username: string, password: string) => {
        return await Auth.signIn({ username, password });
    };

 SignUpUser = async (username: string, password: string,email:string,name:string) => {
        return await Auth.signUp({ username, password, attributes: { email, name } });
    };
and in the component i call 
    const [isUserAuthenticated, setIsUserAuthenticated] = useState<boolean>(false);
    useEffect(() => {
        SignUpUser();
    }, []);
    const SignUpUser = () => {

 await AmplifyService.SignIn("test", "password0")
.then(() => {
                    setIsUserAuthenticated(true);
                })
                .catch((err) => {
// if user not found in dynamoDB
                    AmplifyService.SignUpUser("test", "password0","email@xx.xx","test").then(() => {
                        AmplifyService.SignIn(username, password).then(() => {
                            setIsUserAuthenticated(true);
                        });
                    });
                });
 };

**Comment by cwomack** [comment] 2023-05-23 21:46
@dev1gestionhb, thanks for all the information.  We've been able to reproduce the issue on our side as well when running a production build with EAS.  Did you follow the [React Native tutorial](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/) from our docs by chance when you created your app?

**Comment by cwomack** [comment] 2023-05-25 22:02
Closing this issue now that the PR updating the docs is merged.

**Closed by cwomack** 2023-05-25 22:02 UTC
Labels: documentation, Auth, amazon-cognito-identity-js
