### ISSUE TITLE
React-native Auth.federatedSignIn() redirection URL mismatch error

### ISSUE THREAD

**Issue by yelhow** [aws-amplify/amplify-js#4244] opened 2019-10-24 12:53 UTC
**Describe the bug**
I am following the link : 
https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui 
Section:  OAuth and Hosted UI 

Methods for facebook: 
<button onClick={() => Auth.federatedSignIn({provider: 'Facebook'})}>Open Facebook</button>

The sad state of amplify is there is no where in documentation it talked about redirection URI and everywhere it talked about using withAuthenticator HOC component. 

I end up spending days to solve small issues with Amplify.  It is just a request if someone from Amplify team look into the issue quickly and have documents up to date. There were many similar issues in the forum without resolution and they were closed.

One such reference is here: federated logins in react-native examples #3302

It would be very helpful if someone can tell what would be the exact redirection URL one should put while authenticating federated identities.

I always get this error: with redirectionURL set to: "com.dahersoftware.skillmgt://" (My app name)
https://<app and region>.amazoncognito.com/error?error=redirect_mismatch&client_id <my client id>

While doing Amplify.configure I override redirectionURL values and it never works. It works for my react app though.

**Comment by undefobj** [comment] 2019-10-24 16:16
> It would be very helpful if someone can tell what would be the exact redirection URL one should put while authenticating federated identities.


Are you trying to use Federated Identities instead of User Pools? If so then you'll need to use the overloaded method of `Auth.federatedSignin` with a token as outlined here: https://aws-amplify.github.io/docs/js/authentication#identity-pool-federation

**Comment by dahersoftware** [comment] 2019-10-25 05:34
@undefobj We are using Cognito User Pools.

**Comment by dahersoftware** [comment] 2019-10-26 07:14
@undefobj To add it more info.. We tapped the redirection request
https://<name-dev.auth.region>.amazoncognito.com/oauth2/authorize?redirect_uri=myapp://main/&response_type=code&client_id=<clientid>&identity_provider=Facebook&scopes=phone,email,openid,profile,aws.cognito.signin.user.admin&state=<state string>&code_challenge=kN4NRDBHGDcJ2m2PwoZgkhWdhypod1p7PG_5Nd3SFis&code_challenge_method=S256

Somehow redirection_uri is not right but where we should do it there is no help regarding that. 
As I said earlier we are using Cognito user pool and same user pool we are using for react app and everything works fine there.

**Comment by michalgarcarz** [comment] 2019-10-29 09:39
Have the same challenges as @dahersoftware.
For react it's easy to use Amplify to authenticate via Facebook/Google, for react native extremely challenging (and probably it never worked). Documentation: i do really appreciate had work all of you here, but still it's is a mess - takes a lot of time to even understand what is and what is not supported.

I use the following code:

`export default function App() {
  const [user, setUser] = useState('');
  const [isLoggedIn, setIsLoggedIn] = useState(false)

  useEffect(() => {
    Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
          setUser(data);
          setIsLoggedIn(true);
          console.log("User logged in: ", data);
          break;
        case "signOut":
          setUser('');
          setIsLoggedIn(false);
          console.log("User logged out: ", data);
          break;
        case "customOAuthState":
          setUser(data);
      }
    });
  }, []); //call Hub listen only on component mount & unmount

return (
    <React.Fragment>
    {isLoggedIn ? <Text>User logged in as {user.username}</Text>:
    <View style={styles.container2}>      
      <Button title="FacebookSignIn" onPress={() => { Auth.federatedSignIn({ provider: 'Facebook' }); }} />
      <Button title="GoogleSignIn" onPress={() => { Auth.federatedSignIn({ provider: 'Google' }); }} />
      <Button title="HostedUISignIn" onPress={() => { Auth.federatedSignIn(); }} />
      <Button title="SignOut" onPress={() => { Auth.SignOut(); }} />
    </View>
    }
    </React.Fragment>
   );
}`

in my aws-exports config:
`const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:de11aea1-6ca6-4f74-9953-97b0fxxxxx",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_lJxxxxx",
    "aws_user_pools_web_client_id": "xxxxx",
    "oauth": {
        "domain": "project3310eb456-310eb456-project.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};`


Now in apple IOS simulator i am redirected, authenticate with facebook and get redirected back to my app - but it somehow hangs after that, still troubleshooting.
In Android 10 simulator once i authenticate with facebook and get redirected i got error:

console.error: "[ERROR] 30:55.468 OAuth - Error handling auth response.", {"line":182049,"column":32,"sourceURL":"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false"}
__expoConsoleLog
    RemoteConsole.js:80:37

[ERROR] 30:55.468 OAuth - Error handling auth response., [Error: invalid_grant]
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- ... 16 more stack frames from framework internals

[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_a.accessToken')]
- node_modules/@aws-amplify/auth/lib-esm/Auth.js:1655:57 in <unknown>
- node_modules/@aws-amplify/auth/lib-esm/Auth.js:44:27 in step
- ... 12 more stack frames from framework internals

Would be great to have posted a simple react-native app using hooks with working facebook/google auth - it seems everybody is still struggling with it. Again: the documentation for react vs react native should be splitted IMHO.

Thanks,

**Comment by dahersoftware** [comment] 2019-10-30 14:01
@undefobj  Any update on this.

**Comment by michalgarcarz** [comment] 2019-10-30 18:23
just a side note, since this part of Amplify code seems to be broken (or i am unable to use it correctly) i have started to use expo:
```
Facebook.logInWithReadPermissionsAsync()
Google.logInAsync()
```
And after that i use Amplify:
```
Auth.federatedSignIn() with facebook token 
new AWS.CognitoIdentityCredentials with google token (i have multiple app id and need to use openconnect id with identity pools and that does not seem to be supported by Amplify)
```
Not everything yet works for me, but i have some progress, will post working code once i have it.

**Comment by dahersoftware** [comment] 2019-10-31 14:48
@michalgarcarz expo is okay but we don't use expo and as u said u still don't have working solution.
I am hoping someone put some helping hand here.

**Comment by dahersoftware** [comment] 2019-11-08 12:59
@undefobj is there any way I can receive quick help for this issue. My application deployment is blocked because of this.  Any workaround for now.

**Comment by ni3galave** [comment] 2019-11-11 13:22
> Have the same challenges as @dahersoftware. React native with hooks + expo + Amplify for Cognito user pools using federated auth with facebook/google. No need for Cognito federated identities.
> 
> For react it's easy to use Amplify to authenticate via Facebook/Google, for react native extremely challenging (and probably it never worked). Documentation: i do really appreciate hard work all of you here, but still it's is a mess - takes a lot of time to even understand what is and what is not supported.
> 
> I use the following code:
> 
> ```
> export default function App() {
>   const [user, setUser] = useState('');
>   const [isLoggedIn, setIsLoggedIn] = useState(false)
> 
>   useEffect(() => {
>     Hub.listen("auth", ({ payload: { event, data } }) => {
>       switch (event) {
>         case "signIn":
>           setUser(data);
>           setIsLoggedIn(true);
>           console.log("User logged in: ", data);
>           break;
>         case "signOut":
>           setUser('');
>           setIsLoggedIn(false);
>           console.log("User logged out: ", data);
>           break;
>         case "customOAuthState":
>           setUser(data);
>       }
>     });
>   }, []); //call Hub listen only on component mount & unmount
> 
> return (
>     <React.Fragment>
>     {isLoggedIn ? <Text>User logged in as {user.username}</Text>:
>     <View style={styles.container2}>      
>       <Button title="FacebookSignIn" onPress={() => { Auth.federatedSignIn({ provider: 'Facebook' }); }} />
>       <Button title="GoogleSignIn" onPress={() => { Auth.federatedSignIn({ provider: 'Google' }); }} />
>       <Button title="HostedUISignIn" onPress={() => { Auth.federatedSignIn(); }} />
>       <Button title="SignOut" onPress={() => { Auth.signOut(); }} />
>     </View>
>     }
>     </React.Fragment>
>    );
> }
> ```
> 
> in my aws-exports config:
> 
> ```
>     const awsmobile = {
>     "aws_project_region": "eu-central-1",
>     "aws_cognito_identity_pool_id": "eu-central-1:de11aea1-6ca6-4f74-9953-97b0fxxxxx",
>     "aws_cognito_region": "eu-central-1",
>     "aws_user_pools_id": "eu-central-1_lJxxxxx",
>     "aws_user_pools_web_client_id": "xxxxx",
>     "oauth": {
>         "domain": "project3310eb456-310eb456-project.auth.eu-central-1.amazoncognito.com",
>         "scope": [
>             "phone",
>             "email",
>             "openid",
>             "profile",
>             "aws.cognito.signin.user.admin"
>         ],
>         "redirectSignIn": "exp://127.0.0.1:19000/--/",
>         "redirectSignOut": "exp://127.0.0.1:19000/--/",
>         "responseType": "code"
>     },
>     "federationTarget": "COGNITO_USER_POOLS"
> };
> ```
> 
> Versions:
> "aws-amplify": "^1.2.3",
> "aws-amplify-react-native": "^2.2.3",
> "expo": "^35.0.0",
> "react": "16.8.3",
> 
> Now in apple IOS simulator i am redirected, authenticate with facebook and get redirected back to my app, it's rendered correctly - user name is displayed - but it somehow hangs after that, still troubleshooting.
> In Android 10 simulator once i authenticate with facebook and get redirected i got error:
> 
> console.error: "[ERROR] 30:55.468 OAuth - Error handling auth response.", {"line":182049,"column":32,"sourceURL":"[http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false"}](http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false%22%7D)
> __expoConsoleLog
> RemoteConsole.js:80:37
> 
> [ERROR] 30:55.468 OAuth - Error handling auth response., [Error: invalid_grant]
> 
> * node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
> * ... 16 more stack frames from framework internals
> 
> [Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_a.accessToken')]
> 
> * node_modules/@aws-amplify/auth/lib-esm/Auth.js:1655:57 in
> * node_modules/@aws-amplify/auth/lib-esm/Auth.js:44:27 in step
> * ... 12 more stack frames from framework internals
> 
> When i repeat the same steps using Google authentication i got identical error for both IOS + Android simulator. The same error when choosing HostedUI page (which is interesting because i got this error for IOS simulator when using hostedIU + facebook while i do not get any error and redirection back works fine for IOS simulator and direct facebook).
> 
> Would be great to have posted a simple react-native app using hooks with working facebook/google auth - it seems everybody is still struggling with it. Again: the documentation for react vs react native should be splitted IMHO.
> 
> Thanks,

I also facing same issue with react-native (android).

**Comment by ni3galave** [comment] 2019-11-12 05:33
@dahersoftware did you get any workaround for this issue?

@undefobj any update?

**Comment by dahersoftware** [comment] 2019-11-12 08:50
@ni3galave no update from my side.

**Comment by mlabieniec** [comment] 2019-11-12 15:54
I think the main issue here is that in Expo, Deep linking is built in (see exp:// in that aws-export there)...where as for @dahersoftware he is not using expo. @dahersoftware ultimately you will need to include some sort of deep linking handler in your React Native app using the [Linking](https://facebook.github.io/react-native/docs/linking.html) API in react native, see here for a tutorial on that as well: https://medium.com/react-native-training/deep-linking-your-react-native-app-d87c39a1ad5e

We will add a docs update to better document this for React Native. The Android issue @ni3galave  is experiencing there is something else, the `Error: invalid_grant` error is referring to token/code grant, which right now you have as `"responseType": "code"`. Assuming that's what you have configured in your User Pool as well since it is working on iOS. I think this may be a permissions error on the Android side for **Offline** storage permission potentially. See here:
https://stackoverflow.com/questions/10576386/invalid-grant-trying-to-get-oauth-token-from-google

Do you have this permission set on the Android side? I believe this is also something else Expo takes care of under the covers.

**Comment by dahersoftware** [comment] 2019-11-13 06:55
Thanks @mlabieniec for the update. I will check things as per your post and will update here if things work.

**Comment by Jobel91** [comment] 2019-12-20 10:57
I'm facing this issue, with React-Native without Expo.

Following the example in the doc : https://aws-amplify.github.io/docs/js/authentication#facebook-example-in-react-native-expo, it seems that we need to get a token before launch the process with Auth.federatedSignIn() method.

Maybe a workaround would be to use [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk) with the **LoginManager.logInWithPermissions** method which seems to be equal with the **Facebook.logInWithReadPermissionsAsync()** from Expo Facebook library.

@dahersoftware did you found a workaround ?

**Comment by JSDevelopment17** [comment] 2020-01-13 21:16
I'm using Expo and amplify to login via facebook using the federated login.
This works for me fine on my simulator but when I actually use on the device I can successfully 'Continue' using Facebook (web), but when it redirects back to expo I get an error:
"There was a problem loading the requested app"
![fullsizeoutput_1ee3](https://user-images.githubusercontent.com/33499076/72292727-e4f51180-3649-11ea-9316-8e5a63cf3fa0.jpeg)

**Comment by chunyenHuang** [comment] 2020-02-17 07:00
In case anyone still needs help for expo+amplify+social logins

#### app.json
```json
{
  "expo": {
    "scheme": "exposchemeappname://"
  }
}
```

#### App.js
```javascript
import { Linking } from 'expo';
import * as WebBrowser from 'expo-web-browser';

import awsconfig from './aws-exports';

const amplifyConfig = {
  ...awsconfig,
  oauth: {
    ...awsconfig.oauth,
    urlOpener: async (url, redirectUrl) => {
      // On Expo, use WebBrowser.openAuthSessionAsync to open the Hosted UI pages.
      const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(url, redirectUrl);

      if (type === 'success') {
        await WebBrowser.dismissBrowser();

        if (Platform.OS === 'ios') {
          return Linking.openURL(newUrl);
        }
      }
    },
    options: {
      // Indicates if the data collection is enabled to support Cognito advanced security features. By default, this flag is set to true.
      AdvancedSecurityDataCollectionFlag: true
    },
  }
};

const expoScheme = "exposchemeappname://"
let redirectUrl = Linking.makeUrl();
if (redirectUrl.startsWith('exp://1')) {
  // handle simulator(localhost) and device(Lan)
  redirectUrl = redirectUrl + '/--/';
} else
if (redirectUrl === expoScheme) {
  // dont do anything
} else {
  // handle the expo client
  redirectUrl = redirectUrl + '/'
}
amplifyConfig.oauth.redirectSignIn = redirectUrl;
amplifyConfig.oauth.redirectSignOut = redirectUrl;

Amplify.configure(amplifyConfig);
```

Make sure you add the following redirect urls to amplify `amplify auth update`

```bash
# development
exp://127.0.0.1:19000/--/
exp://192.168.1.101:19000/ # depends on your lan ip

# expo client
exp://exp.host/@[EXPO_ACCOUNT]/[EXPO_APPNAME]/

# expo scheme for standalone
exposchemeappname://
```

**Comment by JSDevelopment17** [comment] 2020-03-01 19:29
Thanks for this chunyenHuang - the use of localIP helped with the expo client on my device. I'm still struggling with the standalone app however. What should the redirect URL be for an app in TestFlight or the AppStore?

**Comment by chunyenHuang** [comment] 2020-03-02 06:05
@JSDevelopment17 
You will need to setup the `scheme` ( you can use any name you like)

```javascript
// app.json
{
  "expo": {
    "scheme": "exposchemeappname://"
  }
}
```

and use this 
```bash
# expo scheme for standalone
exposchemeappname://
```

**Comment by JSDevelopment17** [comment] 2020-03-02 07:45
Apologies if this sounds dumb - where do I use the second bit? I've got app.json setup but it looks like I'm missing it from elsewhere

**Comment by chunyenHuang** [comment] 2020-03-03 15:14
> Apologies if this sounds dumb - where do I use the second bit? I've got app.json setup but it looks like I'm missing it from elsewhere

You need to run `amplify auth update` and add the new redirect url to your cognito service. And you should see the link in your `aws-exports.json`. Then you can use the script I provide here https://github.com/aws-amplify/amplify-js/issues/4244#issuecomment-586845322 to replace the `redirectUrl` from a string list to a single url string.

**Comment by nganoro** [comment] 2020-03-27 18:41
@JSDevelopment17 Hey man, i am struggling with the same issue for my android app using android studio, were you able to figure it out?

thanks

**Comment by rahulje9** [comment] 2020-04-16 14:09
I'm also facing the same issue in react native both android and ios.

I've given redirect url as follows

`redirectSignIn: 'myapp://',
            redirectSignOut: 'myapp://',`

**Comment by DavidBrear** [comment] 2020-06-02 01:50
@chunyenHuang thanks for your advice on the script; it worked really well to get the local expo instance working. I'm still having a problem getting my stand alone app to work with it. I am using facebook auth and it kicks back to my application but does not catch the auth and goes right back to the login page. My scheme is called `fanscout://` and i tried adding `fanscout://--/` to see if that would work but that just caused the `redirect_mismatch` error.

Is there something I need to add to catch the auth only for production? Sadly, because it's production / staging, it's the only place I can't debug.

**Comment by oguzhanali** [comment] 2020-09-15 20:42
@chunyenHuang @kimfucious I used same use case for RN & Expo as [Amplify docs](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend) and your examples shows. I am trying this on dev, everything works fine (user signs in and getting user's pool credentials etc.) but then when I use Auth.signout(), sign out action works okey too (Hub.listener signout event triggers) but also urlOpener(code is below) triggers again with a permission request for redirectSignOut url. There is also an open issue about it #4993  

urlOpener from Amplify docs:


```
async function urlOpener(url, redirectUrl) {

    const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(
        url,
        redirectUrl
    );

    if (type === "success" && Platform.OS === "ios") {
        WebBrowser.dismissBrowser();
        return Linking.openURL(newUrl);
    }

}
```


I use Auth.federatedsignin(Facebook, Google etc.) as an User Pool Federation like #2716 says and I expected just Auth.signout() should be enough. Why urlOpener is triggering again and requesting open webbrowser? I could prevent signout link's request but i am curious about why is it not being mentioned? Didn't you face this issue? This is a very basic use case, am I missing something?

**Comment by oguzhanali** [comment] 2020-09-15 21:15
I found the answer for my question #2115. Short answer is Amplify docs has poor quality, looking for this basic thing for a day or two.

**Comment by sammartinez** [comment] 2020-10-20 15:22
The original issue in regards to the redirection URL mismatch error has been updated in our documentation site. You are able to find the full examples [here](https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples). Resolving

**Closed by sammartinez** 2020-10-20 15:22 UTC
Labels: Auth, React Native, bug, documentation

**Comment by danerbrear** [comment] 2020-12-14 22:28
I believe the solution to this problem has not been fixed yet. @sammartinez comment was a step in the right direction. However, I believe the problem is in url passed to open the facebook provider. See the following:

url passed to Auth.federatedSignIn() as seen through the openUrl() function --> https://myapp.auth.us-east-1.amazoncognito.com/oauth2/authorize?redirect_uri=myapp%3A%2F%2F&response_type=code&client_id=xxxxxxx&identity_provider=COGNITO&scope=email%20openid&state=xxxxxx&code_challenge=xxxx&code_challenge_method=xxx

as you can see, the redirect_uri parameter is myapp://. However, the "://" is encoded. I believe the encoding is causing the error that this thread is based on.

This is without using expo. I also have not yet determined a solution, but hopefully this is another step in the right direction.

**Comment by LoganArnett** [comment] 2021-03-18 20:21
@danerbrear were you ever able to solve this issue? I appear to be running into the same issue
