### ISSUE TITLE
aws-exports.js not created by amplify push

### ISSUE THREAD

**Issue by 01binary** [aws-amplify/amplify-js#3846] opened 2019-08-13 19:22 UTC
**Describe the bug**
Amplify documentation states that aws-exports.js will be created by amplify push command. This file is not created, and makes running the application impossible.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by jordanranz** [comment] 2019-08-13 22:39
Closing as a duplicate of: #3845

**Closed by jordanranz** 2019-08-13 22:39 UTC
