### ISSUE TITLE
An accessor cannot be declared in an ambient context - @aws-amplify - 1.2.5-unstable.5

### ISSUE THREAD

**Issue by vc-ishver** [aws-amplify/amplify-js#4389] opened 2019-11-13 09:29 UTC
ERROR in ·[96m../node_modules/@aws-amplify/core/lib-esm/ServiceWorker/ServiceWorker.d.ts·[0m:·[93m23·[0m:·[93m9·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m23·[0m     get serviceWorker(): ServiceWorker; 
·[7m  ·[0m ·[91m        ~~~~~~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/PubSub.d.ts·[0m:·[93m13·[0m:·[93m17·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m13·[0m     private get awsAppSyncProvider(); 
·[7m  ·[0m ·[91m                ~~~~~~~~~~~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/PubSubProvider.d.ts·[0m:·[93m9·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m9·[0m     protected get options(): ProvidertOptions; 
·[7m ·[0m ·[91m                  ~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts·[0m:·[93m12·[0m:·[93m9·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m12·[0m     get allClients(): string[]; 
·[7m  ·[0m ·[91m        ~~~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts·[0m:·[93m18·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m18·[0m     protected get clientId(): any; 
·[7m  ·[0m ·[91m                  ~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts·[0m:·[93m19·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m19·[0m     protected get endpoint(): any; 
·[7m  ·[0m ·[91m                  ~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts·[0m:·[93m20·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m20·[0m     protected get clientsQueue(): ClientsQueue; 
·[7m  ·[0m ·[91m                  ~~~~~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts·[0m:·[93m21·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m21·[0m     protected get isSSLEnabled(): boolean; 
·[7m  ·[0m ·[91m                  ~~~~~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSIotProvider.d.ts·[0m:·[93m3·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m3·[0m     protected get region(): any; 
·[7m ·[0m ·[91m                  ~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSIotProvider.d.ts·[0m:·[93m5·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m5·[0m     protected get endpoint(): Promise<string>; 
·[7m ·[0m ·[91m                  ~~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/interactions/lib-esm/Providers/InteractionsProvider.d.ts·[0m:·[93m8·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m8·[0m     protected get options(): InteractionsOptions; 
·[7m ·[0m ·[91m                  ~~~~~~~·[0m 
·[96m../node_modules/@aws-amplify/xr/lib-esm/Providers/XRProvider.d.ts·[0m:·[93m8·[0m:·[93m19·[0m - ·[91merror·[0m·[90m TS1086: ·[0mAn accessor cannot be declared in an ambient context. 
 
·[7m8·[0m     protected get options(): ProviderOptions; 
·[7m ·[0m ·[91m                  ~~~~~~~·[0m 
 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! vivanco@0.0.0 build:client-and-server-bundles: `ng build --prod && ng run vivanco:server:production` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the vivanco@0.0.0 build:client-and-server-bundles script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     /root/.npm/_logs/2019-11-13T07_27_56_230Z-debug.log 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! vivanco@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run compile:server` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the vivanco@0.0.0 build:ssr script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     /root/.npm/_logs/2019-11-13T07_27_56_243Z-debug.log 
 
[Container] 2019/11/13 07:27:56 Command did not exit successfully npm run build:ssr exit status 1 
[Container] 2019/11/13 07:27:56 Phase complete: POST_BUILD State: FAILED 
[Container] 2019/11/13 07:27:56 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run build:ssr. Reason: exit status 1 
[Container] 2019/11/13 07:27:56 Expanding base directory path: . 
[Container] 2019/11/13 07:27:56 Assembling file list 
[Container] 2019/11/13 07:27:56 Expanding . 
[Container] 2019/11/13 07:27:56 Expanding file paths for base directory . 
[Container] 2019/11/13 07:27:56 Assembling file list 
[Container] 2019/11/13 07:27:56 Expanding template.yml 
[Container] 2019/11/13 07:27:56 Expanding README.md 
[Container] 2019/11/13 07:27:56 Expanding package.json 
[Container] 2019/11/13 07:27:56 Expanding appspec.yml 
[Container] 2019/11/13 07:27:56 Expanding scripts/* 
[Container] 2019/11/13 07:27:56 Expanding node_modules/**/* 
[Container] 2019/11/13 07:27:56 Expanding dist/**/* 
[Container] 2019/11/13 07:27:56 Expanding template-configuration.json 
[Container] 2019/11/13 07:27:56 Found 75714 file(s) 
[Container] 2019/11/13 07:28:15 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED 
[Container] 2019/11/13 07:28:15 Phase context status code:  Message:

**Comment by iartemiev** [comment] 2019-11-13 17:12
Can you please provide some context?
* What feature of Amplify are you using and what is the action that led to the error?
* Please share a code sample

**Comment by vc-ishver** [comment] 2019-11-14 05:58
I am using "aws-amplify": "^1.2.5-unstable.11" for login purpose in angular 8 universal.

On stable version gives "WINDOW NOT DEFINED" error and I add the unstable version "1.2.5-unstable.5" and on that time it works fine.

But as now, it won't allow me deploy as well as run on local machine with "ng serve".



ng serve
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.75 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2019-11-14T05:50:24.986Z - Hash: 1333d03a06133d940f40 - Time: 13440ms

ERROR in ../node_modules/@aws-amplify/core/lib-esm/ServiceWorker/ServiceWorker.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get serviceWorker(): ServiceWorker;
           ~~~~~~~~~~~~~
../node_modules/@aws-amplify/interactions/lib-esm/Providers/InteractionsProvider.d.ts:8:19 - error TS1086: An accessor cannot be declared in an ambient context.

8     protected get options(): InteractionsOptions;
                    ~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSIotProvider.d.ts:3:19 - error TS1086: An accessor cannot be declared in an ambient context.

3     protected get region(): any;
                    ~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSIotProvider.d.ts:5:19 - error TS1086: An accessor cannot be declared in an ambient context.

5     protected get endpoint(): Promise<string>;
                    ~~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.

12     get allClients(): string[];
           ~~~~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts:18:19 - error TS1086: An accessor cannot be declared in an ambient context.

18     protected get clientId(): any;
                     ~~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts:19:19 - error TS1086: An accessor cannot be declared in an ambient context.

19     protected get endpoint(): any;
                     ~~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts:20:19 - error TS1086: An accessor cannot be declared in an ambient context.

20     protected get clientsQueue(): ClientsQueue;
                     ~~~~~~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.d.ts:21:19 - error TS1086: An accessor cannot be declared in an ambient context.

21     protected get isSSLEnabled(): boolean;
                     ~~~~~~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/Providers/PubSubProvider.d.ts:9:19 - error TS1086: An accessor cannot be declared in an ambient context.

9     protected get options(): ProvidertOptions;
                    ~~~~~~~
../node_modules/@aws-amplify/pubsub/lib-esm/PubSub.d.ts:13:17 - error TS1086: An accessor cannot be declared in an ambient context.

13     private get awsAppSyncProvider();
                   ~~~~~~~~~~~~~~~~~~
../node_modules/@aws-amplify/xr/lib-esm/Providers/XRProvider.d.ts:8:19 - error TS1086: An accessor cannot be declared in an ambient context.

8     protected get options(): ProviderOptions;
                    ~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

**Comment by ekzGuille** [comment] 2019-11-14 16:51
I'm having the same problem using @aws-cdk 

```sh
 > tsc
node_modules/@aws-cdk/core/lib/cfn-element.d.ts:52:9 - error TS1086: An accessor cannot be declared in an ambient context.

52     get creationStack(): string[];
           ~~~~~~~~~~~~~

node_modules/@aws-cdk/core/lib/cfn-element.d.ts:77:9 - error TS1086: An accessor cannot be declared in an ambient context.

77     get ref(): string;
           ~~~

node_modules/@aws-cdk/core/lib/cfn-parameter.d.ts:100:9 - error TS1086: An accessor cannot be declared in an ambient context.

100     get noEcho(): boolean;
            ~~~~~~

node_modules/@aws-cdk/core/lib/cfn-parameter.d.ts:104:9 - error TS1086: An accessor cannot be declared in an ambient context.

104     get value(): IResolvable;
            ~~~~~

node_modules/@aws-cdk/core/lib/cfn-parameter.d.ts:108:9 - error TS1086: An accessor cannot be declared in an ambient context.
```

**Comment by feldmarv** [comment] 2019-11-20 21:04
We are facing the same issue in AWS CodeBuild pipeline with Angular universal 8 and "aws-amplify": "^2.1.0"

**Comment by vc-ishver** [comment] 2019-11-21 05:30
**I had try with "aws-amplify": "^2.1.1-unstable.0" , but it can't work with latest unstable version.**

ERROR in ../node_modules/@aws-amplify/core/lib-esm/ServiceWorker/ServiceWorker.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get serviceWorker(): ServiceWorker;
           ~~~~~~~~~~~~~

**Comment by ekzGuille** [comment] 2019-11-21 07:56
I found out that this error was because last version of **aws-cdk** ([v. 1.16.0](https://github.com/aws/aws-cdk/releases/tag/v1.16.0)) had breaking changes on Stack generation. 
Previously we were using [v. 1.15.0](https://github.com/aws/aws-cdk/releases/tag/v1.15.0).

* ### 1.15.0:
_node_modules/@aws-cdk/core/lib/cfn-element.d.ts_
```ts
52    readonly creationStack: string[];
```
* ### 1.16.3:
_node_modules/@aws-cdk/core/lib/cfn-element.d.ts_
```ts
52     get creationStack(): string[];
```
This ***getter*** (and all new ones in other files) is what is crashing the Stack generation.

**Comment by iartemiev** [comment] 2019-11-22 21:04
@vc-ishver Thank you for the additional info. PR with the fix is up. Will update this issue once it's merged

**Closed** 2019-11-22 21:20 UTC
Labels: Angular, Build, TypeScript, bug

**Comment by iartemiev** [comment] 2019-11-22 21:25
This issue was caused by changes to declaration files generated by TypeScript 3.7+, which are incompatible with the versions of TypeScript supported by current versions of Angular Compiler. Building aws-amplify with TypeScript 3.6.4 resolves the issue.

**Comment by ekzGuille** [comment] 2019-11-22 21:30
@iartemiev Thank you. 
I will check in my project if updating to latest version also updates Typescript to 3.7+ version. If so, I will downgrade to a working version.

**Comment by iartemiev** [comment] 2019-11-22 21:37
@vc-ishver @ekzGuille please try the latest unstable version of aws-amplify (2.1.1-unstable.5
 or later)
