### ISSUE TITLE
OTP SMS Not Delivered Despite Success Status on Log

### ISSUE THREAD

**Issue by livingmine** [aws-amplify/amplify-js#5367] opened 2020-04-11 05:50 UTC
**Describe the bug**
Lately we've been experiencing an intermittent issue in which the user's sign up OTP via SMS is **not delivered** to the user's phone number, despite the fact that the Cloudwatch SNS log showed a **success** status of delivery.

**To Reproduce**

1. Select Phone number as an answer in 

> Which attributes do you want to verify? 
at user pool's MFA and verifications section

2. Use Amplify's Auth.signUp
3. Test sign up as a user
3. Check the Cloudwatch log
```
{
    "notification": {
        "messageId": "a7b58ce7-13f9-5307-b281-da1bxxxx",
        "timestamp": "2020-03-31 06:58:xxx"
    },
    "delivery": {
        "phoneCarrier": "xxx",
        "mnc": 10,
        "destination": "+6xxxx",
        "priceInUSD": xxxx,
        "smsType": "Transactional",
        "mcc": 510,
        "providerResponse": "Message has been accepted by phone",
        "dwellTimeMs": 141,
        "dwellTimeMsUntilDeviceAck": 24296
    },
    "status": "SUCCESS"
} 
```
5. But no OTP message is delivered to the phone number

**Expected behavior**
The actual OTP message should be delivered to the phone number just the same as the status delivery in the log.

**Additional context**
I've also posted this issue to the [forum](https://forums.aws.amazon.com/thread.jspa?threadID=319496) weeks ago but since then there are no replies.

**Comment by ashika01** [comment] 2020-04-15 18:55
@livingmine could you check, in the cognito console, if the user has `enable sms` enabled on them?

**Comment by livingmine** [comment] 2020-04-17 17:59
@ashika01 can you elaborate more on 

> if the user has enable sms enabled on them?

I believe i have done the right setting in the user pool's setting as this only happened occasionally to a few users.

**Comment by ashika01** [comment] 2020-06-05 23:07
@livingmine Apolozies for late reply. Did you get this working?

**Comment by gcqwant** [comment] 2020-07-14 12:32
We do have the issues on our end. Some messages do go through but others don't. Does someone experience the same issue?

**Comment by olbapaicrag** [comment] 2020-10-15 00:59
Hi @livingmine , do you have managed to solve it?

We're facing exactly the same issue when signing-up new users, but in our case, no message is delivered not even occasionally.

**Comment by livingmine** [comment] 2020-10-15 05:50
@olbapaicrag nope, i guess that's the nature of SMS OTP delivery wherever we are in this world :) If you want a better delivery rate you can try to find a local provider in your costumer's country.

So in your case no message is delivered not even occasionally but the log showed success status for all of them?

**Comment by olbapaicrag** [comment] 2020-10-15 15:30
@livingmine yes, we can see success for all the messages sent on the log, but the SMS never reaches its end.

{
    "notification": {
        "messageId": "6beb16c0-1929-51ea-8027-4ec18cf9d9df",
        "timestamp": "2020-10-15 00:10:56.355"
    },
    "delivery": {
        "phoneCarrier": "xxxxxx",
        "mnc": 30,
        "numberOfMessageParts": 1,
        "destination": "+5xxxxxxxxxx",
        "priceInUSD": x.xxxxx,
        "smsType": "Transactional",
        "mcc": 710,
        "providerResponse": "Message has been accepted by phone",
        "dwellTimeMs": 173,
        "dwellTimeMsUntilDeviceAck": 9873
    },
    "status": "SUCCESS"
}

Now we requested an SNS Limit Increase as suggested [here ](https://github.com/aws-amplify/amplify-js/issues/6344#issuecomment-663144472) hoping that solves our issues.

**Comment by olbapaicrag** [comment] 2020-10-19 23:15
Well, 

Today I got the SNS Limit Increase message confirmation. I configured it out accordingly to the limit requested, unfortunately, I was still not able to receive the SMS messages.

So, I went through the configuration of the Role configured by Amplify for Cognito to send SMS messages and figure it out that the Role didn't have the Publish action granted (I guess Amplify should have configured it), after checking it and testing again I was able to receive the SMS.

![image](https://user-images.githubusercontent.com/61715169/96521300-2d230f00-122e-11eb-8110-ae2087ceac96.png)

**Comment by gvb26** [comment] 2020-10-24 15:57
I am also experiencing this issue and updating the role does not fix it. [PLEASE ASSIST](https://github.com/aws-amplify/amplify-js/issues/7026)

**Comment by nikola116** [comment] 2020-11-05 17:09
@gvb26 I am facing that kind of issue too. it seems like that the issue is on AWS SNS (SMS providers) or by some reason, the phone carriers can block the text messages from AWS mobile numbers.

**Comment by gvb26** [comment] 2020-11-08 17:42
@nikola116 I have found a solution to the issue. [Check it out](https://github.com/aws-amplify/amplify-js/issues/7026#issuecomment-723642320)

**Comment by sammartinez** [comment] 2021-02-09 22:05
resolving as the above callout is the solution to this issue.

**Closed by sammartinez** 2021-02-09 22:05 UTC
Labels: Auth, to-be-reproduced
