### ISSUE TITLE
API.get sends 2 identical requests for one execution

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-js#7992] opened 2021-03-25 17:22 UTC
I have almost similar problem to this [ticket](https://github.com/aws-amplify/amplify-js/issues/3592). 

I make a GET request like this:

```js
const result = await API.get(S3_API_NAME, "/getbaseurl");
console.log(result);
```

But this simple request will send 4 requests (2 pairs) to the back-end. 

I checked my code and in my react app only in the `index.js` I have once 

```js
import Amplify from "aws-amplify";
import config from "./aws-exports";
Amplify.configure(config);
```

What could be the reason that it sends 2 requests? My REST API does not need any auth data.

**Comment by siegerts** [comment] 2021-03-25 17:35
Hi @mjza  :wave: - thanks for raising this!  

To get a bit more context, do you mind porting this to the [formatted bug report template](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=).

This will help the team determine the best approach to take based on your environment and setup.

**Comment by mjza** [comment] 2021-03-25 17:40
@siegerts To be honest the number of questions in your form is too much. The information that is needed is I am using the latest aws-amplify 3.3.25.

**Comment by siegerts** [comment] 2021-03-25 17:52
Hi @mjza , thanks for providing that! It would be helpful to understand the steps and structure of your code to replicate :) 

1. Are you importing `API`?:

```js
import Amplify, { API } from 'aws-amplify';
```

Is there any information that you can share on the duplicate request?  The result of your `console.log`, etc.? 

Thanks!

**Comment by mjza** [comment] 2021-03-25 17:58
The API is a simple REST GET api I made by amplify cli. 

Yes I have imported like your code. 

I am pretty sure the I execute `API.get` once, but it sends the request 2 times. 

Just for your information I use `Auth` also but I don't use `Auth.config` at all.

**Comment by siegerts** [comment] 2021-03-25 20:37
Thanks! Without knowing more about your project and what the output is, I'm not able to reproduce duplicate requests to an API being made.  There may be two requests with using different methods (i.e. OPTIONS) but that is based on the preflight request. More on that can be found [here](https://stackoverflow.com/a/29954326/2205847). Please see below.

**Framework**
React

**Amplify APIs** 
REST API

**Amplify Categories**
api, function, hosting


**Steps to reproduce:** 

My example project code can be viewed here - https://github.com/siegerts/create-react-app-amplify-api

1. Create React application (`npx create-react-app react-app-api`)
2. Run `amplify init`  - use defaults
3. Run `amplify add function` - use defaults
4. [Uncomment default Lambda function code to enable CORS](https://github.com/siegerts/create-react-app-amplify-api/blob/main/amplify/backend/function/reactappapicb10fa8f/src/index.js#L6-L9)
5. Run `amplify add api` 
   * REST -> associate with above Function
   * No auth required
6. Run `amplify push`
7. Update React application in [index.js](https://github.com/siegerts/create-react-app-amplify-api/blob/main/src/index.js#L7-L9) and  [App.js](https://github.com/siegerts/create-react-app-amplify-api/blob/main/src/App.js) to make an API request on button click

### On Button click 

#### Running locally (one network request) 

- ![image](https://user-images.githubusercontent.com/634958/112536476-e3fa5c80-8d83-11eb-9bae-fbca0ed06a30.png)


#### Deployed version (one network request) 

- https://d3k2fbglhlgm45.cloudfront.net/

#### Browsers tested
- [x] Brave 
- [x] Chrome 


## Follow on test (locally)

- Added `auth` (with defaults)
- Created  user
- Signed in, and clicked button
- 2 separate requests - OPTIONS/GET 
   - expected behavior  

![image](https://user-images.githubusercontent.com/634958/112540080-245bd980-8d88-11eb-984d-0697e8c5c63b.png)



## Next steps 
If you're steps or setup deviate from above, then please list out in as much detail as it helps to isolate any discrepancies

**Comment by siegerts** [comment] 2021-04-01 14:25
Hey! Closing for now since there hasn't been any follow up.

**Closed by siegerts** 2021-04-01 14:25 UTC
Labels: Can't reproduce, pending-close-response-required
