### ISSUE TITLE
user and session is null after login

### ISSUE THREAD

**Issue by lifedup** [aws-amplify/amplify-js#7832] opened 2021-02-28 01:16 UTC
**Describe the bug**
User is not authenticated error after sign in 
Session is null after sign in (clent and server)
User is null after sign in (client and server)
Incorrect config (server side)

This was happening on both client and server

My users are confirmed and the session and user were returning not logged in even though the user's data was set in cookies (or local storage depending on the config)

There are dozens of users who have reported this issues over the last 3 or so years and ALL of them are closed without solution.

I come with direction and work around, however, I do not know the solution.

I think these errors are because of how the library is importing and exporting the internal functions.

**Config**
Custom UI
Manual setup - did not use CLI to setup
Only using Cognito - not the whole amplify (GovCloud)
next - 10.0.6
@aws-amplify/auth - 3.4.22",
aws-amplify - 3.3.21",

**Expected behavior**
import Auth from '@aws-amplify/auth';
Auth.currentAuthenticatedUser();
Auth.currentSession();

to return authenticated user or session after sign in on both client and server side

**Code Snippet**

I figured out what is happening however I do not know how to fix it with out using both aws-amplify and @aws-amplify/auth libraries together.  I think there are some interdependencies that are not being captured in some of the libraries.  This works with cookies and local storage

### THE BLEOW CODE WORKS AND RETURNS USER AND SESSION

NOTES: 
- I'm using next js so this will cover SSR and client side fixes
- All users must be confirmed prior to being able to sign in

**congnito-config.ts**

I use env vars - I converted and added notes to show localhost settings

```
const amplifyConfig = {
  region: 'us-east-1',
  userPoolId: process.env.NEXT_PUBLIC_COGNITO_POOL_ID,
  userPoolWebClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
  mandatorySignIn: false,
  authenticationFlowType: 'USER_SRP_AUTH',
  cookieStorage: { // can remove to use local storage
    domain: "localhost", // dont add port
    secure: process.env.NODE_ENV !== 'development',// make sure is boolean
    path: "/",
    expires: Number(".5"), //env vars are strings - convert to a number // if you have string cognito throws an unhelpful error that is bc this is a string
    sameSite: "lax", //set to lax bc using multiple sub domains
  },
};

export default amplifyConfig;
```

**_app.tsx** (main app entry point for client side)
You must import Amplify auth prior to being able to use it - you can do it on a page by page basis or like this example - for the whole app.

```
import React from 'react';
import Auth from '@aws-amplify/auth';// you do not need to import core
import amplifyConfig from 'lib/cognito-config';

const App = () => {
  Auth.configure(amplifyConfig); // import amplify auth
  return (<div>My app</div>);
};

export default App;
```

Notes: 

- **This code block is for amplify core team - everyone else ignore it.**
- On client side it does not matter what library you import it will work with the following
- I think this is where the trouble is - this should only work one way.  It appears there are some legacy code causing problems.

```
import Auth from '@aws-amplify/auth';
Auth.configure(amplifyConfig)

OR
import { Auth } from '@aws-amplify/auth';
Auth.configure(amplifyConfig)

OR
import Amplify from '@aws-amplify/core';
Amplify.configure({Auth: amplifyConfig})

OR
import { Auth } from '@aws-amplify/core';
Auth.configure(amplifyConfig)

OR
import Amplify from 'aws-amplify'; (this library is really slow client side I wouldn't use it)
Amplify.configure({Auth: amplifyConfig})
```

Client side example 

**index.tsx (can be any page)**

```
import React from 'react';

const Index = (): JSX.Element => {
  React.useEffect(() => {
    // this uses main entry config in _app.tsx
    // logs in browser
    const getUser = async () => {
      const user = await AmplifyAuth.currentAuthenticatedUser();
      console.log(user);
      const session = await AmplifyAuth.currentSession();
      console.log(session);
    };
    getUser();
  });

  return <div>Some Page</div>;
};

export default Index;
```

Next js server side example

Note: 

- The ssr flag in the cognito config does not make a difference if it's true or false
- On the server the ONLY library that works is "aws-amplify" - none of the others listed above work in any combination.
- You have to import the config in every server render function

**index.tsx (can be any page)**

```
import React from 'react';
import { withSSRContext } from 'aws-amplify';
import AmplifyAuth, { CognitoUser } from '@aws-amplify/auth';
import { GetServerSideProps } from 'next';
import Amplify from 'aws-amplify'; // the only lib that will return a signed in user on the server
import amplifyConfig from 'lib/cognito-config';

type User = {
  user: CognitoUser;
  session: any;
};

const Index = (props: User): JSX.Element => {
  console.log('Nextjs SSR Props - logs in browser', props);
  return <div>Some Page</div>;
};

// next js server side props option
export const getServerSideProps: GetServerSideProps = async (context) => {
  //logs in terminal
  try {
    Amplify.configure({ Auth: amplifyConfig });//the only config that will return a user after signin
    const { Auth, API } = withSSRContext(context);
    const user = await Auth.currentAuthenticatedUser();
    const session = await Auth.userSession(user);
    console.log(API);
    console.log(user);
    console.log(session);
    return {
      props: { user: JSON.stringify(user), session: JSON.stringify(session) },
    };
  } catch (e) {
    console.log(e);
    return { props: { user: null, session: null } };
  }
};

export default Index;
```

**Comment by lifedup** [comment] 2021-02-28 03:32
I think there may be some sort of race condition or an issue how withSSRContext gets the previous config
https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify/src/withSSRContext.ts

Server side this works (using /core lib)

```
**import Amplify from '@aws-amplify/core';**
import amplifyConfig from 'lib/cognito-config';

**Amplify.configure({ Auth: amplifyConfig });**

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const { Auth } = withSSRContext(context);
    const user = await Auth.currentAuthenticatedUser();
    return { props: { user } };
  } catch (e) {
    console.log(e);
    return { props: { user: null } };
  }
};
```

This does not work (moved config into ssr function)

```
import Amplify from '@aws-amplify/core';
import amplifyConfig from 'lib/cognito-config';

export const getServerSideProps: GetServerSideProps = async (context) => {
**Amplify.configure({ Auth: amplifyConfig });**
  try {
    const { Auth } = withSSRContext(context);
    const user = await Auth.currentAuthenticatedUser();
    return { props: { user } };
  } catch (e) {
    console.log(e);
    return { props: { user: null } };
  }
};
```

however, this works (switched Amplify import)

```
import Amplify from 'aws-amplify';
import amplifyConfig from 'lib/cognito-config';

export const getServerSideProps: GetServerSideProps = async (context) => {
**Amplify.configure({ Auth: amplifyConfig });**
  try {
    const { Auth } = withSSRContext(context);
    const user = await Auth.currentAuthenticatedUser();
    return { props: { user } };
  } catch (e) {
    console.log(e);
    return { props: { user: null } };
  }
};
```

**Comment by lifedup** [comment] 2021-02-28 04:10
When debugging make sure you restart your server after changing the import methods.  If you import it in a way that is acceptable it will get cached even though the config could have been changed to a way that does not work - the cache wont bust until next restart.

**Comment by sammartinez** [comment] 2021-05-19 22:12
@lifedup Apologizes on the delay. Would you mind hopping on a call to understand your use case more? @medelman17 is one of our Solution Architects on the Amplify JavaScript team that can work with you to understand how Amplify can work for you instead of a hybrid model. Please let us know

**Comment by tannerabread** [comment] 2022-12-02 16:34
Hi @lifedup, were you ever able to meet with anyone from the team? The users that were previously speaking with you no longer work here so wanted to know if you needed follow up

**Comment by nadetastic** [comment] 2023-01-06 20:38
Following up on this issue:

Since there have been some changes in the library since this issue was first opened, (import Amplify as named export etc) I'll be closing this out as I haven't been able to reproduce this issue with the most recent major version of `aws-amplify` (v5).

**Closed by nadetastic** 2023-01-06 20:38 UTC
Labels: Auth, needs-discussion
