### ISSUE TITLE
Some lower versions of iOS and Android cannot effectively obtain DeviceToken

### ISSUE THREAD

**Issue by linweiboy** [aws-amplify/amplify-js#11105] opened 2023-03-20 08:44 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

notifications

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When I use @aws-amplify/pushnotification, some old devices with lower versions of Android and iOS cannot effectively obtain devicetoken, but I can see in the debugger that Android has the getToken API, and the old iOS version does not have the Register API.
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/31678213/226286916-38e1b50e-01ba-4d7e-be7c-a271c84b03a5.png">

![image](https://user-images.githubusercontent.com/31678213/226287389-3db733ab-69c9-497e-a0d7-21e9a45ab3d5.png)

![image](https://user-images.githubusercontent.com/31678213/226287560-22bdde74-92f3-45cf-817f-9aaa94f2c7be.png)

### Expected behavior

I can get the devicetoken on the Google Pixel model Android 12 mobile phone, but I can’t get the devicetoken when I switch to Samsung SM-N9810, check Yuanshen’s Android error

### Reproduction steps

I think there is nothing wrong with the integration steps, I just switched to a mobile phone test, and did not change the code layer, and then this problem appeared.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by linweiboy** [comment] 2023-03-21 01:31
They are all real device, android 12，Google Pixel 3a XL has devicetoken and receives push notifications, but Samsung SM-N9810cannot get devicetoken and has no push notifications, iOS is iPhone 8, OS 14.1 system did not have the Register API.

**Comment by linweiboy** [comment] 2023-03-21 01:32
Google Pixel 3a XL receives the notification and ends the current process of the APP. Clicking the message in the message bar cannot restart the APP

**Comment by linweiboy** [comment] 2023-03-21 01:35
I don't know if I am missing any configuration when configuring Android, but I follow this process to configure, if there is anything missing, please let me know
[https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/](url)

**Comment by tannerabread** [comment] 2023-03-28 21:57
Hi @linweiboy so I've been trying to figure this one out after not being able to reproduce on my end. 

After reading through some issues in other repos with similar errors, it might be caused by the async nature of the call. Can I ask why you are calling the `NativeModules.RNPushNotification.getToken` directly and not using the [supplied `onRegister` method ](https://docs.amplify.aws/lib/push-notifications/working-with-api/q/platform/react-native/)? Or was that just your way of checking that it exists?

Also is your device connected to the internet when starting the app? I believe the registering happens through a call to an API so it would only work when connected to the internet and the device time is set up correctly.

**Comment by tannerabread** [comment] 2023-04-18 18:20
Hi @linweiboy we have recently released a rewritten Push Notification category with new features, can you try it out and let me know if it works for you?

You can follow the [migration steps here](https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/) or if you are starting again from scratch follow the [getting-started guide here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/)

Also note the new [API method for getting the device token](https://docs.amplify.aws/lib/push-notifications/receive-device-token/q/platform/react-native/)

**Comment by tannerabread** [comment] 2023-04-25 20:52
Hi 👋 Closing this as resolved. This should be handled with the recent release of the rewritten Push Notification category mentioned above. 

If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you.

Thank you!

**Closed by tannerabread** 2023-04-25 20:52 UTC
Labels: investigating, Push Notifications, React Native, pending-response
