### ISSUE TITLE
Auth.FederateSignIn() navigates to url with wrong subpath (Hosted UI, Cognito User Pool with SAML authentication MS Azure AD)

### ISSUE THREAD

**Issue by cptflammin** [aws-amplify/amplify-js#7276] opened 2020-11-24 20:13 UTC
**Describe the bug**

- User Pool > Federation > Identity Provider: Cognito User Pool with SAML Identity Provider (Microsoft Azure AD) configured
- User Pool > App Integration > App client settings > Launch Hosted UI: full authentication flow works as expected

Now:
when calling

() => Auth.federatedSignIn()

on button click in vanilla javascript web app (stencilJS), we are redirected to the right domain (App Integration > Domain name) BUT the subpath is wrong. We are redirect to Hosted UI at url

{domain}**/oauth2/authorize**?{queryString}
instead of
{domain}**/login**?{queryString} 

which cause "An error was encountered with the requested page."

##### Wrong:
https://my.auth.eu-central-1.amazoncognito.com
**/oauth2/authorize**
?{query_string}

##### Correct:
https://my.auth.eu-central-1.amazoncognito.com
**/login**
?{query_string}

awsconfig used in Amplify.configure(awsconfig):
...
 oauth: {
      domain: 'my.auth.eu-central-1.amazoncognito.com',
      scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'http://localhost:1234/auth/signin',
      redirectSignOut: 'http://localhost:1234/auth/signout',
      responseType: 'code', // or 'token', note that REFRESH token will only be generated when the responseType is code
      mandatorySignIn: true,
    }

Package.json

"@aws-amplify/auth": "3.4.13"

**Comment by manueliglesias** [comment] 2020-12-02 18:42
Hi @cptflammin 

Both endpoints ([LOGIN](https://docs.aws.amazon.com/cognito/latest/developerguide/login-endpoint.html) and [AUTHORIZATION](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html)) let you do OAuth flows. They behave almost the same, the AUTHORIZATION one can completely skip the hosted ui if you use a federation provider.

Do you get an error message in the url when you see the `"An error was encountered with the requested page."` message?

**Comment by manueliglesias** [comment] 2021-05-05 23:04
Hi @cptflammin 

Are you still experiencing this issue?

**Comment by sammartinez** [comment] 2021-05-18 15:32
@cptflammin,

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 15:32 UTC
Labels: Auth, Federation, needs-discussion, pending-close-response-required

**Comment by ViVa98** [comment] 2021-09-26 14:18
@sammartinez @manueliglesias 

I want to connect the existing Cognito user pool to Amplify and access Appsync APIs. The existing user pool is custom-created to use Azure AD as a SAML Identity Provider. What are the necessary steps to follow in order to connect this user pool to Amplify?

My frontend is React Web Application
