### ISSUE TITLE
aws-amplify-react-native version 2.1.10 breaks withOAuth Custom Provider Authentication

### ISSUE THREAD

**Issue by jessedoyle** [aws-amplify/amplify-js#3057] opened 2019-04-09 22:48 UTC
**Describe the bug**

After updating `aws-amplify` from version `1.1.24` to `1.1.25` and `aws-amplify-react-native` from `2.1.9` to `2.1.10`, our React Native application's authentication with a custom provider on a Cognito User Pool no longer works using the `withOAuth` HOC.

The error our app receives is (see screenshot 1):

```
NotAuthorizedException: Token is not from a supported provider of this identity pool.
```

At first glance, it looks like this PR introduced the bug: https://github.com/aws-amplify/amplify-js/pull/3005. I have a [comment](https://github.com/aws-amplify/amplify-js/pull/3005#issuecomment-481460171) on that PR that provides some initial details as well.

The upgrade also introduces a YellowBox warning in our app (see screenshot 2):

```
Possible Unhandled Promise Rejection (id: 0)
TypeError: undefined is not an object (evaluating 'window.location.href')
```

**To Reproduce**
Here is a code example similar to our code using the `withOAuth` HOC (generalized):

```js
/*
 * @flow
 */

import React from 'react';
import {
  Button,
  StyleSheet,
  Text
  View,
} from 'react-native';
import { withOAuth } from 'aws-amplify-react-native';
import { Authenticated } from '../../views';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

type Props = {
  oAuthError: ?string,
  oAuthUser: ?{},
  customProviderSignIn: Function,
  signOut: Function,
};

const SignIn = (props: Props) => {
  if (props.oAuthUser) {
    return (<Authenticated {...props} />);
  }

  return (
    <View style={styles.container}>
      <Text>Login</Text>
      <Text>{ props.oAuthError }</Text>
      <Button
        onPress={() => props.customProviderSignIn('azure')}
        title="Proceed to Login"
      />
    </View>
  );
};

export default withOAuth(SignIn);
```

**Expected Behavior**
After clicking the "Proceed to Login" button the user is redirected using the device's browser to the custom provider authentication page.

After the custom provider authenticates, the browser redirects to a deep link that opens our application and provides an  OAuth2 `code` parameter and grant.

This process worked as expected with `aws-amplify-react-native == 2.1.9` and `aws-amplify == 1.1.24`.

**Current Behavior**
On `aws-amplify-react-native == 2.1.10`, the custom provider authentication works successfully in the browser and the deep link redirection occurs opening our application.

After our application opens, Amplify returns the following error:

```
NotAuthorizedException: Token is not from a supported provider of this identity pool.
```

**Screenshots**
### 1 - Error
![Screen Shot 2019-04-09 at 4 20 19 PM](https://user-images.githubusercontent.com/6474230/55840033-38e52f80-5ae7-11e9-800f-1a890e9c78b7.png)

### 2 - Warning
![Screen Shot 2019-04-09 at 4 05 07 PM](https://user-images.githubusercontent.com/6474230/55840040-3e427a00-5ae7-11e9-9278-f9401f820472.png)

**Comment by manueliglesias** [comment] 2019-04-10 19:12
Hi @jessedoyle 

I am working on a fix for this, thanks for the patience.

**Comment by jessedoyle** [comment] 2019-04-10 19:55
@manueliglesias - Great - please let me know if you need some testing done!

Thanks!

**Comment by undefobj** [comment] 2019-04-14 02:45
@jessedoyle can you test again with the latest version?

**Comment by jessedoyle** [comment] 2019-04-14 03:41
@undefobj - Sounds good, I’ll test on Monday and get back to you!

**Comment by jessedoyle** [comment] 2019-04-15 15:48
@undefobj - I'm seeing the same behaviour as originally mentioned in the issue with the following package versions:

- `aws-amplify` - `1.1.26`
- `aws-amplify-react-native` - `2.1.10`

The error message `NotAuthorizedException: Token is not from a supported provider of this identity pool.` is still returned on our app.

**Comment by StefanBuchman** [comment] 2019-04-18 07:20
I'm also getting failures with the new versions above.

I'm seeing the following on authentication after being redirected back to the app

`YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
Error: invalid_request
Error: invalid_request`

**Comment by jessedoyle** [comment] 2019-04-23 21:00
@undefobj - I did a bit of debugging recently.

In React Native, the `URL` parameter in https://github.com/aws-amplify/amplify-js/blob/d95cdac89d9a6f4bcb422fba83348821d52e48de/packages/auth/src/Auth.ts#L1506 resolves to `null`.

This means that `window.location.href` is referenced to set the `currentUrl` value, but `window` is not defined in React Native. This is likely part of the issue with `code` grant types in React Native.

**Comment by jessedoyle** [comment] 2019-04-23 23:15
Okay, I think I've found the root cause of the issue.

I inspected the network activity our application makes during authentication for multiple package versions. 

I tested the following versions:

###### "working" versions
- `aws-amplify === 1.1.24`
- `aws-amplify-react-native === 2.1.9`

###### "non-working" versions
- `aws-amplify === 1.1.26`
- `aws-amplify-react-native === 2.1.10`

In both cases, a request with the following form was made:

```
# request
POST cognito-identity.{{ region }}.amazonaws.com

# headers
x-amz-target:AWSCognitoIdentityService.GetId

# body
{
  "IdentityPoolId": "{{ identity-pool-id }}",
  "Logins": {
    "cognito-idp.{{ region }}.amazonaws.com/{{ user-pool-id }}": "{{ id_token }}"
  }
}

# response body
{
  "__type": "NotAuthorizedException",
  "message": "Token is not from a supported provider of this identity pool."
}
```

With the "working" package versions, the error was not propagated up via props.

With the "non-working" package versions, the error is delivered via props post authentication. I believe that we'll have a configuration change on our identity pool to accept an alternate user pool as a provider.

After debugging, the main concern we have with the recent releases is the yellowbox warning due to the issue mentioned [here](https://github.com/aws-amplify/amplify-js/issues/3057#issuecomment-485972661).

**Comment by undefobj** [comment] 2019-04-25 02:08
Interesting, sounds like you've got a User Pool that is independent of your Identity Pool which is causing an error that was previously being swallowed but is now (correctly) bubbling up. We can look at fixing this, however is there a reason why you don't have the User Pool and Identity Pool connected?

**Comment by jessedoyle** [comment] 2019-04-25 05:13
@undefobj 

> however is there a reason why you don't have the User Pool and Identity Pool connected?

Nope, it's a configuration error on our end. We're not using the identity pool yet, so the error went under the radar for a while.

**Comment by mkrn** [comment] 2019-04-26 17:00
I can confirm the similar behavior, 

Having new `undefined is not an object (evaluating window.location.href)` warning now on start.

Also, the withOAuth + props.facebookSignIn  flow doesn't authenticate the user. I'm getting the code correctly via my urlOpener but the aws-amplify lib fails to sign in the user...  Currently trying to debug this, as this used to work..

**Comment by mkrn** [comment] 2019-04-26 17:19
This may have to do with moving my code to Expo bare minimum setup from full Expo..  
can this affect Linking addEventListener? It seems that `_handleAuthResponse` from Auth.ts fires with empty url (causing that undefined is not an object) and is not firing when receiving auth response (although my urlOpener and Linking listeners in react native code fire just fine)

**Comment by mkrn** [comment] 2019-04-27 00:43
I was able to debug further to get to where it fails for me:
https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/OAuth/OAuth.ts#L144

body is a string like:
```grant_type=authorization_code&code=xxxxx-a6b7-4a91-882b-056265892fbe&client_id=xxxxxx&redirect_uri=xxxx%3A%2F%2FsignIn&code_verifier=xxxxxxxVLOJ97XlmdkN94bbjCVqpAgjYhAKOBNsAPje6neAOiu3Z2Fh```

oAuthTokenEndpoint is `https://xxxxx.auth.us-east-1.amazoncognito.com/oauth2/token`

Error is `invalid_request`
This same Body in POSTMAN gives `"error": "invalid_grant" `

The same code was working for me just recently, I'm using Cognito User Pool with Facebook Federated Identity Provider.  Callback URLs are configured properly in Cognito 

Any help greatly appreciated!

**Comment by mkrn** [comment] 2019-04-27 01:26
Before anyone spends too much time: this issue apparently is related to RN 0.59.0 and the way they implemented URLSearchParams 
https://github.com/facebook/react-native/issues/23922
🤢

**Comment by calboru** [comment] 2019-04-28 05:24
Any solution yet? I have the same problem here.

![image](https://user-images.githubusercontent.com/26364385/56859115-5e31c480-6954-11e9-8a8d-4eec8b86b633.png)

**Comment by mkrn** [comment] 2019-04-28 14:51
Looks like we're discussing 3 different issues:
- undefined is not an object evaluating window.location.href Warning 
- Fail to do Cognito federated identity sign in OAuth flow https://github.com/aws-amplify/amplify-js/issues/3183 
- Fail with `Token is not from a supported provider of this identity pool` using federated identity pools

**Comment by jessedoyle** [comment] 2019-05-07 18:41
@calboru - In our case, authorization error was bubbling up because we had our Identity Pool misconfigured (double check the "Authentication Providers" configuration section for your Identity Pool).

The only remaining issue we have with the recent releases is the YellowBox warnings on React Native.

I've submitted a PR to fix the bug here: https://github.com/aws-amplify/amplify-js/pull/3230.

**Comment by dinukasal** [comment] 2019-05-09 14:44
I also got this error, 
versions, aws-amplify: 1.1.27
aws-amplify-react-native: 2.1.11
It seems we cannot use amplify in react native for social login.

**Closed** 2019-05-09 23:01 UTC

**Comment by imtechnofreak** [comment] 2019-06-06 12:17
I am facing the same issue can anyone help ??
