### ISSUE TITLE
The @aws-amplify/ui-react Package not compatible with React 17

### ISSUE THREAD

**Issue by AhmedSarhan** [aws-amplify/amplify-js#7727] opened 2021-02-10 20:46 UTC
when I try to install the @aws-amplify/ui-react package to my projects it keep refusing to install because of conflicts in the node modules as it's using react 16.x and the projects are using the current version of react which is react 17.x

**Comment by Matt-Butler** [comment] 2021-02-10 22:24
I see the same issue while going through the getting started section:

1) create-react-app .....
2) npm install aws-amplify @aws-amplify/ui-react

```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.7.0" from @aws-amplify/ui-react@0.2.38
```

**Comment by wlee221** [comment] 2021-02-11 16:35
Hello! This is duplicate of #7105 so we will close this one. Please note that pr #7718 will address this.

**Closed by wlee221** 2021-02-11 16:35 UTC
Labels: to-be-reproduced

**Comment by wlee221** [comment] 2021-02-11 16:59
@Matt-Butler, you can pass `--legacy-peer-deps` option as a temporary workaround.

**Comment by AhmedSarhan** [comment] 2021-02-11 18:56
thank you will tray this
