### ISSUE TITLE
401,{"message":"The incoming token has expired"} (aws-amplify-react-native)

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6060] opened 2020-06-11 09:52 UTC
I am getting 401,{"message":"The incoming token has expired"} issue while i am in the app.

```
export async function get (endpoint: string, data?) {
    const currentSession = await Auth.currentSession();
    const providerId = currentSession.getIdToken().payload.sub;
    const identityJwt = currentSession.getIdToken().getJwtToken();
    return GET(endpoint, data, identityJwt, providerId);
}
```

**Comment by amhinson** [comment] 2020-06-12 18:20
Duplicate of https://github.com/aws-amplify/amplify-js/issues/5934

**Closed by amhinson** 2020-06-12 18:20 UTC

**Comment by nihp** [comment] 2020-06-13 03:33
Any update for this issue in Duplicate of #5934
