### ISSUE TITLE
Call Auth functions inside Jest context

### ISSUE THREAD

**Issue by elchicofrommo** [aws-amplify/amplify-js#6627] opened 2020-08-23 18:56 UTC
**Describe the bug**
Calling any of the methods in Auth running in a Jest container returns empty objects. 

**To Reproduce**
I have Auth set up with Auth and Unauth users with an identity pool. This test is for Unauthenticated Guest user. I run code (see below) in Jest.  I have Jest installed globally. 

### Baseline: node ./tests/test.ts
```
const {Logger} = require( '@aws-amplify/core')
const {Auth} = require( '@aws-amplify/auth')
const config = require('../aws-exports.js')
Logger.LOG_LEVEL = 'DEBUG';
const result = Auth.configure(config)

const log = {
  verbose: (message, objects)=>{
    console.log(message);
    objects && console.log(JSON.stringify(objects, null, 2))
  } 
}


log.verbose(`configured with the following`, {config, result})
Auth.currentCredentials().then(creds=>{
  log.verbose(`before all the auth result is`, {creds})
})

```
gives expected values, see partial logs below: 

```

[DEBUG] 38:00.881 AuthClass - getting current credentials
[DEBUG] 38:00.882 Credentials - getting credentials
[DEBUG] 38:00.883 Credentials - picking up credentials
[DEBUG] 38:00.884 Credentials - getting new cred promise
[DEBUG] 38:00.885 Credentials - checking if credentials exists and not expired
[DEBUG] 38:00.885 Credentials - need to get a new credential or refresh the existing one
[DEBUG] 38:00.886 AuthClass - Getting current user credentials
[DEBUG] 38:00.888 AuthClass - failed to get or parse item aws-amplify-federatedInfo SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at AuthClass.<anonymous> (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:1238:50)
    at step (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:45:23)
    at Object.next (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:26:53)
    at fulfilled (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:17:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[DEBUG] 38:00.889 AuthClass - Getting current session
[DEBUG] 38:00.890 AuthClass - Failed to get user from user pool
[DEBUG] 38:00.890 AuthClass - Failed to get the current user No current user
[DEBUG] 38:00.890 AuthClass - getting session failed No current user
[DEBUG] 38:00.891 Credentials - setting credentials for guest
[DEBUG] 38:01.220 Credentials - Load credentials successfully {
  accessKeyId: 'XXXX',
  secretAccessKey: 'XXXX',
  sessionToken: 'XXXXX',
  expiration: 2020-08-23T19:40:18.000Z
}
before all the auth result is
{
  "creds": {
    "accessKeyId": "XXXX",
    "secretAccessKey": "XXXX",
    "sessionToken": "XXXX",
    "expiration": "2020-08-23T19:40:18.000Z",
    "identityId": "us-west-2:b1c269cf-35b3-4b78-9b4b-f9838fa31a20",
    "authenticated": false
  }
}
Waiting for the debugger to disconnect...
```
### Failing tests
```
const {Logger} = require( '@aws-amplify/core')
const {Auth} = require( '@aws-amplify/auth')
const config = require('../aws-exports.js')
Logger.LOG_LEVEL = 'DEBUG';
const result = Auth.configure(config)

const log = {
  verbose: (message, objects)=>{
    console.log(message);
    objects && console.log(JSON.stringify(objects, null, 2))
  } 
}


log.verbose(`configured with the following`, {config, result})
const prom = Auth.currentCredentials().then(creds=>{
  log.verbose(`before all the auth result is`, {creds})

})

const  tt = (message)=>{
    var _testNum = 1;
    const _tt = (message)=>{
        return `EM${_testNum++} ${message}`
    }
    return _tt(message)
}

test(tt('validing initial redux state'), async ()=>{
    expect(true).toBe(true)
    await prom
})
```
log out put as follows

 ```
 console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.742 AuthClass - getting current credentials

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.742 Credentials - getting credentials

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.742 Credentials - picking up credentials

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.742 Credentials - getting new cred promise

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.742 Credentials - checking if credentials exists and not expired

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.742 Credentials - need to get a new credential or refresh the existing one

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.743 AuthClass - Getting current user credentials

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:109
    [DEBUG] 45:25.756 AuthClass - failed to get or parse item aws-amplify-federatedInfo SyntaxError: Unexpected token u in JSON at position 0
        at JSON.parse (<anonymous>)
        at AuthClass.<anonymous> (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/src/Auth.ts:1309:25)
        at step (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:45:23)
        at Object.next (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:26:53)
        at fulfilled (/usr/local/code/cma/cma-app/node_modules/@aws-amplify/auth/lib/Auth.js:17:58)
        at tryCallOne (/usr/local/code/cma/cma-app/node_modules/promise/lib/core.js:37:12)
        at /usr/local/code/cma/cma-app/node_modules/promise/lib/core.js:123:15
        at flush (/usr/local/code/cma/cma-app/node_modules/asap/raw.js:50:29)
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.791 AuthClass - Getting current session

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.791 AuthClass - Failed to get user from user pool

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:109
    [DEBUG] 45:25.791 AuthClass - Failed to get the current user No current user

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:109
    [DEBUG] 45:25.791 AuthClass - getting session failed No current user

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:99
    [DEBUG] 45:25.792 Credentials - setting credentials for guest

  console.log node_modules/@aws-amplify/core/lib/Logger/ConsoleLogger.js:109
    [DEBUG] 45:25.796 Credentials - Failed to load credentials Promise {
      _40: 1,
      _65: 3,
      _55: Promise {
        _40: 0,
        _65: 2,
        _55: ReferenceError: Blob is not defined
            at calculateBodyLength (/usr/local/code/cma/cma-app/node_modules/@aws-sdk/util-body-length-browser/src/index.ts:3:5)
            at /usr/local/code/cma/cma-app/node_modules/@aws-sdk/middleware-content-length/src/index.ts:32:24
            at step (/usr/local/code/cma/cma-app/node_modules/tslib/tslib.js:141:27)
            at Object.next (/usr/local/code/cma/cma-app/node_modules/tslib/tslib.js:122:57)
            at /usr/local/code/cma/cma-app/node_modules/tslib/tslib.js:115:75
            at tryCallTwo (/usr/local/code/cma/cma-app/node_modules/promise/lib/core.js:45:5)
            at doResolve (/usr/local/code/cma/cma-app/node_modules/promise/lib/core.js:200:13)
            at new Promise (/usr/local/code/cma/cma-app/node_modules/promise/lib/core.js:66:3)
            at Object.__awaiter (/usr/local/code/cma/cma-app/node_modules/tslib/tslib.js:111:16)
            at /usr/local/code/cma/cma-app/node_modules/@aws-sdk/middleware-content-length/src/index.ts:21:37,
        _72: null
      },
      _72: null
    }

  console.log tests/Auth.test.ts:9
    before all the auth result is

  console.log tests/Auth.test.ts:10
    {
      "creds": {}
    }

```
**What is Configured?**

   ```
  const awsmobile = {
    "aws_project_region": "us-west-2",
    
    Auth: {
        identityPoolId: "us-west-2:098dac07-c56b-41f2-aeee-cd220bxxxx",
        region: "us-west-2",
        userPoolId: "us-west-2_kAZ2xxxx",   
        userPoolWebClientId: "47gfsqsm84vn2a5mp8jxxxx",

    },
    API: {
        endpoints: [
            {
                name: "CMAGuestAPI",
                endpoint: "https://xxxx",
                region: "us-west-1"
            }
        ]
    },
   ```

- jest 24.9.0
- node v14.2.0
- aws-amplify 3.0.12

**Additional context**
As you can see the test is so simple. I tried drilling into source but I just can't figure out why it's failing in Jest context. 

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by elchicofrommo** [comment] 2020-08-27 15:41
Just wanted to check on this status. It's a little annoying but manageable at the moment, I just have to remove all my auth rules when I'm doing local testing with mock so I'm still able to move forward with most test cases, but in probably 3-4 days i'll need to move to the writing up the Auth tests. Need any help reproducing?

**Comment by mogarick** [comment] 2020-08-28 00:53
Hi @elchicofrommo. I have some related problem reported in #6552. 
In my case I'm having problems with `Auth.signIn` in jest vs calling from UI. 
I'm using a workaround for the moment but I'm stuck because when a call need to call a graphql operation using AWS_IAM I get a 403. Maybe is related to the workaround or to the reported problem. I don't know.

I'm leaving this comment in order to help out the Amplify team to consider grouping both issues when they add this to the dev backlog.

**Comment by evcodes** [comment] 2021-04-02 21:03
Hey @elchicofrommo, I just wanted to follow up and see if you had any luck with this issue. One possible suggestion would be to mock the functionality and not explicitly performing operation on cloud resources. Here are some videos that can help you leverage the mocking functionality within Jest.

https://jestjs.io/docs/mock-functions
https://www.youtube.com/watch?v=4Fl5GH4eYZ8&t=1s

Let me know if there's anything else I can do to help 😄

**Comment by iartemiev** [comment] 2021-04-12 18:16
@elchicofrommo,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:16 UTC
Labels: Auth, Testing, pending-close-response-required
