### ISSUE TITLE
asking a poc for web push notification using aws -amplify-js

### ISSUE THREAD

**Issue by ashishlata** [aws-amplify/amplify-js#5662] opened 2020-05-02 19:07 UTC
**Describe the bug**
Can you please create one poc for web push notification or give some guidance (how we will use service workers )in aws-amplify-js project.

**To Reproduce**

**Expected behavior**

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
       "aws_project_region": "us-east-1",
       "aws_cognito_identity_pool_id": "us-east-1:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
       "aws_cognito_region": "us-east-1",
       "aws_user_pools_id": "us-east-1_xxx",
       "aws_user_pools_web_client_id": "xxxx",
       "oauth": {}
   };
   ```
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
           }
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by jordanranz** [comment] 2020-05-04 18:10
Push Notifications is currently only support for React Native in the javascript environment as noted here: https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js

Marking this as a feature request

**Comment by ericclemmons** [comment] 2020-05-11 22:19
@jordanranz This issue may be better in the docs repo to improve:
> https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js

@ashishlata Do you have questions or suggestions on how we can improve these pages?

- https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js
- https://docs.amplify.aws/lib/utilities/serviceworker/q/platform/js#handling-a-push-notification

**Comment by tannerabread** [comment] 2022-11-29 16:16
Duplicate of #4943

**Closed by tannerabread** 2022-11-29 16:16 UTC
Labels: feature-request, Push Notifications
