### ISSUE TITLE
Auth.currentAuthenticatedUser() is not working in always as expected

### ISSUE THREAD

**Issue by mohanrao** [aws-amplify/amplify-js#1737] opened 2018-09-24 15:41 UTC
** Which Category is your question related to? **
Auth 
** What AWS Services are you utilizing? **
AWS Cognito 
** Provide additional details e.g. code snippets **

`/**
   * This method is used to get current user
   * @returns {Observable<User>}
   */
  public getCurrentUser(): Observable<User> {
    const self = this;
    return Observable.create(observer => {
      Auth.currentAuthenticatedUser()
        .then(authenticatedCognitoUser => {
          self.updateCurrentUser(authenticatedCognitoUser, self);
          observer.next(self.currentUserSubject.value);
        })
        .catch(err => observer.next(self.currentUserSubject.value));
    });
  }`

I have the above code snippet to get the current user to identify if the user is logged in or not. 

Some of our users raised the issue that application is not keeping them logged in when then launch the application after some time or some days.

Please help me what I am missing here

**Comment by powerful23** [comment] 2018-10-12 23:38
@mohanrao sorry to be late. If the user clears the cache (like localStorage) or their session is expired(usually caused by the expiration of id token and refresh token). Can you check if either of these two happened?

**Comment by mohanrao** [comment] 2018-10-13 19:29
@powerful23 Either one of them is not the case. The user was keep accessing the app. Actually it happening when app is used as PWA one scenario we know

**Comment by mohanrao** [comment] 2018-10-18 16:19
Hi @powerful23 I noticed this behavior in Safari. And also if the user refreshes the page it recognizes the user and shows the user is logged in

**Comment by mohanrao** [comment] 2018-10-19 05:07
Sure. Also i am trying to fix the code by changing the order of app initiation logic and will see if it fixes the problem

**Comment by mohanrao** [comment] 2018-10-29 20:00
When i upgraded the aws amplify to the latest version. This is no longer an issue. but running into a new issue with  #1378

**Comment by powerful23** [comment] 2018-12-26 21:36
Closing this issue due to no further response. Feel free to reopen if you still have this issue.

**Closed by powerful23** 2018-12-26 21:36 UTC
Labels: Auth, Cognito
