### ISSUE TITLE
AppSync graphql mutation input name issue with DataStore

### ISSUE THREAD

**Issue by myfairshare** [aws-amplify/amplify-js#7918] opened 2021-03-10 13:14 UTC
**Describe the bug**
There seems to be an inconsistency in an input field name in the create mutation for one of my models.
So I have a User, User has one Profile.
I create/update both using DataStore, all good no problems..

I also have a subscription model called 'PPASubscription'..
User also has one PPASubscription for users subsribing to a service. 

I'm getting an error with DataStore creating a  PPASubscription..

> "Variable 'input' has coerced Null value for NonNull type 'ID!'"

So I think I found the source of the problem and I'm thinking its an issue with the name of my model 'PPASubscription'

When I tried a query on the aws console I noticed this model has an input: 'pPASubscriptionUserId' ..
While the Profile model has input 'profileUserId'

Both these fields are created in the background but it looks like pPA..is causing an issue.

I can create the data using a standard graphql operation but not DataStore.

Is it my fault for the naming convention I used for the model 'PPASubscription' in my graphql schema?

I hope that makes sense, thank you for any feedback

**Comment by amhinson** [comment] 2021-03-10 17:07
Would you be able to share some more information about your project?
- `package.json`
- `graphql.schema`
- code snippets

Reproduction steps would also be great! Ideally, we would like to be able to create a small reproducible sample that shows the behavior you're describing. This would be the quickest way to get a resolution on the issue you're having.

**Comment by iartemiev** [comment] 2021-04-12 18:27
@myfairshare,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:27 UTC
Labels: Can't reproduce, DataStore, pending-close-response-required
