### ISSUE TITLE
Option to set DynamoDB capacity to On-Demand

### ISSUE THREAD

**Issue by chrish-21** [aws-amplify/amplify-js#2315] opened 2018-12-12 07:46 UTC
**Is your feature request related to a problem? Please describe.**
DynamoDB has two pricing models: provisioned capacity mode and on-demand capacity. Amplify always creates tables in provisioned capacity mode, and if you want on-demand capacity, you have to change them manually after every push that results in a table creation.
**Describe the solution you'd like**
I would be nice to have an option to have tables get created with on-demand capacity by default, that doesn't get overwritten on a push.

**Comment by haverchuck** [comment] 2018-12-12 17:12
Duplicate of issue in amplify-cli repository:  https://github.com/aws-amplify/amplify-cli/issues/561.
Closing this issue for now, but referencing it in the existing feature request.

**Closed by haverchuck** 2018-12-12 17:12 UTC
Labels: CLI, Storage, duplicate, feature-request
