### ISSUE TITLE
Validation message is retained all screens

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5092] opened 2020-03-14 08:40 UTC
**Describe the bug**
Validation message is retained in the 'Forgot Password' screen and signup screen and many other screens too. 
For eg)
Error message are not removed from the screen after navigating to Forgot password screen again

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Login screen
2. Click on forgot password link and enter any not registerd email Id and click on the send button
3. It shows the error message below the screen as "Username/ClientId not found
4. Again click on the Back to sign in label
5. It redirect to sign in screen
6. Again click on the  forgot password link
7. It will show the error which i have produced in the step[3]

How can I refresh this. If i clear the cache then only it shows the screen as expected

-- or --

Link to sample code

**Expected behavior**
Need to clear the error message from the screen

**Additional context**
This behavior is same for all the screens (Sign Up, Confirmation Code, SignIn etc)

**Sample code**
Imported all screens from aws-amplify-react-native

```
import {
  Authenticator,
  AmplifyTheme,
  Greetings,
  SignIn,
  ConfirmSignIn,
  RequireNewPassword,
  SignUp,
  ConfirmSignUp,
  VerifyContact,
  ForgotPassword,
  AuthPiece,
} from "aws-amplify-react-native";
```

**Comment by nihp** [comment] 2020-03-17 06:34
@ashika01 Any update on this

**Comment by amhinson** [comment] 2020-04-15 18:02
This seems to be a duplicate of #5143. I'm going to close this issue for now and we can track any progress in the other ticket.

**Closed by amhinson** 2020-04-15 18:02 UTC
Labels: React Native, to-be-reproduced
