### ISSUE TITLE
How to apply the patch

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [aws-amplify/amplify-js#4231] opened 2019-10-22 06:19 UTC
I am using angular 6 with auth
I found many usefull patch. But dont know how to apply these patch. 
i.e update in node_modules aws-amplify-angular folder or copy src folder of aws-amplify-angular as a new modules (which I tried without success).
If have to update in aws-amplify-angular folder which files should I update.
Please can someone help me on this

**Comment by Amplifiyer** [comment] 2019-10-23 22:02
Hi @ashish-dirkmedia-de, can you provide more context on what you are trying to achieve? I don't fully understand what you meant by patches here. Please share some code samples with detailed explanations.

Not sure if it'll be of any help, but here is the local development guide for developing the aws-amplify library https://github.com/aws-amplify/amplify-js/wiki/Local-Development

**Comment by ashish-dirkmedia-de** [comment] 2019-10-24 17:16
Like issue "Add federated sign in for social providers" 
It says to add components "src/components/authenticator/federated-sign-in-component/federated-sign-in.class.ts", "src/components/authenticator/federated-sign-in-component/federated-sign-in.component.core.ts"
etc.
Should I actually change in packages/aws-amplify-angular?

**Comment by Amplifiyer** [comment] 2019-10-25 23:16
Hi @ashish-dirkmedia-de, I'm assuming you are talking about #2900 which is a PR for adding federated providers in angular components. And I believe #4082 is also duplicate of this. 

If you meant to pull these PR changes (which I believe you are calling patches), you can pull the fork and branch of the PR, in this case OrozcoJonathan:angularFederatedIdentity and merge in your local fork. Please note that
* The PR is not approved, so the changes are not yet tested and not recommended for production use case
* The PR is a little old, and so there will be a bunch of conflicts while merging with your local up to date fork.

For further communication, please reply directly on the PR, or +1 if you would want to get it merged to master. Closing this issue.

**Closed by Amplifiyer** 2019-10-25 23:16 UTC
Labels: Angular, question, to-be-triaged
