### ISSUE TITLE
Lambda function not working when trying to call another api from lambda and return to client

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-js#7929] opened 2021-03-13 02:10 UTC
**Describe the bug**
I have a REST api setup connected to a lambda function (both created using amplify cli). I am trying to call an api from the lambda function (for security reasons- not to expose secret key) and then return the data to the client. however I get a CORS error. Note that when I don't call the api within the lambda (return 'hello world'), it works perfectly fine and there is no CORS issue, but when I try to call an api and then return the result of this, I get the cors issue. I have cors configured.
**To Reproduce**

1. use create-react-app and make a react project, add amplify.
2. add a lambda function with no restrictions and for the template select the serverless express option:
3. then add a rest api and select the lambda function you just created to connect to it
4. then if you move into the directory of your lambda, on the terminal run `npm install axios` to use axios library
5. the code i have in the lambda function looks like this (api key removed for security):
```
var express = require('express')
var bodyParser = require('body-parser')
var awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')

// declare a new express app
var app = express()
app.use(bodyParser.json())
app.use(awsServerlessExpressMiddleware.eventContext())

// Enable CORS for all methods
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "*")
  next()
});


/**********************
 * Example get method *
 **********************/
var axios = require('axios')
app.get('/api', function(req, res) {
    axios.get(`https://api.openweathermap.org/data/2.5/onecall?lat=${51.5073509}&lon=${-0.1277583}&units=metric&appid=YOUR_API_KEY`)
    .then(response=>{
        res.json({
            success:'get call succeeded',
            url: req.url,
            data: response.data
          })
 });


app.listen(3000, function() {
    console.log("App started")
});

// Export the app object. When executing the application local this does nothing. However,
// to port it to AWS Lambda we will create a wrapper around that will load the app from
// this file
module.exports = app
```
And then in app.js import the API module and call it some a long the lines of:
```
async myFunction(){
    const data = await API.get('api226786d8','/api')
    console.log(data)
```

**Screenshots**
The error is:
![image](https://user-images.githubusercontent.com/56475258/111015191-88050080-839f-11eb-9024-21699c122a8a.png)

Also, if I type the exact url of my request to my api in my browser it returns in the browser, it returns a blank page with the following:
```
{"message": "Internal server error"}
```
**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
       "aws_project_region": "eu-west-2",
       "aws_cognito_identity_pool_id": "eu-west-2:64f2b50c-0daf-42e4-b941-726e8a5adbe7,
       "aws_cognito_region": "eu-west-2",
       "aws_user_pools_id": "eu-west-2_tqVuu8R5q",
       "aws_user_pools_web_client_id": "6t1o4qvr46m0eq0fvbll7u6ktl",
       "oauth": {}
   };
   ```
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        oauth: {}
       }
   }
   ```

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 81.66 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Edge: 89.0.774.50
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @aws-amplify/ui-react: ^0.2.8 => 0.2.8 
    @gumgum/react-script-tag: 0.0.3 => 0.0.3 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.5.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^3.0.17 => 3.0.17 
    aws-sdk: ^2.734.0 => 2.734.0 
    cors: ^2.8.5 => 2.8.5 
    mdbreact: ^4.27.0 => 4.27.0 
    node-sass: ^4.14.1 => 4.14.1 
    react: ^16.13.1 => 16.13.1 
    react-circular-progressbar: ^2.0.3 => 2.0.3 
    react-dom: ^16.13.1 => 16.13.1 
    react-helmet: ^6.1.0 => 6.1.0 
    react-hook-form: ^6.0.4 => 6.0.4 
    react-markdown: ^4.3.1 => 4.3.1 
    react-reveal: ^1.2.2 => 1.2.2 
    react-router-hash-link: ^1.2.2 => 1.2.2 
    react-scripts: 3.4.1 => 3.4.1 
    react-share: ^4.3.0 => 4.3.0 
    react-typewriting-effect: ^1.0.3 => 1.0.3 
    react-typist: ^2.0.5 => 2.0.5 
    update-json-file: ^1.1.1 => 1.1.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.43.0
    create-react-app: 3.4.1
    gatsby-cli: 2.19.1
    mdb-cli: 1.1.34
    npm: 6.14.11
    test: 0.6.0
```

</details>

**Comment by SanvirDessai** [comment] 2021-03-31 21:18
@asatvilker Have you checked for any error messages in the Cloudwatch logs for that function?

**Comment by mauerbac** [comment] 2021-05-18 20:27
We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by mauerbac** 2021-05-18 20:27 UTC
Labels: API, to-be-reproduced
