### ISSUE TITLE
How to optimize the packaged/bundle size?

### ISSUE THREAD

**Issue by chenhaiyun** [aws-amplify/amplify-js#10727] opened 2022-11-30 08:01 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

<details>

```
# Put output below this line
vue: 2.6
aws-amplify@5.0.4

```

</details>

### Describe the bug

I use the amplify analytics JS SDK to send data to Kinesis. and after run npm run build,  the amplify bundle size is too large. I have made a test and I found whether I use the aws-amplify library or the independent library (@ aws-amplify/core, @ aws-amplify/auth, @ aws-amplify/analytics), the packaged bundle size were the same. I want to know is there any other way to optimize the packaged/bundle size?

### Expected behavior

I want to reduce the bundle size

### Reproduction steps

1. create an vue project
2. npm run build and record the bundle size
3. add amplify analytics module to send data to KDS
4. run npm run build and record the bundle size
5. create another vue project
6. add @amplify/core @amplify/auth @amplify/analytics  package
7. run npm run build and record the bundle size

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="786" alt="image (2)" src="https://user-images.githubusercontent.com/7011985/204739992-996d0b2c-f61e-4dcb-b591-24601343d090.png">
<img width="874" alt="image (1)" src="https://user-images.githubusercontent.com/7011985/204739969-893aedc8-db05-434c-9274-ea75ca47a976.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/7011985/204739996-90633790-8ab8-48dd-8e7b-bfdb2e503ba2.png">

**Comment by mattiLeBlanc** [comment] 2022-12-08 06:11
Hi, I am having the same question.
I use the `aws-amplify` package and only the modules `Auth` and `API`.
When I do a build without these 2 imports I lose almost 500kB of size in my main bundle, which is huge.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/5285035/206370664-93936dfa-48ef-4a20-8d0d-3fa76f6197bb.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/5285035/206370708-15eab950-cfc0-4b4a-87e2-f30d55f02e8c.png">

I only use Auth and graphql. Is there anyway to reduce the size because 500kB is just to much, there must be a lot of JS code that is not relevant that can;t be treeshaken.

**Comment by kevinausmh** [comment] 2023-01-02 21:30
Hi, I'm facing the same problem. I noticed that the PinPoint client from aws-sdk is also bundled, although it should not be necessary when using the Kinesis provider. (Using core & analytics)

**Comment by abdallahshaban557** [comment] 2023-01-03 20:32
Hi @kevinausmh  - we have observed this in our analysis as well. We are working on improving tree shaking for this scenario as part of our overall plan to reduce the bundle size of our packages.

**Comment by blainekasten** [comment] 2023-02-09 15:44
Tree shaking is not supported in react native fwiw, It would be ideal to restructure the library like firebase has to ensure only imported libraries are bundled.

**Comment by abdallahshaban557** [comment] 2023-02-09 18:28
@blainekasten  - we are thinking about that as well! We are working on a way to ensure we serve our JavaScript web and React Native customers. Thank you for the feedback - definitely on our radar!

**Comment by abdallahshaban557** [comment] 2023-06-10 00:41
Hello everybody, our team has been focusing on reducing the bundle size of the Amplify library, and starting v 5.2.5, we have been able to reduce the bundle size for the below use cases:

        * Amplify core + Auth category: 73kB → 54kB (-26%)
        * Amplify core + Analytics category: 56kB → 30kB (-46%)

This is only the first step in our bundle size reduction efforts. In our next major version of Amplify JavaScript, we are going to provide better mechanisms for tree-shaking that will substantially reduce the bundle size. Stay tuned - we will provide updates on this issue when we have expected timelines mapped out. 

Please try out the newest version of Amplify, and let us know if you are seeing the improvements I've mentioned! Your feedback is essential to helping us improve our library!

**Comment by mattiLeBlanc** [comment] 2023-06-12 09:09
Thank you. Can't for the new version which could drastically reduce the bundle size.
Much appreciated!

**Comment by ennioVisco** [comment] 2023-06-28 09:27
> 

I'm not sure how you're counting bytes at AWS, this is what I see in `v5.5.1`:
<img width="1473" alt="Screenshot 2023-06-28 at 11 25 35" src="https://github.com/aws-amplify/amplify-js/assets/740025/ef64f055-398a-4d6c-af6e-ed5ddc1ead97">

**Comment by abdallahshaban557** [comment] 2023-06-30 01:56
Hi @ennioVisco - can we please get your `package.json` so that we can further check this?

**Comment by ennioVisco** [comment] 2023-06-30 06:33
> Hi @ennioVisco - can we please get your `package.json` so that we can further check this?

Sure! Here it is: https://gist.github.com/ennioVisco/1259d50837041396507299a827dbfc5c

**Comment by abdallahshaban557** [comment] 2023-07-06 00:13
Hi @ennioVisco  - can you please try deleting your node_moduled folder, and then re-installing your dependencies and checking your bundle size? We are still seeing smaller bundle sizes when we tried reproducing this.

```
rm -rf node_modules
yarn/npm install
```

**Comment by ennioVisco** [comment] 2023-07-06 06:29
Ok, in a clean install sizes are a bit different. If the sizes you mentioned are gzipped, I guess more or less it checks out, otherwise, I get these:

- `@aws-amplify+auth@5.5.3_react-native@0.72.1/node_modules/@aws-amplify/auth/lib-esm` ~55KB (Gzip: ~15KB)
- `@aws-amplify+core@5.5.2_react-native@0.72.1/node_modules/@aws-amplify/core/lib-esm` ~69KB (Gzip: ~29KB)
- `amazon-cognito-identity-js@6.3.1/node_modules/amazon-cognito-identity-js/es` ~55KB (Gzip: ~18KB)

with some very minor extra dependencies, not relevant for this analysis.

**Comment by abdallahshaban557** [comment] 2023-07-06 14:45
Hi @ennioVisco  - that is correct, the sizes mentioned are gzipped! I am glad you are seeing closer results to our analysis.

**Comment by abdallahshaban557** [comment] 2023-07-14 21:04
Hello everyone, We have made some additional changes to reduce the bundle size which include reduction to the Storage category as part of `aws-amplify@5.3.4`. Below are our updated reduction numbers for the gzip bundle size. Please let us know if you are seeing these reductions in your apps. 

- Amplify core + Auth category: 73kB → 54kB (-26%)
- Amplify core + Analytics category: 56kB → 30kB (-46%)
- Amplify core + Storage category: 71KB → 29kB (-59%).

**Comment by mattiLeBlanc** [comment] 2023-07-16 05:37
I actually saw an increase in  bundle size:
`"aws-amplify": "^5.3.4"`
```
Initial Chunk Files           | Names                                                          |  Raw Size | Estimated Transfer Size
main.c9294920e0fb3feb.js      | main                                                           |   1.61 MB |               331.52 kB
styles.45c175ecf67a26df.css   | styles                                                         | 156.14 kB |                11.65 kB
polyfills.f34159776d2cef6e.js | polyfills                                                      |  33.07 kB |                10.68 kB
runtime.a3c9c54fc9486aa2.js   | runtime                                                        |   4.35 kB |                 2.09 kB
```

`"aws-amplify": "^5.2.5",`
```
Initial Chunk Files           | Names                                                          |  Raw Size | Estimated Transfer Size
main.ab3c1696c8cd858e.js      | main                                                           |   1.59 MB |               330.50 kB
styles.45c175ecf67a26df.css   | styles                                                         | 156.14 kB |                11.65 kB
polyfills.f34159776d2cef6e.js | polyfills                                                      |  33.07 kB |                10.68 kB
runtime.a3c9c54fc9486aa2.js   | runtime                                                        |   4.35 kB |                 2.09 kB
```

**Comment by abdallahshaban557** [comment] 2023-07-18 00:19
Hi @mattiLeBlanc  - can you please try deleting your node_modules folder and then re-installing your dependencies? Also, can you please provide us with your package.json to further investigate this?

**Comment by mattiLeBlanc** [comment] 2023-07-18 01:43
@abdallahshaban557 
I ran a production configuration angular build again:
```
Initial Chunk Files           | Names                                                          |  Raw Size | Estimated Transfer Size
main.8c2b5731f3d94ee6.js      | main                                                           |   1.62 MB |               331.85 kB
styles.45c175ecf67a26df.css   | styles                                                         | 156.14 kB |                11.65 kB
polyfills.f34159776d2cef6e.js | polyfills                                                      |  33.07 kB |                10.68 kB
runtime.8ea17c38f91e9648.js   | runtime                                                        |   4.35 kB |                 2.09 kB

                              | Initial Total                                                  |   1.80 MB |               356.27 kB
```

My package file:
```
{
  "name": "apollo-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "createVersionFile": "node create-version.js",
    "extract-translations": "ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json --sort --format namespaced-json --marker _",
    "aws:init": "npx ts-node --project tsconfig.aws.json scripts/aws-init.ts",
    "deploy": "cdk deploy --require-approval never",
    "cdk": "cdk"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.0.2",
    "@angular/cdk": "^16.0.1",
    "@angular/common": "^16.0.2",
    "@angular/compiler": "^16.0.2",
    "@angular/core": "^16.0.2",
    "@angular/forms": "^16.0.2",
    "@angular/material": "^16.0.1",
    "@angular/material-moment-adapter": "^16.0.1",
    "@angular/platform-browser": "^16.0.2",
    "@angular/platform-browser-dynamic": "^16.0.2",
    "@angular/router": "^16.0.2",
    "@angular/youtube-player": "^16.0.1",
    "@iplab/ngx-file-upload": "^16.0.1",
    "@vimeo/player": "^2.18.0",
    "angular-google-tag-manager": "^1.8.0",
    "aws-amplify": "^5.3.4",
    "axios": "^1.3.4",
    "dayjs": "^1.11.7",
    "nosleep.js": "^0.12.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.2",
    "@angular/cli": "~16.0.2",
    "@angular/compiler-cli": "^16.0.2",
    "@types/jasmine": "~4.3.0",
    "@types/node": "10.17.27",
    "@types/prettier": "2.6.0",
    "@types/vimeo__player": "^2.16.3",
    "@types/youtube": "^0.0.47",
    "aws-cdk": "2.50.0",
    "aws-cdk-lib": "2.50.0",
    "aws-sdk": "^2.1256.0",
    "constructs": "^10.0.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "source-map-support": "^0.5.21",
    "ts-node": "^10.9.1",
    "typescript": "~5.0.4"
  }
}


```

**Comment by abdallahshaban557** [comment] 2023-07-18 04:30
Hi @mattiLeBlanc  - thank you for providing this information. Our team will get back to you!

**Comment by bolshchikov** [comment] 2023-07-18 05:15
Having the same issue when importing `@aws-amplify/core` and `@aws-amplify/auth`. The bundle size stays the same as importing the whole `aws-amplify`.

**Comment by jimblanc** [comment] 2023-07-18 14:12
@bolshchikov What was the size of your `@aws-amplify/auth` import before v5.2.5 (and what version of Amplify were the metrics you posted generated with)? We recommend that customers use the `aws-amplify` package, using the scoped packages won't provide much of a direct bundle size benefit as unused categories would still get tree-shaken out by your bundler.

**Comment by elorzafe** [comment] 2023-07-18 17:35
@mattiLeBlanc I see there is a duplication of `axios` package dependency, can you use the same that is using Amplify `"axios": "0.26.0"`,

**Comment by elorzafe** [comment] 2023-07-18 19:37
I can confirm that deduping `axios` dependency it would reduce the bundle size by `6.2KB`

**Comment by mattiLeBlanc** [comment] 2023-07-19 00:36
@elorzafe 

I am not sure I understand. i am using Axios for my own purposes. I didn't know Amplify or shouldn't care that Amplify has a dependency on that Axios, right?
It is also a very old version. I am using `"axios": "^1.3.4",`. If Amplify would decide to drop Axios, my code would break because I can't reference Axios in my own dependencies?

<img width="974" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/5285035/6cf14e3d-7c7a-4caa-8f73-68df3d505db3">

I only see one folder of Axios in my node modules.
I also do not see `"axios": "0.26.0",` in the package file of`aws-amplify`.

Can you elaborate where you get this from?

**Comment by elorzafe** [comment] 2023-07-19 00:46
@mattiLeBlanc 

I am not saying you should drop axios but just consider to use the same as Amplify to reduce the dependency duplication.

`@aws-amplify/api-rest` has a dependency on `axios@0.26.0` so if you have another version of axios installed it will duplicate that package unnecessary but I understand that version of `axios` is not what you need. 

I am just trying to help to reduce some of the dependency on your app and Amplify, but I understand if is not possible.

I couldn't reproduce the bundle size increase you mention maybe there was another dependency that change that impact the bundle size increase. 

Are you sure the only thing that change on your `package.json` was the version of `aws-amplify`?

**Comment by mattiLeBlanc** [comment] 2023-07-19 01:05
@elorzafe 
Sorry if I made you feel I was annoyed, that is not what I meant. 
I would not prefer to go down to such an old version of Axios, I would even recommend for Amplify to update their dependencies for security concerns.

<img width="1794" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/5285035/ef184917-ab51-43b3-8748-95513a440351">

I did a compare between 2 package files and yes, this the only change.
Of course I did evolve my app between now and 1 week ago. Maybe that is causing the bigger main file?

**Comment by elorzafe** [comment] 2023-07-19 16:57
@mattiLeBlanc 
No worries, we are in the middle of the process of improving the dependencies of Amplify, and hopefully that works better for you.

I think the changes on your App probably made the main file to be bigger, we are working very hard to make the code of Amplify small as possible. We are tracking this issue to communicate more improvements.

Thanks again for your feedback!

**Comment by mattiLeBlanc** [comment] 2023-07-20 02:39
@elorzafe Much appreciated of course, all the work you are doing!
As an end user of your product, I would love to be able to only use AUTH, and Graphql API and perhaps the pub-sub part to enable Grahpql Subscriptions.
If it would be possible to just import modules you need, it would result in a much smaller footprint I think.
I reported in December 2022 that I was getting an extra 500kb of package size due to using AUTH and API, which to me sounds much to big.  So I guess it brings in a lot of unwanted code. 
If you could separate that, that would be awesome!

**Comment by abdallahshaban557** [comment] 2023-07-20 17:04
Hello @mattiLeBlanc and @ennioVisco  - as part of our next major version, we are moving to a more functional approach where you can import specifically the functionality that you need from our categories. We are also removing some of our underlying dependencies and relying more on browser APIs to reduce the bundle sizes further. Please let us know if you have further feedback on Bundle sizes to share.

**Comment by abdallahshaban557** [comment] 2023-07-21 02:16
Hi @nolotz  - I would recommend you keep an eye out on this TypeScript RFC, we will be posting further updates on it! https://github.com/aws-amplify/amplify-js/issues/11113

We do not have an ETA we can share yet, but we will share a status and a preview of what the next major version will look like soon.

**Comment by BearCooder** [comment] 2023-07-23 09:20
> `@aws-amplify/api-rest` has a dependency on `axios@0.26.0`

I suppose replacing the axios dependency with fetch() API in the aws package could be a todo.

Some differences to note:

   - fetch is very lean, so there aren't any out of the box features that comes with Axios (e.g. auto JSON data transformation, response timeouts)
   - Some potential browser incompatibility that might be introduced by fetch. Axios is built using XMLHttpRequest, making it very browser friendly, even with very old browsers
   - In Axios, anything HTTP code 400 and above are considered errors. Fetch just sees them all as responses and will not reject any promises, so we will need to handle them in Taquito accordingly since we have been relying on Axios response errors in some of our code

The benefits of using fetch as opposed to Axios are as follows:

  -  fetch is a built in feature in Node, so no package imports are necessary
   - Since it's a built in Node feature, there no chance it will conflict with other packages
   - It gives us more flexibility to what we want to implement as opposed to something that's abstracted like Axios
   - Removes the dependency on Axios when something doesn't work properly

**Comment by mattiLeBlanc** [comment] 2023-07-23 11:47
Why not stick with Axios, but maybe a newer version?

**Comment by abdallahshaban557** [comment] 2023-07-23 19:14
Hi @BearCooder - that is exactly what we going to do as well! We want to remove any dependencies that can be used natively by your browser to help reduce the bundle size impacts even further. We are going to be doing the same effort for other parts of our library!

**Comment by CGarces** [comment] 2023-09-17 12:46
My use case:

-Very simple amplify web without any framework, the only dependency at package.json is `"aws-amplify": "^5.3.11"`
-I'm only using a REST API, a single call.

```
import { API } from '@aws-amplify/api';
import awsconfig from './aws-exports';
API.configure(awsconfig);

```

Bundle size:
361 KiB   (95.35 kB gziped)

After comment de imports and the API call. 

13KiB (2.01 KiB gziped)

+300 KiB  added just to made API.configure + API.post, probably I'll remove the aws-amplify and just made a standard fetch call.

I have tested webpack and esbuild to try to treeshaking, the best that I can get is 361 KiB and 405 KiB

**Comment by mattiLeBlanc** [comment] 2023-09-30 08:50
Hi, how are we doing with this. 
Just a quick example of my Angular 16 app with Amplify AUTH and API:

Initial Chunk Files           | Names                                                                   |  Raw Size | Estimated Transfer Size
main.a9e23881b1102d3b.js      | main                                                                    |   1.06 MB |               237.01 kB
styles.4330b0d6aa525f60.css   | styles                                                                  | 116.24 kB |                 9.59 kB
polyfills.13f5d6b062104032.js | polyfills                                                               |  33.23 kB |                10.74 kB
runtime.5fb7c0ac635b0d92.js   | runtime                                                                 |   2.95 kB |                 1.42 kB

                              | Initial Total                                                           |   1.21 MB |               258.75 kB

-----------

and without those to items:


Initial Chunk Files           | Names                                                                   |  Raw Size | Estimated Transfer Size
main.c6c897e9e3428831.js      | main                                                                    | 683.86 kB |               157.16 kB
styles.4330b0d6aa525f60.css   | styles                                                                  | 116.24 kB |                 9.59 kB
polyfills.13f5d6b062104032.js | polyfills                                                               |  33.23 kB |                10.74 kB
runtime.8e780576b3cc8520.js   | runtime                                                                 |   2.87 kB |                 1.38 kB

                              | Initial Total                                                           | 836.20 kB |               178.86 kB

So, 400 kb for an API class and the Auth class. That is pretty big, right?
When we just have more modular access to a GraphQL Api class and a Subscription class and a Auth class?

**Comment by abdallahshaban557** [comment] 2023-10-05 19:51
Hello @mattiLeBlanc  - you can check out our dev preview for v6 of the Amplify JavaScript library which has our new changes to reduce the bundle size and provide a more "functional" approach to importing only the functionality you need. https://github.com/aws-amplify/amplify-js/issues/12147

Once we feel confident with this new experience, we will release it in general availability. We are seeing massive reductions in bundle size with this new version. It is most definetely top of mind for us! Please let us know if you have any feedback to share after trying it out!

**Comment by mattiLeBlanc** [comment] 2023-10-06 02:14
I tried and left comments, I am having trouble testing it due to migration issues/differences.

**Comment by cwomack** [comment] 2023-11-16 22:02
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Closed by cwomack** 2023-11-16 22:02 UTC
Labels: feature-request, Build, bundle-size

**Comment by mattiLeBlanc** [comment] 2023-11-20 10:09
@cwomack I mentioned some feedback and issues in the other thread:
`https://github.com/aws-amplify/amplify-js/issues/12147#issuecomment-1815517219`

**Comment by suhaotian** [comment] 2025-03-11 11:09
I just wrote this article, maybe will help you:

[**Replace `axios` and `qs` modules with this in frontend projects and reduce 73KB!**](https://suhaotian.medium.com/replace-axios-and-qs-modules-with-this-in-your-frontend-projects-and-reduce-73kb-in-size-d22faf7a3456)
