### ISSUE TITLE
Auth: Native crypto module could not be used to get secure random number.

### ISSUE THREAD

**Issue by vichoconejeros** [aws-amplify/amplify-js#4886] opened 2020-02-11 04:40 UTC
I'm getting
Native crypto module could not be used to get secure random number.

call 
Auth.signIn

sample code
let user = await Auth.signIn({username:email, password:password})

Expected behavior
cognitoUser should be returned

Callstack
Native crypto module could not be used to get secure random number.
- node_modules\crypto-js\core.js:45:25 in secureRandom
- node_modules\crypto-js\core.js:337:41 in random
- node_modules\amazon-cognito-identity-js\src\AuthenticationHelper.js:25:50 in randomBytes
- node_modules\amazon-cognito-identity-js\src\AuthenticationHelper.js:104:32 in generateRandomSmallA
- node_modules\amazon-cognito-identity-js\src\AuthenticationHelper.js:64:21 in AuthenticationHelper
- node_modules\amazon-cognito-identity-js\src\CognitoUser.js:405:3 in authenticateUserPlainUsernamePassword
- node_modules\amazon-cognito-identity-js\src\CognitoUser.js:211:53 in authenticateUser
- node_modules\@aws-amplify\auth\lib\Auth.js:490:34 in <unknown>
- node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo
- node_modules\promise\setimmediate\core.js:200:23 in doResolve
- node_modules\promise\setimmediate\core.js:66:12 in Promise
- node_modules\@aws-amplify\auth\lib\Auth.js:489:27 in signInWithPassword
* screens\auth\Authentication.js:279:39 in _callee8$
...

- Device: Android Emulator

**Comment by tommy-dev** [comment] 2020-02-11 05:15
Also getting this error when calling signIn api inside jest:

```js
    const user = await Auth.signIn(username, pass);

**Comment by pouchyRT10** [comment] 2020-02-11 05:19
Getting same error

**Comment by vichoconejeros** [comment] 2020-02-11 05:51
this is due to crypto-js/core.js doing this
30:var crypto = global.crypto;
33:return Number('0.' + crypto.randomBytes(3).readUIntBE(0, 3));
y replaced 33 for
return 0.4
and it works. it seems global.crypto is not defined

@tommy-dev 
which aws-amplify version you are using? or you are just using auth and core modules?

**Comment by tommy-dev** [comment] 2020-02-11 05:53
@vichoconejeros should be the latest auth and core modules, since I installed them in a fresh project today

```js
    "@aws-amplify/auth":"^2.1.5",
    "@aws-amplify/core": "^2.2.4",

**Comment by keith1024** [comment] 2020-02-11 07:34
I am getting this same error using the `CognitoUser.authenticateUser` method in the `amazon-cognito-identity-js` package (v3.2.4).

**Comment by gyl9196** [comment] 2020-02-11 07:48
Same error, suddenly happend..

**Comment by CodeforChao** [comment] 2020-02-11 10:08
Get the same error when use `CognitoUser.authenticateUser` method in the amazon-cognito-identity-js package (v3.2.4)

And I cannot signin and get cognito token any more, is there any work around?

Error: Native crypto module could not be used to get secure random number. 
at secureRandom (/srv/node_modules/crypto-js/core.js:45:16) 
at Object.random (/srv/node_modules/crypto-js/core.js:337:30) 
at randomBytes (/srv/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:48:59) 
at AuthenticationHelper.generateRandomSmallA (/srv/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:117:21) 
at new AuthenticationHelper (/srv/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:69:29) 
at CognitoUser.authenticateUserDefaultAuth (/srv/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:295:32) 
at CognitoUser.authenticateUser (/srv/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:268:19)

**Comment by keith1024** [comment] 2020-02-11 11:46
So as @vichoconejeros pointed out. This is a `crypto-js@3.2.0` issue. A simple workaround for now is to go into your `node_modules/amazon-cognito-identity-js/` and `yarn add` or `npm install` the fixed version of `crypto-js@3.1.9-1`

**Comment by CharanRoot** [comment] 2020-02-11 17:58
Another easy solution is Add resolution in your package.json remove `node module `and run `npm install`

```
 "resolutions": {
    "crypto-js": "3.1.9-1"
  }
```

**Comment by gyl9196** [comment] 2020-02-12 00:31
Just a reminder. A new crypto-js version 3.2.1. has been released just 2 hours ago. All working on my side.

**Comment by mikedizon** [comment] 2020-02-12 01:36
You may need to clear your cache before running install again!

**Comment by mdshaner** [comment] 2020-02-12 03:07
Just for others who chance across this, it does appear that the fix with 3.2.1 makes it so that crypto-js isn't usage with ReactNative, however the resolutions solution appear to work at this time.

**Comment by vichoconejeros** [comment] 2020-02-12 03:14
> Another easy solution is Add resolution in your package.json remove `node module `and run `npm install`
> 
> ```
>  "resolutions": {
>     "crypto-js": "3.1.9-1"
>   }
> ```

it works!

**Comment by ptrobert** [comment] 2020-02-12 06:46
@mdshaner you are right,"resolutions": {
    "crypto-js": "3.1.9-1"
  }, is causing 

The package at "node_modules/crypto-js/core.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

whats is the solution

**Comment by akkisagiraju** [comment] 2020-02-12 11:10
@ptrobert I'm getting the exact same error. Because of it, I'm unable to use Amplify in my expo project.

**Comment by zeritte** [comment] 2020-02-12 13:35
crypto-js released 3.3.0 which solves `Native crypto module could not be used to get secure random number.` and `node_modules/crypto-js/core.js" attempted to import the Node standard library module "crypto-js"`. Please delete node_modules and run npm install again to fix related issues

**Comment by ptrobert** [comment] 2020-02-13 07:23
> @mdshaner you are right,"resolutions": {
> "crypto-js": "3.1.9-1"
> }, is causing
> 
> The package at "node_modules/crypto-js/core.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
> 
> whats is the solution

use this resolution for react native, expo

  "resolutions": {
    "crypto-js": "3.1.9-1",
    "**/crypto-js": "3.1.9-1"
  },

**Comment by hendrixroa** [comment] 2020-02-13 17:21
> Another easy solution is Add resolution in your package.json remove `node module `and run `npm install`
> 
> ```
>  "resolutions": {
>     "crypto-js": "3.1.9-1"
>   }
> ```

This is the solution. you can close this issue

**Comment by ericclemmons** [comment] 2020-05-13 19:18
There have been several issues with `crypto-js` introducing regressions. In fact, `3.3.0` is the same as `3.1.9-1` because of bugs with `3.2.0`:
> https://github.com/brix/crypto-js#330

`3.4.0` is out, but we're only upgrading as required because of stability issues such as these.

Closing since upgrading to the latest versions of Amplify or specifying `resolutions` unblocks the original bug:
> https://github.com/aws-amplify/amplify-js/issues/4886#issuecomment-584768632

**Closed by ericclemmons** 2020-05-13 19:18 UTC
Labels: Auth, to-be-reproduced

**Comment by tqhoughton** [comment] 2020-10-31 06:35
I'm seeing this error again in the latest release of `"@aws-amplify/auth": "^3.4.9"`

Adding
```
  "resolutions": {
    "crypto-js": "3.2.1"
  }
```

to my package.json and removing `node_modules` and reinstalling doesn't help.

**Comment by bidva** [comment] 2020-10-31 06:46
> I'm seeing this error again in the latest release of `"@aws-amplify/auth": "^3.4.9"`
> 
> Adding
> 
> ```
>   "resolutions": {
>     "crypto-js": "3.2.1"
>   }
> ```
> 
> to my package.json and removing `node_modules` and reinstalling doesn't help.

Yeah I was playing around with amazon-cognito-identity-js and got this error today. I searched the error and finally got here. I tried resolutions with yarn and even with npm-force-resolutions as npm doesn't support resolutions. it's very frustrating.

**Comment by tqhoughton** [comment] 2020-10-31 06:48
> Yeah I was playing around with amazon-cognito-identity-js@4.5.2 and got this error today. I searched the error and finally got here. I tried resolutions with yarn and even with npm-force-resolutions as npm doesn't support resolutions. it's very frustrating.

Dang, I was just about to try changing my package manager to yarn. :(

If it's any help, I'm running a typescript file using `ts-node ./createUser.ts` and it's throwing this error when signing in a user.

**Comment by bidva** [comment] 2020-10-31 06:49
@tqhoughton I just downgraded to 4.5.1 and seems start working again

**Comment by tqhoughton** [comment] 2020-10-31 06:52
@bidva do you know what version of `@aws-amplify/auth` that would correlate to?

**Comment by bidva** [comment] 2020-10-31 06:55
@tqhoughton no, sorry but you can try to test decrementally

**Comment by tqhoughton** [comment] 2020-10-31 07:03
Downgraded to 3.1.0, which reintroduced a `global fetch is not defined` error, but installing `node-fetch` seems to have fixed that issue.

**Comment by jpignata** [comment] 2020-10-31 09:25
Can you share the call stack of the error you're receiving? Thanks!

**Comment by amhinson** [comment] 2020-10-31 14:24
@tqhoughton @bidva we just merged a fix that should address the issue you're having in Node. Can you try installing all Amplify packages you are using again with the `unstable` tag (i.e. `yarn add aws-amplify@unstable`) for testing? We are planning to do a release early next week to `latest` that will contain this fix. 

You will also need to set the `crypto` module with: `global.crypto = require('crypto')`. Be sure to set that before requiring any Amplify library in your code.

**Comment by Benzer1406** [comment] 2020-11-01 14:52
I'm running `"amazon-cognito-identity-js": "^4.5.2"` which uses `"crypto-js": "^3.3.0"` and get the same error. None of the solutions proposed have worked for me. Even downgrading `amazon-cognito-identity-js`to version `4.5.1`did not work. Any idea how to resolve the issue?

**Comment by amhinson** [comment] 2020-11-01 14:57
@Benzer1406 could you try using the `unstable` tag with `amazon-cognito-identity-js`? Also, could you share more about your app? Is it Node? If so, see my comment above regarding setting the `crypto` module to `global`.

**Comment by Benzer1406** [comment] 2020-11-01 15:01
@amhinson  I just tried using the `unstable` tag with `npm install amazon-cognito-identity-js@unstable` unfortunately it keeps throwing the same error. 

I'm using a serverless.com framework app, that uses the aws-nodejs-typescript template. So it is basically implementing the authentication in a nodejs app that I want to deploy in a serverless architecture (API Gateway, Lambda, ...).

I'm not sure if it's helpful, but I run into the error when invoking the lambda function locally, I haven't deployed the app to AWS yet, but I guess that shouldn't make a difference.

**Comment by amhinson** [comment] 2020-11-01 15:03
@Benzer1406 did you add this line at the top of your file before importing anything? 

`global.crypto = require('crypto')`

Note: this will only work with `unstable` at the moment.

**Comment by Benzer1406** [comment] 2020-11-01 15:08
@amhinson  Thanks for your help. Indeed, I had to install the unstable tag on the project root and the service root folder. And as you pointed out, I had not put that line at the very top of the files that imported `amazon-cognito-identity-js`. Thank you. Please keep me posted as soon as the final release is out.

**Comment by amhinson** [comment] 2020-11-01 15:10
@Benzer1406 ok great! We will be getting a release in the next day or two.

**Comment by tqhoughton** [comment] 2020-11-02 21:54
> @tqhoughton @bidva we just merged a fix that should address the issue you're having in Node. Can you try installing all Amplify packages you are using again with the `unstable` tag (i.e. `yarn add aws-amplify@unstable`) for testing? We are planning to do a release early next week to `latest` that will contain this fix.
> 
> You will also need to set the `crypto` module with: `global.crypto = require('crypto')`. Be sure to set that before requiring any Amplify library in your code.

I tried doing this, and I'm still getting the same error. This is my call stack:
```
Error: Native crypto module could not be used to get secure random number.
    at cryptoSecureRandomInt (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/utils/cryptoSecureRandomInt.js:43:9)
    at WordArray.random (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/utils/WordArray.js:50:56)
    at randomBytes (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:40:58)
    at AuthenticationHelper.generateRandomSmallA (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:101:21)
    at new AuthenticationHelper (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:56:29)
    at CognitoUser.authenticateUserDefaultAuth (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:264:32)
    at CognitoUser.authenticateUser (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:237:19)
    at /mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/@aws-amplify/auth/src/Auth.ts:571:9
    at new Promise (<anonymous>)
    at AuthClass.signInWithPassword (/mnt/c/Users/tqhou/OneDrive/Documents/Projects/Century/aws/node_modules/aws-amplify/node_modules/@aws-amplify/auth/src/Auth.ts:570:10)
```

I'm using node 12.13.1, running on an Ubuntu distribution accessed via bash.exe on my Windows 10 PC.

**Comment by amhinson** [comment] 2020-11-02 22:01
@tqhoughton Do you have `global.crypto = require('crypto')` at the top of your file before any imports?

**Comment by tqhoughton** [comment] 2020-11-02 22:07
> @tqhoughton Do you have `global.crypto = require('crypto')` at the top of your file before any imports?

🤦 I did not have that. Looks like it's working now with the unstable build.

**Comment by amhinson** [comment] 2020-11-02 22:08
Ok great! Here is an open issue you can track to see when it gets released to `latest`: https://github.com/aws-amplify/amplify-js/issues/7098

**Comment by ndk98z** [comment] 2020-11-04 08:49
Get the same error when use `CognitoUser.authenticateUser` method in the `amazon-cognito-identity-js` package (v4.5.3)
I build api server with NodeJs by Typescript
I tried add 
`global.crypto = require('crypto'), `
```
"resolutions": {
    "crypto-js": "3.1.9-1"
  }
```
Both of it not work, is there any work around

**Comment by Zulfin-Skyward** [comment] 2020-11-07 09:23
"amazon-cognito-identity-js": "^4.4.0",
"aws-amplify": "^3.3.7",
"crypto-js": "^3.2.1"

and adding global.crypto = require('crypto') on top of my main.ts worked for me

**Comment by arunmishra152** [comment] 2020-11-12 05:32
I was facing this issue when I was working with amazon cognito in nodejs. After so many hit and trial i found the solution, just change the amazon-cognito-identity-js version to :

**"amazon-cognito-identity-js": "^4.5.4-unstable.6"**

and now it is working for me, hope it will save your time and will work for you all who is facing this issue.

**Comment by amhinson** [comment] 2020-11-13 00:13
Update: `latest` is now up to date with the fix so `global.crypto = require('crypto')` is not required anymore 👍

**Comment by bunatl** [comment] 2021-04-12 20:41
My Auth.SignIn() works fine in my react app however when I want to test it with react-testing-library and Jest, using Auth.SignIn() in the test I am still getting  `Native crypto module could not be used to get secure random number.` error. Does anyone experience the same? What is the solution for this? Thanks!

**Comment by StephenA1** [comment] 2021-05-24 20:02
Seem to be having a similar issue when attempting to use amplify from AWS. It keeps failing on the "import { API, graphqlOperation } from "aws-amplify";" line with error "The package at "node_modules/@aws-amplify/auth/node_modules/crypto-js/core.js" attempted to import the Node standard library module "crypto"". I know that the crypto module is deprecated, but I';m not sure why AWS amplify is trying to access it. Any ideas?

**Comment by mogarick** [comment] 2021-07-12 16:08
@StephenA1 use the solution proposed by @ptrobert above:
https://github.com/aws-amplify/amplify-js/issues/4886#issuecomment-585588102
If your are using `npm` the you need to add this line to your `package.json` file `scripts` section in order to make the `resolutions` work:
``` json
"scripts": {
  "preinstall": "npx npm-force-resolutions",
}
```

**Comment by LeJ84** [comment] 2021-08-16 06:08
As @bunatl, signin works well in my react app but when i try to call it in a test file I get this error. Is there some news about it ?

**Comment by brockcor** [comment] 2021-12-20 19:05
Using `"@aws-sdk/client-cognito-identity-provider": "3.43.0"` and `"aws-amplify": "4.1.3"` and was facing the error: **Native crypto module could not be used to get secure random number.**

Finally got passed this by adding this to my package.json and then running `yarn`:
```
	"resolutions": {
		"crypto-js": "3.1.9-1",
		"amazon-cognito-identity-js": "4.5.4-unstable.6"
	},
```

**Comment by AaronDsilva97** [comment] 2022-07-26 18:04
I am using Nx monorepo for react native app, this is how i resolved this issue. Updated following code in metro.config.js
```
const { withNxMetro } = require('@nrwl/react-native');
const { getDefaultConfig } = require('metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return withNxMetro(
    {
      transformer: {
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: true,
          },
        }),
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
      },
      resolver: {
        assetExts: assetExts.filter((ext) => ext !== 'svg'),
        sourceExts: [...sourceExts, 'svg', 'cjs'],
        resolverMainFields: ['sbmodern', 'browser', 'main'],
        blockList: exclusionList([
        /\.\/dist\/.*/, 
        /#current-cloud-backend\/.*/]),
      },
    },
    {
      // Change this to true to see debugging info.
      // Useful if you have issues resolving modules
      debug: false,
      // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
      extensions: [],
      // the project root to start the metro server
      projectRoot: __dirname,
      // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
      watchFolders: [],
    }
  );
})();

```
