### ISSUE TITLE
 Here's a revised version of your text:  Bug in fetchAuthSession with the {forceRefresh:true} parameter causes an error.

### ISSUE THREAD

**Issue by nadernt** [aws-amplify/amplify-js#12749] opened 2023-12-23 06:08 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 723.77 MB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Chrome Canary: 122.0.6201.0
    Safari: 17.1
  npmPackages:
    @aws-amplify/ui-react: ^6.0.7 => 6.0.7 
    @aws-amplify/ui-react-internal:  undefined ()
    @creativebulma/bulma-divider: ^1.1.0 => 1.1.0 
    @fortawesome/fontawesome-svg-core: ^6.5.1 => 6.5.1 
    @fortawesome/react-fontawesome: ^0.2.0 => 0.2.0 
    @mapbox/mapbox-gl-style-spec:  14.0.0 
    @stripe/react-stripe-js: ^2.4.0 => 2.4.0 
    @stripe/stripe-js: ^2.2.2 => 2.2.2 
    @testing-library/jest-dom: ^6.1.5 => 6.1.5 
    @testing-library/react: ^14.1.2 => 14.1.2 
    @testing-library/user-event: ^14.5.1 => 14.5.1 
    aws-amplify: ^6.0.9 => 6.0.9 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    aws-sdk: ^2.1525.0 => 2.1525.0 
    axios: ^1.6.2 => 1.6.2 
    bulma: ^0.9.4 => 0.9.4 
    bulma-checkradio: ^2.1.3 => 2.1.3 
    compression-webpack-plugin: ^10.0.0 => 10.0.0 
    dompurify: ^3.0.6 => 3.0.6 
    firebase: ^10.7.1 => 10.7.1 
    firebase/analytics:  undefined ()
    firebase/app:  undefined ()
    firebase/app-check:  undefined ()
    firebase/auth:  undefined ()
    firebase/auth/cordova:  undefined ()
    firebase/compat:  undefined ()
    firebase/compat/analytics:  undefined ()
    firebase/compat/app:  undefined ()
    firebase/compat/app-check:  undefined ()
    firebase/compat/auth:  undefined ()
    firebase/compat/database:  undefined ()
    firebase/compat/firestore:  undefined ()
    firebase/compat/functions:  undefined ()
    firebase/compat/installations:  undefined ()
    firebase/compat/messaging:  undefined ()
    firebase/compat/performance:  undefined ()
    firebase/compat/remote-config:  undefined ()
    firebase/compat/storage:  undefined ()
    firebase/database:  undefined ()
    firebase/firestore:  undefined ()
    firebase/firestore/lite:  undefined ()
    firebase/functions:  undefined ()
    firebase/installations:  undefined ()
    firebase/messaging:  undefined ()
    firebase/messaging/sw:  undefined ()
    firebase/performance:  undefined ()
    firebase/remote-config:  undefined ()
    firebase/storage:  undefined ()
    history: ^5.3.0 => 5.3.0 
    intro.js-react: ^1.0.0 => 1.0.0 
    lodash: ^4.17.21 => 4.17.21 
    mapbox-gl: ^3.0.1 => 3.0.1 
    minisearch: ^6.3.0 => 6.3.0 
    moment: ^2.29.4 => 2.29.4 
    node-sass: ^9.0.0 => 9.0.0 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-ga: ^3.3.1 => 3.3.1 
    react-ga4: ^2.1.0 => 2.1.0 
    react-helmet-async: ^2.0.4 => 2.0.4 
    react-joyride: ^2.7.1 => 2.7.1 
    react-responsive: ^9.0.2 => 9.0.2 
    react-router-dom: ^6.21.1 => 6.21.1 
    react-scripts: ^5.0.1 => 5.0.1 
    react-tooltip: ^5.25.0 => 5.25.0 
    sass: ^1.69.5 => 1.69.5 
    source-map-explorer: ^2.5.3 => 2.5.3 
    sweetalert: ^2.1.2 => 2.1.2 
    sweetalert2: ^11.10.1 => 11.10.1 
    sweetalert2-react-content: ^5.0.7 => 5.0.7 
    swiper: ^11.0.5 => 11.0.5 
    util: ^0.12.5 => 0.12.5 
    validator: ^13.11.0 => 13.11.0 
    web-vitals: ^3.5.0 => 3.5.0 
  npmGlobalPackages:
    @aws-amplify/cli: 12.8.2
    corepack: 0.20.0
    nodemon: 3.0.2
    npm-check-updates: 16.14.12
    npm: 10.2.5
    serverless: 3.36.0
    yarn: 1.22.19


```

</details>

### Describe the bug

In version 5 of Amplify Authentication, I passed a parameter {bypassCache: true} to load user information and ignore the cache. The new Amplify version suggests using the fetchAuthSession function. This function works correctly as long as I don't pass the {forceRefresh:true} parameter. When I pass this parameter, it shows the error below and logs out, even though I am already logged in with a valid user. 

### Expected behavior

When you add this parameter, it must ignore the logged-in user information and refresh the user information from the server without logging in or out. This helps clients, after updating their attributes such as name, phone, and address without logging out, to see the latest updates on their account.

### Reproduction steps

1. Login and fetch the user with fetchAuthSession() function ( I have integrated auth with facebook and google)
2. Add this parameter {forceRefresh:true} to fetchAuthSession like this fetchAuthSession({forceRefresh:true}) and see the issue.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![image](https://github.com/aws-amplify/amplify-js/assets/904482/c9bc4773-8aa8-4b37-897b-ef9b29142132)

The recent changes in Amplify auth are disappointing because they make a simple process more complicated with fewer values, and Authentication is a security pillar. Imagine having 100 clients with websites built by Amplify; then, for just a simple update, I need to rewrite the entire authentication system for all clients. Please adopt and thoroughly test tools within your own company before releasing them.

**Comment by israx** [comment] 2023-12-26 17:39
hello @nadernt . Sorry for any inconvenience using the amplify library. Can you share some code snippets that can help us reproduce the same issue?

**Comment by nadernt** [comment] 2023-12-27 01:38
Hi, thanks for the response. This is the sample code I've provided. The main code is more extensive, but here I've made it as short as possible. The updateUserAttributes function has been working without any issues for three years. I was able to change the user attributes and immediately see the changes after reloading the page. In version 6, it does change the attributes, but after calling fetchAuthSession with forceRefresh: true, it shows the error mentioned before.

The "/to-custom-path" is not working in recent version 6 of Amplify either. Redirection is crucial for developers. Imagine a user is interested in an item and wants to pick it. Then you ask them to log in, and redirecting to the same page is important (pop-up has its own issues). The customOAuthState doesn't happen anymore in the HUB events, which is important for redirecting to the original path after the login and redirection process.

```
import {
  fetchAuthSession,
  updateUserAttributes,
  signInWithRedirect,
} from "aws-amplify/auth";

export default function Profile({ api }) {
  const saveUserAttributes = async () => {
    try {
      const done = await updateUserAttributes({
        userAttributes: {
          name: "New Name",
          family_name: "Another Name",
          phone_number: "+61234234234",
        },
      });
      console.log(done);
      await fetchAuthSession({ forceRefresh: true });
      window.location.reload();
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <button
        onClick={() => {
          saveUserAttributes();
        }}
      >
        Change attributes
      </button>
      <button
        onClick={() => {
          signInWithRedirect({
            provider: "Facebook",
            customState: "/to-custom-path",
          });
        }}
      >
        Facebook
      </button>
      <button
        onClick={() => {
          signInWithRedirect({
            provider: "Google",
            customState: "/to-custom-path",
          });
        }}
      >
        Google
      </button>
    </>
  );
}
```

```
import { createContext, useState, useEffect} from "react";
import { signOut, fetchAuthSession } from "aws-amplify/auth";
import { Hub } from "aws-amplify/utils";

export const UserContext = createContext();

const UserProvider = ({ children }) => {
  const [userSession, setUserSession] = useState({});
  const [userSessionLoading, setUserSessionLoading] = useState(true);
  useEffect(() => {

    getSession();
    Hub.listen("auth", (data) => {
      const { payload } = data;
      if (payload.event === "signedIn") {
        getSession();
        console.log("a user has signed in!");
      }
      if (payload.event === "signedOut" || payload.event === "oAuthSignOut") {
        console.log("a user has signed out!");
      }
      if (payload.event === "customOAuthState") {
        window.location.href = decodeURIComponent(payload.data);
      }
    });
  }, []);

  function generateImage(letter) {
    const firstLetter = letter.charAt(0).toUpperCase();
    const canvas = document.createElement("canvas");
    const context = canvas.getContext("2d");

    // Set canvas size
    canvas.width = 96;
    canvas.height = 96;

    // Draw background (optional)
    context.fillStyle = "#3a86ff";
    context.fillRect(0, 0, canvas.width, canvas.height);

    // Draw text
    context.font = "bold 50px Arial";
    context.fillStyle = "white";
    context.textAlign = "center";
    context.textBaseline = "middle";
    context.fillText(firstLetter, canvas.width / 2, canvas.height / 2);

    // Convert the canvas to a data URL
    return canvas.toDataURL("image/png");
  }

  const retrieveProfilePicture = (user) => {
    const providerType =
      user.tokens.idToken.payload.identities[0].providerType.toLowerCase();
    let pic;
    if (providerType === "facebook") {
      pic = JSON.parse(pic).data.url;
    } else {
      pic = user.tokens.idToken.payload.picture;
    }

    if (pic) {
      return pic;
    } else {
      return generateImage(user.tokens.idToken.payload.name);
    }
  };
  const getSession = async () => {
    setUserSessionLoading(true);
    await fetchAuthSession()
      .then((user) => {
        const payload = user.tokens.idToken.payload;
        let profilePictureUrl = retrieveProfilePicture(user);
        setUserSession({
          logged_in: true,
          jwtToken: user.tokens?.idToken?.toString(),
          sub: payload.sub,
          email: payload.email,
          name: payload.name,
          family_name: payload.family_name,
          phone_number: payload.phone_number,
          address: payload.address,
          profile_picture: profilePictureUrl,
        });
        setUserSessionLoading(false);
      })
      .catch((err) => {
        //console.log(err);
        setUserSession({});
        setUserSessionLoading(false);
        return null;
      });
  };

  const SignOut = async () => {
    try {
      //Force to re-initiate the user location recognition at the running of app.
      if (typeof Storage !== "undefined") {
        const cntr = localStorage.getItem("user_country");
        if (cntr !== null) localStorage.removeItem("user_country");
      }
      setUserSession({});
      await signOut();
    } catch (error) {
      console.log("error signing out: ", error);
    }
  };

  const redirectToUrl = (redirectPath) => {
    redirect_path.current = redirectPath;
  };
  const setBasketItemsNumber = (items_no) => {
    setNumberOfBasketItems(items_no);
  };
  return (
    <UserContext.Provider
      value={{
        userSession,
        userSessionLoading,
        setBasketItemsNumber,
        numberOfBasketItems,
        SignOut,
        redirectToUrl,
      }}
    >
      {children}
    </UserContext.Provider>
  );
};

export default UserProvider;
```


![Untitled 1](https://github.com/aws-amplify/amplify-js/assets/904482/eca5c4ea-cb7a-401a-97e6-ec50a90a4c4f)
![Untitled 2](https://github.com/aws-amplify/amplify-js/assets/904482/85a2cd5e-1584-4fda-a115-d43cc5417bf6)
![Untitled 3](https://github.com/aws-amplify/amplify-js/assets/904482/550ab877-1888-4cb6-baee-883784dc9253)
![Untitled 4](https://github.com/aws-amplify/amplify-js/assets/904482/71de0dc0-c1b7-4849-9ab9-88897202ed3f)

**Comment by israx** [comment] 2023-12-29 14:56
hello @nadernt . So sorry for the delay. Thank you for info attached. I was able to reproduce this bug. It happens in the following circumstances:

Authenticate with a social provider -> update user attributes -> call `fetchAuthSession` with force refresh. 

I'll mark this as a bug. Thank you so much for bringing this up. In the mean time. You can call `fetchUserAttributes` to get the updated attributes from your userpool.

**Comment by israx** [comment] 2023-12-29 15:21
Amplify dispatches the `customOAuthState` hub event, which includes the `customState` passed in the `signInWithRedirect` API

**Comment by israx** [comment] 2023-12-29 17:38
hey @nadernt. I was able to dig into the root cause of the issue.  `fetchAuthSession` will throw an error when it is not able to find either an `id_token`, `access_token` or `refresh_token`. In your case, it is not able to find a `refresh_token`

When using oauth flows, you can use a `code grant` or `implicit grant` flow. 

When using `code grant` flow, the library exchanges the `code` param return from Hosted UI and calls the `POST oauth2/token` [endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html#post-token) to exchange that code by tokens. In the response it will include the `refresh_token`. However if you use a `implicit grant` flow, then Hosted UI will return only `access_token` and `id_token`. For more info check this [post](https://docs.aws.amazon.com/cognito/latest/developerguide/federation-endpoints-oauth-grants.html)

saying that, we still have a bug as the error thrown is not meaning full. To troubleshoot, you can change your oauth configuration to use an `code grant` oauth flow. 

```
Amplify.configure({
   Auth: {
    Cognito: {
      ...cognitoConfig,
      loginWith: {
        oauth: {
          ...oauthConfig,
          responseType: "code",
        },
      },
    },
  },
})

```

**Comment by nadernt** [comment] 2023-12-30 04:30
Hi @israx, thanks for the response. I will wait until this problem gets fixed because I manage the user, including Cognito, under a context code, and getting attributes doesn't solve the issue of the old token and attributes from the cache. I understand your point about ```code grant```, but I prefer to wait.

**Comment by israx** [comment] 2024-01-02 14:00
Hey @nadernt . I assume you used to manage your user context before by using the `Auth.currentAuthenticatedUser` with the `bypassCache` option. This would call the underlying `GetUser` Cognito API and return the updated attributes.  However, `fetchAuthSession` doesn't call that API under the hood. It calls `InitiateAuth`, which does require a `refreshToken` to refresh the actual session. 

So using an `implicit grant` oauth flow will not generate this `refreshToken`. Hence, making it not possible for the library to call to the underlying API to get the new session. However, what Amplify can do is to improve the error handling, so instead of throwing `UserUnAuthenticatedException`, it can throw something meaningful that can help to troubleshoot.

Saying that, the upcoming fix will still result in an error as the library does depend on the `refreshToken` to call the underling API. 

The easiest way to workaround this is by using a `code grant` oauth flow or also creating your own `CognitoUser` context by calling the `fetchUserAttributes`, which will call the `GetUser` API under the hood.

**Comment by cwomack** [comment] 2024-01-02 14:06
New duplicate issue opened with additional screenshots/context: #12778

**Comment by gokaten-token** [comment] 2024-01-03 03:11
@cwomack 
Thanks for your help and the [temp solution](https://github.com/aws-amplify/amplify-js/issues/12749#issuecomment-1872238799) do fix the problem when calling `fetchAuthSession({ forceRefresh: true }))` when refresh token not expired .

However when the refresh token expired and call `fetchAuthSession()` will cause the following error.

```
fetch.ts:9     POST https://cognito-idp.ap-northeast-1.amazonaws.com/ 400 (Bad Request)
```

**Comment by israx** [comment] 2024-01-03 13:29
hello @gokaten-token . Can you share the request payload and response from that error ?

**Comment by gokaten-token** [comment] 2024-01-04 01:29
> hello @gokaten-token . Can you share the request payload and response from that error ?

Sure.
Here is the response.

```
{"__type":"NotAuthorizedException","message":"Refresh Token has expired"}
```
I understand now that this is supposed to be an error.


Another problem is that I did not get the console output from the following code inside the `Hub.listen`

```typescript
case "tokenRefresh_failure":
          console.log("failure while refreshing auth tokens.");
          break;
```

Is this `tokenRefresh_failure` event supposed to be fired when `fetchAuthSession()` failed due to `Refresh Token has expired`?

**Comment by israx** [comment] 2024-01-04 13:35
Hello @gokaten-token . It is expected that you get an exception when the `refresh_token` has expired. 

You would need to re-authenticate as the `refresh_token` is used to refresh `access` and `id` tokens. However, you can increase the expire time by accessing to your user pool via de Cognito [console](https://console.aws.amazon.com/cognito/home), and then going to your `clientId` .

Yes. I believe the `tokenRefresh_failure` event should be faired. I'll double check and see if there is an issue. Thanks for brining that up.

**Comment by israx** [comment] 2024-01-10 13:28
The library is not able to refresh tokens via the `oauth2/token` endpoint as mentioned above because it requires a `refresh_token` in the request. Thus, we encourage the usage of the `code` oauth flow as suggested on [this](https://github.com/aws-amplify/amplify-js/issues/12749#issuecomment-1872238799) comment.

We currently merged some changes into the library which includes a better error handling when a `refresh_token` is not present in storage. We also fix the issue where a `tokenRefresh_failure` event was not dispatched when the `refresh_token` was expired. 

These changes are currently in the `unstable` version of the library and can be tested.

**Comment by israx** [comment] 2024-01-12 14:58
Hello @nadernt , @gokaten-token . 

The latest [release](https://www.npmjs.com/package/aws-amplify) included a better error handling when the `fetchAuthSession` API is unable to refresh the session. We also added [refreshing sessions](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#refreshing-sessions) and [refreshing sessions with social providers](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#refreshing-sessions-with-social-providers) documentation to help users to manage sessions.

Let us know if that solves your concerns.

**Comment by cwomack** [comment] 2024-01-23 17:36
We'll close this issue now that the release [referenced above](https://github.com/aws-amplify/amplify-js/issues/12749#issuecomment-1889437365) included the error handling improvements and documentation updates related to managing sessions.  If anyone experiences further blockers with this, please feel free to comment back or open a new issue. Thanks!

**Closed by cwomack** 2024-01-23 17:36 UTC
Labels: bug, Auth

**Comment by JustinHaut** [comment] 2024-04-30 00:22
@cwomack @israx any chance you could keep v5 alive for a while? refresh tokens were smooth... particularly if we wanted to keep resources behind initial authentication but not have to have the user re-authenticate. 🫠

**Comment by realtebo** [comment] 2024-07-29 09:02
migrating from v5 to v6 we lost refresh token. but our app need this to call oauth/revoke.

How can we solve!?!? we cannot rewrite an entire auth flow only because you 'lost' an attribute.
there is NO DOCUMENTED MIGRATION PATH. and is this bad and ugly from programmer perspective

**Comment by nadernt** [comment] 2024-07-29 09:51
> migrating from v5 to v6 we lost refresh token. but our app need this to call oauth/revoke.
> 
> How can we solve!?!? we cannot rewrite an entire auth flow only because you 'lost' an attribute. there is NO DOCUMENTED MIGRATION PATH. and is this bad and ugly from programmer perspective

I am really disappointed. I raised this bug months ago. In addition to the refresh token issue, the redirect doesn't work either. Redirect functionality is crucial for client flow. Despite claims that it's working, I tested it with sample codes in the new version, and it still doesn't work. Amplify authentication in AWS has gone from being one of my favorites to a major bottleneck in the frontend. I'm at a loss for how to address this with the team further. This is not just a complaint or a bug; the product simply isn't working. The events are not firing. I have apps using Google's authentication from nearly a decade ago, and their authentication still works flawlessly.

**Comment by ChartistDev** [comment] 2024-09-25 12:53
I am facing a similar issue @nadernt  in my own react app. I am able to signin/signup. But once I reload the page fetchAuthSession is giving me undefined values and as per my code I am auto signing out.. The strange is this doesn't happen always . After sometime if I do the same mechanism, I get a message from hub that a new token has been processed and I'm allowed to retain the session. This is so weird.. Never happened with V5

**Comment by nadernt** [comment] 2024-09-27 01:17
Nearly a year after raising this issue, it's clear that others are still reporting similar problems, as seen in #13751 and #13638 and #12716  and various related issues around the hub. My software stack heavily relies on a basic logging frontend, and I've been dealing with the ongoing stress of this Amplify bug for a long time.

**Comment by Samaritan1011001** [comment] 2024-09-27 22:35
@nadernt I was analyzing the issue. Have you looked into using [fetchUserAttributes](https://docs.amplify.aws/gen1/react/build-a-backend/auth/manage-user-profile/#retrieve-user-attributes) instead of `fetchAuthSession` to get the `userAttributes`? It might be a better way to get those details. In my testing it updated the attributes successfully via `updateUserAttributes` API and I did not have to call `fetchAuthSession` forceRefresh.
