### ISSUE TITLE
uuid@3.4.0: Please upgrade  to version 7 or higher

### ISSUE THREAD

**Issue by alditis** [aws-amplify/amplify-js#12504] opened 2023-11-03 06:07 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Analytics, GraphQL API, DataStore, Push Notifications, PubSub, Predictions

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
    Memory: 2.07 GB / 5.67 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Brave Browser: 118.1.59.120
    Chrome: 118.0.5993.88
  npmPackages:
    @aws-amplify/ui-vue: ^3.1.18 => 3.1.29 
    @aws-sdk/signature-v4-crt: ^3.78.0 => 3.438.0 
    @aws-sdk/util-utf8-browser: ^3.259.0 => 3.259.0 (3.6.1, 3.186.0)
    @babel/core: ^7.12.16 => 7.23.2 
    @babel/eslint-parser: ^7.12.16 => 7.22.15 
    @maplibre/maplibre-gl-style-spec:  17.0.1 
    @maptiler/geocoder: ^1.1.0 => 1.1.0 
    @mdi/font: ^5.9.55 => 5.9.55 
    @quasar/extras: ^1.15.1 => 1.16.7 
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-eslint: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-router: ~5.0.0 => 5.0.8 
    @vue/cli-service: ~5.0.0 => 5.0.8 
    @vue/compiler-sfc: ^3.1.0-0 => 3.3.7 (2.7.15)
    aws-amplify: ^5.2.6 => 5.3.11 
    eslint: ^7.32.0 => 7.32.0 
    eslint-plugin-vue: ^8.0.3 => 8.7.1 
    exifreader: ^4.5.1 => 4.16.0 
    graphql: ^14.0.0 => 14.7.0 (15.8.0)
    maplibre-gl: ^2.4.0 => 2.4.0 ()
    moment: ^2.29.4 => 2.29.4 
    pinia: ^2.1.3 => 2.1.7 
    pinia-plugin-persistedstate: ^3.1.0 => 3.2.0 
    quasar: ^2.7.7 => 2.13.0 
    roboto-fontface: * => 0.10.0 
    sass: ~1.32.12 => 1.32.13 
    sass-loader: ^10.0.0 => 10.4.1 
    uuid: ^8.3.2 => 8.3.2 (3.4.0)
    vue: ^3.2.13 => 3.3.7 (2.7.15)
    vue-cli-plugin-quasar: ~5.0.1 => 5.0.2 
    vue-router: ^4.0.13 => 4.2.5 
    vue-stack-grid: ^1.2.2 => 1.2.2 
    vue3-lazyload: ^0.2.5-beta => 0.2.5-beta 
    webfontloader: ^1.0.0 => 1.6.28 
    zipson: ^0.2.12 => 0.2.12 
  npmGlobalPackages:
    corepack: 0.18.0
    npm: 9.6.7

```

</details>

### Describe the bug

I got warning report about uuid on aws-amplify dependencies.
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

### Expected behavior

Avoid warnings regarding deprecated uuid.

### Reproduction steps

1. After install all dependecies with: 
`npm i`

2. I got this warning report:
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
3. I then ran this command to inspect uuid@3.4.0:
`npm ls uuid@3.4.0`

4. I got this report:
```
└─┬ aws-amplify@5.3.11
  ├─┬ @aws-amplify/analytics@6.5.5
  │ ├─┬ @aws-sdk/client-firehose@3.6.1
  │ │ └─┬ @aws-sdk/middleware-retry@3.6.1
  │ │   └── uuid@3.4.0
  │ └── uuid@3.4.0
  ├─┬ @aws-amplify/api@5.4.5
  │ └─┬ @aws-amplify/api-graphql@3.4.11
  │   └── uuid@3.4.0
  ├─┬ @aws-amplify/datastore@4.7.5
  │ └── uuid@3.4.0
  ├─┬ @aws-amplify/notifications@1.6.5
  │ └── uuid@3.4.0
  ├─┬ @aws-amplify/predictions@5.5.5
  │ ├─┬ @aws-sdk/client-comprehend@3.6.1
  │ │ └── uuid@3.4.0
  │ ├─┬ @aws-sdk/client-translate@3.6.1
  │ │ └── uuid@3.4.0
  │ └── uuid@3.4.0
  └─┬ @aws-amplify/pubsub@5.5.5
    └── uuid@3.4.0
```

5. This report shows the packages that depend on uuid@3.4.0 and that should be updated.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by bcs-gbl** [comment] 2023-11-03 13:12
+1

**Comment by nadetastic** [comment] 2023-11-06 15:52
Related #8464

**Comment by cwomack** [comment] 2023-11-06 20:11
@alditis, thank you for opening this issue.  We'll consolidate this into the related #8464, as the issues appear to have the same root cause.  As stated in a [comment within that issue](https://github.com/aws-amplify/amplify-js/issues/8464#issuecomment-1749580735), we're moving towards minimizing our third party dependencies heading into the next major version of Amplify.  

Feel free to add any additional context, reactions, or comments to the other issue! We'll track the support for implementing the feature/fix there for v5 of Amplify.

**Closed by cwomack** 2023-11-06 20:11 UTC
Labels: feature-request, Core

**Comment by alaauddin** [comment] 2024-05-13 05:33
+1
