### ISSUE TITLE
DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined:

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7114] opened 2020-11-04 02:56 UTC
**Describe the bug**
DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined:

**To Reproduce**
Generated simple DataStore model with Schema:

type exhibitorStatus @model {
  id: ID!
  exhibitorId : String!
  status: String!
  time: AWSDateTime!
}

called: 
 amplify codegen models
amplify add api
amplify update api
amplify pull

Graphql schema:

/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateExhibitorStatus = /* GraphQL */ `
  subscription OnCreateExhibitorStatus {
    onCreateExhibitorStatus {
      id
      exhibitorId
      status
      time
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateExhibitorStatus = /* GraphQL */ `
  subscription OnUpdateExhibitorStatus {
    onUpdateExhibitorStatus {
      id
      exhibitorId
      status
      time
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteExhibitorStatus = /* GraphQL */ `
  subscription OnDeleteExhibitorStatus {
    onDeleteExhibitorStatus {
      id
      exhibitorId
      status
      time
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;

getting error:
ConsoleLogger.ts:99 [WARN] 46:50.495 DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'onUpdateexhibitorStatus' in type 'Subscription' is undefined @ 'onUpdateexhibitorStatus'"}]}

Also this error seems to popup on random onUpdate, one time it's onUpdateExhibitorStatus, another time onCreateExhibitorStatus.

I also have several more questions:
1. I need to load latest status update per exhibitor Id. Am not sure how this pagination thing works but if i do:

const status = await DataStore.query(exhibitorStatus, c => c.exhibitorId("eq",.exhibitorId),
    {sort: s => s.time(SortDirection.DESCENDING)});

am i guaranteed to get the absolute latest updates? Is this a scanForwardIndex=false query? if not, isn't this going to be slow? 

2. In the case of the device on which my web app is running goes offline for more than 5 minutes (> Keep alive connection), appsync subscription has a timeout disconnect. Is the same thing going to happen if i use Datastore rather than graphql directly? if so, how do i have datastore reconnect the subscription? Or for any other reason that the websocket/appsync connection close, have datastore restart the connection?

Thanks!!

**Comment by mchitson** [comment] 2020-11-04 12:35
also my package.json:

"dependencies": {
        "@aws-amplify/datastore": "^2.7.2",
        "@testing-library/jest-dom": "^5.11.4",
        "@testing-library/react": "^11.1.0",
        "@testing-library/user-event": "^12.1.10",
        "aws-amplify": "^3.3.7",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "react-scripts": "4.0.0",
        "web-vitals": "^0.2.4"
    },

**Comment by mchitson** [comment] 2020-11-04 17:48
could you get back to me as soon as possible - i am trying to get datastore up and running for an imminent project deadline. thank you!!

**Comment by wei** [comment] 2020-11-05 04:12
@mchitson Your error may be due to the casing of the Schema model. Please try using `ExhibitorStatus` instead of `exhibitorStatus` in the schema. 

If that does not work, please provide a minimal reproducible example repo so I can better assist you.

**Comment by mchitson** [comment] 2020-11-05 17:27
Hi

Thanks now the error is gone (who would have thought!). The only issue is now when I do mutations nothing goes to the DB. I am logging in via Cognito and cognito has AuthRole to access the appsync end point (app sync has IAM auth).

**Comment by mchitson** [comment] 2020-11-05 17:56
Hi it works now - I had to add aws_project_region as well to the aws config (I had to modify it to include cognito stuff). Thanks!!

Could you also answer my other questions? Many thanks!

**Comment by wei** [comment] 2020-11-05 18:06
Great, you have to also setup conflict resolution for it to start syncing to appsync in the cloud which sounds like you've already done.

RE your questions: 
1. If you want maximum performance, I would create a new model that only holds the latest status per exhibit and update it anytime you insert into `ExhibitorStatus`
1. I don't know the answer to that

As the original issue has been resolved, please close this ticket and create a discussions on repo's discussions tab or a new issue so others with expertise can identify it easier and help you out.

**Closed** 2020-11-05 19:23 UTC
Labels: DataStore, to-be-reproduced
