### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@aws-sdk%2fclient-lex-runtime-service - Not found npm ERR! 404  npm ERR! 404  '@aws-sdk/client-lex-runtime-service@3.186.3' is not in this registry.

### ISSUE THREAD

**Issue by blessme247** [aws-amplify/amplify-js#11626] opened 2023-07-14 21:24 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line


System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 1.16 GB / 7.88 GB
  Binaries:
    Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @types/react: ^18.2.14 => 18.2.15
    @types/react-dom: ^18.2.6 => 18.2.7
    @vitejs/plugin-react: ^4.0.1 => 4.0.3
    aws-sdk: ^2.1415.0 => 2.1415.0
    axios: ^1.4.0 => 1.4.0
    eslint: ^8.44.0 => 8.45.0
    eslint-plugin-react: ^7.32.2 => 7.32.2
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0
    eslint-plugin-react-refresh: ^0.4.1 => 0.4.3
    formik: ^2.4.2 => 2.4.2
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-router-dom: ^6.14.1 => 6.14.1
    sass: ^1.63.6 => 1.63.6
    vite: ^4.4.0 => 4.4.4
    yup: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    @aws-amplify/cli: 12.1.1
    npm-check-updates: 16.10.13


```

</details>

### Describe the bug

some essential modules that are required are not found in the npmjs registry

### Expected behavior

it is expected to install the dependencies

### Reproduction steps

1. install - npm install aws-amplify

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment] 2023-07-15 01:18
Hello, @blessme247 👋 .  I believe this was tied to an outage that NPM experienced earlier today and should be fixed at this point.  Can you try again and see if the issue is resolved?

**Comment by cwomack** [comment] 2023-07-19 13:20
@blessme247, I'll close this issue out because the `@aws-sdk/client-lex-runtime-service` is a [valid package](https://www.npmjs.com/package/@aws-sdk/client-lex-runtime-service/v/3.186.3) and shouldn't give you further issues if you try again.  

This still seems to be related to that [NPM outage](https://status.npmjs.org/incidents/jglnklhspsnm) on 07/14, but feel free to comment back if you're still experiencing problems and we can reopen the issue.  Thanks!

**Closed by cwomack** 2023-07-19 13:20 UTC
Labels: investigating, Core, pending-response
