### ISSUE TITLE
React Native: `authuser` Role Does Not Seem to Persist

### ISSUE THREAD

**Issue by ZebGirouard** [aws-amplify/amplify-js#1739] opened 2018-09-24 17:30 UTC
**Describe the bug**

After signing up or logging in, I can run `API.get` and `API.post` with no issues.  However, when I try to refresh the app, I get a 403 error when running an `API.get` which claims I am in the `_unauth_` role (i.e. `assumed-role` is the `_unauth_` group, not the `_auth_` one).

**To Reproduce**
1. Log in with AWS
2. Run `API.get` to get user info
3. See user info
4. Hard refresh (cmd-r) in iOS simulator
5. `API.get` returns 403 mentioned above

**Expected behavior**
User state should persist after refresh, since it is held in `AsyncStorage`.  In fact, when I run `Auth.currentSession()` or `Auth.currentAuthenticatedUser()` I get a fully authenticated session and user, respectively.

**Actual behavior**

Despite calling `API.get` after receiving this indication of an authenticated user, I get an `assumed-role` of `_unauth_`.

**Smartphone (please complete the following information):**
 - Device: iOS Simulator

**Additional Context**

This API Gateway endpoint requires a user to be authenticated to hit it.

The truly confusing thing here is that it has no problem running `API.get` or even `API.post` through the API Gateway right after sign up or log in event.  Maybe I just need help explaining the "magic" behind "knowing that a user is logged in".  I thought it was just that Amplify could grab a user session from `AsyncStorage`, but there seems to be more to it than that.

Also fully open to the possibility that this is an issue with my API Gateway (I have only done the default configuration with AWS Mobile CLI).

Here are my Amplify API and Auth versions:

```
    "@aws-amplify/api": {
      "version": "1.0.15-unstable.2",

...

    "@aws-amplify/auth": {
      "version": "1.2.4-unstable.2",
```

Note that I'm using the unstable versions at the moment.  That's because of issue #1646 , and the fix @elorzafe pushed into latest version.

**Comment by elorzafe** [comment] 2018-10-04 23:41
I tried to reproduce the error but is working for me. 

I tried the following code on my App.js file (I used create-react-native-app)
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import Amplify, { API } from 'aws-amplify';
import awsConfig from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react-native';

Amplify.configure(awsConfig);

class App extends React.Component {

  callApi1 = async () => {
    API.get('apic26d80bb', '/items')
    .then(data => console.warn('data:', data))
    .catch(err => console.warn('error from api ', err))
  }
  callApi2 = async () => {
    API.get('api80af4d46', '/items')
    .then(data => console.warn('data:', data))
    .catch(err => console.warn('error from api ', err))
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Button title="callapi1" onPress={this.callApi1}></Button>
        <Button title="callapi2" onPress={this.callApi2}></Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default withAuthenticator(App, true);
```

callApi1 is invoking an api that only allows access for authenticated users, callApi2 allows unauth and auth users. Both works fine after refreshing the app several times.

**Comment by ZebGirouard** [comment] 2018-10-08 16:49
Thank you @elorzafe .  It seems that this is fixed on my app as well, after `npm i` changed my versions to

```
    "@aws-amplify/api": {
      "version": "1.0.15",

...

    "@aws-amplify/auth": {
      "version": "1.2.4",
```

i.e. not "unstable" versions.  Thanks for looking into this.

**Comment by jordanranz** [comment] 2019-06-03 21:46
Closing as the issue seems to be fixed.

**Closed by jordanranz** 2019-06-03 21:46 UTC
Labels: API, React Native
