### ISSUE TITLE
After I upload a picture it tells me that region is missing

### ISSUE THREAD

**Issue by Scorles** [aws-amplify/amplify-js#11157] opened 2023-03-30 00:09 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.12.1

### Amplify CLI Version

v11.0.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None.

### Describe the bug

![error in recoknition demo](https://user-images.githubusercontent.com/129342509/228693194-f2b0a0f4-15e7-4349-b88c-e7969e96791c.PNG)

### Expected behavior

I expected the image to upload and I would get back the text of the image scan by Recoknition AI

### Reproduction steps

The only code that I have is from the docs and a tutorial 

-Index.JS
```js
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import { Amplify } from 'aws-amplify';
import {
  Predictions,
  AmazonAIPredictionsProvider
} from '@aws-amplify/predictions';
import awsconfig from './aws-exports';

Predictions.configure({ region: "us-east-1" });
Amplify.configure(awsconfig);
console.log(awsconfig);
Amplify.addPluggable(new AmazonAIPredictionsProvider());

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

- APP.JS
```js
import './App.css';
import React, {useState} from 'react';

import { Predictions } from 'aws-amplify'

function App() {

    const [response, setResponse] = useState("Upload Pic")
    async function identify(event){
      setResponse("loading...")
      const {target: {files}} = event
      const file = files[0]
      const data = await Predictions.identify({
        labels: { source: {file}, format: "PLAIN"}
      })
      setResponse(data.text.fullText)
    }
    return (
      <div className="App">
        <h3>Text</h3>
        <input 
          type="file" onChange={identify}
          />
        <p>{response}</p>
      </div>
    );
  }

export default App;
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by tannerabread** [comment] 2023-03-30 13:07
Hi @Scorles, can you tell us which tutorial you were following? I don't think we recommend configuring Predictions by itself in newer versions of Amplify and instead do [all of the configuring through Amplify.configure](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/js/#configure-the-frontend)

I'm thinking this line `Predictions.configure({ region: "us-east-1" });` may be the problem. If commenting/deleting that doesn't work, can you also provide your aws-exports file

**Comment by tannerabread** [comment] 2023-03-30 19:23
Interestingly enough I was trying this category on React Native earlier today and noticed that on one project, I was required to do `Predictions.addPluggable` instead of `Amplify.addPluggable`

Can you try that out and see if it works?

**Comment by Scorles** [comment] 2023-03-30 19:34
RegionConfig.ts:34 Uncaught (in promise) Error: Region is missing
    at resolveRegionConfig (RegionConfig.ts:34:1)
    at new RekognitionClient (RekognitionClient.ts:393:1)
    at AmazonAIIdentifyPredictionsProvider.<anonymous> (AmazonAIIdentifyPredictionsProvider.ts:240:1)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:1)
    at fulfilled (tslib.es6.js:71:1)
    
   I tried:
   import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import { Amplify } from 'aws-amplify';
import {
  Predictions,
  AmazonAIPredictionsProvider
} from '@aws-amplify/predictions';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
Predictions.addPluggable(new AmazonAIPredictionsProvider());

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

same error.

**Comment by Scorles** [comment] 2023-04-05 00:04
Hello @tannerabread, if it help this error happened to me after I resolve a previous bug https://github.com/aws-amplify/amplify-cli/issues/12159.

**Comment by tannerabread** [comment] 2023-04-05 16:30
Hi @Scorles I am glad you brought up that CLI issue because I was trying to reproduce and ran into the same thing.

After getting passed that I worked backwards for your error and I believe the `region is missing` problem comes from the following line:
```js
const data = await Predictions.identify({
  labels: { source: { file }, format: "PLAIN" },
});
```
Which should be changed to:
```js
const data = await Predictions.identify({
  text: { source: { file }, format: "PLAIN" },
});
```


After that I started running into permissions errors for the POST requests which will require some modifications to the auth category you set up earlier. To fix that I ran `amplify update auth` and then followed these steps:
```console
Please note that certain attributes may not be overwritten if you choose to use defaults settings.
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Si
gn-In, connected with AWS IAM controls (Enables per-user Storage features for images or 
other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control vi
a AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry a
t registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
```
Run an `amplify push` again after this and try your app again and it should work.

**Comment by Scorles** [comment] 2023-04-05 17:54
Thank you, it solved the missing region error.

I tried:

 Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM co
ntrols (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
✅ Successfully updated auth resource textdemotwo4bab8705 locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

✅ Successfully updated resource update locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


amplify push: was succesfull |

but when I run the app now this appears 

Failed to load resource: the server responded with a status of 400 (Bad Request)
Aws_json1_1.ts:3037 Uncaught (in promise) AccessDeniedException: User: arn:aws:sts::145130901372:assumed-role/amplify-textdemotwo-dev-133603-unauthRole/CognitoIdentityCredentials is not authorized to perform: rekognition:DetectText because no identity-based policy allows the rekognition:DetectText action
    at http://localhost:3000/static/js/bundle.js:38131:62
    at step (http://localhost:3000/static/js/bundle.js:135984:17)
    at Object.next (http://localhost:3000/static/js/bundle.js:135933:14)
    at fulfilled (http://localhost:3000/static/js/bundle.js:135892:24)
App.js:16 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'text')
    at identify (App.js:16:1)
    
Thank you for your help.

**Comment by tannerabread** [comment] 2023-04-05 18:06
Hmm okay I had done another step as well manually in the console but didn't think it was necessary. 

Can you try going to the Cognito console, pressing the `Federated Identities` button on the left navigation pane, and then find the identity pool that matches your app resources. It should be similar to `<appname><resource_string>_identitypool_<resource_string>_dev`

Press `Edit Identity Pool` in the top right corner and under `Unauthenticated identities` check the box for "Enable access to unauthenticated identities"

Keep this screen open and open a new tab navigating to the IAM dashboard. Click on `Roles` then type your app name in the filter search. Click the "unauthRole" rolename and add the [policy shown here](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/react-native/#iam-policy).

**Comment by tannerabread** [comment] 2023-04-05 18:07
Just as a P.S., I think that tutorial was outdated and that is why so many issues arose from following it. I would assume that following the docs would end in less issues

**Comment by Scorles** [comment] 2023-04-05 18:11
IT WORK!!, Thank you for your help and patience. I hope you have a awesome day.

**Comment by tannerabread** [comment] 2023-04-05 18:29
Glad you got it working! Also just a follow up I created the PR for the docs to fix that missing comma.

I hope you also have a wonderful day

**Comment by tannerabread** [comment] 2023-04-05 18:34
I'll also close this for now, but feel free to open up a new issue if you run into any more problems

**Closed by tannerabread** 2023-04-05 18:34 UTC
Labels: Predictions, transferred, pending-triage
