### ISSUE TITLE
Invalid session, session can only be used once error only on iPhone real device in React Native Mobile App

### ISSUE THREAD

**Issue by grkrtech** [aws-amplify/amplify-js#10849] opened 2023-01-09 09:50 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 83.62 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.6.1
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.3.1

```

</details>

### Describe the bug

Ours is a React Native hybrid mobile app targeting both iOS & Android platforms.
AWS Cognito is our Identity & Access Management tool.
Cognito hosted UI is used for mobile authentication, MFA SMS code is enabled.
User enters username, password in Cognito Hosted UI Login page and then enters SMS code received on the iPhone.
Upon click of Sign In, user is facing error - "Invalid session for the user, session can only be used once"

This error is happening only on iPhone real device, doesn't occur in iPhone Simulator, Android Emulator & Android real device.

### Expected behavior

Cognito Hosted UI should accepts SMS code and allow user to login to the mobile app.

### Reproduction steps

AWS Cognito is our Identity & Access Management tool.
Cognito hosted UI is used for mobile authentication, MFA SMS code is enabled.
User enters username, password in Cognito Hosted UI Login page and then enters SMS code received on the iPhone on the next screen.
Upon click of Sign In, user is facing error - "Invalid session for the user, session can only be used once"

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

All iPhone devices

### Mobile Operating System

iOS 16.1

### Mobile Browser

Safari

### Additional information and screenshots

![InvalidSession](https://user-images.githubusercontent.com/68198276/211280843-a8cebc7d-91de-4460-8f8d-a367f015609b.jpg)

**Comment by nadetastic** [comment] 2023-01-10 00:38
Hi @grkrtech thank you for opening this issue. I have some questions about this:

- Can you confirm if you are using the Amplify library at all in your project? (How are calling the HostedUI)
- You mentioned that it works on a simulated device but not on an iOS device. Have you been able to test on Android?

**Comment by grkrtech** [comment] 2023-01-12 09:24
Thanks for investigating.

> Hi @grkrtech thank you for opening this issue. I have some questions about this:
> 
> * Can you confirm if you are using the Amplify library at all in your project? (How are calling the HostedUI)
Yes, we are using AWS Amplify JS  "aws-amplify": "^3.3.12".
`Auth.configure({
				oauth: {
					"domain": xxxx,
					"scope": xxxx,
					"redirectSignIn": redirectURL,
					"redirectSignOut": redirectURL,
					"responseType": "code",
					urlOpener: async (url, redirectUrl) => {
						
					}
				}
			});`
> * You mentioned that it works on a simulated device but not on an iOS device. Have you been able to test on Android?
Yes it is working on iOS simulator, Android Emulator, Android real device but NOT on iPhone read device.

Please let me know if more details are needed.

Thanks

**Comment by nadetastic** [comment] 2023-01-13 06:59
Thank you for confirming @grkrtech 

From what I understand, you are not using social sign in but correct me if I am wrong - is there another reason that you are not using Amplify Auth to here?

[1] https://docs.amplify.aws/lib/auth/emailpassword/q/platform/react-native/#sign-in

**Comment by grkrtech** [comment] 2023-01-18 11:09
Dear @nadetastic 

We are using Federated Sign In for Cognito Hosted UI, not sending username & password.

Thanks

**Comment by nadetastic** [comment] 2023-01-18 16:41
Okay thank you for confirming @grkrtech, Im currently investigating this, i'll follow up with my findings

**Comment by grkrtech** [comment] 2023-01-25 07:58
Dear @nadetastic ,

Please expedite the investigation. Highly Appreciate your help. Thanks

**Comment by nadetastic** [comment] 2023-01-27 01:46
Hi @grkrtech I haven't been able to reproduce this issue when using the latest version of `aws-amplify` and `aws-amplify-react-native`

I also tried with `aws-amplify@3.3.12` which works for me as well, but Im not sure what version of `aws-amplify-react-native`you are using. 

Could you share you `package.json`?

**Comment by nadetastic** [comment] 2023-01-27 01:47
If you are able to, I would recommend upgrading and trying with the latest versions @grkrtech

**Comment by grkrtech** [comment] 2023-01-30 10:14
Dear @nadetastic ,

We are using aws-amplify@3.3.12 and facing this issue only in iPhone Real Device/Phone, NOT in emulator. Reproduced by  multiple folks on iPhone Real devices.
We tested and reproduced the issue even with aws-amplify@latest version (5.x), same issue reproduced in iPhone Real Device.
We are not using aws-amplify-react-native library.

May I know if you have tried with iPhone Emulator or iPhone Real Device ?

Thanks

**Comment by nadetastic** [comment] 2023-02-02 01:41
Hi @grkrtech - I initially tested this on simulator, however I have tested on real device and haven't been able to reproduce this issue. Here are some details

- Using expo/EAS build
- Calling `Auth.federatedSignIn()` with no provider, to display HostedUI
- Configured a custom `urlOpener` as described in [our docs](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples) , so to not open HostedUI in Safari but in an in app browser
- Able to login with credentials, receive and enter MFA code, and sign out with no issues.

Is any part of this different from what you are doing?

**Comment by grkrtech** [comment] 2023-02-02 12:24
Dear @nadetastic,

Thanks for the verification however we observed that a user from US region is not facing this issue in iPhone device but for the same firm, another user from India and few other regions are facing this issue on their iPhones.

Looks like this issue in Cognito Hosted UI is happening for some Geographical users. 
Hope this will help you in further investigation.

Thanks,

**Comment by nadetastic** [comment] 2023-02-08 17:56
Hi @grkrtech,

Thanks for providing the additional details. I'm currently looking into the best way to test this from different regions. However note that this issue maybe more specific to the Cognito service and not Amplify specifically, since the Hosted UI is maintained by Cognito.

I'd like to ask, if possible, could you test by using Amplify Auth to login? In other words, call [`Auth.signIn()`](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#sign-in) directly instead of inputing the user info directly into the Hosted UI.

**Comment by grkrtech** [comment] 2023-02-20 11:40
Dear @nadetastic,

We have tried with Auth.signIn() using aws-amplify-react-native library and is working fine in iPhone real device but we can't implement due to Corporate security reasons. Now we are talking to AWS support on Cognito Hosted UI.

Thanks

**Comment by grkrtech** [comment] 2023-03-03 05:02
Dear @nadetastic,

Now somehow we are able to login to Cognito Hosted UI with MFA SMS option enabled from INDIA & EMEA regions. Looks like some changes have been done in AWS Cognito.

Thanks for all the help and guidance. Appreciate your help.

**Comment by nadetastic** [comment] 2023-03-03 17:57
Hi @grkrtech glad you were able to get this resolved 😄! I'll go ahead and close this issue

**Closed by nadetastic** 2023-03-03 17:57 UTC
Labels: Auth, Cognito, React Native, Service Team, OAuth
