### ISSUE TITLE
HandleAuthResponse clears the history.state and makes `current` undefined

### ISSUE THREAD

**Issue by leopsidom** [aws-amplify/amplify-js#6621] opened 2020-08-22 15:33 UTC
**Describe the bug**
After authentication `window.history.state` gets cleared, and `current` route becomes undefined which causes issue for routing related features.

**To Reproduce**
The problematic line: https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1942

```
window.history.replaceState(
    {},
    null,
    (this._config.oauth as AwsCognitoOAuthOpts).redirectSignIn
);
```

**Expected behavior**
The current history should be kept. https://github.com/vuejs/vue-router-next/issues/366#issuecomment-678622415

```
window.history.replaceState(
  window.history.state,
  '',
  (this._config.oauth as AwsCognitoOAuthOpts).redirectSignIn
);
```

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**
NA

**Smartphone (please complete the following information):**

- Device: Desktop
- OS: Windows
- Browser Chrome
- Version: 84.0.4147.135 

**Additional context**
This breaks advanced features in `vue-router`

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sadooghi** [comment] 2020-08-23 21:11
I have a this problem as well for using this with react native. The errors happens randomly when logged in and out multiple times.

**Comment by sammartinez** [comment] 2020-10-09 18:45
@leopsidom Can you provide a little more insight as to your use case you are looking for? This is by design for our Hosted UI use case that the state will be wiped. Are you looking to track the state? If so, please look to use [Custom State](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend) to do so.

**Comment by leopsidom** [comment] 2020-10-10 00:42
Can you explain how custom state can help here ? Should pass current `window.history` as data while calling `federatedSignIn` ? It doesn't seem immediately clear how that can be done.

**Comment by tannerabread** [comment] 2022-10-10 19:48
@leopsidom @sadooghi are either of you still experiencing this issue?

**Comment by sadooghi** [comment] 2022-10-10 20:49
no, it is resolved. thanks @leopsidom

**Comment by tannerabread** [comment] 2022-10-10 21:12
Closing this as resolved. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with more information so we can re-open this issue and assist you.

Thank you!

**Closed by tannerabread** 2022-10-10 21:12 UTC
Labels: Auth, pending-response
