### ISSUE TITLE
Amplify.configure cause noUserPoolError

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-js#8462] opened 2021-06-17 08:41 UTC
This worked form me on aws-amplify@^3.x.x
```
import Amplify, {Auth} from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
Auth.configure({
  region: process.env.COGNITO_REGION,
  userPoolId: process.env.COGNITO_USER_POOL_ID,
  userPoolWebClientId: process.env.COGNITO_USER_POOL_WEB_CLIENT_ID,
  authenticationFlowType: 'USER_PASSWORD_AUTH',
})
```
In the AWS Amplify auth JS documentation they suggest to use this: (But that triggers the noUserPoolError)
```
Amplify.configure({
  Auth: {
    key: val,
    key2: val2
  }
});
```

Hope that helps :)

_Originally posted by @Hernanm0g in https://github.com/aws-amplify/amplify-js/issues/4001#issuecomment-642286295_

This error is still happening even if the git bot just closed the issue 6days ago....
I have the exact same error with **@aws-amplify/auth@4.0.2** the only way working is using like described by @Hernanm0g is duplicating `Amplify.configure(aws_exports)` with `Auth.configure(aws_exports.Auth)`

**Comment by chrisbonifacio** [comment] 2021-06-17 22:50
Hi @Hideman85 👋 Thanks for raising this. I see that there is a way to configure Auth that works and one that is causing issues in that issue you referenced. However, I am not able to reproduce this issue on an either an older project using `@aws-amplify/auth@3.4.29` nor a newer project using the latest version of 4.0.2.

```js
Amplify.configure({
  Auth: {
    region: "us-east-1",
    userPoolId: "us-east-1_XXXXXX",
    userPoolWebClientId: "XXXXXXXXXXXXXXXXX",
    authenticationFlowType: "USER_SRP_AUTH",
  },
});
```

**Comment by Hideman85** [comment] 2021-06-18 07:05
Hi @chrisbonifacio I suppose in very simple way and manually entered it works fine but in a real world (like react app for example) the general `Amplify.configure` incorrect for some reasons.

What personally I don't understand is why `Amplify.configure(aws_exports)` fails to configure an the line of code just after `Auth.configure(aws_exports.Auth)` is doing the things right...
It must be something wrong doing in `Amplify.configure` is it async/setTimeout in a way? I don't know...

Probably looking the difference between the two calls can put you on the source of the issue :wink:
Unfortunately I don't have time to investigate, I went to github to find a reply why it does not work and found the reply of that guy working for me too. So I just accepted the quick fix and reopened an issue for a non solved problem.

**Comment by chrisbonifacio** [comment] 2021-06-21 17:21
I tried the same configuration with environment variables but wasn't able to reproduce the issue. I don't think this is a current issue on the latest version of Amplify and I think it would come up a lot more often since the proposed issue is with our docs and Auth is one of our most common use cases.

As far as the differences between the two `configure` calls, whatever components are specified within `Amplify.configure`,
we import each component class and call the `configure` method on each of the specified component instances so `Auth.configure` and `Amplify.configure` should function the same way.

https://github.com/aws-amplify/amplify-js/blob/efa2482fc14053145e6db8da70ff52bd7657c80b/packages/auth/src/Auth.ts#L132

https://github.com/aws-amplify/amplify-js/blob/efa2482fc14053145e6db8da70ff52bd7657c80b/packages/core/src/Amplify.ts#L72

That being said, I'm going to close this since as far as I can tell, it's been fixed since the original issue. If someone can provide a simple app and configuration that reproduces this issue consistently then please feel free to open a new issue with that information, then we can debug it and find the cause which might be different for each user if it's not an issue with the Amplify code.

**Closed by chrisbonifacio** 2021-06-21 17:21 UTC
Labels: Can't reproduce
