### ISSUE TITLE
Support for extension service workers in manifest version 3

### ISSUE THREAD

**Issue by chintannp** [aws-amplify/amplify-js#10695] opened 2022-11-21 18:04 UTC
### Is this related to a new or existing framework?

Web Components, New framework

### Describe the feature you'd like to request

Support for extension service workers in manifest version 3. Currently, there are issues when using specific categories with service workers. 

Currently known unsupported categories include:

- [Datastore](https://github.com/aws-amplify/amplify-js/issues/7165)
- Authentication
- [API (GraphQL)
](https://github.com/aws-amplify/amplify-js/issues/10468)
### Describe the solution you'd like

Ability to use the above mentioned categories in extension service workers.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment] 2022-11-23 22:17
Closing as duplicate of #7165.

**Closed by cwomack** 2022-11-23 22:17 UTC
Labels: feature-request, Auth, GraphQL, DataStore, api-graphql, Chrome Extension
