### ISSUE TITLE
Bulk Insert in Amplify Datastore

### ISSUE THREAD

**Issue by nithin-viswanathan** [aws-amplify/amplify-js#8854] opened 2021-09-07 07:32 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

How can we insert bulk data in dynamodb using amplify datastore?

### Expected behavior

The data is in the format of json array. I want to insert and update this using amplify datastore.

Now it is only possible single record save

```
await DataStore.save(
  new Post({
    title: "My First Post",
    rating: 10,
    status: PostStatus.DRAFT
  })
);
```

### Reproduction steps

Install and configure

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2021-09-07 18:36
Hi @nithin-viswanathan 👋 Thanks for raising this issue. I don't think DataStore supports bulk insertions/mutations at the moment. At least, the documentation doesn't seem to mention it.

https://docs.amplify.aws/lib/datastore/data-access/q/platform/js/#create-and-update

**Comment by nithin-viswanathan** [comment] 2021-09-08 07:04
Thanks for the feedback @chrisbonifacio 

Right now we are able to insert the data in datastore by looping( more than 1000 records ). But data synchronization to dynamodb is not working properly, some of the data rows are missing.( we have found that around 350 records are mismatching by comparing indexeddb and dynamodb.

Please advise.

**Comment by Ni7iN** [comment] 2021-09-08 14:07
Hi @chrisbonifacio @nithin-viswanathan  ,
I have the same issue as well. Can you suggest a better way to iterate and insert rather than bulkinsert

**Comment by chrisbonifacio** [comment] 2021-09-09 17:47
@Ni7iN I don't think there's currently a better way to iterate and insert multiple records beside an async function with a for loop that waits for each save to finish before the next. It depends on how you want to handle your promises and when/how to reject.

For example, if you want to handle each promise at a time:

```js
  const savePosts = async (posts) => {
    for (let post of posts) {
      try {
        await DataStore.save(new Post(post));
      } catch (err) {
        console.error(err);
      }
    }
  };
```

rejects immediately upon any of the input promises rejecting, and will reject with that first rejection error message.

```js
  const savePosts = async (posts) => {
   let result;
    try {
      const promises = posts.map((post) => DataStore.save(post));
      results = await Promise.all(promises);
    } catch (err) {
      console.error(err);
    }
    return result
  };
```

returns a with an array of objects that each describes the outcome of each promise after all of the given promises have either resolved or rejected

```js
  const savePosts = async (posts) => {
    let results;
    try {
      const promises = posts.map((post) => DataStore.save(post));
      results = await Promise.allSettled(promises);
    } catch (err) {
      console.error(err);
    }
    return results 
  };
```

**Comment by chrisbonifacio** [comment] 2021-09-09 17:50
I'm going to close this issue btw, as it is not a bug and instead the currently expected behavior.

**Closed by chrisbonifacio** 2021-09-09 17:50 UTC
Labels: DataStore, pending-response

**Comment by nithin-viswanathan** [comment] 2021-09-13 14:55
@chrisbonifacio  - Can you make this as a feature request. We need bulk insert functionality in our project (12k above records), currently it takes much time to complete.
