### ISSUE TITLE
AWS Cognito returns “NotAuthorizedException: Incorrect username or password” when I run it from Jest

### ISSUE THREAD

**Issue by mspoulsen** [aws-amplify/amplify-js#8218] opened 2021-05-04 17:29 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

https://stackoverflow.com/questions/67333167/aws-cognito-returns-notauthorizedexception-incorrect-username-or-password-whe

### Expected behavior

https://stackoverflow.com/questions/67333167/aws-cognito-returns-notauthorizedexception-incorrect-username-or-password-whe

### Reproduction steps

https://stackoverflow.com/questions/67333167/aws-cognito-returns-notauthorizedexception-incorrect-username-or-password-whe

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2021-05-05 13:36
Good morning 👋 Have you tried passing the email and password as an object instead?

this is how `Auth.signIn` is normally called with an object as an argument

```js
const username = "chris";
const password = "Hello123";

async function test() {
  const result = await Auth.signIn({ username, password });
  console.log(result);
}
```

**Comment by chrisbonifacio** [comment] 2021-05-05 14:16
make sure you are using the latest version of `@aws-amplify/auth`, add this line to your package.json, then reinstall your dependencies

```js
"jest": {
    "testEnvironment": "node"
  },
```

I just ran this test with version 3.4.30 (latest) of `@aws-amplify/auth`
<img width="1197" alt="Screen Shot 2021-05-05 at 10 16 09 AM" src="https://user-images.githubusercontent.com/16952986/117155606-eab8be00-ad8a-11eb-865e-2e30d8a5fccd.png">

**Comment by sammartinez** [comment] 2021-05-18 15:36
@mspoulsen,

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 15:36 UTC
Labels: Auth, pending-close-response-required
