### ISSUE TITLE
@aws-amplify/ui-components requires @aws-amplify/interactions

### ISSUE THREAD

**Issue by seang96** [aws-amplify/amplify-js#6802] opened 2020-09-16 13:14 UTC
**Describe the bug**
Installing the a version of @ws-amplify/ui-react after 0.2.15 with only packaging requires @aws-amplify modules causes an error that module @aws-amplify/interactions cannot be resolved. I believe this is due to #6684. Can we get this updated to be a peer dependency or something since I do not need to use a chat bot component?

**To Reproduce**

1. Install latest @aws-amplify/ui-components library or the respective frameworks without installing @aws-amplify as a whole.

**Expected behavior**
@aws-amplify/interactions to not be a required module to use the components library and compile.

**Comment by ashika01** [comment] 2020-09-17 00:22
@seang96: Looking into this. Just curious, Is there a reason for you to not use `aws-amplify` but import the modularized imports? Because with modularization changes we rolled out, it should matter if you import `aws-amplify` or modular ones. Ultimately when you go production, it should enable tree-shaking for you so you wouldnt have any perf impact right?

**Comment by seang96** [comment] 2020-09-17 12:19
@ashika01,
Yeah, that may be true now. Earlier though it did require installing modules individually though. Which my software is doing already.

PR #6811 shows I am not the only one with software that is still importing them as such. From what I saw with that issue Amplify Core registers Credentials as soon as Amplify.Configure is called when then instantiates Auth, where it may not be needed yet in the case the application is serving public pages that doesn't necessarily require backend services until the user reaches a login screen. Anyways, in the case of that issue though if Auth wasn't registered before Credentials registered any library that used Credentials would fail to authenticate properly, AWSS3Provider being one of them.

Another use case is I am using local builds for some packages, more often than not for DataStore, due to PR's that have not been merged yet that are required for my application to run. For development purposes I'd rather build only one module rather than all of them.

**Comment by ashika01** [comment] 2020-09-18 20:57
@seang96 Thanks for the info. The issue solved by #6811 is different from our current issue. 

I looked more into this. Looks like one of our entry point in the module generated does not have a clear distinction in the modules needed. Moving it to peer dependency doesn't solve the problem. I am analyzing the bundles generated to find the root cause. We will keep you posted here.

**Comment by ashika01** [comment] 2020-10-08 18:29
Closing this issue since the PR for this is merged in and released.

**Closed by ashika01** 2020-10-08 18:29 UTC
Labels: Amplify UI Components, dependencies, investigating, needs-discussion
