### ISSUE TITLE
Angular 6 federatedSignIn buttons not showing

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [aws-amplify/amplify-js#4082] opened 2019-09-25 11:54 UTC
I am using Angular 6. Have done all as in the doc. Userpool login works but the social login like facebook, google is not showing in my form.

**Comment by manueliglesias** [comment] 2019-09-26 20:19
Hi @ashish-dirkmedia-de 

This should be addressed by #2900

**Comment by ashish-dirkmedia-de** [comment] 2019-10-16 10:36
I checked recommended link. It says to add components. Can you please guide me more on it like how to copy whole of this as a new module in my angular app.

**Comment by Amplifiyer** [comment] 2019-10-25 23:17
Closing this as duplicate of #4231. Please add your communication directly in the PR you want it to get merged to master

**Closed by Amplifiyer** 2019-10-25 23:17 UTC
Labels: Angular, Auth, question
