### ISSUE TITLE
[Vue] Unable to authenticate on Android

### ISSUE THREAD

**Issue by DanielMuller** [aws-amplify/amplify-js#3598] opened 2019-07-05 17:25 UTC
**Describe the bug**
When trying to authenticate on Chrome Android using _amplify-authenticator_, the username isn't sent to Cognito, resulting in "Username cannot be empty" error.
This happens when typing the username in the field, not when using autocomplete from saved logins.
This doesn't happen on Desktop, only on mobile and only with certain keyboards.

This is related to vuejs/vue#8723

The problem is in https://github.com/aws-amplify/amplify-js/blob/6d34cbd865d813bb6b542bcd90d9ce05eaac40a0/packages/aws-amplify-vue/src/components/authenticator/UsernameField.vue#L92-94
`this.username` is empty when `usernameChanged()` is called.

To solve this, the _input_ attribute needs to be added in input fields.

**To Reproduce**
1. Create an authentication page using _amplify-authenticator_
2. Enter a username
3. Enter a password
4. Login fails "Username cannot be empty"

**Expected behavior**
Typed username should be used.

**Screenshots**
In this [jsfiddle](https://jsfiddle.net/Lpwtfs4o/), typing anything in the fields should reproduce the content in the yellow box.
First box is using only _v-model_, second box is using _v-model_ and _input_

**Desktop (please complete the following information):**
No issue no Desktop

**Smartphone (please complete the following information):**
 - Device: Any Android
 - OS: Android
 - Browser Chrome, Firefox

**Sample code**
https://jsfiddle.net/Lpwtfs4o/

**Comment by jordanranz** [comment] 2019-10-25 17:24
Hey @DanielMuller, could you point me to the documentation related to using the `input` attribute inside of an input element. I couldn't seem to find any information about it. 

I was not able to reproduce this on iOS. I can try on an Android device.

**Comment by jordanranz** [comment] 2019-10-25 18:12
Curious if this change would fix the problem you are experiencing:
https://github.com/vuejs/vuejs.org/pull/1798

**Comment by DanielMuller** [comment] 2019-10-27 05:25
@jordanranz The PR you mention doesn't fix the issue, it just sets the documentation straight.
From this [comment](https://github.com/vuejs/vuejs.org/pull/1798#issuecomment-479560443) on the VueJS repo, it seems to be failing with the default keyboard on Android only. iOS or other Android keyboards don't seem to be affected.

It looks like the issue is how this keybord triggers input changes on Android-MobileWeb.
In the [amplify-vue component](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-vue/src/components/authenticator/UsernameField.vue#L100-L102), they `keyup` event seems to be fored before `this.username` is updated. Which leads to en empty username sent to Cognito.

**Comment by jordanranz** [comment] 2019-10-28 16:30
Sorry, I meant if we use `v-bind` and `v-on:input` instead of `v-model` inside of the Amplify Vue component. This may fix your issue. I will try and reproduce this on a virtual device.

**Comment by DanielMuller** [comment] 2019-10-30 04:47
I was able to make it work by using `v-model` and `v-on:input` based on this [comment](https://github.com/vuejs/vue/issues/8231#issuecomment-416585972).
Tested it on Chrome-Android, and Chrome Desktop. I will push a PR soon.

**Comment by jordanranz** [comment] 2019-10-31 16:39
Awesome, will take a look now. Thanks for submitting a PR

**Comment by jordanranz** [comment] 2019-10-31 18:22
Merged the fix. Please reopen a new issue if there are any related problems to this.

**Closed by jordanranz** 2019-10-31 18:22 UTC
Labels: Auth, Vue, bug
