### ISSUE TITLE
Prototype can only be an object or null

### ISSUE THREAD

**Issue by Arjanvanmaren** [aws-amplify/amplify-js#4025] opened 2019-09-16 08:39 UTC
If I run the application with these packages the following bug appears:
![image](https://user-images.githubusercontent.com/16067826/64944154-fbdb5100-d86d-11e9-9ebd-43529acb69b7.png)

**To Reproduce**
1. this is my package json: 
```{
  "name": "appname",
  "version": "1.0",
  "private": true,
  "scripts": {
    "prestart": "yarn api:download-schema && yarn api:generate-types",
    "start": "react-native start",
    "ios": "react-native run-ios",
    "android": "react-native run-android",
    "bundle:ios": "react-native bundle --entry-file='./src/index.js' --bundle-output='./ios/appname/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios/appname/Bundle.assets' --sourcemap-output='./ios/appname/main.jsbundle.map'",
    "bundle:android": "react-native bundle --entry-file='./src/index.js' --bundle-output='./android/app/index.android.bundle' --dev=false --platform='android' --assets-dest='./android/app/src/main/res' --sourcemap-output='./android/app/index.android.bundle.map'",
    "postbundle:android": "rm -rf ./android/app/src/main/res/raw",
    "codequality": "yarn format && yarn lint && yarn test && yarn tsc",
    "end2end": "detox build --configuration ios.sim.debug && detox test --configuration ios.sim.debug",
    "postinstall": "node scripts/aws-appsync-fix.js && patch-package && yarn jetify && yarn fix-modal",
    "lint": "eslint .",
    "lint:editorconfig": "editorconfig-checker",
    "test": "NODE_ICU_DATA=node_modules/full-icu jest",
    "format": "prettier --check \"{,!(node_modules|android|ios)/**/}*.js*(x)\" \"{,!(node_modules|android|ios)/**/}*.ts*(x)\" \"{,!(node_modules|android|ios)/**/}*.css*\"",
    "fix:format": "prettier --write \"{,!(node_modules|android|ios)/**/}*.js*(x)' \"{,!(node_modules|android|ios)/**/}*.ts*(x)\" \"{,!(node_modules|android|ios)/**/}*.css*\"",
    "api:download-schema": "apollo schema:download",
    "api:extract-calls": "apollo client:extract",
    "api:generate-types": "apollo client:codegen --target=typescript && rimraf ./__generated__",
    "api:generate-types:watch": "apollo client:codegen --target=typescript --watch",
    "fix-modal": "node node_modules/react-native-modal-translucent/scripts/translucent-modal.js"
  },
  "dependencies": {
    "@aws-amplify/api": "^1.1.1",
    "@aws-amplify/auth": "^1.3.1",
    "@aws-amplify/pubsub": "^1.1.2",
    "@react-native-community/async-storage": "1.6.1",
    "@react-native-community/netinfo": "4.1.3",
    "@react-native-firebase/analytics": "0.1.5",
    "@react-native-firebase/app": "0.1.5",
    "@react-native-firebase/crashlytics": "0.1.5",
    "@redux-offline/redux-offline": "2.5.2-native.0",
    "@types/redux-mock-store": "1.0.1",
    "amazon-cognito-identity-js": "^3.0.15",
    "aws-amplify": "^1.1.38",
    "aws-amplify-react-native": "^2.1.19",
    "apollo-cache-inmemory": "1.6.2",
    "apollo-cache-persist": "0.1.1",
    "apollo-client": "2.6.3",
    "apollo-link-http": "1.5.15",
    "aws-appsync": "1.8.1",
    "bugsnag-react-native": "2.22.2",
    "datetime-difference": "1.0.2",
    "full-icu": "1.3.0",
    "graphql": "14.4.2",
    "graphql-tag": "2.10.1",
    "lottie-ios": "3.0.3",
    "lottie-react-native": "3.1.0",
    "react": "16.8.6",
    "react-apollo": "2.5.8",
    "react-native": "0.60.4",
    "react-native-config": "0.11.7",
    "react-native-gesture-handler": "1.3.0",
    "react-native-linear-gradient": "2.5.6",
    "react-native-modal-translucent": "3.0.1",
    "react-native-splash-screen": "3.2.0",
    "react-native-svg": "9.5.3",
    "react-native-svg-transformer": "0.13.0",
    "react-native-webview": "6.9.0",
    "react-navigation": "3.11.1",
    "react-redux": "7.1.0",
    "redux": "4.0.4",
    "redux-devtools-extension": "2.13.8",
    "redux-persist": "5.10.0",
    "styled-components": "4.3.2"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "@types/graphql": "14.2.3",
    "@types/jest": "24.0.15",
    "@types/react-native": "0.60.4",
    "@types/react-redux": "7.1.1",
    "@types/react-test-renderer": "16.8.3",
    "@types/styled-components": "4.1.18",
    "@typescript-eslint/eslint-plugin": "1.13.0",
    "@typescript-eslint/parser": "1.13.0",
    "apollo": "2.16.2",
    "babel-jest": "24.8.0",
    "babel-plugin-module-resolver": "3.2.0",
    "detox": "13.3.1",
    "dotenv-safe": "6.1.0",
    "editorconfig-checker": "2.1.1",
    "eslint": "5.16.0",
    "eslint-config-tuil": "0.5.1",
    "husky": "3.0.1",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.56.0",
    "patch-package": "6.1.2",
    "prettier": "1.18.2",
    "react-test-renderer": "16.8.6",
    "redux-mock-store": "1.5.3",
    "typescript": "3.5.3"
  },
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/appname.app",
        "build": "xcodebuild -workspace ios/appname.xcworkspace -configuration Debug -scheme appname -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.4' -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      },
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Pixel_XL_API_28"
      }
    },
    "test-runner": "jest"
  }
}
```

this issue appears on android and ios.

this is my index.js

```import { AppRegistry } from 'react-native'
import Authenticator from './app/authenticator'
import bugsnag from './app/config/bugsnag'
import awsConfig from '../aws-exports'
import Amplify from '@aws-amplify/core'
Amplify.configure(awsConfig)
AppRegistry.registerComponent('appname', () => Authenticator)
```

I use this in combination with the withAuthenticatorHOC:

```
export default withAuthenticator(
  Root,
  true,
  [
    // @ts-ignore
    <MySignIn />
    // <ForgotPassword/> ,
    // <RequireNewPassword/>
  ],
  null,
  theme
)```

**Comment by elorzafe** [comment] 2019-09-16 18:30
@Arjanvanmaren `aws-amplify` package has a dependency on all the modularized packages `@aws-amplify/api` `aws-amplify/auth`,... and so on, can you try by removing those modularized dependencies?

Are you using predictions category at all?

**Comment by PeteOyable** [comment] 2019-09-18 02:34
@Arjanvanmaren I had the same problem. I've been able to solve it by removing the `aws-amplify` dependency and add the modularized `@aws-amplify/core` instead.

So just run `yarn remove aws-amplify` and `yarn add @aws-amplify/core`, and you should be fine.

**Comment by PeteOyable** [comment] 2019-09-18 19:48
@Arjanvanmaren it turns out, my solution is not working at all. I'am still having this issue. If you've been able to fix it, I'd be glad to know how.

**Comment by Arjanvanmaren** [comment] 2019-09-24 11:40
@elorzafe Yes that is correct. We do not use the predictions api. But we need the withauthenticator HOC which is only available from the aws-amplify-react-native package.

@PeteOyable We still experience the same issue. I temporarily fixed this issue by downgrading to
     
    ```"aws-amplify": "1.1.29",
    "aws-amplify-react-native": "2.1.13",
    "aws-appsync": "1.8.1"```

These packages do not have the predictions build in yet.

**Comment by PeteOyable** [comment] 2019-09-24 12:49
@Arjanvanmaren thank you, I will give it a try with your solution. But it would be nice if a contributor could see the problem. Because it seems nobody else encounters it, I haven't found anything on the internet except here.

**Comment by Arjanvanmaren** [comment] 2019-09-24 13:56
@PeteOyable Yes indeed I couldn't find anything either on the internet, and spend some time to find a solution. I also hope a contributor sees this 👍 Good luck implementing

**Comment by rogueturnip** [comment] 2019-10-04 16:15
I'm also seeing this problem when I version bumped to 1.1.40.

**Comment by ywongweb** [comment] 2019-11-02 18:45
I am bumping into the same problem, version 1.2.40, react native app

**Comment by Arjanvanmaren** [comment] 2019-11-14 08:20
I think this issue is a different issue related to local storage. The issue I have is related to a bug in the predictions library from AWS. It would be nice if they made it possible to individually disable all separate libraries, as I am not using this package.

**Comment by PeteOyable** [comment] 2019-11-14 13:47
@Arjanvanmaren I think it is weird that so few people encounters this issue.
And there's still no contributor to answer us :cry:

**Comment by bakeruk** [comment] 2019-12-20 09:34
+1

**Comment by bakeruk** [comment] 2019-12-20 09:36
Is this just an iOS bug or does it affect Android as well?

**Comment by dhinesh-agentz** [comment] 2019-12-26 08:08
+1

**Comment by AryanJ-NYC** [comment] 2019-12-26 15:37
If you're _not_ using the predictions module, uninstall `aws-amplify` and use `@aws-amplify/core` plus any other services you're using:

`@aws-amplify/storage`
`@aws-amplify/auth`
etc.

**Comment by fhilitski** [comment] 2019-12-27 05:03
I have experienced this issue when using amplify with create-react-app.
In my case, this was fixed by updating dependencies to this:

   "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0"

(This is basically the latest react)...

I notice that @Arjanvanmaren has:

  "react": "16.8.6"

Try updating react dependencies.

**Comment by shalonteoh** [comment] 2019-12-31 07:11
Solved by following dependancies version as suggested by @fhilitski 
then run `npm rebuild node-sass`

**Comment by almpertis** [comment] 2020-02-06 22:14
any news regarding this issue?

**Comment by yangga** [comment] 2020-02-07 14:18
same here

**Comment by almpertis** [comment] 2020-02-08 00:47
Downgrading to the versions @Arjanvanmaren recommended fixed the issue for me but this is not a permanent solution.

**Comment by julianljk** [comment] 2020-02-17 05:03
same issue here

**Comment by almpertis** [comment] 2020-02-17 09:57
If you are using expo make sure that you have installed all your exports. I had the exact same issue. Problem was that I was using an expo import that I had not installed with yarn or npm. The linter would not throw an error and everything seemed to work (apart from the big red error)

**Comment by danrivett** [comment] 2020-03-11 01:17
I have the same issue too using Expo 36. I just decided to stop using the `withAuthenticator` as spent over an hour trying different things, and although downgrading as per @Arjanvanmaren's comment seemed successful, I got React deprecrated warning messages because some of the HOCs provided were using old Component lifecycle methods.

Crazy this hasn't been reproduced. /cc @elorzafe

**Comment by OtavioBraga** [comment] 2020-03-11 19:21
We are experiencing this error too with typescript on rect native 61.5. Downgarding to 1.1.29 solved the problem temporarily. We're suspecting that this error occurs due a circular import in the lib.

**Comment by milo-** [comment] 2020-03-12 10:59
I just ran into this in a new react-native TS project after I added babel-plugin-module-resolver. I've added step to reproduce the issue here, along with the source https://github.com/milo-/AmplifyTest.

**Comment by OtavioBraga** [comment] 2020-03-12 13:06
@milo-, can confirm, i've reproduced the bug following the steps.

**Comment by OtavioBraga** [comment] 2020-03-12 14:28
We solved the problem removing the root key from the babel.config.js.

**Before:**
```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  sourceMaps: true,
  plugins: [
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        root: ['./'], // Removed this key
        alias: {
          src: './src',
          '@components': './src/components',
          '@icons': './src/assets/icons',
          '@locales': './src/locales',
          '@routes': './src/routes',
          '@styles': './src/styles',
          '@utils': './src/utils',
          '@models': './src/models',
          '@hooks': './src/hooks',
        },
      },
    ],
  ],
};
```
**Then:**
```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  sourceMaps: true,
  plugins: [
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        alias: {
          src: './src',
          '@components': './src/components',
          '@icons': './src/assets/icons',
          '@locales': './src/locales',
          '@routes': './src/routes',
          '@styles': './src/styles',
          '@utils': './src/utils',
          '@models': './src/models',
          '@hooks': './src/hooks',
        },
      },
    ],
  ],
};

```

**Comment by shirakaba** [comment] 2020-03-16 22:42
@OtavioBraga This solution had no effect in my case.

@Arjanvanmaren The solutions to downgrade to versions from 9 months ago (i.e. `"aws-amplify": "1.1.29",`) produced different errors of their own (i.e. problems with inconsistent versions between modules).

@dabit3 unfortunately I am unable to complete your recent [The Complete React Native Guide to User Authentication with the Amplify Framework](https://dev.to/dabit3/the-complete-react-native-guide-to-user-authentication-with-the-amplify-framework-ib2) guide due to this error. I installed all dependencies today.

```js
{
// ...
"@aws-amplify/core": "^2.2.5",
"@aws-amplify/datastore": "^1.0.8",
"@react-native-community/netinfo": "^5.6.2",
"aws-amplify": "^2.2.6",
"aws-amplify-react-native": "^3.2.2",
// ...
}
```

I had been attracted to AWS Amplify first and foremost due to the drop-in Authentication UI (which is AWS Amplify's unique selling point compared to Firebase and Azure's offerings). However, after losing the whole day trying to get around this, I am blocked at the first step of entry to the Amplify ecosystem – authentication.

Seeing that this issue has persisted unsolved for half a year already, I'm afraid I'll have to move on to competing solutions.

**Comment by markhker** [comment] 2020-03-23 23:39
I had the same issue, with expoKit 36.0.0, the error was only on iOS simulator (working correctly on android device and web).
Uninstalling `aws-amplify` and installing individual packages (core, auth and api only) worked for me.

**Comment by amhinson** [comment] 2020-04-13 16:42
I was able to reproduce this issue with the repo that @milo- provided above as well as a brand new React Native Amplify project with `aws-amplify@latest` using the same `babel.config.js` as the example repo.

However, the problem does seem to be related to `babel-plugin-module-resolver` usage and not `aws-amplify` itself. When I remove `root: ['./']` as @OtavioBraga mentioned above, the error goes away.

Can anyone else confirm this fixes the error you are seeing?

One important thing you need to do anytime you change `babel.config.js` is be sure to run `watchman watch-del-all` and `react-native start --reset-cache`. Otherwise you might not be seeing the latest changes.

**Closed** 2020-04-28 03:21 UTC
Labels: Predictions, React Native, pending-close-response-required
