### ISSUE TITLE
V6 Auth - confirmSignIn Unkown Error

### ISSUE THREAD

**Issue by steve-calverley** [aws-amplify/amplify-js#12622] opened 2023-11-23 03:23 UTC
> @steve-calverley
> 
> feel free to open a new issue but I am still not sure why `setTokens` is failing, I wonder if there is something related to async storage configuration. Are you running the App on iOS, or Android?

@elorzafe Running on both iOS and Android emulators. Let me look into Async Config before opening new issue

_Originally posted by @steve-calverley in https://github.com/aws-amplify/amplify-js/issues/12593#issuecomment-1823537343_

**Comment by steve-calverley** [comment] 2023-11-23 03:24
@ @elorzafe tokenOrchestrator:  undefined in node_modules/@aws-amplify/auth/src/providers/cognito/tokenProvider/cacheTokens.ts

**Comment by steve-calverley** [comment] 2023-11-24 00:58
So updating node_modules/@aws-amplify/auth/src/providers/cognito/tokenProvider/cacheTokens.ts to import the tokenOrchestrator to import { tokenOrchestrator } from '../tokenProvider';
Seems to resolve the issue for me.

**Comment by steve-calverley** [comment] 2023-11-26 09:21
@nadetastic @elorzafe @israx After 6hrs of removing babel module resolver I can confirm this now works
So to me its a stray '.' import that does not work work with the Babel Module resolver

**Comment by elorzafe** [comment] 2023-11-27 22:42
@steve-calverley thanks for reporting this problem. I couldnt reproduce the problem with latest `expo` and `react-native` CLI, can you share the steps you did or a repo? (even better) so the team can reproduce this problem locally.

Thanks!

**Comment by elorzafe** [comment] 2023-11-28 19:08
@steve-calverley we published a fix for this problem on `unstable` tag on npm, can you verify it works for you?

**Comment by steve-calverley** [comment] 2023-11-28 21:38
@elorzafe Can confirm working on [6.0.6-unstable.cf3a619.0](https://www.npmjs.com/package/aws-amplify/v/6.0.6-unstable.cf3a619.0)

**Comment by cwomack** [comment] 2023-12-05 21:42
The fix for this was released today in Amplify v6.0.6. I'll close this issue for now, but let us know if there are any further issues related to this bug!

**Closed by cwomack** 2023-12-05 21:42 UTC
Labels: bug, Auth, pending-release
