### ISSUE TITLE
DataStore fails to initialize subscriptions when @auth directive with ownerField is used

### ISSUE THREAD

**Issue by mlxyz** [aws-amplify/amplify-js#7318] opened 2020-12-01 22:09 UTC
**Describe the bug**
Consider the following schema:
```gql
type User
@model
@auth(rules: [
    { allow: owner, ownerField: "id", operations: [read] }
])
{
    id: ID!
    # more fields (no "owner" field however)
}
```
DataStore fails to properly initialize the `User` related subscriptions throwing this exception:
```
[WARN] 27:48.926 DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'owner' in type 'User' is undefined @ 'onUpdateUser/owner'"}]}
```
As far as I can tell this is caused by these lines:
https://github.com/aws-amplify/amplify-js/blob/d9dfff3eef7e5909f76fdea6054f8c02eb7ac8a2/packages/datastore/src/sync/utils.ts#L61-L64
which assume that DataStore will receive the implicit "owner" field from AppSync despite the fact that a custom owner field is used (the `ownerField` property of the `@auth` directive is set to `id`).
The `generateSelectionSet` function is called here, when building the GraphQL subscription query:
https://github.com/aws-amplify/amplify-js/blob/d9dfff3eef7e5909f76fdea6054f8c02eb7ac8a2/packages/datastore/src/sync/utils.ts#L263

By looking at the messages DataStore sends over the websocket connection, I can confirm that DataStore expects to receive an `owner` field from the subscription which obviously fails because that field does not exist on the `User` model. 

**To Reproduce**

1. Setup a project using the schema posted above
2. Try to initialize DataStore with subscriptions

**Expected behavior**
I expect DataStore to properly initialize the subscriptions, just like I can do manually using the AppSync Web UI.

**What is Configured?**
<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 14.29 GB / 31.33 GB
    Container: Yes
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 15.3.0 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  Browsers:
    Firefox: 83.0
  npmPackages:
    @angular-devkit/build-angular: ^0.1100.2 => 0.1100.2 
    @angular/cli: ^10.2.0 => 10.2.0 
    @angular/common: ^10.2.3 => 10.2.3 
    @angular/compiler: ^10.2.3 => 10.2.3 
    @angular/compiler-cli: ^10.2.3 => 10.2.3 
    @angular/core: ^10.2.3 => 10.2.3 
    @angular/forms: ^10.2.3 => 10.2.3 
    @angular/language-service: ^10.2.3 => 10.2.3 
    @angular/platform-browser: ^10.2.3 => 10.2.3 
    @angular/platform-browser-dynamic: ^10.2.3 => 10.2.3 
    @angular/router: ^10.2.3 => 10.2.3 
    @angular/service-worker: ^10.2.3 => 10.2.3 
    @aws-amplify/datastore: ^2.8.1 => 2.8.1 
    @aws-amplify/ui-angular: ^0.2.15 => 0.2.15 
    @babel/compat-data: ~7.8.0 => 7.8.6 
    @ionic-native/core: ^5.30.0 => 5.30.0 
    @ionic-native/splash-screen: ^5.30.0 => 5.30.0 
    @ionic-native/status-bar: ^5.30.0 => 5.30.0 
    @ionic/angular: ^5.5.1 => 5.5.1 
    @ionic/angular-toolkit: ^2.3.3 => 2.3.3 
    @types/jasmine: ~3.3.8 => 3.3.16 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/luxon: ^1.25.0 => 1.25.0 
    @types/moment-duration-format: ^2.2.2 => 2.2.2 
    @types/node: ^12.19.7 => 12.19.7 
    aws-amplify: ^3.3.10 => 3.3.10 
    aws-amplify-angular: ^5.0.39 => 5.0.39 
    codelyzer: ^5.1.2 => 5.2.2 
    core-js: ^2.6.12 => 2.6.12 
    cron-parser: ^2.18.0 => 2.18.0 
    jasmine-core: ~3.5.0 => 3.5.0 
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    karma: ~5.0.0 => 5.0.9 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~3.3.0 => 3.3.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4 
    luxon: ^1.25.0 => 1.25.0 
    ngx-image-cropper: ^3.3.1 => 3.3.1 
    protractor: ~7.0.0 => 7.0.0 
    rxjs: ^6.6.3 => 6.6.3 
    ts-node: ~7.0.0 => 7.0.1 
    tslib: ^2.0.3 => 2.0.3 
    tslint: ^6.1.3 => 6.1.3 
    typescript: ^3.9.7 => 3.9.7 
    zone.js: ~0.10.3 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 10.1.6
    @aws-amplify/cli: 4.37.0
    @ionic/cli: 6.12.2
    aws-cdk: 1.60.0
    node-gyp: 7.1.0
    npm: 6.14.8
    semver: 7.3.2
```

</details>

**Comment by iartemiev** [comment] 2020-12-01 22:27
Hey, @mlxyz this is a duplicate of https://github.com/aws-amplify/amplify-js/issues/7315. This bug will be fixed once we merge PR https://github.com/aws-amplify/amplify-js/pull/7317.

One thing to note though is that primary keys (`id` field) in DataStore are not customizable. DataStore will set it to a UUID under the hood, so you should use a different `ownerField` value.

**Closed by iartemiev** 2020-12-01 22:27 UTC
Labels: DataStore, to-be-reproduced
