### ISSUE TITLE
MISSING_AUTHENTICATION_TOKEN with browsers Edge and former Chrome

### ISSUE THREAD

**Issue by DuhamelPhilippe** [aws-amplify/amplify-js#5769] opened 2020-05-13 10:15 UTC
Hello, 
I'm trying to make a call to my Lambda functions, configured with "Authorization: AWS_IAM". The call works well from Chrome (v81), Firefox (v76) and also from IOS and Iphone browsers. But when I do the call from Microsoft Edge or previous Chrome (v49 for example) I receive a 403 error. I've enabled Cloud Watch logs and realized that, when I receive this error, I have the following api gateway execution log : "Gateway response type: MISSING_AUTHENTICATION_TOKEN with status code: 403"
It seems to me that with some browsers authentication data are not "transfered" when making an API call.

**To Reproduce**
- Init an Angular app
- npm install @aws-amplify/core
- npm install @aws-amplify/auth
- npm install @aws-amplify/api
- and use following code

API and Auth configuration
```
import {Amplify} from '@aws-amplify/core';
import {API} from '@aws-amplify/api';
Amplify.configure({
  Auth: {
    mandatorySignIn: true,
    region: "***",
    userPoolId: "***",
    identityPoolId: "***",
    userPoolWebClientId: "***",
  }
});
API.configure(
  {
    endpoints: [
      {
        name: "iw",
        endpoint: "https://***.execute-api.us-east-1.amazonaws.com/dev"
      }
    ]
  }
);
```

API call
```
test() {
    Auth.signIn("***", "***").then(()=> {
      API.get("iw", `/notifications`, null)
      .then(r=> { console.log(r); })
      .catch(e=> { console.log(e); });
    })
    .catch(e => { console.log("Login error :"+e); })
  }
```
package.json
```   
"@aws-amplify/api": "^3.1.9",
"@aws-amplify/auth": "^3.2.6",
"@aws-amplify/core": "^3.2.6",
```

**Comment by alaeri** [comment] 2020-06-14 19:55
We have the same bug in our project. Is there a workaround available?

**Comment by DuhamelPhilippe** [comment] 2020-06-15 03:56
> We have the same bug in our project. Is there a workaround available?

After one month, I'm "happy" to see that I'm not the only one having this issue. 
Nothing new on my side except that Microsoft has updated his browser Edge, about 2 weeks ago. We don't have this issue anymore with updated Edge browsers. 
But the issue still remains with previous versions.

**Comment by sammartinez** [comment] 2020-09-16 20:33
@DuhamelPhilippe Apologizes on circling back on this until now. We do follow support for the previous three versions of major browsers. Please see what we support [here](https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/). Do you have a customer use case where your customers would need to be using old versions as you have called out? Please let us know

**Comment by DuhamelPhilippe** [comment] 2020-09-17 05:00
@sammartinez Thank you for your reply. 
In May, I was able to reproduce (see steps above) this issue with different old browsers and also an up-to-date Edge browser. I don't think that Microsoft has published 3 major versions of his browser during the last 5 months.

**Comment by sammartinez** [comment] 2020-09-17 15:33
@DuhamelPhilippe Thanks for replying back. I will see about reproducing then on the latest Edge. Will provide an update once we are able to reproduce

**Comment by iartemiev** [comment] 2021-04-12 18:03
@DuhamelPhilippe,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:03 UTC
Labels: Auth, Browser Compatibly, pending-close-response-required
