### ISSUE TITLE
User object not detected in Remix.js SSR

### ISSUE THREAD

**Issue by aspittel** [aws-amplify/amplify-js#9780] opened 2022-04-07 15:34 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Remix.js

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line

 System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 30.52 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.3 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 91.7.1
    Safari: 15.3
  npmPackages:
    @aws-amplify/ui-react: ^2.11.0 => 2.11.0
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @remix-run/dev: ^1.3.3 => 1.3.3
    @remix-run/eslint-config: ^1.3.3 => 1.3.3
    @remix-run/react: ^1.3.4 => 1.3.4
    @remix-run/serve: ^1.3.4 => 1.3.4
    aws-amplify: ^4.3.18 => 4.3.18
    eslint: ^8.11.0 => 8.12.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    remix: ^1.3.3 => 1.3.3
  npmGlobalPackages:
    @architect/architect: 10.1.0
    @aws-amplify/cli: 7.6.26
    aws-amplify: 4.3.11-unstable.4+73587d78f
    aws-cdk: 1.131.0
    aws-sdk: 2.1090.0
    create-react-app: 5.0.0
    netlify-cli: 9.13.3
    npm: 8.5.3
    standard: 16.0.4

```

</details>

### Describe the bug

Authorization rules for mutating data don't pass even though I am signed in.

### Expected behavior

If I'm signed in, I should be able to mutate data in SSR functions in Remix. I get errors instead. Also if I try to get the user object, it says I'm not signed in.

```js
{
  data: { createTask: null },
  errors: [
    {
      path: [Array],
      data: null,
      errorType: 'Unauthorized',
      errorInfo: null,
      locations: [Array],
      message: 'Not Authorized to access createTask on type Mutation'
    }
  ]
}
``` 

### Reproduction steps

1. Create a Remix App
2. Enable Amplify Auth (I went through Studio)
3. Enable local auth (withAuthenticator)
4. Create a GraphQL API
5. Create a Remix action for creating a new data instance

### Code Snippet

```javascript
// Form
import { Form } from 'remix'
import { TextField, Button } from '@aws-amplify/ui-react'

export default function CreateTask () {
  return (
    <Form method='post' action='/tasks'>
      <TextField name='task' label='Create a task' />
      <Button marginTop='10px' type='submit' variation='default'>Create</Button>
    </Form>
  )
}
```

```js
// Action
import { redirect } from 'remix'
import { withSSRContext } from 'aws-amplify'
import { createTask } from '../../src/graphql/mutations'

export async function action ({ request }) {
  const body = await request.formData()
  const SSR = withSSRContext(request)

  const user = await SSR.Auth.currentAuthenticatedUser()

  await SSR.API.graphql({
    query: createTask,
    variables: {
      input: {
        name: body._fields.task[0],
        done: false
      }
    }
  })

  return redirect('/')
}
```

```gql
type Task @model  @auth(rules: [{ allow: owner }]) {
  done: Boolean!
  dueDate: AWSDateTime
  name: String!
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://oulcqjwcwrf7dbrrtvdh4bgwdu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-o6lgqk6lvjaplcmupxygskjtsa",
    "aws_cognito_identity_pool_id": "us-east-1:9adfe06e-9a19-4352-ba4e-07c941a43448",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_snzFoLBVY",
    "aws_user_pools_web_client_id": "2trpa7u054fvrksgnk8a48e4if",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
```

### Additional information and screenshots

https://user-images.githubusercontent.com/12969662/162237172-761e361d-86c3-45ca-a895-c4b16dbc51b5.mp4

**Comment by sergiors** [comment] 2022-04-21 02:16
@chrisbonifacio 

The bug occurs because the username contains `@` but in cookies the `@` becomes `%40`, on the following line the username contains `@` instead of `%40` https://github.com/aws-amplify /amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1388

I guess the encodeURIComponent solve the problem

**Comment by asp3** [comment] 2022-04-30 16:42
@sergiors what do you mean by encodeURIComponent? I am having the same issue

**Comment by Davidrl1000** [comment] 2022-05-31 00:56
I had the same issue using NextJs and `getServerSideProps`. To resolve the issue I had to explicitly add the authentication mode, in my case `authMode: 'AMAZON_COGNITO_USER_POOLS’`

Based on that solution you should replace your action query to:

```javascript
export async function action ({ request }) {
  const body = await request.formData()
  const SSR = withSSRContext({request})

  const user = await SSR.Auth.currentAuthenticatedUser()

  await SSR.API.graphql({
    query: createTask,
    authMode: 'AMAZON_COGNITO_USER_POOLS'
    variables: {
      input: {
        name: body._fields.task[0],
        done: false
      }
    }
  })

  return redirect('/')
}
```


I added curly braces to the SSR initialization based on [this guide](https://docs.amplify.aws/lib/ssr/q/platform/js/#withssrcontext).

**Comment by nickarocho** [comment] 2022-06-22 00:26
I'm able to reproduce this issue, both when a user is logged in and when no user is logged in.

Adding `authMode: "AMAZON_COGNITO_USER_POOLS",` to the GQL mutation doesn't make a difference for me.

I'll keep looking into this and keep you posted!

**Comment by visomi-dev** [comment] 2022-09-21 21:48
Reading the code of withSSRContext I found the solution for remix:

```index.tsx```
```typescript
import type { LoaderFunction } from '@remix-run/node';

import type { User } from '~/entities/auth';

import { getUserFromRequest } from '~/lib/amplify/auth/users'

type LoaderData = { user: User | null };

export const loader: LoaderFunction = async ({ request }) => {
  const user = await getUserFromRequest(request);
  
  return json<LoaderData>({ user });
}
```

```lib/amplify/auth/users.ts```
```typescript
import type { Auth as AuthClass } from '@aws-amplify/auth';
import { withSSRContext } from 'aws-amplify';
import get from 'lodash/get';

import type { CognitoUserAttributes, User } from '~/entities/auth';

import logger from '../logger';

export async function getUserFromRequest(request: Request) {
  try {
    const Auth = withSSRContext({
      req: { headers: { cookie: request.headers.get('cookie') } },
    }).Auth as typeof AuthClass;

    const cognitoUser = await Auth.currentAuthenticatedUser();
    const attributes = get<CognitoUserAttributes>(
      cognitoUser,
      'attributes',
      {} as CognitoUserAttributes,
    );

    const user: User = {
      id: cognitoUser.username,
      name: attributes.name,
      email: attributes.email,
    };

    return user;
  } catch (error) {
    logger.debug(`user not authenticated ${error}`);

    return null;
  }
}
```

**Comment by abdallahshaban557** [comment] 2022-09-21 23:06
@visomi-dev - with the changes to these files you are now able to get remix to work in SSR with Amplify?

**Comment by visomi-dev** [comment] 2022-09-22 00:03
@abdallahshaban557 not at all, they need other files, here is my repo you can see these files:

https://github.com/vitea-dev/utopia/blob/main/apps/web/src/root.tsx
https://github.com/vitea-dev/utopia/blob/main/apps/web/src/lib/amplify/index.ts
https://github.com/vitea-dev/utopia/blob/main/apps/web/src/constants/environment.ts
https://github.com/vitea-dev/utopia/blob/main/apps/web/src/lib/auth/user.ts
https://github.com/vitea-dev/utopia/blob/main/apps/web/src/routes/index.tsx

I have only one issue with the signOut, because I don't know how can I remove the cookies on remix, but I will continue searching

**Comment by abdallahshaban557** [comment] 2022-09-23 06:24
got it! Thank you for the feedback @visomi-dev ! If you would like to contribute back to the library to deliver this - give me a heads up if you have an early PR - we can check internally and provide some direction before you get too deep into it!

**Comment by joekendal** [comment] 2022-09-25 16:28
This issue is also in Next.js

**Comment by abdallahshaban557** [comment] 2022-09-26 15:36
@joekendal - Can you please submit a Github issue for us to replicate this issue on Next.JS, we had tested it just recently and we cannot see any issues with using SSR with Next.js.

**Comment by joekendal** [comment] 2022-09-26 23:25
Sorry but we've abandoned Amplify now. There are multiple issues already stuck on Open related to this problem for at least 6 months.

**Comment by joekendal** [comment] 2022-09-27 23:52
I wish I could help but I've abandoned Amplify now because of this and another bug to do with Safari rejecting the websocket being http and causing it to crash even if I don't import the api package and only want auth

**Comment by DavidBrear** [comment] 2022-10-01 20:29
@visomi-dev 's solution https://github.com/aws-amplify/amplify-js/issues/9780#issuecomment-1254262202 ☝️  up there worked for me. One thing I noticed was when you do `Auth.signIn` in the action method it won't set the cookies and actually doesn't return any cookies. I did the auth sign in with:

`login.tsx`
```
export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();
  const email = formData.get("email");
  const password = formData.get("password");
  const SSR = withSSRContext({ req: request });
  const user = await SSR.Auth.signIn(email, password);
  return saveAmplifyCookies(user.pool.storage.store);
}
```

then in `session.server.ts`
```
export async function saveAmplifyCookies(cookies: Record<string, string>) {
  const headers = new Headers();
  Object.keys(cookies).forEach((key) => {
    headers.append(
      "Set-Cookie",
      `${key}=${cookies[key]}; Max-Age=157680000; Path=/; HttpOnly; SameSite=Lax`,
    );
  });
  return redirect("/", { headers });
}```

**Comment by visomi-dev** [comment] 2022-10-02 04:41
@DavidBrear try to call SignIn on frontend directly to aws cognito (no on the server-side).

[Here an example](https://github.com/visomi-dev/vitea/blob/main/apps/web/src/routes/authentication/sign-in.tsx#L71)
[I create my own amplify provider for frontend because I use custom auth](https://github.com/visomi-dev/vitea/blob/main/apps/web/src/lib/amplify/auth/index.ts#L115)
[And aws amplify is very large lib (along 4MB)](https://github.com/visomi-dev/vitea/blob/main/apps/web/src/lib/amplify/auth/sdk.ts#L29)

**Comment by MattyBalaam** [comment] 2022-12-15 15:31
Many thanks to @visomi-dev and @DavidBrear – I spent over a day going around and around trying to work out how to get Auth working server side and your two code snippets have been the answer I was looking for.

**Comment by nadetastic** [comment] 2023-09-22 19:29
Hi all 👋🏾 - following up on this issue. The two key things needed to get this working when attempting to get the auth session on the server side are as follows:
- You will need to login the user on the client as @visomi-dev mentioned
- Pass the cookies  to withSSRContext as shown on [this comment](https://github.com/aws-amplify/amplify-js/issues/9780#issuecomment-1254262202)
- Be sure to set `ssr: true` in your `Amplify.configure()`

With the above configured, you will be able to use withSSRContext in your `loader()` or `action()` functions. I have setup a simple working example here that uses `withSSRContext` in a [`loader()`](https://github.com/nadetastic/remix-amplified/blob/main/app/routes/notes.tsx#L23-L37) function:
- https://github.com/nadetastic/remix-amplified/tree/main

Thanks for all the input and discussion on this issue, let me know if there are any other questions on this.

**Comment by MattyBalaam** [comment] 2023-10-26 19:58
I have been revisting this recently to get some code production ready from the spike I did a while ago.

- Server side login is possible, but there does not seem to be a way of logging the device and user IP that I can find. It just gets reported as nodejs and the IP of the server. Might not be an issue for you, but if anyone knows how that would be great.
- By default the amplify withSSRContext Auth keeps the user details on `cognitoUser.pool.storage.store` and I these are meant to be applied to a cookie in your reponse, which is then read in the request on the cookie.
- We wanted to keep these internal (on DynamoDB), so instead we locally forked `withSSRContext` to just accept the values directly.

Maybe Amplify 6 might be more Remix friendly when it comes out?

**Comment by nadetastic** [comment] 2023-12-01 16:36
With the release of V6 of `aws-amplify` I'll mark this issue as closed as the solution provided only works with previous versions of the library. Will be tracking the V6 related issue here - https://github.com/aws-amplify/amplify-js/issues/12660

**Closed by nadetastic** 2023-12-01 16:36 UTC
Labels: Auth, SSR, pending-response
