### ISSUE TITLE
"Exceeded maximum endpoint per user count 10"

### ISSUE THREAD

**Issue by rygo6** [aws-amplify/amplify-js#1662] opened 2018-09-17 18:06 UTC
I keep getting this error back:
```
{RequestID: "a4d9e97e-baa3-11e8-afca-15f5af9ff730",…}
Message: "Exceeded maximum endpoint per user count 10"
RequestID: "a4d9e97e-baa3-11e8-afca-15f5af9ff730"
```

I have no idea what it means or how to approach it. What does this mean?

**Comment by nidsharm** [comment] 2018-09-17 18:52
Hi @rygo6 ,

Can you please tell us more about the Amplify/Cognito API that you used, it would be useful to figure out more on the issue. As per the error message it looks like you hit the maximum limit on the number of calls allowed.

**Comment by jordanranz** [comment] 2018-12-04 20:30
Closing as this is a duplicate of #1378

**Closed by jordanranz** 2018-12-04 20:30 UTC
Labels: question
