### ISSUE TITLE
VSCode Extension intellisense quirk with Storage

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-js#7886] opened 2021-03-05 12:01 UTC
**Describe the bug**

Using the VSCode extension "AWS Amplify API" (which links back to this repository so hope this is the right place) it seems the intellisense is a bit too keen. Whenever I type a full stop it always suggests the Storage options shown below. This is just adding noise and distractions (here I'm editing the readme file for instance).

![image](https://user-images.githubusercontent.com/1674590/110112769-0f53e200-7daa-11eb-98a3-508a663e5508.png)

**To Reproduce**

Install the extension, open a file and type something with a fullstop at the end and up it should pop!

Additionally if you type the wrong thing it seems to autocomplete a whole constructor in there which is just annoy.

**Expected behavior**

Only show me the Storage stuff when I want it?

**What is Configured?**

VSCode: v1.53.1
Extension (aws-amplify.aws-amplify-vscode): v0.0.4

**Comment by sammartinez** [comment] 2021-05-19 21:25
Thanks for this feedback @PeteDuncanson, I have marked this as a feature request for us to update the VSCode extension

**Comment by StephenBlank** [comment] 2022-02-11 03:59
I am unable to reproduce.

**Comment by tannerabread** [comment] 2022-12-02 20:52
Closing as the VSCode extension has been deprecated as of v5.0.2
[Release Notes](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.2)

**Closed by tannerabread** 2022-12-02 20:52 UTC
Labels: good first issue, feature-request, Storage, Tooling
