### ISSUE TITLE
Can't use code or error query parameters

### ISSUE THREAD

**Issue by mikkilevon** [aws-amplify/amplify-js#10415] opened 2022-10-04 09:54 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 461.06 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.1
    Safari: 16.0
  npmPackages:
    @graphql-codegen/cli: ^2.6.2 => 2.6.2 
    @graphql-codegen/typescript: ^2.4.8 => 2.4.8 
    @reduxjs/toolkit: ^1.6.1 => 1.8.1 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/builder-webpack5: 6.5.0-beta.0 => 6.5.0-beta.0 
    @storybook/manager-webpack5: 6.5.0-beta.0 => 6.5.0-beta.0 
    @storybook/node-logger: ^6.4.22 => 6.4.22 (6.5.0-beta.0)
    @storybook/preset-create-react-app: ^4.1.0 => 4.1.0 
    @storybook/react: 6.5.0-beta.0 => 6.5.0-beta.0 
    @types/enzyme: ^3.10.9 => 3.10.12 
    @types/jest: ^26.0.24 => 26.0.24 
    @types/lodash: ^4.14.175 => 4.14.182 
    @types/node: ^12.20.24 => 12.20.50 (17.0.29, 14.18.16, 16.11.31)
    @types/react: ^18.0.8 => 18.0.8 
    @types/react-dom: ^18.0.0 => 18.0.0 
    @types/react-router-dom: ^5.1.9 => 5.3.3 
    @typescript-eslint/eslint-plugin: ^5.21.0 => 5.21.0 
    @typescript-eslint/parser: ^4.31.1 => 4.33.0 (5.21.0)
    @wojtekmaj/enzyme-adapter-react-17: ^0.6.3 => 0.6.7 
    aws-amplify: ^4.3.15 => 4.3.37 
    axios: ^0.24.0 => 0.24.0 (0.26.0)
    cognito-local: ^3.20.0 => 3.20.0 
    enzyme: ^3.11.0 => 3.11.0 
    eslint: ^8.14.0 => 8.14.0 
    eslint-config-airbnb: ^19.0.4 => 19.0.4 
    eslint-plugin-import: ^2.26.0 => 2.26.0 
    eslint-plugin-jest: ^26.1.5 => 26.1.5 (25.7.0)
    eslint-plugin-jsx-a11y: ^6.5.1 => 6.5.1 
    eslint-plugin-react: ^7.29.4 => 7.29.4 
    eslint-plugin-react-hooks: ^4.5.0 => 4.5.0 
    eslint-plugin-storybook: ^0.5.11 => 0.5.11 
    http-proxy-middleware: ^2.0.6 => 2.0.6 
    jdenticon: ^3.1.1 => 3.1.1 
    jest-react-hooks-shallow: ^1.5.1 => 1.5.1 
    lodash: ^4.17.21 => 4.17.21 
    react: ^18.1.0 => 18.1.0 (16.14.0)
    react-dom: ^18.1.0 => 18.1.0 
    react-redux: ^8.0.1 => 8.0.1 
    react-router-dom: ^6.2.1 => 6.3.0 
    react-scripts: ^5.0.1 => 5.0.1 
    react-toastify: ^8.1.0 => 8.2.0 
    redux: ^4.1.1 => 4.2.0 
    redux-devtools-extension: ^2.13.9 => 2.13.9 
    redux-thunk: ^2.3.0 => 2.4.1 
    smee-client: ^1.2.3 => 1.2.3 
    typescript: ^4.4.3 => 4.6.3 
    use-react-router-breadcrumbs: ^3.1.0 => 3.2.1 
    web-vitals: ^1.1.2 => 1.1.2 
    webpack: 5 => 5.72.0 (4.46.0)
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.25
    amplify: 0.0.11
    corepack: 0.10.0
    npm: 8.5.5
    smee-client: 1.2.2
    yarn: 1.22.18

```

</details>

### Describe the bug

After Amplify.configure has been called and `Auth.oauth.redirectSignIn` and `responseType: 'code'` has been set, if you add query param `code` on any page you will be redirected to the URL set in `redirectSignIn` and the url params are removed. 

This interferes with f.ex GitHub OAuth app authorization flow.

### Expected behavior

This should not happen on any other path than the one set as `redirectSignIn`

### Reproduction steps

1. Configure Amplify (code snippet below)
2. Open browser to app
3. go to any path
4. add `?code=asjknd` to the end of URL
5. get redirected to /authorize

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```javascript
const amplifyConfig = {
  Auth: {
    mandatorySignIn: true,
    region: XXXXXX,
    userPoolId: XXXXXX,
    userPoolWebClientId: XXXXXX,
    oauth: {
      domain: HOSTED_UI_URL_HERE,
      scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
      redirectSignIn: `${window.location.origin}/authorize`,
      redirectSignOut: `${window.location.origin}/logout`,
      responseType: 'code',
    },
  },
};
```

**Comment by chrisbonifacio** [comment] 2022-10-04 15:38
Hey @mikkilevon 👋 thanks for raising this issue. We were able to consistently reproduce the described behavior. However, this is a known and expected behavior at the moment because of how Amplify listens for the code in the URL to be exchanged for Cognito credentials on redirect.

There was a PR opened before looking to address this and contain the consumption of the `code` query parameter only if an oauth flow was started. Please track it here and comment on it with your feedback for the team: https://github.com/aws-amplify/amplify-js/pull/8589

**Comment by dan-lovelace** [comment] 2022-11-25 21:50
I have a hacky workaround that may be worth sharing. I noticed Amplify uses history's `replaceState` method to handle the redirect: https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L2475. I overrode it temporarily to be a noop for any path that starts with `/oauth` then revert it after sign in failure (which will always happen because oauth codes other than Amplify's will be invalid).

```js
import { Amplify, Hub } from "aws-amplify";

// save current replaceState so we can revert to original later
const replaceState = window.history.replaceState;

// temporarily set replaceState with noop
if (window.location.pathname.startsWith("/oauth")) {
  window.history.replaceState = () => false;
}

// configure Amplify (this sets up the default redirect)
Amplify.configure(config);

// configure auth listener
Hub.listen("auth", (data) => {
  if (data.payload.event === "signIn_failure") {
    // revert replaceState to original
    window.history.replaceState = replaceState;
  }
});
```

This allows `code` parameters on any page whose pathname starts with `/oauth`. My specific use case was integrating Slack OAuth which also sends a `code` and I was able to capture the code then call `replaceState` to clean up the URL.

**Comment by liqwid** [comment] 2022-11-30 17:09
> However, this is a known and expected behavior at the moment because of how Amplify listens for the code in the URL to be exchanged for Cognito credentials on redirect.

This is never mentioned anywhere in the docs! Amplify does _extremely_ confusing redirects, this behavior can't be expected - library cannot have exclusive right to a _very common_ query param. Please fix this **ASAP**

**Closed** 2022-12-09 15:40 UTC
Labels: bug, Auth, React, OAuth
