### ISSUE TITLE
No resend verification code API for SMS MFA

### ISSUE THREAD

**Issue by viveksdf** [aws-amplify/amplify-js#9950] opened 2022-05-31 15:29 UTC
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

I am trying to implement resend OTP functionality in my application but there is no API available to do so. Here I am raising it as an enhacement so that we can be resend the OTP.

### Describe the solution you'd like

To have resendMFACode method implemented

### Describe alternatives you've considered

Alternative is to again call Auth.signIn API.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by AjanBikliqi** [comment] 2022-06-08 14:20
I did the sign in process again when user wanted to resend verification code and all that would do is send the verification code again so that did the job for me

**Comment by viveksdf** [comment] 2022-06-08 14:23
> I did the sign in process again when user wanted to resend verification code and all that would do is send the verification code again so that did the job for me

I am doing the same but instead there should a seperate API

**Comment by abdallahshaban557** [comment] 2022-11-10 15:18
closing this as a duplicate of #2010

**Closed by abdallahshaban557** 2022-11-10 15:18 UTC
Labels: feature-request
