### ISSUE TITLE
validationData not passed for "signInWithoutPassword"

### ISSUE THREAD

**Issue by tl1993** [aws-amplify/amplify-js#9136] opened 2021-11-01 15:05 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.35 GB / 12.29 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    @emotion/react: ^11.5.0 => 11.5.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/material: ^5.0.6 => 5.0.6
    @testing-library/jest-dom: ^5.14.1 => 5.14.1
    @testing-library/react: ^11.2.7 => 11.2.7
    @testing-library/user-event: ^12.8.3 => 12.8.3
    @types/jest: ^26.0.24 => 26.0.24
    @types/node: ^12.20.36 => 12.20.36
    @types/react: ^17.0.33 => 17.0.33
    @types/react-dom: ^17.0.10 => 17.0.10
    aws-amplify: ^4.3.3 => 4.3.3
    aws-amplify-react: ^5.1.4 => 5.1.4
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 4.0.3 => 4.0.3
    typescript: ^4.4.4 => 4.4.4
    web-vitals: ^1.1.2 => 1.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.0
    typescript: 4.4.4

```

</details>

### Describe the bug

When trying to pass validationData like this:
Auth.signIn({username:username,password:"",validationData:{email:email}}).....
the validation data in not reaching the createAuthChallenge lambda.

The solution in https://github.com/aws-amplify/amplify-js/issues/6731 seems to not work when trying to authenticate without password.

### Expected behavior

when doing console.log(event)
vailidationData should be avaliable under event.request.validationData.

### Reproduction steps

browser js code

Auth.signIn({username:username,password:"",validationData:{email:email}}).....
lambda trigger

exports.handler = (event, ctx, callback) => {
  console.log(event)
}

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
INFO	{
  version: '1',
  region: 'eu-west-1',
  userPoolId: 'xxxxxxxxxxx',
  userName: 'xxxxxxxxxx',
  callerContext: {
    awsSdkVersion: 'aws-sdk-unknown-unknown',
    clientId: '35h8i3ebu53tu2fo9f7mpg3c0a'
  },
  triggerSource: 'CreateAuthChallenge_Authentication',
  request: {
    userAttributes: {
      sub: '94bf0ab1-94ee-4d47-8c06-890d718fac10',
      'cognito:user_status': 'FORCE_CHANGE_PASSWORD'
    },
    challengeName: 'CUSTOM_CHALLENGE',
    session: []
  },
  response: {
    publicChallengeParameters: null,
    privateChallengeParameters: null,
    challengeMetadata: null
  }
}

```

</details>

### Manual configuration

Auth: {
      mandatorySignId: true,
      region: 'eu-west-1',
      userPoolId: 'eu-west-1-xxxxxx',
      userPoolWebClientId: "xxxxxxxxxxxxxx",
      ssr: true
    }});

**Comment by chrisbonifacio** [comment] 2021-11-01 16:57
Hi @tl1993  👋 how did you implement passwordless authentication? Did you follow this guide?
https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/

**Comment by tl1993** [comment] 2021-11-02 09:58
Hi,
I did implement passwordless authentication but i changed the createAuthChallenge because i need to send a SMS using an external provider. 
Also i need to pass a phone number and verify that it is the user phone number in another external system so i can't verify it with cognito phone number field. , i tried to send the phone number as a validationData.

**Comment by chrisbonifacio** [comment] 2021-11-02 19:40
@tl1993 I implemented passworldless authentication with sms today and I see what you mean about the validationData not being passed to the CreateAuthChallenge lambda event. However, this is outside the control of the Amplify library as it is up to Cognito to expose that to the trigger.

If I understand your use case correctly, why do you need to send the phoneNumber as metadata if the user provides it as the username which does show up in the event? Wouldn't you be passing in the same phoneNumber twice?

for example, this is the request event from my lambda

<img width="764" alt="Screen Shot 2021-11-02 at 1 28 57 PM" src="https://user-images.githubusercontent.com/16952986/139940957-7379f96e-e0db-43b5-a7ec-bcc1a6906862.png">

**Comment by chrisbonifacio** [comment] 2021-11-02 20:36
So, looking deeper into this, it seems that this is expected behavior and is documented in the Cognito docs here:

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#API_InitiateAuth_RequestSyntax

> The ClientMetadata value is passed as input to the functions for only the following triggers:
> 
> Pre signup
> 
> Pre authentication
> 
> User migration

...

> When you use the InitiateAuth API action, Amazon Cognito also invokes the functions for the following triggers, but it does not provide the ClientMetadata value as input:
> 
> Post authentication
> 
> Custom message
> 
> Pre token generation
> 
> Create auth challenge
> 
> Define auth challenge
> 
> Verify auth challenge

So, you might have to use a pre-authentication trigger to access the ClientMetaData and perform validation there.

That being said, closing this issue out as it is not a bug and/or addressable from the Amplify JS library.

**Closed by chrisbonifacio** 2021-11-02 20:36 UTC
Labels: Auth, pending-response

**Comment by ricardoribas** [comment] 2021-12-09 11:12
@chrisbonifacio there is any place where I can create an issue for cognito to analyze? I am having the same problem. I am implementing passwordless authentication on my application, but i need to distinguish between a sign-in made with the email address and a sign-in made with a phone number. The client metadata woud come in handy as i can mark the type of authentication made.
