### ISSUE TITLE
amazon social login in react

### ISSUE THREAD

**Issue by supun19** [aws-amplify/amplify-js#2708] opened 2019-02-14 09:30 UTC
** Social Login**
I am developing react webapp. I integrated amazon social login to my application
```
const federated = {
  google_client_id: '12323231321312pvi.apps.googleusercontent.com',
  amazon_client_id: 'amzn1.application-oa2-client.231231231412321',
};
```
then I warape the my component
```
 <Authenticator federated={federated} onStateChange={(authState, authData) => this.authStateChange(authState, authData)} >
            {this.state.authState === 'signedIn' && <App />}
          </Authenticator>
```

I have also added amazon client id to the identity pool as an authentication provider.
when signing I have received an error 

```{"__type":"NotAuthorizedException","message":"Token is not from a supported provider of this identity pool."}```

I have also integrated google social login it is working. which steps did I miss?

I have another problem How do I get id_token for the access aws resources.

**Comment by manueliglesias** [comment] 2019-02-15 23:48
Hi @supun19 

Can you confirm you see the Amazon identity provider when you run: 

```sh
aws cognito-identity describe-identity-pool --identity-pool-id "<your pool id>"
```

**Comment by supun19** [comment] 2019-02-16 00:00
Hi @manueliglesias 

It says
```
An error occurred (ResourceNotFoundException) when calling the DescribeIdentityPool operation: IdentityPool 'us-east-1:908199f9-794f-231232-1312312' not found.
```

**Comment by manueliglesias** [comment] 2019-02-16 00:46
@supun19 

Are you sure that's the correct identity pool id? Also, could you verify you are using the right credentials?

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by supun19** [comment] 2019-02-16 00:51
Yes, I have a double check I am also confusing. I check identity pool id and I also give administration access for a role ? and google signin working. I also check the identity pool there is amazon client Id.

**Comment by supun19** [comment] 2019-02-16 00:54
Hi @manueliglesias 
 Sorry I have change default region It gave me amazon client id

**Comment by manueliglesias** [comment] 2019-02-16 01:12
When I run the command with my identity pool id, I see something like this:

```json
{
    "IdentityPoolId": "xx-xxxx-x:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "IdentityPoolName": "cognitoxxxxxxxx_identitypool_xxxxxxxx",
    "AllowUnauthenticatedIdentities": false,
    "SupportedLoginProviders": {
        "accounts.google.com": "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
        "www.amazon.com": "amzn1.application-oa2-client.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "CognitoIdentityProviders": [
        {
            "ProviderName": "cognito-idp.xx-xxxx-x.amazonaws.com/xx-xxxx-x_XXXXXXXXX",
            "ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
            "ServerSideTokenCheck": false
        },
        {
            "ProviderName": "cognito-idp.xx-xxxx-x.amazonaws.com/xx-xxxx-x_XXXXXXXXX",
            "ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
            "ServerSideTokenCheck": false
        }
    ]
}
```

do you see an entry in yours for `"www.amazon.com"`?

**Comment by supun19** [comment] 2019-02-16 01:15
@manueliglesias  it something like this
```
{
    "IdentityPoolId": "us-east-1:xxxxxxxxxxxxxxxxxx",
    "IdentityPoolName": "webapp_identity_pool_dev",
    "SupportedLoginProviders": {
        "www.amazon.com": "amzn1.application-oa2-client.xxxxxxxxxx",
        "accounts.google.com": "xxxxxxxxx.apps.googleusercontent.com"
    },
    "CognitoIdentityProviders": [
        {
            "ServerSideTokenCheck": false,
            "ClientId": "xxxxxxxxxxxxxx",
            "ProviderName": "cognito-idp.us-east-1.amazonaws.com/xxxxxxxxxxxxx"
        }
    ],
    "AllowUnauthenticatedIdentities": true
}

```

**Comment by supun19** [comment] 2019-02-16 01:28
@manueliglesias I added identity providet to the cognito pool but also not working google login is working
```
{
    "IdentityPoolId": "us-east-1:xxxxxxxxxxxx",
    "CognitoIdentityProviders": [
        {
            "ProviderName": "cognito-idp.us-east-1.amazonaws.com/xxxxxxxxxx",
            "ServerSideTokenCheck": false,
            "ClientId": "xxxxxxxxxxx"
        }
    ],
    "AllowUnauthenticatedIdentities": true,
    "SupportedLoginProviders": {
        "accounts.google.com": "xxxxxxxxxxxx.apps.googleusercontent.com",
        "www.amazon.com": "amzn1.application-oa2-client.xxxxxxxxxxxxx"
    },
    "IdentityPoolName": "webapp_identity_pool_dev"
}
```

**Comment by akalana** [comment] 2019-02-17 05:07
Hi @supun19 @manueliglesias  ,
I am also trying to integrate amazon social login.Unfortunately, I've had this exact same issue.

**Comment by haverchuck** [comment] 2019-02-18 16:50
@supun19  (and possibly @akalana) - I think the issue might be that you seem to have entered the client_id in the cognito identity pool instead of the application id.  So you what you have in the 'federated' object is right, but the value in the identity pool should be something like 'amzn1.application.***'.  You can find this value in the security profile management screen in your Amazon developer account.

**Comment by haverchuck** [comment] 2019-02-18 20:58
I am going to close this issue as I think the cause was identified in my previous comment; however, please feel free to reopen this!

**Closed by haverchuck** 2019-02-18 20:58 UTC
Labels: Auth, pending-close-response-required

**Comment by supun19** [comment] 2019-02-22 03:35
Now its working thank you @haverchuck
