### ISSUE TITLE
Error when calling currentAuthenticatedUser()

### ISSUE THREAD

**Issue by pgbradbury** [aws-amplify/amplify-js#8485] opened 2021-06-22 11:32 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 80.92 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.7.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Safari: 14.1
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/ui-components: ^1.3.1 => 1.4.0 
    @aws-amplify/ui-react: ^1.2.0 => 1.2.2 
    @babel/core:  undefined ()
    @babel/eslint-parser: ^7.12.1 => 7.14.5 
    @babel/eslint-plugin: ^7.12.13 => 7.14.5 
    @babel/plugin-transform-react-jsx: ^7.10.4 => 7.14.5 
    @babel/preset-env: ^7.10.4 => 7.14.5 
    @babel/preset-react: ^7.10.4 => 7.14.5 
    @fullstory/babel-plugin-annotate-react: ^2.1.0 => 2.1.2 
    @fullstory/browser: ^1.4.9 => 1.4.9 
    @lambdatest/node-tunnel: ^3.0.0 => 3.0.1 
    @material-ui/core: ^4.11.0 => 4.11.4 
    @material-ui/icons: ^4.9.1 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.58 
    @material-ui/pickers: ^4.0.0-alpha.12 => 4.0.0-alpha.12 (3.2.2)
    @material-ui/pickers-adapter-date-fns:  undefined ()
    @material-ui/pickers-adapter-dayjs:  undefined ()
    @material-ui/pickers-adapter-luxon:  undefined ()
    @material-ui/pickers-adapter-moment:  undefined ()
    @reduxjs/toolkit: ^1.6.0 => 1.6.0 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @sentry/fullstory: ^1.1.5 => 1.1.5 
    @sentry/nextjs: ^6.7.0 => 6.7.1 
    @testing-library/jest-dom: 4.2.4 => 4.2.4 
    @testing-library/react: ^11.2.5 => 11.2.7 
    @testing-library/react-hooks: ^5.0.3 => 5.1.3 
    @types/jest: ^26.0.5 => 26.0.23 
    @types/material-ui: ^0.21.8 => 0.21.8 
    @types/node: ^14.14.33 => 14.17.3 (15.12.2, 11.15.54)
    @types/react: ^17.0.2 => 17.0.11 
    @types/react-dom: ^17.0.2 => 17.0.7 
    @typescript-eslint/eslint-plugin: ^4.14.2 => 4.27.0 
    @typescript-eslint/parser: ^4.14.2 => 4.27.0 
    @wojtekmaj/enzyme-adapter-react-17: ^0.4.1 => 0.4.1 
    amphtml-validator:  undefined ()
    amplify-ui-components-loader:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^4.0.2 => 4.1.0 
    axios: ^0.21.1 => 0.21.1 (0.19.2)
    babel-jest: ^26.1.0 => 26.6.3 
    bfj:  undefined ()
    cacache:  undefined ()
    chromedriver: ^85.0.1 => 85.0.1 
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    date-fns: ^2.21.3 => 2.22.1 (2.0.0-alpha.27)
    debug:  undefined ()
    devalue:  undefined ()
    enzyme: ^3.11.0 => 3.11.0 
    escape-string-regexp:  undefined ()
    eslint: ^7.19.0 => 7.28.0 
    eslint-config-prettier: ^7.2.0 => 7.2.0 
    eslint-plugin-babel: ^5.3.1 => 5.3.1 
    eslint-plugin-i18next: ^5.0.0 => 5.1.1 
    eslint-plugin-jest: ^24.1.3 => 24.3.6 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-prettier: ^3.3.1 => 3.4.0 
    eslint-plugin-react: ^7.22.0 => 7.24.0 
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    eslint-plugin-react-perf: ^3.3.0 => 3.3.0 
    eslint-plugin-sonarjs: ^0.5.0 => 0.5.0 
    eslint-plugin-unicorn: ^27.0.0 => 27.0.0 
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    i18next: ^19.8.9 => 19.9.2 
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    isomorphic-fetch: ^3.0.0 => 3.0.0 
    jest: ^26.1.0 => 26.6.3 
    jest-cucumber: ^3.0.0 => 3.0.1 
    jest-junit: ^11.1.0 => 11.1.0 
    jest-sonar-reporter: ^2.0.0 => 2.0.0 
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    material-table: ^1.69.1 => 1.69.3 
    md5: ^2.3.0 => 2.3.0 
    mini-css-extract-plugin:  undefined ()
    moxios: ^0.4.0 => 0.4.0 
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: ^10.2.1 => 10.2.3 
    next-redux-wrapper: ^7.0.2 => 7.0.2 
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    prettier: ^2.2.1 => 2.3.1 
    prop-types: ^15.7.2 => 15.7.2 (15.6.2)
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    react-dropzone: ^11.3.1 => 11.3.2 
    react-feather: ^2.0.8 => 2.0.9 
    react-i18next: ^11.8.9 => 11.11.0 
    react-image: ^4.0.2 => 4.0.3 
    react-redux: ^7.2.4 => 7.2.4 
    react-test-renderer: ^16.14.0 => 16.14.0 (17.0.2)
    react-vis: ^1.11.7 => 1.11.7 
    recast:  undefined ()
    redux-devtools-extension: ^2.13.9 => 2.13.9 
    redux-saga: ^1.1.3 => 1.1.3 
    redux-saga/effects:  undefined ()
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    selenium-webdriver: ^4.0.0-alpha.7 => 4.0.0-beta.4 
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    styled-components: ^5.3.0 => 5.3.0 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    ts-node: ^9.1.1 => 9.1.1 
    typescript: ^4.2.3 => 4.3.3 
    unistore:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    with-typescript:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 4.51.2
    npm: 7.4.3


```

</details>

### Describe the bug

AWS Support asked me to raise this here as they can't find a solution and will escalate to you.

I am building a Typescript/Next.js/React/Redux app and I am trying to pass the user object via the props from the _app.tsx page

I get a ```The user is not authenticated``` error when calling ```currentAuthenticatedUser()```. I am not using federated login.

### Expected behavior

The user object is returned with the logged in user.

### Reproduction steps

It happens as soon as you navigate to the base URL of the app.

### Code Snippet

```javascript
// Put your code below this line.
import React from "react"
import App, { AppInitialProps, AppContext } from "next/app"
import Amplify, { Auth, withSSRContext } from "aws-amplify"
import { CognitoUserInterface } from "@aws-amplify/ui-components"
import { AmplifyAuthenticator, AmplifySignIn } from "@aws-amplify/ui-react"
import { CssBaseline, ThemeProvider } from "@material-ui/core/"

import { config } from "../amplify.config"
import RadiateTheme from "../components/RadiateTheme"
import { wrapper } from "../state/store"

Amplify.configure({ ...config, ssr: true })

class Aura extends App<AppInitialProps> {
    public static getInitialProps = wrapper.getInitialAppProps(
        (store) =>
            async ({ Component, ctx }: AppContext) => {
                const auth = withSSRContext(ctx).Auth as typeof Auth
                const user: CognitoUserInterface =
                    await auth.currentAuthenticatedUser()
                store.dispatch({ type: "SETUSER", payload: user })
                return {
                    pageProps: {
                        ...(Component.getInitialProps
                            ? await Component.getInitialProps({
                                  ...ctx,
                                  store,
                              })
                            : {}),
                    },
                }
            }
    )
    public render() {
        const { Component, pageProps } = this.props

        return (
            <ThemeProvider theme={RadiateTheme}>
                <CssBaseline />
                <AmplifyAuthenticator>
                    <AmplifySignIn
                        hideSignUp
                        usernameAlias="email"
                        slot="sign-in"
                    />
                    <Component {...pageProps} />
                </AmplifyAuthenticator>
            </ThemeProvider>
        )
    }
}

export default wrapper.withRedux(Aura)

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
export const config = {
    aws_project_region: "eu-west-1",
    aws_cognito_identity_pool_id:
        "eu-west-1:xxx",
    aws_cognito_region: "eu-west-1",
    aws_user_pools_id: "eu-west-1_xxx",
    aws_user_pools_web_client_id: "xxx",
    oauth: {},
}
```

### Additional information and screenshots

1. AWS technical support couldn't solve and I still have a ticket open with them
2. If you hard code the user object the code works as expected

Package.json is the following

```json
"dependencies": {
        "@aws-amplify/ui-components": "^1.3.1",
        "@aws-amplify/ui-react": "^1.2.0",
        "@fullstory/browser": "^1.4.9",
        "@material-ui/core": "^4.11.0",
        "@material-ui/icons": "^4.9.1",
        "@material-ui/lab": "^4.0.0-alpha.56",
        "@material-ui/pickers": "^4.0.0-alpha.12",
        "@reduxjs/toolkit": "^1.6.0",
        "@sentry/fullstory": "^1.1.5",
        "@sentry/nextjs": "^6.7.0",
        "@types/material-ui": "^0.21.8",
        "@types/node": "^14.14.33",
        "@types/react": "^17.0.2",
        "@types/react-dom": "^17.0.2",
        "aws-amplify": "^4.0.2",
        "axios": "^0.21.1",
        "date-fns": "^2.21.3",
        "i18next": "^19.8.9",
        "material-table": "^1.69.1",
        "md5": "^2.3.0",
        "next": "^10.2.1",
        "next-redux-wrapper": "^7.0.2",
        "prop-types": "^15.7.2",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "react-dropzone": "^11.3.1",
        "react-feather": "^2.0.8",
        "react-i18next": "^11.8.9",
        "react-image": "^4.0.2",
        "react-redux": "^7.2.4",
        "react-vis": "^1.11.7",
        "redux-devtools-extension": "^2.13.9",
        "redux-saga": "^1.1.3",
        "styled-components": "^5.3.0"
    },
    "devDependencies": {
        "@babel/eslint-parser": "^7.12.1",
        "@babel/eslint-plugin": "^7.12.13",
        "@babel/plugin-transform-react-jsx": "^7.10.4",
        "@babel/preset-env": "^7.10.4",
        "@babel/preset-react": "^7.10.4",
        "@fullstory/babel-plugin-annotate-react": "^2.1.0",
        "@lambdatest/node-tunnel": "^3.0.0",
        "@testing-library/jest-dom": "4.2.4",
        "@testing-library/react": "^11.2.5",
        "@testing-library/react-hooks": "^5.0.3",
        "@types/jest": "^26.0.5",
        "@typescript-eslint/eslint-plugin": "^4.14.2",
        "@typescript-eslint/parser": "^4.14.2",
        "@wojtekmaj/enzyme-adapter-react-17": "^0.4.1",
        "babel-jest": "^26.1.0",
        "chromedriver": "^85.0.1",
        "enzyme": "^3.11.0",
        "eslint": "^7.19.0",
        "eslint-config-prettier": "^7.2.0",
        "eslint-plugin-babel": "^5.3.1",
        "eslint-plugin-i18next": "^5.0.0",
        "eslint-plugin-jest": "^24.1.3",
        "eslint-plugin-jsx-a11y": "^6.4.1",
        "eslint-plugin-prettier": "^3.3.1",
        "eslint-plugin-react": "^7.22.0",
        "eslint-plugin-react-hooks": "^4.2.0",
        "eslint-plugin-react-perf": "^3.3.0",
        "eslint-plugin-sonarjs": "^0.5.0",
        "eslint-plugin-unicorn": "^27.0.0",
        "isomorphic-fetch": "^3.0.0",
        "jest": "^26.1.0",
        "jest-cucumber": "^3.0.0",
        "jest-junit": "^11.1.0",
        "jest-sonar-reporter": "^2.0.0",
        "moxios": "^0.4.0",
        "prettier": "^2.2.1",
        "react-test-renderer": "^16.14.0",
        "selenium-webdriver": "^4.0.0-alpha.7",
        "ts-node": "^9.1.1",
        "typescript": "^4.2.3"
    },
```

**Comment by chrisbonifacio** [comment] 2021-06-22 14:57
Hello @pgbradbury :wave: I think the issue here is that `Auth.currentAuthenticatedUser` is throwing an error so it's blocking your page and authenticator from rendering because there may not be a user currently logged in at first. I'm not very familiar with TS so I removed all the type references but here's what I did to `getInitialProps` to get it working. I basically just wrapped `auth.currentAuthenticatedUser` in a try/catch.

```js
static getInitialProps = async ({ Component, ctx }) => {
    const auth = withSSRContext(ctx).Auth;
    try {
      const user = await auth.currentAuthenticatedUser();
      console.log({ user });

      return {
        pageProps: {
          ...(Component.getInitialProps
            ? await Component.getInitialProps({
                ...ctx,
                store,
              })
            : {
                user,
              }),
        },
      };
    } catch (error) {
      console.error(error);
    }
  };
```

Now when I log in, I get this logged from the server

```json
user: CognitoUser {
    username: 'a042760e-9b68-425d-9ea1-fa2efa783acb',
    pool: CognitoUserPool {
      userPoolId: 'eu-west-1_kjuqvDCHh',
      clientId: '5lb2e8ri6m91a9f9cofq7rmn6j',
      client: [Client],
      advancedSecurityDataCollectionFlag: true,
      storage: [UniversalStorage],
      wrapRefreshSessionCallback: [Function (anonymous)]
    },
    Session: null,
    client: Client {
      endpoint: 'https://cognito-idp.eu-west-1.amazonaws.com/',
      fetchOptions: {}
    },
    signInUserSession: CognitoUserSession {
      idToken: [CognitoIdToken],
      refreshToken: [CognitoRefreshToken],
      accessToken: [CognitoAccessToken],
      clockDrift: 0
    },
    authenticationFlowType: 'USER_SRP_AUTH',
    storage: UniversalStorage {
      cookies: [Cookies],
      store: [Object: null prototype]
    },
    keyPrefix: 'CognitoIdentityServiceProvider.5lb2e8ri6m91a9f9cofq7rmn6j',
    userDataKey: 'CognitoIdentityServiceProvider.5lb2e8ri6m91a9f9cofq7rmn6j.a042760e-9b68-425d-9ea1-fa2efa783acb.userData',
    attributes: {
      sub: 'a042760e-9b68-425d-9ea1-fa2efa783acb',
      email_verified: true,
      phone_number_verified: false,
      phone_number: '+15558085788',
      email: 'christopher.bonifacio@gmail.com'
    },
    preferredMFA: 'NOMFA'
  }
},
```

My page props logged from client
```
{
  pageProps: {
    user: CognitoUser {
      username: 'a042760e-9b68-425d-9ea1-fa2efa783acb',
      pool: [CognitoUserPool],
      Session: null,
      client: [Client],
      signInUserSession: [CognitoUserSession],
      authenticationFlowType: 'USER_SRP_AUTH',
      storage: [UniversalStorage],
      keyPrefix: 'CognitoIdentityServiceProvider.5lb2e8ri6m91a9f9cofq7rmn6j',
      userDataKey: 'CognitoIdentityServiceProvider.5lb2e8ri6m91a9f9cofq7rmn6j.a042760e-9b68-425d-9ea1-fa2efa783acb.userData',
      attributes: [Object],
      preferredMFA: 'NOMFA'
    }
  }
}
```

**Comment by pgbradbury** [comment] 2021-06-22 15:24
Hi,

You seem to have removed the redux wrapper as well. I wrapped the try-catch as you did around my existing code, however I still get an error

I am logging the following

1. getProps created store with state undefined
The user is not authenticated
3. getProps after dispatches has store state undefined
4. WrappedApp created new store with withRedux(_app_Aura) { initialState: undefined, initialStateFromGSPorGSSR: undefined }
props: {
  'data-element': 'Component',
  'data-source-file': '_app.tsx',
  dispatch: [Function: dispatch]
}

I need the initial state to have the user object defined.

**Comment by pgbradbury** [comment] 2021-06-22 15:25
Also, the current state of the user is a logged in authenticated user.

**Comment by chrisbonifacio** [comment] 2021-06-22 15:53
Ah okay, gotcha. So your app was already able to render the authenticator and you were able to log in through the form but you get this error after logging in?

**Comment by pgbradbury** [comment] 2021-06-22 15:57
Not exactly, I am building this in a docker container. So I have previously logged in and it's dropped a cookie. I have then rebuilt the container, so the user still persists in the cookie but is dropped from the server. I have tweaked a couple of things (it was throwing an error after this due to no state, I moved that) and it seems to now work with the try-catch solution. I will try some more scenarios, but I think this has fixed it.

**Comment by chrisbonifacio** [comment] 2021-06-22 16:04
Nice! Yeah, please let me know if you're able to persist user data to your Redux store. I'll still try to work Redux into my reproduction so I'm more familiar with the design pattern.

**Comment by pgbradbury** [comment] 2021-06-22 16:16
I started there but ended up using a library to help with the redux-nextjs integration

https://github.com/kirill-konshin/next-redux-wrapper

https://github.com/vercel/next.js/tree/canary/examples/with-redux-wrapper

**Comment by pgbradbury** [comment] 2021-06-22 22:35
OK, so I have tested this a few different ways. It seems to boil down to this at the moment.

On the first instance of a login the try and catch works, but no user is set, so the app breaks or you catch no user and do something.

If I refresh the app works. I assume this is all tied to amplify SSR logic and figuring out an authenticated user.

A hack would to force a refresh on catching no user, but that is really bad. I thought the whole point of withSSRContext was to make this work.

Any ideas?

P.S. I upgraded aws-amplify to 4.1.1, it made no difference.

**Comment by chrisbonifacio** [comment] 2021-06-23 06:23
I'm thinking since you're using redux and dispatching that action from getInitialProps, maybe you should add the Hub listener from Amplify to a useEffect so the client can dispatch that action that updates the redux store with the current user on a sign in event?

The action from getInitialProps sounds to me like it will only work if the user's already logged in which means credentials have been set to localStorage and/or the cookie exists. So that action would be updating the redux store when a user either reloads the page or comes back to the site at a later time, etc, but that sign in event needs to trigger its own dispatch to the store as well which can be done through the Hub.

**Comment by pgbradbury** [comment] 2021-06-29 14:44
Sorry for the late response, I have been trying a few things out.

The problem is that the server-side doesn't seem to be working at all. I can try with a logged-in user or log in from a clean state, either way, it doesn't pick up the user server-side. I am not sure why as I thought withSSRContext (an amplify component) was supposed to do that as a first-class integration into next.js

**Comment by chrisbonifacio** [comment] 2021-06-30 13:59
Hi @pgbradbury I can't confidently say that this is an issue with Amplify as I don't have any issues using `withSSRContext` outside of a redux project. I've cloned the `with-redux-wrapper` example from the links you shared before and have been messing around with it a bit and while I can get my server side code to log the authenticated user, I haven't figured out how to properly store that data in my redux store and/or get it from the store in my components. So, I'm still trying to figure out how to use them in tandem myself.

**Comment by pgbradbury** [comment] 2021-06-30 15:08
Hi @chrisbonifacio understood, but i'm not sure its redux related. It might be though, I am still working on it too and will post a solution if I find one. 

With regards to the Hub listener, this seems to be very similar to redux. The reason I don't think it will work is that it will listen for an auth event. However a user may already be logged in to the application and simply returning a few hours later. No event happens, but the app needs to find the user from the cookie.

**Comment by pgbradbury** [comment] 2021-07-05 16:45
This issue seems related, it was bot closed but people are still posting to it. #6555

**Comment by pgbradbury** [comment] 2021-07-06 10:08
@chrisbonifacio, OK I have stripped it all back and taken the SSR out. I made the auth call in an index.tsx instead. I am still getting the user not authenticated error, I am getting the following more detailed error from the catch block on the async call.

```
[ERROR] 51:08.525 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
```
 
Could you let me know where you are at with this, I have not changed the configuration from when it was working. This github ticket was generated from a paid support ticket and time really is of the essence now as it has been weeks.

**Comment by chrisbonifacio** [comment] 2021-07-06 14:43
@pgbradbury Okay, well this helps to narrow down the root issue. With those package versions I think the issue might actually just be duplicate dependencies between the scoped amplify packages. How are you importing and configuring `Auth`?

I removed `aws-amplify` and replaced my dependencies with yours. I am importing and configuring like so without issues so far.

```json
import { Auth } from "@aws-amplify/auth";
import { config } from "../amplify.config";

Auth.configure({ ...config });
```

**Comment by chrisbonifacio** [comment] 2021-07-06 14:51
With your dependencies, running the command from this [page](https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js)

resulted in this output

```json
@aws-amplify/core
@aws-amplify/ui-components
```

**Comment by pgbradbury** [comment] 2021-07-06 15:19
OK, so how is that happening, on my machine I just ran the command and it only shows

`@aws-amplify/core`

But it is only defined once in the package.json, the ticket I indicated to you says it fixed the issue by installing a specific version of the auth lib. What versions should be pinned to make this work and why are there conflicting libraries creating breaking changes.

**Comment by pgbradbury** [comment] 2021-07-06 15:56
I have upgraded to the latest versions which has removed the duplicates and I am rebuilding to see if that makes a difference.

**Comment by chrisbonifacio** [comment] 2021-07-06 16:48
Depending on what versions of the scoped packages you install, they are dependent on different versions of other packages. The latest versions should all be compatible with each other though. This is usually only an issue when incompatible versions of the scoped packages, or trying to use them along with `aws-amplify`. The Amplify class is designed as a [singleton](https://en.wikipedia.org/wiki/Singleton_pattern#:~:text=In%20software%20engineering%2C%20the%20singleton,mathematical%20concept%20of%20a%20singleton). and should only have one instance, otherwise there will be configuration issues.

**Comment by chrisbonifacio** [comment] 2021-07-06 18:09
@pgbradbury just wanted to give you a heads up as I just realized it. You will have to use `aws-amplify` if using Auth in an SSR context because `withSSRContext` seems to only be exported from there. None of the scoped packages export it because it's a utility to re-instantiate each package per request.

**Comment by pgbradbury** [comment] 2021-07-07 22:31
Hey, still working on this build, please don't tag auto close by a bot, I will respond once I have something, as I said its a paid support ticket.

**Comment by chrisbonifacio** [comment] 2021-07-08 02:02
@pgbradbury Apologies. My intention was not for this to be auto-closed, it would take a week of no response for the stale bot to do so. I labeled it as such more for the notification I get on my project board because I can tell just by looking at the board another comment was made on the issue since the bot removed the label. I prefer it over the email notification because I get so many from github already and I spend most of my time on here anyway.

I agree that the issue must've been occurring even before Redux if you were already getting that `Auth has not been configured correctly` error. However, I set up my reproduction app with the same Auth configuration you have, basically just used the `amplify.config` file you provided and everything seemed to work both client and server side.

Unless I could take a look at your project repository, it's not obvious to me where the configuration might need to be corrected. I've seen some have issues with the way `Amplify.configure` or `Auth.configure` is being called and the properties set. Maybe that could be part of the problem?

Here's my reproduction [app](https://github.com/chrisbonifacio/amplify-issues/tree/main/8485-ssr-auth) which has no Redux code, just the use of `withSSRContext` to pass each page the currently authenticated use as a prop. You just need to add the `amplify.config` file you shared before for it to work. I added two other pages that logs the user from props and shows whether it got the user from the client or the server.

So, the way I saw the problem was that if you're using the Amplify sign in component, you don't redirected to the next view so you're still on the same page. No request to the server was made for the user that just logged in and we're not storing this data anywhere. What I did was use the Hub to listen for the "signIn" event and set the user locally first just so I can keep the amplify sign in component and still get my user while remaining on the same page. This only happens once. If using a custom sign in form, you could simply redirect to the next page and your server side code should get the user and pass it through pageProps. My `getInitialProps` function is still getting the user on the server side any time the user navigates to another page after the sign in form has been used.

Let me know if this helps and I apologize again for making it seem like this would be auto-closed.

**Comment by chrisbonifacio** [comment] 2021-07-09 16:06
@pgbradbury The Auth configuration was likely due to the mismatching versions between the scoped packages. The SSR and user state management was the original and separate issue, I believe. If you're using the Amplify components to login, you either need to save the response/user data to state locally or even just reload the page/redirect when the `signIn` event happens from the Hub listener. Although, it sounded like you didn't want to have to reload the page on signIn, which is why I did it with local state in my app.

So, it's really just that one time 'signIn' event that needs to be handled before `withSSRContext` can get who the current authenticated user is every time the user from the server on subsequent page requests.

**Comment by pgbradbury** [comment] 2021-07-13 16:37
OK,

So I have still been struggling with this massively, so I completely replaced my _app.tsx and index.tsx with yours, with only minor code mods.

This is what I got

**Server console:**
```
{ error: 'The user is not authenticated' }
{ user: { fromClient: true } }
```

Client console:
```
{user: {…}}
user:
fromClient: true
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
```

Screenshot:
![image](https://user-images.githubusercontent.com/73958879/125491133-deb393bf-0005-4436-b634-30c64c1b8f2b.png)

**Comment by chrisbonifacio** [comment] 2021-07-13 19:43
Sorry to hear that. Would you be willing to jump on a call and take a look at this together? I think it might be easier to explain that way than over gh issues.

**Comment by pgbradbury** [comment] 2021-07-13 20:51
That would be amazing. What is the best way to organise that? I am on London time, but I'll happily do a call my evening time if that helps, assuming you are on Pacific time.

**Comment by chrisbonifacio** [comment] 2021-07-13 21:01
I'm on the East Coast of the U.S., so EST. I think you might have to go through the internal ticket you opened and set up a meeting through there or we could probably set something up faster if you want to email me at christopher.bonifacio@gmail.com 😄

**Comment by chrisbonifacio** [comment] 2021-07-16 14:16
Hey @pgbradbury , just wanted to follow up and see how it's going after our meeting. Let me know if you're in need of further assistance.

**Comment by chrisbonifacio** [comment] 2021-07-19 18:30
@pgbradbury Going to close this issue for now since we were able to address the original issue by handling the thrown error when attempting to get the current Authenticated User when not currently logged in with `getInitialProps`, as well as making sure the user data is being properly accessed and then passed as a prop to each page component as well as dispatched to the redux store.

That being said, it was a pleasure to jump on a call with you and work through it together. Please feel free to open a new issue with the details of any new blocker so we can track the different issues we're tackling. Thank you!

**Closed by chrisbonifacio** 2021-07-19 18:30 UTC
Labels: Auth, Next.js, React, SSR
