### ISSUE TITLE
Vue 3.x - export 'config' was not found in 'vue'

### ISSUE THREAD

**Issue by ghost** [aws-amplify/amplify-js#6756] opened 2020-09-09 03:16 UTC
**Describe the bug**
When trying to import the Vue UI components with `import '@aws-amplify/ui-vue'` in a fresh Vue 3.x app, the console throws the error message `export 'config' was not found in 'vue'`

**To Reproduce**

1. Create new Vue 3.x app with `vue create myamplifyproject`
2. Add Amplify packages `npm install aws-amplify @aws-amplify/ui-vue`
3. Import components in `src/main.js`
```javascript=
import Amplify from 'aws-amplify';
import '@aws-amplify/ui-vue';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
```
4. Start app with `npm run serve`

**Expected behavior**
App to start without any errors

**Additional context**
I guess it has to do with how Vue 3.x exports it different methods

**Comment by jordanranz** [comment] 2020-09-09 18:06
Since Vue 3.x is currently in beta we do not officially support it in Amplify. I'll mark this as a feature request to investigate this so we can prepare for the Vue 3.x official launch.

**Comment by chrisleyva** [comment] 2020-09-24 19:46
Hi @jordanranz , I am sure you are aware but Vue 3 was officially released last week.
Are you aware of any work-arounds to get this import to work in a Vue 3 project?

Thank you. We appreciate your work.

**Comment by csbszb** [comment] 2020-10-16 15:01
If you're looking for a way to use the `@aws-amplify/ui-components`, this is how I got it work in a new Vue 3 project.
I uninstalled the `@aws-amplify/ui-vue` library and then just added these lines to main.(ts|js) file:

```javascript
import { createApp } from 'vue';
import { applyPolyfills, defineCustomElements } from '@aws-amplify/ui-components/loader';

...

applyPolyfills().then(() => {  defineCustomElements(window); });

... 

const app = createApp(App);
app.config.isCustomElement = (tag) => tag.startsWith('amplify-');
```

Ref: [config.ignoredElements Is Now config.isCustomElement](https://v3.vuejs.org/guide/migration/global-api.html#config-ignoredelements-is-now-config-iscustomelement)

**Comment by amhinson** [comment] 2020-10-20 16:53
@chrisleyva For context, it looks like StencilJS, which we use for our UI components, is still working on Vue 3 support. 

https://github.com/ionic-team/stencil-ds-output-targets/pull/94

We will track this and update our library once the Stencil PR is released.

**Comment by krcummings1** [comment] 2020-10-27 17:41
> Since Vue 3.x is currently in beta we do not officially support it in Amplify. I'll mark this as a feature request to investigate this so we can prepare for the Vue 3.x official launch.

Does amplify support Vue 3 yet? I'm getting this error and am unsure if I did something wrong or if it's still unsupported.
`
 warning  in ./node_modules/@aws-amplify/ui-vue/dist/index.js

"export 'default' (imported as 'Vue') was not found in 'vue'`

**Comment by amhinson** [comment] 2020-10-27 17:45
@krcummings1 As mentioned in the comment above, Amplify does not have Vue 3 support yet due to our usage of StencilJS for the UI Components. Once the pending [PR](https://github.com/ionic-team/stencil-ds-output-targets/pull/94) is merged, we will work to upgrade our libraries soon after.

**Comment by IamManchanda** [comment] 2020-11-08 15:26
Thanks @csbszb it works for me atleast settings it up 

Looking at https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-vue/src/index.ts and https://v3.vuejs.org/guide/migration/global-api.html#config-productiontip-removed I feel that your solution should be correct ... will let you guys know if I am still stucked :)

**Comment by wlee221** [comment] 2020-12-04 22:18
> If you're looking for a way to use the `@aws-amplify/ui-components`, this is how I got it work in a new Vue 3 project.
> I uninstalled the `@aws-amplify/ui-vue` library and then just added these lines to main.(ts|js) file:
> 
> ```js
> import { createApp } from 'vue';
> import { applyPolyfills, defineCustomElements } from '@aws-amplify/ui-components/loader';
> 
> ...
> 
> applyPolyfills().then(() => {  defineCustomElements(window); });
> 
> ... 
> 
> const app = createApp(App);
> app.config.isCustomElement = (tag) => tag.startsWith('amplify-');
> ```
> 
> Ref: [config.ignoredElements Is Now config.isCustomElement](https://v3.vuejs.org/guide/migration/global-api.html#config-ignoredelements-is-now-config-iscustomelement)

Thanks for this @csbszb! This is the intended workaround while we work on vue3 support. Note that if you used `vue-cli` to bootstrap the project, you would need to add `isCustomElement` arguments to `vue.config.js` [as such](https://github.com/vuejs/vue-next/issues/1414#issuecomment-648998826).

**Comment by wlee221** [comment] 2020-12-04 22:43
As per official vue3 support, we are working on a plan that would support both Vue 1/2 and Vue 3. Keep reading if interested!

As you all have noted, Vue 3 deprecated global configuration `Vue.config` and scoped it down to an [instance level](https://v3.vuejs.org/guide/migration/global-api.html#config-ignoredelements-is-now-config-iscustomelement).  In doing so, Vue has deprecated `default export` so that's why you will see the `export 'config' was not found in 'vue'` error. Here's what the difference looks like:

```js
// Vue 2
import Vue from 'vue'; // I'm a default export!

Vue.config.ignoredElements = [/^amplify-/];

// Vue 3
import { createApp } from 'vue'; // now I'm a named export?!

const app = createApp({});
app.config.isCustomElement = tag => tag.startsWith('amplify-');
```
The problem is apparent — we cannot satisfy both versions because their configurations are almost mutually exclusive. Moreover, this approach doesn't work with Vue 3 if customer used `@vue/cli` as mentioned above. 

So we are looking to use stencil output binding (based on the PR @amhinson mentioned) to generate vue components. But this would only support vue 3 again, so we are trying to devise a plan that would satisfy all vue versions and minimize configuration complexity on the user end.

We will keep this issue open to track vue 3 support. Please feel to contribute or give suggestion as we work through this. Thanks!

**Comment by sammartinez** [comment] 2021-01-07 16:17
Hello! I wanted to provide an update here, we are currently planning work for support of Vue 3 into the UI Components. While we can't provide a timeline on when this will be released, this work has begun this sprint.

**Comment by modullar** [comment] 2021-01-29 23:14
@csbszb 
Although the chunk of code made the app works, I am still getting this error in the browser console:

```Uncaught TypeError: Cannot set property 'isCustomElement' of undefined```
I have the app assigned this way: `const app =  createApp(App).mount('#app')`

I wonder if the last line is important at all

**Comment by csbszb** [comment] 2021-01-30 10:47
Hey @modullar,

I think the problem is that with this line  `const app = createApp(App).mount('#app')` 
The app variable won't be an `App` type but whatever the `mount` function returns (`ComponentPublicInstance`)

If you split them like this it works fine:
```javascript
const app = createApp(App);

app.config.isCustomElement = (tag) => tag.startsWith('amplify-');
app.mount('#app');
```

**Comment by wlee221** [comment] 2021-05-03 19:10
Closing as our docs have been updated for Vue 3: https://github.com/aws-amplify/docs/pull/2880.

**Closed by wlee221** 2021-05-03 19:10 UTC
Labels: Amplify UI Components, Vue, feature-request
