### ISSUE TITLE
duplicated invocation to cognito /token endpoint

### ISSUE THREAD

**Issue by scott1028appaegis** [aws-amplify/amplify-js#7614] opened 2021-01-25 03:47 UTC
**Describe the bug**
Call to auth.<region>.amazoncognito.com/oauth2/token twice but 400 status returned from second one. Here we use same amplify configure. It might be set up twice with "same configure object", same appClientId, userPoolId, etc. All settings are the same and also I didn't use any amplify-component UI like `amplify-vue`.

**To Reproduce**
Steps to reproduce the behavior but you can not reproduce it every time. It's about approximately 5% that you can reproduce:

1. In browser, click "Sign in" with saml federated identityProvider ex: Azure.
2. Click the button for the identity provider
3. Provide username & password if prompted, and click Sign In in third-party IdP page and then wait for redirect process done.
4. observe your network monitor of chrome, sometimes you can find this problem.
5. You might need to repeat 1-30 times.

**Expected behavior**
1. auth token invocation should once always.
2. Same behavior and result should be always the same in every time event it causes error.
3. Also it should not be invoked twice about auth token API.

**Code Snippet**
```
  const configure = {...}
  Amplify.configure(configure);
  Amplify.configure(configure);   <-- with same object.
   ...

  <styled-button
       type="button"
       :key="idx"
      class="formLogin__button formLogin__button--idp"
      @click.prevent="() => samlSignIn({ idpProviderName })"
  >
     ...
  async samlSignIn({ idpProviderName }) {    <-- listen button clicked
      LOG('samlSignIn:', idpProviderName);
      await Auth.federatedSignIn({
        provider: idpProviderName,
        customState: idpProviderName,
      });
  },
  ...
  Hub.listen('auth', callback);    <-- listen auth event
```

**Screenshots**
![image](https://user-images.githubusercontent.com/59074640/105658568-ae5f0180-5f01-11eb-87dd-39ed9e4f35d4.png)

**What is Configured?**
```
"{
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:xxxxxxxxxxx",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_xxxxxx",
  "aws_user_pools_web_client_id": "xxxxxxx",
  "oauth": {
    "domain": "appaegis-sandbox.auth.us-east-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "profile",
      "openid",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "https://xxxxxx-sandbox.xxxxxxx.com/",
    "redirectSignOut": "https://xxxxxx-sandbox.xxxxxxx.com/"/signout",
    "responseType": "code"
  },
  "aws_appsync_graphqlEndpoint": "https://xxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_cloud_logic_custom": [
    {
      "name": "aegeanREST",
      "endpoint": "https://xxxxxx.execute-api.us-xxxx-1.amazonaws.com/sandbox",
      "region": "us-east-1"
    },
    {
      "name": "webhook",
      "endpoint": "https://xxxxxxx.execute-api.us-xxx-1.amazonaws.com/sandbox",
      "region": "us-east-1"
    }
  ],
  "aws_user_files_s3_bucket": "xxxxxxx-assets-sandbox",
  "aws_user_files_s3_bucket_region": "us-xxxx-xxx"
}"
```

**Smartphone (please complete the following information):**

- Device: x86_64
- OS: Linux Mint 20 Ulyana
- Browser Chrome 
- Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by scott1028appaegis** [comment] 2021-01-25 03:51
amplify-js sdk verison below:
```
  "dependencies": {
    "@babel/core": "^7.7.2",
    "@nuxtjs/moment": "^1.4.0",
    "aws-amplify": "^1.2.3",
```

**Comment by ericclemmons** [comment] 2021-01-26 16:50
@scott1028appaegis I noticed that you're using a very old version of `aws-amplify`.  The latest is:

> https://www.npmjs.com/package/aws-amplify/v/3.3.14

We have a check to prevent duplicate calls here, but that fix likely isn't in your version (which explains why I had difficulties reproducing):

https://github.com/aws-amplify/amplify-js/blob/7b5b23f9fa6f1c4934c631ab6bfc363b8d3eeac2/packages/auth/src/Auth.ts#L234-L240

Can you update & let me know if that resolves it for you? 🙏

**Comment by scott1028appaegis** [comment] 2021-01-27 01:13
@ericclemmons Thanks! Let me check and give it a try. This looks good. It might be able to resolve my problem.

**Comment by iartemiev** [comment] 2021-04-12 18:29
@scott1028appaegis,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:29 UTC
Labels: Auth, Can't reproduce, pending-close-response-required
