### ISSUE TITLE
Login Not Allowed

### ISSUE THREAD

**Issue by raquila** [aws-amplify/amplify-js#3402] opened 2019-06-05 12:56 UTC
**Describe the bug**
I have not tried to reproduce this login error using amplify-js but I assume I would get the same error.

If I set the policy to only allow administrators to create users, my existing cognito IdP user is not able to login. I get the error Login not allowed in the hosted ui login screen.. If I switch the policy to allow users to sign themselves up, the user is able to login. I want to disable users from being able to sign up but still allow users which already exist in cognito to login using their identity provider, how do I do this?

**To Reproduce**
1) Set Policy to Only Allow Administrators to create users

![image](https://user-images.githubusercontent.com/124973/58957644-fb132900-876e-11e9-94d9-fc8bc0bff765.png)

2) Try to login through the Hosted UI with a user that already exists in cognito as an identity provided user and get this error

![image](https://user-images.githubusercontent.com/124973/58957834-7d035200-876f-11e9-9894-efbb27ad7eba.png)

![image](https://user-images.githubusercontent.com/124973/58957521-c56e4000-876e-11e9-9cf0-b35f01ce6ff8.png)

3) Set Policy to Allow users to sign themselves up

![image](https://user-images.githubusercontent.com/124973/58957692-1b42e800-876f-11e9-8fec-7b4819ac15d2.png)

4) Login will work

Here are my attribute settings

![image](https://user-images.githubusercontent.com/124973/58957877-9efcd480-876f-11e9-893c-45923ff5596f.png)

**Comment by jordanranz** [comment] 2019-06-05 21:41
This seems to be a Cognito service specific question. Have you tried asking on the [AWS forum](https://forums.aws.amazon.com/forum.jspa?forumID=173)?

**Comment by raquila** [comment] 2019-06-06 00:50
I have but that forum doesn't seem to be too active with people answering questions.  I was hoping someone here could figure this out.

**Comment by raquila** [comment] 2019-06-06 12:40
@jordanranz Any idea on getting the product team's attention?

**Comment by jordanranz** [comment] 2019-06-06 17:39
@raquila, can you also try and open an AWS support case:
https://console.aws.amazon.com/support/home#/case/create?issueType=technical

In the meantime, I will try and get in touch with the service team.

**Comment by raquila** [comment] 2019-06-11 20:59
@jordanranz I don't have a technical support plan to open a ticket.

**Comment by jlee95** [comment] 2019-07-12 22:56
Can you give steps on how to reproduce this error and also provide your user pool configuration? 
I tried reproducing this through CLI and Hosted UI but both did not lead to this scenario.

Here's what I tried doing:
1. Create a user pool with default properties
2. SignUp and confirm a user
3. Login through CLI and hosted UI works
4. Set user pool to only allow admins to create user
5. Login still works with the same user

**Comment by raquila** [comment] 2019-07-12 23:57
@jlee95 Basic username/password users are not an issue.  The issue is when you are using a SAML IDP user.  Let me know if you need anymore than the steps listed above.

**Comment by mauerbac** [comment] 2020-05-07 17:12
Hi @raquila  - are you still looking for assistance with this?

**Comment by raquila** [comment] 2020-05-07 17:39
Yes this is still an issue.

**Comment by elorzafe** [comment] 2020-07-11 00:05
@raquila is the first time that user is login with the hosted UI? The first time is signing up and signing in.

Basically you can enable Hosted UI for 3rd party providers but not signup

**Comment by sammartinez** [comment] 2020-10-22 19:01
Hello @raquila, this looks to be specific to Amazon Cognito and not Amplify as we do not own the code, Hosted UI. Amplify JS is a pass through to Cognito and as @jordanranz has called out we do believe talking to Cognito via their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173). Resolving as this is unrelated to Amplify JS.

**Closed by sammartinez** 2020-10-22 19:01 UTC
Labels: Cognito, Service Team, bug
