### ISSUE TITLE
Saml endpoint Integration with Cognito

### ISSUE THREAD

**Issue by 2mahender** [aws-amplify/amplify-js#4543] opened 2019-12-10 04:53 UTC
I have configured aws cognito with adfs , i am able to get the saml response from adfs but its not getting redirected to cognito , can you please let me know how to do in react using amplify?
![samllogin](https://user-images.githubusercontent.com/58421352/70496820-13596b80-1b37-11ea-9318-9867e149cec1.PNG)

**Comment by tannerabread** [comment] 2022-11-11 17:56
Duplicate of #439

**Closed by tannerabread** 2022-11-11 17:56 UTC
Labels: feature-request, Cognito, OAuth
