### ISSUE TITLE
amplify-authenticator component prevents save password

### ISSUE THREAD

**Issue by srchulo** [aws-amplify/amplify-js#6782] opened 2020-09-12 19:03 UTC
**Describe the bug**
Browsers do not prompt to save username/password after logging in with amplify authenticator:

https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue

**To Reproduce**
1. Go to a login page with amplify authenticator on it
2. Enter username and password
3. Login

**Expected behavior**
Browsers should prompt you to save username/password.

**Additional context**
LastPass also doesn't prompt to save password after logging in.

**Comment by srchulo** [comment] 2020-09-21 02:16
@mauerbac thanks! I guess thought this was a bug since I would assume it would work with however browsers normally autodetect this? Sorry for putting into docs-- didn't realize I did that!

**Comment by jcardus** [comment] 2020-10-22 02:40
It doesn't even tell the browser to remeber the email / username. I'm tryed using inputPros and set autocomplete but nothing. There's no way the browser saves the user / password...

**Comment by ChristopheBougere** [comment] 2020-10-27 12:19
I'm having the same issue (with react).
The browser was prompting well with the old system, this is a regression with the new auth component.

**Comment by camhart** [comment] 2020-11-20 00:02
Is the shadow-root stuff new?  If so, that could be the cause (see https://bugs.chromium.org/p/chromium/issues/detail?id=746593).

**Comment by camhart** [comment] 2020-11-20 00:02
> I'm having the same issue (with react).
> The browser was prompting well with the old system, this is a regression with the new auth component.

What was the old system?  Do I just need to roll a version number back?

**Comment by ChristopheBougere** [comment] 2020-11-20 08:12
> > I'm having the same issue (with react).
> > The browser was prompting well with the old system, this is a regression with the new auth component.
> 
> What was the old system? Do I just need to roll a version number back?

I mean the [legacy one](https://docs.amplify.aws/ui-legacy/q/framework/react) (`aws-amplify-react` instead of `@aws-amplify/ui-react`), but going back the legacy doesn't sound as a good idea.

For my part, I decided to get rid of amplify UI (because of this and many other bugs I've been facing).
I built a custom one using [this tutorial](https://blog.logrocket.com/authentication-react-apps-aws-amplify-cognito/), you can have a look [here](https://github.com/claptime/claptime/pull/25/files) (React with hooks + AntDesign)

**Comment by ccate** [comment] 2020-12-16 21:02
https://stackoverflow.com/questions/16420898/chrome-safari-and-opera-do-not-remember-password-on-simple-form

**Comment by slewis77** [comment] 2020-12-22 22:26
Ironically (and frustratingly), when using the AmplifyAuthenticator it doesn't trigger LastPass for login, but after logging in, LastPass icons are added to the first input control on each page. Didn't happen with the aws-amplify-react version.

**Comment by mark-a-bailey** [comment] 2021-01-20 20:52
If you inspect the form, its because the name fields are missing and the browser wont trigger on email and password when only used in the id fields. How do we add custom fields to the input tag? I cant find it in the docs anywhere

**Comment by pegasign** [comment] 2021-01-25 12:23
Likewise, no sign of anywhere allowing modifcation of the form to include the required "name" fields. Firefox seems to be the only browser displaying amplify-authenticator without this regression

**Comment by bwindsor** [comment] 2021-01-26 13:09
You can add custom fields like this, however this doesn't solve the issue. I think it could be related to use of the shadow DOM, e.g. [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=649162) which has been around for over 4 years... 

[This page](https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands) and [this page](https://www.chromium.org/developers/design-documents/create-amazing-password-forms) explain what is required for autocompleting passwords to work. If you follow that stuff, it works, but shadow DOM seems to mess things up.

```tsx
<AmplifyAuthenticator>
  <AmplifySignIn
    slot={'sign-in'}
    formFields={[{
        type: 'email',
        inputProps: {autocomplete: 'username', name: 'email'}
    }, {
        type: 'password',
        inputProps: {autocomplete: 'current-password', name: 'password'}
    }]}
  />
</AmplifyAuthenticator>
```
Looks like it could be related to use of the shadow DOM.

**Comment by ClaudioVR** [comment] 2021-02-02 14:21
Same problem with Vue.js. Tried adding the formfields as above without any success. 

Am I missing something? Hard to believe this is even an issue...

**Comment by bwindsor** [comment] 2021-03-01 17:47
See also #5782

**Comment by wlee221** [comment] 2021-04-26 19:21
Hello, this is duplicate of #5782 so we will track the issue there. Please see https://github.com/aws-amplify/amplify-js/issues/5782#issuecomment-826968238 for more detail as well.

**Closed by wlee221** 2021-04-26 19:21 UTC
Labels: Amplify UI Components, feature-request
