### ISSUE TITLE
Can't upload images from my javascript app to Storage setup via the CLI

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-js#7526] opened 2021-01-06 11:39 UTC
I've added Storage via the CLI and given permission to Authenticated (read, write, delete) and Guest users (read only) and then pushed.

I've got an app that I have to log into (which is working) and then I've then got a form that tries to upload an image to the storage but its failing with 403 forbidden. I'm not sure where to go from here to get it to authenticate or to try to work out what the issue might be.

Any ideas?

**To Reproduce**

run ```amplify add Storage``` or ```amplify update storage``` if already added

![image](https://user-images.githubusercontent.com/1674590/103673206-39894f00-4f75-11eb-8ad0-7048d62e6ae6.png)

Then using this little helper:

```
import { Storage } from "aws-amplify";

export async function s3Upload(sourceFile, targetFilename) {
  const filename = targetFilename ?? `${Date.now()}-${sourceFile.name}`;

  const stored = await Storage.put(filename, sourceFile, {
    contentType: sourceFile.type,
  });

  console.info("S3 Response", stored);

  return stored.key;
}
```

Used in my ```onChange``` handler for my file input:

```
const handleFileChange = async (event) => {
  console.info("File changed", event.target.files[0]);
  const file = event.target.files[0];
  const attachment = await s3Upload(file);
  console.info("File uploaded to " + attachment );
}
```

When using the form I get this error in the console:

![image](https://user-images.githubusercontent.com/1674590/103673977-19a65b00-4f76-11eb-882b-f7039bd27aaf.png)

**Expected behavior**

Adding Storage and allowing the permissions I have for Authenticated users I would expect that I could push images up once logged in (Authenticated right?).

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 87.0.4280.88

**Additional context**
Not sure if this is related: https://github.com/aws-amplify/amplify-console/issues/1403

This issue was copied from https://github.com/aws-amplify/amplify-console/issues/1427 as I raised it in the wrong repo.

**Comment by PeteDuncanson** [comment] 2021-01-08 20:57
Hey @edwardfoyle thanks for looking at this. I'm using Google to login with, the fact I'm seeing my back office makes me think I'm logged in as the API is secured in the same way? Could I be missing something in the wiring up of the login or something?

Checking the request I get this back:

![image](https://user-images.githubusercontent.com/1674590/104063382-fe488380-51f3-11eb-8ba7-193e37044582.png)

Happy do to a screen share or similar if that would help?

**Comment by edwardfoyle** [comment] 2021-01-08 21:07
@PeteDuncanson if you're able to make other authenticated calls successfully then it seems like you have authenticated properly. Maybe read through the docs here: https://docs.amplify.aws/lib/auth/social/q/platform/js to make sure. Hopefully someone on the JS team can help you debug further

**Comment by amhinson** [comment] 2021-01-11 17:29
@PeteDuncanson Could you share your `aws-exports.js` file (remove sensitive data if needed) and more about how you are authenticating users in the app? Code snippets would be great 👍

**Comment by PeteDuncanson** [comment] 2021-01-12 22:08
Hey @amhinson,

Thanks for getting back. Requested goodies are below :)

aws_exports.js

```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://XXXX.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "XXXX",
    "aws_cloud_logic_custom": [
        {
            "name": "webFormHandlerAPi",
            "endpoint": "https://XXXXX.eu-west-1.amazonaws.com/live",
            "region": "eu-west-1"
        },
        {
            "name": "customerCsvExport",
            "endpoint": "https://XXXXX.execute-api.eu-west-1.amazonaws.com/live",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:XXXXX",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_XXXX",
    "aws_user_pools_web_client_id": "XXXX",
    "oauth": {
        "domain": "XXXX-live.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "image-store-liveXXXXX-live",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
```

Hastily hacked together code snippet, this should be the important bits:

```
import { s3Upload } from "../utils/S3Tools";

// My callback for the input field
  const handleFileChange = async (event) => {
    // No null check as I was hacking to try to get this working, don't judge ;)
    const file = event.target.files[0];
    console.info("File changed", event.target.files[0]);
    const attachment = file ? await s3Upload(file) : null;
    if (file && file.size > maxUploadFileSize) {
      alert(
        `Please pick a file smaller than ${maxUploadFileSize / 1000000} MB.`
      );
      return;
    }
    try {
      const attachment = file ? await s3Upload(file) : null;    // Fails here with 403 error
      setFieldValue("profilePictureUrl", attachment);
      setFieldTouched("profilePictureUrl", true);
      console.info("File uploaded", attachment);
    } catch (e) {
      console.error("Error uploading image", e);
    }
  };

// Other stuff cut out for ease

//My file upload input, elsewhere in my render method:
   <input
        type="file"
        name="profilePictureFilePicker"
        accept="image/png, image/jpeg"
        onChange={handleFileChange}
      />
```

**Comment by amhinson** [comment] 2021-01-13 16:42
Thanks for that info! Could you share more about how you're using Amplify Auth in your app?

**Comment by PeteDuncanson** [comment] 2021-01-13 16:44
We've got a Auth Provider that we wrap the whole App with:

```
import { CognitoUser } from "@aws-amplify/auth";
import { CognitoUserSession } from "amazon-cognito-identity-js";
import { CognitoHostedUIIdentityProvider } from "@aws-amplify/auth/lib/types";
import Amplify, { Auth } from "aws-amplify";
import React from "react";

export type UserContextType = {
  user: CognitoUser;
  isLoading: boolean;
  login: Function;
  googleLogin: Function;
  logout: Function;
  isAdmin: Function;
};

// Create a context that will hold the values that we are going to expose to our components.
export const UserContext = React.createContext<UserContextType | null>(null);

// Create a "controller" component that will calculate all the data that we need to give to our components bellow via the `UserContext.Provider` component.
// This is where the Amplify will be mapped to a different interface, the one that we are going to expose to the rest of the app.
export const UserProvider = ({ children }) => {
  const [user, setUser] = React.useState(null) as CognitoUser | any;
  const [
    userSession,
    setUserSession,
  ] = React.useState<CognitoUserSession | null>(null);
  const [isLoading, setIsLoading] = React.useState<boolean>(true);

  React.useEffect(() => {
    // Configure the keys needed for the Auth module
    Auth.configure({});

    // attempt to fetch the info of the user that was already logged in
    Auth.currentAuthenticatedUser()
      .then((user) => {
        setUser(user);
        Auth.currentSession().then((session) => {
          setUserSession(session);
        });
      })
      .catch(() => {
        setUser(null);
      })
      .finally(() => setIsLoading(false));
  }, []);

  // We make sure to handle the user update here, but return the resolve value in order for our components to be  able to chain additional `.then()` logic.
  // Additionally, we `.catch` the error and "enhance it" by providing a message that our React components can use.
  const login = (usernameOrEmail: string, password: string) =>
    Auth.signIn(usernameOrEmail, password)
      .then((cognitoUser) => {
        setUser(cognitoUser);
        Auth.currentSession().then((session) => {
          setUserSession(session);
        });
        return cognitoUser;
      })
      .catch((err) => {
        if (err.code === "UserNotFoundException") {
          err.message = "Invalid username or password";
        }
        throw err;
      })
      .finally(() => setIsLoading(false));

  const googleLogin = () =>
    Auth.federatedSignIn({ provider: CognitoHostedUIIdentityProvider.Google })
      .then((cognitoUser) => {
        setUser(cognitoUser);
        Auth.currentSession().then((session) => {
          setUserSession(session);
        });
        return cognitoUser;
      })
      .catch((err) => {
        if (err.code === "UserNotFoundException") {
          err.message = "Invalid username or password";
        }
        throw err;
      })
      .finally(() => setIsLoading(false));

  const logout = () =>
    Auth.signOut()
      .then((data) => {
        setUser(null);
        setUserSession(null);
        // We should clear out the DataStore incase we have different users using the same machine
        Amplify.DataStore.clear();
        return data;
      })
      .finally(() => setIsLoading(false));

  const isAdmin = () => {
    let isAdmin = false;
    if (userSession) {
      const groups = userSession.getAccessToken().payload["cognito:groups"];
      if (groups.includes("admin")) {
        isAdmin = true;
      }
    }

    console.info("Is Admin? " + isAdmin, userSession);

    return isAdmin;
  };

  // Make sure to not force a re-render on the components that are reading these values, unless the `user` value has changed.
  // This is an optimisation that is mostly needed in cases where the parent of the current component re-renders and thus the current component is forced to re-render as well.
  // If it does, we want to make sure to give the `UserContext.Provider` the same value as long as the user data is the same.
  // If you have multiple other "controller" components or Providers above this component, then this will be a performance booster.
  const values = React.useMemo(
    () =>
      ({
        user,
        isLoading,
        login,
        googleLogin,
        logout,
        isAdmin,
      } as UserContextType),
    [user, isLoading, userSession]
  );

  // Finally, return the interface that we want to expose to our other components
  return <UserContext.Provider value={values}>{children}</UserContext.Provider>;
};

// We also create a simple custom hook to read these values from.
// We want our React components to know as little as possible on how everything is handled
// so we are not only abtracting them from the fact that we are using React's context, but we also skip some imports.
export const useUser = () => {
  const context = React.useContext(UserContext);

  if (context === undefined) {
    throw new Error(
      "`useUser` hook must be used within a `UserProvider` component"
    );
  }
  return context;
};

```

**Comment by amhinson** [comment] 2021-01-13 17:14
In your `s3Upload` function, could you add this to confirm that there is an authenticated user when you are making the call:

```javascript
const user = await Auth.currentAuthenticatedUser();
console.log(user);

const stored = await Storage.put(filename, sourceFile, {
  contentType: sourceFile.type,
});
```

**Comment by PeteDuncanson** [comment] 2021-01-13 19:52
@amhinson done 👍 

![image](https://user-images.githubusercontent.com/1674590/104503390-e64c7780-55d8-11eb-8f34-e7487298c70c.png)

**Comment by amhinson** [comment] 2021-01-13 22:35
Hmm I'm still having no luck reproducing this with a federated Google user uploading a file to S3. This does appear to be similar to other issues such as:
https://github.com/aws-amplify/amplify-cli/issues/4055
https://github.com/aws-amplify/amplify-js/issues/5729
https://github.com/aws-amplify/amplify-js/issues/1094

I know there are a lot of potential solutions presented in those, but have you looked deeper into the roles/policies/groups as suggested in the other issues?

Another suggestion would be to create a sample app from scratch and document every single step to see if you experience the same behavior, since it looks like the original reproduction steps just start with `update storage` instead of `add storage`. If the same thing happens, then providing those complete reproduction steps here would be great for us to debug on our side. If you can't reproduce it with the new app, then you can compare what might be different in the policies & S3 bucket.

Let me know what you find! 👍

**Comment by chrisbonifacio** [comment] 2021-06-07 21:12
Hey, @PeteDuncanson ! 👋 Closing this for now. Please re-open if you're still experiencing this issue and require further assistance.

**Closed by chrisbonifacio** 2021-06-07 21:12 UTC
Labels: Can't reproduce, Storage, pending-close-response-required

**Comment by exx-betterteem** [comment] 2021-07-17 16:38
anyone solved this? I am getting 403 upon upload. I can confirm that user is authenticated.
![image](https://user-images.githubusercontent.com/85896622/126043758-2d718f66-da1f-4d8f-94f2-afc922c1a11f.png)

**Comment by PeteDuncanson** [comment] 2021-07-20 08:54
Nope, I still get it, I've assumed it a permissions issue somewhere along the line in my setup, just not sure where! I've more pressing issues I have my focus at the moment. Hoping to take another look at it in a few weeks. If you get its sorted please do let me know.

**Comment by Leandros** [comment] 2021-11-02 11:34
I'm having the same issue as well.

**Comment by Leandros** [comment] 2021-11-02 11:46
Hey @amhinson / @chrisbonifacio: I've uploaded the CLI created templates for inspection. 

Similar case compared to @PeteDuncanson. I've got an authenticated user. With some cognito groups. No further customizations.

Trying to upload throws a 403. 

[s3storage.zip](https://github.com/aws-amplify/amplify-js/files/7460315/s3storage.zip)

**Comment by shwetajoshi601** [comment] 2021-11-10 00:27
I am using a similar setup, but in my case I want to download an image file stored in S3. I get a 403 error for GetObject operation.
