### ISSUE TITLE
While in the mock mode, I cannot upload a file.  The `PUT` request is sent to the `https` endpoint instead of the `http`

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-js#5320] opened 2020-04-02 14:13 UTC
**Describe the bug**
While in the mock mode, I cannot upload a file.  The `PUT` request is sent to the `https` endpoint instead of the `http`

**Amplify CLI Version**
`4.13.4`

**To Reproduce**
- `amplify add auth`
- `amplify add storage`
- `amplify mock`
- observe message in terminal `Mock Storage endpoint is running at http://localhost:20005`
- try to upload a file
- go to Chrome's console
- observe error message `PUT https://localhost:20005/my-bucket-name/public/my-file.png?x-id=PutObject net::ERR_SSL_PROTOCOL_ERROR`

**Expected behavior**
to be able to upload a file and see it in `amplify/mock-data/S3/my-bucket` directory

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version: v10.13.0

**Comment by Amplifiyer** [comment] 2020-04-07 17:08
Transferring this issue to amplify-js. I believe the issue is with new major version release where underlying aws-sdk-js-v3 is not honoring the overridden end point protocol. I have an issue opened with them.

**Comment by sakhmedbayev** [comment] 2020-04-28 10:35
Is there any news on this issue? Please let us know.

**Comment by Afanasievov** [comment] 2020-05-07 19:27
Hi! Have the same behavior

Amplify CLI version: `4.18.1`
aws-amplify: `3.0.10`
aws-amplify-react: `4.1.19`

**Comment by elchinillo** [comment] 2020-05-23 17:21
Any update on this issue? Same behavior over here:

Amplify CLI: 4.20.0
aws-amplify@3.0.12

**Comment by lukeramsden** [comment] 2020-05-26 13:54
Also getting this issue, CLI version 4.20.0, `@aws-amplify/storage@3.1.9`, `aws-amplify@3.0.10`, `aws-sdk@2.675.0`.

**Comment by Amplifiyer** [comment] 2020-05-26 16:49
Hi please try with the latest version of amplify (try removing the node_modules and lock files if required.) There is currently another bug with Storage.Put which we are working on priority right now #5876

**Comment by BernhardSmuts** [comment] 2020-05-28 21:53
Same here. 

Some services need Https, especially with federated auths. 
Yet mock only serves over HTTP.

**Comment by elchinillo** [comment] 2020-05-30 18:41
Just upgraded to @aws-amplify/cli 4.21.0 and is still an issue.

**Comment by Amplifiyer** [comment] 2020-06-03 16:56
@elchinillo and @BernhardSmuts what's the amplify-js version are you using? Are you still facing issues with using Storage in mock mode?

**Comment by BernhardSmuts** [comment] 2020-06-05 10:45
Hi, @Amplifiyer.

I have recreated my test code for this and it is as follows:

My schema.graphql file has the following:

```
type imageCard @model {
  is: ID!
  name: String!
  image: S3Object!
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```
Using ReactJS, The select image and upload image functions are as follows:

```
const reader = new FileReader();

  const handleSelectImage = (evt) => {
    console.log("Handling Image Select");
    const file = evt.target.files[0];

    if (file) {
      reader.readAsDataURL(file);
    }

    reader.addEventListener(
      "load",
      async () => {
        console.log(reader);
      },
      false
    );
  };

  const handleUploadImage = () => {
    console.log("Uploading image");

    Storage.put("TestingImage.jpg", reader, {
      level: "public",
    })
      .then((result) => console.log(result))
      .catch((err) => console.log(err));
  };
```
This works fine when using with the actual AWS services... and after upload I get returned the key which in this case is `TestingImage.jpg`

I am hosting the ReactJS app using `($env:HTTPS="true") -and (npm start)`

However, the problem comes in when I try and mock the storage. I get the following:

In the console:

![image](https://user-images.githubusercontent.com/22454448/83866773-9cd5a900-a728-11ea-86b7-17a66c0d8e9b.png)

In the network tab:

![image](https://user-images.githubusercontent.com/22454448/83866949-dd352700-a728-11ea-8d0c-16dafc8a217c.png)
 
In the network request:

![image](https://user-images.githubusercontent.com/22454448/83867192-55035180-a729-11ea-9d1a-8c8e1e40e10e.png)

AWS mock server:

![image](https://user-images.githubusercontent.com/22454448/83867265-7106f300-a729-11ea-893d-de8bbbf1d1d9.png)

and the aws_exports file when running in mock is as follows:

![image](https://user-images.githubusercontent.com/22454448/83867608-f8ecfd00-a729-11ea-8479-6640a194a994.png)


To the best of my understanding, the S3 request is being done over HTTPS as can be seen in the network tab, but the AWS server is hosting the mock endpoint over HTTP. I have also allowed the Insecure setting in Google Chrome for the AWS endpoints.

**Comment by lukeramsden** [comment] 2020-06-05 10:50
I actually resorted to changing the AppSync endpoint port to 20005, on which I was running an `mitmproxy` command with a self-signed and system-wide trusted root certificate - and I modified my `/etc/hosts` file to redirect my `env:dev` S3 URL to another instance of `mitmproxy`, because the port for S3 is hardcoded in the JS library, which is very annoying.

**Comment by BernhardSmuts** [comment] 2020-06-05 10:56
> I actually resorted to changing the AppSync endpoint port to 20005, on which I was running an `mitmproxy` command with a self-signed and system-wide trusted root certificate - and I modified my `/etc/hosts` file to redirect my `env:dev` S3 URL to another instance of `mitmproxy`, because the port for S3 is hardcoded in the JS library, which is very annoying.

Cool, thanks will try something like this. The whole point of mock it to not have to go through all those configs. It would be nice if they could let you define the SSL env to run mock on.

**Comment by lukeramsden** [comment] 2020-06-05 12:05
I agree completely, there was a relevant conversation [here](https://github.com/aws-amplify/amplify-js/pull/3806/files/5c218499ee22a6ab1f671177a69c036814480bf5#diff-c7c081aa778dae8f92ac9eee463ebaff) but it still feels like a design oversight. 

These are the commands I'm using with [mitmproxy](https://docs.mitmproxy.org/stable/tools-mitmdump/)
```bash
mitmdump -p 20006 --mode reverse:http://192.168.1.109:20002/
mitmdump -p 443 --mode reverse:http://192.168.1.109:20005/
```

And then you add an entry in `/etc/hosts`:
```bash
$ cat /etc/hosts
# other stuff
# ...
127.0.0.1 apps3bucketname-dev.s3.eu-west-2.amazonaws.com
```

And then remove the "dangerously_connect_etc_etc" entries from your aws_exports.

**Comment by elchinillo** [comment] 2020-06-06 18:58
> @elchinillo and @BernhardSmuts what's the amplify-js version are you using? Are you still facing issues with using Storage in mock mode?

I'm using aws-amplify@3.0.11

Here is what I get when I run `npm list | grep amplify`, I'm hopping this gets you more details.

```
npm list | grep amplify
├─┬ aws-amplify@3.0.11
│ ├─┬ @aws-amplify/analytics@3.1.10
│ │ ├── @aws-amplify/cache@3.1.10 deduped
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ ├─┬ @aws-amplify/api@3.1.10
│ │ ├─┬ @aws-amplify/api-graphql@1.0.12
│ │ │ ├── @aws-amplify/api-rest@1.0.12 deduped
│ │ │ ├── @aws-amplify/auth@3.2.7 deduped
│ │ │ ├── @aws-amplify/cache@3.1.10 deduped
│ │ │ ├── @aws-amplify/core@3.2.7 deduped
│ │ │ ├── UNMET PEER DEPENDENCY @aws-amplify/pubsub@3.0.11 deduped
│ │ ├─┬ @aws-amplify/api-rest@1.0.12
│ │ │ ├── @aws-amplify/core@3.2.7 deduped
│ │ └── UNMET PEER DEPENDENCY @aws-amplify/pubsub@^2.1.1
│ ├─┬ @aws-amplify/auth@3.2.7
│ │ ├── @aws-amplify/cache@3.1.10 deduped
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ ├─┬ @aws-amplify/cache@3.1.10
│ │ └── @aws-amplify/core@3.2.7 deduped
│ ├─┬ @aws-amplify/core@3.2.7
│ ├─┬ @aws-amplify/datastore@2.1.0
│ │ ├── @aws-amplify/api@3.1.10 deduped
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ │ ├── UNMET PEER DEPENDENCY @aws-amplify/pubsub@3.0.11 deduped
│ ├─┬ @aws-amplify/interactions@3.1.10
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ ├─┬ @aws-amplify/predictions@3.1.10
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ │ ├── @aws-amplify/storage@3.2.0 deduped
│ ├─┬ UNMET PEER DEPENDENCY @aws-amplify/pubsub@3.0.11
│ │ ├── @aws-amplify/auth@3.2.7 deduped
│ │ ├── @aws-amplify/cache@3.1.10 deduped
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ ├─┬ @aws-amplify/storage@3.2.0
│ │ ├── @aws-amplify/core@3.2.7 deduped
│ ├── @aws-amplify/ui@2.0.2
│ ├─┬ @aws-amplify/xr@2.1.10
│ │ └── @aws-amplify/core@3.2.7 deduped
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.10
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.10
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/datastore@2.1.0
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api-graphql@1.0.12
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.10
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.10
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.10
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.10
```

**Comment by Amplifiyer** [comment] 2020-06-09 18:23
@elchinillo can you try with the latest aws-amplify version and not the amplify-cli? Regarding the https end point, it is outside the scope of this issue. Please open a new feature request for that.

**Comment by elchinillo** [comment] 2020-06-10 01:22
I'll try again over the weekend. Regarding the https endpoint, isn't that why this issue started?

**Comment by Amplifiyer** [comment] 2020-06-10 01:46
> 
> 
> I'll try again over the weekend. Regarding the https endpoint, isn't that why this issue started?

No, the issue was started because amplify-js library was **incorrectly** sending requests to https endpoint instead of the server running on http end point.

**Comment by sammartinez** [comment] 2020-07-09 22:29
@elchinillo were you able to test the latest? Please let us know.

**Closed** 2020-07-18 00:00 UTC
Labels: React Native, Storage, pending-close-response-required, version-3
