### ISSUE TITLE
[Typescript] Error: No pubsub module applied for subscription when attempting to create subscription.

### ISSUE THREAD

**Issue by Bluepuff71** [aws-amplify/amplify-js#10287] opened 2022-09-02 12:15 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 116.57 GB / 127.90 GB
  Binaries:
    Node: 16.15.0 - E:\x64\nodejs\node.EXE
    npm: 8.18.0 - E:\x64\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @aws-amplify/ui-vue: ^2.4.19 => 2.4.19
    @popperjs/core: ^2.11.6 => 2.11.6
    @rushstack/eslint-patch: ^1.1.4 => 1.1.4
    @types/node: ^16.11.47 => 16.11.56
    @vitejs/plugin-vue: ^3.0.1 => 3.0.3
    @vue/eslint-config-prettier: ^7.0.0 => 7.0.0
    @vue/eslint-config-typescript: ^11.0.0 => 11.0.0
    @vue/tsconfig: ^0.1.3 => 0.1.3
    aws-amplify: ^4.3.34 => 4.3.34
    bootstrap: ^5.2.0 => 5.2.0
    bootswatch: ^5.2.0 => 5.2.0
    eslint: ^8.21.0 => 8.23.0
    eslint-plugin-vue: ^9.3.0 => 9.4.0
    npm-run-all: ^4.1.5 => 4.1.5
    pinia: ^2.0.17 => 2.0.21
    prettier: ^2.7.1 => 2.7.1
    typescript: ~4.7.4 => 4.7.4
    vite: ^3.0.4 => 3.0.9
    vite-plugin-checker: ^0.5.0 => 0.5.0
    vue: ^3.2.37 => 3.2.38
    vue-router: ^4.1.3 => 4.1.5
    vue-tsc: ^0.39.5 => 0.39.5
  npmGlobalPackages:
    @angular/cli: 14.2.1
    @aws-amplify/cli: 9.2.1
    npm: 8.18.0
```

</details>

### Describe the bug

When attempting to create a subscription, the error: `Error: No pubsub module applied for subscription` is thrown.

I believe this has something to do with line 29 of GraphQLAPI.ts: `import PubSub from '@aws-amplify/pubsub';` not working correctly.

When putting`import PubSub from '@aws-amplify/pubsub';` into my `main.ts` the app no longer starts, giving the error: `TypeError: Object.setPrototypeOf: expected an object or null, got undefined`.

### Expected behavior

The subscription is created with no issue.

### Reproduction steps

Install any version of aws-amplify after 4.3.31.
Start the app
Attempt to create a subscription

### Code Snippet

```typescript
// Put your code below this line.
function createSubscribe() {
  API.graphql(graphqlOperation(onCreateX)) as Observable<any>;
}
```

### Log output

<details>

```
// Put your logs below this line
Error: No pubsub module applied for subscription

```

</details>

### aws-exports.js

```javascript

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7d085aec-f2b1-4b27-970e-xxx",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xxx",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://xxx.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "xxx",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
```

### Additional information and screenshots

Downgrading to 4.3.31 fixes this issue.

**Comment by stocaaro** [comment] 2022-09-07 19:09
Thank you for the great detail. I have been able to reproduce this issue and have a change in PR that fixes the issue in the example app I'm testing with.

**Comment by stocaaro** [comment] 2022-09-09 20:09
As mentioned above, I have been able to reproduce this issue. In testing out the above fix, I thought my testing of the fix was still failing due to issues with package linking, but have confirmed with the latest release that the bug while fixed in the apparently relate React issue (#10295) still exists for Vue and I will continue troubleshooting.

**Comment by stocaaro** [comment] 2022-09-21 15:39
I have a [tested fix out for PR](https://github.com/aws-amplify/amplify-js/pull/10353). I have tested this change against the vue sample app I had used to reproduce this issue and the change resolves the problem. I'll keep you up to date as we get this reviewed and released.

Thanks, Aaron

**Comment by stocaaro** [comment] 2022-09-21 21:56
The fix has been merged and will be available on the `unstable` tag shortly. The full release that you can auto-upgrade is expected to be out a week from tomorrow.

**Comment by dreamorosi** [comment] 2022-09-28 11:02
I'm seeing this also with React + vite. I have tried the `unstable.5` and `unstable.6` releases which were published around the time of the comment above but none worked.

Hopefully the actual release fixes it and we don't have to wait for another week.

**Comment by voodootikigod** [comment] 2022-09-29 15:04
@stocaaro just checking if that timeline is still valid?

**Comment by abdallahshaban557** [comment] 2022-10-01 00:07
We have now released the fix in our latest version. Please inform us if you are still facing an issue!

**Comment by voodootikigod** [comment] 2022-10-03 15:00
Verified against my local codebase and things are golden. Thank you!

**Closed** 2022-10-03 17:10 UTC
Labels: GraphQL, pending-response, p1

**Comment by dreamorosi** [comment] 2022-10-03 19:52
I have also verified and it seems that the issue is fixed. I'll open another issue in case it's not after more extensive tests.
