### ISSUE TITLE
Auth.signIn takes something between 10 seconds and up to more than a minute depending on device (React Native)

### ISSUE THREAD

**Issue by liebharc** [aws-amplify/amplify-js#10521] opened 2022-10-22 18:39 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```

# Put output below this line
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600XT 6-Core Processor
    Memory: 9.84 GB / 31.93 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.11.0 - ~\AppData\Local\pnpm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)
  npmGlobalPackages:
    cdk: 2.47.0
    yarn: 1.22.19
# Dependencies which we use on Production, we did update everything on dev and confirmed that the issue appears with the lastest dependencies as well
react-native: 0.69.4 # We haven't enabled Hermes yet
amplify: 4.3.29
amazon-cognito-identity-js: "^5.2.10"

```

</details>

### Describe the bug

We got reports from users that the login didn't work in our React Native app on their Android and iOS devices. We were able to reproduce this on different test devices and found that the login works, but it's awfully slow. Often Auth.signIn takes 10 to 15 seconds. On some devices it needs more than a minute. Even worse, the UI isn't reacting for the first 5 seconds on most devices and so no loading indicator is shown. Of course, users then believe that the login is totally broken and give up. 

We are also running the same code base on the web with react-native-web and logins take 3 seconds there (with no UI freezing).

In a week of investigation we found that the issue is caused by https://github.com/aws-amplify/amplify-js/issues/3444 which it seems was closed without resolution. It however helped us find a very dirty workaround (which is explained below) as it identifies BigInteger.modPow as root cause for this issue, which we found is true for us as well.

### Expected behavior

Auth.signIn should take only up to 3 seconds as it does for our web version and if the workaround (see Code Snippet) is applied.

### Reproduction steps

Steps we took about 12 weeks ago as we started this project:

1. Install amplify and amazon-cognito-identity-js to a react native starter project (we don't use expo)
2. Implement a button which calls Auth.signIn 
3. Use the button and observe on how long it takes for the promise to return and/or for a Hub event to occur

### Code Snippet

Since this issue is critical for us (our customers stop using the app immediately), we applied a workaround and utilize react-native-modpow to speed up the modpow calculation in BigInteger.js. For this we replace the bnModPow function in amazon-cognito-identity-js with:

```javascript
...
import nativeModPow from 'react-native-modpow';
export default BigInteger;
...
function bnModPow(e, m, callback) {
  const nresult = nativeModPow({
    target: this.toString(16),
    value: e.toString(16),
    modifier: m.toString(16),
  });

  const result = new BigInteger(nresult, 16);
  callback(null, result);
  return result;
}
...
```

As this is super dirty, we would love to get rid of this workaround as quickly as possible.

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

We use Amplify only for the frontend and deploy the backend with cdk. This is the code which configures amplify with the output which we obtain from cdk:

```js
Amplify.configure({
    storage: AwsAsyncStorage,
    aws_project_region: awsexports.region,
    aws_cognito_region: awsexports.region,
    aws_user_pools_id: awsexports.userPoolId,
    aws_cognito_identity_pool_id: awsexports.identityPoolId,
    aws_user_pools_web_client_id: awsexports.userPoolClientId,
    aws_cloud_logic_custom: [
      {
        name: 'restapi',
        endpoint: awsexports.apiEndpoint,
        region: awsexports.region,
      },
    ],
    auth: {
      type: 'AMAZON_COGNITO_USER_POOLS',
      jwtToken: async () =>
        (await Auth.currentSession()).getAccessToken().getJwtToken(),
    },
    aws_appsync_graphqlEndpoint: awsexports.graphEndpoint,
    aws_appsync_region: awsexports.region,
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_appsync_token: async () =>
      (await Auth.currentSession()).getAccessToken().getJwtToken(),
  });
```

### Manual configuration

```json
{
  "apiEndpoint": "https://ID.execute-api.eu-central-1.amazonaws.com/prod/",
  "graphEndpoint": "https://ID.appsync-api.eu-central-1.amazonaws.com/graphql",
  "identityPoolId": "eu-central-1:ID",
  "region": "eu-central-1",
  "userPoolClientId": "ID",
  "userPoolId": "eu-central-1_ID",
}
```

### Mobile Device

OnePlus Nord2 and iPhone 5s as well as emulator devices and some customer devices

### Mobile Operating System

Android 12, iOS 12.5.6

### Mobile Browser

React Native

### Mobile Browser Version

React Native 0.69.4

### Additional information and screenshots

We took a look at https://github.com/aws-amplify/amplify-js/issues/5539 but the issue described here is different in that it happens on iOS as well and isn't related to network wait times.

**Comment by MatthewChon** [comment] 2022-10-24 19:23
Bump

**Comment by liebharc** [comment] 2022-10-25 06:41
Thanks to all reactions so far and for putting this into progress 😊

There was a question yesterday about why we use amazon-cognito-identity-js. Looks like the comment was removed, but since we did some backtracking yesterday to answer this question I'll still post the details anyway:

We call Amplify ourselves:

```js
...
import { Auth } from 'aws-amplify';
...
const signIn = useCallback(async () => {
    try {
      if (!email) {
        setMessage(t('auth.validation.usernameMissing'));
        return;
      }
      if (!password) {
        setMessage(t('auth.validation.passwordMissing'));
        return;
      }

      await Auth.signIn({
        username: email.trim(),
        password: password.trim(),
      });
     ....
  }, [email, password, setMessage, dispatch, props, t]);
```

amazon-cognito-identity-js is then being used by Amplify. I've added our Amplify configure call to the initial issue description in case this is due to our configuration. We use cdk for the backend and Amplfiy for the frontend, which made it a little harder to put the configuration together.

We also need amazon-cognito-identity-js as direct dependency for two reasons:

1. Without it, we get an error message that a native dependency is missing, I'll add the message in a couple of minutes. Note that we use React Native, but don't use Expo.
2. We use amazon-cognito-idenity-js directly to workaround an issue we found as we tried to answer a custom auth challenge (defined with defineAuthChallenge, createAuthChallenge, verifyAuthChallengeResponse on the backend) with Amplify. I can give you more details about this this is helpful, but don't want to sidetrack the conversation.

**Comment by tannerabread** [comment] 2022-11-01 02:22
Probably related #5539

**Comment by liebharc** [comment] 2022-11-28 16:39
Hi @chrisbonifacio , is there any update on this one or anything required to allow progress?

**Comment by liebharc** [comment] 2022-11-30 20:52
As there is already a native method for modpow available, [this change](https://github.com/liebharc/amplify-js/commit/a9c76e2e6bbe96c3188eaa1f691021e7b92417c1) should be enough to address this issue. I would give it some more testing and then open a PR if that's ok.

**Comment by chrisbonifacio** [comment] 2022-11-30 21:13
Hey, @liebharc! That's totally okay, and appreciate you taking a crack at this! I'll ping the team to get your PR reviewed once it's opened.

**Comment by liebharc** [comment] 2022-12-01 16:20
Hi @chrisbonifacio , the more I work on this the more it appears that code for handling this issue was already in place at some point before. I think the best way to proceed is to restore this code and get it fully working again, but I fail to understand the mechanism, so perhaps you have an idea?

What I found:

- [The package.json of amazon-cognito-identity-js](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/package.json) has a "react-native" config which specifies an alternative entry point "enhance-rn.js"
- [enhance-rn.js](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/enhance-rn.js) then patches BigInteger to use a native modPow. It also patches a second method which looks nice.
- The package.json config also seems to try to enable a [native version of StorageHelper](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/StorageHelper-rn.js). These changes are necessary so that users remained logged in in React Native. We have done the same change a couple of months ago in our app and were wondering back in the time, that this wasn't very obvious. If we would get this code working again then react native users would have a better out of the box experience.

Now, what I don't understand is what the "react-native" block in the package.json of amazon-cognito-identity-js is supposed to do. [Neither npm nor yarn specify this block](https://classic.yarnpkg.com/lang/en/docs/package-json/). I guess what would need to happen is that depending on the project configuration it either uses the main or react-native entry point so that web projects (and all other platforms) don't run into issue due to react-native specific code, while react-native projects benefit from the native code. I'm not aware that there is such a feature in npm/yarn/pnpm. Do you or the team have any information about how this should work?

Overall, I'm a little worried that I break the code for all non-react-native users and that the [check I put in place on my branch](https://github.com/liebharc/amplify-js/commit/a9c76e2e6bbe96c3188eaa1f691021e7b92417c1) isn't sufficient to prevent this. Therefore I hope that if we understand how the solution worked in the past, that we can recreate this and have a reliable way to handle different platforms correctly.

**Comment by AllanZhengYP** [comment] 2022-12-14 20:13
hi @liebharc 

This issue seems to be related to #5539, which was possibly caused by a React Native dualstack IP resolution issue. The thread mentioned an workaround to patch the RN Android DNS factory class([link](https://gist.github.com/danmaas/c60af5fed9f55d2bc616ce302696540d)). Can you try the workaround mentioned above and verify whether it works for you?

**Comment by liebharc** [comment] 2022-12-14 21:48
Hi @AllanZhengYP , I tried the solutions mentioned in #5539 with no success before opening this issue. I also followed some of the diagnostic steps provided and didn't see the network traffic patterns mentioned in the ticket. So this ticket and #5539 are two different root causes for the "login being slow" symptom.

As mentioned in my previous comment the fix for this issue is mostly already in the code base, but the necessary changes don't get activated (more details are in my previous comment). In fact it seems like everything had be in place at some point, but some got broken somewhere in the past. What we would need to understand is how to enable the existing native extensions on react native again, but only on react native. 

Personally I feel like we are close in fixing it again. If we only get some insight in how react native specific code pieces were handled in the past.

**Comment by liebharc** [comment] 2023-01-14 10:04
We've recently switched to the Hermes engine and while retesting this issue we found that it was fixed! We looked further into it and apparently React Native Hermes considers the `react-native`section in the [package.json of amazon-cognito-identity-js](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/package.json) and loads the React Native enhancements mentioned there.

I still don't understand how this loading works, or why React Native didn't load it before we switched to Hermes. But this issue therefore isn't an amplify issue. So apologies for that.

If someone else encounters this issue:

- An indication that you're dealing with this issue and e.g. not with https://github.com/aws-amplify/amplify-js/issues/5539 is that the UI doesn't react for a few seconds. E.g. if you show a loading spinner after `await Auth.signIn` then the loading spinner won't appear for a few seconds.
- If you're still uncertain if you're facing this issue, then you might want to use a debugger or console logs to ensure that [enhance-rn.js](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/enhance-rn.js) is loaded  
- Switch to React Native Hermes by following the  React Native documentation and this issue is resolved

**Comment by nthchild1** [comment] 2023-03-02 00:10
We're facing this same issue in my team. Our app is not picking up the entry point for `react-native` even though we're using Hermes. If we manually set `"main": "lib/index.js"` to `"main": "./enhance-rn.js"` it pickups the changes and applies the patches, but it does not automatically. we also use `react-native-web`

**Comment by nadetastic** [comment] 2023-07-11 14:40
Hi @therealtgd @filipmilo thanks for the additional context, I'll go ahead an re-open this issue for further investigation on it. Are you able to provide a sample repo of you app to aide in troubleshooting?

**Comment by therealtgd** [comment] 2023-07-12 07:58
> Hi @therealtgd @filipmilo thanks for the additional context, I'll go ahead an re-open this issue for further investigation on it. Are you able to provide a sample repo of you app to aide in troubleshooting?

I've tried recreating the issue in a fresh app but I failed. I am currently investigating what is causing the issue and I'll keep you posted if I find something out.

**Comment by nadetastic** [comment] 2023-07-13 22:11
@therealtgd thanks for that. Could you also share the `package.json` of the affected app? I'm looking to see the versions of packages - namely `aws-amplify` and `amazon-cognito-identity-js` you are using, to try and reproduce this.

**Comment by eric-nclusion** [comment] 2023-08-15 01:01
This problem recently started occurring for me, as well.  I began backing out changes that I had added to see if anything made a difference.  I had added the following line to my resolver in the `metro.config.js` file:

```
 resolverMainFields: ['react-native', 'module', 'browser', 'main'],
```

By removing this line, everything started working again.  It seems the offending bit is adding `module` as the other three are defaults for React Native.  I have no idea why this fixed the problem for me, but maybe it is helpful for someone else.

**Comment by janet-rivas** [comment] 2023-08-22 13:38
I found that I was running in debug mode and when I switch to prod and bundle in Android the Auth works fine, 

My system info, I hope this helps.

```
System:
    OS: macOS 13.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.14 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2023.05.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/.rvm/rubies/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 21, 23, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-28 | Google X86_ARM Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-33-ext4 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Amazon AWS amplify React Native
    "amazon-cognito-identity-js": "^6.2.0",
    "aws-amplify": "^5.0.25",
    "aws-amplify-react-native": "^7.0.2",
```

**Comment by rahilrvahora** [comment] 2023-08-25 14:39
Facing the same issue but with sendCustomChallengeAnswer, the button freezes and does not show the loading indicator until after 5 to 10 seconds (on iPhone 8), even worse on a lower level android phone.

**Comment by JacobDel** [comment] 2023-08-28 23:28
same issue after updating from 4.3.15 to 5.3.9

**Comment by JacobDel** [comment] 2023-08-29 08:36
package.json
```
{
  "name": "appname",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator 'iPhone X' ",
    "start": "react-native start",
    "web": "sh scripts/load_env.sh && cross-env react-app-rewired start",
    "build": "sh scripts/load_env.sh && cross-env GENERATE_SOURCEMAP='false' DISABLE_ESLINT_PLUGIN='true'  react-app-rewired build",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "clear-cache": "yarn start --reset-cache",
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@material-ui/core": "^4.12.4",
    "@material-ui/icons": "^4.11.3",
    "@mdi/js": "^7.2.96",
    "@notifee/react-native": "^7.8.0",
    "@react-native-async-storage/async-storage": "^1.19.2",
    "@react-native-clipboard/clipboard": "^1.11.2",
    "@react-native-community/cli": "^11.3.7",
    "@react-native-community/netinfo": "^9.4.1",
    "@react-native-community/slider": "^4.4.3",
    "@react-native-picker/picker": "^2.5.0",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "@wcj/generate-password": "^1.0.3",
    "amazon-cognito-identity-js": "^6.3.4",
    "aws-amplify": "^5.3.9",
    "color": "^4.2.3",
    "core-js": "^3.32.1",
    "eject": "^0.0.4",
    "expo": "^49.0.8",
    "expo-file-system": "~15.4.3",
    "graphql-react": "^20.0.0",
    "i18next": "^23.4.5",
    "iconsax-react-native": "^0.0.8",
    "moment": "^2.29.4",
    "obfuscator-io-metro-plugin": "^2.1.3",
    "react": "18.2.0",
    "react-art": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^13.2.0",
    "react-native": "0.72.4",
    "react-native-asset": "^2.1.1",
    "react-native-htmlview": "^0.16.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.2",
    "react-native-localize": "^3.0.2",
    "react-native-rsa": "^0.0.3",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.24.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.13.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "https://github.com/JacobDel/react-native-vector-icons#head=latest_release",
    "react-native-web": "^0.19.7",
  },
  "devDependencies": {
    "@babel/core": "^7.22.10",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-object-rest-spread": "^7.20.7",
    "@babel/preset-env": "^7.22.10",
    "@babel/preset-flow": "^7.22.5",
    "@babel/preset-react": "^7.22.5",
    "@babel/preset-typescript": "^7.22.5",
    "@babel/runtime": "^7.22.10",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/d3": "^7.4.0",
    "@types/jest": "^29.5.4",
    "@types/react": "^18.0.24",
    "@types/react-native": "^0.72.2",
    "@types/react-native-vector-icons": "^6.4.14",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-loader": "^9.1.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.47.0",
    "graphql": "^16.8.0",
    "gts": "^5.0.1",
    "javascript-obfuscator": "^4.0.2",
    "jest": "^29.6.3",
    "metro-react-native-babel-preset": "^0.77.0",
    "prettier": "^2.4.1",
    "react-app-rewired": "^2.2.1",
    "react-native-pager-view": "^6.2.0",
    "react-scripts": "^5.0.1",
    "react-test-renderer": "18.2.0",
    "serve": "^14.2.1",
    "ts-loader": "^9.4.4",
    "typescript": "^5.1.6",
    "webpack-obfuscator": "^3.5.1"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
  }
}

```
metro.config.js
```
const {getDefaultConfig} = require('expo/metro-config');
const {mergeConfig} = require('@react-native/metro-config');

const jsoMetroPlugin = require('obfuscator-io-metro-plugin')(
  {
    compact: false,
    sourceMap: false,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    numbersToExpressions: true,
    simplify: true,
    stringArrayShuffle: true,
    splitStrings: true,
    stringArrayThreshold: 1,
  },
  {
    runInDev: false /* optional */,
    logObfuscatedFiles: true /* optional generated files will be located at ./.jso */,
    // source Map generated after obfuscation is not useful right now
    sourceMapLocation:
      './index.android.bundle.map' /* optional  only works if sourceMap: true in obfuscation option */,
  },
);

const config = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true, // option that can help accelerate an app's startup time by delaying the execution of JavaScript modules until they are used
      },
    }),
  },
  ...jsoMetroPlugin,
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);

```

**Comment by JacobDel** [comment] 2023-08-29 09:07
I updated to 5.3.10 and my issue is resolved..

**Comment by rahilrvahora** [comment] 2023-08-29 13:54
> Facing the same issue but with sendCustomChallengeAnswer, the button freezes and does not show the loading indicator until after 5 to 10 seconds (on iPhone 8), even worse on a lower level android phone.

Updating to 5.3.10 fixes this issue, thanks @JacobDel!

**Comment by cwomack** [comment] 2023-08-29 17:23
@rahilrvahora and @JacobDel, thank you for the confirmations! 

We'll close this issue then for now, but if anyone else experiences further problems with Auth.signIn() **after** upgrading to v5.3.10 of Amplify... please comment and we can reopen the issue.

**Closed by cwomack** 2023-08-29 17:23 UTC
Labels: investigating, Auth, React Native, amazon-cognito-identity-js, pending-response

**Comment by langerkirill** [comment] 2024-03-14 23:38
I am seeing long login times still with 5.3.10

 LOG  time 1 1710459399425
 (trigger Auth.signIn)
 LOG  time 2 1710459425359
 LOG  total time -25934

I attempted to upgrade to aws-amplify 6+ but ran into [issues there](https://github.com/aws-amplify/amplify-js/issues/13122) as well.

**Comment by wm-gabriellopez** [comment] 2024-06-24 19:30
I am using expo with  "aws-amplify": "5.3.18". My sign ins are taking a pretty consistent 12 seconds 

```
Execution time to sign in: 12627 ms
```
