### ISSUE TITLE
Appsync graphQL connection closed error

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7070] opened 2020-10-27 22:35 UTC
Hi I am using subscription via graphQL and getting frequent connection closed error from Appsync, for no apparent reason. It seems to happen at random times. Don't know how to reproduce it. 

<img width="985" alt="Screen Shot 2020-10-27 at 6 23 09 PM" src="https://user-images.githubusercontent.com/48572310/97369050-83bdc800-1882-11eb-82b1-88073356d7a2.png">

My .js code:

 subscribeExhibitorNotifications = async() => {
    try  {
      this.exhitorStatusSubscription = await API.graphql(graphqlOperation(onCreateOveceventsExhibitorStatus));
      if (this.exhitorStatusSubscription) {
       this.exhitorStatusSubscription.subscribe({
          next: (event) => { ...
            }
            else {
              ....
            }
          },
          error: error => {
            console.log("error in graphQL onCreateOveceventsExhibitorStatus: ", error);
          }
        });
      }
    }
    catch (e) {
      console.log("error in graphQL onCreateOveceventsExhibitorStatus: ", e) 
    }
  }

Schema:

export const onCreateOveceventsExhibitorStatus = /* GraphQL */ `
  subscription OnCreateOveceventsExhibitorStatus {
    onCreateOveceventsExhibitorStatus {
      id
      datetime
      status
    }
  }
`;

export const createOveceventsExhibitorStatus = /* GraphQL */ `
  mutation CreateOveceventsExhibitorStatus($id: String!, $status: String!) {
    createOveceventsExhibitorStatus(id: $id, status: $status) {
      id
      datetime
      status
    }
  }
`;

**Comment by mchitson** [comment] 2020-10-28 13:47
for more info, i also see a comment from webpack after the appsync error: 

![image](https://user-images.githubusercontent.com/48572310/97444327-69c3ca00-1902-11eb-8034-eb8e0c18ee5c.png)

Not sure if it's react closing the connection or appsync causing react to print out that command.

that's my version of react:

  "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.3"

**Comment by SalvoCozzubo** [comment] 2020-10-28 19:06
Same here. I have a react app with three subscriptions and all subscriptions received a "Connection Closed" in a complete random way.

Sometimes the connections are stable and sometimes they are closed after a couple minutes.
I will continue to investigate.

**Comment by mchitson** [comment] 2020-10-29 01:19
Hello amplify guys, any luck?

**Comment by chunyanj** [comment] 2020-10-29 21:27
Hi, I’m from the AppSync team. I’m happy to look into the issue you’ve been seeing, would anyone impacted be able to share a rough timestamp (open time and drop time), api id, and region for a connection that dropped? Sorry for the issues!

**Comment by mchitson** [comment] 2020-10-30 01:43
Hi Chunyanj is it possible to send you a private message regards to API id?
In the meanwhile the other info:

region is us-east-1
open time probably around 10am EST (not quite sure if i am remembering the open time accurately), drop time around 1:35pm EST, all 29th oct 2020.

**Comment by chunyanj** [comment] 2020-10-30 19:27
Thank you for the response! We have started to investigate. The API id has been recorded and you could delete the comment if you want. We will get back to you when we have update.

**Comment by mchitson** [comment] 2020-10-30 19:41
great - thank you.

**Comment by mchitson** [comment] 2020-10-31 10:37
hi Chunyan

 I have another question and i have been seeing those questions over the web but no response - if a device is online and currently get subscriptions, then goes offline and then online again, will the subscription still work and then get the latest mutation that was missed?

**Comment by mchitson** [comment] 2020-11-03 17:37
hi there -> any upates? thanks!

**Comment by chunyanj** [comment] 2020-11-03 17:41
Hey mchitson, we are actively investigating the ticket. Sorry for any inconvenience. Please expect an update today.

**Comment by chunyanj** [comment] 2020-11-03 18:05
As for the question above, unfortunately the answer is no. Typically, people could achieve this using delta sync. The doc for delta sync is here: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-delta-sync.html

**Comment by mchitson** [comment] 2020-11-03 18:07
thanks but the document is not very detailed. it's unclear to me whether i need to use datastore with it or what datasync client to use. datastore also does not seem to recover subscriptions - at least not the way i see it documented.

**Comment by chunyanj** [comment] 2020-11-04 01:24
Hey mchitson, we have root caused it.

Sorry for the issue. We dove deep to confirm, and this is an issue we’ve seen reported a few times where code deployments on our end can result in connections temporarily being broken up. We’re investigating a few avenues to alleviate some of these headaches, both on the client end and on our end. Thanks!

**Comment by chunyanj** [comment] 2020-11-04 01:25
Thanks for you feedback of the doc, we'll put this in our backlog and discuss improving it!

**Comment by mchitson** [comment] 2020-11-04 01:36
Thank you Chunyan

So going forward there shouldn’t be a connection closed issue?

**Comment by mchitson** [comment] 2020-11-04 01:43
Also I am trying Datastore as I would like my subscriptions to be up to date when a device is temporarily disconnected and reconnected. I am however getting those errors:
DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined:

My package.json:

 "dependencies": {
        "@aws-amplify/cli": "^4.32.0",
        "@aws-amplify/datastore": "^2.7.2",
        "@testing-library/jest-dom": "^5.11.4",
        "@testing-library/react": "^11.1.0",
        "@testing-library/user-event": "^12.1.10",
        "aws-amplify": "^3.3.7",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "react-scripts": "4.0.0",
        "web-vitals": "^0.2.4"
    },

Secondly, am also seeing a timeout disconnect on appSync at less than 5mins. Is there a way to re-subscribe with appsync after this?

**Comment by mchitson** [comment] 2020-11-04 11:09
Hello Chunyan

The connection closed yet again last night around: 10:41 pm EST. I couldn't quite figure out from your response whether that problem has been solved or is still being solved after the root cause was identified. Thanks!

**Comment by mchitson** [comment] 2020-11-05 00:54
Hello

I have yet another connection close at 5:15Pm 11/4/2020, i am going live soon and this can not happen so frequently, is this being fixed now that you have identified the root cause?

**Comment by chunyanj** [comment] 2020-11-05 01:05
Hey mchitson,

Sorry for the ambiguity we made! The issue hasn't been solved 100% but we have taken actions to reduce the possibility of happening. We believe we can keep the frequency of happening in a very low rate. 

As for the re-subscribe question, we'll provide an update later.

Thanks for the feedbacks!

**Comment by mchitson** [comment] 2020-11-05 01:33
Hey Chunyan

Am not sure if it’s as a result of what you guys have done to improve things, but I am getting disconnected even more often now! Like literally 20 mins ago!

**Comment by mchitson** [comment] 2020-11-10 11:42
i am still getting that connection closed issue happened yesterday again, barely couple of hours after my app started. 

11/9/2020 10:19:12 PM Objecterror: errors: Array(1)0: {message: "Connection closed"}length: 1__proto__: Array(0)__proto__: Objectprovider: AWSAppSyncRealTimeProvider {_config: {…}, socketStatus: 0, keepAliveTimeout: 300000, subscriptionObserverMap: Map(0), promiseArray: Array(0), …}__proto__: Object
GraphQLServices.js:79

**Comment by chunyanj** [comment] 2020-11-11 22:03
Hey mchitson,

Thanks for the feedback! We'll investigate it again to see if it is the same root cause.

**Comment by abdulqudoos** [comment] 2020-11-17 08:08
I also faced connection closed issue today.

**Comment by abdulqudoos** [comment] 2020-11-17 10:37
{
  "provider": {
   
    "socketStatus": 0,
    "keepAliveTimeout": 300000,
    "subscriptionObserverMap": {},
    "promiseArray": [],
    "awsRealTimeSocket": null,
    "keepAliveTimeoutId": 202
  },
  "error": {
    "errors": [
      {
        "message": "Connection closed"
      }
    ]
  }
}

**Comment by EliasCoelho** [comment] 2020-11-27 21:15
Good afternoon, this uncaugth exception was raised in console for my web apps. 
This exception can reflect an security breach for all api environment that it working with graphql... 

Steps: 
1. activate airplane mode
2. desactivate airplane mode
3. move to other tabs in browser
4. go the tabs with the web app and this error show for me in the console

![image](https://user-images.githubusercontent.com/9299757/100484729-f44f4300-30d3-11eb-86d3-5920b0b3756d.png)

**Comment by Mootook** [comment] 2021-05-06 17:22
This is happening in my team's application, as well.

We use appsync graphql and vue apollo composable, and I see this error quite a bit.
From a bit of trial/error, the issue seems to arise from subscribing/unsubscribing in quick succession.

Vue apollo composable handles subscriptions internally in accordance with component lifecycles (from my understanding), so in this case, mounting and unmounting a component that subscribes/unsubscribe quickly will produce this error.
If I wait some time in between mounting/unmounting, the error is less common.
Not sure if that's actually the root cause or a way to get consistent behavior, just wanted to share in case it could help.

**Comment by GiridharCR** [comment] 2021-05-26 16:42
@Mootook i doubt `subscribing/unsubscribing in quick succession` is the cause as i see this issue where i do not even unsubscribe the listeners. If i leave the tab open for some time i see the connection closed error after approximately(not sure) 15 min .

**Comment by mikhail-shekhtman** [comment] 2021-05-31 15:59
hey @mchitson, @chunyanj was the issue eventually resolved? Were you using MQTT as transport or WebSocket? 

Can we experience the same as what was fixed at MQTT year ago and now connection is closing on WebSocket transport?

**Comment by michaeljajou** [comment] 2021-07-01 03:11
Any updates to this issue?

**Comment by IgorDePaula** [comment] 2021-07-30 16:14
I want put a digital store using amplify, now I think that is not secure with all this problems and almost 700 issues.

**Comment by david-mcafee** [comment] 2021-08-24 18:31
[This issue](https://github.com/aws-amplify/amplify-js/issues/7019) is identical, but not yet sure if the root cause is the same. Potentially related to using a VPN.

**Comment by david-mcafee** [comment] 2021-08-24 18:42
> for more info, i also see a comment from webpack after the appsync error:
> 
> ![image](https://user-images.githubusercontent.com/48572310/97444327-69c3ca00-1902-11eb-8034-eb8e0c18ee5c.png)
> 
> Not sure if it's react closing the connection or appsync causing react to print out that command.
> 
> that's my version of react:
> 
> "react": "^16.13.1",
> "react-dom": "^16.13.1",
> "react-scripts": "3.4.3"

**Comment by david-mcafee** [comment] 2021-08-30 17:38
Closing this issue. Remediation steps are listed in my previous comment. Please reach out if there are further issues!

**Closed by david-mcafee** 2021-08-30 17:38 UTC
Labels: API

**Comment by efimk-lu** [comment] 2022-03-03 07:52
Hey @david-mcafee , regarding your comment
```
2. Connection issues breaking the subscription:
For users that are using the GraphQL API without DataStore, a disruption in the network connection will close the subscription. There are several discussions on Discord on this. One user [posted a solution that could work to re-establish the subscription](https://discord.com/channels/705853757799399426/717109993416949811/827076511928549437)
```

I'm unable to connect to the discord channel, can you share the answer here?

**Comment by david-mcafee** [comment] 2022-03-03 07:58
> Hey @david-mcafee , regarding your comment
> 
> ```
> 
> 2. Connection issues breaking the subscription:
> 
> For users that are using the GraphQL API without DataStore, a disruption in the network connection will close the subscription. There are several discussions on Discord on this. One user [posted a solution that could work to re-establish the subscription](https://discord.com/channels/705853757799399426/717109993416949811/827076511928549437)
> 
> ```
> 
> 
> 
> I'm unable to connect to the discord channel, can you share the answer here?

@efimk-lu - it looks like the related Discord chat is no longer available, but the GH issue I linked to also details the same issue. Are you using a VPN?

**Comment by efimk-lu** [comment] 2022-03-03 08:07
No VPN, just regular internet connection. The computer sometimes goes into sleep mode, the network gets disconnected and we are unable to subscribe again

**Comment by CSHaze** [comment] 2022-03-29 22:12
I am running into this problem as well. It happens on web (computer goes to sleep, network change, etc) and iOS and android (app goes into background). 

The only solution seems to be refreshing the page or closing and reopening the app. Neither of these solutions are practical, is there another way to refresh the connection?

**Comment by majirosstefan** [comment] 2022-04-07 00:20
I think this should not be closed, it should not forward users to sites outside of Github / and all code samples / workarounds should be posted HERE.

**Comment by lehoai** [comment] 2022-05-26 10:07
Got same issue!

**Comment by lehoai** [comment] 2022-05-26 11:16
![image](https://user-images.githubusercontent.com/3907614/170477295-4417de5c-e4bd-477e-99d8-fadc09248c38.png)

 If I leave the tab open for ~20mins, (the internet is still connected)  then the subscription is closed.

**Comment by AlphaJuliettOmega** [comment] 2022-12-06 13:03
Same issue, no VPN.

Issue should not be closed as there was no mitigation.

The error should also be caught or documentation should be clear that the error will be thrown _at unspecified moments in runtime_.

**Comment by ihtisham-sohail** [comment] 2022-12-20 07:42
Our application is also facing this issue , for us it's mostly triggered when too many subscription requests are coming ( We have a bulk creation feature - upto 1000 DB entries are created and it listens on their creation ). 
Not sure if graphQL has a limit on how many concurrent requests it listens

**Comment by dannyhw** [comment] 2023-05-24 17:43
We have this issue, no VPN or anything like that. The listed "fixes" are not useful, seems pretty clear that this issue should be re-opened (in my opinion).

This happens intermittently for our subscriptions and the connection is always closed by app-sync for seemingly no reason.

**Comment by 999roberto999** [comment] 2023-06-22 14:09
I just had this happen while doing some stress testing on our app, so sending a lot of updates.  Basically we had 2 out of 6 devices get this error at the exact same moment.  Please reopen this issue, it doesn't appear to be related to any of the issues that were outlined above.  Not using VPN, Network connection is stable, and the Dev server did not go down.  Also I noticed the link to a discord solution for re-subscribing, simply open discord so that doesn't really help at all. 

It is alarming to me that this issue is closed when the issue is obviously still happening to a lot of people.  I am going to attempt to setup my own system to resubscribe but, any additional guidance would be appreciated as this issue is a pretty big deal for our app and could force us to change cloud services/tools if we don't have any good solutions.

**Comment by JandenMa** [comment] 2023-09-27 10:35
> This is happening in my team's application, as well.
> 
> We use appsync graphql and vue apollo composable, and I see this error quite a bit. From a bit of trial/error, the issue seems to arise from subscribing/unsubscribing in quick succession.
> 
> Vue apollo composable handles subscriptions internally in accordance with component lifecycles (from my understanding), so in this case, mounting and unmounting a component that subscribes/unsubscribe quickly will produce this error. If I wait some time in between mounting/unmounting, the error is less common. Not sure if that's actually the root cause or a way to get consistent behavior, just wanted to share in case it could help.

I agree with @Mootook, in my case, mounting and unmounting a component that subscribes/unsubscribes quickly will produce this error.
