### ISSUE TITLE
More efficient way to get file's metadata for list of files than Storage.list() -> Storage.get({download:true})?

### ISSUE THREAD

**Issue by sandeshakya** [aws-amplify/amplify-js#3236] opened 2019-05-07 17:22 UTC
I have an application that lists the files uploaded by a user. I'm using `Storage.list()` for this. I would like to use each file's metadata (`x-amz-meta-owner`) to enable/disable a button. For now, I'm using `Storage.get()` with `download:true` to get the metadata, (I've added x-amz-meta-owner in the CORS configuration). I've found this to be slow and expensive, as it has to download each file as a UIntArray. Is there a more efficient way to get the metadata for each file than this?

Thank you.

**Comment by undefobj** [comment] 2019-05-07 19:15
@sandeshakya interesting request. Can you go deeper into your use case and what you're trying to build so that we can look at this further from a feature perspective?

**Comment by sandeshakya** [comment] 2019-05-07 20:37
@undefobj for my use case, I want to set the `disabled` attribute based on a metadata attribute for a file. But for a more general case, an option to return the objects' metadata might also help in filtering, using metadata to conditionally render certain objects, without having to download every object in a folder.

**Comment by powerful23** [comment] 2019-05-07 21:18
Corresponding method in aws-sdk-js: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property

**Comment by undefobj** [comment] 2019-05-07 21:27
So this is specifically for LIST operations?

**Comment by sandeshakya** [comment] 2019-05-09 17:00
@powerful23 , that's the kind of functionality I was hoping could be added to Amplify. Good find. Thank you.

**Comment by sandeshakya** [comment] 2019-05-09 17:02
@undefobj , might make more sense to have it in the Get operation, similar to @powerful23's post.

**Comment by mrichman** [comment] 2020-05-27 11:00
I'm trying to do this as well.

**Comment by nicholasrobertson** [comment] 2022-03-28 02:23
2022 and would like to do this also

**Comment by abdallahshaban557** [comment] 2022-08-10 02:00
Closing this issue as a duplicate of #1550

**Closed by abdallahshaban557** 2022-08-10 02:00 UTC
Labels: feature-request, Storage
