### ISSUE TITLE
wrong parsing of `email_verified` field in auth ~ 3.4.24

### ISSUE THREAD

**Issue by jhonny-e-SB** [aws-amplify/amplify-js#7917] opened 2021-03-10 11:53 UTC
**Describe the bug**
On newer versions of the auth package, the response for the `currentAuthenticatedUser` method is parsed wrongly

**To Reproduce**
1. update `"@aws-amplify/auth"` to latest(ish) version, 3.4.24 and above
2. verify your email address with cognito
2. log in using `Auth.signIn(email, password)`
2. call `currentUserInfo = Auth.currentAuthenticatedUser({ bypassCache: true })` 

**Result:** 
`currentUserInfo.attributes.email_verified` is `false`
**Expected behavior**
`currentUserInfo.attributes.email_verified` is `"True"`

**Code Snippet**
```
await Auth.signIn(email, password);
const currentUserInfo = await Auth.currentAuthenticatedUser({ bypassCache: true });
const emailVerified = currentUserInfo.attributes.email_verified; # should be "True"
```
**Screenshots**
N/A

**What is Configured?**
N/A
<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 93.30 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Firefox Developer Edition: 87.0
    Safari: 14.0.3
  npmPackages:
    @aws-amplify/auth: ^3.4.24 => 3.4.24 
    @babel/core: ^7.9.6 => 7.13.1 
    @babel/plugin-proposal-class-properties: ^7.13.0 => 7.13.0 
    @babel/plugin-proposal-object-rest-spread: ^7.13.0 => 7.13.0 
    @babel/plugin-proposal-throw-expressions: ^7.12.13 => 7.12.13 
    @babel/plugin-transform-arrow-functions: ^7.13.0 => 7.13.0 
    @babel/plugin-transform-async-to-generator: ^7.13.0 => 7.13.0 
    @babel/polyfill: ^7.12.1 => 7.12.1 
    @babel/preset-env: ^7.13.5 => 7.13.5 
    @babel/preset-react: ^7.12.13 => 7.12.13 
    @babel/preset-typescript: ^7.13.0 => 7.13.0 
    @emotion/core: ^10.1.1 => 10.1.1 
    @emotion/is-prop-valid: ^0.8.8 => 0.8.8 
    @emotion/styled: ^10.0.27 => 10.0.27 
    @onefifteen-z/react-input-otp: ^1.0.5 => 1.0.5 
    @simplybusiness/mobius: 0.1.0-rc.5.5-retainerspatchdonotdelete.6 => 0.1.0-rc.5.5-retainerspatchdonotdelete.6 
    @testing-library/jest-dom: ^5.11.9 => 5.11.9 
    @testing-library/react: ^11.2.5 => 11.2.5 
    @testing-library/user-event: ^12.7.3 => 12.7.3 
    @types/jest: ^26.0.20 => 26.0.20 
    @types/react: ^16.14.4 => 16.14.4 
    @types/react-dom: ^16.9.11 => 16.9.11 
    @types/react-redux: ^7.1.16 => 7.1.16 
    @typescript-eslint/eslint-plugin: ^4.15.2 => 4.15.2 
    @typescript-eslint/parser: ^4.15.2 => 4.15.2 
    amazon-cognito-identity-js: ^4.5.12 => 4.5.12 
    babel-jest: ^25.5.1 => 25.5.1 
    babel-loader: ^8.2.2 => 8.2.2 
    babel-plugin-emotion: ^10.2.2 => 10.2.2 
    babel-plugin-module-resolver: ^4.1.0 => 4.1.0 
    clean-webpack-plugin: ^0.1.19 => 0.1.19 
    clsx: ^1.1.1 => 1.1.1 
    copy-webpack-plugin: ^5.1.2 => 5.1.2 
    cross-env: ^7.0.3 => 7.0.3 
    css-loader: ^3.6.0 => 3.6.0 
    date-fns: ^1.30.1 => 1.30.1 
    dotenv: ^8.2.0 => 8.2.0 
    emotion-theming: ^10.0.27 => 10.0.27 
    enzyme: ^3.7.0 => 3.11.0 
    enzyme-adapter-react-16: ^1.15.6 => 1.15.6 
    enzyme-to-json: ^3.6.1 => 3.6.1 
    es-check: 5.2.0 => 5.2.0 
    eslint: ^7.20.0 => 7.20.0 
    eslint-config-airbnb: ^17.1.0 => 17.1.1 
    eslint-import-resolver-babel-module: ^5.2.0 => 5.2.0 
    eslint-plugin-import: ^2.22.1 => 2.22.1 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-react: ^7.22.0 => 7.22.0 
    file-loader: ^6.2.0 => 6.2.0 
    formik: ^1.3.2 => 1.5.8 
    hoist-non-react-statics: ^3.1.0 => 3.3.2 
    html-webpack-plugin: ^4.5.2 => 4.5.2 
    imagemin-webpack-plugin: ^2.4.2 => 2.4.2 
    jest: ^26.6.3 => 26.6.3 
    jest-html-reporter: ^3.3.0 => 3.3.0 
    mockdate: ^2.0.2 => 2.0.5 
    promise.prototype.finally: ^3.1.0 => 3.1.2 
    proxyquire: ^2.1.1 => 2.1.3 
    query-string: 5.1.1 => 5.1.1 
    react: ^16.14.0 => 16.14.0 
    react-dom: ^16.14.0 => 16.14.0 
    react-redux: ^7.2.2 => 7.2.2 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-test-renderer: ^16.14.0 => 16.14.0 
    redux: ^4.0.0 => 4.0.5 
    redux-mock-store: ^1.5.3 => 1.5.4 
    redux-saga: ^1.0.3 => 1.1.3 
    redux-saga-test-plan: ^4.0.1 => 4.0.1 
    reselect: ^4.0.0 => 4.0.0 
    serialize-javascript: >=4.0.0 => 4.0.0 
    typescript: ^3.9.9 => 3.9.9 
    typescript-eslint-parser: ^22.0.0 => 22.0.0 
    unused-webpack-plugin: ^2.4.0 => 2.4.0 
    url-loader: ^4.1.1 => 4.1.1 
    webpack: ^4.46.0 => 4.46.0 
    webpack-bundle-analyzer: ^3.9.0 => 3.9.0 
    webpack-cli: ^3.3.12 => 3.3.12 
    webpack-dev-server: ^3.11.2 => 3.11.2 
    webpack-merge: ^4.1.4 => 4.2.2 
    whatwg-fetch: ^3.6.1 => 3.6.1 
    yup: ^0.26.6 => 0.26.10 
  npmGlobalPackages:
    npm: 6.14.5
```

</details>

**Comment by Jordan-Nelson** [comment] 2021-03-25 16:46
Hi @jhonny-e-SB, thanks for opening the issue. Could you please confirm the following:
- How are you verifying the email address. Are you using `Auth.confirmSignUp()`? For reference, here are the [docs on confirming sign up](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#confirm-sign-up).
- How are you configuring amplify in your project? For reference, here are the [docs on Amplify client side configuration](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js).

**Comment by iartemiev** [comment] 2021-04-12 18:27
@jhonny-e-SB,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:27 UTC
Labels: Auth, pending-close-response-required, to-be-reproduced

**Comment by dwilt** [comment] 2022-02-16 17:52
@iartemiev we are running into this at the moment.. we've seen [similar](https://github.com/aws-amplify/amplify-js/issues/7528) issues and have tried `bypassCache: true` but to no avail.. any ideas?
