### ISSUE TITLE
DataStore.save not sending correct input data to graphQL endpoint

### ISSUE THREAD

**Issue by caridavidson** [aws-amplify/amplify-js#11241] opened 2023-04-13 10:29 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API, DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
    "@aws-amplify/cli": "^11.0.3",
    "@aws-amplify/core": "^5.1.8",
    "@aws-amplify/datastore": "^4.1.7",
    "aws-amplify": "^5.1.1",

```

</details>

### Describe the bug

Note, that I did find [this ticket](https://github.com/aws-amplify/amplify-js/issues/10806)  but it was closed without conclusion.

I'm calling `DataStore.save` on this model:

```javascript
type LevelInfo @model @auth(rules: [
    { allow: groups, groupsField: "tenant", operations: [read, update] },
    { allow: owner }
]) {
  id: ID!
  tenant: String @default(value: "admin")
  name: String!
  order: Int!
  people: [Person] @hasMany
}
```

Generated code as 

```javascript
type LazyLevelInfo = {
  readonly [__modelMeta__]: {
    identifier: ManagedIdentifier<LevelInfo, 'id'>;
    readOnlyFields: 'createdAt' | 'updatedAt';
  };
  readonly id: string;
  readonly tenant?: string | null;
  readonly name: string;
  readonly order: number;
  readonly people: AsyncCollection<Person>;
  readonly createdAt?: string | null;
  readonly updatedAt?: string | null;
}
```

It has this value:

```javascript
{
  _deleted: undefined
  _lastChangedAt: undefined
  _version: undefined
  createdAt: null
  id: '871ba18a-b6bf-42b8-ad20-1627a5bce514'
  name: 'New Level'
  order: 2
  people: ƒ ()
  tenant: 'xxx'
  updatedAt: null
}
```

Log output is below

### Expected behavior

DataStore formats the POST to GraphQL properly and the Item is saved to DynamoDB since it does contain both required fields. 
If there is an error, it throws an error (not as worried about this part since it's a known issue with how DataStore works), (note that in logs it says DataStore - Mutation sent successfully with authMode: AMAZON_COGNITO_USER_POOLS) despite it failing.

### Reproduction steps

1. Detailed instructions above

### Code Snippet

```javascript
// Put your code below this line.
  const lvl = new LevelInfo({
    name: 'New Level',
    order: 1,
  })
  DataStore.save(lvl)
```

### Log output

<details>

```
// Put your logs below this line
[WARN] 59:18.506 DataStore {recoverySuggestion: 'Ensure app code is up to date, auth dir…thub.com/aws-amplify/amplify-js/issues', localModel: {…}, message: 'Variable 'input' has coerced Null value for NonNull type 'String!'', operation: 'Create', errorType: 'BadRecord', …}

// Network Payload is incorrectly created (missing name and order)
query: "mutation operation($input: CreateLevelInfoInput!) {\n  createLevelInfo(input: $input) {\n    id\n    tenant\n    name\n    order\n    createdAt\n    updatedAt\n    owner\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n"
variables: {input: {id: "3cdbe3e5-c8fe-4fa0-a6e6-ad688ec0711d", tenant: "tekkr.io"}}
input:{id: "3cdbe3e5-c8fe-4fa0-a6e6-ad688ec0711d", tenant: "tekkr.io"}

// Complete amplify logs
[DEBUG] 38:39.424 DataStore - Attempting mutation with authMode: AMAZON_COGNITO_USER_POOLS
ConsoleLogger.js:87 [DEBUG] 38:39.424 Util -  attempt #1 with this vars: ["LevelInfo","Create","{\"tenant\":\"tekkr.io\",\"id\":\"71cc288b-6a49-420d-9291-6d1a661d7d0f\"}","{}",null,null,{"data":"{\"tenant\":\"tekkr.io\",\"id\":\"71cc288b-6a49-420d-9291-6d1a661d7d0f\"}","modelId":"71cc288b-6a49-420d-9291-6d1a661d7d0f","model":"LevelInfo","operation":"Create","condition":"{}","id":"01GXX6HKZEA9ZFCVSG4MGN23X1"}]
ConsoleLogger.js:87 [DEBUG] 38:39.424 AuthClass - Getting current session
ConsoleLogger.js:99 [DEBUG] 38:39.425 AuthClass - Succeed to get the user session CognitoUserSession {idToken: CognitoIdToken, refreshToken: CognitoRefreshToken, accessToken: CognitoAccessToken, clockDrift: -1}
ConsoleLogger.js:99 [DEBUG] 38:39.425 AuthClass - Succeed to get the user session CognitoUserSession {idToken: CognitoIdToken, refreshToken: CognitoRefreshToken, accessToken: CognitoAccessToken, clockDrift: -1}
ConsoleLogger.js:99 [DEBUG] 38:39.425 RestClient - POST https://eunhffv72raqlgolbhj2axas54.appsync-api.eu-central-1.amazonaws.com/graphql
ConsoleLogger.js:87 [DEBUG] 38:39.622 DataStore - Mutation sent successfully with authMode: AMAZON_COGNITO_USER_POOLS
ConsoleLogger.js:87 [DEBUG] 38:39.622 DataStore - done retrying
```

</details>

### aws-exports.js

```javascript

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://eunhffv72raqlgolbhj2axas54.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-central-1:10815ea4-dd8c-4f62-8d6a-0a1e7315d3d1",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_jYr6oXxWw",
    "aws_user_pools_web_client_id": "7kv2rsa14um3g3l2jlqr10ajuo",
    "oauth": {
...
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "**",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};
```

**Comment by dpilch** [comment] 2023-04-13 21:40
Hi @caridavidson, I wasn't able to reproduce this behavior. Could you share a code snippet of the `DataStore.save` call that is causing the issue.

**Comment by caridavidson** [comment] 2023-04-14 03:25
It's already in there

**Comment by caridavidson** [comment] 2023-04-14 12:08
Adding to this...

Since the models do exist locally, I'm able to assign them to models.  (for example, `Person` has a `LevelInfo` relation of @belongsTo).  The id is set, but since the model doesn't exist on the server-side, corruption occurs and sync gets out of whack.

**Comment by dpilch** [comment] 2023-04-14 14:14
Sorry, my mistake. I'm not sure how I missed that!

**Comment by caridavidson** [comment] 2023-04-14 15:44
I'm able to work around this by not using DataStore and calling graphQL  thus:
... it is not ideal though. 
note also that other models are working, so I'm not sure what's happening. 

```javascript
const createLevelInfo = async () => {
  const result = await API.graphql<GraphQLQuery<any>>(
    graphqlOperation(mutations.createLevelInfo, { input: {
      title: 'New Level',
      order: 1,
      tenant: auth.tenant
    }})
  );
  items.value.push(LevelInfo.fromJSON(result.data.createLevelInfo))
}
```

**Comment by caridavidson** [comment] 2023-04-14 15:55
> Do you have both aws-amplify and @aws-amplify/datastorepackages listed in your dependencies? Sometimes including both packages can lead to unexpected behavior. If this is the case only includeaws-amplify`.

I do.  I thought the same thing.   I made an effor to switch to @aws-amplify/* but there were some incompatibilities so I stashed it.

**Comment by dpilch** [comment] 2023-04-14 15:59
My best guess is that multiple DataStore singletons are being included. It is probably related to this change https://github.com/aws-amplify/amplify-js/pull/11171. My theory is that DataStore is erasing the fields that have been set because the information is not shared between the two instances of DataStore.

My recommendation would be to install and import only from `aws-amplify`. Tree shaking should automatically remove any unused categories from the production bundle.

**Comment by caridavidson** [comment] 2023-04-14 16:04
OK. already started working on it.  btw.   What's the 'aws-amplify' equivalent of `isPredicateObj` and `isPredicatesAll` ? It's one of the things getting in my way.

**Comment by dpilch** [comment] 2023-04-14 16:08
You will actually need to import that from `@aws-amplify/datastore`. So not everything from `aws-amplify` 😄.

I think this should be fine though. I've never had issue importing these types of exports.

**Comment by caridavidson** [comment] 2023-04-14 16:33
Nope... same thing. essage: "Variable 'input' has coerced Null value for NonNull type 'String!'", operation: 'Create', errorType: 'BadRecord', …}

**Comment by dpilch** [comment] 2023-04-14 16:40
Hmm, could you try pinning to `aws-amplify@5.0.24` to see if https://github.com/aws-amplify/amplify-js/pull/11171 is indeed the source of the issue? Maybe there is some edge case that is not accounted for.

**Comment by caridavidson** [comment] 2023-04-14 16:50
ok, so that didn't work, I hadn't deleted the lockfile.  that made a difference. 😅  I should have tried that much, much sooner.   looks good now.  
Thank you SOOO much for your help!

**Comment by dpilch** [comment] 2023-04-14 16:53
🎉 Happy to help!

So there must be some issue with https://github.com/aws-amplify/amplify-js/pull/11171. We'll try to find the fix.

**Comment by chrisbonifacio** [comment] 2023-04-14 19:32
Hey @caridavidson 👋 would you be interested in joining us on a call to troubleshoot the bug you are currently experiencing on v5.1.1?

If so, please schedule a meeting [here](https://prelude.amazon.com/s/fmLGKDysf/dyGzV/-/convos-with-dxe-team) and I will coordinate with engineering.

In the meantime, please also run the following command:

`amplify diagnose --send-report`

And share the project identifier that is output

This will give us some insight into your backend config and recreate the backend env to attempt to reproduce the issue on our end

**Comment by caridavidson** [comment] 2023-04-14 20:48
Sure. Happy to help.  I'll schedule something next week.

**Comment by adamk-au** [comment] 2023-04-15 01:50
I also found running `.copyOf()` multiple times and then calling `.save()` is now missing data. Seems to work ok if `.copyOf()` is only called once, then `.save()` is called.

```typescript
const existingOrder = await DataStore.query(Order, order.id);
orderChangeA = Order.copyOf(existingOrder, (draft) => {
  draft.name = "Bob"
});
orderChangeB = Order.copyOf(orderChangeA, (draft) => {
  draft.address = "Smith street"
});
await DataStore.save(orderChangeB); 
```

**Comment by chrisbonifacio** [comment] 2023-04-15 05:07
Thank you @caridavidson, looking forward to meeting with you!

@adamk-au thank you for reporting this. Do you mind sharing what the mutation input looks like in the outgoing GraphQL request? If you are seeing only the most recent copyOf changes, this bug may be a regression. There's an an older issue that might be related:

https://github.com/aws-amplify/amplify-js/issues/9891

**Comment by kklobe** [comment] 2023-04-18 18:25
I am also seeing this same behavior with one of my models after upgrading to v5.1.1, and going back to v5.0.24 solved the issue. I can see in the datastore `outboxMutationProcessed` event that a field with a value is stripped out, causing the same error (Variable 'input' has coerced Null value for NonNull type).

**Comment by finvillaco** [comment] 2023-04-20 09:44
I'm facing the same problem and I cannot use v.5.0.24 because it causes another problem ([#11187](https://github.com/aws-amplify/amplify-js/pull/11192)). However, #11187 was fixed in v.5.0.25. Thus, I have to wait for new version and hope it will be released soon.

**Comment by finvillaco** [comment] 2023-04-21 06:06
I'm facing the same problem and I cannot use v.5.0.24 because it causes another problem (https://github.com/aws-amplify/amplify-js/pull/11192). However, https://github.com/aws-amplify/amplify-js/issues/11187 was fixed in v.5.0.25. Thus, I have to wait for new version and hope it will be released soon.

**Comment by chrisbonifacio** [comment] 2023-04-24 18:24
Hi @adamk-au , is there a reason why you're not saving the record in between copyOf calls and instead calling it consecutively?

@finvillaco I was not able to reproduce this behavior on the latest version of `aws-amplify` (5.1.3), can you try upgrading and letting me know if the issue persists?

**Comment by kklobe** [comment] 2023-04-24 21:02
@chrisbonifacio I also continue to see this error on 5.1.3. Here is the object I'm saving as returned by `Datastore.save()`:
```json
{
	"owner": "89afb671-407e-47be-9dea-d33d5a830745",
	"startDate": "2023-04-24T20:47:33.610Z",
	"behavior": "NONE_SELECTED",
	"dangerZone": "UNINITIALIZED",
	"durationInSeconds": 5,
	"instances": 3,
	"observedInstances": 0,
	"competingResponseInstances": 0,
	"id": "ae502db0-1fbf-4eed-93a7-3ba79bf522e1",
	"uuid": "29fe0652-2245-4dab-8289-7f25a74a033e",
	"activity": null,
	"deflectedEngaged": null,
	"intensity": null,
	"journal": null,
	"location": null,
	"mood": null
}
```

and here is the Datastore outbox event:
```json
{
	"event": "outboxMutationEnqueued",
	"data": {
		"element": {
			"startDate": "2023-04-24T20:47:33.610Z",
			"durationInSeconds": 5,
			"instances": 3,
			"uuid": "29fe0652-2245-4dab-8289-7f25a74a033e",
			"id": "ae502db0-1fbf-4eed-93a7-3ba79bf522e1"
		}
	}
}
```
causing the error:
```log
"Variable 'input' has coerced Null value for NonNull type 'BehaviorType!'"
```
With 5.0.24, this works just fine. Here's the `Datastore.save()` object:
```json
{
	"id": "90005d46-b01f-47de-9c6e-53398c856c71",
	"owner": "89afb671-407e-47be-9dea-d33d5a830745",
	"uuid": "593bc68b-4bc1-4b6a-b73d-12a43916f1f5",
	"startDate": "2023-04-24T20:55:56.620Z",
	"activity": null,
	"behavior": "NONE_SELECTED",
	"dangerZone": "UNINITIALIZED",
	"deflectedEngaged": null,
	"durationInSeconds": 114.81,
	"instances": 6,
	"observedInstances": 0,
	"competingResponseInstances": 0,
	"intensity": null,
	"journal": null,
	"location": null,
	"mood": null,
	"_version": 1,
	"_lastChangedAt": 1682369790071,
	"_deleted": null
}
```
and the outbox event:
```json
{
	"event": "outboxMutationProcessed",
	"data": {
		"element": {
			"id": "90005d46-b01f-47de-9c6e-53398c856c71",
			"owner": "89afb671-407e-47be-9dea-d33d5a830745",
			"uuid": "593bc68b-4bc1-4b6a-b73d-12a43916f1f5",
			"startDate": "2023-04-24T20:55:56.620Z",
			"activity": null,
			"behavior": "NONE_SELECTED",
			"dangerZone": "UNINITIALIZED",
			"deflectedEngaged": null,
			"durationInSeconds": 114.81,
			"instances": 6,
			"observedInstances": 0,
			"competingResponseInstances": 0,
			"intensity": null,
			"journal": null,
			"location": null,
			"mood": null,
			"_version": 2,
			"_lastChangedAt": 1682369941004,
			"_deleted": null
		}
	}
}
```
The post-5.0.24 versions are completely erasing `owner`, `behavior`, and `dangerZone` after `Datastore.save()`

**Comment by kklobe** [comment] 2023-04-25 15:13
@chrisbonifacio sure, here's the generated `index.d.ts`, let me know if you want a different source:

```typescript
type EagerPullGesture = {
  readonly id: string;
  readonly owner?: string | null;
  readonly persistentBandId: string;
  readonly deleted?: boolean | null;
  readonly gestureNumber: number;
  readonly trained: GestureTrained | keyof typeof GestureTrained;
  readonly behavior: BehaviorType | keyof typeof BehaviorType;
  readonly dangerZone: DangerZone | keyof typeof DangerZone;
  readonly isCompetingResponse?: boolean | null;
  readonly nickName?: string | null;
  readonly metadata?: string | null;
}

type LazyPullGesture = {
  readonly id: string;
  readonly owner?: string | null;
  readonly persistentBandId: string;
  readonly deleted?: boolean | null;
  readonly gestureNumber: number;
  readonly trained: GestureTrained | keyof typeof GestureTrained;
  readonly behavior: BehaviorType | keyof typeof BehaviorType;
  readonly dangerZone: DangerZone | keyof typeof DangerZone;
  readonly isCompetingResponse?: boolean | null;
  readonly nickName?: string | null;
  readonly metadata?: string | null;
}

export enum BehaviorType {
  HAIR_PULLING = "HAIR_PULLING",
  SKIN_PICKING = "SKIN_PICKING",
  NAIL_BITING = "NAIL_BITING",
  THUMB_SUCKING = "THUMB_SUCKING",
  COMPETING_RESPONSE = "COMPETING_RESPONSE",
  NONE_SELECTED = "NONE_SELECTED"
}

export enum DangerZone {
  UNINITIALIZED = "UNINITIALIZED",
  HEAD_HAIR_BACK = "HEAD_HAIR_BACK",
  HEAD_HAIR_TOP = "HEAD_HAIR_TOP",
  HEAD_HAIR_LEFT = "HEAD_HAIR_LEFT",
  HEAD_HAIR_RIGHT = "HEAD_HAIR_RIGHT",
  HEAD_FOREHEAD = "HEAD_FOREHEAD",
  HEAD_EYEBROWS_LEFT = "HEAD_EYEBROWS_LEFT",
  HEAD_EYEBROWS_RIGHT = "HEAD_EYEBROWS_RIGHT",
  HEAD_CHEEK_LEFT = "HEAD_CHEEK_LEFT",
  HEAD_CHEEK_RIGHT = "HEAD_CHEEK_RIGHT",
  HEAD_MOUTH_CHIN = "HEAD_MOUTH_CHIN",
  HEAD_NECK = "HEAD_NECK",
  HEAD_OTHER = "HEAD_OTHER",
  BODY_ARM_LEFT = "BODY_ARM_LEFT",
  BODY_ARM_RIGHT = "BODY_ARM_RIGHT",
  BODY_CHEST = "BODY_CHEST",
  BODY_LEG_LEFT = "BODY_LEG_LEFT",
  BODY_LEG_RIGHT = "BODY_LEG_RIGHT",
  BACK_LEFT = "BACK_LEFT",
  BACK_RIGHT = "BACK_RIGHT",
  BACK_LOWER = "BACK_LOWER",
  BODY_HANDS = "BODY_HANDS",
  BODY_OTHER = "BODY_OTHER",
  COMPETING_RESPONSE = "COMPETING_RESPONSE"
}
```

These are all update saves after a `.copyOf(...)`

This is an inherited project, where could I find the resolution strategy? There is a custom handler:
```typescript
    DataStore.configure({
      errorHandler: error => {
        LOG(`DataStore errorHandler: ${JSON.stringify(error)}`, LogLevel.error)
        Sentry.captureException(JSON.stringify(error))
      },
      conflictHandler: conflict => {
        if (conflict.operation !== 'DELETE') {
          LOG(`DataStore conflictHandler: ${JSON.stringify(conflict)}`, LogLevel.warn)
        }
        return DISCARD
      },
    })
```

**Comment by chrisbonifacio** [comment] 2023-04-26 18:27
@kklobe you can find the resolution strategy in the `amplify/backend/api/<apiName>/cli-inputs.json` file

**Comment by kklobe** [comment] 2023-04-26 18:35
@chrisbonifacio I don't have that file but I do have `transform.conf.json`, looks like auto merge:
```json
{
    "Version": 5,
    "StackMapping": {
        "QuerypullGesturesByOwnerResolver": "PullGesture"
    },
    "ElasticsearchWarning": true,
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        }
    }
}
```
Also just wanted to mention that I have never seen the logging message trigger for the conflict handler.

**Comment by temrb** [comment] 2023-04-29 23:25
I also ran into similar issues with DataStore.save for my schemas-- I think downgrading to v.24 helped resolve this issue for now..

**Comment by svidgen** [comment] 2023-07-03 16:04
@kklobe Thanks for helping us dig on this, and sorry for the delay. I had some hunches based on your input, but was still unfortunately unable to repro. Can you share a few more things with us?

1. The broken model's graphql (with associated enums) from your `schema.graphql` file
2. The `models/schema.js` entries from bullet `1`
3. The `models/index.d.ts` entries if there have been any change from above.
4. Your CLI version?

Also, just to confirm, your broken model doesn't have any *related* models (`@hasMany`, `@belongsTo`, or `@hasOne` fields), does it?

And finally, is there any possibility you've been able to repro this on a fresh app and are able to provide targeted repro steps? Or, has this issue just affected one seemingly random model?

**Comment by kklobe** [comment] 2023-07-03 17:22
@svidgen thanks for the follow-up.

`schema.graphql` model:
```graphql
type HabitEpisode
  @model
  @auth(rules: [{ allow: owner }])
  @key(name: "ByOwner", fields: ["owner"], queryField: "habitEpisodesByOwner") {
  id: ID!
  owner: String
  uuid: String
  startDate: AWSDateTime!
  activity: ActivityType
  behavior: BehaviorType!
  dangerZone: DangerZone!
  deflectedEngaged: EngagedDeflectedType
  durationInSeconds: Float!
  instances: Int
  observedInstances: Int # how many of instances the user was aware of
  # e.g. in beat keen mode, a button push was detected within 5 seconds
  competingResponseInstances: Int #  How many of instances were fist twist events
  # e.g. the user stopped themselves from doing the behavior
  intensity: Int
  journal: String
  location: LocationType
  mood: MoodType
}

enum ActivityType {
  GETTING_READY
  EATING
  EXERCISING
  RELAXING
  SLEEPING
  THINKING
  READING
  STUDYING
  WORKING
  WATCHING_TV
  TALKING
  OTHER
}

enum BehaviorType {
  HAIR_PULLING
  SKIN_PICKING
  NAIL_BITING
  THUMB_SUCKING
  COMPETING_RESPONSE
  NONE_SELECTED
}

enum DangerZone {
  UNINITIALIZED

  # Head options:
  HEAD_HAIR_BACK
  HEAD_HAIR_TOP
  HEAD_HAIR_LEFT
  HEAD_HAIR_RIGHT
  HEAD_FOREHEAD
  HEAD_EYEBROWS_LEFT
  HEAD_EYEBROWS_RIGHT
  HEAD_CHEEK_LEFT
  HEAD_CHEEK_RIGHT
  HEAD_MOUTH_CHIN
  HEAD_NECK
  HEAD_OTHER

  # Body options
  BODY_ARM_LEFT
  BODY_ARM_RIGHT
  BODY_CHEST
  BODY_LEG_LEFT
  BODY_LEG_RIGHT
  BACK_LEFT
  BACK_RIGHT
  BACK_LOWER
  BODY_HANDS
  BODY_OTHER

  # CRT
  COMPETING_RESPONSE
}

enum EngagedDeflectedType {
  ENGAGED_BEHAVIOR
  DEFLECTED_BEHAVIOR
}

enum LocationType {
  BEDROOM
  BATHROOM
  KITCHEN
  LIVING_ROOM
  WORK
  SCHOOL
  VEHICLE
  OUT_AND_ABOUT
  OTHER
}

enum MoodType {
  CALM
  HAPPY
  BORED
  SAD
  TIRED
  ASHAMED
  ANGRY
  FRUSTRATED
  ANXIOUS
}
```

and the `schema.js` entries:

```JSON
        "HabitEpisode": {
            "name": "HabitEpisode",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "owner": {
                    "name": "owner",
                    "isArray": false,
                    "type": "String",
                    "isRequired": false,
                    "attributes": []
                },
                "uuid": {
                    "name": "uuid",
                    "isArray": false,
                    "type": "String",
                    "isRequired": false,
                    "attributes": []
                },
                "startDate": {
                    "name": "startDate",
                    "isArray": false,
                    "type": "AWSDateTime",
                    "isRequired": true,
                    "attributes": []
                },
                "activity": {
                    "name": "activity",
                    "isArray": false,
                    "type": {
                        "enum": "ActivityType"
                    },
                    "isRequired": false,
                    "attributes": []
                },
                "behavior": {
                    "name": "behavior",
                    "isArray": false,
                    "type": {
                        "enum": "BehaviorType"
                    },
                    "isRequired": true,
                    "attributes": []
                },
                "dangerZone": {
                    "name": "dangerZone",
                    "isArray": false,
                    "type": {
                        "enum": "DangerZone"
                    },
                    "isRequired": true,
                    "attributes": []
                },
                "deflectedEngaged": {
                    "name": "deflectedEngaged",
                    "isArray": false,
                    "type": {
                        "enum": "EngagedDeflectedType"
                    },
                    "isRequired": false,
                    "attributes": []
                },
                "durationInSeconds": {
                    "name": "durationInSeconds",
                    "isArray": false,
                    "type": "Float",
                    "isRequired": true,
                    "attributes": []
                },
                "instances": {
                    "name": "instances",
                    "isArray": false,
                    "type": "Int",
                    "isRequired": false,
                    "attributes": []
                },
                "observedInstances": {
                    "name": "observedInstances",
                    "isArray": false,
                    "type": "Int",
                    "isRequired": false,
                    "attributes": []
                },
                "competingResponseInstances": {
                    "name": "competingResponseInstances",
                    "isArray": false,
                    "type": "Int",
                    "isRequired": false,
                    "attributes": []
                },
                "intensity": {
                    "name": "intensity",
                    "isArray": false,
                    "type": "Int",
                    "isRequired": false,
                    "attributes": []
                },
                "journal": {
                    "name": "journal",
                    "isArray": false,
                    "type": "String",
                    "isRequired": false,
                    "attributes": []
                },
                "location": {
                    "name": "location",
                    "isArray": false,
                    "type": {
                        "enum": "LocationType"
                    },
                    "isRequired": false,
                    "attributes": []
                },
                "mood": {
                    "name": "mood",
                    "isArray": false,
                    "type": {
                        "enum": "MoodType"
                    },
                    "isRequired": false,
                    "attributes": []
                }
            },
            "syncable": true,
            "pluralName": "HabitEpisodes",
            "attributes": [
                {
                    "type": "model",
                    "properties": {}
                },
                {
                    "type": "key",
                    "properties": {
                        "name": "ByOwner",
                        "fields": [
                            "owner"
                        ],
                        "queryField": "habitEpisodesByOwner"
                    }
                },
                {
                    "type": "auth",
                    "properties": {
                        "rules": [
                            {
                                "provider": "userPools",
                                "ownerField": "owner",
                                "allow": "owner",
                                "identityClaim": "cognito:username",
                                "operations": [
                                    "create",
                                    "update",
                                    "delete",
                                    "read"
                                ]
                            }
                        ]
                    }
                }
            ]
        },      
        "ActivityType": {
            "name": "ActivityType",
            "values": [
                "GETTING_READY",
                "EATING",
                "EXERCISING",
                "RELAXING",
                "SLEEPING",
                "THINKING",
                "READING",
                "STUDYING",
                "WORKING",
                "WATCHING_TV",
                "TALKING",
                "OTHER"
            ]
        },
        "BehaviorType": {
            "name": "BehaviorType",
            "values": [
                "HAIR_PULLING",
                "SKIN_PICKING",
                "NAIL_BITING",
                "THUMB_SUCKING",
                "COMPETING_RESPONSE",
                "NONE_SELECTED"
            ]
        },
        "DangerZone": {
            "name": "DangerZone",
            "values": [
                "UNINITIALIZED",
                "HEAD_HAIR_BACK",
                "HEAD_HAIR_TOP",
                "HEAD_HAIR_LEFT",
                "HEAD_HAIR_RIGHT",
                "HEAD_FOREHEAD",
                "HEAD_EYEBROWS_LEFT",
                "HEAD_EYEBROWS_RIGHT",
                "HEAD_CHEEK_LEFT",
                "HEAD_CHEEK_RIGHT",
                "HEAD_MOUTH_CHIN",
                "HEAD_NECK",
                "HEAD_OTHER",
                "BODY_ARM_LEFT",
                "BODY_ARM_RIGHT",
                "BODY_CHEST",
                "BODY_LEG_LEFT",
                "BODY_LEG_RIGHT",
                "BACK_LEFT",
                "BACK_RIGHT",
                "BACK_LOWER",
                "BODY_HANDS",
                "BODY_OTHER",
                "COMPETING_RESPONSE"
            ]
        },
        "EngagedDeflectedType": {
            "name": "EngagedDeflectedType",
            "values": [
                "ENGAGED_BEHAVIOR",
                "DEFLECTED_BEHAVIOR"
            ]
        },
        "LocationType": {
            "name": "LocationType",
            "values": [
                "BEDROOM",
                "BATHROOM",
                "KITCHEN",
                "LIVING_ROOM",
                "WORK",
                "SCHOOL",
                "VEHICLE",
                "OUT_AND_ABOUT",
                "OTHER"
            ]
        },
        "MoodType": {
            "name": "MoodType",
            "values": [
                "CALM",
                "HAPPY",
                "BORED",
                "SAD",
                "TIRED",
                "ASHAMED",
                "ANGRY",
                "FRUSTRATED",
                "ANXIOUS"
            ]
        },        
```

the `index.d.ts` entries are the same as posted a few messages above.

I have not tried a clean project, but I will try a single, isolated script in my current project to see if it repros. I have not seen any other model in my project with this issue, it's just `HabitEpisode`, and only on post-`5.0.24` builds.

**Comment by lwang-79** [comment] 2023-07-30 00:27
Hi @svidgen, 

I encountered the same issue with the latest version and downgrading to 5.0.24 works for me.

After some troubleshooting, I was able to easily replicate the issue. It seems that the #11171 fix doesn't consider the following scenario:

A new object is created such as `new Todo({...})` but not imediately saved. Later on, use Todo.copyOf() to update some of the non-null fields and run DataStore.save(). It appears that all these non-updated fields are being removed and displayed as 'undefined' in the localModel. Therefore, the create mutation fails since "Null value for NonNull type"

Replication code
```
function App() {

  const todoRef = useRef();

  useEffect(() => {
    todoRef.current = new Todo({
      f1: 'f1',
      f2: 'f2',
      f3: 'f3',
      f4: 'f4',
      f5: 'f5',
      f6: 'f6'
    })
  }, []);

  const testClicked = () => {
    const toSave = Todo.copyOf(todoRef.current, updated => {
      updated.f1 = 'updated f1';
    });

    console.log(toSave);

    DataStore.save(toSave);
  }

  return (
    <div className="App">
      <button onClick={testClicked}>Test</button>
    </div>
  );
}
```

<img width="851" alt="Screenshot 2023-07-30 at 10 08 23 am" src="https://github.com/aws-amplify/amplify-js/assets/80386004/5a5ca922-3523-4bd9-97c2-2e56e136a3ec">

**Comment by chrisbonifacio** [comment] 2023-10-23 18:50
Hi @lwang-79 , apologies for the delay. It seems like the issue with your code snippet is that, in order to correctly update a record using `copyOf`, it must be first be saved to the local store.

So, your code would become

```js
function App() {

  const todoRef = useRef();

  useEffect(() => {
    todoRef.current = new Todo({
      f1: 'f1',
      f2: 'f2',
      f3: 'f3',
      f4: 'f4',
      f5: 'f5',
      f6: 'f6'
    })
  }, []);
  
  const savedTodo = await DataStore.save(todoRef.current);

  const testClicked = () => {
    const toUpdate = Todo.copyOf(savedTodo, updated => {
      updated.f1 = 'updated f1';
    });

    console.log(toUpdate);

    await DataStore.save(toUpdate);
  }

  return (
    <div className="App">
      <button onClick={testClicked}>Test</button>
    </div>
  );
}
```

**Comment by kklobe** [comment] 2023-10-25 20:34
@chrisbonifacio this didn't quite work for me, but when I add an explicit query before the `copyOf()`, it does:

```js
  const testClicked = () => {
    const savedTodo = await DataStore.save(todoRef.current);
    const queriedTodo = await DataStore.query(Todo, savedTodo.id);
    const toUpdate = Todo.copyOf(queriedTodo, updated => {
      updated.f1 = 'updated f1';
    });

    console.log(toUpdate);

    await DataStore.save(toUpdate);
  }
```

I'm testing with 5.3.11 and it looks good - thanks for following up on this.

**Comment by kklobe** [comment] 2023-11-14 15:52
Saving before updating with `copyOf` doesn't change anything for my scenario.

**Comment by svidgen** [comment] 2024-03-07 19:29
@kklobe I still haven't been able to repro this with the model you provided. I've actually tried to repro this issue and similar ones a good dozen times or so to no avail -- other than the caveat @chrisbonifacio noted around performing `copyOf`'s prior to saving. So, with that in mind, is there any possibility at all you can share a GH repro with a minimal reproduction of the issue with us?

**Comment by david-mcafee** [comment] 2024-03-18 17:40
@kklobe closing this ticket as we have not heard back from you, and we were unable to reproduce the issue. If you are still encountering this issue, please don't hesitate to let us know! Thank you!

**Closed by david-mcafee** 2024-03-18 17:40 UTC
Labels: bug, DataStore, pending-response

**Comment by kklobe** [comment] 2024-07-15 18:55
@david-mcafee @svidgen I have finally been able to reproduce this consistently. It happens when a non-nullable field is "updated" to the same value in the mutator when using `copyOf()`. 

Here is the HabitEpisode model I posted above:

```typescript
type LazyHabitEpisode = {
  readonly id: string;
  readonly owner?: string | null;
  readonly uuid?: string | null;
  readonly startDate: string;
  readonly activity?: ActivityType | keyof typeof ActivityType | null;
  readonly behavior: BehaviorType | keyof typeof BehaviorType;
  readonly dangerZone: DangerZone | keyof typeof DangerZone;
  readonly deflectedEngaged?: EngagedDeflectedType | keyof typeof EngagedDeflectedType | null;
  readonly durationInSeconds: number;
  readonly instances?: number | null;
  readonly observedInstances?: number | null;
  readonly competingResponseInstances?: number | null;
  readonly intensity?: number | null;
  readonly journal?: string | null;
  readonly location?: LocationType | keyof typeof LocationType | null;
  readonly mood?: MoodType | keyof typeof MoodType | null;
}
```

and here's a code snippet that will reproduce the error every time (using `aws-amplify v5.3.19`):

```typescript
  async updateHabitEpisode(
    maybeId: undefined | string,
    mutator: (draft: MutableModel<HabitEpisode>) => void,
  ): Promise<void> {
...
...
 const draft = new HabitEpisode({
        owner: owner,
        startDate: '2000-01-01T00:00:00.000Z',
        behavior: BehaviorType.HAIR_PULLING,
        dangerZone: DangerZone.HEAD_OTHER,
        durationInSeconds: 17,
      })

      const newEpisode_t = HabitEpisode.copyOf(draft, mutator)
      const newEpisode = HabitEpisode.copyOf(newEpisode_t, d => {
        d.durationInSeconds = 17
      })
      const savedObject = await DataStore.save(newEpisode)
```

If the mutator value for `durationInSeconds` is different from `draft`, it works:
```typescript
const draft = new HabitEpisode({
        owner: owner,
        startDate: '2000-01-01T00:00:00.000Z',
        behavior: BehaviorType.HAIR_PULLING,
        dangerZone: DangerZone.HEAD_OTHER,
        durationInSeconds: 17,
      })

      const newEpisode_t = HabitEpisode.copyOf(draft, mutator)
      const newEpisode = HabitEpisode.copyOf(newEpisode_t, d => {
        d.durationInSeconds = 16
      })
      const savedObject = await DataStore.save(newEpisode)
```

I hope the additional information is helpful, thanks!
