### ISSUE TITLE
No notification when websocket closes

### ISSUE THREAD

**Issue by Stephan221713** [aws-amplify/amplify-js#5403] opened 2020-04-14 10:11 UTC
**Describe the bug**
When AppSync-WebSockets close, the observer is not notified.

**To Reproduce**
Observed on Android devices running Google Chrome. When the device is in standby mode (+ maybe power save mode), webosckets often get closed. Our observer, which uses Amplify to subscribe to AppSync, is not notified of this, so we cannot tell if we need to reconnect after returning to the device.

**Expected behavior**
When the websocket closes, the observer should receive an error.

**Details**
We are using aws-amplify 3.0.6
The problematic code is in packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts lines 674-686:
```
if (type === MESSAGE_TYPES.GQL_CONNECTION_ACK) {
	ackOk = true;
	this.keepAliveTimeout = connectionTimeoutMs;
	this.awsRealTimeSocket.onmessage = this._handleIncomingSubscriptionMessage.bind(
		this
	);
	this.awsRealTimeSocket.onerror = err => {
		logger.debug(err);
		this._errorDisconnect(CONTROL_MSG.CONNECTION_CLOSED);
	};
	res('Cool, connected to AWS AppSyncRealTime');
	return;
}
```

As you can see, once the connection is established, messages and errors from the socket are passed to the observer, but a socket close is not. In our case, the socket only fires an onclose event, but no onerror when the websocket closes, so our observer is not notified. We patch our local version by treating onclose exactly like onerror and calling this._errorDisconnect(CONTROL_MSG.CONNECTION_CLOSED), which solves the issue for us. We decided not to create a Pull Request on this, because we are not sure if our solution has problematic side effects. However, it is very important for observers to be notified about closed websockets in some way.

**Comment by adamup928** [comment] 2020-07-28 22:42
Can confirm that applying the local patch mentioned by @Stephan221713 allows our subscriptions to reconnect gracefully when returning from standby on MacOS. Without this fix, the subscriptions do not connect.

**Comment by greimela** [comment] 2020-07-29 08:50
I just opened a pull request fixing this issue, since it seems to impair multiple people.

**Comment by ericclemmons** [comment] 2020-08-11 22:11
I'm reviewing #6448 now.

@adamup928 can you describe your scenario so I can test that as well?  It sounds like you have an app with `GraphQL.subscribe(...)`, close the lid, then get socket errors in the devtools' Network tab?

**Comment by adamup928** [comment] 2020-08-11 22:48
@ericclemmons - that's essentially correct.  We're establishing a subscription exactly as the docs specify [here](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js#enable-queries-mutations-and-subscriptions) like so:

```
import { API } from 'aws-amplify';
import { onCreateTodo } from './graphql/subscriptions';

// Subscribe to creation of Todo
const subscription = API.graphql(
    graphqlOperation(onCreateTodo)
).subscribe({
    next: (todoData) => {
      console.log(todoData);
      // Do something with the data
    }
});
```

Then (at least on MacOS), close the lid, wait a bit for the system to hibernate (30 seconds or so) and then open the lid and note the socket errors in the network tab.

Hope this helps!

**Comment by ericclemmons** [comment] 2020-08-11 22:50
@adamup928 That's a fantastic description! I have an example already doing something like that, so this should be a cinch to validate. Thanks again :)

**Comment by elorzafe** [comment] 2020-09-08 21:24
@greimela fix was already published to latest, are you still having this issue?

**Comment by greimela** [comment] 2020-09-10 07:37
@elorzafe We upgraded to the latest amplify version and the issue is fixed for us!

**Comment by elorzafe** [comment] 2020-09-10 16:24
@greimela that is great to read!! 

I will close the issue and thank you for your contribution!

**Closed by elorzafe** 2020-09-10 16:24 UTC
Labels: PubSub, bug
