### ISSUE TITLE
DataStore.configure not working with Selective Sync

### ISSUE THREAD

**Issue by EliasCoelho** [aws-amplify/amplify-js#7101] opened 2020-11-02 15:49 UTC
**Describe the bug**
We are provide DataStore.configure with new sintax for support Selective Sync and DataStore not working. 

**To Reproduce**
1. Configure the DataStore.configure as following
DataStore.configure({
            syncExpressions: [
                syncExpression(db.SupplierSetup, (c) =>
                    c.supplierId("eq", currentSupplier)
                ),
            ],
            errorHandler: (error) => {
                console.log(error)
            },
            conflictHandler: (conflict) => {
                console.log("DataStore.Configure() error", conflict)
            },
            maxRecordsToSync: 3000,
            fullSyncInterval: 2, //minutes
        })
2. see the following error
![image](https://user-images.githubusercontent.com/9299757/97888143-2ce04480-1d01-11eb-8af3-41182876b0c2.png)

**What is Configured?**
"@aws-amplify/ui-react": "^0.2.26",
"aws-amplify": "^3.3.6",
 "aws-sdk": "^2.783.0",

**Comment by EliasCoelho** [comment] 2020-11-02 15:52
Hi @iartemiev , we are setting the DataStore.configure() as describe it in the documentation, but it not working... 
The documentation link is the following:
https://docs.amplify.aws/lib/datastore/sync/q/platform/js#async-expressions

**Comment by iartemiev** [comment] 2020-11-02 16:14
@EliasCoelho what value does `currentSupplier` have? Will this value be available when you're starting DataStore? Are there any other errors you see in the console?

**Comment by iartemiev** [comment] 2020-11-02 16:24
Do you still get the error if you use the function syntax, as opposed to the shorthand?
```js
DataStore.configure({
  syncExpressions: [
    syncExpression(db.SupplierSetup, () => {
      return (c) => c.supplierId('eq', currentSupplier);
    }),
  ],
});
```

**Comment by EliasCoelho** [comment] 2020-11-02 16:46
currentSupplier is a string with the value for id of SupplierSetup table. I set the value directly in the configure object 

        console.log("Doing DataStore.configure() && DataStore.start()")
        DataStore.configure({
            errorHandler: (error) => {
                console.log(error)
            },
            conflictHandler: (conflict) => {
                console.log("DataStore.Configure() error", conflict)
            },
            maxRecordsToSync: 3000,
            fullSyncInterval: 2, //minutes
            syncExpressions: [
                syncExpression(db.SupplierSetup, () => {
                    return (c) =>
                        c.supplierId(
                            "eq",
                            "879f521f-fbbc-4cdb-b916-3c842a4224aa"
                        )
                }),
            ],
        })

        await DataStore.start()



![image](https://user-images.githubusercontent.com/9299757/97894865-69b03980-1d09-11eb-83a4-eff9bcd448e2.png)

**Comment by iartemiev** [comment] 2020-11-02 17:05
Could you try deleting your lock file and re-installing your dependencies?
```bash
rm -rf node_modules yarn.lock
yarn
```

**Comment by EliasCoelho** [comment] 2020-11-02 17:33
I do... npm clean cache --force and npm install again, but it not work for me

**Comment by iartemiev** [comment] 2020-11-02 19:34
Could you share the entire contents of your SyncData.js file?

**Comment by EliasCoelho** [comment] 2020-11-02 19:41
Sure... 

[syncData.txt](https://github.com/aws-amplify/amplify-js/files/5477581/syncData.txt)

This file is a component for show loading gif while DataStore Sync to Ready event and redirect to Main view...

**Comment by iartemiev** [comment] 2020-11-02 22:34
I don't see anything in that file that should be causing any problems. 
Are you calling `DataStore.configure` anywhere else in your app?

Here's a sample app running in CodeSandbox that does the same thing you're attempting to do in this issue and it works fine: https://codesandbox.io/s/dank-surf-8q8to 

I'm going to mark this as "could not reproduce". If you can provide a sample app that exhibits this issue, I'll be happy to take another look.

**Comment by EliasCoelho** [comment] 2020-11-03 00:26
Hi @iartemiev ... I test your codesandbox and I can reproduce it. You only must add aws-amplify @3.3.6 as  the documentation indicate it.

![image](https://user-images.githubusercontent.com/9299757/97933633-af8cf200-1d49-11eb-8584-2f566ea89bfc.png)


![image](https://user-images.githubusercontent.com/9299757/97933517-650b7580-1d49-11eb-8156-91732da72e52.png)

**Comment by hmisonne** [comment] 2020-11-03 02:06
I am having the same issue..
I tried adding the `aws-amplify@3.3.6` package but it did not work.

It looks like `syncExpression` is only accessible from the package `@aws-amplify/datastore": "^2.7.1` which is different from the tutorial's instructions: 
![image](https://user-images.githubusercontent.com/52170580/97938202-abef7000-1d35-11eb-929e-e877be9735cd.png)

After running `npm i @@aws-amplify/datastore@2.7.1` to add this specific package it raises another error (which I did not have before)
![image](https://user-images.githubusercontent.com/52170580/97938283-e1945900-1d35-11eb-8fe2-239f32e20502.png)

**Comment by iartemiev** [comment] 2020-11-03 02:30
You're right, @EliasCoelho, thank you for pointing that out.

Will be fixed in this PR: https://github.com/aws-amplify/amplify-js/pull/7104

**Comment by iartemiev** [comment] 2020-11-03 02:31
@hmisonne, you're seeing that error due to having both `@aws-amplify/datastore` and `aws-amplify` dependencies installed at the same time. 

Here's what you can do in the meantime if you'd like to use this feature: uninstall `aws-amplify` and install the other Amplify dependencies you're using separately. 

So e.g., if you currently have:
```js
import Amplify, { Auth, DataStore } from 'aws-amplify`
```
You could install and import from the following:
```js
import Amplify from '@aws-amplify/core`
import { Auth } from '@aws-amplify/auth`
import { DataStore } from '@aws-amplify/datastore`
```

Once we deploy the fix in that PR you can go back to importing everything from `aws-amplify`.

**Comment by EliasCoelho** [comment] 2020-11-03 03:32
thanks @iartemiev, I wait to PR approved for upgrade version and use it.

**Comment by hocnx** [comment] 2020-11-03 14:08
@EliasCoelho 
I faced the same error. The bellow solution work for me.

Instead of 
``` javascript
import { DataStore, syncExpression } from 'aws-amplify';
```

Just use
```javascript
import {DataStore, syncExpression} from "@aws-amplify/datastore";
```

Bellow is my package version
```
    "@aws-amplify/core": "^3.8.1",
    "@aws-amplify/datastore": "^2.7.1",
    "aws-amplify": "^3.3.6",
```

**Comment by hmisonne** [comment] 2020-11-03 15:40
> @hmisonne, you're seeing that error due to having both `@aws-amplify/datastore` and `aws-amplify` dependencies installed at the same time.
> 
> Here's what you can do in the meantime if you'd like to use this feature: uninstall `aws-amplify` and install the other Amplify dependencies you're using separately.
> 
> So e.g., if you currently have:
> 
> ```js
> import Amplify, { Auth, DataStore } from 'aws-amplify`
> ```
> 
> You could install and import from the following:
> 
> ```js
> import Amplify from '@aws-amplify/core`
> import { Auth } from '@aws-amplify/auth`
> import { DataStore, syncExpression } from '@aws-amplify/datastore`
> ```
> 
> Once we deploy the fix in that PR you can go back to importing everything from `aws-amplify`.

Thanks @iartemiev , I followed your instructions and uninstalled the `aws-amplify` package and replaced all the imports but I am having the following issue:

```
Module not found: Can't resolve 'aws-amplify' in 'C:\...\node_modules\aws-amplify-react-native\dist'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
```

**Comment by iartemiev** [comment] 2020-11-03 15:47
@hmisonne `aws-amplify-react-native` has a hard dependency on `aws-amplify`, so you won't be able to use those instructions. We'll merge the PR a bit later today, so you'll be able to use the prerelease version of `aws-amplify` then. I'll update this issue once this fix gets deployed.

**Closed** 2020-11-03 16:30 UTC
Labels: DataStore

**Comment by iartemiev** [comment] 2020-11-03 19:07
PR has been merged. The fix is now available in `aws-amplify@3.3.8-unstable.1` and will be included in the next release.

If you have `aws-amplify` as well as `@aws-amplify/datastore` in your package.json, please uninstall `@aws-amplify/datastore`. Having both can cause unintended consequences.

**Comment by iartemiev** [comment] 2020-11-03 19:08
@EliasCoelho @hmisonne ^^

**Comment by EliasCoelho** [comment] 2020-11-03 19:28
@iartemiev the offical package with the fix is awailable soon?

**Comment by iartemiev** [comment] 2020-11-03 19:38
@EliasCoelho yes, we typically do a release weekly

**Comment by hmisonne** [comment] 2020-11-03 21:29
Thanks @iartemiev , I can confirm that downloading the `aws-amplify@3.3.8-unstable.1` version worked for me!

**Comment by hmisonne** [comment] 2020-11-04 02:08
@iartemiev I am wondering if installing and uninstalling aws-amplify packages could have had unexpected impacts.
After starting the expo app on an Android emulator, I am having this issue which I did not have before. The web interface is till working fine. Here is the error: 
```
Failed building JavaScript bundle.
Unable to resolve "../asyncstorage" from "node_modules\@aws-amplify\datastore\lib-esm\storage\adapter\getDefaultAdapter\index.native.js"
```
I am not using asynstorage in my app anywhere. I also compared this particular file with another file from a brand new project and it has the exact same content.

I know this is out of the scope of the original issue, I was just hoping to see if there is a way to reset my packages.

**Comment by iartemiev** [comment] 2020-11-04 15:28
@hmisonne It appears you might have conflicting Amplify dependencies because asyncstorage.js recently got renamed to AsyncStorageAdapter.js. So `getDefaultAdapter\index.native.js` should not be attempting to import ../asyncstorage.

Could you try running 
```
rm -rf node_modules yarn.lock
yarn
```
(Or if using npm, delete package-lock.json instead)
Then run your app again and let me know if that helps. 

If you continue seeing that error, please run `npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages` and post your output

**Comment by hmisonne** [comment] 2020-11-04 16:06
Thank you for your reply @iartemiev, I really appreciate it! So I tried deleting package-lock.json and running `npm i` before running my app but I am still having the same error.

Here is the output of the envinfo:

```
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.48 GB / 15.78 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.183
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @babel/core: ~7.9.0 => 7.9.6
    @iconify/icons-mdi: ^1.0.142 => 1.0.142
    @iconify/react: ^1.1.3 => 1.1.3
    @react-native-community/masked-view: 0.1.10 => 0.1.10
    @react-native-community/netinfo: 5.9.6 => 5.9.6
    @react-native-community/picker: 1.6.6 => 1.6.6
    @react-navigation/bottom-tabs: ^5.9.1 => 5.9.1
    @react-navigation/native: ^5.7.5 => 5.7.5
    @react-navigation/stack: ^5.9.2 => 5.9.2
    aws-amplify: ^3.3.7 => 3.3.7
    aws-amplify-react-native: ^4.2.7 => 4.2.7
    babel-polyfill: ^6.26.0 => 6.26.0
    expo: ~39.0.2 => 39.0.3
    expo-font: ^8.3.0 => 8.3.0
    expo-mail-composer: ^8.4.0 => 8.4.0
    expo-splash-screen: ^0.6.2 => 0.6.2
    expo-status-bar: ~1.0.2 => 1.0.2
    ini: ^1.3.5 => 1.3.5
    inquirer: ^6.5.1 => 6.5.2
    jest: ^26.4.2 => 26.4.2
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    react-native-gesture-handler: ~1.7.0 => 1.7.0
    react-native-paper: ^4.3.0 => 4.3.0
    react-native-reanimated: ~1.13.0 => 1.13.1
    react-native-safe-area-context: 3.1.4 => 3.1.4
    react-native-screens: ~2.10.1 => 2.10.1
    react-native-web: ~0.13.12 => 0.13.14
    react-redux: ^7.2.1 => 7.2.1
    react-redux-loading-bar: ^5.0.0 => 5.0.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-test-renderer: ^16.13.1 => 16.13.1
    redux: ^4.0.5 => 4.0.5
    redux-thunk: ^2.3.0 => 2.3.0
    redux-undo: ^1.0.1 => 1.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.31.1
    @ionic/cli: 6.7.0
    bower: 1.8.8
    create-react-native-app: 3.1.0
    exp: 57.2.1
    expo-cli: 3.27.12
    express-generator: 4.16.1
    gulp: 4.0.2
    sequelize-cli: 6.1.0
    serverless: 1.71.3
    sharp-cli: 1.14.1
    wscat: 4.0.0
```

**Comment by iartemiev** [comment] 2020-11-04 17:10
@hmisonne great! Glad it's working now. 

Typically, deleting node_modules and the lock file and then re-installing is a good thing to try with these types of issues.

**Comment by EliasCoelho** [comment] 2020-11-12 21:25
Hi @iartemiev, we are waiting npm release of aws-amplify@3.3.8 version, but it isn't release yet. Do you know about when it can be available for download from npm?

We need implement it for PRD enviroment asap..

**Comment by iartemiev** [comment] 2020-11-12 22:30
Hey @EliasCoelho we'll have the next release out by tomorrow

**Comment by EliasCoelho** [comment] 2020-11-12 22:42
Ok, thanks @iartemiev ...

**Comment by iartemiev** [comment] 2020-11-13 00:20
@EliasCoelho [aws-amplify@3.3.8](https://www.npmjs.com/package/aws-amplify) just got released (:

**Comment by EliasCoelho** [comment] 2020-11-13 01:10
@iartemiev thanks again... it's a good news... we'll implement it in this moment
