### ISSUE TITLE
Blank password on logon gives "Custom auth lambda trigger is not configured for the user pool" error

### ISSUE THREAD

**Issue by TonyAsbestosAlert** [aws-amplify/amplify-js#7067] opened 2020-10-27 12:06 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
User pool configured for login with email only.
If I attempt to login with an email address but leave the password field empty then i get the message:
   "Custom auth lambda trigger is not configured for the user pool."
A similar issue was recently fixed for the account registration dialog.

**Amplify CLI Version**
4.31.1

**To Reproduce**
1) Cognito user pool - required attributes: email, username attributes: email
2) amplify logon with an email address and NO PASSWORD

**Expected behavior**
I would expect a "please enter a password" message

**Screenshots**
![Screenshot 2020-10-27 115803](https://user-images.githubusercontent.com/71257638/97298709-bef0d480-184b-11eb-8bd4-d55b70a13cd5.png)

**Desktop (please complete the following information):**
 - OS: debian
 - Node Version: v10.21.0

**Additional context**
The error occurs both on my local (debian) development instance and on a published instance.

**Comment by jhockett** [comment] 2020-10-27 17:06
Hi @TonyAsbestosAlert. I had your issue transferred because the error message you're getting isn't apart of the CLI. cc @sammartinez

**Comment by elorzafe** [comment] 2020-10-27 20:53
Thanks @TonyAsbestosAlert 

This is a duplicate of the issue #5623 I will close this issue but please keep looking on the other for further information

**Closed by elorzafe** 2020-10-27 20:53 UTC
