### ISSUE TITLE
AsyncStorage conflict between core and communit

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#3422] opened 2019-06-08 16:34 UTC
I wanted to put this out to help accelerate the conversion to the community version of asyncstorage.

It appears there is a race condition if both community version and core version are being used on iOS.  It causes both to try to write to the same file and thus overwrite each other.  See this github issue here:
https://github.com/react-native-community/react-native-async-storage/issues/118#issuecomment-500138053

**Comment by paul-doherty** [comment] 2019-06-10 07:51
I second this. Recently found this as well. For me it manifested in logins being persisted to Async storage but closing the app and restarting it I am forced to login again. I eventually tracked it down and AsyncStorage.getItem was returning `undefined` for values **that were present** in the storage. 

This is pretty serious if we cannot rely on Async storage

**Comment by rogueturnip** [comment] 2019-06-10 20:37
I suspect moving to the community asyncstorage would be need to be a major release because switching this out in a minor release will break people that are still using the core asyncstorage in their app.

**Comment by jessedoyle** [comment] 2019-06-10 22:50
@rogueturnip 

> I suspect moving to the community asyncstorage would be need to be a major release

I made a comment on another issue [here](https://github.com/aws-amplify/amplify-js/issues/3209#issuecomment-495294744) with a proposal for backwards-compatibility dependency injection.

For ease of reference, I propose something along the lines of:

```js
import MyAsyncStorage from '@react-native-community/async-storage';

Amplify.configure({
  ...
  Dependencies: {
    AsyncStorage: MyAsyncStorage, // would default to react-native provided AsyncStorage
  },
  ...
});
```

**Comment by haverchuck** [comment] 2019-06-14 20:51
@rogueturnip Disclaimer: I am not super familiar with this ongoing issue with RN AsyncStorage.  If this issue you are having is specific to the Auth module with Amplify, could you try writing your own storage wrapper for Auth (which Amplify supports as outlined [here](https://aws-amplify.github.io/docs/js/authentication#manual-setup)) to use whichever specific version of AsyncStorage you want?

**Comment by rogueturnip** [comment] 2019-06-14 22:06
Thanks!  I will do that when I get back to upgrading the AsyncStorage.  I looked at the custom storage wrapper example that used AsyncStorage.  I couldn't get it to work.  I wasn't sure where MemoryStorage came from to import it.

**Comment by tallpants** [comment] 2019-06-21 02:28
We should move Amplify over to using @react-native-community/async-storage because AsyncStorage is being removed from React Native core in the next release (0.60) which should be out in a few weeks -- which means someone who `react-native init`s a new application and follows the instructions on Amplify's docs exactly will end up with a broken app.

Using your own storage wrapper should work, but it's not a good experience to have a broken app by default.

This would probably necessitate a major release since we'd need people to install and link `@react-native-community/async-storage` first to use Amplify (unless they're on Expo).

In the meantime I'd at least suggest adding this issue and the workaround to the docs because it's pretty serious to not be able to rely on async storage @haverchuck. I'd be happy to open a PR for it if you can tell me where in the docs it'd be most appropriate to put this!

**Comment by tallpants** [comment] 2019-06-21 02:31
Also cc @powerful23 just so you're aware of this

**Comment by willdady** [comment] 2019-07-11 00:36
Moving to @react-native-community/async-storage needs to be done however I think it would be good to be able to override the default with your own storage engine similar to what @jessedoyle is saying above. The problem is you can't use AsyncStorage from core _and_ the community one in the same app. It's one or the other. Being able to choose which storage engine could make the transition to using the community one easier, especially if you still have other dependencies in your app using AsyncStorage from core.

**Comment by mllrmat** [comment] 2019-07-29 14:25
Is there any progress on this issue? This is a pressing issue for me as it breaks functionality and can lead to some very strange side effects. 
E.g. If I use amplify which uses the core async storage and another dependency which uses the new one, those dependencies will overwrite each others changes.

**Comment by joelfsreis** [comment] 2019-07-29 18:55
I would like to know as well if progress are being made. We upgraded RN to latest version and we use amplify-js, so any input on the issue update would be much appreciated

**Comment by taschik** [comment] 2019-08-01 01:21
Is there any update from the maintainers? Right now, aws-amplify is not usable with current RN 0.60.X as it can't persist the authentication. So either having a hotfix for the community version or the specification of a custom storage via configuration would be desirable.

**Comment by anthonyjoeseph** [comment] 2019-08-03 14:41
> Thanks! I will do that when I get back to upgrading the AsyncStorage. I looked at the custom storage wrapper example that used AsyncStorage. I couldn't get it to work. I wasn't sure where MemoryStorage came from to import it.

@rogueturnip using `MyStorage` instead of `MemoryStorage` works

**Comment by rogueturnip** [comment] 2019-08-03 14:53
I switched back to the old asyncstorage for the time being because of time.  @anthonyjoeseph  would you be willing to post your solution for everyone?

**Comment by anthonyjoeseph** [comment] 2019-08-03 15:11
https://gist.github.com/anthonyjoeseph/16ab868408bb874a742fdf77d0be3fd1

**Comment by anthonyjoeseph** [comment] 2019-08-03 15:21
My guess is that the `MyStorage` implementation referenced in the [amplify docs](https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens) is an imperfectly modified version of the actual `MemoryStorage` [implementation](https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens) used in amplify, which is why there's that confusing static reference to `MemoryStorage.syncPromise`, and the unused reference to `MyStorage.syncPromise`.

**Comment by rogueturnip** [comment] 2019-08-03 15:23
Thanks so much!  if anyone from AWS is reading this it would make alot of sense to use @anthonyjoeseph example in your documentation and comment on the conflict with RN 0.60.

**Comment by taschik** [comment] 2019-08-22 18:10
@rogueturnip I saw your post here: https://github.com/react-native-community/async-storage/issues/118 and was wondering what your final solution for the problem here is. 

Are you using the custom storage workaround or did you downgrade to an older version of async-storage? and if so which version? Thanks so much for the support!

**Comment by rogueturnip** [comment] 2019-08-22 18:56
I took the simple route and just downgraded to use the react native core asyncstorage.

Sent from Mail for Windows 10

**Comment by kirkryan** [comment] 2019-09-11 17:07
This caused a bug that took days to track down - Please ensure that Amplify is updated to use the react-native-community async-storage, please!

**Comment by lenarmazitov** [comment] 2019-10-09 11:58
I have same bug, and as a result I have troubles with my own redux-persist store. I can not clean it.

**Comment by TomJKlug** [comment] 2019-10-25 22:31
This also caused a huge headache. Would greatly appreciate a switch the the react-native-community/async-storage

**Comment by mllrmat** [comment] 2019-10-30 16:37
Is there any progress on this issue?

**Comment by mllrmat** [comment] 2019-10-31 08:58
For all that having an issue with AsyncStorage and Amplify here is my workaround: 

1. Implement your own storage class, that uses the community async storage: 
```
import AsyncStorage from '@react-native-community/async-storage';

const MEMORY_KEY_PREFIX = '@MemoryStorage:';
let dataMemory = {};

export default class AmplifyAuthStorage {
  private static syncPromise = null;

  /**
   * This is used to set a specific item in storage
   */
  static setItem(key, value) {
    AsyncStorage.setItem(MEMORY_KEY_PREFIX + key, value, error => {
      console.log('error setting item', error);
    });
    dataMemory[key] = value;
    return dataMemory[key];
  }

  /**
   * This is used to get a specific key from storage
   */
  static getItem(key) {
    return Object.prototype.hasOwnProperty.call(dataMemory, key)
      ? dataMemory[key]
      : undefined;
  }

  /**
   * This is used to remove an item from storage
   */
  static removeItem(key) {
    AsyncStorage.removeItem(MEMORY_KEY_PREFIX + key);
    return delete dataMemory[key];
  }

  /**
   * This is used to clear the storage
   */
  static clear() {
    dataMemory = {};
    return dataMemory;
  }

  /**
   * Will sync the MemoryStorage data from AsyncStorage to storageWindow MemoryStorage
   */
  static sync() {
    if (!this.syncPromise) {
      console.log('****** sync items to memory storage!');
      this.syncPromise = new Promise((res, rej) => {
        AsyncStorage.getAllKeys((errKeys, keys) => {
          if (errKeys) {
            rej(errKeys);
          }
          const memoryKeys = keys.filter(key =>
            key.startsWith(MEMORY_KEY_PREFIX)
          );
          AsyncStorage.multiGet(memoryKeys, (err, stores) => {
            if (err) {
              rej(err);
            }
            stores.map((result, index, store) => {
              const key = store[index][0];
              const value = store[index][1];
              const memoryKey = key.replace(MEMORY_KEY_PREFIX, '');
              dataMemory[memoryKey] = value;
            });
            res();
          });
        });
      });
    }
    return this.syncPromise;
  }
}
```

2. Then use your storage class in the Auth configuration
```
Auth.configure({storage: AmplifyAuthStorage});
```
or

```
Auth: {
        identityPoolId: xxx,
        region: xxx,
        userPoolId: xxx,
        userPoolWebClientId: xxx,
        mandatorySignIn: false,
        storage: AmplifyAuthStorage
      }
```
3. Replace all AsyncStorage imports in your code with the community version. 

Please note: 
- Unfortunately the example in the documentation is very confusing (see https://github.com/aws-amplify/docs/issues/983) as it uses a non defined variable. 
- You have to use the prefix `@MemoryStorage:` instead of `@MyStorage:` otherwise all your users are logged out!

It would be very nice, if help would come directly from the amplify team, on such critical issues in a commercial product.

**Comment by lvlrSajjad** [comment] 2019-10-31 09:58
@mllrmat just replace 
```es6
  private static syncPromise = null;
```
with
```es6
  static syncPromise = null;
```

**Comment by lafiosca** [comment] 2019-11-05 16:14
One thing I don't understand just looking at this file: is there some logic elsewhere that clears `syncPromise`, or can the `sync` method effectively only ever be used once?

**Comment by lafiosca** [comment] 2019-11-06 02:43
Based on @mllrmat 's code above, I made a more TypeScript-y version: https://gist.github.com/lafiosca/774fa014d3326fcc992b55198ac5ea1d

While working on this, I found several things about the storage module interface odd; for example, `setItem` returns the value being set, but it doesn't appear that the current lib code uses the return value. Seems to me it would be nicer if these methods could return Promises, but that would obviously require more invasive changes to the packages.

**Comment by joebernard** [comment] 2019-12-06 03:52
Bad bot, not stale.

**Comment by camin-mccluskey** [comment] 2019-12-31 09:09
Any update on this? This is causing a major bug (logged out users on each app start) on a product application

**Comment by jessedoyle** [comment] 2020-01-30 14:49
This is still very much a significant issue. Please don't mark the issue as stale.

**Comment by Off2Race** [comment] 2020-02-29 15:36
This is still an issue. Many of us have worked around the problem but it should be fixed. Please don't mark the issue as stale.

**Comment by alexpanov** [comment] 2020-03-05 09:21
This makes me want to migrate away from amplify. What a damn shame.

**Comment by mauerbac** [comment] 2020-04-15 16:04
hi @alexpanov - sorry to hear that. Following up on this -- are you still facing this issue?

**Closed** 2020-04-23 04:09 UTC
Labels: React Native, pending-close-response-required, question

**Comment by iamstiil** [comment] 2020-11-16 15:03
FYI: Expo moved to the comminity package :)
[Reference](https://docs.expo.io/versions/latest/sdk/async-storage/)

**Comment by sotomaque** [comment] 2021-02-23 20:57
updates on this?

**Comment by cristinaITdeveloper** [comment] 2022-04-11 12:12
I have this problem. I have the aws-amplify@4.3.19 version.
