### ISSUE TITLE
Set chunk size for multi-part uploads

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-js#10757] opened 2022-12-09 17:55 UTC
### Is this related to a new or existing API?

Storage

### Describe the feature you'd like to request

Allow for larger chunks in multi-part uploads. 

### Describe the solution you'd like

https://github.com/aws-amplify/amplify-js/blob/main/packages/storage/src/providers/AWSS3ProviderManagedUpload.ts#L43

https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html

The chunk size is hard-coded at ~5mb. The maximum parts for an S3 upload is 10000. Therefore the maximum file size allowed by a multi-part upload is ~50gb.

### Describe alternatives you've considered

There isn't really an alternative other than to not use Amplify Storage. You could use non-mulit-part uploads, but then the user cannot pause the upload and for large files (multi-GB) that would not be a good experience. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by abdallahshaban557** [comment] 2022-12-09 18:00
Closing this as a duplicate of #8772

**Closed by abdallahshaban557** 2022-12-09 18:00 UTC
Labels: feature-request, Storage
