### ISSUE TITLE
Cognito error: The server did not understand the operation that was requested

### ISSUE THREAD

**Issue by hmisonne** [aws-amplify/amplify-js#7113] opened 2020-11-04 01:07 UTC
**Describe the bug**
I am developing a React Native App with Expo and after running the app, I am having this error after starting the datastore:

![image](https://user-images.githubusercontent.com/52170580/98056616-3519ac00-1df5-11eb-8e24-b098fdee3968.png)

However, it does not prevent me from using the app, and the user get authenticated.

**Code Snippet**

```javascript
import { withAuthenticator } from "aws-amplify-react-native";

const App = () => {
  ...
}
export default withAuthenticator(App);

```

```javascript
import { Auth } from 'aws-amplify'

 async identifyUser() {
    try {
      const userInfo = await Auth.currentUserInfo();
      ...
      console.log("User info retrieved successfully!");
    } catch (error) {
      console.log("Error retrieving user info", error);
    }
  }
````

**Screenshots**

![image](https://user-images.githubusercontent.com/52170580/98057161-78284f00-1df6-11eb-8563-b0cc02d5cfa0.png)

**Project Dependencies**
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.98 GB / 15.78 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @babel/core: ~7.9.0 => 7.9.6
    @iconify/icons-mdi: ^1.0.142 => 1.0.142
    @iconify/react: ^1.1.3 => 1.1.3
    @react-native-community/masked-view: 0.1.10 => 0.1.10
    @react-native-community/netinfo: 5.9.6 => 5.9.6
    @react-native-community/picker: 1.6.6 => 1.6.6
    @react-navigation/bottom-tabs: ^5.9.1 => 5.9.1
    @react-navigation/native: ^5.7.5 => 5.7.5
    @react-navigation/stack: ^5.9.2 => 5.9.2
    aws-amplify: ^3.3.7 => 3.3.7
    aws-amplify-react-native: ^4.2.7 => 4.2.7
    babel-polyfill: ^6.26.0 => 6.26.0
    expo: ~39.0.2 => 39.0.3
    expo-font: ^8.3.0 => 8.3.0
    expo-mail-composer: ^8.4.0 => 8.4.0
    expo-splash-screen: ^0.6.2 => 0.6.2
    expo-status-bar: ~1.0.2 => 1.0.2
    ini: ^1.3.5 => 1.3.5
    inquirer: ^6.5.1 => 6.5.2
    jest: ^26.4.2 => 26.4.2
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    react-native-gesture-handler: ~1.7.0 => 1.7.0
    react-native-paper: ^4.3.0 => 4.3.0
    react-native-reanimated: ~1.13.0 => 1.13.1
    react-native-safe-area-context: 3.1.4 => 3.1.4
    react-native-screens: ~2.10.1 => 2.10.1
    react-native-web: ~0.13.12 => 0.13.14
    react-redux: ^7.2.1 => 7.2.1
    react-redux-loading-bar: ^5.0.0 => 5.0.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-test-renderer: ^16.13.1 => 16.13.1
    redux: ^4.0.5 => 4.0.5
    redux-thunk: ^2.3.0 => 2.3.0
    redux-undo: ^1.0.1 => 1.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.31.1
    @ionic/cli: 6.7.0
    bower: 1.8.8
    create-react-native-app: 3.1.0
    exp: 57.2.1
    expo-cli: 3.27.12
    express-generator: 4.16.1
    gulp: 4.0.2
    sequelize-cli: 6.1.0
    serverless: 1.71.3
    sharp-cli: 1.14.1
    wscat: 4.0.0
```

**Comment by amhinson** [comment] 2020-11-06 16:52
@hmisonne A few questions:
- Could you share your `Amplify.configure()` as well as `aws-exports.js` with any sensitive data removed?
- Does this error go away if you remove DataStore, but continue to use Auth?

**Comment by amhinson** [comment] 2020-11-06 17:34
@hmisonne If you remove datastore (temporarily) from your JS code, are you still seeing the errors?

**Comment by hmisonne** [comment] 2020-11-06 17:48
@amhinson, if I am just rendering a simple app without Datastore :

```javascript
import React from "react";
import Amplify from "aws-amplify";
import config from "./aws-exports";
import { withAuthenticator } from "aws-amplify-react-native";

Amplify.configure({
  ...config,
  Analytics: {
    disabled: true,
  },
});

const App = () => {
  return(
    <View>
      <Text>Hello</Text>
    </View>
  )
};

export default withAuthenticator(App);
```
I do not have any errors.

**Comment by hmisonne** [comment] 2020-11-06 19:52
After spending some time to debug, it looks like this error is only occurring while running the project locally on a **Windows Operating System**. 

This error is not showing on Android Emulator, or Ubuntu.

Thanks again for your help @amhinson :smiley_cat:

**Comment by div5yesh** [comment] 2021-04-01 20:40
Hi @hmisonne, closing this issue since I was not able to reproduce it. If you are still facing this issue please let us know.

**Closed by div5yesh** 2021-04-01 20:40 UTC
Labels: Auth, React Native, to-be-reproduced
