### ISSUE TITLE
updateEndpoint method doesn't have endpointId

### ISSUE THREAD

**Issue by bigzidane** [aws-amplify/amplify-js#7649] opened 2021-01-29 15:08 UTC
**Is your feature request related to a problem? Please describe.**
Currently when I use updateEndpoint method, I have no way to pass endpointId (which does exist in 'configure' method). It is causing everytime I call updateEndpoint with the same 'address', I will have multiple endpoint ids stored.

**Describe the solution you'd like**
I would like to have endpointId as part of updateEndpoint and we can control create or update endpoint id

**Additional context**
I have an use case is
1. An user user1@domain.com login -> call updateEndpoint with 'address' field is user1@domain.com and then it is stored as a new endpoint id as Active status
2. An user user2@domain.com login -> call updateEndpoint with 'address' field is user2@domain.com and then it is stored as a new endpoint id as Active status
3. The user user1@domain.com login again from another device or from different time -> call updateEndpoint with 'address' field is user1@domain.com and then it is stored as a new endpoint id as Active status

Now user1@domain.com has 2 endpoints stored at back-end.

**Comment by tannerabread** [comment] 2022-11-18 20:14
Closing as duplicate of #4573, which has a workaround in the comments

**Closed by tannerabread** 2022-11-18 20:14 UTC
Labels: feature-request, Analytics
