### ISSUE TITLE
signOut() is asking users to sign in again when using apple as identity provider 

### ISSUE THREAD

**Issue by ryanSoftwareEngineer** [aws-amplify/amplify-js#13132] opened 2024-03-16 20:14 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Amplify CLI

### Environment information

<details>

```
"@aws-amplify/rtn-web-browser": "^1.0.20",
...

```

</details>

### Describe the bug
I configured sign in with apple and it works. i'm able to create and sign in to aws cognito. 
i followed this tutorial: https://docs.amplify.aws/react-native/build-a-backend/auth/add-social-provider/

the following code however asks the user to sign in again before it executes. 
```
import { signOut } from "aws-amplify/auth";

 await signOut();      
```

They don't actually have to sign in, if they press continue it signs them out properly however if they don't press continue or they close the app they are unable to sign back in. [UserAlreadyAuthenticatedException: There is already a signed in user.]

         

### Expected behavior

I would prefer no prompt at all when signing out but at least changing it to "sign out" instead of "sign in" would be ok.

Is this possible without having to manually handle oauth?

### Reproduction steps

sign in with 

```
await signInWithRedirect({
  provider: "Apple",
});
```
then once signed in, try to sign out with 

`await signOut()`

the user is prompted to sign in again. If they press continue it properly signs them out. If they don't then they aren't signed out and  they are locked from signing in with other accounts until they do.  I uploaded a photo of the prompt. 

### amplifyconfig

```
  oauth: {
    domain: "appname-dev.auth.us-east-2.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "appname://authresponse",
    redirectSignOut: "appname://SignIn",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_AND_IDENTITY_POOLS",
  aws_cognito_username_attributes: ["EMAIL", "PHONE_NUMBER"],
  aws_cognito_social_providers: ["APPLE"],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: "OPTIONAL",
  aws_cognito_mfa_types: ["SMS", "TOTP"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["PHONE_NUMBER"],
```

### Mobile Device

iphone 12 

### Additional information and screenshots
below is the prompt shown for signing out which is confusing to the user
![image0 (1)](https://github.com/aws-amplify/amplify-js/assets/52197930/3c9f9479-3836-4b87-bf6b-522d89bce14d)

**Comment by ryanSoftwareEngineer** [comment] 2024-03-17 01:53
Oh i found the solution! on IOS you can these options: i didn't notice this in any documentation but I saw it by looking into the types!. 

```
   await signInWithRedirect({
                provider: "Apple",
                options: {
                  preferPrivateSession: true,
                },
              });
```

**Comment by ryanSoftwareEngineer** [comment] 2024-04-11 14:35
https://docs.amplify.aws/javascript/build-a-backend/auth/auth-migration-guide/#authfederatedsignin

`Auth.federatedSignIn has become signInWithRedirect in v6, `

**Comment by asp3** [comment] 2024-04-25 16:43
> Oh i found the solution! on IOS you can these options: i didn't notice this in any documentation but I saw it by looking into the types!.
> 
> ```
>    await signInWithRedirect({
>                 provider: "Apple",
>                 options: {
>                   preferPrivateSession: true,
>                 },
>               });
> ```

This should really be in the docs somewhere. I see it in the [swift](https://docs.amplify.aws/swift/build-a-backend/auth/sign-in-with-web-ui/) docs, but not in the React Native ones. @nadetastic

**Comment by hcac10** [comment] 2024-04-30 00:30
> options: {
>                   preferPrivateSession: true,
>                 },

+1

**Comment by hcac10** [comment] 2024-04-30 00:31
> > Oh i found the solution! on IOS you can these options: i didn't notice this in any documentation but I saw it by looking into the types!.
> > ```
> >    await signInWithRedirect({
> >                 provider: "Apple",
> >                 options: {
> >                   preferPrivateSession: true,
> >                 },
> >               });
> > ```
> 
> This should really be in the docs somewhere. I see it in the [swift](https://docs.amplify.aws/swift/build-a-backend/auth/sign-in-with-web-ui/) docs, but not in the React Native ones. @nadetastic

+1 to adding to react native docs

**Comment by gbyesiltas** [comment] 2024-07-09 13:20
> Oh i found the solution! on IOS you can these options: i didn't notice this in any documentation but I saw it by looking into the types!.
> 
> ```
>    await signInWithRedirect({
>                 provider: "Apple",
>                 options: {
>                   preferPrivateSession: true,
>                 },
>               });
> ```

This does fix this issue indeed, but I don't see why signing in with a non-private session would end-up causing a "sign-in" prompt while signing out? I feel like this is still a bug if I'm not missing anything

**Comment by wootencl** [comment] 2024-07-14 15:08
Have to agree with @gbyesiltas. This seems like a workaround. Why the prompt is required on sign out is the core problem. @ryanSoftwareEngineer able to re open this issue so it is back on the Amplify team's radar?

**Comment by ryanSoftwareEngineer** [comment] 2024-08-09 05:44
@gbyesiltas  Yes I agree. I started using google sign in on the IOS devices to add more options for users to sign in/up with. 

This behavior is a bad UX. When you have a private session for other providers the user has to type in your password and email again even if they are signed in on their browser. 

An update on sign out would be needed for a production quality experience

**Comment by cwomack** [comment] 2024-08-09 18:42
@ryanSoftwareEngineer and @gbyesiltas, we actually have this feature request to be able to customize the pop up behavior when calling `signInWithRedirect` in iOS (using React Native) being tracked in #3410. I've updated the title of that feature request to be more clear as well.

We'll close this issue out as a duplicate of that feature request, but let feel free to reply back if you feel there's a strong reason to keep this one open. Thank you!

**Closed by cwomack** 2024-08-09 18:42 UTC
Labels: question, documentation, Auth
