### ISSUE TITLE
Valid authorization header not provided with additional Cognito setup

### ISSUE THREAD

**Issue by TomBrouwer** [aws-amplify/amplify-js#5846] opened 2020-05-20 14:46 UTC
**Describe the bug**
When I set authorization to Cognito for a custom mutation. And I do a request to the mutation, I get a 401 "Valid authorization header not provided." error.

**To Reproduce**

1. Set up Amplify project with `AWS_IAM` as default auth mode.
2. Add `AMAZON_COGNITO_USER_POOLS` as additional auth mode.
3. Create a function to add `no_user` group to the token, link it to "Pre Token Generation Lambda Trigger".
4. Create a Lambda function with `add function`.
5. Create a custom mutation which calling the function:
```
type Mutation {
  setUp(
      businessName: String!
      businessAddress: String!
      creditCardLinkNumber: String!
      ): String
      @function(name: "setUpAccount-${env}")
      @auth(rules: [{ allow: groups, groups: ["no_user"] }])
}
```
6. Copy `aws-export.js` to your frontend project (other repoistory with only amplify hosting enabled).
7. After import `aws-export.js` set `aws_appsync_authenticationType` to `"AMAZON_COGNITO_USER_POOLS"` before using the imported object in the configure method:
```
import aws_exports from "./aws-exports";
aws_exports.aws_appsync_authenticationType = "AMAZON_COGNITO_USER_POOLS";

Amplify.configure(aws_exports);
```
8. Now use the generated mutation to do the request with an authenticated user with group `no_user`. You will get the `UnauthorizedException` with message: `Valid authorization header not provided.`.

**Expected behavior**
The lamda function is used to handle the request. The user is authenticated and authorized.

**Code Snippet**
I did also write this down in discussions, cause I think I make a mistake and it is not a bug. There is more information, also about generated files. But no response there. And I need to have it working to go further with the project.
https://github.com/aws-amplify/amplify-js/discussions/5823

**Screenshots**
I do not have screenshots.
Amplify tells me (output in js from API.graphql method):
```
{ "data": {}, "errors": [ { "message": "Request failed with status code 401" } ] }
```

Response of request tells me:
```
{
  "errors" : [ {
    "errorType" : "UnauthorizedException",
    "message" : "Valid authorization header not provided."
  } ]
}
```

Really nice project! And thanks to all contributers, I hope to help you soon with contribution! First learn about it. Thanks!

**Comment by rogerheykoop** [comment] 2020-05-21 07:00
I am experiencing exactly the same error. I have a project that has both API_KEY and AWS_COGNITO_USERPOOLS methods. Even when authenticated I am not able to update a record using cognito.

**Comment by FilipPyrek** [comment] 2020-05-21 14:19
I have probably experienced similar issue. Can you please try importing `API` and `Auth` and using it somewhere (for example `console.log`)?

For example like this:

```typescript
import aws_exports from "./aws-exports";
import { Amplify, API, Auth } from 'aws-amplify'
console.log(API, Auth) // temp fix
aws_exports.aws_appsync_authenticationType = "AMAZON_COGNITO_USER_POOLS";

Amplify.configure(aws_exports);
```

<hr/>

Because [`Amplify.configure`](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Amplify.ts#L46-L56) passes the configuration object only to "[registered](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Amplify.ts#L28-L44)" components.

And these components are [registering](https://github.com/aws-amplify/amplify-js/blob/master/packages/api-graphql/src/GraphQLAPI.ts#L55) when they are constructed. And they are [constructed only when imported](https://github.com/aws-amplify/amplify-js/blob/master/packages/api-graphql/src/GraphQLAPI.ts#L373).

So what happens, is that when you call `Amplify.configure`, Amplify passes the configuration to it's components which are already registered. But because `API` and `Auth` have not been imported yet, they are not registered in Amplify yet. So Amplify sends the configuration to no components and after that `Auth` and `API` registeres.

**Comment by FilipPyrek** [comment] 2020-05-21 14:52
But the issue I mentioned seems to be fixed by https://github.com/aws-amplify/amplify-js/pull/5681

**Comment by elorzafe** [comment] 2020-05-21 19:33
@TomBrouwer @FilipPyrek @rogerheykoop 

`API.graphql` sends the access token for authorization. That token contains the  cognito groups where that user is member. In that scenario the user should be part of the group before signing in (for the jwt to contain that information). Amplify CLI provides mechanisms to automatically or programmatically add users to groups, for more info you can check [here](https://docs.amplify.aws/cli/auth/groups).

Cognito Pre Token Generation Lambda Trigger, changes the id token not the access token. That said if you want to use id token on your app instead of the access token, you will need to do this.

```javascript
Amplify.configure({
    API: {
        aws_appsync_graphqlEndpoint: 'https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql',
        aws_appsync_region: 'us-east-1',
        aws_appsync_authenticationType: 'NONE',
        graphql_headers: async () => ({
            'Authorization': (await Auth.currentSession()).getIdToken().getJwtToken()
        })
    }
});
```

**Comment by TomBrouwer** [comment] 2020-05-22 08:30
All thanks for your comments.

@elorzafe
About the ID token, I know, it is the most common search result for problems with auth. I tried that but it didn't change anything.

Because I really wanted to continue with the project, I did the following:
I removed everything and started a new Amplify project. As standard method Cognito. As additional IAM.

It is working fine now. I am new in Amplify JS/CLI and learning. I think I did set the IAM as standard to avoid a circulair dependencies error (Cognito and pre token trigger (request DB)). I found an answer for this; https://github.com/aws-amplify/amplify-cli/issues/1874#issuecomment-606073890 but I don't know what to do exactly. I have to learn further.

But still it was a stange problem, and I didn't found a answer for it. @rogerheykoop experiencing the same. I think it's worth checking it out.

**Comment by elorzafe** [comment] 2020-05-22 19:18
@TomBrouwer what I would do on the case you mention on the description of the issue is adding a  user to a group as is mention on the [add user to a group docs](https://docs.amplify.aws/cli/usage/lambda-triggers#add-user-to-group). That will allow you to use the API with Cognito Authorization for signed in users. 

In case you want to enable unauthenticated access to the API you will need to use IAM Authorization for guest users. This is explained on the [public authorization docs](https://docs.amplify.aws/cli/graphql-transformer/directives#public-authorization)

**Closed** 2020-05-30 06:02 UTC
Labels: Auth, pending-close-response-required, question
