### ISSUE TITLE
Getting "message": "The incoming token has expired" when I am using Auth.currentSession();

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5934] opened 2020-05-28 14:46 UTC
I am using Auth.currentSession() to get the token. But i am facing the incoming token has expired issue. 

```
export async function get (endpoint: string, data?) {
    const currentSession = await Auth.currentSession();
    const providerId = currentSession.getIdToken().payload.sub;
    const identityJwt = currentSession.getIdToken().getJwtToken();
    return GET(endpoint, data, identityJwt, providerId);
}
   
```

**Comment by mauerbac** [comment] 2020-07-09 15:26
@nihp - are you still experiencing this issue? Curious if the above PR helps?

**Comment by nihp** [comment] 2020-07-09 16:50
Yes, occasionally facing this issue

**Comment by mauerbac** [comment] 2020-07-09 20:47
@nihp - Did you see the PR ? Does that help

**Comment by nihp** [comment] 2020-07-10 03:39
> Did you see the PR ? Does that help

Which PR?

**Comment by sammartinez** [comment] 2020-09-16 21:44
Apologizes on circling back until now, are you still experiencing this issue on the latest version of Amplify? Also, please provide us your `package.json` so we can validate against your use case. Thanks ahead of time

**Comment by nihp** [comment] 2020-12-17 07:41
I am facing the above still any solution

**Comment by mauerbac** [comment] 2020-12-17 17:07
Let me re-open this

**Comment by andre-rabold-tfs** [comment] 2021-01-26 19:27
Running into the same problem right now. I'm using an Axios interceptor to set the token in every request as follows:
```ts
  // Add authentication header to every request
  client.interceptors.request.use(async request => {
    const session = await Auth.currentSession()
    const token = session.getIdToken().getJwtToken()
    request.headers.Authorization = `Bearer ${token}`
    return request
  })
```

It's noteworthy that here the **ID token** is used, not the access token! This is due to how the backend works over which I don't have any control at this time.

The assumption is that the token would automatically refresh but it doesn't seem to be the case. I get the `The incoming token has expired` error rather frequently. 

```
aws-amplify@3.3.14
```


I wonder if there's a workaround such as manually refreshing the tokens periodically? Others seem to have run into this as well, but I haven't found any solution yet.

**Comment by elorzafe** [comment] 2021-02-10 17:52
@andre-rabold-tfs @nihp 
Tokens should get refreshed automatically every time they are expired. What are your userpool app client settings in terms of token longevity do you have?

Do you have the device with the clock skewed? The client has a mechanism to detect that but i am curious if there was a regression around that.

**Comment by iartemiev** [comment] 2021-04-12 18:04
@nihp,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:04 UTC
Labels: Auth, React Native, pending-close-response-required
