### ISSUE TITLE
Analytics Record [Unhandled promise rejection: Error: No credentials, applicationId or region

### ISSUE THREAD

**Issue by evanlarkin10** [aws-amplify/amplify-js#6145] opened 2020-06-23 12:08 UTC
**Describe the bug**
Analytics record function throws error: 
[Unhandled promise rejection: Error: No credentials, applicationId or region]
- node_modules/@aws-amplify/analytics/lib-esm/Providers/AWSPinpointProvider.js:173:41 in __generator$argument_1
......
.....

**Expected behavior**
Analytics logs record event without error.

**Code Snippet**
Analytics.record({name: 'profileVisit',attributes: { id: marker.id }});

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which resources do you have configured?
Auth, Storage (S3) and Analytics are configured. 
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "dinnerbellxxxxxx-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aws_mobile_analytics_app_region": "us-east-1"
};
 
Package.json
"@aws-amplify/analytics": "~3.2.1",
"@aws-amplify/api": "~3.1.9",
"@aws-amplify/auth": "~3.2.5",
"@aws-amplify/core": "~3.2.5",
"@aws-amplify/storage": "~3.2.0",

Using expo SDK 37, which uses react native 0.61

At the time of logging the analytics event, the user is authenticated with Auth.signIn().

**Comment by elliottower** [comment] 2020-06-29 19:24
I have gotten this same issue with trying to use analytics with auth, tried solutions from this thread (https://github.com/aws-amplify/amplify-js/issues/3484) and disabling analytics fixes it, but I would like to find a real fix.

**Comment by jeffsteinmetz** [comment] 2020-08-28 22:17
I can confirm a similar issue still.  It is a plain vanilla react-native expo application, using the exact steps prior to, and up to this step in the getting started guide:
https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native
relates to
https://github.com/aws-amplify/amplify-js/issues/3484
package.json snippet:
```
    "aws-amplify": "^3.0.24",
    "aws-amplify-react-native": "^4.2.5",
    "expo": "~38.0.8",
```

**Comment by jpignata** [comment] 2020-11-27 15:36
@joebernard is seeing this also on `3.3.11`.

**Comment by sammartinez** [comment] 2020-11-27 16:36
Hopped on a call with @Joe8Bit and @jpignata, @Joe8Bit is checking if pinning specific versions of the analytics package will resolve his issue.

**Comment by danielesalvatore** [comment] 2021-01-09 15:37
+1

**Comment by sammartinez** [comment] 2021-02-09 22:49
Resolving as this issue as a duplicate of the above related issue.

**Closed** 2021-02-09 22:49 UTC
Labels: Analytics, React Native, duplicate
