### ISSUE TITLE
Amplify with ReactJS and API "No Access-Control-Allow-Origin header" response.

### ISSUE THREAD

**Issue by gopal-abbineni** [aws-amplify/amplify-js#7749] opened 2021-02-15 15:15 UTC
> Hi @SamnnyWong
> 
> How was your api created? when created via the amplify cli, the API GW endpoint includes handling of preflight requests for CORS
> 
> If the amplify cli wasn't used, you might need to follow manual steps to handle it, [this](https://enable-cors.org/server_awsapigateway.html) might help

<img width="1062" alt="Screenshot 2021-02-15 at 8 41 56 PM" src="https://user-images.githubusercontent.com/12975073/107963563-58482000-6fce-11eb-837e-35d85df1656c.png">
 Created Using Amplify CLI but still facing the issue. amplify version 4.43.0. Could please help me in resolving the issue

_Originally posted by @gopal-abbineni in https://github.com/aws-amplify/amplify-js/issues/6357#issuecomment-779284697_

**Comment by gopal-abbineni** [comment] 2021-02-15 16:30
Tried removing the restrictions on the API, then it is working fine? Am I missing something when I am access with authenticated users? I am passing the authorization header with JWT Token

**Comment by amhinson** [comment] 2021-02-15 17:55
Hey @gopal-abbineni 👋  Thanks for opening this issue. Would you be able to provide some reproduction steps for the issue that you are facing? That will help us greatly in trying to debug the issue you're having.

**Comment by gopal-abbineni** [comment] 2021-02-16 03:48
Thanks for the response @amhinson, Issue got resolved by creating the custom authorizer in api gateway manually. But it needs to be automated this workflow. Seems like this was added as a todo list for amplify cli

https://github.com/aws-amplify/amplify-cli/issues/5716

**Comment by amhinson** [comment] 2021-02-16 18:41
Ah ok, thanks for the update! I'll close this issue, since it appears to mostly be related to the CLI.

**Closed by amhinson** 2021-02-16 18:41 UTC
Labels: API
