### ISSUE TITLE
Signing up to aws-samples/aws-mobile-react-native-starter does not log in user too.

### ISSUE THREAD

**Issue by degaray** [aws-amplify/amplify-js#898] opened 2018-05-23 22:22 UTC
Do you want to request a feature or report a bug?
Report a bug

What is the current behavior?
Not logged in after signing up in an app created with aws-samples/aws-mobile-react-native-starter. The user has to manually enter the user and password and re-confirm the SMS being charged twice.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Just create a plain version of aws-samples/aws-mobile-react-native-starter, and it will happen. 

What is the expected behavior?
The app should log in automatically after signing up.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
I am using iOS.

**Comment by sammartinez** [comment] 2019-10-08 21:05
@degaray Are you still experiencing this issue with later updates to this starter? In testing the [starter](https://github.com/aws-samples/aws-mobile-react-native-starter) I was unable to reproduce this issue. If you are still using this starter, please report back if not, please go ahead and close this issue.

**Closed** 2019-10-15 21:08 UTC
Labels: pending-close-response-required, starter:react-native
