### ISSUE TITLE
Support for email-only SignUp through withAuthenticator

### ISSUE THREAD

**Issue by rlmartin** [aws-amplify/amplify-js#104] opened 2017-12-27 14:57 UTC
I'd like to be able to expose a SignUp form (and corresponding ConfirmSignUp) that shows only email address, not username. Unfortunately the Mobile Hub project creation doesn't fully support this (it creates a user pool with a type that still requires a username), but we could SHA-2 hash the email address in place of the username and then rely on the "alternative sign in" support for email address in the SignIn form.

The same support goes for phone number in place of email address.

The withAuthenticator HOC could take a `props` argument with a `usernameTypes` property that would be an array of enums (values: `email`, `phoneNumber`, `username`); this could then be used by all applicable auth components (SignUp, ConfirmSignUp, SignIn, ForgotPassword) for both display and data processing.

I'm immediately focused on the `aws-amplify-react-native` project and could take a pass at implementing it - but support in `aws-amplify-react` project would be necessary too.

**Comment by mlabieniec** [comment] 2017-12-27 17:12
@rlmartin thanks for the feedback. We are working on signup with custom attributes, it's in review and pending a few changes in PR #79

**Comment by rlmartin** [comment] 2017-12-27 17:20
@mlabieniec thanks for pointing out that other PR. I had seen it, but it didn't eliminate the requirement of username in the SignUp component so I created this issue. However I can see where you'd like to get that PR merged first, then consider this enhancement. Tell me if I can lend a hand.

**Comment by mlabieniec** [comment] 2018-01-26 23:36
@rlmartin Just fyi, we are working on abstracting out the authentication and higher level logic into the aws-amplify core package. This way, react and react-native can share all basic functionality i.e. persistent auth, federation, session management etc. So you would basically work with react-native the same way as aws-amplify-react. We are shooting to finish it this sprint, but it may end up in the following release at this point. Once that's out would like to get your feedback and contributions on that (in aws-amplify core).

**Comment by rlmartin** [comment] 2018-01-27 22:49
👍

**Comment by dillonbailey** [comment] 2018-02-19 06:42
@rlmartin is there presently a way to use amplify and allow signup with email as username?

**Comment by ldgarcia** [comment] 2018-02-19 13:29
@dillonbailey yes, but you need to write your own custom SignUp component.

Modify `handleSignup` to use something like this:

````javascript
// const attributes = { ... }
Auth.signUp({
  username: email,
  password: password,
  attributes
})
  .then(data => {
  this.changeState('confirmSignUp', email)
})
  .catch(err => {
  this.error(err)
})
````

**Comment by rlmartin** [comment] 2018-02-19 17:36
@dillonbailey I actually took a different approach. Whenever I set email, I set username to a hash of the email. Unfortunately the change is in a private repo so I can't give you a link to the commit, but it looks roughly like this:

Overridden `SignUp.js`:
```js
import React from 'react';
import { I18n } from 'aws-amplify';
import { Email, ErrorRow, Header, LinkCell, Password, SignUp as CoreSignUp } from 'aws-amplify-react-native';
import { Button, View } from 'react-native';
import sha from 'sha.js';

const Footer = (props) => {
  const { theme, onStateChange } = props;
  return (
    <View style={theme.sectionFooter}>
      <LinkCell theme={theme} onPress={() => onStateChange('confirmSignUp')}>
        {I18n.get('Confirm a Code')}
      </LinkCell>
      <LinkCell theme={theme} onPress={() => onStateChange('signIn')}>
        {I18n.get('Sign In')}
      </LinkCell>
    </View>
  )
}

export default class SignUp extends CoreSignUp {
  showComponent(theme) {
    return (
      <View style={theme.section}>
        <Header theme={theme}>{I18n.get('Sign Up')}</Header>
        <View style={theme.sectionBody}>
          <Email
            theme={theme}
            onChangeText={(text) => this.setState({ email: text, username: new sha.sha256().update(text).digest('hex') })}
          />
          <Password
            theme={theme}
            onChangeText={(text) => this.setState({ password: text })}
          />
          <Button
            title={I18n.get('Sign Up')}
            onPress={this.signUp}
            disabled={!this.state.username || !this.state.password}
          />
        </View>
        <Footer theme={theme} onStateChange={this.changeState} />
        <ErrorRow theme={theme}>{this.state.error}</ErrorRow>
      </View>
    );
  }
}
```

Overridden `ConfirmSignup.js`:
```js
import React from 'react';
import { I18n } from 'aws-amplify';
import { ConfirmationCode, ConfirmSignUp as CoreConfirmSignUp, Email, ErrorRow, Header, LinkCell } from 'aws-amplify-react-native';
import { Button, View } from 'react-native';
import sha from 'sha.js';

const Footer = (props) => {
  const { theme, onStateChange } = props;
  return (
    <View style={theme.sectionFooter}>
      <LinkCell theme={theme} onPress={() => onStateChange('signIn')}>
        {I18n.get('Back to Sign In')}
      </LinkCell>
    </View>
  )
}

export default class ConfirmSignUp extends CoreConfirmSignUp {
  showComponent(theme) {
    return (
      <View style={theme.section}>
        <Header theme={theme}>{I18n.get('Confirm Sign Up')}</Header>
        <View style={theme.sectionBody}>
          <Email
            theme={theme}
            value={this.state.email}
            onChangeText={(text) => this.setState({ username: new sha.sha256().update(text).digest('hex') })}
          />
          <ConfirmationCode
            theme={theme}
            onChangeText={(text) => this.setState({ code: text })}
          />
          <Button
            title={I18n.get('Confirm')}
            onPress={this.confirm}
            disabled={!this.state.username || !this.state.code}
          />
          <Button
            title={I18n.get('Resend a Code')}
            onPress={this.resend}
            disabled={!this.state.username}
          />
        </View>
        <Footer theme={theme} onStateChange={this.changeState} />
        <ErrorRow theme={theme}>{this.state.error}</ErrorRow>
      </View>
    );
  }
}
```

Then you can pass in those overridden components, along with the default components for the other screens, into the `withAuthenticator` HOC like in the example here: https://github.com/aws/aws-amplify#3-override-default-authentication-screens.

If you were to diff those overridden components against the default ones, the only real differences are the lines with `sha` in them (specifically the `onChangeText` prop on each `<Email/>` component).

**Comment by dillonbailey** [comment] 2018-02-19 21:00
@rlmartin @ldgarcia - thanks for the options guys! 👍 

The only issue I'm running into now, and this may be related to https://github.com/aws/awsmobile-cli - but setting `email` as an alias doesn't yet seem to be an option if you are using Mobile Hub.

Are either of you guys using Mobile Hub and having any success with this?

**Comment by rlmartin** [comment] 2018-02-19 21:06
I've been using Mobile Hub, but not the cli. I've been able to set it up without a problem to allow for login using either email or username.

**Comment by dillonbailey** [comment] 2018-02-19 21:11
Awesome - thanks @rlmartin - on further reading it looks like setting the username with the UUID is the key to making this work!

**Comment by ldgarcia** [comment] 2018-02-21 19:21
@dillonbailey this is my user pool configuration:

<img width="1020" alt="screen shot 2018-02-21 at 12 07 46 pm" src="https://user-images.githubusercontent.com/1865386/36500478-0022c080-170a-11e8-895e-1fc3ddc150fb.png">

With the approach I mentioned, you don't need to generate the UUID youself, Cognito does it (the `sub` attribute).

**Comment by dillonbailey** [comment] 2018-02-22 04:50
@ldgarcia interesting - whether I go via CLI or GUI, it ends up force checking the Username radio button...*opening a case with AWS*

**Comment by andythedandyone** [comment] 2018-02-23 07:23
I'm facing a similar issue, User management created by Mobile Hub won't allow changes on Cognito attributes. It won't allow sign in with email or assign an email to username on signup.
Disappointing so far :/

**Comment by dillonbailey** [comment] 2018-02-23 07:48
@andythedandyone I’ve got an open case with support on this, will let you know how I get on.

**Comment by elorzafe** [comment] 2018-02-24 02:49
Hi @rlmartin  @dillonbailey  @ldgarcia  @andythedandyone  thanks for your feedback!
On awsmobile-cli you can do the following.

1) if you don't have the feature enabled run: 
```awsmobile user-signin enable -p```
and then: 
1.1) 
-Go to advance settings
-Cognito UserPools
-Select how are users are going to login: Email
-Password length
-Password requirements

finally
```awsmobile push```

2) if you have enabled user-signin and cognito is the only signin method run:
```awsmobile user-signin disable``` 
```awsmobile push```(this will delete your UserPool)
and then repeat steps 1)

3) if you have enabled user-signin and cognito is not the only signin method
```awsmobile user-signin configure```. Select cognito UserPools, then disable it, 
```awsmobile push``` (this will delete your UserPool)
```awsmobile user-signin configure```. 
then repeat from step 1.1)

Please let me know if you have any issues with this

**Comment by andythedandyone** [comment] 2018-02-24 03:18
@elorzafe I did that when I integrated cognito to mobile hub. I chose to login by email, pwd requirements/length. There is a print screen of what I get with this setup I mentioned here.(see below)
However, I still get stuck at the things I mentioned above. I will give it another try thru the cli instead the web interface MH.
But why not allow to change attributes for the user pool?
The solution I found for the meantime was to follow one of the posts above and hash the email to username.

```  
    signUp = () => {
        sha256(this.state.email.toLowerCase()).then(data => {
            Auth.signUp({
                username: data,
                password: this.state.password,
                attributes: {
                    email: this.state.email.toLowerCase(),
                    phone_number: 
                }
            }).then(data => {
                this.props.navigation.navigate('Login');
            }).catch(err => console.log('errors sign up  ', err));
        })
    }
```

and login

```    
    signIn = () => {
        sha256(this.state.email.toLowerCase()).then(data => {
            Auth.signIn(data, this.state.password).then(data => {
                Keyboard.dismiss();
                setTimeout(() => {
                    this.props.navigation.navigate('TopBar');
                }, 2000);
            }).catch(err => console.log('error was there => ', err))
        }).catch(err => console.log('could not hash ', err));
    }
```
![image](https://user-images.githubusercontent.com/20182536/36625121-6573b26c-18e7-11e8-8fc9-860b0163bbfd.png)

**Comment by mwarger** [comment] 2018-03-07 22:00
@dillonbailey I'm facing the same issue wherein Cognito isn't letting me select the email address as username.  Any update from support?

**Comment by dillonbailey** [comment] 2018-03-07 22:07
@mwarger feedback from support was the following:

```
Thank you for the information and feedback. I have read through the provided resources and tried out a few different options. At the moment, the ability to make changes to the standard attributes for a Cognito User Pool once it has been created is not available. As a result of this, you will not be able to have Mobile Hub create a user pool and make the subsequent changes in order to provide for the described use case.

I do see though that a feature request for this functionality has been raised already and I have added your case as an additional request for this feature. I do not have an ETA on the delivery of this feature. I will suggest to keep an eye on https://aws.amazon.com/new/ for information on new features and capabilities added.

As a workaround I can suggest 2 possible scenarios. The first and most straightforward is to create the User Pool manually or via Cloud Formation [AWS::Cognito::UserPool:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html] and not with Mobile Hub. All the code still needs to be implemented within the application to deal with Cognito as usual even with creating a pool with Mobile Hub. If it has, remove the pool from the Mobile Hub configuration and replace the existing required references within the application with the new pool information.

One could possibly consider making use of another Identity Provider via SAML 2.0 and federate identities with the Mobile Hub created user pool. This in turn will allow full control on what information a user can use for registration and login but will require further work as far as the Identity Provider is concerned. Authentication will take place against the Identity Provider and not via the User Pool which might defeat the purpose. See https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html for full description on implementing this with Cognito User Pools.
```

**Comment by chrisehlee** [comment] 2018-04-14 10:48
@mlabieniec you're doing an awesome job on following this up. However, what's the ETA for 0.4 though?

**Comment by wzup** [comment] 2018-06-20 14:29
@ldgarcia 

How can it be that you use **email** in place of **username**? Can you use **integers** where system requires **string** types? You can't! Then why do you pass one type in place of the other?
https://github.com/aws/aws-amplify/issues/104#issuecomment-366693354

```
{
    username: email
}

// Your example 
Auth.signUp({
  username: email,
  password: password,
  attributes
})
```

**Comment by wzup** [comment] 2018-06-20 14:37
Error still exists

https://github.com/aws/aws-amplify/issues/1063

```javascript
Auth.signUp( {email, password, attributes: {
    foo: 'bar'
}})
    .then( data => {
    } )
    .catch( err => {
        // `Username cannot be empty` // Why?
    } );
```

**Comment by ldgarcia** [comment] 2018-07-12 22:51
@wzup You can use email as an username alias... BTW, your analogy makes no sense in this case.

Relevant documentation: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings-option-2

**Comment by mlabieniec** [comment] 2018-07-19 17:20
we are working on a new tracking system now that we've migrated to the new org. We are working on grooming all these and getting them assigned to realistic milestones. Will get these updated soon.

**Comment by angineering** [comment] 2018-10-23 16:54
Any updates on this? Would be useful to be able to create a user pool with email.

**Comment by uclaeamsavino** [comment] 2018-10-24 16:51
> Error still exists
> 
> #1063
> 
> ```js
> Auth.signUp( {email, password, attributes: {
>     foo: 'bar'
> }})
>     .then( data => {
>     } )
>     .catch( err => {
>         // `Username cannot be empty` // Why?
>     } );
> ```

This works for me:
```
    const signUpData = {
      username: data.get('email'),
      password: data.get('password'),
    };

    try {
      const user = await Auth.signUp(signUpData);
```

**Comment by uclaeamsavino** [comment] 2018-10-24 16:55
I can even sign in through the client-side component generated when using the withAuthenticator HOC. But it seems that the user still has to enter email twice. If we could just hide one of those fields it would be perfect. 

![image](https://user-images.githubusercontent.com/43759901/47447643-dd122e80-d772-11e8-87cc-20c2f58e51a9.png)

**Comment by andreupifarre** [comment] 2018-11-25 23:18
Any updates on this? I am having the same issue, I don't want to show the username field on my amplify signup form.

**Comment by rjbaker** [comment] 2018-12-04 12:50
+1 This is fairly common use case and requires a comprehensive workaround instead of a simple prop to configure the component without the username field.

**Comment by lotjuh** [comment] 2018-12-16 15:09
+1 Facing the same issue. I want the username to be automatically set to the user's email address. Don't want to need the user to fill out their email twice...

**Comment by mapkbalaji** [comment] 2019-02-13 10:12
> @dillonbailey this is my user pool configuration:
> 
> <img alt="screen shot 2018-02-21 at 12 07 46 pm" width="1020" src="https://user-images.githubusercontent.com/1865386/36500478-0022c080-170a-11e8-895e-1fc3ddc150fb.png">
> 
> With the approach I mentioned, you don't need to generate the UUID yourself, Cognito does it (stores it in the `sub` attribute).

How do you make this configuration using cli?

**Comment by askpatrickw** [comment] 2019-02-19 23:46
> > @dillonbailey this is my user pool configuration:
> > <img alt="screen shot 2018-02-21 at 12 07 46 pm" width="1020" src="https://user-images.githubusercontent.com/1865386/36500478-0022c080-170a-11e8-895e-1fc3ddc150fb.png">
> > With the approach I mentioned, you don't need to generate the UUID yourself, Cognito does it (stores it in the `sub` attribute).
> 
> How do you make this configuration using cli?

You can see how to do it here: https://github.com/aws-amplify/amplify-cli/issues/102#issuecomment-432730047

It does require manual config file editing before you push your config.

**Comment by fcwheeler** [comment] 2019-03-03 20:26
I am using the SignUpConfig prop for Authenticator to hide the username and phone_number fields. 
```
<Authenticator  signUpConfig={{ hiddenDefaults:['username','phone_number'],signUpFields: [{
            label:"Email",
            key:"email",
            required: true,
            displayOrder: 1,
            type: 'string',
            custom: false
          },        
          {
            label:"Password",
            key:"password",
            required: true,
            displayOrder: 1,
            type: 'password',
            custom: false
          }]}
            
          }>
```

Maybe this is a recent enhancement, or i am not understanding the question

**Comment by undsoft** [comment] 2019-03-22 14:50
@fcwheeler 
Your config gives me a validation error "Username is required" or something like that.

This works for me:
```
{
  hideAllDefaults: true,
  signUpFields: [
    {
      label:"Email",
      key:"username",
      required: true,
      displayOrder: 1,
      type: 'email',
      custom: false
    },
    {
      label:"Password",
      key:"password",
      required: true,
      displayOrder: 2,
      type: 'password',
      custom: false
    }
  ]
}

```

The login will still say 'username' though.

**Comment by navraj007in** [comment] 2019-04-11 14:34
Hi,
I am using amplify to create a sign up form. however i need a custom field called user type which will have 2 possible values(Employer/Contractor). This should be input through radio button and its essential to capture at the time of sign up. I tried to look into signupFields options and type can have only 3 values as of now: string, number and date. is there a way to incorporate Fields like these?
even the gender field needs a radio button rather than a text field.

Would like to know if its already a feature or yet to be developed?

Thank you.

**Comment by uclaeagit** [comment] 2019-04-11 15:32
Can you make it a hidden field that resolves from the radio button selection using Javascript?

**Comment by jorgemarrero** [comment] 2019-05-14 15:23
Working with `withAuthenticator`.

```export default withAuthenticator(Main, {
  signUpConfig: {
    hiddenDefaults: ["username", "phone_number"],
    signUpFields: [
      {
        label: "Email",
        key: "email",
        required: true,
        displayOrder: 1,
        type: "string",
        custom: false
      },
      {
        label: "Password",
        key: "password",
        required: true,
        displayOrder: 1,
        type: "password",
        custom: false
      }
    ]
  }
});
```


You can find the docs here: https://aws-amplify.github.io/docs/js/react#signup-configuration

Probably a better explanation or link in https://aws-amplify.github.io/docs/js/authentication#using-withauthenticator-hoc may help a lot


_Thanks for the tip @fcwheeler_

**Comment by powerful23** [comment] 2019-05-20 22:07
Hi All, the feature is implemented in the beta version of amplify UIs:
```js
aws-amplify-react@beta
aws-amplify-react-native@beta
aws-amplify-angular@beta
aws-amplify-vue@beta
```

The docs is in: https://github.com/aws-amplify/docs/pull/622
Basically you can change the default sign in or sign up component by passing the `usernameAttributes` props in the `Authenticator`. For example, in React:
```js
import { Authenticator } from 'aws-amplify-react';

class App extends React.Component {
    //.....
    render() {
         return (
                <Authenticator usernameAttributes="email"/>
         );
    }
}
```

Welcome any feedback. Thanks.

**Comment by powerful23** [comment] 2019-05-20 22:49
Hi All, the feature is implemented in the beta version of amplify UIs:
```js
aws-amplify-react@beta
aws-amplify-react-native@beta
aws-amplify-angular@beta
aws-amplify-vue@beta
```

The docs is in: https://github.com/aws-amplify/docs/pull/622
Basically you can change the default sign in or sign up component by passing the `usernameAttributes` props in the `Authenticator`. For example, in React:
```js
import { Authenticator } from 'aws-amplify-react';

class App extends React.Component {
    //.....
    render() {
         return (
                <Authenticator usernameAttributes="email"/>
         );
    }
}
```

Welcome any feedback. Thanks.

**Comment by rtuin** [comment] 2019-07-30 18:35
This looks good 👍 I see it's in master now.

For those ending up here via search engines, here's the link to the docs: https://aws-amplify.github.io/docs/js/react#sign-upin-with-emailphone-number

This worked for me to get a sign up component with only email address + password fields:

```javascript
export default withAuthenticator(App, {
  usernameAttributes: 'email',
  signUpConfig: {
    hiddenDefaults: ['phone_number']
  }
});
```

**Comment by jpyne17** [comment] 2019-08-20 09:22
Unless I'm missing something email/phone as username still not supported for `Auth.signUp()`and `Auth.signIn()` methods while the user pool is set up that way.
I can sign up fine, but I think it needs the generated UUID username for the sign in.

Should I create a separate issue?

**Comment by plisitza** [comment] 2019-08-22 17:27
affecting me too. the fact that Cognito allows this but libraries do not is odd/wrong. this is a common use case and not everyone wants to use the stock components...

**Comment by haverchuck** [comment] 2019-08-22 18:37
@jpyne17 @plisitza  I believe that the use of email or phone number is supported with Auth.signIn.  This method accepts a parameter called 'usernameOrSignInOpts'.  If the usernameAttribute is set to 'email' (i.e. you are using an email address as the username), passing the email as this parameter should work (I just confirmed it).  If it is not working, please details the exact behavior you're experiencing.

**Comment by sammartinez** [comment] 2019-10-07 20:10
In looking at the original feature request, I am seeing that this is now complete. Resolving this feature request. @rlmartin Please let us know if something isnt complete. 

@jpyne17 @plisitza Please open up a separate issue with us if you are still experiencing issues after @haverchuck comment.

**Closed by sammartinez** 2019-10-07 20:10 UTC
Labels: Auth, feature-request

**Comment by nihp** [comment] 2020-03-17 11:59
I have enabled both Email and phone number.

But I only receiving the code in Phone number. I not get any acknowledgement or any code in my email? 

I need to know why the code not received in my mail?

**Comment by johnmesotech** [comment] 2020-03-21 06:18
> I have enabled both Email and phone number.
> 
> But I only receiving the code in Phone number. I not get any acknowledgement or any code in my email?
> 
> I need to know why the code not received in my mail?
It's a feature, not a bug. Ref:
https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html

**Comment by hutch120** [comment] 2020-03-22 11:11
Amplify is looking great, but some of these default settings boggle the mind.

A simple email and password login is the most common signup process in the world. No one wants to bother their users to have to enter some weird username (which is most likely their email anyway) or phone number, or any one of the 20 other weird fields (what on earth is zoneinfo?). Also, no one is going to put their phone number into a signup form for 99.99% or websites in the world.

I strongly suggest adding the following example to the doco to save almost everyone who wants to use this component to have to search this issue thread. (OR better yet, make it the default behaviour)

The code below was the only way I could get the react sign up component to display only email address and password fields. ( Thanks @rtuin )

```
export default withAuthenticator(App, {
  usernameAttributes: 'email',
  signUpConfig: {
    hiddenDefaults: ['phone_number']
  }
});
```

![image](https://user-images.githubusercontent.com/1034955/77247935-cfbfe300-6c89-11ea-9ce3-7a588192ad67.png)

**Comment by nihp** [comment] 2020-03-23 08:50
@johnmesotech Thanks.

I have another one clarification. Can you clarify? The error messages are retaining in all the screens if I revisit that screen after creating or it will shows an error with wrong input.
