### ISSUE TITLE
ClientMetadata not passing to Cognito Trigger, with `Auth.signIn({... , validationData: {foo: 'bar'}})`

### ISSUE THREAD

**Issue by obonyojimmy** [aws-amplify/amplify-js#6731] opened 2020-09-04 22:49 UTC
**Describe the bug**
ClientMetadata not passing to  Cognito Trigger, when using Amplify Custom Ui components and Auth.signIn()
 `Auth.signIn({... , validationData: {foo: 'bar'}})`, even with static preconfigured ClientMetadata, 
 `Auth.configure({  authenticationFlowType: 'CUSTOM_AUTH', clientMetadata: {foo: 'bar'}  })` or 
`Amplify.configure({ Auth: {  authenticationFlowType: 'CUSTOM_AUTH', clientMetadata: {foo: 'bar'} }  })` 

**To Reproduce**

*browser js code*

```
Auth.configure({ clientMetadata: {foo: 'bar'}  })
await Auth.signIn({ username: 'someuser', validationData: {xyz: 'abc'} })
```
*lambda trigger*

```
exports.handler = (event, ctx, callback) => {
  console.log(event)
}
```

**Expected behavior**

Expect to see log of `foo` , `xyz` ClientMetadata in lambda cloudwatch logs , this are missing.
 
**Additional context**
 Amplify versions

- "aws-amplify": "^3.1.1",
- "aws-amplify-react": "^4.2.2",

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

*browser_debug_log*

![Screenshot_20200905_014143 (1)](https://user-images.githubusercontent.com/14318239/92289484-4e979800-ef19-11ea-902d-cf48d0e2d105.png)

*cloudwatch log**

```
2020-09-04T22:19:05.727Z	****	INFO	{
  version: '1',
  region: 'us-west-2',
  userPoolId: '****',
  userName: '****',
  callerContext: {
    awsSdkVersion: 'aws-sdk-unknown-unknown',
    clientId: '****'
  },
  triggerSource: 'DefineAuthChallenge_Authentication',
  request: {
    userAttributes: {
      sub: '****',
      email_verified: 'true',
      'cognito:user_status': 'CONFIRMED',
      'cognito:email_alias': '****',
      given_name: '****',
      family_name: '****',
      email: '****'
    },
    session: [],
    userNotFound: false
  },
  response: { challengeName: null, issueTokens: null, failAuthentication: null }
}

```

**Comment by obonyojimmy** [comment] 2020-09-08 22:32
SO : https://stackoverflow.com/questions/62548852/aws-cognito-and-amplify-clientmetadata-not-sent-when-session-is-refreshed?noredirect=1#comment112752281_62548852

**Comment by JiboStore** [comment] 2020-10-08 09:03
Hi, any update on this?

`clientMetadata` is not received in lambda at all on second and subsequent call to `Auth.signIn`.. this is really a deal breaker for us.

I've been trying work arounds like calling signOut first, etc but to no avail..

**Comment by pr1ze** [comment] 2020-10-22 07:07
This really needs to be prioritized. This nearly caused our production users to be able to see each others data!!!

**Comment by hmelchander-indpro** [comment] 2020-10-26 12:38
@jordanranz Is it possible to get some help with this?

**Comment by sammartinez** [comment] 2020-11-11 23:19
@obonyojimmy Apologizes on the late response to this. Are you configuring the Lambda triggers via our Amplify CLI? I want to make sure this issue gets routed to the correct location so please let me know. Thanks ahead of time

**Comment by obonyojimmy** [comment] 2020-11-12 02:32
Hi @sammartinez , thanks for reply , the lambda triggers are not configured using Amplify Cli , but manaully from cognito console page.

> @obonyojimmy Apologizes on the late response to this. Are you configuring the Lambda triggers via our Amplify CLI? I want to make sure this issue gets routed to the correct location so please let me know. Thanks ahead of time

**Comment by pr1ze** [comment] 2020-11-12 02:41
@sammartinez i did configure via Amplify CLI - and im having the same problem.

**Comment by mkozjak** [comment] 2020-11-14 19:39
A huge deal breaker for us too. It's year 2020!!

**Comment by hmelchander-indpro** [comment] 2020-11-15 20:20
@sammartinez:

Please see my original SO question mentioned by @obonyojimmy: https://stackoverflow.com/questions/62548852/aws-cognito-and-amplify-clientmetadata-not-sent-when-session-is-refreshed

This is how it works in our current implementation: it is possible to set a `clientMetadata` object in the `Auth.signIn` request, like this:

```
Auth.signIn(auth.email, auth.password, {"metadataKey1": "metadataValue1"})
    .then(response => {
        // Sign in OK
    })
    .catch(error => {
        // Something went wrong
    });
```

In our manually configured lambda triggers, we can read this metadata from two trigger points: **Pre authentication** and **Pre Token Generation**. In the **Pre authentication** trigger, it can be read from `request.validationData`. In the **Pre Token Generation** trigger, it can be read from `request.clientMetadata`.

Problem 1: we see that during the `Auth.signIn` process, the Amplify library automatically does a session refresh where the clientMetadata object is not included. I have not found a way how to make sure it gets set.

Problem 2: when we do a manual session refresh, by calling `Auth.currentAuthenticatedUser()` and then doing a `user.refreshSession` call, it is possible to send a clientMetadata object but it is not possible to read in the *Pre Token Generation**.

What we expect: if it is possible to set a clientMetadata object during `Auth.signIn`, the same clientMetadata object should be sent with the automatic session refresh and it should also be possible to send the clientMetadata when manually refreshing the user session.

**Comment by nicolasheady** [comment] 2020-11-17 16:22
The [docs here](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#pre-authentication-and-pre-sign-up-lambda-triggers) also say you can pass validationData/clientMetadata to Auth.signUp, but that doesn't appear to be the case when looking at the[ function definitions.](https://github.com/aws-amplify/amplify-js/blob/a047ce73/packages/aws-amplify-react/src/Auth/SignUp.tsx#L205)

**Comment by jcowley** [comment] 2020-11-18 01:01
I've gotten the `validationData` to show up in `event.request`, but only in the migrate user lambda trigger. I have not been successful in passing `clientMetadata` to any lambda trigger.

This is pretty limiting, and I need it for several use cases as we migrate our users into Cognito.

It's not clear to me if this is a Cognito bug or an Amplify bug, at this point. Careful reading of the Cognito docs, along with some googling, seems to indicate that `clientMetaData` is never passed to the "Define Auth Challenge" trigger. But it _should_ be available in the "Create Auth Challenge" and "Verify Auth Challenge" triggers, but I've had no luck getting it to work with Amplify.

At this point, I'm considering abandoning Amplify and just using the aws-sdk. Not sure the benefits of Amplify outweigh the limitations.

**Comment by AlexMayleRdn** [comment] 2020-11-25 15:41
@jcowley I can see the web request to the Cognito endpoint does have clientMetadata defined, so I'm not sure whether the Cognito docs are just wrong or if it's a Cognito bug.

Either way, not being able to manipulate claims in the access token, and not having client metadata in the preTokenGeneration hook make Cognito useless for anything other than the most basic auth flows.

**Comment by mkozjak** [comment] 2020-11-25 15:44
+1. I decided to use Cognito only for authentication and lambdas for authorization. Works for us and we won't wait for quite a while to get this one fixed.

**Comment by sammartinez** [comment] 2020-11-30 18:18
Thanks for your feedback and patience on this issue. We have identified the issue and we are talking to the Amazon Cognito team internally about this. We will provide an update once we have one.

**Comment by hmelchander-indpro** [comment] 2020-11-30 18:31
@sammartinez, thanks for getting back to us on this issue. Do you have any idea when this may be resolved? We are in the progress of rewriting our authentication backend, but if this is resolved within a reasonable timeframe we will skip that rewrite.

The main thing for us is that the clientMetadata should be made available in all the available Cognito lambda triggers. It is also important that if the clientMetadata has been set during Auth.signIn in the js client, it should be set automatically if the Auth framework does an automatic refresh.

**Comment by artur-zsuravely** [comment] 2021-01-16 10:54
I have a working code snippet to pass data as parameter to the lambda function with Cognito Pre authentication trigger:
```
await Auth.signIn({
	username: username,
	password: password,
	validationData: {
		metaDataKey: "metaDataValue"
	}
});
```
You can fetch the passed data value from "event.request.validationData.metaDataKey" on the Lambda side (Node.js).

An example for email validation to check if email unconfirmed or not:
Client-side:
```
await Auth.signIn({
	username: username,
	password: password,
	validationData: {
		email: email
	}
});
```

Lambda function (Node.js):
```
var AWS = require('aws-sdk');

exports.handler = async (event, context, callback) => {
    console.log("Received event");
    console.log(event);
    var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({
        apiVersion: "2016-04-18",
        region: event.region
    });
    let params = {
        UserPoolId: event.userPoolId,
        AttributesToGet: ["email"],
        Filter: "email='"+event.request.validationData.email+"'"
    };

    try {
        let response = await cognitoidentityserviceprovider.listUsers(params).promise();
        console.log(response);
        let users = response.Users;
        if (users.length > 0) {
            let user = users[0];
            if (user.UserStatus == "UNCONFIRMED") {
                console.log("user is unconfirmed");
                let customError = new Error("error_user_not_confirmed");
                callback(customError, event);
            }
        }
    }
    catch (e) {
        console.log(e);
    }
    callback(null, event);
};
```

@sammartinez The following is also supposed to work, but in this case does not pass the clientMetaData to Lambda function as validationData:
```
await Auth.signIn(username, password, {
	metaDataKey: "metaDataValue"
});
```

**Comment by hmelchander-indpro** [comment] 2021-01-20 09:55
@sammartinez any updates?

**Comment by AlexMayleRdn** [comment] 2021-01-21 13:27
This doesn't seem to be an issue with amplify at all. Cognito simply does not support this, regardless of which client library you use. The docs conflict.

1. This says that clientMetadata is passed to the preTokenGeneration lambda. Analogous pages for other hooks also exist. https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html
2. The lower-level API reference directly contradicts the reference above with "The ClientMetadata value is passed as input to the functions for only the following triggers: Pre signup, Pre authentication, User migration." https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html

So this should really be brought to the Cognito team's attention.

**Comment by elorzafe** [comment] 2021-01-27 20:01
I can confirm the issue with token refresh. `clientMetadata` from `Auth.configure` is not being used for token refresh.

However in case you override `clientMetadata` when doing `Auth.signIn`, it seems that should be part of the session as well. I am not 100% sure about that behavior, meanwhile I will send a PR to fix the issue when `clientMetadata` is used on `Auth.configure` so at least that use case is covered.

**Comment by elorzafe** [comment] 2021-01-29 00:48
Amplify JS library latest version 3.3.15 is sending `ClientMetadata` for token refresh when is configured at category level.`Auth.configure`.

We will have a follow up pr to support clientMetadata param on `Auth.signIn` as well. 

Cognito service team needs to support sending ClientMetadata on pre token generation lambda for InitiateAuth API calls, they currently support this for AdminRespondToAuthChallenge and RespondToAuthChallenge  APIs

**Comment by elorzafe** [comment] 2021-01-29 21:29
Amplify JS library has this problem solved. Latest version is sending `ClientMetadata` for token refresh.

We are expecting now from Cognito service to fix the problem on the server side.

Please +1 on one of this issues on AWS Forums to keep more feedback for this internally
https://forums.aws.amazon.com/thread.jspa?messageID=946444&#946444
https://forums.aws.amazon.com/thread.jspa?messageID=910021&#910021

or feel free to create an issue on AWS Forums as well

**Closed by elorzafe** 2021-01-29 21:29 UTC
Labels: Auth, Cognito, Service Team, amazon-cognito-identity-js, bug

**Comment by Bykerbry** [comment] 2021-03-07 23:47
Any word from the Cognito team? It seems Amplify is now handling the clientMetadata correctly, however, Cognito only includes it sometimes. The clientMetadata is included in the PreTokenGeneration Lambda event during login, but not on token refresh. This causes our app to break whenever the token refreshes because the token's claims change.

**Comment by jherrerosb** [comment] 2021-03-10 22:33
I'm desperately needing this to work!! any news?

**Comment by symbianm** [comment] 2021-03-29 15:25
Need it too

**Comment by zoloogg** [comment] 2021-05-28 08:53
Just confirmed that ClientMetadata is nowhere seen in AWS Lambda triggeres. frustrated.

**Comment by AlexMayleRdn** [comment] 2021-06-02 17:33
> Just confirmed that ClientMetadata is nowhere seen in AWS Lambda triggeres. frustrated.

@zoloogg please go post in one of the topics below or make another one as this will only get solved if the Cognito team, not the Amplify SDK team, honors the client metadata.

https://forums.aws.amazon.com/thread.jspa?messageID=946444&#946444
https://forums.aws.amazon.com/thread.jspa?messageID=910021&#910021

**Comment by ymussi** [comment] 2021-07-09 18:55
> I have a working code snippet to pass data as parameter to the lambda function with Cognito Pre authentication trigger:
> 
> ```
> await Auth.signIn({
> 	username: username,
> 	password: password,
> 	validationData: {
> 		metaDataKey: "metaDataValue"
> 	}
> });
> ```
> 
> You can fetch the passed data value from "event.request.validationData.metaDataKey" on the Lambda side (Node.js).
> 
> An example for email validation to check if email unconfirmed or not:
> Client-side:
> 
> ```
> await Auth.signIn({
> 	username: username,
> 	password: password,
> 	validationData: {
> 		email: email
> 	}
> });
> ```
> 
> Lambda function (Node.js):
> 
> ```
> var AWS = require('aws-sdk');
> 
> exports.handler = async (event, context, callback) => {
>     console.log("Received event");
>     console.log(event);
>     var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({
>         apiVersion: "2016-04-18",
>         region: event.region
>     });
>     let params = {
>         UserPoolId: event.userPoolId,
>         AttributesToGet: ["email"],
>         Filter: "email='"+event.request.validationData.email+"'"
>     };
> 
>     try {
>         let response = await cognitoidentityserviceprovider.listUsers(params).promise();
>         console.log(response);
>         let users = response.Users;
>         if (users.length > 0) {
>             let user = users[0];
>             if (user.UserStatus == "UNCONFIRMED") {
>                 console.log("user is unconfirmed");
>                 let customError = new Error("error_user_not_confirmed");
>                 callback(customError, event);
>             }
>         }
>     }
>     catch (e) {
>         console.log(e);
>     }
>     callback(null, event);
> };
> ```
> 
> @sammartinez The following is also supposed to work, but in this case does not pass the clientMetaData to Lambda function as validationData:
> 
> ```
> await Auth.signIn(username, password, {
> 	metaDataKey: "metaDataValue"
> });
> ```

It works for me!

**Comment by ClaudionorJunior** [comment] 2021-07-09 18:57
> I have a working code snippet to pass data as parameter to the lambda function with Cognito Pre authentication trigger:
> 
> ```
> await Auth.signIn({
> 	username: username,
> 	password: password,
> 	validationData: {
> 		metaDataKey: "metaDataValue"
> 	}
> });
> ```
> 
> You can fetch the passed data value from "event.request.validationData.metaDataKey" on the Lambda side (Node.js).
> 
> An example for email validation to check if email unconfirmed or not:
> Client-side:
> 
> ```
> await Auth.signIn({
> 	username: username,
> 	password: password,
> 	validationData: {
> 		email: email
> 	}
> });
> ```
> 
> Lambda function (Node.js):
> 
> ```
> var AWS = require('aws-sdk');
> 
> exports.handler = async (event, context, callback) => {
>     console.log("Received event");
>     console.log(event);
>     var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({
>         apiVersion: "2016-04-18",
>         region: event.region
>     });
>     let params = {
>         UserPoolId: event.userPoolId,
>         AttributesToGet: ["email"],
>         Filter: "email='"+event.request.validationData.email+"'"
>     };
> 
>     try {
>         let response = await cognitoidentityserviceprovider.listUsers(params).promise();
>         console.log(response);
>         let users = response.Users;
>         if (users.length > 0) {
>             let user = users[0];
>             if (user.UserStatus == "UNCONFIRMED") {
>                 console.log("user is unconfirmed");
>                 let customError = new Error("error_user_not_confirmed");
>                 callback(customError, event);
>             }
>         }
>     }
>     catch (e) {
>         console.log(e);
>     }
>     callback(null, event);
> };
> ```
> 
> @sammartinez The following is also supposed to work, but in this case does not pass the clientMetaData to Lambda function as validationData:
> 
> ```
> await Auth.signIn(username, password, {
> 	metaDataKey: "metaDataValue"
> });
> ```

It works for me, thank you save my life, my co-worker would kick me if I couldn't make it work!

**Comment by Lvitoria** [comment] 2021-07-09 19:02
> I have a working code snippet to pass data as parameter to the lambda function with Cognito Pre authentication trigger:
> 
> ```
> await Auth.signIn({
> 	username: username,
> 	password: password,
> 	validationData: {
> 		metaDataKey: "metaDataValue"
> 	}
> });
> ```
> 
> You can fetch the passed data value from "event.request.validationData.metaDataKey" on the Lambda side (Node.js).
> 
> An example for email validation to check if email unconfirmed or not:
> Client-side:
> 
> ```
> await Auth.signIn({
> 	username: username,
> 	password: password,
> 	validationData: {
> 		email: email
> 	}
> });
> ```
> 
> Lambda function (Node.js):
> 
> ```
> var AWS = require('aws-sdk');
> 
> exports.handler = async (event, context, callback) => {
>     console.log("Received event");
>     console.log(event);
>     var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({
>         apiVersion: "2016-04-18",
>         region: event.region
>     });
>     let params = {
>         UserPoolId: event.userPoolId,
>         AttributesToGet: ["email"],
>         Filter: "email='"+event.request.validationData.email+"'"
>     };
> 
>     try {
>         let response = await cognitoidentityserviceprovider.listUsers(params).promise();
>         console.log(response);
>         let users = response.Users;
>         if (users.length > 0) {
>             let user = users[0];
>             if (user.UserStatus == "UNCONFIRMED") {
>                 console.log("user is unconfirmed");
>                 let customError = new Error("error_user_not_confirmed");
>                 callback(customError, event);
>             }
>         }
>     }
>     catch (e) {
>         console.log(e);
>     }
>     callback(null, event);
> };
> ```
> 
> @sammartinez The following is also supposed to work, but in this case does not pass the clientMetaData to Lambda function as validationData:
> 
> ```
> await Auth.signIn(username, password, {
> 	metaDataKey: "metaDataValue"
> });
> ```

It works for me

**Comment by ricardoribas** [comment] 2021-12-09 12:09
@chrisbonifacio  there is any place where I can create an issue for cognito to analyze? I am having the same problem. I am implementing passwordless authentication on my application, but i need to distinguish between a sign-in made with the email address and a sign-in made with a phone number. The client metadata woud come in handy as i can mark the type of authentication made.

**Comment by Nighthawk14** [comment] 2021-12-30 15:58
> @chrisbonifacio there is any place where I can create an issue for cognito to analyze? I am having the same problem. I am implementing passwordless authentication on my application, but i need to distinguish between a sign-in made with the email address and a sign-in made with a phone number. The client metadata woud come in handy as i can mark the type of authentication made.

I'm trying to achieve a very similar flow, did you find any workaround?

**Comment by cmaycumber** [comment] 2022-02-16 16:14
Solved this by implementing a two-step custom challenge flow as described here: 

https://github.com/aws-samples/amazon-cognito-passwordless-email-auth/issues/9

**Comment by subhan300** [comment] 2023-01-30 15:22
> from Cognito service to fix the problem on the server side.

is there any way to pass any data from the pre-auth lambda function to the define-auth lambda function?

**Comment by dey00p2** [comment] 2023-03-08 14:54
> aws-samples/amazon-cognito-passwordless-email-auth#9

Facing the same problem even now for the same feature. Looks like InitiateAuth API still doesn't support client metadata where respondToAuthChallenge API does. But Ideally need to have both working with client meta data.

**Comment by royraulmilta** [comment] 2024-05-13 09:04
> SO : https://stackoverflow.com/questions/62548852/aws-cognito-and-amplify-clientmetadata-not-sent-when-session-is-refreshed

is this issue fixed?

**Comment by rashidwiizb** [comment] 2024-05-13 09:27
> SO : https://stackoverflow.com/questions/62548852/aws-cognito-and-amplify-clientmetadata-not-sent-when-session-is-refreshed

is this issue fixed?

**Comment by anttiviljami** [comment] 2024-05-28 21:01
We're in 2024 and `ClientMetadata` is still not received for token refresh events in the pre token generation triggers in Cognito. I guess not hope of getting this fixed by the Cognito Team :/

**Comment by keremnalbant** [comment] 2024-05-28 21:57
`PreTokenGenerationEvents` doesn't support passing `ClientMetadata` on `triggerSource`: `TokenGeneration_RefreshTokens`. Although this may seem like an easy thing to solve, it is a pity that no action has been taken for years by Cognito Team.

**Comment by iKnowJavaScript** [comment] 2024-06-10 16:54
It's interesting how this has dragged on for so long without a proper solution in sight.
I'm right here with everyone else.

**Comment by AntoniBertel** [comment] 2024-10-12 22:25
Same here, my perception is that the service doesn't have any ownership
