### ISSUE TITLE
Azure SSO integration with amplify app.

### ISSUE THREAD

**Issue by dloaizarico** [aws-amplify/amplify-js#11331] opened 2023-05-03 11:06 UTC
### Amplify CLI Version

lastest

### Question

Hi Amplify team,

I wonder if you know a way to integrate Azure SSO with an amplify app by using IaC, I have seen a few example by configuring everything through the cognito console but not by using amplify CLI or amplify code.

Thanks a lot.

**Comment by nadetastic** [comment] 2023-05-03 17:01
Hi @dloaizarico could you try visiting the Hosted UI directly and see if you have an option to SSO with Azure? The easiest way to do so is to go to the App Client associated with Cognito User Pool and click on the View Hosted UI link.

Using `Auth.federatedSignIn()` should do the same thing, but Im hoping to determine if the issue is on the client side or on Cognito side.

![Screenshot 2023-05-03 at 11 58 43 AM](https://user-images.githubusercontent.com/87148442/235987416-aba492eb-ee41-487e-8dfe-d775716967b3.png)

**Comment by dloaizarico** [comment] 2023-05-04 00:18
Hi @nadetastic, thanks for the answer, I have tried that and when clicking that button from the console, I got my logic page of Microsoft:

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/78745641/236078144-719a5241-744d-4b01-8bc5-bd97c3dc2002.png">

https://login.microsoftonline.com/tenantID/oauth2/v2.0/authorize?client_id=clientID&redirect_uri=https%3A%2F%2Fssodev.auth.ap-southeast-2.amazoncognito.com%2Foauth2%2Fidpresponse&scope=email+profile+openid&response_type=code&state=H4sI....

**Comment by nadetastic** [comment] 2023-05-04 18:12
Okay thank you for verifying - it looks like there maybe some misconfiguration on the client side - could you share your `aws-exports.js` file? There are a few config options needed (such as client id, redirect urls etc) for `Auth.federatedSignIn()` to work [as seen here](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#authentication-amazon-cognito), and want to make sure that those have been set.

**Comment by nadetastic** [comment] 2023-05-04 18:15
Also note that since you are using overrides, you may need to manually plug them in when calling `Amplify.configure()`

For example:

```js
import { Amplify } from 'aws-amplify'
import awsExports from './src/aws-exports.js'

Amplify.configure({
	...awsExports,
	// additional config
})

**Comment by dloaizarico** [comment] 2023-05-05 15:56
Hi @nadetastic after trying with a few configurations it kind of work for me I guess but I do have a question in regards to all this flow:

I have an amplify app with react and we have normal cognito authentication flow with username and password. Now, we want to include Microsoft as part of our authentication options on a SSO process. However, we don't want to go through the AD of Azure because we have many clients so as you can imagine we can't go and ask more than 100 clients for their tenant ids, secrets, and so on a so forth, and also creat cognito app clients for each tenant (customer). Is there a way to authenticate users with just an outlook email, not an AD account? similar to how Google and Facebook do and that is described here: https://docs.amplify.aws/lib/auth/social/q/platform/js/.

Also, do you know why in the same link https://docs.amplify.aws/lib/auth/social/q/platform/js/, there's no direct process for outlook/microsoft accounts as there is for Google, Facebook and Apple?

Thanks a lot for any clarification.

**Comment by dloaizarico** [comment] 2023-05-11 10:52
I wonder if you have any updates on my latest comments @nadetastic ?

Thanks a lot.

**Comment by nadetastic** [comment] 2023-05-23 15:55
@dloaizarico apologies for the delay - unfortunately, Cognito only support Google, Apple, Facebook, and Amazon as default providers where you can follow the steps that are outlined in the documentation. In order to use Microsoft, you would need to set it up as a SAML provider with Active Directory.

**Comment by nadetastic** [comment] 2023-05-23 15:56
Related https://github.com/aws-amplify/amplify-js/issues/439

**Comment by dloaizarico** [comment] 2023-05-25 03:05
HEY @nadetastic, we have a lot of clients and it seems that cognito does not allow multitenancy with AD, is there any way to approach this solution?

**Comment by nadetastic** [comment] 2023-06-27 14:35
Hi @dloaizarico - a potential approach for multi-tenancy with cognito would be to use Cognito Groups, where each tenant can be a part of a group based on the access they should have. Have you had a chance to look at this option?

- [Adding User groups with Amplify](https://docs.amplify.aws/cli/auth/groups/)
- [Cognito user pool groups](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html)

**Comment by nadetastic** [comment] 2023-07-05 15:32
@dloaizarico following up here, if you have any additional questions, let me know. If not, I'll go ahead and close this issue out. Thanks!

**Closed** 2023-07-06 00:29 UTC
Labels: question, documentation, Auth, transferred, pending-response
