### ISSUE TITLE
delete social idp linked user / delete EXTERNAL_PROVIDER user

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#6121] opened 2020-06-18 21:44 UTC
**Is your feature request related to a problem? Please describe.**

I have been using user object returned by currentAuthenticatedUser to deleteUser. It has been working but recently I added login with Google and noticed that it doesn't delete the linked account in Cognito (the entry with EXTERNAL_PROVIDER status). 
```
  const user = await Auth.currentAuthenticatedUser();
  user.deleteUser((error, data) => {
    if (error) {
      throw error;
    }
  });
```

**Describe the solution you'd like**

Could it be made to delete linked entries? 

It seems to be related to https://github.com/aws-amplify/amplify-js/issues/469

**Describe alternatives you've considered**

[Admin actions](https://docs.amplify.aws/cli/auth/admin) doesn't seem to provide delete user function either.

**Comment by Jun711** [comment] 2020-06-25 00:05
I figured it out after checking other issues. I had to go to my user pool on AWS Console for Cognito > "App client settings" > "Allowed OAuth Scopes" and check "aws.cognito.signin.user.admin" to authorize delete account action.

**Comment by Jun711** [comment] 2020-06-25 20:05
@amhinson 
It seems that it cannot delete both cognito account and linked account at the same time.

Considering these 3 cases in user pool
1) Google login (EXTERNAL_PROVIDER) account
2) Cognito account
3) Cognito account + linked Google login (EXTERNAL_PROVIDER) account

When I run the following code, it can delete case 1 and 2 from user pool. For case 3, it would only delete the Cognito account, the linked Google login (EXTERNAL_PROVIDER) account would still exist in the user pool.

```
const user = await Auth.currentAuthenticatedUser();
  user.deleteUser((error, data) => {
    if (error) {
      throw error;
    }
  });
```

**Comment by kimfucious** [comment] 2020-06-26 16:59
Hi Jun,

I commented on your other thread [here](https://github.com/aws-amplify/amplify-js/issues/469#issuecomment-650284148).

Hope it helps.

Best,

Kim

**Comment by tannerabread** [comment] 2023-03-01 23:03
Closing this as a duplicate of #3431. I believe they are asking for the same thing so we will track progress on the other issue. 

Thank you.

**Closed by tannerabread** 2023-03-01 23:03 UTC
Labels: feature-request, Auth
