### ISSUE TITLE
Pinpoint Provider does not handle clock skew and breaks down

### ISSUE THREAD

**Issue by FinestV** [aws-amplify/amplify-js#7334] opened 2020-12-04 03:29 UTC
**Describe the bug**
The Pinpoint provider does not account for clock skew. Requests to Pinpoint endpoints will fail with a 403 and not be retryed. Further requests will not be sent and analytics events from these user sessions are lost We get alot of these errors each month from our user base.

**To Reproduce**
1. Enable Pinpoint using @aws-amplify/analytics call Analytics.configure({ AWS.Pinpoint: {...} }) and enable Analytics.autoTrack('pageView', { enable: true })
2. Change your operating system clock to -1 hour before the actual time
3. Load a page and watch the console and network tab. You will see 403 responses and Promise rejections in the console. These failed requests will not be retryed and Pinpoint will fall over.

**Expected behavior**
This has been fixed for @aws-amplify/api-graphql and @aws-amplify/api-rest https://github.com/aws-amplify/amplify-js/pull/5869 The same fix should be applied to the Pinpoint provider. Note this fix uses a helper function isClockSkewError https://github.com/aws-amplify/amplify-js/pull/5869/files#diff-47b9fffbfc9dddeb69085d8904d2af3f634f430b7bcdab580764d0ecf8e2159aR69 In this instance `x-amzn-errortype` will be `InvalidSignatureException` so a similar function would need to be modified to account for this

**Code Snippet**
```
Auth.configure({
	Auth: {
		identityPoolId,
		region: cognitoRegion,
	},
});

Analytics.configure({
	AWSPinpoint: {
		appId,
		region: pinpointRegion,
		mandatorySignIn: false,
		endpoint,
	},
});

Analytics.autoTrack('pageView', {
	enable: true,
	type: 'SPA',
});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13340489/101118635-5ec12f80-364e-11eb-8a3d-ed9a9c943bc9.png)

![image](https://user-images.githubusercontent.com/13340489/101118067-3dac0f00-364d-11eb-9981-2f1ff057e80d.png)

**Comment by sammartinez** [comment] 2020-12-11 23:05
@FinestV thanks for reporting this issue. This is a known issue, and we are looking to pull this into our backlog to address. Once we have this groomed, we can provide a timeline when to expect a fix for this. Thanks again for reporting this!

**Comment by ericclemmons** [comment] 2021-05-11 16:40
Sharing some prior research into this specifically:

https://github.com/aws-amplify/amplify-js/pull/5869#issuecomment-634932879

**Comment by jamesaucode** [comment] 2022-01-06 20:03
This will be fixed by upgrading our AWS SDK dependencies. There are impacts on React Native by upgrading it so we are still working on the upgrade.

**Comment by cwomack** [comment] 2022-11-17 18:01
Closing this issue due to being a duplicate of #9281, but there are more recent conversations and context within that issue. Please follow the newer one for updates or add new comments there.

**Closed by cwomack** 2022-11-17 18:01 UTC
Labels: bug, Analytics
