### ISSUE TITLE
Electron app leveraging DataStore shows error - "Realtime disabled when in a server-side environment"

### ISSUE THREAD

**Issue by Gab1988** [aws-amplify/amplify-js#8538] opened 2021-07-05 11:07 UTC
### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 290.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @preconstruct/cli: ^2.0.7 => 2.1.0 
    @zeplin/cli: 1.1.12 => 1.1.12 
    @zeplin/cli-connect-react-plugin: ^1.1.1 => 1.1.1 
    rimraf: ^3.0.2 => 2.7.1 (3.0.2, 2.2.8)
    webpack-cli: ^4.6.0 => 4.7.2 (3.3.12)
  npmGlobalPackages:
    @aws-amplify/cli: 4.20.0
    @zeplin/cli-connect-react-plugin: 1.1.1
    @zeplin/cli-connect-storybook-plugin: 0.5.3
    @zeplin/cli: 1.1.11
    create-react-native-app: 3.6.0
    env-cmd: 10.1.0
    expo-cli: 4.5.2
    lerna: 4.0.0
    netlify-cli: 3.21.9
    npm: 6.14.13
    react-devtools: 4.10.1
    rimraf: 3.0.2
    serverless: 2.19.0
    sharp-cli: 1.15.0
    source-map-explorer: 2.5.2
    wscat: 4.0.1
    yarn: 1.22.10

```

</details>

### Describe the bug

Datastore correctly saves and queries data when I use the app on Native and/or Web. Both online and offline
When I instead run my app on electron I get the following error 

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/47523111/124461027-7ecaf400-ddd3-11eb-9a2c-a0b4012de97f.png">

These are the versions of the packages involved
```
    "@aws-amplify/auth": "^4.1.0",
    "@aws-amplify/core": "4.1.2",
    "@aws-amplify/datastore": "3.1.2",

```

If it can help with the troubleshooting, Amplify Auth/Core do work correctly as far as I can tell
I can see the credentials are indeed stored on the local storage and I can see the relevant schema in the IndexedDB section
<img width="495" alt="image" src="https://user-images.githubusercontent.com/47523111/124461501-0fa1cf80-ddd4-11eb-9747-2b71d6883d3d.png">

<img width="968" alt="image" src="https://user-images.githubusercontent.com/47523111/124462682-4b896480-ddd5-11eb-98ad-44438dce942e.png">

Hope someone can help  

### Expected behavior

Be able to push and retrieve data from local storage as the web version

### Reproduction steps

Create a react native app with expo (Managed workflow)
Follow the integration steps suggested by AWS
Run expo electron

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

<img width="968" alt="image" src="https://user-images.githubusercontent.com/47523111/124462339-f64d5300-ddd4-11eb-8572-c1f9e0edc894.png">

```

</details>

**Comment by Gab1988** [comment] 2021-07-07 12:12
After additional digging it comes down to the function `isNode` that is used by DataStore and AppSync to determine whether the process is running on the browser or not
As the electron main is running on node.js I would assume indexedDB cannot be correctly accessed

Not sure whether there is some sort of workaround I can apply as we would really like to use Datastore

**Comment by Gab1988** [comment] 2021-07-08 04:41
It might help someone hence sharing here
The problem I have been facing with DataStore can be bypassed using AppSync only

Once again I'm using a managed expo workflow to get the electron integration out of the box

Basically the approach is to fork at compile time how the AppSync client is created leveraging expo/webpack resolution strategy which will pick the filename with electron as extension first :

I'm thinking of using this strategy to abstract the client generation and remove if-else condition which is not pretty but it does work for now

Default client -> AppSyncClient - browser instance
nodeClientGenerator ->  AppSyncClient - node instance

Adapt the code as you see fit but mine is as follows 

//my AppSyncClient.js 

```

import AWSAppSyncClient from "aws-appsync";
import { Rehydrated } from "aws-appsync-react";
import { ApolloProvider } from "react-apollo";
import API, { graphqlOperation } from "@aws-amplify/api";
import Amplify from "@aws-amplify/core";
import nodeClientGenerator from "./wherever you place it"

AppAuth.Auth.configure(config);
// API.configure({ ...config });
Amplify.configure({
  ...config,
  DataStore: {
    fullSyncInterval: 60 * 24 * 15, // 15 days
    syncPageSize: 1000, // "limit" sent to graphql
    maxRecordsToSync: 2000000,
  },
});
....
let client;
if (process.versions.node) {
  console.log("Trying to generate client for node");
  client = nodeClientGeneratorElectron.client;
} else
  client = new AWSAppSyncClient({
    url: config.aws_appsync_graphqlEndpoint,
    region: config.aws_appsync_region,
    disableOffline: true, // up to you here
    auth: {
      type: config.aws_appsync_authenticationType,
      // Get the currently logged in users credential.
      jwtToken: async () =>
        (await AppAuth.Auth.currentSession()).getAccessToken().getJwtToken(),
    },
    // Amplify uses Amazon IAM to authorize calls to Amazon S3. This provides the relevant IAM credentials.
    complexObjectsCredentials: () => AppAuth.Auth.currentCredentials(),
  });
console.log("This is the client", client);

<ApolloProvider client={client}>
      <Rehydrated>
.....Your app
   </Rehydrated>
    </ApolloProvider>
```
//my  nodeClientGenerator.electron.js

```
/* eslint-disable no-console */
global.WebSocket = require("ws");
require("es6-promise").polyfill();
require("isomorphic-fetch");
const config = require("../Auth/aws-exports").default;
const AppAuth = require("@toothfairy/shared-ui/AppAuthScreen").default;
// eslint-disable-next-line import/no-extraneous-dependencies
const AWS = require("aws-sdk");
const AUTH_TYPE = require("aws-appsync/lib/link/auth-link").AUTH_TYPE;
const AWSAppSyncClient = require("aws-appsync").default;

const url = config.aws_appsync_graphqlEndpoint;
const region = config.aws_appsync_region;
const type = config.aws_appsync_authenticationType;

AWS.config.update({
  region: config.REGION,
  credentials: new AWS.Credentials({
    accessKeyId: config.AWS_ACCESS_KEY_ID,
    secretAccessKey: config.AWS_SECRET_ACCESS_KEY,
  }),
});
const credentials = AWS.config.credentials;

// Set up Apollo client
const client = new AWSAppSyncClient({
  url: url,
  region: region,
  auth: {
    type: type,
    jwtToken: async () =>
      (await AppAuth.Auth.currentSession()).getAccessToken().getJwtToken(),
  },
  //disableOffline: true      //Uncomment for AWS Lambda
});

export default {client}
```

In the meantime it would be great to get some support on DataStore or if anyone has remarks on this solution please let me know

**Comment by chrisbonifacio** [comment] 2021-07-12 15:35
Hey @Gab1988 thanks for raising this and providing a workaround 😄 I'm not familiar with using DataStore in an Electron app but I think I understand why it's throwing that error when it checks whether it's running in a Node environment or not. I'll take this to the team and get some feedback for you.

**Comment by Gab1988** [comment] 2021-07-13 07:00
Thanks @chrisbonifacio, let me know if I can help :-)

**Comment by Gab1988** [comment] 2021-07-20 03:54
Hey @chrisbonifacio further update on this "issue"

I managed to debug DataStore and it seems that because of Electron, the storage adapter constructor does end up with IndexedDB no matter what ( at the certain point I thought maybe something is going on with AsyncStorage...)
We could also see that the storage was indeed initialised with no errors
See .../node_modules/@aws-amplify/datastore/lib-esm/storage/storage.js
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/47523111/126259403-7e02a18a-4d97-49a2-9509-f9e9a7bf1d43.png">

In attempt to troubleshoot one more time, I did add the following additional packages:

`"aws-appsync": "4.0.5",
"aws-appsync-react": "4.0.5"
"@react-native-community/async-storage": "1.12.1"`

Once done I can see DataStore working correctly on Electron as well!

So not sure whether I missed this info on the docs but it could be meaningful to verify whether my assumptions are correct, if so maybe specify this peer deps in the docs 

Hope it makes sense

**Comment by james-braund** [comment] 2021-09-05 13:09
Hi @chrisbonifacio ,

Wanted to add some of my own experiences and findings to what @Gab1988 has shared.

I've been using Electron with Datastore in an app we've been working on for the last ~8 months. The warning about "realtime disabled" seemed non-harmful to us during initial online testing, but when we've been testing the app's offline capabilities, we found that it was problematic. There seem to be various checks throughout the Amplify codebase that make the assumption that if it is running in a Node context, then it must be server-side, and it must have guaranteed connectivity.

I appreciate that running in Electron (also a Node environment) is probably not one of the main use-cases that Amplify is considered for, but I've found it to be a very useful combination of technologies.

For now, I'm hacking around this by using [patch-package](https://www.npmjs.com/package/patch-package) to override `JS.browserOrNode` and force `isNode` to return false. Dirty, yes, but testing so far suggests it's successful.

Some suggestions for how Amplify could be modified for better compatibility with client-side Node runtime environments:
-  Allow a manual override - bit dirty, and requires specific effort by the developer using the lib. Might go against the ethos of Amplify.
- Add a specific flag for `isElectron` - again, feels a bit dirty, since it's tied to a specific runtime environment. But equally, `isNode` is conceptually similar? Would also require more updates through the codebase.
- Attempt to infer a client-side Node environment by checking if both `isNode` and `isBrowser` are `true`. This feels the most elegant, but would still require updates through the codebase. There may also be some odd edge-cases where this doesn't elicit the expected behaviour.

Just a few suggestions, but hopefully handy. Having more support for the Electron runtime environment would be really appreciated.

**Comment by smachesney1991** [comment] 2022-04-21 10:27
Hi @james-braund 
Can you show me how you overrode JS.browserOrNode and force isNode to return false please? I'm having the same issue

**Comment by dpilch** [comment] 2022-06-28 16:44
Thanks for the suggestions. Based on the use case described in #7597 I am leaning towards the manual override. Seems like an easy win for the two use cases, but like you said may not be in line with the Amplify design philosophy.

**Comment by alharris-at** [comment] 2022-10-19 19:31
I'm going to close this issue. Electron is not a supported platform for Amplify Datastore, and we have no plans to support it at this point.

Because there are corner cases that may bite users down the road (as you've already experienced) I don't want to suggest a workaround to make it work in the short-term. If you wish to continue down the untested route I'd suggest operating in a fork of the repo.

**Closed by alharris-at** 2022-10-19 19:31 UTC
Labels: DataStore
