### ISSUE TITLE
Quasar (vuejs) amplify cannot read property 'bytelength' of undefined

### ISSUE THREAD

**Issue by belhadjhaythem** [aws-amplify/amplify-js#10387] opened 2022-09-17 00:55 UTC
I'm using the aws-amplify library to upload images from devices to aws amplify storage.
My config is : 

                           
              Amplify.configure({
                 Auth: {
                 identityPoolId: 'xxxxxxxxxxxxxxxx', 
                 region: 'xxxxxxxx', 
                 userPoolId: 'xxxxxxxxxxxx', 
                 userPoolWebClientId: 'x'
               },
              Storage: {
                AWSS3: {
                  bucket: 'xxxxx-name',
                  region: 'xxxxxxxx',
                }
              }
            });
            
and the `Storage.put` Method for uploading files.

On the browser, it works perfect, i can upload images.
But from the device (Android emulator) with **cordova-plugin-camera** it throws a `cannot read property 'bytelength' of undefined`. 

Here is code used for mobile devices : 
```

navigator.camera.getPicture(
        data => {
          Storage.put("test.jpeg", dataConvertedToBlob).then((res) => {
            this.imageSrc = res.toString();
          });
        },
        (err) => { // on fail
          console.error('Could not access device camera.');
        },
        {
          quality: 100,
          destinationType: Camera.DestinationType.DATA_URL,
          encodingType: Camera.EncodingType.JPEG,
          sourceType: Camera.PictureSourceType.CAMERA,
          mediaType: Camera.MediaType.PICTURE,
          cameraDirection: Camera.Direction.BACK,
        }
      })
```

I tried a lot of convertion methods like sending to the put method blob, convert image to javascript File, sending base64 data, **none of them worked on device**

Any ideas ?

**Comment by abdallahshaban557** [comment] 2022-09-28 22:37
Moving this to the Amplify-JS library since it appears to be a potential issue with the library.

**Comment by QruiserHarish** [comment] 2022-10-01 07:10
Similar issue with Storage.get but I am using React-native. It works on Android but not on IOS.

**Comment by nadetastic** [comment] 2022-10-06 20:46
Hi @belhadjhaythem 👋,

Thanks for raising this issue, I haven't been able to successfully reproduce this and would like to ask some questions:
- This error is usually produced with incorrect/missing credentials, can you confirm whether this is the case?
- After `Storage.put()` do you see the file uploaded to the S3 bucket, when this error happens?

**Comment by nadetastic** [comment] 2022-10-13 21:49
@belhadjhaythem following up with you.

Let me know if you still need help here - unfortunately I haven't been able to reproduce this issue, and are getting the expected result.

Please note that when using Storage, it is common to get the error `...cannot read property 'bytelength' of undefined...` due to incorrect credentials, or attempting to `get()` with an object key that does not exist.

**Comment by belhadjhaythem** [comment] 2022-10-22 13:08
This happens when "**access to unauthenticated identities**" is disabled. Once we activate that in cognito console, this problems disappears.
You can see it ?

**Comment by nadetastic** [comment] 2023-12-06 16:55
Hi @belhadjhaythem following up here - thanks for the additional context, the "access to unauthenticated identities" setting you mentioned is what tells cognito whether you want guest users to have permissions (via the unauthenticated IAM Role) or not. With that disabled, it would make sense that a user who is not logged in will see this error. With V5(and before) the `bytelength` error message usually pointed to permissions issues as the library would try to access an object that was undefined, since the backend rejected the request and did not return anything.

Also please note that the cognito console has been updated and the setting above has shifted and is displayed as a Guest access section under the "User access" tab your identity pool.

Let me know if this is still an issue for you, otherwise I can mark this as closed. Thanks!

**Closed** 2023-12-12 02:51 UTC
Labels: Storage, pending-response
