### ISSUE TITLE
Receiving CORB warning for Pinpoint `_session.stop` event when navigating to new tab in Chrome.

### ISSUE THREAD

**Issue by sahaam** [aws-amplify/amplify-js#6150] opened 2020-06-23 22:13 UTC
**Describe the bug**
Receiving CORB warning for Pinpoint _session.stop event when navigating to new tab in Chrome.

**To Reproduce**

1. Create amplify (3.2.1) app using create-react-app (3.2.0) and set up Analytics following instructions in documentation.
2. Open in Chrome 83.
3. Navigate to new tab.
4. Return to tab in which the amplify app is running.
5. Observe CORB warning in the console.

**Expected behavior**
There should not be any CORB warning.

#4606 

**Additional context**
The _session.stop event, along with all other events, is received and recorded in Pinpoint as expected. The only issue is this CORB warning.

Looks like the issue happens because response header for url `https://pinpoint.${region}.amazonaws.com/v1/apps/${ApplicationId}/events` has `Content-Type: application/json`, but request header has `Content-Type: text/plain;charset=UTF-8` (due to navigator.beacon supports that). So here we have a mismatch of the Content-Type.

**Comment by sahaam** [comment] 2020-07-07 23:41
Hi. Any update on this ?

**Comment by sammartinez** [comment] 2021-02-09 22:51
@sahaam are you still looking for support for this? Please let us know

**Comment by iartemiev** [comment] 2021-04-12 18:04
@sahaam,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:04 UTC
Labels: Analytics, Service Team, pending-close-response-required
