### ISSUE TITLE
Facebook login on ios is failing

### ISSUE THREAD

**Issue by hieunv12** [aws-amplify/amplify-js#10316] opened 2022-09-13 07:50 UTC
I have followed the instructions on  (https://docs.amplify.aws/lib/auth/social/q/platform/js/#full-samples) page but only on android and ios side is having problem not getting login information from aws

**Comment by tannerabread** [comment] 2022-09-14 02:22
Duplicate of #10315

**Comment by tannerabread** [comment] 2022-09-14 02:36
Duplicate of https://github.com/aws-amplify/amplify-js/issues/10315

**Closed by tannerabread** 2022-09-14 02:36 UTC
Labels: duplicate, amplify/js
