### ISSUE TITLE
Amplify PubSub unsubscribe method does not report the status/complete before sign out?  

### ISSUE THREAD

**Issue by entest-hai** [aws-amplify/amplify-js#9805] opened 2022-04-13 13:29 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

PubSub

### Amplify Categories

Not applicable

### Environment information

<details>

```
I am using [Amplify PubSub to subscribe to an IoT topic ](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#subscribe-to-a-topic). I want to stop/unsubscribe before sign out. However, there is no mechanism to check/ensure that unsubscribe completed before sign out.  


```

</details>

### Describe the bug

Sign out happens before unsubscribe completed, therefore, the client (web browser) still subscribe the IoT topic even after sign out. 

### Expected behavior

The unsubscribe method of PubSub should has a mechanism to inform the status of unsubscribe

### Reproduction steps

https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#subscribe-to-a-topic

### Code Snippet

```javascript
const sub1 = PubSub.subscribe('myTopicA').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    complete: () => console.log('Done'),
});

sub1.unsubscribe();
// You will no longer get messages for 'myTopicA'

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2022-04-22 14:37
Hi @entest-hai 👋 thanks for raising this issue. I was able to reproduce consistently and therefore marking as a bug for the team.

**Comment by stocaaro** [comment] 2022-10-04 22:40
Reconnection is now staged on the `next` tag in preparation for release in aws-amplify v5. To test against this update install the `next` tag version of the aws-amplify packages your project is using. eg `yarn add aws-amplify@next`.

With this change any disrupted connection will attempt to reconnect when possible. Reconnection can be expected to trigger 5 seconds after the resources to reconnect are available. If the network is disrupted in a way that can't be detected, reconnection will be attempted every minute until the connection is recovered.

Note that missed messages will not backfill on recovery. If you need to trigger behavior to catch up missed messaged on recovery, this should be possible to implement using the [connection state Hub messages](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#unsubscribe
) released last month.

**Comment by stocaaro** [comment] 2023-02-16 17:02
Hello @entest-hai ,

I'm not sure the behavior you're expecting is consistent with how subscriptions/observables should work.

Reviewing the [zen-observable documentation](https://github.com/zenparsing/zen-observable), I think unsubscribe and complete fit separate use-cases. The two sections from the document that seem most relevant are:
- the subscription's `unsubscribe` method will be invoked when the subscription has closed
- `complete()` Terminates the sequence successfully.

In context, `unsubscribe` is how the client communicates to the back end that it isn't following a given topic any longer where the `complete()` callback is how the back end communicates to the client that the observed sequence is at an end.

Since the MQTT service topic isn't ending in your example, but instead the client is unsubscribing from further updates, I don't think it would be in line with the observable pattern to send a `complete()` callback call in this case.

Further, since these MQTT topics on IoT are never closed, I'm not sure they should ever send a `complete()` callback call. There are cases where errors cause the connection to fail in non-retriable ways, which prompt it to end with an `error()` callback.

Maybe I'm looking at this incorrectly. Are there other examples of observable interfaces where `unsubscribe` triggers `complete()`? Is there a different use-case where `complete()` makes sense and is missing?

Thanks,
Aaron

**Closed** 2023-03-02 15:05 UTC
Labels: bug, PubSub
