### ISSUE TITLE
Ability to override AuthMode in generated API.service.ts

### ISSUE THREAD

**Issue by JrPribs** [aws-amplify/amplify-js#9931] opened 2022-05-24 03:52 UTC
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication, GraphQL API

### Describe the feature you'd like to request

Unless I am missing something the current generated API.service.ts for use with Angular only allows you to work with the default auth strategy. In order to use iam unauthenticated logins I've had to write a custom service & queries to apply the `authMode` option override. This is not very obvious and obviously not ideal since all the queries are already conveniently available in the generated API service

### Describe the solution you'd like

I think it would be ideal to be able to pass in an optional `authMode` param to all the generated functions in the generated `API.service.ts` 

### Describe alternatives you've considered

I am already writing an additional custom service to make my unauthenticated user calls, this is one option but not ideal. 
Alternatively there could just be a second optional service generated that contains queries specific to an auth strategy, bu that seems like it would be much more effort and create more code on the client.

### Additional context

I would be happy to take a look at implementing this, but honestly don't know where that file generation logic lives. If you all are on board with the idea and could give me some direction on locating and updating that code I'd be happy to give it a go. thanks!

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by chrisbonifacio** [comment] 2022-05-24 16:19
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/10461

**Closed** 2022-05-24 16:19 UTC
Labels: feature-request, Angular
