### ISSUE TITLE
Not getting updated Email from Social login

### ISSUE THREAD

**Issue by satishSKY** [aws-amplify/amplify-js#9956] opened 2022-06-02 06:31 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Here is the scenario:-
I am using AWS Cognito for authentication 

I have an apple account and I have login with an apple account and got all details including the email (myemail@abc.com) from the response.
 Then after a few days, I have updated my Email (xyz@gmail.com) from my apple account,
Now I am again login with apple social login, in this case, I got the Old email id (myemail@abc.com), It should be xyz@gmail.com

### Expected behavior

It should return updated details 

### Reproduction steps

1. I have an apple account and I have login with an apple account and got all details including the email (myemail@abc.com) from the response.
2. Then update the Email (xyz@gmail.com) from my apple account.
3. Now I am again login with apple social login, in this case, I got the Old email id (myemail@abc.com), It should be xyz@gmail.com

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

{"UserAttributes":[{"Name":"sub","Value":"xxxxxxxxxxx"},{"Name":"identities","Value":"[{"userId":"xxxxxxxxxxx","providerName":"SignInWithApple","providerType":"SignInWithApple","issuer":null,"primary":true,"dateCreated":xxxxxxxxxxxx}]"},{"Name":"email_verified","Value":"false"},{"Name":"name","Value":"xxxx"},{"Name":"phone_number_verified","Value":"true"},{"Name":"phone_number","Value":"+xxxxxxx"},{"Name":"email","Value":"[myemail@abc.com](mailto:myemail@abc.com)"}],"Username":"signinwithapple_xxxxxxxxxx"}

**Comment by satishSKY** [comment] 2022-06-02 15:42
> Hi @satishSKY wave thanks for raising this issue. I believe there is a limitation on Apple ID where user information is only exposed on the first sign in. If this is a test user and you don't mind removing your app from the user's Apple ID.
> 
> You can do this by navigating to:
> 
> Choose Apple menu  > System Preferences. Click Apple ID, then choose Password & Security. Click Edit next to Apps Using Apple ID.
> 
> Then, select the app you want to remove and click Stop Using Apple ID. The user will be asked to create a new account the next time they try signing in with Apple.
> 
> <img alt="Screen Shot 2022-06-02 at 10 10 48 AM" width="359" src="https://user-images.githubusercontent.com/16952986/171648889-bd9f0977-89a6-488c-9afc-86f3346bed61.png">
> 
> At this point their new email should be reflected in the Cognito session. I understand this is not ideal when you need current information on the user. It seems the only way is for the user themselves to share that information with your app.
> 
> This is a common issue, being reported on Apple developer support forums as recently as a month ago.
> 
> https://developer.apple.com/forums/thread/132223

Thanks @chrisbonifacio

**Comment by chrisbonifacio** [comment] 2022-06-03 15:32
Closing as duplicate of https://github.com/aws-amplify/amplify-js/issues/8976

**Closed by chrisbonifacio** 2022-06-03 15:32 UTC
Labels: Auth, Federation, OAuth, pending-response
