### ISSUE TITLE
Auth in SSR Context Next JS (getInitialProps)

### ISSUE THREAD

**Issue by shweta-codeprism** [aws-amplify/amplify-js#7748] opened 2021-02-15 08:33 UTC
**Describe the bug**
Auth is ssrContext doesn't work inside getInitialProps of nextJS application. 

**To Reproduce**
```javascript
MyApp.getInitialProps = async (context) => {
  const { Auth } = withSSRContext(context);
  try {
    const user = await Auth.currentAuthenticatedUser();
    console.log("my user: ", user);
    return {
      props: {
        authenticated: true,
        username: user.username
      }
    };
  } catch (err) {
    return {
      props: {
        authenticated: false
      }
    };
  }
};
```

**Expected behavior**
It should give the currentUser if user is loggedin. But always throws "No Current User/ Unauthenticated"

**Additional context**
Although getInitialProps is deprecated, its the only way we can fetch global data from _app,js (getStaticProps, getServderSideProps not yet allowed in _app.js)

**Comment by ericclemmons** [comment] 2021-02-15 18:15
Can you share your client-side code as well?  Namely the `Amplify.configure` portion? Thanks!

**Comment by shweta-codeprism** [comment] 2021-02-25 15:26
Amplify configure uses the default aws-exports, without any modification, Just ssr tag is set to true
```javascript
import config from "./src/aws-exports";
Amplify.configure({
  ...config,
  ssr: true
});
```

**Comment by manueliglesias** [comment] 2021-03-09 03:54
Hi @shweta-codeprism 

can you share your dependencies from `package.json` and the output of `npm ls @aws-amplify/auth` or (`yarn list @aws-amplify/auth`) ?

**Comment by shweta-codeprism** [comment] 2021-03-11 10:45
Hi, following are the details in order
<img width="173" alt="dependencies" src="https://user-images.githubusercontent.com/25504208/110775500-fbfeb600-8284-11eb-95c2-62f656963169.PNG">
<img width="357" alt="dev-dependencies" src="https://user-images.githubusercontent.com/25504208/110775506-fdc87980-8284-11eb-9031-f3dfaba93029.PNG">
<img width="535" alt="list" src="https://user-images.githubusercontent.com/25504208/110775510-fdc87980-8284-11eb-8efd-c49546b7296b.PNG">

**Comment by sammartinez** [comment] 2021-05-19 21:19
resolving as the above comment and marking this as a duplicate of #8011

**Closed by sammartinez** 2021-05-19 21:19 UTC
Labels: SSR, UI, to-be-reproduced
