### ISSUE TITLE
CognitoUserPool - Client.js - missing http status error code

### ISSUE THREAD

**Issue by trylas** [aws-amplify/amplify-js#6460] opened 2020-07-30 19:18 UTC
It seems to like error codes are missing and methods like signUp (CognitoUserPool) respond errors as per below. Instead of 400 code you get string 'InvalidParameterException'.

{ 
  code: 'InvalidParameterException',
  name: 'InvalidParameterException',
  message: '1 validation error detected: Value null at \'confirmationCode\' failed to satisfy constraint: Member must not be null' 
}

InvalidParameterException
This exception is thrown when the Amazon Cognito service encounters an invalid parameter.
HTTP Status Code: 400

Link to file
https://github.com/aws-amplify/amplify-js/blob/3642e6af455ee1848c1cc743a7a503e96baefa41/packages/amazon-cognito-identity-js/src/Client.js#L55

**Comment by sammartinez** [comment] 2021-02-09 23:17
@trylas Please let us know if you still are looking for support for this. If so, can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by iartemiev** [comment] 2021-04-12 18:07
@trylas,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:07 UTC
Labels: Cognito, amazon-cognito-identity-js, pending-close-response-required
