### ISSUE TITLE
Use Storage without Credentials

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#1318] opened 2018-07-26 15:21 UTC
This is a question/feature request.

Currently when using the Storage library requires having credentials for Cognito on the AWS account to access a public bucket.  The bucket can be accessed and listed using HTTP get but not with Storage.

What have is a bucket in another AWS account that I need access to and I don't want to have to duplicate it to the AWS account that the app is authenticated through.  Is it possible to use Storage without credentials?

**Comment by manueliglesias** [comment] 2018-07-27 20:30
Hi @rogueturnip 

For now the Storage category always look for credentials. I'll talk to the team about supporting your use case.

The category internally uses the low-level aws-sdk S3 client; meanwhile you can try that (see this [example](http://docs.amazonaws.cn/en_us/AWSJavaScriptSDK/guide/node-examples.html#Amazon_S3__Getting_a_pre-signed_URL_for_a_getObject_operation__getSignedUrl_))

```javascript
var s3 = new AWS.S3();
var params = {Bucket: 'myBucket', Key: 'myKey'};
s3.getSignedUrl('getObject', params, function (err, url) {
  console.log("The URL is", url);
});
```

**Comment by rogueturnip** [comment] 2018-07-28 04:40
Thanks.

In our set up we are using AWS Organizations to seperate our environments but want to store common files at the top level or so we don't have to copy them around and potentially miss something.

**Comment by booboothefool** [comment] 2018-09-28 12:28
@manueliglesias I also have this use case. My auth is provided by another service, so not using Cognito, but would like to use this library for Storage to make things easier.

What is your recommendation on how this should be done manually?

Currently I am doing:
user tries to upload an image from React Native app client -> call backend server to get aws s3 signed url and return it back to the client -> client does the actual POST request to upload

Could this be made easier somehow or am I doing it all correctly? For example, should I possibly just generate presigned url on the client instead of backend? Do I really even need to generate presigned url every time? Looking for the proper balance between security and performance/efficiency.

Thanks!

**Comment by elorzafe** [comment] 2019-02-08 18:29
@anjmao can you try just configuring `Storage` like this.

```javascript
Storage.configure({
        bucket: 'xxxxx',
        region: 'us-east-1',
        credentials: {
            accessKeyId: 'xxx',
            secretAccessKey: 'xxx'
        }
    });
```

**Comment by rogueturnip** [comment] 2019-03-29 15:00
Hi there,
I'm back on this problem.  I tried the above configuration with IAM credentials and I'm still getting an access denied on the list even with the bucket being a public bucket.  I can use the failed get url and access it from the browser directly.

**Comment by rogueturnip** [comment] 2019-03-29 15:06
I also noticed the documentation has the configure JSON slightly different so I tried that with no luck:
Storage.configure({
    AWSS3: {
        bucket: '',//Your bucket name;
        region: ''//Specify the region your bucket was created in;
    }
});

**Comment by rogueturnip** [comment] 2019-03-29 15:13
Figured it out from looking at the amplify storage code.  You can't define credentials in the configure, it's not used at all but you an assign the credentials directly to each call (get, list, put) like this:
        let result = Storage.list('', {credentials: {
                accessKeyId: 'xxx',
                secretAccessKey: 'xxx'
            }});

I think the credentials should also be supported at the storage level so it keeps the code cleaner.

**Comment by rogueturnip** [comment] 2019-03-29 15:52
This also means you can't use any of the components (S3Album) because you can't pass in a credentials prop in this setup.

**Comment by craigjsmith** [comment] 2019-06-15 20:37
How can Storage credentials be defined without exposing them on the front end?

**Comment by Zerquix18** [comment] 2019-08-19 22:43
+1

**Comment by LucasSubli** [comment] 2019-10-16 11:18
+1

**Comment by shiviishiv** [comment] 2020-09-25 03:45
Assume that I have created s3 bucket and got a token, and that token I had put in front-end to upload files to s3.
is there any feature like that, so that I won't have to expose credentials.

**Comment by masbaehr** [comment] 2020-10-03 07:57
I think something has to be provided for the following use case:

Assume a public S3 bucket which files are readable by an authenticated user, but also a not-authenticated user (e.g. no credentials are available). A public S3 bucket/folder is listable by using a simple plain HTTP request without any signed url (confirmed to work just by browsing)

So when doing Storage.list on such a key , the error should not be this (which  happens now), but it should correctly list the contents as they are public!

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>undefined</AWSAccessKeyId>

**Comment by patelvarun** [comment] 2020-10-10 07:15
Hey, any update in this? Can we use storage without Cognito?

**Comment by masbaehr** [comment] 2020-10-10 07:44
anjmao posted already how to use it without cognito (secretkey) - but be aware that anyone can write to your folder if you deploy the secretkey to your client-side package , so be sure to use this method only with node.js server-side

If you mean a public s3 bucket, you can also use axios like i posted, but it depends what you want to do .. read or write..

**Comment by patelvarun** [comment] 2020-10-25 14:17
@masbaehr - Thanks. I already tried that but it was showing no credentials while uploading.

Storage.configure({
        bucket: 'xxxxx',
        region: 'XXX',
        credentials: {
            accessKeyId: 'xxx',
            secretAccessKey: 'xxx'
        }
    });

**Comment by kenchoong** [comment] 2021-08-09 10:02
> How can Storage credentials be defined without exposing them on the front end?

I think is using the Amplify Environment Variables 

https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html


So it is available in build time

**Comment by stocaaro** [comment] 2022-06-02 14:17
Related to #9418 and #5296

**Comment by abdallahshaban557** [comment] 2022-08-10 01:50
Closing this issue as a duplicate of #9418

**Closed by abdallahshaban557** 2022-08-10 01:50 UTC
Labels: feature-request, Storage
