### ISSUE TITLE
please udate  device tracking and remembering features

### ISSUE THREAD

**Issue by sumanchem1989** [aws-amplify/amplify-js#7688] opened 2021-02-05 14:40 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

**Comment by sammartinez** [comment] 2021-02-05 15:47
@sumanchem1989 Thanks for this feature request, can you please look to fill in the template information? Without it, we will need to close the feature request. Thanks ahead of time

**Comment by iartemiev** [comment] 2021-04-12 18:30
@sumanchem1989,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:30 UTC
Labels: feature-request, pending-close-response-required
