### ISSUE TITLE
Pushes are not shown inside the app if our app was opened via tapped push on Notification center (Android)

### ISSUE THREAD

**Issue by RadagastCH** [aws-amplify/amplify-js#6792] opened 2020-09-15 13:59 UTC
Pushes are not shown inside the app if our app was opened via tapped push on Notification center (Android)

**To Reproduce**
1)Send the push via aws/pinpoint
2)push is shown
3)Minimize app to background
4)Send a push - tap on a banner on device screen
5)App launches
6)send a push again

Actual: Notification is not received 

**Expected behavior**
Notification is received 

**Code Snippet**
 PushNotification.onNotification((notification) => {
    console.log('in app notification', notification);
});

Config:
"@aws-amplify/pushnotification": "3.1.3"
"aws-amplify": "2.2.5",
"aws-amplify-react-native": "3.2.2",
"react-native": "0.61.5"

**Comment by amhinson** [comment] 2020-10-20 21:13
This appears to be a duplicate of https://github.com/aws-amplify/amplify-js/issues/6000. We will continue to track in that issue.

**Closed by amhinson** 2020-10-20 21:13 UTC
Labels: Push Notifications, to-be-reproduced
