### ISSUE TITLE
Cognito bug on Safari 15.0 - QuotaExceededError: The quota has been exceeded.

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/amplify-js#9140] opened 2021-11-01 20:40 UTC
### Discussed in https://github.com/aws-amplify/amplify-js/discussions/8986

<div type='discussions-op-text'>

<sup>Originally posted by **chengjiaapraamcos** October  4, 2021</sup>
This happened on the latest Safari 15.0 on both Mac system and IOS system.

Seems like sometimes the localstorage stopped working sometimes, and it could be solved by refreshing the page etc.

Anyone can help?</div>

**Comment by KalvinWei** [comment] 2021-11-23 21:26
> ### Discussed in #8986
> Originally posted by **chengjiaapraamcos** October 4, 2021 This happened on the latest Safari 15.0 on both Mac system and IOS system.
> 
> Seems like sometimes the localstorage stopped working sometimes, and it could be solved by refreshing the page etc.
> 
> Anyone can help?

I experienced the same.

**Comment by alexrogo** [comment] 2021-11-30 12:29
Any updates?
Experienced the same.

**Comment by JakeRuth** [comment] 2021-11-30 18:09
I am also having a few users of our application reporting this issue, the are getting the error: "The quota has been exceeded" when trying to login using aplify/cognito.  This is preventing users from being able to log into our app from their iphones

I will edit/add to this as I learn more and debug.

**Comment by adityasrini** [comment] 2021-12-02 22:00
I got this same error, only for it to work on Chrome Incognito.

**Comment by nefarioustim** [comment] 2021-12-06 04:10
We also have users experiencing this error. I have personally seen it in both Mac OS Safari and Mac OS Chrome, as well as iOS Safari.

**Comment by eltaf-buckitapp** [comment] 2021-12-06 06:05
Some of our clients are also facing this issue, it happened to us a few months back but hardly to reproduce. Does anyone how to trigger it.
@JakeRuth, have you by any chance come with any sort of solution for this issue internally?

**Comment by RNm-dove** [comment] 2021-12-08 01:09
I also had this error.
Client browser is safari and refresh token has expired.

**Comment by djcolon** [comment] 2021-12-08 09:01
We're seeing the same issue.
It seems to be related to calls to window.localStorage.setItem failing because local storage has exceeded its maximum size.

**Comment by davidattias** [comment] 2021-12-10 11:17
I've encountered this issue as well. Only once though.

**Comment by aadu999** [comment] 2021-12-10 14:17
I've experienced the same, Any updates ?

**Comment by silberistgold** [comment] 2021-12-13 11:41
Seeing this as well. Would be great to get a fix asap as this is preventing users from logging in.

**Comment by chengjiaapraamcos** [comment] 2021-12-14 00:14
This happens on Safari 15+ (MacOS, IOS) and all browsers on IOS 15. Guess it's a bug from Safari but could anyone report this issue to Safari team? It's affecting not only Cognito but also the whole Localstorage.

**Comment by chengjiaapraamcos** [comment] 2021-12-14 00:27
Just reported this issue to Apple, hope it can help.

**Comment by r-moore** [comment] 2021-12-14 12:05
Also seeing this on a number of projects that use Cognito. 

If anyone has a link to an issue being tracked by the Webkit/Safari team that would be really helpful

**Comment by yyberi** [comment] 2021-12-15 18:23
Had the same in my Ionic application as well. 
I updated @aws-amplify/auth to 4.3.18 and now it works. No quota errors anymore.

**Comment by KalvinWei** [comment] 2021-12-15 20:13
> Had the same in my Ionic application as well.
> I updated @aws-amplify/auth to 4.3.18 and now it works. No quota errors anymore.

@yyberi mate. Where do you update the @aws-amplify/auth package?
I only installed @aws-amplify and @aws-amplify/react-ui in my React application.

**Comment by KalvinWei** [comment] 2021-12-16 19:47
@yyberi Cheers, mate. Then I assume the problem is the auth module in @aws-amplify is not updated. Hope Amplify staff can notice this.

**Comment by thomasdashney** [comment] 2021-12-16 19:55
I'm not so sure that it's a fix on the amplify side ... I'm seeing this with other third-party libraries (Segment's analytics.js), as well as my own localstorage calls. It could be that it's hard to reproduce, which is why you haven't seen it since upgrading? Or possibly the new amplify version falls back to in-memory storage instead of using localstorage?

**Comment by djcolon** [comment] 2021-12-17 08:56
> Had the same in my Ionic application as well. I updated @aws-amplify/auth to 4.3.18 and now it works. No quota errors anymore.

After upgrading to 4.3.19 my tester is still getting the issue on Safari.

**Comment by fetmar** [comment] 2021-12-21 19:17
I'm experiencing this in my cordova app on iOS 15.1, which uses Safari. I can swipe the app away and try again and it works. If I swipe away again it will not work. There's no way to tell if it will work or not. When I connect my ipad to my laptop and I go to the safari dev tools network tab, I can copy the curl command. The curl command works.

**Comment by angusho1** [comment] 2021-12-22 01:28
We've also been getting this in our Ionic app, currently running on aws-amplify v4.0.3. I'll try updating our package to the latest version (4.3.11), but as others have suggested the library itself doesn't appear up to date.

**Comment by ahurlburt** [comment] 2022-01-03 21:25
> Just reported this issue to Apple, hope it can help.

Is there a bug number? Would be good to upvote this if it's an Apple bug

**Comment by fetmar** [comment] 2022-01-04 22:22
> Having the same issue, haven't updated my amplify app at all, but users just started reporting this to me this week.

Exactly, used to work just fine. Then 15.1 came along. I'm almost not surprised, Safari on iOS has weird media issues too. I don't think anyone cares about Safari iOS.

**Comment by onevision** [comment] 2022-01-11 10:56
I get this issue too. If I refresh the login page it then normally lets me login

**Comment by onevision** [comment] 2022-01-11 10:57
Not sure if this is relevant?
https://stackoverflow.com/questions/42467908/quotaexceedederror-dom-exception-22-the-quota-has-been-exceeded-on-safari-in

**Comment by ahurlburt** [comment] 2022-01-11 15:53
> Not sure if this is relevant? https://stackoverflow.com/questions/42467908/quotaexceedederror-dom-exception-22-the-quota-has-been-exceeded-on-safari-in

I saw that but it's 4 years old and this issue isn't just happening in incognito. The root cause (localstorage not being available) is likely still the root cause and maybe setting to incognito can help reliably reproduce but these seemingly random  failures just started happening (and resolve on refresh)

**Comment by nefarioustim** [comment] 2022-01-11 22:09
I concur with @ahurlburt. The users it is affecting within my app are certainly not using incognito mode regularly. Similarly, it also resolves on refresh, however, that's only useful within a browser—in a WebView wrapped app, the user is less able to just refresh and we are having to advise complete shutdown and restart of the app.

**Comment by carl** [comment] 2022-01-16 19:52
just had this happen yesterday on iOS Safari, not in incognito mode. While trying to debug using Firefox on Mac at least one time saw in the Console > Network tab that it normally makes 5 POST requests to https://cognito-idp.us-east-1.amazonaws.com/ when authenticating in under 1 second, and twice it made 8 POST requests. This seems like a lot. Right now when it does 5 it's doing:

POST AuthFlow | "USER_SRP_AUTH"
POST ChallengeName: PASSWORD_VERIFIER
POST AccessToken: "eyJraWQiO..."
POST AccessToken: "eyJraWQiO..."
POST AccessToken: "eyJraWQiO..."

It seems the last 2 POST requests are kinda redundant.

**Comment by svidgen** [comment] 2022-01-19 20:18
@elorzafe, can you speak to the expected Cognito interaction? Is the behavior @carl is seeing correct?

As for the `QuotaExceededError` itself, our [`StorageHelper`](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/StorageHelper.js) does perform a probing `localStorage.setItem()` call, falling back to an in memory store if the probe fails. But, it only performs this probe *once*. If subsequent `setItem()` calls fail, it looks like they fail loudly.

Working around this will require a little discussion internally here. The `localStorage` probe appears to be succeeding (the exception should be eaten if it fails), which suggests `localStorage` only _eventually_ starts failing. We may need to investigate whether we're keeping `localStorage` clean, and then consider falling back to in memory store more dynamically. But, that could lead to its own issues. So, there's no quick fix _on our end_ for this one AFAIK. We don't want to add bloat just to trade one error for another!

All that said, it may be a good idea to give the `localforage` powered [community solution](https://github.com/aws-amplify/amplify-js/discussions/8986#discussioncomment-1874133) a try in the meantime.

**Comment by svidgen** [comment] 2022-01-19 21:21
@carl When the redundant looking requests occur, can you see whether any of them are CORS preflights?

**Comment by jkananen** [comment] 2022-01-22 20:02
A tester reported that he updated Safari to 15.2.1 and can no longer reproduce the problem. A fluke with a fresh app version, or a resolution? Does anyone know more?

**Comment by darkmarthur** [comment] 2022-02-21 23:09
Hello people!

In my company, we are facing the same issue in our web application on iOS devices when trying to login to the application (using AWS Cognito auth) after a long period (a couple of days) of inactivity with the device browser.

Does anybody find a solution or a workaround to avoid the `QuotaExceededError` response?

**Comment by togro** [comment] 2022-03-05 02:12
I was receiving that message when login with social apple and switch to normal login (on mac) , I check Local Storage and this variables was set on true : 'amplify-signin-with-hostedUI' .

I clean all storages y probe again and can login with problems .

When login was successfull I see on Local Storage 'amplify-signin-with-hostedUI' = false

-------- message ----
This message : {event: "signIn_failure", data: QuotaExceededError: The quota has been exceeded., message: "19c79271-2d2f-4706-aef7-97f95ec384a9 failed to signin"}
"The quota has been exceeded."

**Comment by darkmarthur** [comment] 2022-03-08 16:51
Hello @togro 

Are you saying that cleaning the storage always before attempting login will work around this problem?

**Comment by teemu47** [comment] 2022-03-16 08:23
Worked around this by catching the error, clearing localStorage and instructing the user to try again.
```javascript
if (error.name === 'QuotaExceededError') {
  window.localStorage.clear()
```

**Comment by chengjiaapraamcos** [comment] 2022-03-22 00:43
> Worked around this by catching the error, clearing localStorage and instructing the user to try again.
> 
> ```js
> if (error.name === 'QuotaExceededError') {
>   window.localStorage.clear()
> }
> ```

This works! Many thanks!

**Comment by chengjiaapraamcos** [comment] 2022-03-30 16:32
> 

ts```        try {
           // login here
        } catch (e: any) {
          if (e?.name === "QuotaExceededError") {
  window.localStorage.clear()
// login again
          }
        }```

**Comment by dsharygin** [comment] 2022-04-06 14:38
Looks like this workaround works for the custom authentication code. Does anyone know of a solution for the standard UI component provided in the Amplify library?

**Comment by ryanprince** [comment] 2022-08-04 17:45
Also having this issue in the standard Amplify library UI component. I just saw it after resetting my password using a code sent to my email and then trying to log in again.

**Comment by mariela-plaza** [comment] 2022-10-25 08:48
We are currently having the same issue with a user of our React app. This is the first time it occurs and we've been using Cognito for a while now.

**Comment by jcary741** [comment] 2022-11-30 15:19
This is still an issue, just had a user encounter it using the AWS amplify React authenticator. @nadetastic Are you who should deal with this one? I saw you assigned on a couple other signin issues, but this one bug is >1 old with no assignee.

**Comment by Woodz** [comment] 2023-04-26 07:53
We just encountered this in Safari 15.4. Disappointing that such a high impact bug has been open for so long without any action

**Comment by cwomack** [comment] 2023-08-15 18:16
Wanted to give an update to anyone following this issue.  The next major version of Amplify will include changes to how a user is authenticated, and should result in a reduced amount of network requests.  We believe this will resolve this issue, but we will rely on hearing from those of you impacted by this issue once Amplify v6 is released.  We appreciate everyone’s patience on this!

**Comment by cwomack** [comment] 2023-10-04 20:15
The developer preview for v6 of Amplify has officially been released with updates to the Auth package and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

We believe this issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment] 2023-11-16 21:56
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Closed by cwomack** 2023-11-16 21:56 UTC
Labels: bug, Auth, Browser Compatibly, fixed-in-dev-preview

**Comment by stefankosc01** [comment] 2024-01-16 16:52
hey, experienced this issue (QuotaExceededError: The quota has been exceeded.). 
"@aws-amplify/ui-react": "^6.0.7"

Mac OS X Version:>=10.15.7
browser [Safari 15.0]

**Comment by natuan62** [comment] 2024-11-12 02:52
I got same problem with 

```
"aws-amplify": "^6.6.4",

macOS 15.1 (24B83)

Safari Version 15.3 (17612.4.9.1.8)
```

**Comment by IAMOTZ** [comment] 2025-04-23 23:40
Experiencing the same problem

```
"aws-amplify": "^6.0.30",

MacOs 11.6 (BigSur)

Version 15.0 (16612.1.29.41.4, 16612)
```
