### ISSUE TITLE
PasswortReset when Email not verified and Confirmation status unconfirmed

### ISSUE THREAD

**Issue by johannespn** [aws-amplify/amplify-js#13610] opened 2024-07-18 15:14 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
npmPackages:
    @aws-amplify/adapter-nextjs: 1.0.25 => 1.0.25 
    @aws-amplify/adapter-nextjs/api:  undefined ()
    @aws-amplify/adapter-nextjs/data:  undefined ()
    aws-amplify: 6.4.0 => 6.4.0 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/data:  undefined ()
    aws-amplify/data/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    ...
    next: 14.1.4 => 14.1.4 
```

</details>

### Describe the bug

Calling `resetPassword({ username: values.email })` from `import { resetPassword } from 'aws-amplify/auth'`
 when user `Email verified = No` and `Confirmation status = Unconfirmed` results in
```
{
    "resetPasswordStep": "CONFIRM_RESET_PASSWORD_WITH_CODE",
    "codeDeliveryDetails": {
        "deliveryMedium": "EMAIL",
        "destination": "j***@i***",
        "attributeName": "email"
    }
}
```
but no email with code is being sent. 

### Expected behavior

I would expect this method to **throw an error** in the case that user `Email verified = No` and `Confirmation status = Unconfirmed`

### Reproduction steps

see description

**Comment by cwomack** [comment] 2024-07-18 18:47
Hello, @johannespn and thank you for opening this issue.  Can you double check in the Cognito console that this user's email is unconfirmed?  We'd expect that a user with no confirmed email or phone number would throw an `InvalidParameterException` when trying to call the `resetPassword()` API in this situation (see Cognito docs [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html#API_ForgotPassword_Errors:~:text=If%20neither%20a%20verified%20phone%20number%20nor%20a%20verified%20email%20exists%2C%20this%20API%20returns%20InvalidParameterException.%20If%20your%20app%20client%20has%20a%20client%20secret%20and%20you%20don%27t%20provide%20a%20SECRET_HASH%20parameter%2C%20this%20API%20returns%20NotAuthorizedException.)).

**Comment by johannespn** [comment] 2024-07-18 20:22
Thank you for the quick answer @cwomack, I double checked that the user emails is unconfirmed: see screenshot. I am not getting the exception, but the behavior I described above.

<img width="203" alt="Screenshot 2024-07-18 at 21 18 28" src="https://github.com/user-attachments/assets/fa5ae009-5f87-4af2-9b07-54ff9aadd2ca">

**Comment by cwomack** [comment] 2024-07-30 20:15
@johannespn, was this user created via either the AWS CLI or manually in the Cognito console?

**Comment by johannespn** [comment] 2024-07-31 17:47
We create users via the JavaScript SDK which uses AWS CLI in the background, I believe

**Comment by johannespn** [comment] 2024-08-22 11:21
@cwomack any updates on this? Our customers are complaining that they cannot reset their password

**Comment by josefaidt** [comment] 2024-08-26 20:42
Hey @johannespn :wave: how are users created with the SDK? Do the end users receive an invitation mail they use to log in for the first time?

To reset the password for an unconfirmed user that has not verified their email, you will need to use the `Admin*` APIs from the SDK, specifically `AdminResetUserPassword`
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminResetUserPassword.html

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/command/AdminResetUserPasswordCommand/

**Comment by ysabri** [comment] 2024-09-05 21:15
@josefaidt I'm facing this issue as well and I believe it's similar to this issue: https://github.com/aws-amplify/amplify-js/issues/11270

I recently upgraded to V6 and now I can't handle this error from the frontend side because the hub doesn't send events with errors anymore. I have no way of finding out if the user who is attempting to reset their password has an unconfirmed email.

**Comment by cwomack** [comment] 2024-09-12 15:36
@johannespn, appreciate your patience on responses here.  After @josefaidt's [comment](https://github.com/aws-amplify/amplify-js/issues/13610#issuecomment-2311054071) above and the related issue that @ysabri opened, can you let us know if you think this issue is fundamentally different than #11270? This appears to be the same Cognito limitation reported there.

**Comment by cwomack** [comment] 2024-09-12 15:37
@ysabri, appreciate you linking these two! As for your comment about the hub events, what you mentioned is indeed tied to the changes in the Hub events that are emitted in Auth channel within v6, where there are fewer ([v5 examples](https://docs.amplify.aws/gen1/react/prev/build-a-backend/auth/auth-events/#listen-to-and-log-auth-events) vs [v6 examples](https://docs.amplify.aws/gen1/react/build-a-backend/auth/auth-events/#listen-to-and-log-auth-events)).

**Comment by ysabri** [comment] 2024-09-12 18:12
- @cwomack Yeah this is what I did in V5 to detect that the user is stuck in such a state (account confirmed + email not verified + trying to resest password):

```
 Hub.listen("auth", res => {
      const {payload} = res;
      const {event} = payload;

      const errorMsg = res.payload.data.message ? res.payload.data.message : null;
      if (errorMsg) {
        let errorNotif = errorMsg;

        if (errorMsg === "User does not exist.") {
          errorNotif = "Wrong email or password."
        } else if (errorMsg === "Username/client id combination not found.") {
          errorNotif = "The email is not registered."
        } else if (errorMsg === "Cannot reset password for the user as there is no registered/verified email or phone_number") {
          // Notify the user to open a support ticket so we can help them
          return;
        }
        notifyError(errorNotif);
      }
    });
```

As you mentioned, this isn't the case in V6. I was hoping that at least the `handleForgotPassword` service method in V6 would throw an error I could catch, but it executes successfully even though the operation isn't possible. This seems possible given that V5 had this code as part of the hub event errors.

**Comment by johannespn** [comment] 2024-10-21 16:30
> @johannespn, appreciate your patience on responses here. After @josefaidt's [comment](https://github.com/aws-amplify/amplify-js/issues/13610#issuecomment-2311054071) above and the related issue that @ysabri opened, can you let us know if you think this issue is fundamentally different than #11270? This appears to be the same Cognito limitation reported there.

Yes, seems like the same issue! A user signs up / is being signed up and does not verify their email. Then, they cannot use password reset flow.

**Comment by cwomack** [comment] 2024-10-21 18:51
@johannespn, thank you for the confirmation.  To consolidate the areas where we are tracking this and providing updates, we'll close this as a duplicate of #11270 since they stem from the same root cause.  Please follow that issue for progress and updates, and thank you for taking the time to create this one!

**Closed by cwomack** 2024-10-21 18:51 UTC
Labels: duplicate, question, Auth, pending-maintainer-response
