### ISSUE TITLE
SignOut not changing state to signIn

### ISSUE THREAD

**Issue by kfiras** [aws-amplify/amplify-js#3036] opened 2019-04-07 20:34 UTC
** Which Category is your question related to? **
aws-amplify-react-native
** What AWS Services are you utilizing? **
Amplify
** Provide additional details e.g. code snippets **
Hi,

I am seeing the same issue where I am able to sign out but the app does not render. I tried the code below, but it does not seem to work:

```
import {Greetings} from 'aws-amplify-react-native';

export default class MainScreen extends Greetings {
  signOut() {
    Auth.signOut()
        .then(() => { this.changeState('signedOut'); console.log('here') })
        .catch(err => { this.error(err); console.log('error is .......' + err)} );
  }
  constructor(props){
    super(props);
  }
   render(){
     return (
      <SafeAreaView>
        ...
            <TouchableHighlight style={[styles.buttonContainer]} onPress={() => this.signOut()}>
              <Text style={styles.signupText}>Sign out</Text>
            </TouchableHighlight>
         </View>
        </ScrollView>
      </SafeAreaView>
     );
   }
```

I can see the user being signed out. It also changes the state but it still does not route or render the SignIn page. Any suggestions on how to resolve this issue? Anyone dealt with this issue before? Thanks

**Comment by kfiras** [comment] 2019-04-08 22:34
Any update on this issue? I am not sure what should I do to resolve this issue. I tried many things and rendering signin page does not happen.

**Comment by powerful23** [comment] 2019-04-09 18:57
@kfiras can you provide more details about your app? I can provide a skeleton sample here for you:
```js
import { Greetings } from 'aws-amplify-react-native';
import * as React from 'react';
import { View } from 'react-native';

export default class MainScreen extends React.Component {
  
  constructor(props){
    super(props);

    this.handleAuthStateChange = this.handleAuthStateChange.bind(this);
    this.state = {
      authState: 'signIn', // indicates the current auth state
      authData: null, // would be the user object after signing in
    };
  }

  handleAuthStateChange(state, data) {
    this.setState({ authState: state, authData: data });
  }
  render() {
    const { authState, authData } = this.state;
    const signedIn = (authState === 'signedIn');
    // when user is signed in
    if (signedIn) { 
      return (
        <View>
          <Greetings
              authState={authState}
              authData={authData}
              onStateChange={this.handleAuthStateChange}
              theme={this.props.theme}
          />
          <SignedInComponent
              authState={authState}
              authData={authData}
              onStateChange={this.handleAuthStateChange}
          />
          </View>
        );
    } else {
      // when user is not signed in
      return (
        <View>
            <SignInComponent 
              authState={authState}
              authData={authData}
              onStateChange={this.handleAuthStateChange}
            />
        </View>
      )
    }
  }
}
```

You can also check the doc about how to write your own component and listen on those auth state changes: https://aws-amplify.github.io/docs/js/authentication#customize-your-own-components
or to use the Authenticator: https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component

**Comment by kfiras** [comment] 2019-04-09 19:17
Hi @powerful23 
Below is my mainScreen code.  When I click on 'Sign out', it change the state to 'signedOut' and it did sign me out but it does not refresh the page to the 'Sign in' page.
```
import React, { Component }  from 'react';

import {
  View,
  Image,
  ScrollView,
  SafeAreaView,
  StyleSheet,
  Text,
  TouchableHighlight,
  Alert
} from 'react-native';

import ToolBar from '../components/ToolBar';
import {Auth} from 'aws-amplify';
import {Greetings, AuthPiece} from 'aws-amplify-react-native';

export default class MainScreen extends AuthPiece {
  handleLogout = () => {
    const {authState, authData} = this.props;
    const greetings = new Greetings({
      authState,
      authData,
      onStateChange: this.handleAuthStateChange,
    });
    greetings.signOut();
  }

  signOut() {
    Auth.signOut()
        .then(() => { {this.changeState('signIn')}})
        .catch(err => { this.error(err)} );
  }
  constructor(props){
    super(props);
    //this._validAuthStates = ['signIn', 'signedOut', 'signedUp'];
    this._validAuthStates = ['signedIn'];
  }

  render(){
     return (
      <SafeAreaView>
        <ToolBar />
        <ScrollView style={styles.content}>
          <View style={[styles.container, styles.content]}>
            <TouchableHighlight style={[styles.buttonContainer, styles.taskButton]} onPress={() => this.onClickListener('Tasks')}>
              <Text style={styles.taskText}>Tasks</Text>
            </TouchableHighlight>
           ..
            <TouchableHighlight style={[styles.buttonContainer, styles.taskButton]} onPress={() => this.signOut()}>
              <Text style={styles.taskText}>Sign out</Text>
            </TouchableHighlight>
         </View>
        </ScrollView>
      </SafeAreaView>
     );
   }
  onClickListener = (viewId) => {
    Alert.alert("Alert", "Button pressed "+viewId);
  }

}

const styles = StyleSheet.create({
  content: {
    backgroundColor: '#ffffff',
    height: '100%'
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#DCDCDC'
  },
  buttonContainer: {
    height:45,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop:10,
    marginBottom: 10,
    width:350,
    borderRadius:30,
  },
  taskButton: {
    backgroundColor: '#1abc9c'
  },
  taskText: {
    color: 'white',
    fontWeight: 'bold'
  },
  signupText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold'
  },
});
```

**Comment by kfiras** [comment] 2019-04-11 22:01
Hi @powerful23, any help on the above please?

**Comment by powerful23** [comment] 2019-04-12 22:51
@kfiras can you try editing the following code:
```js
const RootStack = createStackNavigator(
  {
    Main: MainScreen,
    Customer: CustomerScreen,
    Reports: ReportsScreen,
    Signup: SignupScreen
  },
  {
    initialRouteName: 'Main',
  }
);

const AppContainer = createAppContainer(RootStack);

export class App extends React.Component {
  constructor(props) {
        super(props);

  }

  render() {
    return (
      <AppContainer onStateChange={this.props.onStateChange}/>
    );
  }
}

```

Because the root cause of this issue is that when you call `changeState` in your `MainScreen` component, the state is not transferred correctly to the `<SignInScreen/>` component.

**Comment by kfiras** [comment] 2019-04-13 00:47
Hi @powerful23 ,

I made these changes:
```
import React from 'react';
import { createStackNavigator, createAppContainer } from 'react-navigation';

import Amplify, { Auth } from 'aws-amplify';

import awsconfig from './aws-exports';

//window.LOG_LEVEL = 'DEBUG';

Amplify.configure(awsconfig);

import LoginScreen from './LoginScreen';
import MainScreen from './MainScreen';
import CrewsScreen from './CrewsScreen';
import CustomerScreen from './CustomerScreen';
import ReportsScreen from './ReportsScreen';
import SignupScreen from './SignupScreen';
import SignInScreen from './SignInScreen';

import {
    ConfirmSignIn,
    ConfirmSignUp,
    ForgotPassword,
    Greetings,
    RequireNewPassword,
    VerifyContact,
    withAuthenticator
} from 'aws-amplify-react-native';

const lawnicon = require('./icons/field.png');

const RootStack = createStackNavigator(
    {
        Login: LoginScreen,
        Main: MainScreen,
        Customer: CustomerScreen,
        Reports: ReportsScreen,
        Signup: SignupScreen
    },
    {
        initialRouteName: 'Main',
    }
);

const AppContainer = createAppContainer(RootStack);

export class App extends React.Component {
    constructor(props) {
        super(props);

    }
    render() {
        return (
            <AppContainer  onStateChange={this.props.onStateChange}/>
        );
    }
}

export default withAuthenticator(App, true, [
    <SignInScreen/>,
    <ConfirmSignIn/>,
    <VerifyContact/>,
    <SignupScreen/>,
    <ConfirmSignUp/>,
    <ForgotPassword/>,
    <RequireNewPassword />
]);
```
and this
```
import React, {Component} from 'react';

import {
    View,
    Image,
    ScrollView,
    SafeAreaView,
    StyleSheet,
    Text,
    TouchableHighlight,
    Alert
} from 'react-native';

import ToolBar from '../components/ToolBar';
import {Auth} from 'aws-amplify';
import {Greetings, AuthPiece} from 'aws-amplify-react-native';

export default class MainScreen extends Component {
    handleLogout = () => {
        const {authState, authData} = this.props;
        const greetings = new Greetings({
            authState,
            authData,
            onStateChange: this.handleAuthStateChange,
        });
        greetings.signOut();
        console.log('authState: ' + authState);
    }
    signOut() {
        const {authState, authData} = this.props;
        Auth.signOut()
            .then(() => {
                {
                    this.setState({authState: 'signIn', authData: null})
                    console.log('I am here')
                }
            })
            .catch(err => {
                this.error(err);
                console.log('error is :' + err);
            });
    }
    handleAuthStateChange(state, data) {
        this.setState({authState: state, authData: data});
    }

    constructor(props) {
        super(props);
        //this._validAuthStates = ['signIn', 'signedOut', 'signedUp'];
        this._validAuthStates = ['signedIn'];
    }

    render() {
            return (
                <SafeAreaView>
                    <ToolBar/>
                    <ScrollView style={styles.content}>
                        <View style={[styles.container, styles.content]}>
                            <TouchableHighlight style={[styles.buttonContainer, styles.taskButton]}
                                                onPress={() => this.onClickListener('Tasks')}>
                                <Text style={styles.taskText}>Tasks</Text>
                            </TouchableHighlight>
                            ...
                            <TouchableHighlight style={[styles.buttonContainer, styles.taskButton]}
                                                onPress={() => this.onClickListener('Admin')}>
                                <Text style={styles.taskText}>Admin</Text>
                            </TouchableHighlight>
                            <TouchableHighlight style={[styles.buttonContainer, styles.taskButton]}
                                                onPress={() => this.signOut()}>
                                <Text style={styles.taskText}>Sign out</Text>
                            </TouchableHighlight>
                        </View>
                    </ScrollView>
                </SafeAreaView>
            );
    }

    onClickListener = (viewId) => {
        Alert.alert("Alert", "Button pressed " + viewId);
    }

}

const styles = StyleSheet.create({
    content: {
        backgroundColor: '#ffffff',
        height: '100%'
    },
    container: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#DCDCDC'
    },
    buttonContainer: {
        height: 45,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
        width: 350,
        borderRadius: 30,
    },
    taskButton: {
        backgroundColor: '#1abc9c'
    },
    taskText: {
        color: 'white',
        fontWeight: 'bold'
    },
    signupText: {
        color: 'black',
        fontSize: 16,
        fontWeight: 'bold'
    },
});
```
If I cann signOut() in MainScreen, I got logged out as before but still same behavior, it never refreshes to SignIn screen. If I call handleLogout() I get warning 'can't call setState on a component that is not yet mounted. It also logs me out but same thing does not route to the SignInScreen.

Thanks and regards

**Comment by kfiras** [comment] 2019-04-13 13:41
what worked for me is this: [https://github.com/aws-amplify/amplify-js/issues/1876](url)

**Closed** 2019-04-13 13:42 UTC
Labels: React Native, bug
