### ISSUE TITLE
Empty error thrown for getAccessToken

### ISSUE THREAD

**Issue by akinzalowevidation** [aws-amplify/amplify-js#10127] opened 2022-07-28 16:54 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.36 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 88.0
    Safari: 15.5
  npmPackages:
    @babel/core: ^7.9.0 => 7.18.6 (7.12.0, 7.18.0, 7.18.9)
    @babel/runtime: ^7.9.0 => 7.18.6 (7.16.5, 7.12.0, 7.10.5, 7.18.0, 7.11.2)
    @bugsnag/plugin-react-navigation: ^7.13.2 => 7.17.0 
    @bugsnag/react-native: ^7.13.2 => 7.17.3 
    @bugsnag/source-maps: ^2.0.0 => 2.0.0 
    @react-native-community/async-storage: ^1.12.0 => 1.12.1 
    @react-native-community/clipboard: ^1.2.3 => 1.5.0 
    @react-native-community/netinfo: ^5.9.5 => 5.9.7 
    @react-native-cookies/cookies: ^6.2.1 => 6.2.1 
    @react-native-firebase/analytics: ^7.3.1 => 7.6.7 
    @react-native-firebase/app: ^8.2.0 => 8.4.5 
    @react-native-firebase/crashlytics: ^8.1.2 => 8.4.9 
    @react-native-masked-view/masked-view: ^0.2.6 => 0.2.6 
    @react-native-picker/picker: ^2.3.1 => 2.3.1 
    @react-navigation/bottom-tabs: ^6.0.9 => 6.0.9 
    @react-navigation/elements: ^1.2.1 => 1.2.1 
    @react-navigation/native: ^6.0.6 => 6.0.6 
    @react-navigation/stack: ^6.0.11 => 6.0.11 
    @testing-library/dom: ^7.12.0 => 7.26.0 (8.11.3)
    @testing-library/jest-dom: ^5.9.0 => 5.11.4 
    @testing-library/react: ^11.0.0 => 11.1.0 (12.1.3)
    @testing-library/react-native: ^7.0.2 => 7.0.2 
    @types/i18n-js: ^3.0.3 => 3.0.3 
    @types/jest: ^26.0.0 => 26.0.14 
    @types/node: ^13.7.4 => 13.13.15 (14.14.37, 14.11.8, 13.13.48)
    @types/react-dom: ^16.9.8 => 17.0.17 (17.0.13)
    @types/react-native: ^0.63.2 => 0.68.2 (0.63.25)
    @types/react-native-snap-carousel: ^3.8.1 => 3.8.2 
    @types/react-native-video: ^5.0.13 => 5.0.13 
    @types/react-query: ^1.1.2 => 1.1.2 
    @types/react-test-renderer: 16.9.2 => 17.0.2 (17.0.1)
    @types/styled-components: ^5.1.0 => 5.1.3 
    @types/yup: ^0.29.2 => 0.29.4 
    @typescript-eslint/eslint-plugin: ^4.8.1 => 4.8.1 (4.29.3)
    @typescript-eslint/parser: ^3.7.1 => 3.8.0 (4.29.3)
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: 5.2.3 => 5.2.10 (5.2.3)
    babel-jest: ^26.1.0 => 26.5.2 (26.6.0)
    date-fns: ^2.14.0 => 2.16.1 (2.21.1)
    detox: ^17.10.3 => 17.10.3 
    eslint: ^7.5.0 => 7.6.0 (7.32.0)
    eslint-plugin-flowtype: ^5.9.1 => 5.9.1 
    eslint-plugin-import: ^2.24.2 => 2.24.2 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-react: ^7.25.1 => 7.25.1 (7.24.0)
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    example:  0.0.1 
    expo-localization: ^9.0.0 => 13.0.0 
    firebase-tools: ^9.8.0 => 9.8.0 
    firepit:  1.1.0 
    formik: ^2.2.6 => 2.2.6 
    hermes-inspector-msggen:  1.0.0 
    husky: ^4.2.5 => 4.3.0 
    i18n-js: ^3.5.1 => 3.7.1 
    jest: ^26.6.0 => 26.6.0 
    jest-circus: ^26.6.0 => 26.6.0 
    jest-fetch-mock: ^3.0.3 => 3.0.3 
    jest-styled-components: ^7.0.2 => 7.0.3 
    json-schema-yup-transformer: ^1.5.9 => 1.5.9 
    lottie-react-native: ^4.0.3 => 5.1.3 
    metro-react-native-babel-preset: ^0.61.0 => 0.71.3 (0.67.0)
    msw: ^0.21.2 => 0.21.3 
    path: ^0.12.7 => 0.12.7 
    prettier: ^2.6.0 => 2.6.0 
    pretty-quick: ^3.1.0 => 3.1.0 
    query-string: ^6.12.0 => 6.13.5 (7.1.0)
    react: 16.13.1 => 17.0.2 
    react-dom: 16.13.1 => 17.0.2 
    react-native: 0.63.4 => 0.68.2 
    react-native-date-picker: ^4.2.0 => 4.2.0 
    react-native-default-preference: ^1.4.3 => 1.4.3 
    react-native-device-info: ^6.2.0 => 6.2.0 
    react-native-fbsdk: ^3.0.0 => 3.0.0 
    react-native-gesture-handler: ^1.10.3 => 1.10.3
    react-native-inappbrowser-reborn: ^3.6.0 => 3.6.3 
    react-native-keyboard-aware-scroll-view: ^0.9.5 => 0.9.5 
    react-native-kochava-tracker: ^1.4.2 => 1.5.1 
    react-native-linear-gradient: ^2.5.6 => 2.5.6 
    react-native-mmkv: ^2.4.3 => 2.4.3 
    react-native-reanimated: ^1.8.0 => 1.13.4 
    react-native-safe-area-context: ^3.3.2 => 3.3.2 
    react-native-screens: ^3.10.1 => 3.10.1 
    react-native-sensitive-info: ^6.0.0-alpha.6 => 6.0.0-alpha.9 
    react-native-snap-carousel: ^4.0.0-beta.6 => 4.0.0-beta.6 
    react-native-svg: ^12.1.1 => 12.1.1 
    react-native-url-polyfill: ^1.2.0 => 1.2.0 
    react-native-video: ^5.2.0 => 5.2.0 
    react-native-webview: ^11.0.0 => 11.22.7 
    react-query: ^2.23.1 => 2.23.1 (3.34.16)
    react-test-renderer: ^16.14.0 => 17.0.2 
    styled-components: ^5.1.0 => 5.2.0 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    typescript: ^4.6.3 => 4.6.4 (4.4.2)
    urbanairship-react-native: ^9.0.0 => 9.0.0 
    victory-native: ^35.3.1 => 35.3.1 
    yup: ^0.32.9 => 0.32.9 (0.29.3)
  npmGlobalPackages:
    bit-bin: 14.8.8
    corepack: 0.10.0
    eas-cli: 0.47.0
    eslint: 7.19.0
    expo-cli: 5.4.3
    npm: 8.11.0
    prettier: 2.4.1
    react-devtools: 4.10.4
    yarn: 1.22.17

```

</details>

### Describe the bug

We are seeing a number of users get an error thrown from the following code snippet that is just an empty object (`{}`):

```javascript
import { Auth } from "@aws-amplify/auth";

...

try {
  const session = await Auth.currentSession();
  return session.getAccessToken().getJwtToken();
} catch (error) {
  // error is {}
}
```

### Expected behavior

A more meaningful error is returned. Is this error supposed to mean that no access token or user is found? If so, what is the difference between this error being returned and "No current user"?

### Reproduction steps

We are currently unsure how to reproduce it.

### Code Snippet

```javascript
import { Auth } from "@aws-amplify/auth";

...

try {
  const session = await Auth.currentSession();
  return session.getAccessToken().getJwtToken();
} catch (error) {
  // error is {}
}
```

### Mobile Device

iPhone X (CDMA) (iPhone10,3)

### Mobile Operating System

iOS15.5

**Comment by nadetastic** [comment] 2022-08-04 20:02
Hi @akinzalowevidation 👋,

I haven't been able to replicate this issue on my end, and I understand that it's also hard to replicate it as it seems to occur sporadically?

One thing I'm curious on is if this is happening with `Auth.currentSession()` or when you try to get the tokens. With `Auth.currentSession()` it should return some sort of error:
 
ex: No current user
https://github.com/aws-amplify/amplify-js/blob/360bde20716778b69af339f4f66b42c05ccf4639/packages/auth/src/Auth.ts#L1625-L1629

Would it be possible to test and see if `session` contains any data from `const session = await Auth.currentSession();
` before calling `session.getAccessToken().getJwtToken();` when the empty error happens?

**Comment by akinzalowevidation** [comment] 2022-08-18 17:34
Thanks @nadetastic, we've split up our function containing this snippet and will log the errors of both. I will report the results. Thanks!

**Comment by tannerabread** [comment] 2022-10-07 16:49
:wave: @akinzalowevidation Have you found anything since your last update?

**Comment by akinzalowevidation** [comment] 2022-10-07 16:58
> 👋 @akinzalowevidation Have you found anything since your last update?

Hi @tannerabread we are still following this but have made one observation:
We recently switched from `react-native-secure-storage` to `react-native-mmkv` for token storage (for the `storage` configuration option) and noticed a large decrease in the amount of `{}` thrown errors. We still see them occasionally. 

We did split up our logging for `Auth.currentSession` and `session.getAccessToken().getJwtToken()` but we are seeing the `{}` error thrown in _both_ functions.

**Comment by nadetastic** [comment] 2023-01-24 00:43
Hi @akinzalowevidation - following up on this

Any additional information? Were you able to get this resolved?

**Comment by akinzalowevidation** [comment] 2023-01-26 13:53
@nadetastic We are still experiencing this problem, but I do have an update:

Here is how we are now obtaining an access token in production:

```
import { Auth } from "@aws-amplify/auth";

export const getSession = async (source: string) => {
  try {
    const session = await Auth.currentSession();
    return session;
  } catch (error) {
    if (error !== CognitoError.NoCurrentUser) {
      Logger?.warn(
        `[getSession][source=${source}] failed to retrieve Cognito session: ${JSON.stringify(
          error
        )}`
      );
    }
    throw error;
  }
};

export const getAccessToken = async (source: string) => {
  try {
    const session = await getSession(source);
    return session.getAccessToken().getJwtToken();
  } catch (error) {
    if (error !== CognitoError.NoCurrentUser) {
      Logger?.warn(
        `[getAccessToken][source=${source}] failed to retrieve Cognito access token: ${JSON.stringify(
          error
        )}`
      );
    }
    throw error;
  }
};
```

Here is the logs sent in the error tracking for when we get the `{}` Cognito error:
```
[getSession][source=Authentication] failed to retrieve Cognito session: {}
```

So it does appear to be throwing from the initial `Auth.currentSession` call. Hopefully this helps.

**Comment by cwomack** [comment] 2023-05-23 19:52
Possibly related to #11156.  

@akinzalowevidation can you confirm what version of Amplify you were on?

**Comment by nadetastic** [comment] 2023-06-21 17:14
Hi @akinzalowevidation following up here - i'm still not able to reproduce this issue. Hoping for any additional information on what has been going on for you.

**Comment by nadetastic** [comment] 2023-06-29 21:29
Hi @akinzalowevidation I'll go ahead and close this issue out. If you are still having this issue please let me know and I can re-open to discuss further.

**Closed by nadetastic** 2023-06-29 21:29 UTC
Labels: question, investigating, Auth, React Native, not-reproducible, pending-response, Expo
