### ISSUE TITLE
Cant call rest api from getserversideprops

### ISSUE THREAD

**Issue by didemkkaslan** [aws-amplify/amplify-js#13124] opened 2024-03-15 06:52 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

REST API

### Amplify Version

v6

### Amplify Categories

api

### Backend

CDK

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I'm getting unauthorized error trying to access rest api endpoints using getServerSideProps  in a NextJS app(pages router).

### Expected behavior

It shouldnt be unauthorized

### Reproduction steps
```js
  const user = await runWithAmplifyServerContext({
    nextServerContext: { request: ctx.req, response: ctx.res },
    operation: async (contextSpec) =>
      get({
        apiName: APINames.PlatformCoreRestApi,
        path: '/people/me',
        options: {
          headers: {
            Authorization: `Bearer ${contextSpec.token.value.toString()}`,
          },
        },
      }),
  });
```
### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment] 2024-03-15 19:23
@didemkkaslan, it looks like this is a duplicate of issue #13125 that you also opened.  I'll close this one and follow up there, but let me know if this needs to be reopened.

**Closed by cwomack** 2024-03-15 19:23 UTC
Labels: duplicate, question, API-REST
