### ISSUE TITLE
Can't change Federated Button text in Ionic/Angular application

### ISSUE THREAD

**Issue by Sathyapriyad** [aws-amplify/amplify-js#7626] opened 2021-01-27 05:33 UTC
We are using Amplify framework with javascript (angular/ionic).
We have two kinds of login - hosted UI and SAML based authentication (Federal login).

We are able to use the Federated signin calls and could get authenticated but the UI page has a Federated button (with text as Signin with AWS).
We wanted to change  that text to say as (Signin with Microsoft365)

We made the relevant change in the  code to change the Federated button  text.
When we added federated-button slot with button,  the change didn't show in the sign in page (But that element shows in DOM).

Sample Code
---------------------
**app.component.html**
`<amplify-authenticator usernameAlias="email">
    <amplify-sign-in id="auth" usernameAlias="email" slot="sign-in">
      <amplify-sign-in-button slot="federated-buttons" (click)="federatedSignIn()">
        This is the custom text
      </amplify-sign-in-button>
    </amplify-sign-in>
    <ion-app>
      <ion-router-outlet></ion-router-outlet>
    </ion-app>
</amplify-authenticator>`

**app.component.ts**
`federatedSignIn(){
	Auth.federatedSignIn();
}`

When I used the <amplify-sign-in-button slot=“federated-buttons”> instead of overriding the component already present with text “Sign In with AWS” it created a new html tag within the <amplify-authenticator>. Please refer to the attached image ionic.png for the DOM this application rendered. 

<img width="663" alt="ionic" src="https://user-images.githubusercontent.com/67996587/105946857-09256400-608e-11eb-85ea-80dcb97aa901.png">

**Comment by wlee221** [comment] 2021-02-11 17:22
Hi @Sathyapriyad, thanks for reporting this issue! I was unable to reproduce your issue however. Here's my [repro](https://github.com/wlee221/amplify-js-issues-repro/tree/main/samples/ionic/7626-federated-buttons):

- [app.component.html](https://github.com/wlee221/amplify-js-issues-repro/blob/main/samples/ionic/7626-federated-buttons/src/app/app.component.html)
- [app.component.ts](https://github.com/wlee221/amplify-js-issues-repro/blob/main/samples/ionic/7626-federated-buttons/src/app/app.component.ts)

Please try to look for possible discrepancy between our files. Looking at your screenshot, it's alarming that your `"federated-buttons"` slot is actually an empty `div`:

```jsx
<div _ngcontent-hgs-c185 slot="federated-buttons"></div> // this shouldn't be an empty div
```

This should be your `amplify-sign-in-button` according to your `html` file. This also explains why you don't see the overridden content. Can you double check your `html`? (Or even try directly pasting my html file into yours)

**Comment by Sathyapriyad** [comment] 2021-02-12 04:59
I tried your code in my html file. But still i can't change federated button text name.
Below is the code i tried. "This is the custom text" button name is displayed in the DOM but didn't displayed in the screen.

`<amplify-authenticator usernameAlias="email">
	<amplify-sign-in id="auth" usernameAlias="email" slot="sign-in">
		<amplify-sign-in-button
			slot="federated-buttons"
			(click)="federatedSignIn()"
		>
			This is the custom text
		</amplify-sign-in-button>
	</amplify-sign-in>
	<ion-app>
		<ion-router-outlet></ion-router-outlet>
	</ion-app>
</amplify-authenticator>`

![federated](https://user-images.githubusercontent.com/67996587/107731741-b6e67300-6d1c-11eb-9ec0-3050e04862da.png)

**Comment by wlee221** [comment] 2021-02-12 15:09
That is indeed interesting. Can you provide us a sample reproduction repo so we can investigate further?

**Comment by wlee221** [comment] 2021-02-15 19:28
Follow-up: I received a repro repo on https://github.com/madaboutaws/angular-reproduce.

I was able to get this work with a minor tweak: __app.component.html__

```diff
<amplify-authenticator>
-  <div>
    <amplify-sign-in slot="sign-in" >
      <amplify-sign-in-button slot="federated-buttons">This is a new button</amplify-sign-in-button>
    </amplify-sign-in>
-  </div>
</amplify-authenticator>
```

There shouldn't be an empty parent div within `amplify-authenticator`. 

Working Screenshot:
![Screen Shot 2021-02-15 at 11 22 08 AM](https://user-images.githubusercontent.com/43682783/107986037-155f5b80-6f80-11eb-9ff2-d61736269453.png)

**Comment by wlee221** [comment] 2021-02-15 19:42
If this is **not** working:

I was able to reproduce it in my and the provided reproduction app, so I think this is something on the local end. Let's get on the same page by calling `Amplify.configure` with an empty object:

_app.module.ts_
```diff
- import awsconfig from "../aws-exports";
- Amplify.configure(awsconfig);
+ Amplify.configure({});
```
so that we can focus on the visual side first before we configure Amplify. (Your authenticator should not work, but it should be fully rendered and visible). Do you still see no changes in your app?

**Comment by Sathyapriyad** [comment] 2021-02-17 05:07
I created the new ionic/angular app with latest version of aws-amplify and @aws-amplify/ui-angular. That's working fine.
Need to check why not working in our existing application

**Comment by wlee221** [comment] 2021-02-17 19:47
Good to know it's working! I'm suspecting https://github.com/aws-amplify/amplify-js/pull/7522 may have fixed it indirectly. I'll be closing this issue as the latest version has been working for you. Please let us know if you have additional concerns.

**Closed** 2021-02-17 19:47 UTC
Labels: Amplify UI Components, Angular, Can't reproduce
