### ISSUE TITLE
Auth.setupTOTP - Invalid session for the user

### ISSUE THREAD

**Issue by mkpratt** [aws-amplify/amplify-js#6461] opened 2020-07-30 21:02 UTC
**Describe the bug**
I set up Amplify with Cognito authentication with SMS MFA enabled. I have configured my own UI to provide the credentials and it used to work just fine. However, the SMS text messages suddenly stopped being delivered. I could tell the messages were trying to be sent. CloudWatch had the errors logged and said "Phone is currently unreachable/unavailable." In all the research I've done, I haven't been able to find a reason why. Increased spending limits did not solve the problem. I encountered another issue that sounded similar [#5137] and although it wasn't technically resolved I decided to implement the workaround from that issue. 

The workaround was to implement TOTP MFA. However, I am unable to get it to work. Every time 
```
Auth.setupTOTP(user)
```
is called, I get this error:
```
{code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Invalid session for the user."}
``` 
This is the `CognitoUser`  object returned from the sign in method provided by Amplify:
```
{
  Session: "xxxxxx"
  authenticationFlowType: "USER_SRP_AUTH"
  challengeName: "SMS_MFA"
  challengeParam: {CODE_DELIVERY_DELIVERY_MEDIUM: "SMS", CODE_DELIVERY_DESTINATION: "+*******9088"}
  client: Client {endpoint: "https://cognito-idp.us-west-2.amazonaws.com/", userAgent: "aws-amplify/0.1.x js"}
  keyPrefix: "CognitoIdentityServiceProvider.xxx"
  pool: CognitoUserPool {userPoolId: "us-west-2_xxx", clientId: "xxx", client: Client, advancedSecurityDataCollectionFlag: true, storage: Storage}
  signInUserSession: null
  storage: Storage {aws.cognito.identity-id.us-west-2:xxx: "us-west-2:xxx", aws.cognito.identity-id.us-west-2:xxx: "us-west-2:xxx", CognitoIdentityId-us-west-2:xxx: "us-west-2:xxx", CognitoIdentityId-us-west-2:xxx: "us-west-2:xxx", length: 4}
  userDataKey: "CognitoIdentityServiceProvider.xxx.michael.userData"
  username: "michael"
}
```

The `Session` variable has a value, but the `signInUserSession` variable is null. I assume the `signInUserSession` being null is the reason why this isn't working.

**To Reproduce**

1. Configure app via amplify cli to have MFA (TOTP) required
2. Sign up a new user (confirm email and everything)
3. Sign in newly created user using `Auth.signIn`
4. Attempt to set up MFA TOTP via `Auth.setupTOTP` with the `user` object returned from the sign in method

**Expected behavior**
```Auth.setupTOTP(user)``` would accept the user object returned from the ```Auth.signIn(username, password)``` method to allow MFA TOTP to be configured. With this, the setupMFA method would return a code to generate a QR code for end user to configure their Authenticator application.

**Comment by amhinson** [comment] 2020-10-19 19:24
@mkpratt Are you still seeing this behavior?

**Comment by austinhinderer** [comment] 2020-11-12 23:18
I'm currently seeing this issue.

**Comment by mkpratt** [comment] 2020-11-12 23:25
@amhinson I had to pivot back to using SMS MFA instead of TOTP to keep my project moving forward, but I assume if I were the revisit the issue I would still see this behavior.

**Comment by amhinson** [comment] 2020-11-12 23:26
Ok thanks for the update! We will look further into this issue and respond back here with any updates

**Comment by austinhinderer** [comment] 2020-11-13 00:07
I have confirmed I can reproduce this issue with 2 different users, 1 in a pre "create new password" state, and 1 that has set a user password and registered SMS 2fa.

**Comment by Jsunny271** [comment] 2021-03-19 07:19
Anyone resolved this issue?

**Comment by krayray2020** [comment] 2021-04-02 11:13
After doing Auth.setupTOTP you have to verify the TOTP

**Auth.setupTOTP**(user).then((code) => {
            // You can directly display the `code` to the user or convert it to a QR code to be scanned.
            console.log('set up totp code? ' + code) 
            // E.g., use following code sample to render a QR code with `qrcode.react` component:  
            //      import QRCode from 'qrcode.react';
            //      const str = "otpauth://totp/AWSCognito:"+ username + "?secret=" + code + "&issuer=" + issuer;
            //      <QRCode value={str}/>

            // Enter this code into the phone app to connect the phone app to your application
            //Then you want to send the code from the phone application (authy, google authenticator etc) to Auth.verifyTotpToken
            var challengeAnswer = prompt('Please input verification code: ' ,'')
            **Auth.verifyTotpToken**(user, challengeAnswer).then(() => {

                // don't forget to set TOTP as the preferred MFA method
                **Auth.setPreferredMFA**(user, 'TOTP');
                console.log('Success?')
            }).catch( e => {
                console.log('Token is not verified')
            });

            }).catch((error) => {
                console.log(error)
            })

**Comment by crenacer** [comment] 2021-04-26 18:23
I'm having the same issue now. The code I use:

```
const verifyTOTP = async() => {
  const user = await Auth.signIn(verifyTOTPRequest.login, verifyTOTPRequest.password);
  const verificationResult = await Auth.verifyTotpToken(user, verifyTOTPRequest.answer);
}
```

This sends following payload to the Cognito:
```
{ "Session":"my session string from Auth.signIn()","UserCode":"413059","FriendlyDeviceName":"My TOTP device" }
```

And error is 
```
{ code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Invalid session for the user." }
```

**Comment by apolegoshko** [comment] 2021-04-28 20:03
Just wanna confirm that following workflow works: initiateAuth -> associcateSoftwareToken -> VerifySoftwareToken -> RespondToAuthChallenge.

**Comment by crenacer** [comment] 2021-04-29 11:58
@apolegoshko Just tested it and still getting the same issue. I guess that's somehow related to pool settings and its API doesn't return appropriate error and always "Invalid session for the user.". 
My flow is (I'm using amazon-cognito-identity-js. MFA is required in the pool and only TOTP enabled): 
1. Create new user, set email and phone, don't send any verification email
2. Call to cognitoUser.authenticateUser -> you get `NEW_PASSWORD_REQUIRED` challenge

NEW_PASSWORD_REQUIRED challenge:
3. Call cognitoUser.authenticateUser again to store `Session` inside
4. Call to cognitoUser.completeNewPasswordChallenge -> password changed and next challenge is MFA_SETUP with MFAS_CAN_SETUP: [SOFTWARE_TOKEN_MFA]

MFA_SETUP challenge:
4. Call cognitoUser.authenticateUser again to store `Session` inside
5. Call to cognitoUser.associateSoftwareToken to get code and use as part of url for QR code
6. Scan this QR code to add an account to your Authenticator app
7. Call cognitoUser.authenticateUser again to store `Session` inside
8. Call to cognitoUser.verifySoftwareToken to get session for finishing MFA_SETUP sign_in challenge <- here is where the error happens. 

Upon sending VerifySoftwareToken request with `Session` obtained from authenticateUser to AWS Cognito API it [throws](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L2078) that error `{ code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Invalid session for the user." }`. It doesn't even reach RespondToAuthChallenge.

As for me, this is super weird behavior

**Comment by apolegoshko** [comment] 2021-04-29 12:45
Hey @crenacer Initially, I receive the same error, but important thing here, is that you have to follow such approach:

MFA_SETUP : For users who are required to setup an MFA factor before they can sign-in. The MFA types enabled for the user pool will be listed in the challenge parameters MFA_CAN_SETUP value. To setup software token MFA, use the session returned here from InitiateAuth as an input to AssociateSoftwareToken , and use the session returned by VerifySoftwareToken as an input to RespondToAuthChallenge with challenge name MFA_SETUP to complete sign-in.

Session token are different between associateSoftwareToken, verifySoftwareToken, RespondToAuthChallenge steps. 

Please let me know, if it helped.

**Comment by crenacer** [comment] 2021-04-29 12:51
@apolegoshko , thanks for the response. 
> Session token are different between associateSoftwareToken, verifySoftwareToken, RespondToAuthChallenge steps.
I do use the different ones, see step 7, it's executed in different server route in different request.

> and use the session returned by VerifySoftwareToken as an input to RespondToAuthChallenge
Issue is that VerifySoftwareToken itself returns an error

**Comment by apolegoshko** [comment] 2021-04-30 15:02
@crenacer which session do you pass to VerifySoftwareToken ? I'm not js person, but here is a snippet from my golang implementation:

```
....
// step 1
		initiateParams := &cognitoidentityprovider.InitiateAuthInput{
			ClientId:       &client_id,
			AuthFlow:       "USER_PASSWORD_AUTH",
			AuthParameters: AuthParameters, // Auth params contains username, password, secret_hash
		}
		initiateResponse, err := cognitoClient.InitiateAuth(ctx, initiateParams)
....
// step 2
		associateParams := &cognitoidentityprovider.AssociateSoftwareTokenInput{
			Session: initiateResponse.Session, // session from step 1
		}
		associateResponse, err := cognitoClient.AssociateSoftwareToken(ctx, associateParams)
....
// step 3

		vParams := &cognitoidentityprovider.VerifySoftwareTokenInput{
			Session:  &associateResponse.Session, // Token here from AssociateSoftwareToken method (session from step 2)
			UserCode: &t.Code, // Code from MFA app from User side
		}
...
// step4
		respondParams := &cognitoidentityprovider.RespondToAuthChallengeInput{
			Session:       v.Session, // session from step 3
			ClientId:      &client_id,
			ChallengeName: "MFA_SETUP",
			ChallengeResponses: map[string]string{
				"USERNAME":    t.Username,
				"SECRET_HASH": c,
			},
		}
                _, err = a.RespondToAuthChallenge(ctx, respondParams)
``` 

This is working.

**Comment by crenacer** [comment] 2021-05-03 07:40
@apolegoshko As I can see you use USER_PASSWORD_AUTH which is deprecated, I am using SRP Auth. Anyway what I'm telling is that it is something in cognito settings, not in the library itself. For example, do you have MFA selected as "required" and not "optional" for your user pool?

**Comment by apolegoshko** [comment] 2021-05-03 08:39
Hey @crenacer, definitely yes, MFA is selected as required. Could you please send me the link to deprecation notice ?

**Comment by crenacer** [comment] 2021-05-03 09:46
Hey @apolegoshko sorry, I can't find exact words. I just understood this from documentation that it'll execute AWS "user migration" lambda if set

**Comment by apolegoshko** [comment] 2021-05-03 10:27
> UPD: maybe there's an issue with it when MFA required & SRP sign-in used

Looks like it requires additional investigation.

**Comment by crenacer** [comment] 2021-05-03 10:53
> > UPD: maybe there's an issue with it when MFA required & SRP sign-in used
> 
> Looks like it requires additional investigation.

Yep, that's why I'm writing here after reading library code and trying different scenarios. So far I've left MFA as optional and "emulate" cognito behavior returning MFA_SETUP challenge on login/completeNewPassword calls if not set for user. Maybe it'll help somebody

**Comment by chrisbonifacio** [comment] 2021-05-04 18:02
Hello 👋 I'm currently working to reproduce this issue consistently so that we can work towards a resolution. If you are still experiencing this issue, please comment with your package.json or amplify packages and versions in your project.

**Comment by chrisbonifacio** [comment] 2021-05-04 21:02
Actually, I just noticed that in your attempt to sign in you are getting a "SMS_MFA" challenge when, I think, you should be getting the "MFA_SETUP" challenge which is when you would want to call `Auth.setupTOTP`.

If you look at the [Advanced Use Cases](https://docs.amplify.aws/lib/auth/mfa/q/platform/js#advanced-use-cases) section of the docs, it shows the intended flow for the MFA challenges. 

So, with the "SMS_MFA" challenge you're getting, this is what is expected to happen according to the docs

```js
 const user = await Auth.signIn(username, password);
        if (user.challengeName === 'SMS_MFA' ||
            user.challengeName === 'SOFTWARE_TOKEN_MFA') {
            // You need to get the code from the UI inputs
            // and then trigger the following function with a button click
            const code = getCodeFromUserInput();
            // If MFA is enabled, sign-in should be confirmed with the confirmation code
            const loggedUser = await Auth.confirmSignIn(
                user,   // Return object from Auth.signIn()
                code,   // Confirmation code  
                mfaType // MFA Type e.g. SMS_MFA, SOFTWARE_TOKEN_MFA
            );
```

The problem being, the code is not being sent even though it's showing in the `Auth.signIn` response that the code should have already been delivered, as you can see the delivery info in the `challengeParams` property

<img width="381" alt="Screen Shot 2021-05-04 at 4 53 05 PM" src="https://user-images.githubusercontent.com/16952986/117068376-34f15f00-acf9-11eb-9247-e85dfa2e1aad.png">

This might explain why the session is invalid.

This is what happens when I call `Auth.confirmSignIn` with an invalid code. The user session seems to be accepted just fine but the code is the issue.

<img width="994" alt="Screen Shot 2021-05-04 at 5 01 06 PM" src="https://user-images.githubusercontent.com/16952986/117069308-53a42580-acfa-11eb-9f8b-41ed62eb0099.png">

**Comment by chrisbonifacio** [comment] 2021-05-10 22:40
The more I've been working with MFA issues, the more I'm convinced this is not a bug.

Update on my previous comment: The reason I wasn't getting SMS codes was due to my particular type of aws account. So that wasn't the issue.

However, I have been able to use both SMS and TOTP to go through the whole MFA flow from end to end. This error only seems to occur when you attempt to perform an action like `Auth.setupTOTP` when the current user's auth challenge does not call for it. Perhaps we could provide better/more useful error messages in these instances.

Please watch out for the `challengeName` property in the CognitoUser returned from `Auth.signIn` and call the appropriate methods to address the challenge.

`Auth.signIn` user --> "MFA_SETUP" Challenge --> `Auth.setupTOTP(user)` --> `Auth.verifyTotpToken(user, token)` --> Authenticated

`Auth.signIn` user --> "SMS_MFA" or "SOFTWARE_TOKEN_MFA" Challenge --> `Auth.ConfirmSignIn(user, code, mfaType)` --> Authenticated

I did not change the CognitoUser or session between any of the steps, kept and used the same `user` from the original `Auth.signIn` call for each flow.

**Comment by chrisbonifacio** [comment] 2021-05-18 16:01
> Hi @chrisbonifacio , thank you for investigation. Let me try to reproduce it with amazon-cognito-identity-js as I'm using it on my backend.

I hope things are going well! Let me know if you've been able to get past this issue yet.

**Comment by crenacer** [comment] 2021-05-18 16:28
Hi @chrisbonifacio , I've used `@aws-sdk/client-cognito-identity-provider` with the same flow proposed by you and still getting this `Invalid session for the user.` in the same way as I did with Amplify.

Everything was good unless I call to VerifySoftwareToken using `Session` returned from InitAuth that is requiring "MFA_SETUP" challenge. I know it's not an Amplify's issue. Shall I report the issue in the `aws-sdk` repo or you can help me somehow?

**Comment by chrisbonifacio** [comment] 2021-05-19 19:58
Yeah, opening an issue on the sdk repo should help to get a second look/opinion on what might be going on here. You can link them to this issue as well so they can get the context from our conversation.

I'll close this issue for now since it doesn't seem actionable on our side.

**Closed by chrisbonifacio** 2021-05-19 19:58 UTC
Labels: Auth, MFA

**Comment by steven87vt** [comment] 2021-09-15 13:09
this topic helped clarify the TOTP MFA registration process for me so thank you for that. 

>Just wanna confirm that following workflow works: initiateAuth -> associcateSoftwareToken -> VerifySoftwareToken -> RespondToAuthChallenge.

> One thing to note: If even after associating a token with a user you are getting "Invalid User Session", maybe because the user left the app or the session timed out for whatever reason, you just need to let the user generate another token.

for anyone else in a similar situation: 

1. not having time or scope to create a custom UI to process a MFA TOTP for a user registration.
2. frustrated with cognito hosted ui not having this feature by default in the standard workflow.
3. no plans to integrate cognito into your already running and validated authentication system.
4. simply want to MFA auth some alb routes to guard 3rd party tools (like traefik dashboard).

you can hack apart the below (hacks) to fit your needs. in our case we are using cognito to secure alb traffic to a 3rd party app dashboard (traefik) and basic auth just wont side on the security side. 

using a python script for secret_hash (because we have app_client secret) and a bash script to init/verify i was able to register MFA. the below is given without warranty and your mileage may very :)

the trick is getting the output of the bash script into the MFA generator quickly enough to confirm a response before the session ends. if your set up in advance you can copy/paste it + send it to your phone for quick access to enter into google authenticator. you can use any (hopefully more secure) means of doing this then say text message or email.

the starting point for these scripts came from (credits):

1. [python - aws white paper](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-unable-to-verify-secret-hash/)
2. [bash - SO gist link](https://gist.github.com/Can-Sahin/377fee56a53a0a31bf9e5ce7f9847ac2)

`secrethash.py`
```python
import sys
import hmac, hashlib, base64

username = sys.argv[1]
app_client_id = sys.argv[2]
app_client_secret = sys.argv[3]

if (username is None):
  raise Error('username required')

if (app_client_id is None):
  raise Error('app client id required')

if (app_client_secret is None):
  raise Error('app client secret required')

message = bytes(sys.argv[1]+sys.argv[2],'utf-8')
app_client_secret = bytes(sys.argv[3],'utf-8')
secret_hash = base64.b64encode(hmac.new(app_client_secret, message, digestmod=hashlib.sha256).digest()).decode()

print("SECRET HASH:",secret_hash)
```

`initauth.sh`
```bash
#!/bin/bash

export AWS_PROFILE="<add your profile here>"
debug=false #set to true if you need to see additional output

username="$1"
password="$2"
clientid="$3"
secretHash="$4"
twoFactCode="$5"

callHelp=false
[[ -z \
"${username}" || -z \
"${password}" || -z \
"${clientid}" || -z \
"${secretHash}" ]] &&
  callHelp=true

if [ "${callHelp}" == true ]; then
  cat <<-EOF
  initauth.sh
    First run attempts to establish a MFA secret which you can use to configure a MFA TOTP device.
    Second run requires all the same parameters and also the MFA two factor token to use for verification.

    Once the above two steps are complete you can log in using cognito default hosted UI via TOTP MFA.

    Note: this is set up for app clients with secret keys which require SECRET_HASH variable in the api calls.
    Requires environment parameters:
      1: username, value: '${username}' - the username (not email) of the cognito user
      2: password, value: '${password}' - the user's password
      3: clientid, value: '${clientid}' - the app client id
      4: secretHash, value: '${secretHash}' - the secret key generated in a previous step (see secrethash.py)

    Second run additional parameters:
      5: twoFactCode, value: '${twoFactCode}' - the 6 digit code generated by your authenticator app (google authenticator in my case)
EOF

  exit 1
fi

response=""
if [ -z "${twoFactCode}" ]; then
  response=$(aws cognito-idp initiate-auth --auth-flow USER_PASSWORD_AUTH --client-id $clientid --auth-parameters USERNAME=$username,PASSWORD=$password,SECRET_HASH=$secretHash)
  cName=$(echo "${response}" | jq .ChallengeName | xargs)

  if [ "${debug}" == "true" ]; then
    echo "Response: ${response}"
    echo "ChallengeName: ${cName}"
  fi

  if [ "${cName}" == "MFA_SETUP" ]; then
    session=$(echo "${response}" | jq .Session | xargs)
    tokenResponse=$(aws cognito-idp associate-software-token --session "${session}")
    session=$(echo "${tokenResponse}" | jq .Session | xargs)
    secret=$(echo "${tokenResponse}" | jq .SecretCode | xargs)

    echo
    echo "Token Response: ${tokenResponse}"
    echo "If everything Worked You need to enter this value into google authenticator manually: ${secret}"
    echo
    echo "Once your done & your app is generating two fact codes you will need to execute the script again with the following parameters followed by your new two fact code: ./initauth.sh ${username} ${password} ${clientid} ${session} yourTwoFactCodeHere"
  fi
else
  echo "Attempting Two Factor Verification"

  response=$(aws cognito-idp verify-software-token --session "${secretHash}" --user-code "${twoFactCode}" --friendly-device-name "${username} authenticator app")
  isSuccess=$(echo "${response}" | jq .Status | xargs)

  if [ "${debug}" == "true" ]; then
    echo "Response: ${response}"
    echo "isSuccess: ${isSuccess}"
  fi

  if [ "${isSuccess}" == "SUCCESS" ]; then
    echo "Success code indicated in response. Try to log into cognito, if logged in previously use the logout url to trigger a logout first to expire an old session."
    return 0
  fi
fi
```
