### ISSUE TITLE
Angular Signup Component doesn't handle datetime attributes correctly

### ISSUE THREAD

**Issue by scottjbaldwin** [aws-amplify/amplify-js#2484] opened 2019-01-07 11:00 UTC
**Describe the bug**
When birthdate (or any other datetime type) is added as a SignupField to the amplify-authenticator control in angular, the only option is to type in the input in the expected format for the cognito api request, i.e. YYYY-MM-DD. Any other date time format is rejected.

**To Reproduce**
1. Create an AWS cognito User Pool with birthdate as a required attribute
2. Create an Angular app with an amplify-authenticator that points to this user pool, and add birthdate as a SignUpField
3. Open the app and attempt to Sign Up a new user
4. Enter a human readable date format like... '03-AUG-1973' into the field

**Expected behavior**
Date should be parsed appropriately, and the cognito API should be called with the date in the appropriate format

**Screen Shots**
Error returned **Attributes did not conform to the schema: birthdate: Number must be no longer than 10 characters**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 71.0.3578.98

**Additional context**
Angular 6

**Comment by haverchuck** [comment] 2019-01-17 23:02
@scottjbaldwin -  I got this to work by using: 
```
  signUpConfig = {
    signUpFields: [
      {
        label: 'Birthdate',
        type: 'date',
        key: 'birthdate'
      }
    ]
  };
```  
I believe type=datetime is [not encouraged,](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime) is this what you were using?

The control isn't super pretty, but it presents a calendar control and formats the user input in the correct format.  We are working on *potential* styling customization, which would at least allow you to style the date input for webkit (I don't believe there is cross-browser support for styling a date input).

**Comment by haverchuck** [comment] 2019-01-18 22:32
Closing the issue for now since I reproduced and fixed using value posted above; if this isn't adequate please reopen this issue.

**Closed by haverchuck** 2019-01-18 22:32 UTC
Labels: Angular, UI

**Comment by scottjbaldwin** [comment] 2019-01-26 07:35
Yeah, @haverchuck , that works, thanks for that. 
Not the prettiest datetime control ever, but it's functional, and I can use it for my purposes.
Cheers
