### ISSUE TITLE
window.history.replaceState is null with Microsoft Office add-in

### ISSUE THREAD

**Issue by jrowen** [aws-amplify/amplify-js#11023] opened 2023-02-23 19:50 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: Linux 4.14 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 3.77 GB / 15.48 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.21.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  npmGlobalPackages:
    corepack: 0.15.1
    http-server: 14.1.1
    npm: 8.19.4
```

</details>

### Describe the bug

The aws-amplify library is being used for auth as part of a Vue app that is being accessed via a Microsoft Excel Add-in.  The window.history.replaceState call in Auth.js fails because window.history.replaceState is null.  

![image](https://user-images.githubusercontent.com/1530030/221010674-67a0424a-0d3b-45f2-ab6b-52270b6eb559.png)

It appears that this is a side-effect of Office add-ins.  Here's an example of how it was resolved for a similar project: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2501/files, https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/utils/BrowserUtils.ts#L25

![image](https://user-images.githubusercontent.com/1530030/221010287-cfabe010-51c1-445f-81e3-5d0975cd0443.png)

### Expected behavior

Handle window.history.replaceState == null.

### Reproduction steps

The aws-amplify library is being used for auth as part of a Vue app that is being accessed via a Microsoft Excel Add-in.  The auth flow uses Cognito with a Federated identity provider.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment] 2023-02-24 17:20
@jrowen, can you share a little bit more about your app/project such as what version of Amplify you're on, errors you're seeing in the console (if any), and how the Office Add-In was integrated with Amplify?

**Comment by jrowen** [comment] 2023-02-27 13:53
Certainly.  We're currently using v4.2.9.

We've built several Vue apps that use amplify to authenticate via Cognito and an internal identity provider.  These all work well in a standard browser.  If not authenticated, the user will first be redirected to log in via an internal system before being given access to the site.  Once we have an active session, we can utilize the user's tokens to access various data services.

We've been able to use the same Vue framework to create an Office add-in by leveraging the office.js library to interact with the Office apps.  When installed, it runs in a sidebar within the Office app.  It is essentially the same as our other web apps, as the add-in page can also be opened in a browser.  Since the webapp relies on the office.js library to do work, it's not very useful when opened outside of an Office app.  The same auth flow mentioned above is triggered whether the app opens within an Office app side bar or within the browser.

The Office apps must run some type of slimmed down browser in the sidebar.  This means the noted amplify code throws a console error and returns a blank page upon the first login attempt.  Reloading the add-in will usually cause it to then work fine, as it must be using the active auth session that initially errored out.

Here's the full console error.
![image](https://user-images.githubusercontent.com/1530030/221581509-9c6f39ed-eceb-476b-8825-fdf91f9ea3b4.png)
And main.js references this amplify call in the app `Amplify.configure(awsExportsInstance)`

Let me know if you need any additional details.

**Comment by cwomack** [comment] 2023-03-22 14:44
@jrowen, are you able to confirm that the initial login issue/error does **_not_** happen if the Vue app is opened outside of the Office sidebar and the same login flow is attempted?  Also, what version of office.js are you currently using?

**Comment by jrowen** [comment] 2023-03-22 17:06
Correct, we only see this when running the app as an Office add-in, and everything works fine when opened via a regular browser.  

We're using  the latest version of office.js from https://appsforoffice.microsoft.com/lib/1/hosted/office.js

**Comment by cwomack** [comment] 2023-03-22 23:08
Appreciate the quick follow up!  It seems the Office Add-ins determine which embedded browser/engine to use [based on the user's computer, OS, etc](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).  Only bringing this up because if Internet Explorer 11 is being used, this error might be getting thrown due to the `window.history.replaceState` property [not being supported](https://learn.microsoft.com/en-us/office/dev/add-ins/reference/window-objects-unsupported-in-add-ins#:~:text=window.history.replaceState).  Any chance you can verify what embedded browser control/webview is being used? 

The workaround examples you provided (and were implemented for Microsoft's Active Directory) are very appreciated as examples of how to better support more browser versions within Amplify's Auth flow.

**Comment by jrowen** [comment] 2023-03-23 01:34
When I view the Security Info from within the add-in, it says Runtime: Microsoft Edge, Version: 1.0.0.1, so I believe this means the add-in is using the chromium-based Edge.

**Comment by cwomack** [comment] 2023-12-11 18:56
With the release of the latest major version of Amplify (aws-amplify@>6), we highly recommend updating to the most recent version to see if this issue is now resolved. Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

If this issue is not resolved after attempting to upgrade to v6, please let us know with a reply back.

**Comment by cwomack** [comment] 2024-01-10 18:40
Closing this due to the release of v6 referenced above as well as [this commit ](https://github.com/aws-amplify/amplify-js/pull/12796/commits/44fdfe80476a59510514b842da3e93a6472bf506) that updated how the window history with current browser session's state behaves.  Please feel free to comment back or (ideally) open a new issue with updated context/reproduction steps if possible.  Thanks!

**Closed by cwomack** 2024-01-10 18:40 UTC
Labels: Auth, pending-response
