### ISSUE TITLE
Failing to instantiate amplify because of __exportStar is not a function

### ISSUE THREAD

**Issue by eriktisme** [aws-amplify/amplify-js#10059] opened 2022-07-05 15:17 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 2.56 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    nx: ^14.4.1 => 14.4.1
    typescript: ^4.7.4 => 4.7.4
    vite: ^2.9.13 => 2.9.13
  npmGlobalPackages:
    npm: 8.6.0
    pnpm: 7.3.0
    pre-commit: 1.2.2
    yarn: 1.22.19
```

</details>

### Describe the bug

When trying to instantiate Amplify and configure the authentication component I receive the following error in the browser console 

```
Uncaught TypeError: tslib_1.__exportStar is not a function
    pnpm aws-amplify.js:798
    __require2 aws-amplify.js:18
    <anonymous> Signer.ts:15
```

### Expected behavior

An Amplify object is instantiated with the authentication component configured

### Reproduction steps

1. Clone the reproduction repo `git clone git@github.com:eriktisme/minimal-repo-aws-amplify-bug-microfrontends.git`
2. Install dependencies `pnpm install`
3. Run the development environment `pnpm dev`
4. Check the browser `http://localhost:3000/`
5. Open the console and see the error

### Code Snippet

https://github.com/eriktisme/minimal-repo-aws-amplify-bug-microfrontends

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2022-07-05 18:27
Hi @eriktisme 👋 thanks for raising this issue. I was able to reproduce the error, which seems to be coming from the `@aws-crypto` package, given the sample repo and steps provided. Marking this as a bug for the team to investigate further.

<img width="1448" alt="Screen Shot 2022-07-05 at 2 25 44 PM" src="https://user-images.githubusercontent.com/16952986/177392029-55f191d1-e9da-4af5-9139-f5fc86db134c.png">

**Comment by eriktisme** [comment] 2022-09-10 08:03
@chrisbonifacio has there been any progress made on this issue?

**Closed** 2023-12-14 19:06 UTC
Labels: bug, Core, pending-response
