### ISSUE TITLE
NotAuthorizedException Invalid login token. Couldn't verify signed token

### ISSUE THREAD

**Issue by srchulo** [aws-amplify/amplify-js#6573] opened 2020-08-14 01:39 UTC
**Describe the bug**
I'm using amplify-authenticator for Vue, and intermittently when I go to my app I will get a not authorized exception. Then I refresh (I don't login again), and it works.

**To Reproduce**
I'm not sure exactly how to reproduce this. I run into it about 3% of the time.

**Expected behavior**
Authentication should not fail intermittently. 

**Code Snippet**
I'm not sure what code would be most relevant, but here is how I'm using the amplify-authenticator component:

```
                    <amplify-authenticator>
                        <amplify-sign-in
                            slot="sign-in"
                            header-text=""
                            username-alias="email"
                            submit-button-text="LOGIN"
                            hide-sign-up
                        ></amplify-sign-in>

                        <div v-if="signedIn">
                            <Header />
                            <nuxt />
                            <Footer />
                        </div>
                    </amplify-authenticator>
```

Here is the response I get from the authentication request:

`{"__type":"NotAuthorizedException","message":"Invalid login token. Couldn't verify signed token."}`

And then when my app tries to make API calls after failing to authenticate:

`{"message":"Missing Authentication Token"}`

Please let me know if there's any more information I can provide to help!

**Comment by srchulo** [comment] 2020-08-14 04:29
I also have a har file for a failed request, but I don't know if posting that will contain sensitive data?

**Comment by srchulo** [comment] 2020-08-17 00:50
It looks like this is the API call that's failling:

https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetId.html

And I can verify that the exact same request payload that fails, passes the next time when I refresh the page.

**Comment by srchulo** [comment] 2020-08-17 02:13
And `amplify-authenticator` is letting me through to the app, so it thinks that the authState is `signedin`, but then getting the identity fails.

**Comment by srchulo** [comment] 2020-08-17 02:53
I feel like this should maybe be caught/retried, since it seems okay on refresh, but if not, maybe authState could be changed to signout so that a user could get the login screen instead of an error?

**Comment by srchulo** [comment] 2020-08-21 04:21
It seems like I can reproduce this when:

- Load my app
- Let the page sit for a while (maybe 20 minutes)
- Come back and refresh the tab

I think the token has expired.

BUT, after looking into this more, I think it's possible that this may not be an Amplify UI bug, and could be an issue with the `asyncData` method in Nuxt being called when the page is loaded before the page component is even shown, because it looks like <amplify-authenticator> is making follow-up requests to get a new token that isn't expired.

**Comment by srchulo** [comment] 2020-08-23 17:28
It may be nice if there was a Nuxt [auth middleware](https://nuxtjs.org/guide/routing#middleware) provided by amplify-js, that could check that tokens are fresh, user is logged in, before going to the next page, and refresh the tokens if needed.

I imagine this is similar to what the [API](https://aws-amplify.github.io/amplify-js/api/classes/apiclass.html) module does for you if tokens are expired?

Something like this in an auth middleware I think would make sense:

https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/api/src/API.ts#L488-L501

**Comment by srchulo** [comment] 2020-08-23 19:10
I tried adding this as my auth middleware, and I think it worked. I wonder if something official like this would be good for people using Nuxt?

```
import Auth from '@aws-amplify/auth'

export default async function ({ redirect, route }) {
    if (route.name !== 'index') { // specific to my app, probably not needed for a generic one
        try {
            await Auth.currentAuthenticatedUser()
        } catch (e) {
            try {
                await Auth.signOut()
            } catch (e) {}

            return redirect({ path: '/', query: { route: route.fullPath } })
        }
    }
}
```

Then in nuxt.config.js:

```
    router: {
        middleware: ['auth'],
    },
```

**Comment by srchulo** [comment] 2020-08-24 19:53
I also added logging around `Auth.currentSession()`, and I log the session out to the console once I get it, and I do get a session object back, but then I immediately make my API call and that fails. I see a failed `AWSCognitoIdentityService.GetId` request with this response:

`{"__type":"NotAuthorizedException","message":"Invalid login token. Couldn't verify signed token."}`

And then my API calls after that get back 403s:

`{"message":"Missing Authentication Token"}`

**Comment by srchulo** [comment] 2020-08-24 20:33
It actually looks like CognitoUserSession.isValid checks if it has expired and does not check if it will expire soon, although it seems unlikely that I would run into this issue at the exact right milliseconds:

https://github.com/aws-amplify/amplify-js/blob/9761ead5665aca598b64578d29caf9d47eeee583/packages/amazon-cognito-identity-js/src/CognitoUserSession.js#L85-L93

**Comment by srchulo** [comment] 2020-08-29 05:02
For anyone else who runs into this issue, I wasn't able resolve the root issue (hopefully we can still get this fixed!), but in addition to my auth.js middleware, I also made an API call wrapper that tries up to three times to refresh the current session before making an API call. Here are the two files I ended up using:

**~/middleware/auth.js:**

```
import Auth from '@aws-amplify/auth'

export default async function ({ redirect, route }) {
    if (route.name !== 'index') {
        try {
            await Auth.currentSession()
        } catch (e) {
            try {
                await Auth.signOut()
            } catch (e) {}

            return redirect({ path: '/', query: { route: route.fullPath } })
        }
    }
}
```

And here is my API call wrapper. Some of this is specific to me, but demonstrates the general idea:

**~/libs/API.js**

```
/* eslint-disable no-console */
import Auth from '@aws-amplify/auth'
import { signOut } from '~/libs/authstate-handler'

function redirectToLogin({ router, route, redirect }) {
    const redirectParams = { path: '/', query: { route: route.fullPath } }
    if (router) {
        router.push(redirectParams)
    } else {
        redirect(redirectParams)
    }
}

export default async function apiCallWrapper({ store, router, redirect, route, lambda }) {
    try {
        await Auth.currentSession()
    } catch (error) {
        console.log('Failed to get current session')
        return redirectToLogin({ router, route, redirect })
    }

    try {
        return await lambda()
    } catch (error) {
        if (
            (error.response && (error.response.status === 401 || error.response.status === 403)) ||
            (error.data && error.data.message === 'Missing Authentication Token')
        ) {
            console.log(error)
            console.log('API call failed with authorization error. Will attempt to get session.')

            try {
                await Auth.currentSession()
                return await lambda()
            } catch (e) {
                console.log(e)
                console.log('Second API call try failed')
            }

            try {
                await signOut({ store, router, route })
            } catch (e) {
                console.log(e)
                console.log('Failed to sign out user')
            }

            console.log('Unable to resolve 4xx error, redirection to home page')

            return redirectToLogin({ router, route, redirect })
        }

        throw error
    }
}

```


And here's an example service file that uses the API wrapper:

**~/services/SettingsService.js**

```
import { API } from 'aws-amplify'
import apiCallWrapper from '~/libs/API'

export default {
    getSettings(store, redirect, route) {
        return apiCallWrapper({
            store,
            redirect,
            route,
            lambda: () => API.get('myapi', `/settings`),
        })
    },
}

```

**Comment by amhinson** [comment] 2020-11-16 21:01
@srchulo This is in a Nuxt app, correct? Would you be able to share your `package.json`?

**Comment by srchulo** [comment] 2020-11-16 22:50
Sure!

```
{
  "name": "myapp.com",
  "version": "1.0.0",
  "description": "My App",
  "author": "Adam Hopkins",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "export": "nuxt export",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore ."
  },
  "dependencies": {
    "@aws-amplify/ui-vue": "^0.2.8",
    "@nuxtjs/toast": "^3.3.1",
    "aws-amplify": "^3.0.17",
    "chart.js": "^2.9.3",
    "date-fns": "^2.15.0",
    "lazysizes": "^5.2.2",
    "lodash": "^4.17.19",
    "marker-clusterer-plus": "^2.1.4",
    "meta-ctrl-enter": "^1.0.2",
    "nuxt": "^2.14.6",
    "psl": "^1.8.0",
    "ua-parser-js": "^0.7.21",
    "uuid": "^8.3.0",
    "vee-validate": "^3.4.3",
    "vue-chartjs": "^3.5.0",
    "vue-clipboard2": "^0.3.1",
    "vue-select": "^3.10.7",
    "vue2-google-maps": "^0.10.7",
    "vuejs-dialog": "^1.4.2",
    "vuejs-paginate": "^2.1.0"
  },
  "devDependencies": {
    "@aceforth/nuxt-optimized-images": "^1.3.0",
    "@nuxtjs/eslint-config": "^3.0.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "babel-eslint": "^10.0.1",
    "concurrent-transform": "^1.0.0",
    "eslint": "^7.3.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-prettier": "^3.1.2",
    "gulp": "^4.0.2",
    "gulp-awspublish": "^4.1.2",
    "gulp-cloudfront-invalidate-aws-publish": "^1.0.0",
    "gulp-rename": "^2.0.0",
    "imagemin-gifsicle": "^7.0.0",
    "imagemin-mozjpeg": "^9.0.0",
    "imagemin-pngquant": "^9.0.0",
    "imagemin-svgo": "^8.0.0",
    "lqip-loader": "^2.2.0",
    "merge-stream": "^2.0.0",
    "prettier": "^2.0.5",
    "responsive-loader": "^2.0.2",
    "sharp": "^0.26.0",
    "sqip-loader": "^1.0.0",
    "webp-loader": "^0.6.0"
  }
}
```

**Comment by amhinson** [comment] 2020-11-17 00:14
Ok thank you!

For clarity, are you running any of this code in a Lambda? I'm particularly looking at `apiCallWrapper`.

**Comment by srchulo** [comment] 2020-11-17 01:43
No problem!

All of this code is run client side in the browser in my Nuxt app.

**Comment by amhinson** [comment] 2020-11-17 16:56
Ok cool. I know you've included a handful of code snippets, but would it be possible to provide a basic Nuxt repo that shows the behavior you're seeing (even if it is intermitted)? I want to reproduce this issue for you, but just want to make sure I'm starting in the same place as you are.

**Comment by iartemiev** [comment] 2021-04-02 20:45
Hey, we've made some changes to the library since this issue was opened that we think may resolve the problem. Could you please let us know if you're still experiencing this issue with the latest version of aws-amplify?

**Comment by iartemiev** [comment] 2021-04-12 18:16
@srchulo,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:16 UTC
Labels: Amplify UI Components, Auth, SSR, Vue, pending-close-response-required
