### ISSUE TITLE
User authentication via federated sign in is failing with "TypeError: Object(...) is not a function".

### ISSUE THREAD

**Issue by icecog** [aws-amplify/amplify-js#7759] opened 2021-02-17 09:41 UTC
**Describe the bug**
User authentication via federated sign in is failing with "TypeError: Object(...) is not a function".
Users cannot log in.

**To Reproduce**
1. Configure Amplify
2. Amplify.Logger.LOG_LEVEL = 'DEBUG';
2. Start app
3. Call Auth.federatedSignIn();
4. No user signed in
5. See error in console

**Expected behavior**
Up until recently I was able to log in with the settings as is. And now something has broken, and I don't think I can claim responsibility.

**Observed behavior**
Local Storage used to have all my tokens etc. but now only contains:
amplify-redirected-from-hosted-ui: true

And Cookies now contain:
XSRF-TOKEN and cognito

**Code Snippet**
```
<button on:click={async () => await Auth.federatedSignIn()}>Sign In</button>
```

**Errors**
<details>
  <summary><strong>Errors</strong></summary>

```
ConsoleLogger.js:97 [DEBUG] 27:24.616 AuthClass - OAuth signIn in progress, waiting for resolution...
ConsoleLogger.js:97 [DEBUG] 27:24.699 Credentials - set credentials from session
ConsoleLogger.js:107 [DEBUG] 27:24.701 Credentials - Failed to load credentials Promise {<rejected>: TypeError: Object(...) is not a function
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/m…}__proto__: Promise[[PromiseState]]: "rejected"[[PromiseResult]]: TypeError: Object(...) is not a function
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:175611:202
    at step (http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:268609:23)
    at Object.next (http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:268590:53)
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:268583:71
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:268579:12)
    at Object.defaultUserAgentProvider (http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:175607:88)
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:173012:46
    at step (http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:268609:23)
    at Object.next (http://localhost:3000/client/399f3c5f82bfe2a2a67d/main.js:268590:53)
ConsoleLogger.js:107 [DEBUG] 27:24.702 Credentials - Error loading credentials TypeError: Object(...) is not a function
    at index.js:13
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at Object.defaultUserAgentProvider (index.js:9)
    at user-agent-middleware.js:27
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
ConsoleLogger.js:107 [DEBUG] 27:24.702 AuthClass - Error in cognito hosted auth response TypeError: Object(...) is not a function
    at index.js:13
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at Object.defaultUserAgentProvider (index.js:9)
    at user-agent-middleware.js:27
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
ConsoleLogger.js:107 [DEBUG] 27:24.702 Hub - Dispatching to auth with  {event: "signIn_failure", data: TypeError: Object(...) is not a function
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/m…, message: "The OAuth response flow failed"}
ConsoleLogger.js:107 [DEBUG] 27:24.703 Hub - Dispatching to auth with  {event: "signIn_failure", data: TypeError: Object(...) is not a function
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/m…, message: "The OAuth response flow failed"}
ConsoleLogger.js:107 [DEBUG] 27:24.703 AnalyticsClass - on hub capsule auth {event: "signIn_failure", data: TypeError: Object(...) is not a function
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/m…, message: "The OAuth response flow failed"}
ConsoleLogger.js:107 [DEBUG] 27:24.703 Hub - Dispatching to auth with  {event: "signIn_failure", data: TypeError: Object(...) is not a function
    at http://localhost:3000/client/399f3c5f82bfe2a2a67d/m…, message: "The OAuth response flow failed"}
```
</details>

**What is Configured?**

   ```
const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:xxxx",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_xxx",
    "aws_user_pools_web_client_id": "xxxx",
    "oauth": {
        "domain": "xxxx.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "http://localhost:3000/callback,https://develop.xxxx.amplifyapp.com/callback",
        "redirectSignOut": "http://localhost:3000/logout,https://develop.xxxx.amplifyapp.com/logout",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};
   ```
   * If applicable, please provide your manual configuration example:
   ```
const updatedAwsConfig = {
    ...awsconfig,
    oauth: {
        ...awsconfig.oauth,
        redirectSignIn: isLocalhost ? localRedirectSignIn : productionRedirectSignIn,
        redirectSignOut: isLocalhost ? localRedirectSignOut : productionRedirectSignOut,
    }
};
 Amplify.configure({ ...updatedAwsConfig, ssr: true });
   ```

<details>
  <summary><strong>Amazon Cognito</strong></summary>
If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)

```
{
    "UserPool": {
        "Id": "eu-central-1_xxxxxx",
        "Name": "xxxxxx",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": true,
                "RequireLowercase": true,
                "RequireNumbers": true,
                "RequireSymbols": true,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": "2020-12-04T15:05:25.152000+01:00",
        "CreationDate": "2020-12-04T15:05:25.152000+01:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "SmsVerificationMessage": "The verification code to your new account is {####}",
        "EmailVerificationMessage": "The verification code to your new account is {####}",
        "EmailVerificationSubject": "Verify your new account",
        "VerificationMessageTemplate": {
            "SmsMessage": "The verification code to your new account is {####}",
            "EmailMessage": "The verification code to your new account is {####}",
            "EmailSubject": "Verify your new account",
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 4,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "Domain": "envar-beta",
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": false,
            "UnusedAccountValidityDays": 7
        },
        "Arn": "arn:aws:cognito-idp:eu-central-1:xxxx:userpool/eu-central-xxxx",
        "AccountRecoverySetting": {
            "RecoveryMechanisms": [
                {
                    "Priority": 1,
                    "Name": "verified_phone_number"
                },
                {
                    "Priority": 2,
                    "Name": "verified_email"
                }
            ]
        }
    }
}
```
 </details>

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz
    Memory: 2.67 GB / 15.92 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @sveltejs/svelte-scroller: ^2.0.6 => 2.0.6 
    aws-amplify: ^3.3.19 => 3.3.19 
    body-parser: ^1.19.0 => 1.19.0 
    compression: ^1.7.1 => 1.7.4 
    file-loader: ^6.0.0 => 6.2.0
    markdown: ^0.5.0 => 0.5.0
    polka: next => 1.0.0-next.11
    sapper: ^0.29.1 => 0.29.1
    sirv: ^1.0.0 => 1.0.11
    svelte: ^3.32.3 => 3.32.3
    svelte-loader: ^2.13.6 => 2.13.6
    uuid: ^8.3.1 => 8.3.2
    webpack: ^4.7.0 => 4.46.0
    webpack-modules: ^1.0.0 => 1.0.0
  npmGlobalPackages:
    @aws-amplify/cli: 4.40.0
    aws-amplify: 3.3.14
    aws-cdk: 1.75.0
    cdkp: 0.6.1
    contentful-cli: 1.5.18
    npm-check-updates: 10.2.2
    typescript: 4.1.3
    yarn: 1.22.10
```

</details>

**Computer:**
- Device: Laptop
- OS: Windows 10
- Browser: Chrome 
- Version: 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
It makes no difference if I run ssr: false, or remove 'ssr: true'.

**Comment by icecog** [comment] 2021-02-17 10:13
Reproduction:
[amplify-auth-error-reproduction.zip](https://github.com/aws-amplify/amplify-js/files/5994886/amplify-auth-error-reproduction.zip)

**Comment by wlee221** [comment] 2021-02-19 22:25
Hi @icecog, thanks a lot for the reproduction repo! I was able to reproduce it and make some investigations.

- This works as intended on on `aws-amplify@3.8.12`. Please know that you can install that version as a workaround while we work on this.
- The error occurs on this line: https://github.com/aws-amplify/amplify-js/blob/aecdf3cccbf07d315b707f8babbea4451d41a857/packages/core/src/Credentials.ts#L318-L322
- Hence it is likely the @aws-sdk 3.4.1 [bump](https://github.com/aws-amplify/amplify-js/pull/7726) that is causing this regression.

We will continue looking at this.

**Comment by wlee221** [comment] 2021-02-23 07:11
I explored more and found that https://github.com/aws/aws-sdk-js-v3/issues/1992 is the root cause. This problem does not occur when your bundler uses `es5` module, which was not the case with `sapper build`. This should be fixed as we bump to sdk to `3.5.0` or later.

ps. @icecog if you have yarn, can you try a fresh install with latest Amplify and the following addition to your `package.json`:
```diff
  "devDependencies": {
    "file-loader": "^6.0.0",
    "sapper": "^0.28.0",
    "svelte": "^3.17.3",
    "svelte-loader": "^2.9.0",
    "webpack": "^4.7.0",
    "webpack-modules": "^1.0.0"
-  },
+  }
+   "resolutions": {
+     "@aws-sdk/util-user-agent-browser": "3.6.1"
  }
```
and see if this works? Just want to confirm this fixes on your side as well before we bump aws-sdk.

**Comment by icecog** [comment] 2021-02-24 06:20
> * This works as intended on on `aws-amplify@3.3.17`. Please know that you can install that version as a workaround while we work on this.

Thank you, William! That worked great! 

I also did a fresh install of aws-amplify that resulted in `"aws-amplify": "^3.3.20",` being install and then added the resolution as you specified above to the end of package.json 
```json
{
...
  "dependencies": {
    "aws-amplify": "^3.3.20",
    ...
  },
  "devDependencies": {
    ...
  },
  "resolutions": {
    "@aws-sdk/util-user-agent-browser": "3.6.1"
  }
}
```

then ran.
```
yarn
yarn run dev
```
That also resulted in a successful login and the problem being resolved.
I ran the following and all resulted in the expected login/logout behavior:
```
yarn run dev
---
yarn run build
node __sapper__/build
---
yarn run export
npx serve __sapper__/export -l 3000
```
So thank you kindly for taking a look, William! Much appreciated :)

**Closed** 2021-02-25 20:43 UTC
Labels: Auth, Federation, bug

**Comment by wlee221** [comment] 2021-02-25 22:50
@icecog, glad to hear it's working! And thanks for confirming that `resolutions` worked. The fix is now released on latest Amplify. Please do a fresh install of `aws-amplify` and you can remove the workarounds now :)

**Comment by icecog** [comment] 2021-02-26 05:54
@wlee221 I reinstalled and all works as expected :) 
Thanks again for the quick work, a load of my mind :)
