### ISSUE TITLE
Way to execute Cognito Federated Login in Localhost for Testing

### ISSUE THREAD

**Issue by MiqueiasGFernandes** [aws-amplify/amplify-js#8165] opened 2021-04-23 14:31 UTC
**Is your feature request related to a problem? Please describe.**
I have search about a way to execute Cognito federated Login in localhost, to test this without need deploy frontend into Amplify 
hosting environment, but i didn't found anything about this in documentation. I tried configure Google Cloud Credentials to allow http://localhost and i add it to redirect URI's configuration in Cognito panel. However, when i select my account in opened Google Login page, the follow step show me this: An error was encountered with the requested page.

**Describe the solution you'd like**
Provide a way to execute Cognito with federated sign locally.
e. g: a command `amplify mock auth` or any support in communication between cognito server and Google oAuth to localhost.

**Comment by manueliglesias** [comment] 2021-04-26 23:49
Hi @MiqueiasGFernandes 

We have a documentation section for [Social sign-in](https://docs.amplify.aws/lib/auth/social/q/platform/js), You can follow those steps when developing in localhost too, you just need to make sure to add the appropriate *redirect signin URI* and *redirect signin URI* when the CLI prompts you

**Comment by sammartinez** [comment] 2021-05-18 15:52
@MiqueiasGFernandes,

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 15:52 UTC
Labels: OAuth, pending-close-response-required, question
