### ISSUE TITLE
Datastore - Observe query results in real-time with @hasOne relation doesn't add nested data after first sync

### ISSUE THREAD

**Issue by sebboe** [aws-amplify/amplify-js#9682] opened 2022-03-07 19:14 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.22

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I'm facing an issue while observing objects with "@hasOne" relationship. When adding a new object, the observer returns only the main object, without the relation field. After one refresh/moving to another component and coming back, the nested object appears as part of the main object.

[According to the doc:](https://docs.amplify.aws/lib/datastore/real-time/q/platform/js/#observe-model-mutations-in-real-time)

> observeQuery(...) returns an initial data set, similar to query(...), and also automatically subscribes to subsequent changes to the query.

### Expected behavior

I would like to directly return the nested object.

### Reproduction steps

1. Link two models with "@hasOne"
2. Add object with relation
3. Observe objects:

```
    this.flightList = DataStore.observeQuery(Flight).subscribe(snapshot => {
      const { items, isSynced } = snapshot;
      console.log(`[Snapshot] item count: ${items.length}, isSynced: ${isSynced}`);
      console.log(items);
      this.flights = items;
    });
```

### GraphQL schema(s)

```graphql
# Put schemas below this line
type Flight @model {
  id: ID!
  pilot: String!
  airplane: Aircraft @hasOne(fields: ["airplaneId"])
  airplaneId: ID
}

type Aircraft @model {
  id: ID!
  registration: String!
  category: String
  lastIndex: String
  specs: AircraftSpecs
}

type AircraftSpecs {
  passenger:Boolean
  fuel:String
}

```

### Log output

```
# Object returned right after saving it:
{
    "id": "5a91ab15-0866-4919-9703-3083018cdeab",
    "pilot": "Sébastien",
    "airplaneId": "3e154d19-af70-47d2-9d66-829fce65b93a",
    "_version": 1,
    "_lastChangedAt": 1646679807385,
    "_deleted": null
}
# Object returned after refresh
{
    "id": "5a91ab15-0866-4919-9703-3083018cdeab",
    "pilot": "Sébastien",
    "airplaneId": "3e154d19-af70-47d2-9d66-829fce65b93a",
    "_version": 1,
    "_lastChangedAt": 1646679807385,
    "_deleted": null,
    "airplane": {
        "id": "3e154d19-af70-47d2-9d66-829fce65b93a",
        "registration": "AV-ION",
        "category": "Airplane",
        "lastIndex": "22299:99",
        "createdAt": "2022-03-06T23:30:51.363Z",
        "updatedAt": "2022-03-07T19:03:27.671Z",
        "specs": {
            "passenger": true,
            "fuel": "AVGAS"
        },
        "_version": 8,
        "_lastChangedAt": 1646679807692,
        "_deleted": null
    }
}
```

**Comment by sebboe** [comment] 2022-03-30 08:44
As a workaround, instead of using data returned by the subscription, I call a classic DataStore.query when new data are emitted.

```
    this.flightList = DataStore.observeQuery(Flight).subscribe(snapshot => {
      //const { items, isSynced } = snapshot;
      //console.log(`[Snapshot] item count: ${items.length}, isSynced: ${isSynced}`);
      this.refreshData().then(flights => {
        this.flights = flights;
        console.log(this.flights);
      })
    });
  }

  async refreshData(){
    this.flights = await DataStore.query(Flight);
    return this.flights
  }
```

**Comment by chow11** [comment] 2022-04-19 14:05
I also see this issue and the same problem arises after updating the model.  The re-query workaround addresses both issues.

**Comment by tomyates** [comment] 2022-05-05 09:58
I am also have this issue, I'll try the re-query workaround.

**Comment by svidgen** [comment] 2022-06-29 20:47
@sebboe This should be fixed. Are you still seeing this problem on the latest version of amplify?

**Comment by cbirkenstock** [comment] 2022-08-18 00:59
I am still not receiving nested objects from the observe part of observeQuery and my datastore version is 3.12.6 (most up to date)

**Comment by chow11** [comment] 2022-08-18 01:30
It is working for me, 1 level deep.


type Post @model {
  id: ID!
  title: String!
  rating: Int!
  status: PostStatus!
  # New field with @hasMany
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

# New model
type Comment @model {
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post! @belongsTo(fields: ["postID"])
  content: String!
}

If Comment.postID does not contain a value that exists in the Post collection, then the Comment.post field will not show up in the results.  Note that Post.comments never shows up in results for me.  If I want to query for the relationship, I have to query and reduce the Comments collection like:

const [postComments, setPostComments] = React.useState({ });
const subscription = DataStore.observeQuery(Comments).subscribe(({ items }) => {
	setPostComments(prev => items.reduce((a, o) => {
        if (o.postID in a) {
            a[o.postID][o.id <http://o.id/>] = o;
        } else {
            a[o.postID] = { [o.id]: o }
        }
        return a;
    }, { …prev }));
});

Then the comment array for a post like: const comments = Object.values(postComments[postId]);

**Comment by dpilch** [comment] 2022-08-18 15:58
May be related to https://github.com/aws-amplify/amplify-js/issues/10211

**Comment by bc4253** [comment] 2022-08-18 20:05
One thing about updating relationships as being different from adding a new one.  In the above example, if postID is null then updating the Comments document only requires setting postID.  If postID is already pointing to post "A", then updating just postID to the ID of post "B" fails.  Update (and delete - set posID=null) of an existing relationship requires also setting post to the "B" post model.

Why is setting the model reference field required?  post is a calculated field.

**Comment by bc4253** [comment] 2022-08-18 20:13
I have also noticed that one can set postID to anything if postID was null previously.  If postID is a value that is not the ID of a Post document, then no error is generated on the update.  querying/observing will obviously not return a Post model in the post field in this case.

**Comment by dpilch** [comment] 2023-02-20 21:29
I'm not able to reproduce this. It may have been incidentally fixed with the lazy loading change. Please comment if you are still experiencing this issue.

**Closed by dpilch** 2023-02-20 21:29 UTC
Labels: DataStore, transferred, p2

**Comment by qwertylolman** [comment] 2024-04-20 13:24
> I'm not able to reproduce this. It may have been incidentally fixed with the lazy loading change. Please comment if you are still experiencing this issue.
I'm having exactly the same issue, but with amplify-flutter

**Comment by chrisbonifacio** [comment] 2024-04-20 18:08
@qwertylolman can you please create a new issue on the amplify flutter repo with either a sample repo that reproduces the issue or reproduction steps? 

You can reference/link to this issue as well to include as context for the amplify flutter team
