### ISSUE TITLE
Multiple authorization types (IAM & Cognito) returns 401 error on type create mutation, regardless of which authorization type you start with as the default, via Amplify CLI

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-js#5540] opened 2020-04-24 13:50 UTC
The following initial schema, supplied to `amplify add api` returns 401 response on create mutation of `type PrivateTrack`, when setting up multiple authorization types, with IAM being the default authorization type, even though the Cognito user-pool user that has been created & confirmed is successfully logged-in when making the call to `CreatePrivateTrack({ path: 'some-path' })` (using Angular generated service code in browser, with all current versions):
```graphql
type Search
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [create, update, read] }
    ]
  )
  @key(fields: ["normalizedQuery"])
{
  normalizedQuery: String!
  titles: String!
  nTimes: Float!
  nTimesInLast24h: Int!
  updatedAt: AWSTimestamp!
  titlesUpdatedAt: AWSTimestamp!
}

type PrivateTrack
  @model
  @auth(rules: [{ allow: owner } ])
{    
  id: ID!
  path: String!
}

type PublicTrack
  @model
  @auth(
    rules: [
      { allow: owner },
      { allow: public, provider: iam, operations: [read] }
    ]
  )
{
  id: ID!
  path: String!
}
```
Using amplify-cli v 4.18.1.

**Comment by dorontal** [comment] 2020-04-24 13:52
See Issue #5518 for a lengthy description of this problem.

**Comment by elorzafe** [comment] 2020-04-24 20:02
@dorontal 
When using `owner` authorization for a type you will have to use `AMAZON_COGNITO_USER_POOLS` as the auth_mode for that operation.

**Comment by elorzafe** [comment] 2020-04-24 20:06
I will close this issue because is a duplicate of #5518 the other issue you posted

**Closed by elorzafe** 2020-04-24 20:06 UTC
Labels: API, GraphQL, to-be-reproduced

**Comment by dorontal** [comment] 2020-04-24 20:27
@lorzafe - thanks for the response, but:

I am. I am using AMAZON_COGNITO_USER_POOLS for that operation.

The CreatePrivateTable is the operation (mutation).

The user (owner) is logged in, successfully, at the time that I call that mutation.

I get a 401 error.

This is what this entire issue is about.

Did I miss something?

**Comment by dorontal** [comment] 2020-04-24 20:30
Oops, just saw the comment to keep communicating on issue #5518.  Apologies for responding here. I will only communicate in that other issue from now on.
