### ISSUE TITLE
Need to insert bulk data

### ISSUE THREAD

**Issue by uc-apa** [aws-amplify/amplify-js#4861] opened 2020-02-07 06:08 UTC
I am using data store in my react native app. But I did not find any solution for inserting multiple records in one go which I am receiving from an ajax request. I do not want to write code to insert each record individually as they are always 8000+ in number.
```
await DataStore.save(
        new Todo(todo)
);
```
Please provide a solution. Thank you.

**Comment by manueliglesias** [comment] 2020-02-08 00:17
Hi @uc-apa 

Thanks for trying Amplify and the DataStore

Can you elaborate a little on your use case? I am thinking that if the 8k+ records come from an ajax call, they already are in some sort of backend, would it make sense for your use case to have  your existing backend trigger graphql mutations directly to your appsync api? And then, your clients using DataStore automatically sync

**Comment by uc-apa** [comment] 2020-02-10 03:39
Hello,

Thanks for your quick response. The problem we are facing with our architecture is that we are not able to sync our mobile data properly with web. The autosync api will help us a lot in our case as it will automatically manage all the sync operations. We actually have millions of records already in our database and want to provide only a subset of it for user's offline use and sync them automatically as and when they are updated online.

**Comment by uc-apa** [comment] 2020-02-17 09:51
I am also stuck at below point:-

1. I have created 4 records in my ios device at the time when my android device was off.
2. Later I opened my app in android and want all data of dynamoDb to be automatically updated/sync in local Datastore. I do not want to run 
`API.graphql(graphqlOperation(queries.listTodos));`
if possible, rather use only `DataStore.query(Todo, Predicates.ALL)`. So that all my data will be always in sync on all my devices. If it could be query based i.e. user_id specific data only will be imported in datastore then it would be great.
Thank you.

**Comment by Ashish-Nanda** [comment] 2020-03-05 19:05
Hey @uc-apa 

Can you give DataStore for React Native a try? It was launched after you created the issue, so do take a look at the [docs](https://aws-amplify.github.io/docs/js/datastore)
This should allow your data to sync across multiple devices.

With regards to syncing only a subset of your records as you mention [here](https://github.com/aws-amplify/amplify-js/issues/4861#issuecomment-583942288), we currently are tracking it as a feature request #4957  

I'm closing this one as its a duplicate of the feature request. If you have a different issue please open a new one. Thanks!

**Closed by Ashish-Nanda** 2020-03-05 19:05 UTC
Labels: DataStore, React Native, question
