### ISSUE TITLE
Clock Drift/Skew code does not handle all skew error scenarios

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-js#6494] opened 2020-08-05 06:28 UTC
**Describe the bug**
See my comments https://github.com/aws-amplify/amplify-js/issues/2014#issuecomment-668914147 onwards. DateUtils' isClockSkewError only checks for one kind of error type related to bad clock, but there's actually many possible error types. See https://github.com/aws/aws-sdk-js-v3/blob/47770fa493c3405f193069cd18319882529ff484/packages/service-error-classification/src/constants.ts#L8

**To Reproduce**

1. Setup API Gateway via amplify cli
2. Set your computer time 10 minutes early or more
3. Have your code sign into cognito, then make a REST API call to API Gateway
4. You'll get error back with 'x-amzn-errortype' of "InvalidSignatureException" and now retry will occur with proper clock offset. 

**Expected behavior**
Retry would occur with correct clock offset. For some reason your code expects "BadRequestException" error to be returned but in my case "InvalidSignatureException" is returned.

**Screenshots**
See https://github.com/aws-amplify/amplify-js/issues/2014#issuecomment-668914147 for example error. In this case error came from cloudfront in an edge-optimized API Gateway, but same error comes back from regional API Gateway too. 

<img width="268" alt="89360718-8bf0d780-d686-11ea-8ca0-01ef564f5aae" src="https://user-images.githubusercontent.com/81853/89379061-5530b680-d6b2-11ea-99fd-0fd01a19dbad.png">

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "EssRestAPI",
            "endpoint": "https://....execute-api.us-east-1.amazonaws.com/...",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://....appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:8...",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_g0...",
    "aws_user_pools_web_client_id": "1e1rhg332...",
    "oauth": {}
};```
   * If applicable, please provide your manual configuration example:
   ```Amplify.configure(awsmobile);
Auth.configure({
  authenticationFlowType: 'USER_PASSWORD_AUTH'
});```




```
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 104.32 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    @angular-builders/custom-webpack: ^10.0.0 => 10.0.0 
    @angular-devkit/build-angular: ^0.1000.4 => 0.1000.4 
    @angular/animations: ~10.0.5 => 10.0.5 
    @angular/cdk: ^10.1.0 => 10.1.0 
    @angular/cli: ~10.0.4 => 10.0.4 
    @angular/common: ~10.0.5 => 10.0.5 
    @angular/compiler: ~10.0.5 => 10.0.5 
    @angular/compiler-cli: ^10.0.5 => 10.0.5 
    @angular/core: ~10.0.5 => 10.0.5 
    @angular/elements: ~10.0.5 => 10.0.5 
    @angular/forms: ~10.0.5 => 10.0.5 
    @angular/material: ^10.1.0 => 10.1.0 
    @angular/platform-browser: ~10.0.5 => 10.0.5 
    @angular/platform-browser-dynamic: ~10.0.5 => 10.0.5 
    @angular/router: ~10.0.5 => 10.0.5 
    @aws-amplify/api: ^3.1.20 => 3.1.20 
    @aws-amplify/api-rest: ^1.1.3 => 1.1.3 
    @aws-amplify/auth: ^3.3.2 => 3.3.2 
    @ng-select/ng-option-highlight: 0.0.5 => 0.0.5 
    @ng-select/ng-select: ^4.0.0 => 4.0.4 
    @ngneat/until-destroy: ^7.1.6 => 7.3.2 
    @stripe/stripe-js: ^1.8.0 => 1.8.0 
    @types/jasmine: ~3.5.0 => 3.5.11 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/node: 14.0.4 => 14.0.4 
    @types/node-zendesk: ^1.4.0 => 1.4.0 
    array-flat-polyfill: ^1.0.1 => 1.0.1 
    axios: ^0.19.2 => 0.19.2 
    body-parser: ^1.19.0 => 1.19.0 
    codelyzer: ^6.0.0 => 6.0.0 
    document-register-element: ^1.7.2 => 1.14.3 
    folder-hash: ^3.3.0 => 3.3.2 
    fs-extra: ^9.0.0 => 9.0.1 
    jasmine-core: ~3.5.0 => 3.5.0 
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    karma: ~5.0.0 => 5.0.9 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~3.3.0 => 3.3.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4 
    libphonenumber-js: ^1.7.51 => 1.7.54 
    lodash-es: ^4.17.15 => 4.17.15 
    lodash.merge: ^4.6.2 => 4.6.2 
    lodash.snakecase: ^4.1.1 => 4.1.1 
    ng2-pdf-viewer: ^6.3.2 => 6.3.2 
    ngx-build-plus: ^10.1.1 => 10.1.1 
    ngx-stripe: ^10.1.1 => 10.1.1 
    node-sass: ^4.13.1 => 4.14.1 
    object.fromentries: ^2.0.2 => 2.0.2 
    postcode-validator: ^3.1.0 => 3.1.0 
    prettier: ^1.19.1 => 1.19.1 
    prettier-tslint: ^0.4.2 => 0.4.2 
    prompt-sync: ^4.2.0 => 4.2.0 
    protractor: ~7.0.0 => 7.0.0 
    rxjs: ~6.6.0 => 6.6.0 
    stripe: ^8.25.0 => 8.72.0 
    tmp: ^0.1.0 => 0.1.0 
    ts-node: ~8.3.0 => 8.3.0 
    tslib: ^1.13.0 => 1.13.0 
    tslint: ~6.1.0 => 6.1.2 
    typescript: ~3.9.6 => 3.9.6 
    webpack-bundle-analyzer: ^3.8.0 => 3.8.0 
    which: ^2.0.2 => 2.0.2 
    zone.js: ~0.10.3 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 10.0.3
    @aws-amplify/cli: 4.26.0
    local-web-server: 4.2.1
    node-gyp: 7.0.0
    npm: 6.14.4```

</details>

**Comment by hisham** [comment] 2020-08-05 07:02
I was able to fix my issue with this one line before the Rest API call: 

`DateUtils.setClockOffset(user.signInUserSession.clockDrift * 1000 * -1);`

**Comment by houmark** [comment] 2020-08-05 22:46
Could you elaborate more on the one-liner fix @hisham? 

Is this for public API, or only REST? I have been testing and for Cognito it seems to auto fix for me, but for a public GraphQL API, I get errors and I am not sure how to fix it.

Could you share more related code to the above one-liner?

**Comment by hisham** [comment] 2020-08-05 23:15
@houmark I'm using it only for REST API (API Gateway). I call it after user signs in via Cognito: 

```
    return from(Auth.signIn(email, password, clientMetadata)).pipe(
      tap((user: CognitoUser) => {
        // Can probably remove this once https://github.com/aws-amplify/amplify-js/issues/6494
        // is resolved / clarified.
        DateUtils.setClockOffset(user.signInUserSession.clockDrift * 1000 * -1);
      })
    );
```

Then I do REST API call: 

`RestAPI.post(environment.restEndpointName, '/items', {}))`

In my case my REST API requires users to be authenticated via cognito and is not public.

**Comment by houmark** [comment] 2020-08-05 23:22
And DateUtils is imported from Amplify? Because while it may be the same utility function, I've seen it imported from `aws-sdk` and `@amplify/core`.

Maybe it's a REST situation you have then, I tested last night with normal GraphQL after login with clock 10 minutes off, and it was working all around, so my main issue is GraphQL to a public API configured like this in Amplify:

```graphql
@auth(rules: [
    { allow: public, provider: iam, operations: [read, update] }
])
```

It's really annoying important stuff like this is not first of handled natively by the libraries or at least are well documented and works in all situations and pushed early in the documentation. Many Amplify users will have this problem without even knowing about it and once they finally realize why, they will struggle fixing it.

Other platforms just doesn't have these problems and if there's something the developer need to have attention to, then they will make sure that it's highlighted in documentation.

Amplify feels like some random small startup where they are hacking around on an non-released alpha without proper documentation.

**Comment by hisham** [comment] 2020-08-05 23:37
Yeah I import DateUtils from @amplify/core: 

`import { DateUtils } from '@aws-amplify/core';`

I haven't tested GraphQL API calls from computers with wrong clocks. All my consumer-facing APIs currently are REST and that's where I have run into these weird scenarios so far. 

Yes feels like Amplify Team has been following the minimum viable product spirit to the extreme. They've been iterating though and things have gotten better over the last year. So I think it's a matter of time. We're the early adopters I guess who get to deal with these bugs/limitations for better or worse.

**Comment by guibernardino** [comment] 2020-08-19 20:24
I'm not sure if he can handle any scenario.

The current solution depends on the response header of the request.
https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Util/DateUtils.ts#L62
```
	isClockSkewError(error: any) {
		if (!error.response || !error.response.headers) {
			return false;
		}
```


But for requests that return error 4xx, axios does not return the response object.
https://github.com/axios/axios#handling-errors
```
axios.get('/user/12345')
  .catch(function (error) {
    if (error.response) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else if (error.request) {
      // The request was made but no response was received
      // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
      // http.ClientRequest in node.js
      console.log(error.request);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    console.log(error.config);
  });
```
https://github.com/axios/axios/issues/960

**Comment by hisham** [comment] 2021-03-15 20:45
Hey @sammartinez @elorzafe - I found another related issue. S3 PUT uploads also fail with 403 if user's clock is wrong. Any suggested workarounds / solutions / timelines in resolving this?

**Comment by chriskinzel** [comment] 2021-05-05 16:26
The solution in https://github.com/aws-amplify/amplify-js/issues/6494#issuecomment-669019819 does not seem to work for S3 PUT uploads (``Storage.put(`${cred.identityId}/${randomFilename}`, file, {...``).

Looks like `systemClockOffset` needs to be set but there doesn't seem to be any way to do this from Amplify.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#systemClockOffset-property

<img width="663" alt="Screen_Shot_2021-05-04_at_8 25 42_PM" src="https://user-images.githubusercontent.com/25732038/117173359-ea6bf300-ad89-11eb-87cc-a3ceec4e57af.png">

Parsing the XML response and patching `Date.now` works but is extremely hacky

<img width="671" alt="Screen_Shot_2021-05-04_at_8 26 08_PM" src="https://user-images.githubusercontent.com/25732038/117173494-0ec7cf80-ad8a-11eb-8df5-23177532e40c.png">

Seems like the clock offset should be set automatically in this case by Amplify and this is a bug.

**Comment by matheus-rn** [comment] 2021-05-16 05:42
Any correction prediction?

**Comment by aldodaquino** [comment] 2021-10-21 21:33
Ours customers are facing this issue too. We have used one workaround to set clockskew on API calls. Is there any similar workaround for storage.get() calls?

**Comment by david-mcafee** [comment] 2021-10-22 00:57
Clock skew errors appear to have affected both API calls, and S3 uploads. While investigating this, it appears we had [a previous fix for API calls](https://github.com/aws-amplify/amplify-js/pull/5869).

@thava and @aldodaquino - can you provide us with additional reproduction steps? Are you only experiencing this for Storage, or somewhere else? Thank you!

**Comment by david-mcafee** [comment] 2021-11-01 19:39
As @jamesaucode mentioned in his closed PR, "we decided to upgrade the @aws-sdk version (that includes a patch that will fix this clockskew issue) instead of rolling out our own middleware." Will update this ticket once we've made that upgrade.

**Comment by jamesaucode** [comment] 2021-11-04 23:12
Turns out upgrading the @aws-sdk is going to take a little longer than we thought and will probably need another discussion with the team before we do that. Meanwhile we merged #9125 that should fix this issue

**Comment by hisham** [comment] 2021-11-22 22:10
@jamesaucode - I verified the s3 uploads now work when clock is wrong, however the original bug I filed this ticket for (cognito / rest requests) still exists and I still have to keep the workaround I detailed in https://github.com/aws-amplify/amplify-js/issues/6494#issuecomment-669592409.

**Comment by jamesaucode** [comment] 2021-11-22 23:54
> @jamesaucode - I verified the s3 uploads now work when clock is wrong, however the original bug I filed this ticket for (cognito / rest requests) still exists and I still have to keep the workaround I detailed in [#6494 (comment)](https://github.com/aws-amplify/amplify-js/issues/6494#issuecomment-669592409).

@hisham Thanks. I will look into the cognito/rest issue.

**Comment by jamesaucode** [comment] 2021-11-23 22:52
I was able to repro the problem. I will track down the root cause and give an update here when I do 😄

**Comment by jamesaucode** [comment] 2021-11-23 22:52
re-opening this so I can track it

**Comment by hisham** [comment] 2021-11-25 16:59
Thanks @jamesaucode , fyi, I also found similar issue with analytics (pinpoint) requests - I filed https://github.com/aws-amplify/amplify-js/issues/9281 for it. Thanks!

**Comment by jamesaucode** [comment] 2021-11-30 02:29
Hi all, I spent a good chunk of today trying to debug this issue. So, It looks like this is **not a library issue** but is instead an API Gateway / CLI issue.

The way we correct any clock skew error, as pointed out by @hisham is as follow
1. Make a request 
2. Gets an error response from the server
3. Check the type of error to see if it's related to a clock skew
4. If yes, check the `Date` header from the error response and call `DateUtils.setClockOffset` by calculating the difference between the request time & the server response time

see: https://github.com/aws-amplify/amplify-js/blob/8448b4fe1f995f0d6056bcb46dd0fb2023fb197d/packages/api-rest/src/RestClient.ts#L194-L225

This part actually works as intended, the problem is, if we look at the screenshot provided, the CORS headers are missing (which is also the problem I encountered when I repro-ed the problem). Javascript won't be able to access the error response, therefore the library couldn't identify it as a clock skew error. Therefore the solution is to actually make API gateway respond with the CORS header for 4XX errors. 

You can follow the walkthrough below for a temporary workaround:

1. Go to your AWS console -> look for the API gateway page -> select the API you want to configure
![Screen Shot 2021-11-29 at 5 39 58 PM](https://user-images.githubusercontent.com/40404256/143970100-25c211c5-4bc0-46ba-b4f7-2fe007073e1d.png)
2. Go to **'Gateway responses'**
![Screen Shot 2021-11-29 at 7 14 50 PM](https://user-images.githubusercontent.com/40404256/143973639-dec4898f-77c3-4d85-ae30-9b2efe8c8c6d.png)
3. Click **'Invalid Signature'** (This is the error I'm getting for 403, if yours is different then select the error type you are getting instead of this)
Configure the response headers to allow CORS, and **expose the `Date` and `x-amzn-errortype` headers**
Here's an example, (change **'my-domain.com'** to a value that fits your use case)
![Screen Shot 2021-11-29 at 6 20 05 PM](https://user-images.githubusercontent.com/40404256/143974090-7119872d-f793-4e3a-aa4c-67de44cb6c1b.png)
4. Deploy the API
5. Now your API should work despite a clock time mismatch!

Demo:

https://user-images.githubusercontent.com/40404256/143974566-429a7c05-d989-485e-8ad1-8a2e41e1981f.mov

**Comment by jamesaucode** [comment] 2021-12-01 00:23
https://github.com/aws-amplify/amplify-cli/pull/9158 I have submitted a PR on the CLI side to add this behavior as a default 4xx / 5xx gateway response

**Closed** 2022-01-21 23:42 UTC
Labels: bug, API, Storage
