### ISSUE TITLE
Amplify Storage depends on file's extension rather than contentType

### ISSUE THREAD

**Issue by jbhammon** [aws-amplify/amplify-js#10053] opened 2022-07-02 13:06 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Storage

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.21 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    @aws-amplify/ui-react: ^2.15.3 => 2.20.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @mapbox/mapbox-gl-style-spec:  13.18.0-dev 
    @material-ui/core: ^4.11.0 => 4.12.4 
    @material-ui/icons: ^4.9.1 => 4.11.3 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.61 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.4.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^4.3.20 => 4.3.26 
    axios: ^0.21.1 => 0.21.4 (0.26.0)
    empty-npm-package:  undefined (1.0.0)
    exif-js: ^2.3.0 => 2.3.0 
    mapbox-gl: ^1.12.0 => 1.13.2 
    prop-types: ^15.7.2 => 15.8.1 
    react: ^17.0.0 => 17.0.2 (18.0.0)
    react-dom: ^17.0.0 => 17.0.2 
    react-google-recaptcha: ^2.1.0 => 2.1.0 
    react-hook-form: ^7.31.3 => 7.33.1 
    react-router-dom: ^5.1.2 => 5.3.3 
    react-scripts: 4.0.0 => 4.0.0 
  npmGlobalPackages:
    aws-cdk: 2.16.0
    corepack: 0.10.0
    npm: 8.1.2
    typescript: 4.6.2

```

</details>

### Describe the bug

Uploading a file with `Storage.put()` uses the file's extension for the `Type` in s3 bucket, rather than the provided `contentType` parameter. 

This results in an object with a blank type:
```js
await Storage.put("profile_photo", file, {
  contentType: "image/jpeg",
  level: "protected",
});
```

This results in an object with a type of "jpeg":
```js
await Storage.put("profile_photo.jpeg", file, {
  level: "protected",
});
```

### Expected behavior

It's my understanding that extensions (e.g. ".jpeg", ".txt") on s3 object names don't actually mean anything to s3, and it's the content type that's important for knowing what kind of file something is within a bucket. I could save a jpeg file as `test.txt` as long as I set the type to `image/jpeg`. 

I expect I should be able to upload an image with the name "profile_photo" and the type as "image/jpeg" and have the type in s3 set correctly, but currently it's empty.

### Reproduction steps

1. I am using an s3 bucket that only allows users to upload to a path with their Identity Pool, basically the default setup for the `protected` setting from Amplify Storage but I configured it manually with the `cdk`. Not sure if that's relevant, haven't tested uploads outside the "protected" setting yet.
2. Try to upload any file, I don't think it has to be an image file, with `Storage.put()`. Specify a `key` (e.g. "profile_photo") without any file extension, and in the `config` specify the appropriate `contentType` (e.g. "image/jpeg").
3. The object in s3 should have a blank type
<img width="781" alt="Screen Shot 2022-07-02 at 8 53 53 AM" src="https://user-images.githubusercontent.com/6494408/177001613-033b7dcc-eda6-4582-b03b-0e22fdf9e6ed.png">

4. Now upload the same file, but include the extension in the file name (e.g. "profile_photo.jpeg"). You can include the `contentType` or not, it doesn't seem to make a difference
5. The object should have the correct type now. This second screenshot did not specify a `contentType` when uploading.
<img width="539" alt="Screen Shot 2022-07-02 at 8 56 59 AM" src="https://user-images.githubusercontent.com/6494408/177001729-27f849c6-ff36-4a86-8391-af76d05cdf5d.png">

### Code Snippet

Here's more of the exact code I'm using to upload this file:

```javascript
// react component logic:
  async function handleImageUpload(e) {
    const file = e.target.files[0];
    const fileType = file.type;
    try {
      await Storage.put("profile_photo", file, {
        contentType: fileType,
        level: "protected",
      });
    } catch (error) {
      console.log("File upload error: ", error);
    }
  }

...

// inside component's `return`
<input
  accept="image/*"
  id="file_upload"
  type="file"
  onChange={handleImageUpload}
/>
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```js
export const config = {
  Auth: {
    region: "us-east-2",
    identityPoolId: "us-east-2:3f08395e-c375-4940-9033-e13e1eb7a4a8",
    userPoolId: "us-east-2_ls02q6o3A",
    userPoolWebClientId: "7fiai2ug4orp83rnf7bjjb5i4e",
    mandatorySignIn: true,
    authenticationFlowType: "USER_SRP_AUTH",
  },
  Storage: {
    AWSS3: {
      bucket: "stack-local-localuserimagesbucketuploadsbuc-jisnhwchzto6",
      region: "us-east-2",
    },
  },
};

export default config;
```

**Comment by ahilashsasidharan** [comment] 2022-07-14 03:00
I was able to reproduce the issue you are facing. It seems that the type will display based on the file's extension, but as you said, the file extension shouldn't affect anything in s3. As far as I could tell from my testing, except for the type displayed, it doesn't. As far as behavior is concerned, it looks like s3 will refer to the contentType in metadata. This means if you upload a file with a key with the .jpeg extension but set the contentType to text/html it will treat the file as an html, so logging into the AWS console and downloading the file from the bucket means the file will download as an html file. The same will happen if you use storage.get request to get the file and download it. This extension problem only seems to create issues for text/plain contentType where s3 doesn't add its type, so whatever extension you have will be indentified as the file type when downloaded. Even when you don't specify a contentType, as you mentioned in your issue the type displayed in the bucket won't influence how the file is treated. Instead, the contentType will default to binary/octet-stream, which seems to be the default when the contentType is unknown. It appears to be treated as such since when getting a link for the file using storage.get the link will download instead of displaying like an image as expected. The metadata where contentType will be stored can be accessed by going to the bucket, clicking on the file, and scrolling down. Overall it seems like the type doesn't affect behavior, so it is a bit wonky. I still need to test whether the same behavior happens with type when uploading directly to the s3 API. I will update the comment when I do. I have attached some of the tests and results I did for this issue in this document: 
https://docs.google.com/document/d/1RWr9XZBxHL4-OLI2uV0aZT14yagVPdI2qjNp7tH8Izo/edit?usp=sharing

**Comment by ahilashsasidharan** [comment] 2022-07-27 19:18
I added a change to the amplify documentation under JavaScript -> Storage-> upload files section (refer to where I mentioned this issue above for the PR) to clarify the behavior found through this issue. This should prevent confusion due to the behavior of Type in AWS S3 Console not matching the contentType stored in metadata of the S3 object, which as you stated, determines the behavior of how the file is treated in S3.

**Closed** 2022-07-27 19:19 UTC
Labels: good first issue, Storage, pending-triage
