### ISSUE TITLE
Invalid state in OAuth flow

### ISSUE THREAD

**Issue by demsey2** [aws-amplify/amplify-js#3055] opened 2019-04-09 20:42 UTC
When I log in through the hosted UI, I am redirected to my domain with a code. All was working fine with version 1.1.23, when I upgraded to 1.1.25 I got an exception "Invalid state in OAuth flow"

The exception is thrown from 
```
OAuth.prototype._validateState = function (urlParams) {
        if (!urlParams) {
            return;
        }
        var savedState = oAuthStorage.getState();
        var returnedState = urlParams.state;
        if (savedState !== returnedState) {
           throw new Error('Invalid state in OAuth flow');
        }
    };
```
When I check savedState and returnedState, savedState is null and returnedState is undefined

 - Device: MacBook Pro
 - OS: 10.13.6
 - Browser Chrome
 - Version 73

[DEBUG] 36:20.15 AuthClass - getting current authenticted user
ConsoleLogger.js:78 [DEBUG] 36:20.77 AuthClass - cannot load federated user from auth storage
ConsoleLogger.js:78 [DEBUG] 36:20.78 AuthClass - get current authenticated userpool user
ConsoleLogger.js:78 [DEBUG] 36:20.78 AuthClass - Failed to get user from user pool
ConsoleLogger.js:88 [DEBUG] 36:20.79 AuthClass - The user is not authenticated by the error

**Comment by manueliglesias** [comment] 2019-04-09 22:10
Hi @demsey2 

Are you using `Auth.federatedSignIn()` or manually building a url to cognito hosted ui?

With the recent changes to federation, crafting your own url to cognito hosted ui won't work, since it won't have the expected state and or PKCE params for extra security

**Comment by demsey2** [comment] 2019-04-09 22:28
I create my own url

**Comment by manueliglesias** [comment] 2019-04-09 22:56
can you try with `Auth.federatedSignIn()`? let me know if it doesn't cover your use case

**Comment by CaryLandholt** [comment] 2019-04-10 04:48
Yes, this was a break for us too.
Signing in via `https://<your_domain>/login?response_type=code&client_id=<your_app_client_id>&redirect_uri=<your_callback_url>`
results in an **Invalid state in OAuth** flow exception.

We have users that SSO into our site using the following scheme.
`https://<your_domain_prefix>.auth.us-east-1.amazoncognito.com/oauth2/authorize?response_type=code&client_id=<your_app_client_id>&redirect_uri=<your_callback_url>&identity_provider=<your_identity_provider>`, which broke with the recent change.

Since our users aren't trigger the federated sign in action on our site, but instead launching from their own portal and SSOing into our site, any recommendations on how to address this?

**Comment by tamdilip** [comment] 2019-04-10 05:27
Even we manually build the url to cognito hosted ui, but that approach breaks with the latest version expecting "state" in the callback url along with "code".

New approach to redirect to cognito hosted ui -

`Auth.federatedSignIn({ provider: 'your_identity_provider' });`

This seems working with the latest version, which internally handles the URL construction automatically and also the other required params for `federatedSignIn`  -"provider, tokens, expires_at ..." are optional now it seems ( #2716 ), so just mentioning the provider alone should directly takes to your IDP sign in page.

**Comment by CaryLandholt** [comment] 2019-04-10 05:30
@tamdilip thanks - that does seem to work if signing in is initiated via `Auth.federatedSignIn({ provider: 'your_identity_provider' });`, but our users initiate outside of our app, from their employer's portal, where they don't have access to the `Auth.federateSignIn` action.

**Comment by Goues** [comment] 2019-04-10 09:31
Hi, we have the same problem with `@aws-amplify/auth` version `1.2.21`. Our setup is basically this:

```
Auth
	.currentAuthenticatedUser()
	.then(doSomething)
	.catch(redirectToHosterUI)
```

We use Congito's UI where users can login using Google account. After logging in, they are redirected to

https://our.domain/login.php?code={code}

At this point, amplify fails with said error. This happenned after upgrading from `1.2.18`.

**Comment by Goues** [comment] 2019-04-10 09:32
p.s.: this is a duplicate of #3054

**Comment by danludwig** [comment] 2019-04-10 13:21
Hi, I am the author of #3054. Does the Auth.federatedSignIn allow the passing of a custom state argument now or not? We were constructing a manual URL because at the time the code was written, amplify offered no way to pass a value for that querystring parameter.

**Comment by manueliglesias** [comment] 2019-04-10 19:11
Hi,

I am working on a fix for this, thanks for the patience.

**Closed** 2019-04-10 23:21 UTC
Labels: review

**Comment by manueliglesias** [comment] 2019-04-10 23:41
Hi, can you try?

aws-amplify@1.1.26-unstable.0
aws-amplify-react@2.3.6-unstable.0

**Comment by ChristineMLew** [comment] 2019-04-11 00:45
I am also encountering this issue and just tried those new versions.  Unfortunately the error still occurs `exception "Invalid state in OAuth flow`

**Comment by manueliglesias** [comment] 2019-04-11 01:02
@ChristineMLew please make sure session storage is cleared before you try it (you might have `state` from a previous run)

Also, can you paste the output of:

```sh
yarn list --depth 0 | grep amplify
# or 
npm list --depth 0 | grep amplify
```

**Comment by JiboStore** [comment] 2020-04-30 02:21
Hi, I am using
`Auth.federatedSignIn({Provider: "Facebook"});` and get the same error, any idea?

**Comment by tamdilip** [comment] 2020-04-30 16:48
> Hi, I am using
> `Auth.federatedSignIn({Provider: "Facebook"});` and get the same error, any idea?

@JiboStore Not sure, but have u tried mentioning "identityProvider" along with the auth config attributes and just call with "Auth.federatedSignIn()" without passing over here as a param.

**Comment by sagun786** [comment] 2020-06-02 07:47
Hi I am using the browser to hit the manually created url to test it before using Postman/Insomnia to test whether facebook login has been correctly integrated or not and to generate a token. I am getting the same error of invalid state when I use insomnia but when I use the browser it works fine. What optional parameters can I include like STATE AND PKCE params that will solve this 

https://mydomain.auth.ap-southeast-1.amazoncognito.com/login?response_type=code&client_id=56n1ij8fich189q4e5inkjb8nc&redirect_uri=<REDIRECT-URL>

**Comment by AlexWang-16** [comment] 2020-08-28 18:52
II'm also getting this issue with my react application while using amplify. I have version 3.0.23.
