### ISSUE TITLE
Bypass verification on signup   

### ISSUE THREAD

**Issue by techlando** [aws-amplify/amplify-js#10747] opened 2022-12-06 05:04 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/d11dv10hkl0k7g/settings/general

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

I am using Amplify for authorization on my app. my app is for kids and will not require a email or phone number for sign up. I can not seem to bypass the verification for amplify on custom sign up.... please help

**Comment by nadetastic** [comment] 2022-12-06 17:56
Hi @techlando 👋

As @arundna mentioned could you describe a bit more how you have you project setup? Mainly confirm if you are using the UI components?

Also if you followed any guides for this please share the link with me.

**Comment by nadetastic** [comment] 2022-12-06 19:09
A few more questions on this @techlando - It sounds like you are working on implementing some sort of auto sign-up/auto verify of the users on your app.

Can you elaborate more on this?

**Comment by techlando** [comment] 2022-12-07 00:06
@nadetastic Thank you so much for the quick follow up.

I am currently using  Auth UI components for Authentication on my react native app. currently when I change the settings in  MFA and verification in cognito console to bypass verification I get this error... 
<img width="1407" alt="Screen Shot 2022-12-06 at 5 18 48 PM" src="https://user-images.githubusercontent.com/98988726/206051605-6400f6b0-be5f-409f-9ce4-6d012e97aa97.png">

I have read docs, on running a preSign up lambda trigger function but also am receiving an error when doing this. here is my lambda function 
<img width="779" alt="Screen Shot 2022-12-06 at 5 20 02 PM" src="https://user-images.githubusercontent.com/98988726/206052377-5c29863b-0b35-4588-b826-3db2c01d6407.png">


I am currently using withAuthenticator higher order function to test authentication flow.. after I can successfully signup without verification I plan on implementing the Auth components in my custom UI.

I am happy to answer any question and will work on responding quickly. thank you again for the help.

**Comment by techlando** [comment] 2022-12-07 00:10
reference:
https://docs.amplify.aws/lib/auth/emailpassword/q/platform/react-native/#sign-out
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

**Comment by techlando** [comment] 2022-12-07 02:11
so update here, I finally got it to work!! yay! I got the lambda function to work. here is the updated code 

<img width="779" alt="Screen Shot 2022-12-06 at 5 20 02 PM" src="https://user-images.githubusercontent.com/98988726/206070288-ed321400-5671-4aa1-afdf-287c9ceb99dc.png">

I do have one more question though.... Because I am bypassing verification, is it true that reset password component wont work??? 

My team do not plan on implementing any kind of verification, but we do need reset password to work, guidance here would be helpful

**Comment by techlando** [comment] 2022-12-08 17:05
Any update on my follow up question...
Can we still use reset password without verification?

**Comment by nadetastic** [comment] 2022-12-08 20:20
Hi @techlando glad you were able to get some movement.

Regarding you follow up question, you should still be able to reset the password be either:
- Using [admin actions](https://docs.amplify.aws/cli/auth/admin/) to reset a user's password
- Using [`Auth.forgotPassword()`](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#forgotpassword)

Note that both of these flows will eventually result in a code being sent to the verified contact tied to the user account.

**Comment by techlando** [comment] 2022-12-08 21:26
@nadetastic thank you. 
I think I understand but just to clarify... if I'm requiring just username and password for sign in, and user needs to reset password. They still will need to get a code, via phone # or email? There is no way to bypass this step at all.. if I understand correctly 


Thank you in advance and I apologize for being amplify newbie lol

**Comment by techlando** [comment] 2022-12-11 00:03
@nadetastic

**Comment by nadetastic** [comment] 2022-12-12 15:58
Hi @techlando, apologies for the delay. I wanted to clarify this flow with the Cognito team. As mentioned, a reset to the user password will at some point send a verification code to the user based on the email or phone number they have confirmed since reseting the password will change the user accounts confirmation status.

Also note that if the user does not have a verified contact (phone or email) then attempting to reset the password will result in an error such as `Cannot reset password for the user as there is no registered/verified email or phone_number`

**Comment by techlando** [comment] 2022-12-12 16:34
@nadetastic Thank you so much!🙏🙏🙏

**Comment by nadetastic** [comment] 2022-12-20 14:54
@techlando happy to help - Let me know if you have any more questions regarding this issue. If not feel free to close it out

**Closed** 2022-12-20 15:48 UTC
Labels: question, Auth, React Native, transferred
