### ISSUE TITLE
Sign up form validation not working with "required" formField

### ISSUE THREAD

**Issue by borisdayma** [aws-amplify/amplify-js#6885] opened 2020-09-28 21:53 UTC
**Describe the bug**

In the sign up form, "required" fields are only considered for email, username and password.
The form does not catch any incomplete fields that have been set to "required".

**To Reproduce**

In Vue, create a sign up form from `<amplify-sign-up>` component and add some required formFields.
Then you can still sign-up without filling in those required fields.

**Expected behavior**
We should get a notification mentioning that those fields are required

**Code Snippet**

```vue
<template>
  <amplify-authenticator username-alias="email">
    <amplify-sign-up
      slot="sign-up"
      username-alias="email"
      :form-fields.prop="formFields"
    />
  </amplify-authenticator>
</template>

<script>
export default {
  data() {
    return {
      formFields: [
        {
          type: 'email',
          required: true,
        },
        {
          type: 'given_name',
          label: 'First Name *',
          placeholder: 'Enter your first name',
          required: true,
        },
        {
          type: 'password',
          required: true,
        },
        {
          type: 'phone_number',
          required: true,
        },
      ],
    }
  },
}
</script>
```

**Screenshots**

We can create an account without filling in "First name" and "Phone Number", which are required fields.

![image](https://user-images.githubusercontent.com/715491/94489156-9670ae80-01a9-11eb-981f-2ce19f37857c.png)

Once, I got a message saying that given_name was required but it never happened again…

**Additional information**

I see there is a `validationData` parameter which appears to be empty.
I assume it should be completed based on these `required` parameters.
It would be nice to also explain how to use it for more complex scenarios.

**Comment by amhinson** [comment] 2020-10-19 16:49
@borisdayma Could you also share what version of the Amplify packages you are using?

**Comment by borisdayma** [comment] 2020-10-28 22:52
I use:
`@aws-amplify/ui v2.0.2`
`aws-amplify v3.3.1`

**Comment by sammartinez** [comment] 2020-11-16 22:05
@borisdayma Thanks for reporting this, in checking the code, I am seeing this as a miss on our side and we need to further step up validation for fields besides phone number, email, and password as you have called out. I do want to call out that we are busy with other priorities within the library and may not get to this for a little bit of time. However, if you are up for it, we would accept a contribution from you if this is something you are want to work on if you have time yourself. Thanks ahead of time!

**Comment by ericclemmons** [comment] 2020-11-16 22:11
Here are the two places that could have `required` added:

https://github.com/aws-amplify/amplify-js/blob/dbd46299af9c558251b8c652c3e50208982655c8/packages/amplify-ui-components/src/components/amplify-form-field/amplify-form-field.tsx#L53-L63

https://github.com/aws-amplify/amplify-js/blob/dbd46299af9c558251b8c652c3e50208982655c8/packages/amplify-ui-components/src/components/amplify-input/amplify-input.tsx#L46-L57

If it's passed along there, these inputs should automatically get HTML5 `required` validation!

**Comment by krikork** [comment] 2020-12-10 04:23
I recently migrated to @aws-amplify/ui-react from aws-amplify-react so I can leverage the support for SSR with nextjs and am struggling with the same issue.

**Comment by mattschutt** [comment] 2020-12-24 02:45
This is also happening on the React reset password screen.  I had to do a lot of customization and copying code out of the library to be able to simply send down the 'name' field.  I would love to just tell it to render the require fields and handle it.

Looks like this happened in the Angular library as well:  https://github.com/aws-amplify/amplify-js/issues/5636

**Comment by ironspur5** [comment] 2021-03-30 15:59
Any updated on enforcing the required flag? I have custom attributes defined in form fields on sign up, and have set them to be required. Yet, I am able to sign up without them, still.

**Comment by nstilesm** [comment] 2021-05-12 16:04
Still running into this issue where adding the below does not throw an error when the field is not filled out.
```js 
required: true
```

### Current Version
- @aws-amplify/ui-react 1.0.0
- aws-amplify 4.0.0

**Comment by jo2** [comment] 2021-06-01 14:17
Is there anything new on this issue? 

> Here are the two places that could have `required` added:
> 
> https://github.com/aws-amplify/amplify-js/blob/dbd46299af9c558251b8c652c3e50208982655c8/packages/amplify-ui-components/src/components/amplify-form-field/amplify-form-field.tsx#L53-L63
> 
> https://github.com/aws-amplify/amplify-js/blob/dbd46299af9c558251b8c652c3e50208982655c8/packages/amplify-ui-components/src/components/amplify-input/amplify-input.tsx#L46-L57
> 
> If it's passed along there, these inputs should automatically get HTML5 `required` validation!

As far as I've seen, the required field is not used in https://github.com/aws-amplify/amplify-js/blob/56deb453a2b31ac8c7f53741507dca7df8ef7fa8/packages/amplify-ui-components/src/components/amplify-select/amplify-select.tsx#L71-L78 and https://github.com/aws-amplify/amplify-js/blob/56deb453a2b31ac8c7f53741507dca7df8ef7fa8/packages/amplify-ui-components/src/components/amplify-input/amplify-input.tsx#L117-L136

I kind of need this feature, so I could submit a PR if you want.

**Comment by jacoblogan** [comment] 2021-06-15 17:59
This issue has been reproduced and is being worked on

**Comment by eddiekeller** [comment] 2021-06-16 16:17
Merged in PR ^^ to fix the `required` prop not doing anything on those inputs. I will close this ticket now, but please open it back up or submit a new ticket to us if any issues remain for you!

**Closed by eddiekeller** 2021-06-16 16:17 UTC
Labels: UI, needs-discussion
