### ISSUE TITLE
API returns the same result when calling an endpoint multiple times

### ISSUE THREAD

**Issue by lifercode** [aws-amplify/amplify-js#8036] opened 2021-04-06 17:55 UTC
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

REST API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
    Memory: 863.70 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @aws-amplify/ui-react: ^0.2.28 => 0.2.31 
    @stripe/stripe-js: ^1.11.0 => 1.11.0 
    @tanem/react-nprogress: ^3.0.51 => 3.0.51 
    @types/color: ^3.0.1 => 3.0.1 
    @types/node: ^14.14.7 => 14.14.12 
    @types/react: ^16.9.56 => 16.14.2 
    @types/react-beautiful-dnd: ^13.0.0 => 13.0.0 
    @types/react-dom: ^16.9.0 => 16.9.10 
    @types/react-router-dom: ^5.1.3 => 5.1.6 
    @types/react-select: ^3.0.26 => 3.0.27 
    @types/styled-components: ^5.1.0 => 5.1.5 
    @typescript-eslint/eslint-plugin: ^4.7.0 => 4.9.1 
    @typescript-eslint/parser: ^4.7.0 => 4.9.1 
    @uppy/core: ^1.15.0 => 1.15.0 
    @uppy/dashboard: ^1.14.0 => 1.14.0 
    @uppy/image-editor: ^0.2.0 => 0.2.0 
    @uppy/locales: ^1.17.1 => 1.17.1 
    @uppy/react: ^1.11.0 => 1.11.0 
    @uppy/transloadit: ^1.6.16 => 1.6.16 
    @uppy/webcam: ^1.8.2 => 1.8.2 
    aws-amplify: ^3.3.16 => 3.3.16 
    aws-sdk: ^2.834.0 => 2.834.0 
    axios: ^0.21.1 => 0.21.1 
    color: ^3.1.2 => 3.1.3 
    date-fns: ^2.16.1 => 2.16.1 
    eslint: ^7.13.0 => 7.15.0 
    eslint-config-prettier: ^6.11.0 => 6.15.0 
    eslint-plugin-prettier: ^3.1.4 => 3.2.0 
    eslint-plugin-react: ^7.20.3 => 7.21.5 
    eslint-plugin-security: ^1.4.0 => 1.4.0 
    prettier: ^2.0.5 => 2.2.1 
    query-string: ^6.13.8 => 6.13.8 
    react: ^17.0.1 => 17.0.1 
    react-beautiful-dnd: ^13.0.0 => 13.0.0 
    react-calendly: ^1.3.0 => 1.3.0 
    react-custom-scrollbars: ^4.2.1 => 4.2.1 
    react-dom: ^17.0.1 => 17.0.1 
    react-easy-crop: ^3.3.1 => 3.3.1 
    react-helmet: ^6.1.0 => 6.1.0 
    react-hook-form: ^6.11.2 => 6.12.2 
    react-phone-input-2: ^2.13.9 => 2.13.9 
    react-query: ^2.26.2 => 2.26.4 
    react-query-devtools: ^2.6.3 => 2.6.3 
    react-responsive-modal: ^6.0.0 => 6.0.0 
    react-router-dom: ^5.1.2 => 5.2.0 
    react-scripts: 4.0.0 => 4.0.0 
    react-select: ^3.1.0 => 3.1.1 
    react-truncate: ^2.4.0 => 2.4.0 
    react-webcam: ^5.2.2 => 5.2.2 
    sanitize-html: ^2.2.0 => 2.2.0 
    slugify: ^1.4.6 => 1.4.6 
    sockette: ^2.0.6 => 2.0.6 
    styled-components: ^5.0.0 => 5.2.1 
    styled-media-query: ^2.1.2 => 2.1.2 
    twilio: ^3.55.0 => 3.55.1 
    typescript: ~4.0.5 => 4.0.5 
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.2
    @nestjs/cli: 7.5.3
    code-push-cli: 2.1.9
    create-react-app: 3.4.1
    expo-cli: 4.3.0
    install-peerdeps: 2.0.3
    ios-deploy: 1.10.0
    json-server: 0.16.1
    node-gyp: 7.0.0
    npm: 6.14.4
    react-native-rename: 2.7.0

```

</details>

### Describe the bug

When I call the same endpoint several times, it seems that amplify saves the return in the cache and always returns the result generated on the first call.

But if i open an anonymous tab in broswer it will reprocess the enspoint and give me the correct result.

### Expected behavior

Ideally, the endpoint should be processed again with each call, and the result of the current call returned to me.

### Reproduction steps

1. call the endpoint /callback passing parameters of success;
2. call the endpoint /callback by passing fault parameters;

Expected: the second call always returns the same result as the first.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Describe the bug

When I call the same endpoint several times, it seems that amplify saves the return in the cache and always returns the result generated on the first call.

But if i open an anonymous tab in broswer it will reprocess the enspoint and give me the correct result.

---

### Expected behavior

Ideally, the endpoint should be processed again with each call, and the result of the current call returned to me.

---

### Reproduction steps:

1. call the endpoint /callback passing parameters of success;
2. call the endpoint /callback by passing fault parameters;

Expected: the second call always returns the same result as the first.

**Comment by iartemiev** [comment] 2021-04-07 14:06
The API category of AmplifyJS does not cache requests. It's essentially a pass-through to Axios with added convenience functionality for auth and interacting with API Gateway.

Could you share your library code and config?

**Comment by sammartinez** [comment] 2021-05-18 15:53
@lifercode,

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 15:53 UTC
Labels: API, pending-close-response-required
