### ISSUE TITLE
Error uploading on S3 through amplify storage reactjs

### ISSUE THREAD

**Issue by nerxhan-eduongo** [aws-amplify/amplify-js#7117] opened 2020-11-04 20:20 UTC
I'm using the latest version of **aws-amplify** 3.3.7 on **reactjs**

This is the code

````
const s3Upload = async (file) => { 
    const filename = file.name.replace(/\s/g, '') 
    await Storage.vault.put(filename, file, { 
      contentType: file.type 
   })
}
````

When I try to upload small files (1 Mb file) it works fine, but when I try to upload bigger files i.e. 6 Mb zip file, I'm getting the error:

```
AWSS3ProviderManagedUpload - error happened while finishing the upload. Cancelling the multipart upload Error: Request failed with status code 40

```
Anyone faced this problem

**Comment by sw-yx** [comment] 2020-11-04 22:07
@iartemiev this looks similar to https://github.com/aws-amplify/amplify-js/issues/5873

**Comment by nerxhan-eduongo** [comment] 2020-11-05 09:44
so you suggest me to downgrade to version **3.0.13** . I guess I have tried that one, but didn't works for me

**Comment by sw-yx** [comment] 2020-11-05 09:56
no it wasnt a suggestion, i was tagging the engineer that fixed this last time

**Comment by shenmander** [comment] 2020-11-18 11:26
any solution? getting the same problem

**Comment by nerxhan-eduongo** [comment] 2020-11-18 11:38
I have implement this solution on my S3 bucket https://stackoverflow.com/questions/64681196/error-uploading-on-s3-through-amplify-storage-reactjs, and is working, not sure how secure is this

**Comment by sammartinez** [comment] 2021-03-23 22:02
@nerxhan-eduongo Are you still experiencing this on the latest version of `aws-amplify`? We have resolved similar issues for multi-part with upgrades to our `aws-sdk` dependenices. Please let us know.

**Comment by iartemiev** [comment] 2021-04-12 18:20
@nerxhan-eduongo,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:20 UTC
Labels: Build, Storage, pending-close-response-required

**Comment by danielvouch** [comment] 2021-08-17 08:18
We are having a similar issue to this using nuxt/vue, some users are receiving this error when uploading video files (mostly mp4 files). - `AWSS3ProviderManagedUpload - error happened while uploading a part. Cancelling the multipart upload`.

The network call is as follows
```
POST `https://<bucket>.s3.<region>.amazonaws.com/<key>.mp4?uploads=` 200
DELETE https://<bucket>.<region>.amazonaws.com/<key>.mp4?uploadId=<UploadId>x-id=AbortMultipartUpload 204
```

Any ideas why this action would be failing?
