### ISSUE TITLE
adminUpdateUserAttributes - Update another user attributes

### ISSUE THREAD

**Issue by jaing** [aws-amplify/amplify-js#5103] opened 2020-03-15 21:56 UTC
Is there a way we can update another user attributes?
In AWS docs i see that there is a method - adminUpdateUserAttributes - but how to use it with Amplify library?

 I.e. when user reply to a post I want to change a rating of a person that started a thread. I want to have a single point of user data and keep all attributes in cognito not to divide it between cognito and i.e. dynamodb.

**Comment by jeremysouthon** [comment] 2020-12-09 01:49
I don't think there is a way to use `adminUpdateUserAttributes` via Amplify. The way I managed to use this was by creating a lambda function, importing the `aws-sdk`  and using `adminUpdateUserAttributes` from there.

My use case was to allow an admin to update users emails.

**Comment by tannerabread** [comment] 2023-02-27 23:46
Closing as a duplicate of #6704. Both asking for adminUpdateUserAttributes to be implemented and the other feature-request has a recent workaround available plus more information.

Thank you for opening this feature request and please follow the other for more information on progress

**Closed by tannerabread** 2023-02-27 23:46 UTC
Labels: feature-request, Auth
