### ISSUE TITLE
React Native - AWSS3Provider - ensure credentials error cannot get guest credentials

### ISSUE THREAD

**Issue by blakecallens** [aws-amplify/amplify-js#9599] opened 2022-02-16 20:48 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, Storage

### Amplify Categories

auth, storage

### Environment information

<details>

```
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
    Memory: 597.18 MB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/bin/node
    npm: 6.14.15 - /usr/bin/npm
    Watchman: 20220130.171601.0 - /usr/local/bin/watchman
  Browsers:
    Firefox: 96.0
  npmPackages:
    @apollo/client: ^3.5.8 => 3.5.8 
    @apollo/client/cache:  undefined ()
    @apollo/client/core:  undefined ()
    @apollo/client/errors:  undefined ()
    @apollo/client/link/batch:  undefined ()
    @apollo/client/link/batch-http:  undefined ()
    @apollo/client/link/context:  undefined ()
    @apollo/client/link/core:  undefined ()
    @apollo/client/link/error:  undefined ()
    @apollo/client/link/http:  undefined ()
    @apollo/client/link/persisted-queries:  undefined ()
    @apollo/client/link/retry:  undefined ()
    @apollo/client/link/schema:  undefined ()
    @apollo/client/link/utils:  undefined ()
    @apollo/client/link/ws:  undefined ()
    @apollo/client/react:  undefined ()
    @apollo/client/react/components:  undefined ()
    @apollo/client/react/context:  undefined ()
    @apollo/client/react/hoc:  undefined ()
    @apollo/client/react/hooks:  undefined ()
    @apollo/client/react/parser:  undefined ()
    @apollo/client/react/ssr:  undefined ()
    @apollo/client/testing:  undefined ()
    @apollo/client/testing/core:  undefined ()
    @apollo/client/utilities:  undefined ()
    @apollo/client/utilities/globals:  undefined ()
    @babel/core: ^7.12.9 => 7.16.12 
    @babel/runtime: ^7.12.5 => 7.16.7 
    @fortawesome/fontawesome-svg-core: ^1.2.36 => 1.2.36 
    @fortawesome/free-solid-svg-icons: ^5.15.4 => 5.15.4 
    @fortawesome/react-native-fontawesome: ^0.2.7 => 0.2.7 
    @react-native-async-storage/async-storage: ^1.15.17 => 1.15.17 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @react-native-community/netinfo: ^7.1.9 => 7.1.9 
    @react-native-masked-view/masked-view: ^0.2.6 => 0.2.6 
    @react-native-picker/picker: ^2.2.1 => 2.2.1 
    @types/jest: ^26.0.23 => 26.0.24 
    @types/lodash-es: ^4.17.6 => 4.17.6 
    @types/luxon: ^2.0.9 => 2.0.9 
    @types/react-native: ^0.66.15 => 0.66.15 
    @types/react-test-renderer: ^17.0.1 => 17.0.1 
    @typescript-eslint/eslint-plugin: ^5.7.0 => 5.10.2 (3.10.1)
    @typescript-eslint/parser: ^5.7.0 => 5.10.2 (3.10.1)
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.6 => 5.2.6 
    aws-amplify: ^4.3.14 => 4.3.14 
    aws-amplify-react-native: ^6.0.2 => 6.0.2 
    babel-jest: ^26.6.3 => 26.6.3 
    eslint: ^7.14.0 => 7.32.0 
    graphql: ^16.3.0 => 16.3.0 (15.8.0)
    hermes-inspector-msggen:  1.0.0 
    intl: ^1.2.5 => 1.2.5 
    jest: ^26.6.3 => 26.6.3 
    lodash-es: ^4.17.21 => 4.17.21 
    luxon: ^2.3.0 => 2.3.0 
    metro-react-native-babel-preset: ^0.66.2 => 0.66.2 
    native-base: ^3.3.4 => 3.3.4 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.1 => 0.67.1 
    react-native-device-info: ^8.4.9 => 8.4.9 
    react-native-linear-gradient: ^2.5.6 => 2.5.6 
    react-native-safe-area-context: ^3.3.2 => 3.3.2 
    react-native-skeleton-placeholder: ^5.0.0 => 5.0.0 
    react-native-svg: ^12.1.1 => 12.1.1 
    react-router-native: ^6.2.1 => 6.2.1 
    react-test-renderer: 17.0.2 => 17.0.2 
    rn-fetch-blob: ^0.12.0 => 0.12.0 
    typescript: ^4.4.4 => 4.5.5 
  npmGlobalPackages:
    @angular/cli: 13.1.2
    eslint: 7.29.0
    npm: 6.14.15
    webpack-bundle-analyzer: 4.5.0


```

</details>

### Describe the bug

After authentication using the `aws-amplify-react-native` library, a call to `Storage.get` with values that work on web throws:
```
 AWSS3Provider - ensure credentials error cannot get guest credentials when mandatory signin enabled
```
This appears similar to issues #1273 and #6096, which were resolved in updated versions of the library. This leads me to believe that this fix has perhaps not been migrated to `aws-amplify-react-native`, because I previously encountered an issue with that library's use of a deprecated `AsyncStorage` module, which required a workaround.

### Expected behavior

After logging in through the `Auth` library, `Storage.get` should make use of the session.

### Reproduction steps

1. Install `aws-amplify` and `aws-amplify-react-native` in a React Native project.
2. Configure Amplify for Cognito and S3.
3. Use `Auth` to sign in through Cognito.
4. Attempt to connect to S3 through the Storage library.

### Code Snippet

```TypeScript
import {environment} from '../../environment';
import Amplify from 'aws-amplify';

// ...

const region = 'us-east-1';
Amplify.configure({
  Auth: {
    region,
    identityPoolId: environment.cognito.IdentityPoolId,
    userPoolId: environment.cognito.UserPoolId,
    userPoolWebClientId: environment.cognito.ClientId,
    authenticationFlowType: 'USER_PASSWORD_AUTH',
    mandatorySignIn: true,
  },
  Storage: {
    AWSS3: {
      bucket: environment.s3.Bucket,
      region,
      customPrefix: {
        public: '',
      },
    },
  },
});

// ... After sign in through Cognito
const rawFiles: S3ProviderListOutputItem[] = await Storage.list('[s3-url]');
// Error thrown
```

### Log output

<details>
 WARN  [WARN] 40:27.67 AWSS3Provider - ensure credentials error cannot get guest credentials when mandatory signin enabled
 ERROR  [Error: No credentials]
</details>

### Mobile Device

Android emulator

### Mobile Operating System

Android 11

### Additional information and screenshots

![Screenshot_1645044320](https://user-images.githubusercontent.com/39135/154354000-1e76b7a7-2534-428e-bfab-42ed82ed8c32.png)

**Comment by wtravO** [comment] 2022-02-17 17:28
Also need this fixed

**Comment by blakecallens** [comment] 2022-02-17 19:40
@chrisbonifacio, we are set up for Auth users only.

**Comment by chrisbonifacio** [comment] 2022-02-17 22:43
@blakecallens I have not been able to reproduce this behavior. I configured my app the same way and made sure I was authenticated but I did not get the mandatory signin error.

https://www.loom.com/share/d569f001565e445a9c73ab2a5ab8d91e

For reference and comparison, these are my storage cli inputs

```js
{
  "resourceName": "s307d73b29",
  "policyUUID": "07d73b29",
  "bucketName": "starter063640379be84c2f99b2df107a4ca1af",
  "storageAccess": "auth",
  "guestAccess": [],
  "authAccess": [
    "CREATE_AND_UPDATE",
    "READ",
    "DELETE"
  ],
  "triggerFunction": "NONE"
}
```

and these are my auth cli-inputs

```js
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "starter32a651c2_identitypool_32a651c2",
    "allowUnauthenticatedIdentities": true,
    "resourceNameTruncated": "starte32a651c2",
    "userPoolName": "starter32a651c2_userpool_32a651c2",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "starte32a651c2_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "sharedId": "32a651c2",
    "resourceName": "starter32a651c2",
    "authSelections": "identityPoolAndUserPool",
    "useDefault": "manual",
    "userPoolGroupList": [
      "admin"
    ],
    "serviceName": "Cognito",
    "usernameCaseSensitive": false,
    "useEnabledMfas": true,
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": true,
    "dependsOn": [],
    "thirdPartyAuth": false,
    "userPoolGroups": false,
    "adminQueries": false,
    "triggers": {},
    "hostedUI": false,
    "authProviders": [],
    "parentStack": {
      "Ref": "AWS::StackId"
    },
    "permissions": []
  }
}
```

**Comment by blakecallens** [comment] 2022-02-22 16:19
@chrisbonifacio any insight on that log output?

**Comment by calebpollman** [comment] 2022-02-22 17:10
@blakecallens Can you please comment with the content of your _package.json_? In particular curious about the dependencies

**Comment by blakecallens** [comment] 2022-02-23 15:34
@calebpollman here's the dependencies:

```JSON
{
  "dependencies": {
    "@apollo/client": "^3.5.8",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/react-native-fontawesome": "^0.2.7",
    "@react-native-async-storage/async-storage": "^1.15.17",
    "@react-native-community/netinfo": "^7.1.9",
    "@react-native-picker/picker": "^2.2.1",
    "amazon-cognito-identity-js": "^5.2.6",
    "aws-amplify": "^4.3.14",
    "aws-amplify-react-native": "^6.0.2",
    "graphql": "^16.3.0",
    "intl": "^1.2.5",
    "lodash-es": "^4.17.21",
    "luxon": "^2.3.0",
    "native-base": "^3.3.4",
    "react": "17.0.2",
    "react-native": "0.67.1",
    "react-native-device-info": "^8.4.9",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-svg": "^12.1.1",
    "react-router-native": "^6.2.1",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/lodash-es": "^4.17.6",
    "@types/luxon": "^2.0.9",
    "@types/react-native": "^0.66.15",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.7.0",
    "@typescript-eslint/parser": "^5.7.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
}
```

**Comment by Samaritan1011001** [comment] 2022-02-25 01:58
@blakecallens are you trying to migrate existing users using Lambda triggers, specifically do you have a modified Lambda trigger for the migration? I ask this as I can see that you set `authenticationFlowType: 'USER_PASSWORD_AUTH',` inside `Amplify.configure` .  Referring to this documentation [here](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js/#userpasswordauth-flow). 

Further, can you check whether you are seeing the error when you sign-up and sign-in as a new user?

**Comment by blakecallens** [comment] 2022-02-28 15:39
@Samaritan1011001 I'm getting info on the authentication configuration, since I wasn't the one to set it up. Will get back to you soon.

**Comment by blakecallens** [comment] 2022-03-01 20:15
@Samaritan1011001 We haven't done any user migration. We switched to SRP and have no change to the issue. This is for new and existing users.

**Comment by blakecallens** [comment] 2022-03-03 13:41
@chrisbonifacio what version of RN did you confirm this working with? Our app is running `0.67.1`.

**Comment by blakecallens** [comment] 2022-03-07 14:04
@chrisbonifacio @Samaritan1011001 another issue came up that leads me to believe this is due to the deprecated AsyncStorage moducle in `aws-amplify-react-native`.

I integrated Pinpoint into the application and it throws this error when trying to send in an event:

```
Possible Unhandled Promise Rejection (id: 1): Error: No credentials, applicationId or region
```

If these sub-libraries pull credentials from local device storage, and the current version of the library is using an AsyncStorage module that doesn't work with the latest ReactNative, then that could explain both of these issues. Here is my current workaround file. Perhaps there's something you know of that I could add to it and fix this issue.

```TypeScript
import AsyncStorage from '@react-native-async-storage/async-storage';

const MEMORY_KEY_PREFIX = '@MemoryStorage:';
let dataMemory: any = {};

/**
 * This fixes the aws-amplify-react-native deprecated AsyncStorage
 */
export default class AmplifyAuthStorageUtility {
  static setItem(key: string, value: string): string {
    AsyncStorage.setItem(`${MEMORY_KEY_PREFIX}${key}`, value, () => {});
    dataMemory[key] = value;
    return value;
  }

  static getItem(key: string): string | undefined {
    return dataMemory[key];
  }

  static removeItem(key: string): boolean {
    AsyncStorage.removeItem(`${MEMORY_KEY_PREFIX}${key}`);
    return delete dataMemory[key];
  }

  static clear(): any {
    dataMemory = {};
    return dataMemory;
  }

  static async sync(): Promise<any> {
    try {
      // Get all keys using the AWS prefix
      const keys = (await AsyncStorage.getAllKeys())?.filter((key: string) =>
        key.startsWith(MEMORY_KEY_PREFIX),
      );
      if (keys) {
        // Storage objects come back as [[key, value], [key, value]]
        // Convert them to {key: value} and add merge them into dataMemory
        const stores = await AsyncStorage.multiGet(keys);
        dataMemory = {
          ...dataMemory,
          ...stores.reduce(
            (memo: any, item: [string, string | null]) => ({
              ...memo,
              [item[0].replace(MEMORY_KEY_PREFIX, '')]: item[1],
            }),
            {},
          ),
        };
      }
    } catch (err) {
      console.error('AmplifyAuthStorageUtility - sync error', err);
      throw err;
    }
  }
}

```

**Comment by elorzafe** [comment] 2022-03-09 01:04
@blakecallens

How are you doing `signIn` in your App?

**Comment by elorzafe** [comment] 2022-03-09 18:42
Cool, can you share the code for `Auth.signIn` and from where are you importing it.

Can you also remove `amazon-cognito-identity-js` dependency from your `package.json`? Also can you clear `node_modules` directory and try again?

**Comment by blakecallens** [comment] 2022-03-10 20:28
@elorzafe I removed `amazon-cognito-identity-js` from the `package.json` and there was no change - which also means my AsyncStorage shim works without it too.

Here's my `AuthUtility` code, using `signIn` and `currentSessiion`. When I comment out my `AsyncStorage` shim, I get the error: `checkForSession error No current user` when reloading the app. Has `aws-amplify-react-native` been confirmed working with `react-native` `0.67.x`?

```TypeScript
import {CognitoUserSession} from 'amazon-cognito-identity-js'; // This is now coming from the aws-amplify dependency
import {Auth} from 'aws-amplify';

export default class AuthUtility {
  /**
   * Retrieves the current Cognito session
   * @returns The current session object
   */
  static async getCurrentSession(): Promise<CognitoUserSession> {
    try {
      return await Auth.currentSession();
    } catch (err) {
      console.log('AuthUtility - getCurrentSession error');
      throw err;
    }
  }

  /**
   * Retrieves the latest JWT token from Cognito
   * @returns The latest JWT token
   */
  static async getJwtToken(): Promise<string> {
    try {
      const session = await Auth.currentSession();
      return session.getIdToken().getJwtToken();
    } catch (err) {
      console.log('AuthUtility - getIdToken error');
      throw err;
    }
  }

  /**
   * Logs a user in through Cognito
   * @param username The user email
   * @param password The user password
   * @returns The authentication result
   */
  static async login(username: string, password: string): Promise<any> {
    try {
      return await Auth.signIn(username, password);
    } catch (err) {
      console.log('AuthUtility - login error');
      throw err;
    }
  }

  /**
   * Logs a user out through Cognito
   * @returns The authentication result
   */
  static async logOut(): Promise<any> {
    try {
      return await Auth.signOut();
    } catch (err) {
      console.log('AuthUtility - logOut error');
      throw err;
    }
  }
}


```

**Comment by elorzafe** [comment] 2022-03-10 22:04
@blakecallens the following setup worked for me

`package.json`
```json
{
  "name": "testcredentials",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.16.1",
    "@react-native-community/netinfo": "^8.1.0",
    "aws-amplify": "^4.3.15",
    "aws-amplify-react-native": "^6.0.3",
    "react": "17.0.2",
    "react-native": "0.67.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

`App.js`
```jsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import type {Node} from 'react';

import { Amplify, Auth, Storage } from 'aws-amplify';
import awsconfig from './src/aws-exports';

Amplify.Logger.LOG_LEVEL = 'DEBUG';

Amplify.configure(awsconfig);
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Button
} from 'react-native';

import {
  Colors,
  DebugInstructions,
  Header,
} from 'react-native/Libraries/NewAppScreen';

const Section = ({children, title}): Node => {
  function signIn() {
    Auth.signIn({
      username:'*******',
      password: '********'
    });
  }

  async function currentSession() {
    try {
      const user = await Auth.currentUserPoolUser();
      console.log({user});
    } catch (error) {
      console.log(error);
    }
  }

  async function upload() {
    try {
      const uploadResult = await Storage.put('test.txt', 'test 123');
      console.log({uploadResult});
    } catch(error) {
      console.log(error);
    }
  }

  async function download() {
    try {
      const data = await Storage.get('test.txt');
      const content = await (await fetch(data)).text();
      console.log({content});
    } catch (error) {
      console.log(error);
    }
  }

  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Button onPress={signIn} title="Sign in"></Button>
      <Button onPress={currentSession} title="Current session"></Button>
      <Button onPress={upload} title="Upload"></Button>
      <Button onPress={download} title="Download"></Button>
    </View>
  );
};

const App: () => Node = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Section title="Step One">
            Edit <Text style={styles.highlight}>App.js</Text> to change this
            screen and then come back to see your edits.
          </Section>
          
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;

```

**Comment by blakecallens** [comment] 2022-03-15 12:09
@elorzafe 

* What does your awsconfig look like? Does it differ from the one I provided with the bug? I'm wondering if there's a setting in mine that is blocking things.
* I see you've brought in the new AsyncStorage. Are you implementing my workaround? If so, does the session automatically reload when you kill and reopen the app, and does the Storage library still work then?

**Comment by elorzafe** [comment] 2022-03-15 18:46
@blakecallens 

This is my config file

```
const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxx",
    "oauth": {
        "domain": "xxxxxxxxxxx-xxxxxxxx-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "testCredentials://",
        "redirectSignOut": "testCredentials://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "xxxxxxxxx-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};
````
I haven't tried your workaround, for me it worked when refreshing the App but I will try on different devices just to confirm.

**Comment by elorzafe** [comment] 2022-03-15 21:28
@blakecallens 

I tested your code on simulator and on a real device and it works as expected. I had to add `amazon-cognito-identity-js` on my `package.json` in order to do the react-native link.

Sometimes there is an issue when packages are duplicated inside of `node_modules` can you check inside `@aws-amplify/auth` directory contains a nested `node_modules` that has `amazon-cognito-identity-js`?

**Comment by blakecallens** [comment] 2022-03-16 13:12
@elorzafe `react-native link` is something that isn't often run manually anymore, because RN has been updated to have auto-linking at build time or pod install now, and explicit linking by library name is deprecated. I think there may be something to our issue, if `aws-amplify-react-native` still requires it (RNAWSCognito is in the list of auto-linked libraries when I do a pod install, though). The [Getting Started Tutorial](https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native/) doesn't mention `react-native link`.

`@aws-amplify/auth` does not have a sub `node_modules` folder. I also modified my config to follow your format and was able to log in, but the issues persisted. What explicit `react-native link` are you running?

**Comment by elorzafe** [comment] 2022-03-16 18:57
I did `npx react-native link amazon-cognito-identity-js`

**Comment by elorzafe** [comment] 2022-03-16 18:58
What devices and OS are you testing the App? I tried on Android real device (Pixel 4a 5G) and simulator

**Comment by blakecallens** [comment] 2022-03-17 12:21
For Android, I'm running on a simulated Pixel XL (Android 11) and a physical LineageOS device. For iOS, I'm running in the simulator and a physical iPad (iOS 15).

I'm going to build a new RN app from scratch and see if your example works. I don't know if that will be good or bad if it does :) , because our app is essentially doing what your example does: `Amplify.configure -> Auth.signIn -> Storage.get` and Storage says there's no session right after signIn, though the token that comes back from that signIn works for ad hoc access to other services (outside of Amplify), such as the API Gateway to our GraphQL instance.

While I'm doing that, do you know of any backend settings, Cognito or otherwise, that may work for web, but prevent `aws-amplify-react-native` from properly storing the session?

**Comment by blakecallens** [comment] 2022-03-17 16:14
@elorzafe I have confirmed that the conflict is with `@apollo/client`. Not necessarily directly with it, but it requires that you extend your `metro.config.js` to resolve `cjs` files. By importing my app, piece by piece, into a new RN app where I confirmed your code working, this was the break point - all my abstracted context providers and whatnot worked and the session was retained by Amplify up unto the point where Apollo was brought in.

Here's my modified `metro.config.js`. Perhaps there's something I can add to this to ensure both Apollo and Amplify work. Worst case, I can use `fetch` to build a GraphQL service, but it would of course be preferable to be able to use both libraries.

```JavaScript
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const {getDefaultConfig} = require('metro-config');
const {resolver: defaultResolver} = getDefaultConfig.getDefaultValues();

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    ...defaultResolver,
    sourceExts: [...defaultResolver.sourceExts, 'cjs'],
  },
};
```

**Comment by elorzafe** [comment] 2022-03-18 18:24
@blakecallens 

Why do you need to use cjs in order to use `@apollo/client` on react-native?
Are you using an old version of react-native cli to configure the project?

**Comment by blakecallens** [comment] 2022-03-21 13:42
@elorzafe the latest version of `@apollo/client` (3.5.10) delivers has `main.cjs` as its entry point. I'm using core ReactNative, not Expo, which may already have `cjs` resolution in its settings.

From previous examples, it looks like you're testing in Expo. While it's a great framework that sits on top of RN, I wouldn't use it as a benchmark, because it's very opinionated about how it wraps RN.

**Comment by blakecallens** [comment] 2022-03-29 13:16
@elorzafe checking in. Do you have a way for both libraries to work in a pure RN build?

**Comment by chrisbonifacio** [comment] 2022-04-26 18:51
Closing as the issue was with a third party library, not a bug with the Amplify libraries.

**Closed by chrisbonifacio** 2022-04-26 18:51 UTC
Labels: Storage, React Native, pending-response

**Comment by oxbits** [comment] 2022-04-30 22:28
@chrisbonifacio I thought we had to use Apollo to work with AppSync.  Shouldn't Amplify work with AppSync?

@blakecallens I am having this same issue.  I tried rolling back to `npm install @apollo/client@3.4.17 --force` before Apollo's workaround, and now everything is blowing up.  I am wondering if the Apollo workaround can be made more specific so it only includes that one `main.cjs`?

here are links to the same issue over in Apollo:
https://github.com/apollographql/apollo-client/issues/9648
https://github.com/apollographql/apollo-client/issues/9194
https://github.com/apollographql/apollo-client/issues/9531
workaround:
https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19
