### ISSUE TITLE
withAuthenticator HOC has invalid dependency since React Native 0.66.1

### ISSUE THREAD

**Issue by kirkryan** [aws-amplify/amplify-js#9135] opened 2021-10-31 16:02 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 115.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 7.24.0 - /opt/homebrew/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.30
    Safari: 15.0
  npmPackages:
    @aws-amplify/datastore: ^3.5.1 => 3.5.1
    @babel/core: ^7.12.9 => 7.15.8
    @babel/runtime: ^7.12.5 => 7.15.4
    @react-native-async-storage/async-storage: ^1.15.9 => 1.15.9
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/netinfo: ^6.0.4 => 6.0.4
    @react-native-picker/picker: ^2.1.0 => 2.1.0
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^5.2.2 => 5.2.2
    aws-amplify: ^4.3.4 => 4.3.4
    aws-amplify-react-native: ^5.0.5 => 5.0.5
    babel-jest: ^26.6.3 => 26.6.3
    eslint: 7.14.0 => 7.14.0
    hermes-inspector-msggen:  1.0.0
    jest: ^26.6.3 => 26.6.3
    metro-react-native-babel-preset: ^0.66.2 => 0.66.2
    nanoid: ^3.1.30 => 3.1.30
    react: 17.0.2 => 17.0.2
    react-native: 0.66.1 => 0.66.1
    react-native-background-fetch: ^4.0.4 => 4.0.4
    react-native-background-geolocation: ^4.4.0 => 4.4.0
    react-native-get-random-values: ^1.7.0 => 1.7.0
    react-test-renderer: 17.0.2 => 17.0.2
  npmGlobalPackages:
    @aws-amplify/cli: 6.3.1
    gatsby-cli: 3.11.0
    npm: 7.24.0
    typescript: 4.3.5

```

</details>

### Describe the bug

When using the HOC for withAuthenticator, react-native now errors (before it used to warn and continue) that the picker component used in the phone field is no longer part of react-native.

```
ERROR  Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker

This error is located at:
    in PhoneField (at SignUp.tsx:275)
    in RCTView (at View.js:32)
    in View (at SignUp.tsx:255)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at SignUp.tsx:248)
    in TouchableWithoutFeedback (at AmplifyUI.tsx:261)
    in Wrapper (at SignUp.tsx:247)
    in SignUp (at Authenticator.tsx:233)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at AmplifyUI.tsx:47)
    in Container (at Authenticator.tsx:253)
    in Authenticator (at Auth/index.tsx:138)
    in Wrapper (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in testrig(RootComponent) (at renderApplication.js:60) 
```

The UI for SignUp.tsx needs to be updated (as well as any other components using picker) to depend on the correct source of picker as listed above (@react-native-picker/picker).

### Expected behavior

When pressing on the "Sign Up" button of the HOC the standard user registration form should display.

### Reproduction steps

1. Create fresh react-native project
2. Install amplify and auth as normal
`npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage` && `npx pod-install`
3. Wrap App component with Auth HOC
4. Start the app and the HOC is shown as below:
![image](https://user-images.githubusercontent.com/18603029/139592078-f82ec43e-04e1-4746-bebb-ad7223299952.png)
5. Press SignUp and the app will error:
![image](https://user-images.githubusercontent.com/18603029/139592093-175b8d72-2da6-42ad-9907-bf0bc2428c85.png)

Manually installing react-native-picker as suggested does not fix the issue.

### Code Snippet

```javascript
// Put your code below this line.
export default withAuthenticator(App);
```

### Log output

<details>

```
// Put your logs below this line
 ERROR  Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker

This error is located at:
    in PhoneField (at SignUp.tsx:275)
    in RCTView (at View.js:32)
    in View (at SignUp.tsx:255)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at SignUp.tsx:248)
    in TouchableWithoutFeedback (at AmplifyUI.tsx:261)
    in Wrapper (at SignUp.tsx:247)
    in SignUp (at Authenticator.tsx:233)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at AmplifyUI.tsx:47)
    in Container (at Authenticator.tsx:253)
    in Authenticator (at Auth/index.tsx:138)
    in Wrapper (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in testrig(RootComponent) (at renderApplication.js:60)

```

</details>

### Mobile Device

iPhone 12 Max

### Mobile Operating System

iOS 15.0

**Comment by kirkryan** [comment] 2021-10-31 20:25
@renebrandel - one to be aware of amigo.

**Comment by calebpollman** [comment] 2021-11-01 16:19
@kirkryan Thanks for opening the ticket, we are aware of the issue and working towards resolving it. 

Closing as a duplicate of https://github.com/aws-amplify/amplify-js/issues/6845

**Closed** 2021-11-01 16:19 UTC
Labels: React Native, pending-triage

**Comment by krrby** [comment] 2021-11-04 04:49
I am also getting this error at the moment :( I've tried to install picker it doesn't recognise it (for windows and Android
