### ISSUE TITLE
Getting Error in ADD Amplify Pluggable

### ISSUE THREAD

**Issue by saharJ95** [aws-amplify/amplify-js#10335] opened 2022-09-16 10:03 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

react-app-rewired

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

![image](https://user-images.githubusercontent.com/113641921/190614561-063cc979-6d35-4fd2-a20a-7c1515229673.png)

Hi There,
Issue : amplify.addPluggable throws error when deploy on Aws Amplify Project but works fine on Localhost

Node Version: v16.13.1
"aws-amplify": "^4.3.35",
"@aws-amplify/pubsub": "^4.5.3"

Locally everything is fine either its adding provider or creating mqtt connection but after deployment on amplify it throws above error

### What's the expected behaviour?

connected to AWSProvider Successfully

### Help us reproduce the bug!

![image](https://user-images.githubusercontent.com/113641921/190614381-20e21c81-cf47-41d9-861d-b6487eb3c85c.png)

### Code Snippet

```typescript
// Put your code below this line.

```
![image](https://user-images.githubusercontent.com/113641921/190614398-8075f288-fe6e-4964-bc25-0b5d2779c87e.png)

**Comment by tannerabread** [comment] 2022-09-16 18:32
Closing as duplicate of #10331

**Closed by tannerabread** 2022-09-16 18:32 UTC
