### ISSUE TITLE
Disable automatic token fetch?

### ISSUE THREAD

**Issue by Steve-OH** [aws-amplify/amplify-js#8303] opened 2021-05-19 13:08 UTC
### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

Scenario: I have a SPA using hash routing that I'd like to authenticate to two different OIDC auth services, one of which is Cognito. Because the app uses hash routing, there is only one "real" URI for the app, so the redirect URIs for both services have to be the same. The problem is that whenever the redirect URI is hit, the `Auth` object automatically attempts to parse it. If it sees `code` and `state` params in the query portion, it assumes that it's a Cognito callback and tries to fetch the tokens. This doesn't work if those values pertain to the other auth server, of course. This throws an untrappable error deep within the bowels of the Auth class.

### Describe the solution you'd like

Best: Provide a means to turn off `Auth`'s interception of and automatic response to the redirect (which is, frankly, kind of an arrogant thing to do without also having a means of preventing it). In my own code, I distinguish the nature of the redirect by looking at the `state` param, which I've customized for the two auth services. If it weren't for `Auth` grabbing the redirect and acting on it, everything would work perfectly fine.

Better: Provide some kind of "onAuthRedirect" hook or other means of customizing the response to the redirect.

Good: Provide some kind of "onError" hook or other means of trapping the `Auth`-related errors that occur.

### Describe alternatives you've considered

The only practical alternative I've been able to make work is to just ignore the errors. An impractical alternative is to disable the `Auth` object entirely except when needed, and it's not clear that that would even work.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by tannerabread** [comment] 2023-03-13 14:17
We are trying to consolidate similar issues/feature-requests, so I am closing this as a duplicate of #9208. While this one was opened before, the other has a lot more context plus a PR attached that has been reviewed.

Thank you for opening this and bringing the issue to our attention. If you believe this was different from that feature-request please let me know and we can discuss it further. I encourage you to follow the other issue and thumbs up the OP so that we can better prioritize the fix.

**Closed by tannerabread** 2023-03-13 14:17 UTC
Labels: feature-request, Auth
