### ISSUE TITLE
Does Amplify require zen-observable?

### ISSUE THREAD

**Issue by TriangularCube** [aws-amplify/amplify-js#4506] opened 2019-12-03 23:03 UTC
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Just Auth

After updating from 1.5 to ~~2.2~~ 2.1.1, it seems Auth is now missing a dependency of zen-observable that must be manually installed. This doesn't seem to be documented anywhere. Is the documentation simply lagging behind or am I missing something?

**Comment by ericclemmons** [comment] 2019-12-04 00:03
Hi @TriangularCube,

Can you share your `package.json` and the exact error you're getting?  

I was testing this out in a sandbox (https://codesandbox.io/s/httpsgithubcomaws-amplifyamplify-jsissues4506-sr9l1), and `zen-observable` appears to come in from a sub-dependency of `aws-amplify`:

```console
yarn why zen-observable
yarn why v1.16.0
warning package.json: No license field
[1/4] Why do we have the module "zen-observable"...?
[2/4] Initialising dependency graph...
warning https-githubcom-aws-amplify-amplify-js-issues-4506@1.0.0: No license field
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "zen-observable@0.8.15"
info Reasons this module exists
   - "aws-amplify#@aws-amplify#pubsub" depends on it
   - Hoisted from "aws-amplify#@aws-amplify#pubsub#zen-observable"
   - Hoisted from "aws-amplify#@aws-amplify#api#zen-observable"
```

**Comment by TriangularCube** [comment] 2019-12-04 01:10
It is a sub-dependency of aws-amplify, but this is not documented anywhere, and is not automatically installed when I use `npm install`.

I can't duplicate this in codesandbox, and I have no idea how it's installing dependencies, so here's a simple package.json I threw together.

`{
  "name": "amplify-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.js --open"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-amplify/auth": "^2.1.1"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  }
}`

Simply run `npm i`, then add `import Auth from "@aws-amplify/auth";` to the top of index.js, and parel should fail to compile.

I notice you're using Yarn though, so maybe it's an NPM issue?

**Comment by ericclemmons** [comment] 2019-12-04 01:13
Oh, I see: the original post mentioned `2.2`, which only exists for `aws-amplify`.  `@aws-amplify/auth`'s latest is `2.1.1` as you mentioned.

I'll validate some more. Thanks!

**Comment by TriangularCube** [comment] 2019-12-04 01:16
> Oh, I see: the original post mentioned `2.2`, which only exists for `aws-amplify`. `@aws-amplify/auth`'s latest is `2.1.1` as you mentioned.

You're right, my bad :sweat_smile:

**Comment by ericclemmons** [comment] 2019-12-04 01:18
Hey no worries!  Thanks for sharing your `package.json` and the clear steps for reproducing.  I'll let you know what I find 🙏

**Comment by ericclemmons** [comment] 2019-12-04 17:13
I'm struggling to reproduce this.  I'm going to spin up a local repo with `npm` like you mentioned & try that...

> https://codesandbox.io/s/youthful-sky-h0pok
> ![Screen Shot 2019-12-04 at 9 12 47 AM](https://user-images.githubusercontent.com/15182/70164611-55396c00-1676-11ea-9116-7f8cf3377475.png)

**Comment by ericclemmons** [comment] 2019-12-04 17:21
@TriangularCube **Reproduced!** 
> https://github.com/ericclemmons/amplify-js-issues-4506

![Screen Shot 2019-12-04 at 9 17 39 AM](https://user-images.githubusercontent.com/15182/70165162-456e5780-1677-11ea-9f9e-df97c4f9c94d.png)

```console
❯ npm run start

> amplify-test@1.0.0 start /private/tmp/4506
> parcel index.js --open

Server running at http://localhost:1234
🚨  /private/tmp/4506/node_modules/@aws-amplify/core/lib-esm/Util/Reachability.js:1:28: Cannot resolve dependency 'zen-observable'
> 1 | import * as Observable from 'zen-observable';
    |                            ^
  2 | var ReachabilityNavigator = /** @class */ (function () {
  3 |     function ReachabilityNavigator() {
  4 |     }

```

Thanks for your clear steps & the `package.json`.  It's interesting that CodeSandbox using Parcel doesn't have the issue, while we do locally...

**Comment by ericclemmons** [comment] 2019-12-04 17:26
`yarn` vs. `npm` doesn't make a difference.  I'm going to dig into it more.  There have been releases recently, and it looks like `@aws-amplify/core` has a hard-dependency on `zen-observable` without it being explicitly included.

**Comment by ericclemmons** [comment] 2019-12-04 18:54
Alright, this should address it! https://github.com/aws-amplify/amplify-js/pull/4511

Finding out a way to validate this...

**Comment by TriangularCube** [comment] 2019-12-04 19:44
Thanks so much!

**Comment by KingDarBoja** [comment] 2019-12-18 19:04
> Alright, this should address it! #4511
> 
> Finding out a way to validate this...

Awaiting for the next release as I step into this error too. Glad to know it got fixed on that PR.

**Comment by jordanranz** [comment] 2019-12-27 21:44
@ericclemmons this seems to have been merged and released. Is this safe to close?

**Comment by ericclemmons** [comment] 2019-12-27 22:04
Safe to close! Thanks for everyone's help!

**Closed by ericclemmons** 2019-12-27 22:04 UTC
Labels: bug
