### ISSUE TITLE
Caching files from Storage.get()

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [aws-amplify/amplify-js#1342] opened 2018-07-30 14:37 UTC
Right now all links received from Storage.get() are signed links with AWSAccessKeyId, Expire, Signature etc. And on each call to Storage.get() to the same object key we receive different unique link to the same object.
As we receive signed link even with `level: 'public'` objects this behavior prevents any content to be cached in web browser as it uses the whole url query as key for cached resource. 
Is this an intended behavior? Or is there any workaround to be able to cache resources requested from s3?

**Comment by manueliglesias** [comment] 2018-07-30 15:55
Hi @AlpacaGoesCrazy 

This is the expected behavior, when using the Storage module, credentials are assumed to be available (from either the authenticated role, or unauthenticated role configured in a Cognito Identity Pool). 

Using `level: 'public'` means that the resources can be accessed by both authenticated and unauthenticated roles, but credentials are still needed. You can think of it as *It is public for users of your app, not for the whole world* 

I haven't tested this, but you might be able to pass an `expires` option to `Storage.get()`, and achieve some client side caching by using a fixed time in the future. 

Let us know how it goes

**Comment by AlpacaGoesCrazy** [comment] 2018-07-31 07:12
Right now not passing `expires` to `Storage.get()` returns link which expires after 15 minutes by default. So passing custom expiration time will do nothing to browser caching behavior as on subsequent link generation it will still generate different Signature for that link which will result in a cache miss. 
Or am I missing something and maybe I am supposed to store a signer url once I generated it?

**Comment by MainAero** [comment] 2018-08-03 13:00
@AlpacaGoesCrazy I think your are supposed to store the signer url once you generated it.

@manueliglesias It seems that `expires` can't be greater than `Auth.currentSession().accessToken.payload.exp` time. When I passing `expires: 604800` (1 week, max allowed value) to `Storage.put` all the signed urls are expired after `Auth.currentSession().accessToken.payload.exp`

If there is no way to extend the expiration time `Storage.get` should set the value accordingly

Another way to to cache the images is to download them (@AlpacaGoesCrazy) e.g.

```javascript
import React from 'react'
import { Storage, Cache } from 'aws-amplify'

const getBase64Image = (data) => 'data:' + data.ContentType + ';base64,' + data.Body.toString('base64')

const getRemoteImageCached = async (imgKey) => {
    try {
        const cachedImage = await Cache.getItem(imgKey)
        if (cachedImage) {
            console.log('Cache hit: ', imgKey)
            return cachedImage
        }
        return Storage.get(imgKey, { download: true })
            .then(data => {
                console.log('Cache miss: ', imgKey)

                const base64Image = getBase64Image(data)
                Cache.setItem(imgKey, base64Image)
                return base64Image
            })
    } catch (err) {
        console.log(err)
        // your error handling
    }
}

const RemoteImageUrlAwareHOC = Component => props => <Component {...props} getRemoteImageCached={getRemoteImageCached} />

export default RemoteImageUrlAwareHOC
```

**Comment by AlpacaGoesCrazy** [comment] 2018-08-06 10:31
@MainAero Thank you for this solution. While there is not much sense in storing images in Amplify cache if you have lots of them (as it's max size is capped at 5Mb), storing links to images works just fine!

**Comment by MainAero** [comment] 2018-08-07 09:46
@AlpacaGoesCrazy Yes you are right. The AsyncStorage is limited to 6MB and Amplify Cache to 5MB. Furthermore AsyncStorage is not intended to cache blob data like images. I missed that in my first attempt of caching. 

For me caching the signed urls is not satisfying because the signed urls will expire mostly within a 1h (see my comment above). 
I wrote a Caching util which will cache the images in the cache directory of the storage let the cache key be the md5 hash of the image.

By the way the `expires` option on Cache will take the utc time in milliseconds e.g. (new Date()).getTime() + 604800000

**Comment by AlpacaGoesCrazy** [comment] 2018-08-07 12:58
@MainAero You are right, I just realized that no matter what expiration time you set while retrieving signed URL the cognito token which was used to sign that URL will expire much earlier and render that link inaccessible. This makes storing signer URLs for longer period of times not an option.
However I am not sure how to implement caching in this case. Can you give me a hint on how to better implement it?

**Comment by ScubaDrew** [comment] 2018-10-25 05:52
Storage.get(key, { download: true })

Can someone post some example code using this to access the actual data that is downloaded?

**Comment by destpat** [comment] 2019-02-16 22:12
You can access to a `level: 'public'` or `level: 'protected'` picture without signature, just remove the signature before adding the url in a dom.

`photoUrl.substring(0, photoUrl.indexOf('?'))`

**Comment by jordanranz** [comment] 2019-03-13 22:22
Seem the question has been answered. Going to close this now. Please reopen if you have any related questions or concerns.

**Closed by jordanranz** 2019-03-13 22:22 UTC
Labels: Caching, question

**Comment by kkshyu** [comment] 2019-03-19 15:16
@jordanranz this issue has not been solved yet

I have tried the method from @destpat , and still got the 403
i can access the public files only with `Storage.get()` but not the url without signature

is there any other ideas to get the permanent link of the public files with `Storage.get()`?

**Comment by thongnx6** [comment] 2019-03-26 08:18
me neither, can someone post some example code using this to access the actual data that is downloaded?
