### ISSUE TITLE
Support API Gateway websockets to PubSub

### ISSUE THREAD

**Issue by yareyaredesuyo** [aws-amplify/amplify-js#3591] opened 2019-07-04 01:36 UTC
Currently, there is no support for API Gateway websockets, so it maybe a good idea for supporting it.

Related to https://github.com/aws-amplify/amplify-js/issues/2924, but that title looks not good. So made a new issue.

**Comment by JustFly1984** [comment] 2019-07-05 11:08
+1

**Comment by 0x6C38** [comment] 2019-09-14 21:25
+1

**Comment by cbarlow1993** [comment] 2019-09-18 22:56
+ 1

**Comment by a428tm** [comment] 2019-11-29 12:29
+1

**Comment by JustFly1984** [comment] 2019-11-29 14:01
+1

**Comment by paudyaln** [comment] 2019-12-09 16:49
+1

**Comment by paudyaln** [comment] 2019-12-16 16:10
+1

**Comment by na-o-ys** [comment] 2020-01-30 01:17
+1

**Comment by lyziane** [comment] 2020-04-10 08:59
+1

**Comment by aethernet** [comment] 2020-05-21 08:05
+1

**Comment by ppanchal97** [comment] 2020-06-08 09:24
+1

**Comment by noahking27** [comment] 2020-07-01 14:24
+1

**Comment by mrcportillo** [comment] 2020-08-18 17:49
+1

**Comment by bertinnv** [comment] 2020-09-10 16:56
+1

**Comment by utajum** [comment] 2020-10-06 14:50
+1

**Comment by kaammii** [comment] 2020-10-16 15:31
+1

**Comment by nichwch** [comment] 2020-11-10 03:13
+1

**Comment by raffibag** [comment] 2020-12-08 21:07
+1... we need this: 

```? Please select from one of the below mentioned services: (Use arrow keys)
❯ GraphQL 
  REST 
  Websocket
```

**Comment by agileurbanite** [comment] 2021-05-04 22:21
This seems like a duplicate of #2924, am I missing something here or is this just a duplicate with a different title?

**Closed** 2021-07-21 03:36 UTC
Labels: API, feature-request, pending-close-response-required
