### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto' in amazon-cognito-identity-js/es/utils with angular 11 / webpack 4.44.2

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-js#7454] opened 2020-12-28 16:26 UTC
**Describe the bug**

I'm upgrading to angular 11, and I get this warning when running an angular app:

warning: ./node_modules/amazon-cognito-identity-js/es/utils/cryptoSecureRandomInt.js
Module not found: Error: Can't resolve 'crypto' in '/<my_dir>/node_modules/amazon-cognito-identity-js/es/utils'

**To Reproduce**
Upgrade angular app from 10 to 11. 

**Expected behavior**
No warnings

**Additional context**
I'm running angular 11.0.5 with webpack 4.44.2

I do see similar issue at https://github.com/aws-amplify/amplify-js/issues/7185 with webpack 5, but this warning seems to happen in webpack 4 as well.

**Comment by hisham** [comment] 2020-12-28 16:34
I resolved by adding the following in my package.json: 

```
  "browser": {
    "crypto": false
  },
```

And the warning is gone. 

And things seem to be working fine in my app so far. 

Is crypto actually needed in browser-based apps?

**Comment by 9037568** [comment] 2020-12-29 18:22
Same problem here, and if I use the `package.json` hack mentioned by @hisham, the warning goes away, but auth functionality doesn't work.

**Comment by stephannagel** [comment] 2021-01-04 22:03
Same Issue here

**Comment by amhinson** [comment] 2021-01-04 23:10
Here's a response from another issue referencing this console warning: https://github.com/aws-amplify/amplify-js/issues/7098#issuecomment-743304973

However, this warning shouldn't have any effect on functionality. What exactly doesn't work for you @9037568?

**Comment by 9037568** [comment] 2021-01-05 04:07
@amhinson: see https://github.com/aws-amplify/amplify-js/issues/7458

I was hoping that the workaround mentioned here would fix that problem, but no.

**Comment by amhinson** [comment] 2021-01-05 16:31
@9037568 I'd say that this issue regarding crypto is unrelated to the Angular UI components issue you are seeing. I'm going to close this one for now since this original issue here is a duplicate of #7098.

**Closed by amhinson** 2021-01-05 16:31 UTC
Labels: Angular
