### ISSUE TITLE
Subscriptions on REAL device stop working after network/connection is lost for a few seconds

### ISSUE THREAD

**Issue by avronyc** [aws-amplify/amplify-js#4857] opened 2020-02-06 12:15 UTC
**Describe the bug**
This happens ONLY on a REAL device, not in browser

Once subscribed to receive subscription notifications (graphql) the subscriptions stop receiving updates after connection is lost for a few seconds only.

**To Reproduce**

1. Subscribe to a graphql subscription
2. Updates/notifications arrive properly
3. In your device activate airplane mode for just a few seconds while your app is open. after a few seconds disable airplane mode so connection is restored.
4. Subscriptions DO not receive any more updates and its not possible to resubscribe until the old ones expire/timeout, currently set at 5mins

**Expected behavior**
Subscriptions should continue to work after a few seconds of connection loss, OR we should be able to resubscribe without having to wait 5 minutes until the original websocket connections timeout

``  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.61 GB / 15.76 GB
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    aws-amplify: ^2.2.2 => 2.2.2
    aws-amplify-angular: ^4.1.3 => 4.1.3
    buffer: ^5.4.3 => 5.4.3
    card.io.cordova.mobilesdk: ^2.1.0 => 2.1.0
    codelyzer: ~4.5.0 => 4.5.0
    cordova-android: ^8.1.0 => 8.1.0
    cordova-browser: 6.0.0 => 6.0.0
    cordova-ios: 5.0.1 => 5.0.1
    cordova-plugin-appsflyer-sdk: ^4.4.26 => 4.4.26
    cordova-plugin-device: ^2.0.3 => 2.0.3
    cordova-plugin-ionic: ^5.4.6 => 5.4.6
    cordova-plugin-ionic-keyboard: ^2.2.0 => 2.2.0
    cordova-plugin-ionic-webview: ^4.1.3 => 4.1.3
    cordova-plugin-mixpanel: ^4.7.0 => 4.7.0
    cordova-plugin-network-information: ^2.0.2 => 2.0.2
    cordova-plugin-splashscreen: ^5.0.3 => 5.0.3
    cordova-plugin-statusbar: ^2.4.3 => 2.4.3
    cordova-plugin-whitelist: ^1.3.4 => 1.3.4
    core-js: ^2.5.4 => 2.6.5
    ionic-tags-input: ^0.1.2 => 0.1.2
    jasmine-core: ~2.99.1 => 2.99.1
    jasmine-spec-reporter: ~4.2.1 => 4.2.1
    karma: ~4.1.0 => 4.1.0
    karma-chrome-launcher: ~2.2.0 => 2.2.0
    karma-coverage-istanbul-reporter: ~2.0.1 => 2.0.5
    karma-jasmine: ~1.1.2 => 1.1.2
    karma-jasmine-html-reporter: ^0.2.2 => 0.2.2
    mixpanel-browser: ^2.29.1 => 2.29.1
    moment: ^2.24.0 => 2.24.0
    node-sass: ^4.12.0 => 4.12.0
    object-hash: ^1.3.1 => 1.3.1
    protractor: ~5.4.0 => 5.4.2
    rxjs: ~6.3.3 => 6.3.3
    rxjs-compat: ^6.5.2 => 6.5.2
    text-mask-core: ^5.1.2 => 5.1.2
    ts-node: ~8.3.0 => 8.3.0
    tslint: ~5.17.0 => 5.17.0
    typescript: ~3.1.6 => 3.1.6
    zone.js: ~0.8.29 => 0.8.29``

**Smartphone (please complete the following information):**

- Device: [e.g. Android MotoG, iPhone6-10]
- OS: [e.g. iOS13+, Android 27+]

**Comment by ashika01** [comment] 2020-07-29 22:47
@avronyc I think this doesn't happen anymore. Could you verify this with newer versions and let us know. I will close this issue for now, since I wasn't able to reproduce this. But if it still happens, ping me and I can reopen this issue.

**Closed by ashika01** 2020-07-29 22:47 UTC
Labels: GraphQL, PubSub, to-be-reproduced
