### ISSUE TITLE
AmplifyAuthenticator stuck in loading state after refresh

### ISSUE THREAD

**Issue by sysless** [aws-amplify/amplify-js#7081] opened 2020-10-29 13:11 UTC
**Describe the bug**
After signing in with hosted UI, I am redirected to my React App and signed in.
But the first time I refresh the page, I am stuck in `loading` state, no AuthStateChange gets fired.
And yet, if I refresh again, I am signed in and it does not happen anymore for the session. 

**To Reproduce**

1. Use `AmplifyAuthenticator` from `@aws-amplify/ui-react`
2. Sign in from cognito hosted ui
3. Refresh

**Expected behavior**
I should stay signed in even after a simple refresh.

**Additional context**
Here are the console logs in DEBUG:
```
[DEBUG] 01:26.759 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}data: {url: "http://localhost:3000/app/"}event: "parsingCallbackUrl"message: "The callback url is being parsed"__proto__: Object
[DEBUG] 01:26.760 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
[DEBUG] 01:26.763 AnalyticsClass - on hub capsule auth {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
[DEBUG] 01:26.764 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
[DEBUG] 01:26.764 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
[DEBUG] 01:26.765 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
[DEBUG] 01:26.765 AnalyticsClass - on hub capsule auth {event: "configured", data: null, message: "The Auth category has been configured successfully"}
[DEBUG] 01:26.766 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
```

**Comment by D0berm4n** [comment] 2020-11-25 09:44
Hi all. Expiriencing same issue with `"@aws-amplify/ui-vue": "0.2.25"` and `"aws-amplify": "3.3.6"`

**Comment by harrysolovay** [comment] 2020-12-04 19:21
This is likely because upon a second refresh, there is another attempt to use the code in the query params to get a token from the given OAuth provider. Can you please try clearing the query parameters & see if that fixes this? 

```ts
if (history.pushState) {
    const newurl = window.location.protocol + "//" + window.location.host + window.location.pathname;
    window.history.pushState({path:newurl}, "", newurl);
}
```

**Comment by sysless** [comment] 2020-12-07 10:30
When should I do this?

If this is to clear the `#idToken`, it is not present when I have the issue.

In the meantime, I added a 2-second timeout that will force refresh if it is not cleared on the first `handleAuthStateChange`.

**Comment by jmannau** [comment] 2021-01-14 05:01
I am also experiencing this with the following dependancies and Angular.
```
    "@aws-amplify/api": "^3.2.17",
    "@aws-amplify/api-graphql": "^1.2.17",
    "@aws-amplify/auth": "^3.4.17",
    "@aws-amplify/core": "^3.8.9",
    "@aws-amplify/pubsub": "^3.2.15",
    "@aws-amplify/ui": "^2.0.2",
    "@aws-amplify/ui-angular": "^0.4.17",
```

What seams to be happening is that the authenticator component checks if the page has been loaded from Cognito Hosted ui here - https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L88

```
   const byHostedUI = localStorage.getItem(REDIRECTED_FROM_HOSTED_UI);
    localStorage.removeItem(REDIRECTED_FROM_HOSTED_UI);
    if (byHostedUI !== 'true') await this.checkUser();
```

`byHostedUi` in this situation is `'true'` and `checkUser()` is never called. Hence the component gets stuck in `loading` state

**Comment by yespeaceee** [comment] 2021-03-02 10:58
> I am also experiencing this with the following dependancies and Angular.
> 
> ```
>     "@aws-amplify/api": "^3.2.17",
>     "@aws-amplify/api-graphql": "^1.2.17",
>     "@aws-amplify/auth": "^3.4.17",
>     "@aws-amplify/core": "^3.8.9",
>     "@aws-amplify/pubsub": "^3.2.15",
>     "@aws-amplify/ui": "^2.0.2",
>     "@aws-amplify/ui-angular": "^0.4.17",
> ```
> 
> What seams to be happening is that the authenticator component checks if the page has been loaded from Cognito Hosted ui here - https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L88
> 
> ```
>    const byHostedUI = localStorage.getItem(REDIRECTED_FROM_HOSTED_UI);
>     localStorage.removeItem(REDIRECTED_FROM_HOSTED_UI);
>     if (byHostedUI !== 'true') await this.checkUser();
> ```
> 
> `byHostedUi` in this situation is `'true'` and `checkUser()` is never called. Hence the component gets stuck in `loading` state

huge thanks @jmannau 

thanks to your comment I've been able to implement a dirty fix

```js
...
Hub.listen('auth', ({ payload: { event } }) => {
    switch (event) {
        case 'signIn':
            this.authState = 'signedin'
            break
        case 'cognitoHostedUI':
            // this line do the trick
            localStorage.setItem(
                'amplify-redirected-from-hosted-ui',
                false
            )
            break
    }
})
...
```

**Comment by sammartinez** [comment] 2021-05-19 16:00
@ericclemmons / @wlee221 / @ErikCH Is this an issue? Can one of you confirm?

**Comment by wlee221** [comment] 2021-05-19 19:50
Looking into this now -- sorry about the delay. I was unable to reproduce this with the latest `@aws-amplify/ui-react`. But I completely agree with @jmannau's research that code snippet is what would trigger this issue.

The intended flow is that on your first hosted ui login, Amplify will remove the `REDIRECTED_FROM_HOSTED_UI`:

```
 const byHostedUI = localStorage.getItem(REDIRECTED_FROM_HOSTED_UI);
 localStorage.removeItem(REDIRECTED_FROM_HOSTED_UI);
 if (byHostedUI !== 'true') await this.checkUser();
```

So on subsequent reloads, `byHostedUI` will be false and `this.checkUser` will be called as intended. For some reason, it seems that the code wasn't run on the initial login thus causing this issue.

**Comment by wlee221** [comment] 2021-05-19 19:53
Are you still experiencing this issue on the latest `@aws-amplify/ui-[framework]`? If so, can you provide us with a reproducible sample?

**Comment by jmannau** [comment] 2021-05-20 04:12
@wlee221 Yes, we are still experiencing the issue. I won't be able to develop a clear example repo for some time unfortunately.  It's also tricky to set up a clear repo given the dependancy on cognito and a oauth provider.

**Comment by ericclemmons** [comment] 2021-05-20 16:40
@wlee221 I believe we can remove this `if (byHostedUI)` check entirely, or at least remove it & validate it.

The original `aws-amplify-react` version had this check because the OAuth flow needed time to complete after redirecting:

https://github.com/aws-amplify/amplify-js/blob/ef358a761cf74d16b61172cd1a75b4bc6cfd2bdf/packages/aws-amplify-react/src/Auth/Authenticator.tsx#L94-L104

So, naturally, this code got migrated to `@aws-amplify/ui-components`:

https://github.com/aws-amplify/amplify-js/blob/ef358a761cf74d16b61172cd1a75b4bc6cfd2bdf/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L93-L98

Soon after, @elorzafe put in a fix to correctly _wait_ for an OAuth flow to complete before resolving `Auth.currentAuthenticatedUser()` in https://github.com/aws-amplify/amplify-js/pull/5929

The UI shouldn't have to be that aware of JS internals, but those workaround were necessary at the time. But still buggy.

**Comment by wlee221** [comment] 2021-05-20 17:14
@ericclemmons thanks for the context! I agree, the check shouldn't be necessary -- especially in our current components because that'll just get the component stuck. I'll create a PR to remove that check entirely.

**Comment by wlee221** [comment] 2021-05-28 21:36
I opened #8357 to address this issue.

**Closed** 2021-06-03 23:18 UTC
Labels: UI, bug
