### ISSUE TITLE
TOTP setup => Nothing in Documentation

### ISSUE THREAD

**Issue by rdick** [aws-amplify/amplify-js#9393] opened 2021-12-21 21:48 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

The documents for "@aws-amplify/ui-react": "^2.1.5", authentication are not very helpful. After looking at this for a week I can still not figure out how to setup TOTP (MFA). Please rewrite the documentation with more information for the users instead of making it look fancy. 

### Describe the bug

The documents for authentication are not very helpful. After looking at this for a week I can still not figure out how to setup TOTP (MFA). Please rewrite the documentation with more information for the users instead of making it look fancy. 

### Expected behavior

The documents for authentication are not very helpful. After looking at this for a week I can still not figure out how to setup TOTP (MFA). Please rewrite the documentation with more information for the users instead of making it look fancy. 

### Reproduction steps

The documents for authentication are not very helpful. After looking at this for a week I can still not figure out how to setup TOTP (MFA). Please rewrite the documentation with more information for the users instead of making it look fancy.

**Comment by chrisbonifacio** [comment] 2021-12-22 18:11
Hi @rdick 👋 Thanks for raising this issue. This seems to have to do with our new UI Library so I'm going to transfer this over to that repo for better support. In the meantime, can you go into more detail about what documentation you used and what issues or potential errors you're running into while trying to set it up?

I just tried setting up TOTP on the latest version of the CLI (7.6.5) and was not able to because there's a known bug where TOTP only configs are failing on `amplify push`.

I'm getting this error. Is this what you're running into?

<img width="819" alt="Screen Shot 2021-12-22 at 10 24 13 AM" src="https://user-images.githubusercontent.com/16952986/147136776-b7eab103-e4b9-442e-b0ff-fcb49fdcaf44.png">

**Comment by rdick** [comment] 2021-12-22 18:20
Hi Chris, This is specifically with the Amplify Auth Library. Additionally, there is little information / examples about how the Authenticator component works.

Eg. Props aren't explained, slots types aren't explained, examples aren't helpful, how MFA / TOTP works isn't explained. I just manually went through the code in your package to figure out how it works.

I don't think a lot of people understand Higher Order Components and your library used higher order components in the most confusing way possible. 

It is almost like you need to rewrite all of the documentation with examples that make more sense for an average user. I just switched back to the older version of aws amplify authentication. If you want to shoot me a call at 780-299-5886 I would be happy to show you examples of problems that I have found.

**Comment by chrisbonifacio** [comment] 2021-12-22 19:31
There's separate documentation for the Auth library and the UI Library.

Here's documentation for setting up TOTP through the Auth library, with which you would have to create your own custom UI to handle each auth state.
https://docs.amplify.aws/lib/auth/mfa/q/platform/js/

The Authenticator from the UI Library automatically infers the UI from the config in your `aws-exports` file. I'm not sure if it handles TOTP automatically though, I just tried with SMS MFA and got this after trying to verify my email after signing up. From here I agree that it's not clear what to do next or how to unblock the user.

<img width="484" alt="Screen Shot 2021-12-22 at 2 26 13 PM" src="https://user-images.githubusercontent.com/16952986/147145403-cbae6e9d-125d-4403-9b74-62a3175fadf2.png">

So, are you trying to use the Auth library directly to setup MFA or are you trying to use the Authenticator and want it to handle that for you?

**Comment by chrisbonifacio** [comment] 2021-12-22 19:50
This was just shared with me as a workaround to the CLI bug:
https://github.com/aws-amplify/amplify-ui/tree/main/environments/auth-with-totp-mfa

Currently going through it to verify the TOTP MFA process can be handled through the Authenticator.

**Comment by rdick** [comment] 2021-12-22 19:55
Hey Chris, Thanks for the article - however the issue seems to be on the AWS cognito portal / CLI (backend) and the frontend. If you can fix this and create documentation so people don't have to do these workarounds that would make a lot more sense.

eg. If newbies have to search through GitHub every-time they have a problem with AWS the documentation / platform will become useless.

**Comment by chrisbonifacio** [comment] 2021-12-22 20:10
No problem! I just finished importing an existing Cognito User Pool into a project by following the article and the Authenticator does indeed handle the MFA flow without any additional config.

The Setup TOTP Authenticator view
<img width="483" alt="Screen Shot 2021-12-22 at 2 56 19 PM" src="https://user-images.githubusercontent.com/16952986/147148590-6b08f4e7-4470-433c-a0d0-fbc918cda2c5.png">

Once I entered the temporary code, I was able to login. So, this use case is currently blocked by the CLI but will be unblocked soon once the fix is merged and released.

The feedback is appreciated but the documentation for setting up MFA is there and is still the correct flow for the Auth library. There's no config necessary for the Authenticator, and that is explicitly stated in the documentation.

The problem is with the CLI, the Cognito User Pool resource can still be configured with TOTP MFA and imported into an Amplify project and the front end will still be able to handle it.

You can track the PR here: https://github.com/aws-amplify/amplify-cli/pull/9214

Apologies for the inconvenience. This was a good issue to raise because now the workaround is discoverable.

**Closed** 2021-12-23 18:41 UTC
Labels: Auth, pending-response
