### ISSUE TITLE
SignInWithApple and Amplify not working user is never authenticated (I have all lastest updates for all)

### ISSUE THREAD

**Issue by rapgithub** [aws-amplify/amplify-js#8445] opened 2021-06-14 10:31 UTC
anyone has implemented signInWithApple using amplify Auth.federatedSignIn? in my case credentials are null and user is never authenticated
```
Auth.federatedSignIn(
          {
            provider: 'SignInWithApple',
            token: accessToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
```

credentials returning all the time null 

if I use       

```
Auth.currentAuthenticatedUser()
      .then(user => {
        console.log(user);
        return user;
      })
```

the error says user it is not authenticated i am using cognito with aws and amplify with my Cordova mobile app!
With facebook and google everything works perfectly but not with apple sign in!

Anyone knows why it is not working? why credentials are null and why user is not registered?
thanks

**Comment by chrisbonifacio** [comment] 2021-06-14 18:11
Hi @rapgithub :wave: did you setup SignInWithApple by following the steps in the docs? Just asking so I know what steps to take to try and reproduce the same issue.

https://docs.amplify.aws/lib/auth/social/q/platform/js

**Comment by chrisbonifacio** [comment] 2021-06-14 18:13
Also, if you can share how the code where `Auth.federatedSignIn` and `Auth.currentAuthenticatedUser` are called, please do. It may be even just be an issue with how the code is written.

**Comment by rapgithub** [comment] 2021-06-15 12:39
I have Facebook and Google working perfectly with amplify and cognito but apple sign in it is not working! My environment it is javascript I use framework7 and Cordova amplify, I have added apple sign in and followed all steps for store connect in  developers.apple and set up service Id and keys and cognito enable the apple sign in too... according the amplify explanation and credentials are returned "null" with apple sign in but with Facebook and google are working fine!

Also the curious thing it is that in cognito pools I can see the user registered with the apple sign in but Auth.currentAuthenticatedUser is null also using Auth.federatedSignIn credentials are null too...

I do not understand this wrong behaviour from amplify js with the apple sign in because it is not working and not returning the user logged in after logged in.

do you have a code sample to check with my code?
how do you use Auth.federatedSignIn to get the credentials after signed in with apple?

Credentials is always null but the apple user is in cognito pool registered and I can see it in my user pool! if I call getCurrentUser after signed up with Apple the user is always null all the time.

here my code:

```
 signInWithApple({
      state
    }, {
      $f7, $
    }) {

      console.log("signInWithApple...");

      window.cordova.plugins.SignInWithApple.signin(
        { requestedScopes: [0, 1] },
        function(response){

          console.log({response}); //user data is retrieved here 
          const accessToken = response.identityToken;
        
          const { exp } = jwt_decode(response.identityToken);
          const expires_at = exp * 1000 + new Date().getTime();

          if (!accessToken) {
            return;
          }

          state.accessToken = accessToken;

          const user = {
            email: response.email,
            id: response.user,
            name: response.fullName.givenName
          };

          Auth.federatedSignIn(
            {
              provider: 'SignInWithApple',
              token: accessToken,
              expires_at: expires_at
            }, user).then(credentials => {
        
            console.log({credentials}); //always null

            Auth.currentCredentials().then(
              credentials => {
                console.log({credentials}); //always null

              });

          }).then(user => {
            console.log({user}); //always null


          }).catch(err => {
            console.log('aws: error');
            console.log(err);
<img width="473" alt="Screenshot 2021-06-15 at 14 34 53" src="https://user-images.githubusercontent.com/11996194/122053234-dbe01500-cde6-11eb-8f00-60df282f588e.png">

          });

        },
        function(err){
          console.error(err)
          console.log(JSON.stringify(err))
        }
      )      

    },


    getCurrentUser({
      state
    }, {
      $f7, $
    }) {

      console.log("getCurrentUser...");

      Auth.currentAuthenticatedUser()
      .then(user => {
        console.log(user); //always null
        return user;
      })
      .catch(err => {
        console.log(err);
      });
  

    },
```

my Cordova plugins list

<img width="465" alt="Screenshot 2021-06-15 at 14 35 20" src="https://user-images.githubusercontent.com/11996194/122053309-ebf7f480-cde6-11eb-8342-f45bc96011da.png">

I hope to find a solution! it seems that amplify with cognito and apple sign in it is not working properly somewhere!

Do you have a sample of your code? and how you can get the credentials with apple sign in?
thanks

**Comment by rapgithub** [comment] 2021-06-16 07:24
any solution from amplify team so far?

**Comment by rapgithub** [comment] 2021-06-17 21:52
any assignees out there?

**Comment by chrisbonifacio** [comment] 2021-06-18 14:01
Hi @rapgithub We're still looking into this issue. Sorry for the delay.

**Comment by rapgithub** [comment] 2021-06-18 16:09
thank you I hope it can be solved! I stay tuned for updates! thanks

**Comment by rapgithub** [comment] 2021-06-21 21:31
any news? my development is stopped due to this issue with amplify and signInWithApple provider not returning credentials and undefined! Also Apple is making mandatory the fact to add socials other than theirs and this is why I am looking for a fix or solution because I am using amplify for this! I do appreciate any resolution, update or fix!
thanks

**Comment by chrisbonifacio** [comment] 2021-06-24 18:18
Hey @rapgithub sorry for the delay. I was sort of able to reproduce the issue but I'm not sure if it's because of the same issue.  For me it was because I didn't have my attributes properly mapped in Cognito User Pools. I would recommend wrapping your `Auth.federatedSignIn` call in a try/catch and log the error so that we get a better idea of what the issue is. That's what I had to do to be able to tell.

**Comment by chrisbonifacio** [comment] 2021-06-24 18:22
here is the `aws-exports` file for my backend where it's working. I think you can test it if you just swap yours out for mine.

```json
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a4529695-07af-4cf3-8367-d5d6fa4ac4c2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_miC3FMwhK",
    "aws_user_pools_web_client_id": "17qpv7ughl5e9eamtqvmsk6svm",
    "oauth": {
        "domain": "8445signinwithapple626ba43a-626ba43a-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};
```

Here's my attribute mapping

<img width="1206" alt="Screen Shot 2021-06-24 at 2 21 44 PM" src="https://user-images.githubusercontent.com/16952986/123313411-834ffc80-d4f7-11eb-882c-52949e33572c.png">

**Comment by rapgithub** [comment] 2021-06-28 07:49
> Hey @rapgithub sorry for the delay. I was sort of able to reproduce the issue but I'm not sure if it's because of the same issue. For me it was because I didn't have my attributes properly mapped in Cognito User Pools. I would recommend wrapping your `Auth.federatedSignIn` call in a try/catch and log the error so that we get a better idea of what the issue is. That's what I had to do to be able to tell.

I will check now if it works! thanks for getting back!

**Comment by rapgithub** [comment] 2021-06-28 07:51
> Hey @rapgithub sorry for the delay. I was sort of able to reproduce the issue but I'm not sure if it's because of the same issue. For me it was because I didn't have my attributes properly mapped in Cognito User Pools. I would recommend wrapping your `Auth.federatedSignIn` call in a try/catch and log the error so that we get a better idea of what the issue is. That's what I had to do to be able to tell.

My mapping attributes are OK setup! did you release a fix upgrade? which version of amplify states in your package.json?

**Comment by chrisbonifacio** [comment] 2021-06-28 17:40
@rapgithub I'm just using the latest version of `aws-amplify` (4.1.1)

```json
"dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "aws-amplify": "^4.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
```

**Comment by chrisbonifacio** [comment] 2021-06-28 17:45
Any particular error message you're getting if you wrap it in a try/catch like so?

```js
const handleAppleSignIn = async () => {
    try {
      const user = await Auth.federatedSignIn({
        provider: "SignInWithApple",
      });
      console.log({ user });
    } catch (error) {
      console.error(error);
    }
  };
```

**Comment by chrisbonifacio** [comment] 2021-06-28 17:49
I just realized that you are passing extra arguments to `Auth.federatedSignIn`. What happens if you call it with just this argument?

```js
Auth.federatedSignIn({
        provider: "SignInWithApple",
      });
```

**Comment by rapgithub** [comment] 2021-06-28 21:36
> I just realized that you are passing extra arguments to `Auth.federatedSignIn`. What happens if you call it with just this argument?
> 
> ```js
> Auth.federatedSignIn({
>         provider: "SignInWithApple",
>       });
> ```
> 
> I think the way you are calling it is not pulling from User Pools but expecting a custom OAuth provider domain.

Why should I pass only providerName when with Facebook and google works just fine? is that SignInWithApple does not need those? I need to know when session needs to renew as well! I am making my tests! Please can you tell me which version of amplify are you using to be sure it matches with yours working?

**Comment by chrisbonifacio** [comment] 2021-06-28 22:09
The way you're using `federatedSignIn` looks like this example from the docs.

https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation

If this is how you intend to use it, you might just be missing `domain` as the first argument.

**Comment by rapgithub** [comment] 2021-06-28 22:23
I just used both ways and same error undefined! can you please provide your full async function where you wrap inside

```
Auth.federatedSignIn({
        provider: "SignInWithApple",
      });
```

I am using it like you mentioned me and same error undefined credentials:

```
            const credentials = await Auth.federatedSignIn({
              provider: "SignInWithApple",
            });

            console.log({credentials});
```

<img width="627" alt="Screenshot 2021-06-29 at 00 21 06" src="https://user-images.githubusercontent.com/11996194/123710957-e6cb8880-d86f-11eb-9b4c-9749f2a9735c.png">

Can you tell me if you test it is only with the browser because I am using it for mobile and in mobile Hybrid app it is not working!, if I used the hostedUI for web it works! but not when in mobile! try it inside a react app etc.. and only Facebook and google works! apple not working!

Please provide me more details about the full async code! thanks

**Comment by chrisbonifacio** [comment] 2021-06-28 22:25
This is my full reproduction app

https://github.com/chrisbonifacio/amplify-issues/tree/dev/8445-signinwithapple

**Comment by rapgithub** [comment] 2021-06-28 22:32
> This is my full reproduction app
> 
> https://github.com/chrisbonifacio/amplify-issues/tree/dev/8445-signinwithapple

thanks I will review your react code, my app does not use react just pure core javascript! I will test it and see what is the main difference mine gives this error! 

I use cordova with framework7 and framework7 use core pure javascript if not using it with react! it is supposed to work fine with the same browser code but in my case only google and Facebook works perfect but not the apple!

I will check where there must be the issue comparing your react code! and get back to you with the news!

**Comment by rapgithub** [comment] 2021-06-28 22:50
> https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation

Have you tried using it like this https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation?

I have tried 

```
        const accessToken = response.identityToken;
        const {exp, email, sub} = jwt_decode(response.identityToken);
        const expires_at = exp * 1000 + new Date().getTime();

        Auth.federatedSignIn(
          'signInWithApple',
          {
            token: accessToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
...
```

<img width="649" alt="Screenshot 2021-06-29 at 00 50 17" src="https://user-images.githubusercontent.com/11996194/123713102-fbaa1b00-d873-11eb-90ae-323d0f00cecf.png">



```
        const accessToken = response.identityToken;
        const {exp, email, sub} = jwt_decode(response.identityToken);
        const expires_at = exp * 1000 + new Date().getTime();

        Auth.federatedSignIn(
          'appleid.apple.com',
          {
            token: accessToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
...

```

<img width="650" alt="Screenshot 2021-06-29 at 00 46 17" src="https://user-images.githubusercontent.com/11996194/123712836-6b6bd600-d873-11eb-96f1-fef726ec344f.png">

Look the error it throws! as mentioned above apple and google works perfect with this way https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation but apple does not work! 

maybe Amplify forgot to include Apple with this way? can you double check anyway your way and this way gives different errors!

thanks!

**Comment by chrisbonifacio** [comment] 2021-06-28 23:04
I will ask the team if this is supported for Apple Sign In. Just so I'm clear, are you using Identity Pools or User Pools?

**Comment by chrisbonifacio** [comment] 2021-06-28 23:19
just out of curiosity, if you changed `appleid.apple.com` to just `apple` does that make a difference for you?

**Comment by rapgithub** [comment] 2021-06-28 23:44
> > ```
> >     const accessToken = response.identityToken;
> >     const {exp, email, sub} = jwt_decode(response.identityToken);
> >     const expires_at = exp * 1000 + new Date().getTime();
> > 
> >     Auth.federatedSignIn(
> >       'appleid.apple.com',
> >       {
> >         token: accessToken,
> >         expires_at: expires_at
> >       }, user)
> >       .then(credentials => {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> 
> 
> just out of curiosity, if you changed `appleid.apple.com` to just `apple` as your domain does that make a difference for you?

it gives the same error! as shown above! but I tried something! I used your aws-exports below:

```
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a4529695-07af-4cf3-8367-d5d6fa4ac4c2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_miC3FMwhK",
    "aws_user_pools_web_client_id": "17qpv7ughl5e9eamtqvmsk6svm",
    "oauth": {
        "domain": "8445signinwithapple626ba43a-626ba43a-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};
```
and it looks like it works in browser just fine but in the app it breaks but this is just because redirectSignIn and redirectSignOut is pointing to http://localhost:3000/... and not returning to the app myapp://  so I wonder if you share your cognito setup to check if the problems comes from there

this is mine:


<img width="937" alt="Screenshot 2021-06-29 at 01 40 40" src="https://user-images.githubusercontent.com/11996194/123716506-061be300-d87b-11eb-986b-c3d5b5012428.png">

can you share what you have there?

and also here did you use the service Id or your bundle id as the apple service Id?

<img width="951" alt="Screenshot 2021-06-29 at 01 42 18" src="https://user-images.githubusercontent.com/11996194/123716647-6ca10100-d87b-11eb-946e-2979d4ed2112.png">

here my attribute mapping it looks just fine:

<img width="984" alt="Screenshot 2021-06-29 at 01 44 32" src="https://user-images.githubusercontent.com/11996194/123716707-90644700-d87b-11eb-89d7-d3a901b901a3.png">

**Comment by rapgithub** [comment] 2021-06-29 00:22
> > ```
> >     const accessToken = response.identityToken;
> >     const {exp, email, sub} = jwt_decode(response.identityToken);
> >     const expires_at = exp * 1000 + new Date().getTime();
> > 
> >     Auth.federatedSignIn(
> >       'appleid.apple.com',
> >       {
> >         token: accessToken,
> >         expires_at: expires_at
> >       }, user)
> >       .then(credentials => {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> 
> 
> just out of curiosity, if you changed `appleid.apple.com` to just `apple` as your domain does that make a difference for you?


Testing it like this:

````
    const accessToken = response.identityToken;
    const {exp, email, sub} = jwt_decode(response.identityToken);
    const expires_at = exp * 1000 + new Date().getTime();

        Auth.federatedSignIn(
          'apple',
          {
            token: accessToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
....
```

using with 'apple' same issue!

<img width="645" alt="Screenshot 2021-06-29 at 02 20 29" src="https://user-images.githubusercontent.com/11996194/123718894-94df2e80-d880-11eb-9440-9032f4bedfbb.png">

can you please try to bypass the hostedUI using it this way 

https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation? 

Google and Facebook works perfectly that way but apple doesn't!

I think the problem comes from this side of the amplify code! and apple only works with the hostedUI interface returning all credentials but not for the mobile side bypassing the HostedUI!

Try it! thanks

**Comment by hkjpotato** [comment] 2021-06-29 15:18
@rapgithub sorry about the confusion, the `federatedSignIn` is an overloaded method, by passing different forms of parameters it behaves differently.

case1: no parameter - user pool federation
`Auth.federatedSignIn()`. This simply opens up a new page of the user pool "Hosted UI". 

case2: directly go to third party login page - still user pool federation
`Auth.federatedSignIn({provider: 'SignInWithApple'})`. 

The above two cases allow you to federate the customer into the user pool. 

case3: identity pool federation.
```
Auth.federatedSignIn(
  'appleid.apple.com',
  {  
     token: APPLE_ID_TOKEN,
     expires_at: expires_at
  },
  user
)
```


In this case, you need to directly set the federation in identity pool (by clicking the "edit button" of the identity pool). User federate into identity pool directly has nothing to do with user pool. 
![](https://user-images.githubusercontent.com/16952986/123714304-0cdb3380-d844-11eb-8c55-0c58da8a7cb6.png)

This is also the only path where you get the credentials when the promise gets resolved (e.g. by calling `then`).

You can follow this https://docs.aws.amazon.com/cognito/latest/developerguide/apple.html#set-up-apple-1.javascript to setup apple idp in your identity pool.

------

The above 3 are the only valid syntax, the call does not accept a syntax like 

```
 Auth.federatedSignIn(
          {
            provider: 'SignInWithApple',
            token: accessToken,
            expires_at: expires_at
          }, user)
```

I would suggest you to try the case3 approach, using `appleid.apple.com` as the first argument. The error you get back `Token is not from a supported identity provider of this identity pool` is very likely due to some misconfiguration of your identity pool.

**Comment by rapgithub** [comment] 2021-06-30 07:51
> @rapgithub sorry about the confusion, the `federatedSignIn` is an overloaded method, by passing different forms of parameters it behaves differently.
> 
> case1: no parameter - user pool federation
> `Auth.federatedSignIn()`. This simply opens up a new page of the user pool "Hosted UI".
> 
> case2: directly go to third party login page - still user pool federation
> `Auth.federatedSignIn({provider: 'SignInWithApple'})`.
> 
> The above two cases allow you to federate the customer into the user pool.
> 
> case3: identity pool federation.
> 
> ```
> Auth.federatedSignIn(
>   'appleid.apple.com',
>   {  
>      token: APPLE_ID_TOKEN,
>      expires_at: expires_at
>   },
>   user
> )
> ```
> 
> In this case, you need to directly set the federation in identity pool (by clicking the "edit button" of the identity pool). User federate into identity pool directly has nothing to do with user pool.
> ![](https://user-images.githubusercontent.com/16952986/123714304-0cdb3380-d844-11eb-8c55-0c58da8a7cb6.png)
> 
> This is also the only path where you get the credentials when the promise gets resolved (e.g. by calling `then`).
> 
> You can follow this https://docs.aws.amazon.com/cognito/latest/developerguide/apple.html#set-up-apple-1.javascript to setup apple idp in your identity pool.
> 
> The above 3 are the only valid syntax, the call does not accept a syntax like
> 
> ```
>  Auth.federatedSignIn(
>           {
>             provider: 'SignInWithApple',
>             token: accessToken,
>             expires_at: expires_at
>           }, user)
> ```
> 
> I would suggest you to try the case3 approach, using `appleid.apple.com` as the first argument. The error you get back `Token is not from a supported identity provider of this identity pool` is very likely due to some misconfiguration of the identity pool.

I will try to use 3case and see what happens! if not working and stay saying undefined then the error comes from the cognito user pools somewhere, I doubt it but it is the only thinking now! Also it will be helpful in amplify documentation add how to use apple sign in correctly with auth.federatedSignIn since many are posting wrong info regarding this because the documentation is incomplete now!

Appreciated your time to reply! I will get back to you soon with my test! thanks

**Comment by rapgithub** [comment] 2021-06-30 11:07
> > @rapgithub sorry about the confusion, the `federatedSignIn` is an overloaded method, by passing different forms of parameters it behaves differently.
> > case1: no parameter - user pool federation
> > `Auth.federatedSignIn()`. This simply opens up a new page of the user pool "Hosted UI".
> > case2: directly go to third party login page - still user pool federation
> > `Auth.federatedSignIn({provider: 'SignInWithApple'})`.
> > The above two cases allow you to federate the customer into the user pool.
> > case3: identity pool federation.
> > ```
> > Auth.federatedSignIn(
> >   'appleid.apple.com',
> >   {  
> >      token: APPLE_ID_TOKEN,
> >      expires_at: expires_at
> >   },
> >   user
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this case, you need to directly set the federation in identity pool (by clicking the "edit button" of the identity pool). User federate into identity pool directly has nothing to do with user pool.
> > ![](https://user-images.githubusercontent.com/16952986/123714304-0cdb3380-d844-11eb-8c55-0c58da8a7cb6.png)
> > This is also the only path where you get the credentials when the promise gets resolved (e.g. by calling `then`).
> > You can follow this https://docs.aws.amazon.com/cognito/latest/developerguide/apple.html#set-up-apple-1.javascript to setup apple idp in your identity pool.
> > The above 3 are the only valid syntax, the call does not accept a syntax like
> > ```
> >  Auth.federatedSignIn(
> >           {
> >             provider: 'SignInWithApple',
> >             token: accessToken,
> >             expires_at: expires_at
> >           }, user)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would suggest you to try the case3 approach, using `appleid.apple.com` as the first argument. The error you get back `Token is not from a supported identity provider of this identity pool` is very likely due to some misconfiguration of the identity pool.
> 
> I will try to use 3case and see what happens! if not working and stay saying undefined then the error comes from the cognito user pools somewhere, I doubt it but it is the only thinking now! Also it will be helpful in amplify documentation add how to use apple sign in correctly with auth.federatedSignIn since many are posting wrong info regarding this because the documentation is incomplete now!
> 
> Appreciated your time to reply! I will get back to you soon with my test! thanks

Hi there! I found the issue that was not an issue itself was a clear documentation and how to use apple sign in in amplify correctly when using it with mobile or web.

Using this it works only for web!
```
Auth.federatedSignIn({ provider: 'SignInWithApple' });
```

my code was always fine this way below but documentation in amazon / amplify is misleading and confusing! they must state to use "appleid.apple.com" that way first thing!

```
        Auth.federatedSignIn(
          "appleid.apple.com",
          {
            token: identityToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
...
```

Second thing in cognito federated identities nobody knows which ID to use for Apple the service ID or Bundle ID. 
It is confusing in amplify that does not mention which one to use there it only says in a small text in amazon in the link you sent me above that for web use the bundle id while for native apps use the service ID..

So it is misleading to show enter "Apple Services ID" in  federated identities -> Authentication providers -> Apple when it must say enter "Apple Services ID (for native iOS apps)" or "Bundle ID (for web)".

<img width="1016" alt="Screenshot 2021-06-30 at 12 40 31" src="https://user-images.githubusercontent.com/11996194/123949719-2ba40c00-d9a3-11eb-8eff-15b36fc7dd51.png">

it must say so:

<img width="1009" alt="Screenshot 2021-06-30 at 12 59 09" src="https://user-images.githubusercontent.com/11996194/123949760-38c0fb00-d9a3-11eb-8b2f-1947f2acff02.png">


now I get the credentials this way correctly!  Credentials are not anymore undefined! the amplify error on the console was misleading to find out the issue!

<img width="647" alt="Screenshot 2021-06-30 at 12 51 49" src="https://user-images.githubusercontent.com/11996194/123949844-58582380-d9a3-11eb-9945-9a256a2cbe85.png">


It will be useful to provide in amplify a clear sample of apple sign in code in javascript as it is explained well for google and facebook with the right information using it this way to bypass the HostedUI and get credentials!

```
        Auth.federatedSignIn(
          "appleid.apple.com",
          {
            token: identityToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
...
```

My error was using the Apple Service ID when it says  Apple Service ID in federated identities -> Authentication providers -> Apple and using my Apple Bundle ID solved the issue!

Please provide clear information in amplify for the apple sign in and with the samples! and also add Apple Bundle ID / Apple Service ID as shown below:

<img width="1009" alt="Screenshot 2021-06-30 at 12 59 09" src="https://user-images.githubusercontent.com/11996194/123950335-db797980-d9a3-11eb-87ba-fa5ee9e1591a.png">

The information must be clear anywhere in amazon documentation and amplify! so nobody spend so many days to find an errors that are not there! Many people making mistakes for missing clear information regarding this topic!

Thanks a lot!
That will be helpful for all too :)

**Comment by chrisbonifacio** [comment] 2021-06-30 14:21
@rapgithub Thank you for pointing this out! I'm glad it's working for you. Some follow up questions if you don't mind because I'm not sure I understand why the Service ID would work for web and not for mobile.

You enabled Sign In With Apple in your developer account for your service ID, correct? Like so?

<img width="1201" alt="Screen Shot 2021-06-30 at 10 19 04 AM" src="https://user-images.githubusercontent.com/16952986/123977319-e4128580-d98c-11eb-895e-83d5a78ceb59.png">

**Comment by rapgithub** [comment] 2021-06-30 15:38
> With

No, It was already enabled there! 

I just only changed the Apple Service ID for my Bundle ID and worked! 
and I put "appleid.apple.com" as provider/domain in Auth.federatedSignIn like so:

```
        Auth.federatedSignIn(
          "appleid.apple.com",
          {
            token: identityToken,
            expires_at: expires_at
          }, user)
          .then(credentials => {
...
```

Using the Apple Service ID as stated in federated identities -> Authentication providers -> Apple it does not work for me and it only gives misleading errors! my app is an hybrid app so it must be stated in the amplify and amazon documentation to use Bundle ID instead of Service ID in federated Identities if your app is not native and use the "appleid.apple.com" as the domain if you use this way above! This will solve many problems many users are having for missing information and samples!

A better documentation is a good way to avoid all this errors done by many!
THANKS!

**Comment by chrisbonifacio** [comment] 2021-06-30 16:20
Interesting. We'll have to do some testing to confirm this and really understanding why but we appreciate your patience with us throughout all this.

I'm going to close this issue for now then since you were able to get it working but please re-open and give us any new details if you experience any unstable behavior with Sign In With Apple with either Web or Native at any point during your development.

**Closed by chrisbonifacio** 2021-06-30 16:20 UTC
Labels: OAuth

**Comment by hkjpotato** [comment] 2021-06-30 20:13
@rapgithub glad it works 💯 . The identity token you get from Apple is a JWT token. You can use https://jwt.io/ to decode it and check its info. Basically the "aud"(audience) field needs to match the "Apple Services Id" you set in the identity pool dashboard.

The value of "aud" field of the identity token depends on how you get it in the mobile application.

**Comment by rapgithub** [comment] 2021-07-02 19:20
> @rapgithub glad it works 💯 . The identity token you get from Apple is a JWT token. You can use https://jwt.io/ to decode it and check its info. Basically the "aud"(audience) field needs to match the "Apple Services Id" you set in the identity pool dashboard.
> 
> The value of "aud" field of the identity token depends on how you get it in your application.
#
Yes I decide the JWT token but glad you point this info! I will check that in my JWT if it matches!
It only worked with my Apple Bundle ID in my case my app is an hybrid app, not native!

**Comment by rapgithub** [comment] 2021-07-02 19:22
> I'm going to close this issue for now then since you were able to get it working but please re-open and give us any new details if you experience any unstable behavior with Sign In With Apple with either Web or Native at any point during your development.

I wil big thanks to you too! :)
