### ISSUE TITLE
Pinpoint - new endpoints are created for the user without deleting the old ones, which causes the number of endpoints to reach 10 (which is the max)

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#6896] opened 2020-10-01 14:17 UTC
**Describe the bug**
In my React Native app I call the updateEndpoint function whenever the app starts so that it creates an endpoint for my user if it doesn't exist, and update data if the endpoint already exists (Demographic, Location etc). What I think happens is that it creates an endpoint every time, and using the AWS CLI to list endpoints for my user I can see a lot of endpoints that have the INACTIVE status, and then an endpoint with the same address that has an ACTIVE status, according to the docs - 
```
Amazon Pinpoint automatically sets this value to ACTIVE when you create an endpoint or update an existing endpoint. Amazon Pinpoint automatically sets this value to INACTIVE if you update another endpoint that has the same address specified by the Address property.
```
Maybe is there a way that Amplify can check if there are INACTIVE endpoints for the user then delete them? And if there are active endpoints for the user then use them and do not create new ones.

**To Reproduce**
Call Analytics.updateEndpoint with the notification token of the device when the app starts, after a few times (some re-installs, different app builds) you will see you have a lot of endpoint even though you are only using a single device.

**Expected behavior**
Analytics.updateEndpoint() function knows how to handle existing endpoints, new endpoints, old endpoints...

**Code Snippet**
```
await Analytics.updateEndpoint({
  address: pushToken,
  userId: userId,
  userAttributes: {
    ...userAttributes,
  },
  optOut: 'NONE',
});
```

**What is Configured?**
the fields that exist in the aws-exports file are 
```
aws_project_region
aws_cognito_identity_pool_id
aws_cognito_region
aws_user_pools_id
aws_user_pools_web_client_id
aws_appsync_graphqlEndpoint
aws_appsync_region
aws_appsync_authenticationType
aws_user_files_s3_bucket
aws_user_files_s3_bucket_region
aws_mobile_analytics_app_id
aws_mobile_analytics_app_region
``` 
and the custom config for Amplify.configure looks like this 
```
const config = {
  ...aws_exports,
  graphql_headers: async () => {
    try {
      const token = (await Auth.currentSession()).getIdToken().getJwtToken();
      return { Authorization: token };
    } catch (e) {
      console.error(e);
      return {};
    }
  },
  Auth: {
    storage: AmplifyCommunityAsyncStorage,
  },
  PushNotification: {
    appId: aws_exports.aws_mobile_analytics_app_id,
    requestIOSPermissions: false,
  },
};
```

**Additional context**
Maybe I am using Analytics.updateEndpoint() wrong... I would be happy to see what the recommended usage it, because the docs don't say anything about usage - they just show a very simple example and no real usage which is disappointing.

**Comment by sammartinez** [comment] 2021-02-09 23:36
Thank you for providing this feedback. Since Amplify JS is a proxy to the Amazon Pinpoint service, I have marked this as a feature request and will let the Pinpoint service team know about this feature request. Thanks!

**Comment by eryon** [comment] 2021-05-04 20:51
@sammartinez is this a new feature request or is it a bug? Referring to the additional context, are we using `updateEndpoint` incorrectly when we expect it to switch an INACTIVE endpoint to ACTIVE with updated attributes?

**Comment by mariotsi** [comment] 2021-09-10 15:57
@sammartinez this feature was present and has been deleted without any explanation via #7245 and is trying to be restored via this other PR #7733.

Can you please have a look to what happened? This is stopping us to upgrade Amplify

**Comment by GeorgeBellTMH** [comment] 2021-09-12 00:22
@sammartinez you keep punting this to pinpoint team...but I think we need a fix in the CLI/JS until the time that pinpoint team fixes this...it's been over a year at this point...

**Comment by GeorgeBellTMH** [comment] 2021-09-12 00:24
There seems to be a few options
- Fix it in pinpoint (not happening)
- Fix it in JS such that if there is an error it is handled automatically
- Fix it in lambda such that we can clean up the error with an automatically generated lambda
- Documentation on how to handle these errors properly (or at least some tips)

**Comment by GeorgeBellTMH** [comment] 2021-09-12 00:26
I would just add that this seems to be impacting more users now, overtime these endpoints stack up...but also we are seeing more endpoints because each OS/browser upgrade seems to create new endpoints...really annoying for developers on beta's...but still it is impacting customers as well...

**Comment by hkjpotato** [comment] 2021-10-01 18:43
@GeorgeBellTMH Here is some information I collect so far, I am still thinking of a possible way to fix it.
https://github.com/aws-amplify/amplify-js/issues/7251#issuecomment-931579550

For now my understanding is only if you delete the endpoint id from localStorage, the endpoint id will be lost. Can you help me understand what do you mean by developer beta? 

Another thing I think might be helpful for now is to delete the endpoints manually as admin.

**Comment by pcolmer** [comment] 2022-01-21 11:49
So @hkjpotato committed #8992 to set the channel type to PUSH for web analytics but then, seemingly, undid that commit with #8999.

Does that mean we still don't have a fix for web analytics?

We're using AWS Amplify *only* with web browsers, so we don't have "devices" to worry about. All of our endpoints are set to the logged-in user's email address but because the RequestId value changes each time, new endpoints are being created over and over again for the same user.

For web analytics, I just want one endpoint per user. Is that really so hard to achieve?

**Comment by cwomack** [comment] 2022-12-21 00:46
Closing this issue as a duplicate of #7251.  While this issue is older, the other has some additional context and addresses the core problem/root cause of what's reported here.

We'll keep #7251 updated with progress, and know that we are looking into a mechanism to allow for "clean up" of unused endpoints as part of what it will take to close that one out.

**Closed by cwomack** 2022-12-21 00:46 UTC
Labels: Analytics, React Native, Service Team
