### ISSUE TITLE
AccessDeniedException on DynamoDB and S3 calls with Auth.federatedSignIn only after upgrading to Amplify 3.0.18 from 1.1.10

### ISSUE THREAD

**Issue by TheVaporTrail** [aws-amplify/amplify-js#6220] opened 2020-07-03 00:34 UTC
**Describe the bug**
I recently upgraded the libraries in my project from Amplify 1.1.10 to 3.0.18. I am now getting AccessDeniedException with federated logins only (Google). I do not have the issue with non-federated logins. I am currently only testing with localhost. (I am not using React or Angular or any other frameworks.)

AccessDeniedException: User: arn:aws:sts::XXXXXXX:assumed-role/polygoniadev_auth_MOBILEHUB_XXXXX/CognitoIdentityCredentials is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:XXXXXX:table/polygoniadev-mobilehub-XXXXXX-AccountInfo

My site, using the old libraries: https://Polygonia.design

I saw a similar issue mentioned: (_Originally posted by @chadfaurie in https://github.com/aws-amplify/amplify-js/issues/5729#issuecomment-629323168_ )
>I seem to be experiencing the same thing with aws-amplify: 3.0.11, except I am using google federated logins and only experience a 403 when using a google account
>
>I've had a look at the logs and it seems that identityId: undefined

**Code Snippet**
The Google signin callback.
```
	var AuthManager_Google_Authorized = function(googleUser)
	{
		console.log("AuthManager_Google_Authorized");
		
		let googleIdToken = googleUser.getAuthResponse().id_token;
        let expires_at = googleUser.getAuthResponse().expires_at;

        const profile = googleUser.getBasicProfile();
        let user = {
            username: profile.getName(),
            authenticatedBy: "google",
            imageURL: profile.getImageUrl(),
            attributes: { email: profile.getEmail() }
        };
		console.log(JSON.stringify(user, null, 2));
		Auth.federatedSignIn("google", { token: googleIdToken, expires_at }, user)
		.then(credentials => 
		{ 
			console.log(JSON.stringify(credentials, null, 2));
			
			// If success, you will get the AWS credentials
			global.AWS.config.credentials = credentials;
			
			AuthManager_CacheCredentialsId(credentials);
			
			return Auth.currentAuthenticatedUser();
		})
		.then(user => 
		{
			console.log(JSON.stringify(user, null, 2));
			// If success, the user object you passed in Auth.federatedSignIn
			authUser = user;
			AuthMgr_PopulateUsername();
			authState = AuthState.AUTHORIZED;
			AuthManager_AccountMgrSignedIn();
			AuthManager_MonitorForWakeFromSleep();
			AuthManager_UpdateUI();
			AuthManager_UpdateLastRelaunch();
			AuthManager_PerformSignInCallback();
		})
		.catch(e => 
		{
			console.log(e)
		});
	}
```

**What is Configured?**

* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 2.428s

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
    Memory: 61.71 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 65.0.2
    Safari: 13.1.1
  npmPackages:
    aws-amplify: ^3.0.18 => 3.0.18 
    aws-sdk: ^2.708.0 => 2.708.0 
    copy-webpack-plugin: ^6.0.3 => 6.0.3 
    webpack: ^4.43.0 => 4.43.0 
    webpack-cli: ^3.3.12 => 3.3.12 
  npmGlobalPackages:
    npm: 6.14.5
    PolygoniaV2_Dev2: 1.0.0
```

</details>

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by Amplifiyer** [comment] 2020-07-03 01:25
I believe the issue is with the following lines if you are relying on that to be available.
```
// If success, you will get the AWS credentials
global.AWS.config.credentials = credentials;
```

With Amplify major version V3, AWS.config global namespace doesn't exist anymore, please see https://github.com/aws-amplify/amplify-js/#amplify3xx-has-breaking-changes-please-see-the-breaking-changes-below

If the above is not related to your issue, please turn on the debug logs and paste the logs here so we can troubleshoot https://docs.amplify.aws/lib/utilities/logger/q/platform/js#setting-logging-levels

**Comment by TheVaporTrail** [comment] 2020-07-03 02:05
@Amplifiyer, thank you very much for your quick response. 

Any guidance on how to correctly use Auth.federatedSignIn in Amplify 3.x.x (as compared to 1.x.x)? Should I still be using that call or are federated logins handled differently now?

**Comment by Amplifiyer** [comment] 2020-07-03 18:23
Everything remains the same except that there is no AWS.global namespace available for storing credentials. The only other issue I can see is that `Auth.federatedSignIn()` resolves before (it's a race condition) the credentials are made available and hence calling `Auth.currentAuthenticatedUser()` right after resolving `Auth.federatedSignIn()` may not work. The correct way (which is not a breaking change and applies to V1 as well) is to listen to `Hub` events. See full example here https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples

**Comment by TheVaporTrail** [comment] 2020-07-06 19:48
@Amplifiyer, I am now listening to `Hub` events and am mapping them to the events I have for managing the authentication state in my app. This allowed me to move the federated sign-in processing into the state machine (and out of the code I posted above, in the issue description).

I am still having the same issue with the credentials.

Also, when I removed all of the calls `global.AWS.config.credentials = credentials;` I introduced a similar issue with Cognito sign-in, which is the access denied error attempting to read and write from my DynamoDB table. I restored those lines for the time being.

At the moment, this code, assigning the credentials to the global namespace, seems to be necessary to access my DynamoDB tables:
```
Auth.currentUserCredentials()
	.then(credentials => 
		{
			global.AWS.config.credentials = credentials;
			...
		})
```

I currently have the following questions:
1. What call sequence or event processing is needed to establish valid credentials for federated sign-in?
2. How can credentials, provided from either Cognito or federated sign-in, be made available to DynamoDB?

Thank you for your time.

**Comment by TheVaporTrail** [comment] 2020-07-06 22:00
Keeping the code changes mentioned above (specifically, using `Hub` to listen for `Auth` events), I do not have the access denised problem when I downgrade to amplify@2.3.0.

```
$ npm ls --depth=0
PolygoniaV2_Dev2@1.0.0 /Users/david/Desktop/Development/Javascript/PolygoniaV2_Dev2
├── aws-amplify@2.3.0
├── copy-webpack-plugin@6.0.3
├── lodash@4.17.15
├── webpack@4.43.0
└── webpack-cli@3.3.12
```

**Comment by Amplifiyer** [comment] 2020-07-06 23:25
@TheVaporTrail it seems you were using aws-amplify V3 and aws-sdk V2 which is fine, but yes that would require you to set the global AWS credentials for services that you are using aws-sdk directly (i.e. outside of Amplify). 

Listening to Hub events is the right way to get the User credentials for both V2 and V3 of aws-amplify

**Comment by TheVaporTrail** [comment] 2020-07-06 23:45
@Amplifiyer, I was unsuccessful getting User credentials for federated sign-in using the `Hub` with aws-amplify V3. Not only did I have problems outside of Amplify, with dynamoDB, but I also had problems with the Amplify S3 Storage calls. 

In response to which Auth event can I call `Auth.currentUserCredentials()` when using federated sign-in?

Also, shouldn't the Amplify modules already have the user credentials for the S3 Storage calls when doing federated sign-in?

**Comment by TheVaporTrail** [comment] 2020-08-09 12:40
This issue was not resolved as per my July 6 comment.

**Comment by TheVaporTrail** [comment] 2020-09-17 21:09
I am commenting because this has just been marked stale. I have not had a chance to test with 3.x.x.

**Comment by iartemiev** [comment] 2021-04-02 20:14
We believe this should be fixed in the latest version of aws-amplify. Could you please let us know if you're still experiencing the issue with the current version?

**Comment by iartemiev** [comment] 2021-04-12 18:05
@TheVaporTrail,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:05 UTC
Labels: Auth, Federation, pending-close-response-required
