### ISSUE TITLE
ReactJS in production build isn't fully configuring Amplify

### ISSUE THREAD

**Issue by sblackstone** [aws-amplify/amplify-js#8060] opened 2021-04-08 22:12 UTC
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Environment information

<details>

```
  System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 53.00 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.24.0 - ~/.nvm/versions/node/v10.24.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v10.24.0/bin/npm
  npmGlobalPackages:
    create-react-app: 4.0.3
    npm: 6.14.11

```

</details>

### Describe the bug

I'm using Amplify.configure manually with my own details and its in my top level react component.

In development, this works fine, the when I load Amplify within another class, its configured.

e.g.
```
AmplifyClass {_components: Array(15), _config: {…}, _modules: {…}, Auth: AuthClass, Analytics: AnalyticsClass, …}
```

When I do a production build (`yarn build`), the same code yields window.Amplify as 

```
e {_components: Array(5), _config: {…}, _modules: {…}, Auth: e, Analytics: null, …}
```

I've added debugging to ensure that my call to Amplify.configure is still happening, and it is...  (It actually happens as part of a React.useEffect which I hope is ok so long as the rest of my application doesn't render until this step is complete)

### Expected behavior

window.Amplify should be of type AmplifyClass regardless of whether we are in development or production.

### Reproduction steps

create a new app

manually do Amplify.configure in your App (in my case this is part of a useEffect)

insepect window.Amplify in a production vs development build.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

As this isn't an amplify app, this is being called..

```
Amplify.configure({
  Auth: {
    region: 'us-east-1',
    identityPoolId: "xxx",
    userPoolId: 'xxx',
    userPoolWebClientId: 'xxx', 
  },
  API: {
      endpoints: [
          {
              name: "xxx",
              endpoint: "xxx",
          }
      ]
  }
});
```

**Comment by sblackstone** [comment] 2021-04-08 22:18
PRODUCTION LOG

```
[DEBUG] 16:33.111 Amplify - amplify config {Auth: {…}, API: {…}}
ConsoleLogger.ts:91 [DEBUG] 16:33.111 AuthClass - configure Auth
ConsoleLogger.ts:99 [DEBUG] 16:33.112 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 16:33.112 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:91 [DEBUG] 16:33.113 Storage - storage configure called
ConsoleLogger.ts:91 [DEBUG] 16:33.113 StorageClass - configure Storage
ConsoleLogger.ts:99 [DEBUG] 16:33.113 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 16:33.113 AWSS3Provider - configure Storage undefined
ConsoleLogger.ts:91 [DEBUG] 16:33.114 Storage - storage vault configure called
ConsoleLogger.ts:91 [DEBUG] 16:33.114 StorageClass - configure Storage
ConsoleLogger.ts:99 [DEBUG] 16:33.114 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 16:33.115 AWSS3Provider - configure Storage undefined
ConsoleLogger.ts:91 [DEBUG] 16:33.115 I18n - configure I18n
ConsoleLogger.ts:91 [DEBUG] 16:33.115 I18n - create I18n instance
App.tsx:84 {userPoolId: "us-east-xxxxx", userPoolClientId: "xxxx", identityPoolId: "us-east-1:fxxxxx", apiGateway: "xxxx.execute-api.us-east-1.amazonaws.com"}
ConsoleLogger.ts:91 [DEBUG] 16:33.190 AuthClass - getting current authenticated user
ConsoleLogger.ts:91 [DEBUG] 16:33.191 AuthClass - get current authenticated userpool user
ConsoleLogger.ts:99 [DEBUG] 16:33.194 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signedin", data: e}
ConsoleLogger.ts:91 [DEBUG] 16:33.194 AuthClass - getting current authenticated user
ConsoleLogger.ts:99 [DEBUG] 16:33.195 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signedin", data: e}
ConsoleLogger.ts:91 [DEBUG] 16:33.195 AuthClass - getting current authenticated user
ConsoleLogger.ts:99 [DEBUG] 16:33.195 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signedin", data: e}
2ConsoleLogger.ts:91 [DEBUG] 16:33.195 AuthClass - get current authenticated userpool user
ConsoleLogger.ts:99 [INFO] 16:33.225 Authenticator - Inside onAuthStateChange Method current authState: loading
ConsoleLogger.ts:99 [INFO] 16:33.226 Authenticator - Auth Data was set: e {username: "bf8a4a22-114e-46d8-b954-c14d8859c3d8", pool: e, Session: null, client: e, signInUserSession: e, …}
ConsoleLogger.ts:91 [INFO] 16:33.226 Authenticator - authState has been updated to signedin
```

**Comment by sblackstone** [comment] 2021-04-08 22:19
DEVELOPMENT LOG

```
[DEBUG] 18:56.723 Amplify - amplify config {Auth: {…}, API: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.723 I18n - configure I18n
ConsoleLogger.ts:91 [DEBUG] 18:56.723 I18n - create I18n instance
ConsoleLogger.ts:91 [DEBUG] 18:56.723 AuthClass - configure Auth
ConsoleLogger.ts:99 [DEBUG] 18:56.723 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 18:56.724 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.724 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.724 AnalyticsClass - on hub capsule auth {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.724 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.725 AnalyticsClass - configure Analytics {Auth: {…}, API: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.725 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 18:56.725 AWSPinpointProvider - configure Analytics {disabled: undefined, autoSessionRecord: true, Auth: {…}, API: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.726 Hub - Dispatching to analytics with  {event: "configured", data: null, message: "The Analytics category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.726 AnalyticsClass - on hub capsule analytics {event: "configured", data: null, message: "The Analytics category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.726 AnalyticsClass - current configuration {autoSessionRecord: true, Auth: {…}, API: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.726 Storage - storage configure called
ConsoleLogger.ts:91 [DEBUG] 18:56.726 StorageClass - configure Storage
ConsoleLogger.ts:99 [DEBUG] 18:56.726 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 18:56.727 AWSS3Provider - configure Storage undefined
ConsoleLogger.ts:91 [DEBUG] 18:56.727 Storage - storage vault configure called
ConsoleLogger.ts:91 [DEBUG] 18:56.727 StorageClass - configure Storage
ConsoleLogger.ts:99 [DEBUG] 18:56.727 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 18:56.727 AWSS3Provider - configure Storage undefined
ConsoleLogger.ts:99 [DEBUG] 18:56.727 RestAPI - configure Rest API {opt: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.728 RestAPI - create Rest API instance
ConsoleLogger.ts:99 [DEBUG] 18:56.728 RestClient - API Options {endpoints: Array(1), Auth: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.728 PubSub - configure PubSub {opt: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.728 GraphQLAPI - configure GraphQL API {opt: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.728 GraphQLAPI - create Rest instance
ConsoleLogger.ts:99 [DEBUG] 18:56.728 RestClient - API Options {Auth: {…}, endpoints: Array(1)}
ConsoleLogger.ts:99 [DEBUG] 18:56.728 RestAPI - configure Rest API {opt: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.728 RestAPI - create Rest API instance
ConsoleLogger.ts:99 [DEBUG] 18:56.729 RestClient - API Options {endpoints: Array(1), Auth: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.729 GraphQLAPI - configure GraphQL API {opt: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.729 GraphQLAPI - create Rest instance
ConsoleLogger.ts:99 [DEBUG] 18:56.729 RestClient - API Options {Auth: {…}, endpoints: Array(1)}
ConsoleLogger.ts:99 [DEBUG] 18:56.730 Interactions - configure Interactions {opt: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.730 XR - configure XR {opt: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.730 AbstractXRProvider - configure SumerianProvider {Auth: {…}, API: {…}}
ConsoleLogger.ts:99 [DEBUG] 18:56.730 Predictions - configure Predictions {Auth: {…}, API: {…}}
ConsoleLogger.ts:91 [DEBUG] 18:56.730 AuthClass - configure Auth
ConsoleLogger.ts:99 [DEBUG] 18:56.730 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.ts:99 [DEBUG] 18:56.731 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.731 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.732 AnalyticsClass - on hub capsule auth {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.ts:99 [DEBUG] 18:56.732 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
App.tsx:84 {userPoolId: "us-east-1_bz3CR2mjF", userPoolClientId: "gepmt5uf4l3l9tduo3snbipk", identityPoolId: "us-east-1:fbeeb93d-61b8-4173-9fca-d5d3078c5df1", apiGateway: "z575q1rv3l.execute-api.us-east-1.amazonaws.com"}
ConsoleLogger.ts:91 [DEBUG] 18:56.759 AuthClass - getting current authenticated user
ConsoleLogger.ts:91 [DEBUG] 18:56.760 AuthClass - get current authenticated userpool user
ConsoleLogger.ts:99 [DEBUG] 18:56.764 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signedin", data: CognitoUser}
ConsoleLogger.ts:91 [DEBUG] 18:56.765 AuthClass - getting current authenticated user
ConsoleLogger.ts:99 [DEBUG] 18:56.766 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signedin", data: CognitoUser}
ConsoleLogger.ts:91 [DEBUG] 18:56.766 AuthClass - getting current authenticated user
ConsoleLogger.ts:99 [DEBUG] 18:56.767 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signedin", data: CognitoUser}
ConsoleLogger.ts:91 [DEBUG] 18:56.767 AuthClass - get current authenticated userpool user
ConsoleLogger.ts:91 [DEBUG] 18:56.768 AuthClass - get current authenticated userpool user
ConsoleLogger.ts:99 [INFO] 18:56.827 Authenticator - Inside onAuthStateChange Method current authState: loading
ConsoleLogger.ts:99 [INFO] 18:56.827 Authenticator - Auth Data was set: CognitoUser {username: "bf8a4a22-114e-46d8-b954-c14d8859c3d8", pool: CognitoUserPool, Session: null, client: Client, signInUserSession: CognitoUserSession, …}
ConsoleLogger.ts:91 [INFO] 18:56.828 Authenticator - authState has been updated to signedin

**Comment by wlee221** [comment] 2021-04-09 16:21
Hello @sblackstone, can you share which versions of Amplify you are on by running `npx envinfo  --npmPackages` on the root level of the package? And do you experience this issue with the latest version of Amplify?

**Comment by sblackstone** [comment] 2021-04-09 18:49
```
  npmPackages:
    @aws-amplify/ui-components: ^1.1.1 => 1.1.1
    @aws-amplify/ui-react: ^1.0.6 => 1.0.6
    @material-ui/core: ^4.11.3 => 4.11.3
    @material-ui/icons: ^4.11.2 => 4.11.2
    @testing-library/jest-dom: ^5.11.4 => 5.11.10
    @testing-library/react: ^11.1.0 => 11.2.6
    @testing-library/user-event: ^12.1.10 => 12.8.3
    @types/jest: ^26.0.15 => 26.0.22
    @types/node: ^12.0.0 => 12.20.7
    @types/react: ^17.0.0 => 17.0.3
    @types/react-dom: ^17.0.0 => 17.0.3
    @types/react-router-dom: ^5.1.7 => 5.1.7
    aws-amplify: ^3.3.26 => 3.3.26
    node-fetch: ^2.6.1 => 2.6.1
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-router-dom: ^5.2.0 => 5.2.0
    react-scripts: 4.0.3 => 4.0.3
    typescript: ^4.1.2 => 4.2.3
    web-vitals: ^1.0.1 => 1.1.1
    ```

**Comment by wlee221** [comment] 2021-04-12 18:15
Thanks for the reply. Can you share some code snippets how and where you are calling `Amplify.configure`? This should be configured once at the top level and not inside `useEffect`. Also, you should only directly reference what's imported from `import { Amplify } from 'aws-amplify'`.

**Comment by sblackstone** [comment] 2021-04-12 18:46
This should be a minimal example...  When I use a build version of this, the console.log shows null.  When I use this in development mode, it shows a properly populated AmplifyClass object.

```
const App: React.FunctionComponent = () => {
    const [ amplifyReady, setAmplifyReady ] = React.useState<any|null>(null);

    const configAmplify = async () => {
      const apiEndpoint = "https://tquhpwuu91.execute-api.us-east-1.amazonaws.com/v1";
      const data = await window.fetch(`${apiEndpoint}/meta`);
      const meta = await data.json();

      Amplify.configure({
        Auth: {
          region: 'us-east-1',
          identityPoolId: meta.identityPoolId,
          userPoolId: meta.userPoolId,
          userPoolWebClientId: meta.userPoolClientId,
        },
        API: {
            endpoints: [{ name: "subscriber", endpoint: `https://${meta.apiGateway}/v1`}]
        }
      });
      console.log(Amplify.API);
      setAmplifyReady(true);
    };

    React.useEffect(()=> {
        if (!amplifyReady) {
          configAmplify();
        }
    });

    return amplifyReady === (<h1>Loading</h1>) ? null : (
      <h1>Hello World</h1>
    );
}
```

**Comment by wlee221** [comment] 2021-04-13 02:51
Thanks for providing the sample app! I was able to run it and reproduce your issue on prod. The problem is that `Amplify.configure` is being [tree-shaken](https://webpack.js.org/guides/tree-shaking/) by webpack. 

To prevent this, use `import Amplify, { API } from 'aws-amplify'`  instead of using `Amplify.API` (fyi the former method is deprecated and should not be used). This marks the API category as used and webpack will not eliminate code from it. I was able to confirm that importing `{ API }` prevented it from being eliminated. Here's my edited code snippet in case it might help.

<details>
 <summary>App.js</summary>

```js
import React from 'react';
import './App.css';
import Amplify, { API } from 'aws-amplify';

const App = () => {
  const [amplifyReady, setAmplifyReady] = React.useState(null);

  const configAmplify = async () => {
    const debugEndpoint =
      'https://dlxc2rhip4.execute-api.us-east-1.amazonaws.com/v1';
    const data = await window.fetch(`${debugEndpoint}/meta`);
    const meta = await data.json();

    Amplify.configure({
      Auth: {
        region: 'us-east-1',
        identityPoolId: meta.identityPoolId,
        userPoolId: meta.userPoolId,
        userPoolWebClientId: meta.userPoolClientId,
      },
      API: {
        endpoints: [
          { name: 'subscriber', endpoint: `https://${meta.apiGateway}/v1` },
        ],
      },
    });
    console.log(Amplify, API); // API used here, let webpack know API is being used
    setAmplifyReady(true);
  };

  React.useEffect(() => {
    if (!amplifyReady) {
      configAmplify();
    }
  }, [amplifyReady]); // make sure this hook is not called multiple times once `amplifyReady` is set

  return amplifyReady ? <h1>Hello World</h1> : <h1>Loading</h1>;
};

export default App;
```

</details>

ps. we suggest you ensure you only call `Amplify.configure` once at the top level, outside your react component to prevent possible side-effects.

**Comment by wlee221** [comment] 2021-04-13 02:52
Please let us know if using `import Amplify, { API } from 'aws-amplify'` works for you too.

**Comment by sblackstone** [comment] 2021-04-13 13:35
Yep, that resolves it for me as well...

-S

**Comment by wlee221** [comment] 2021-05-25 20:26
@sblackstone, apologies for the late reply. In that case, it should be okay to do it with the code snippet you shared (or having those aws-exports credentials stored somewhere secure so you don't need to fetch it). I'll be closing this as tree-shake problem was resolved. Please feel free to open a new issue if you face difficulties with Amplify. Thanks!

**Closed by wlee221** 2021-05-25 20:26 UTC
Labels: React
