### ISSUE TITLE
Trying Auth.signout to clear the cognito session, shows a pop-up "Appname" wants to use "amazoncognito.com" to Sign in

### ISSUE THREAD

**Issue by payalb** [aws-amplify/amplify-js#10723] opened 2022-07-07 05:31 UTC
**Page**: [`/lib/auth/emailpassword/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js)

**Feedback**:

When trying to use Auth.signout to clear the cognito session, shows a pop-up "Appname" wants to use "amazoncognito.com" to Sign in. Is there a way to prevent this pop-up from being shown?
<img width="957" alt="1" src="https://user-images.githubusercontent.com/18390065/177698776-27474d7d-3851-4488-b244-260b83df7dc4.png">

**Comment by nadetastic** [comment] 2022-11-30 23:39
Hi @payalb 👋,

This appears to be unexpected behavior, as the SignOut method should not display this pop up. Could you clarify your use case a bit more?

I.E. Did you sign in with cognito user pools or social sign in? (`Auth.signIn` vs `Auth.federatedSignIn`) also since there has been a recent major release of Amplify (V5) can you confirm if you are still facing this issue and on what version?

**Comment by nadetastic** [comment] 2022-12-01 21:49
Hi @payalb following up here, I'll close this out since it is a duplicate of #3410 please follow up with any comments on the other issue.

**Closed by nadetastic** 2022-12-01 21:49 UTC
Labels: Auth, OAuth, transferred, pending-response, pending-triage

**Comment by ucheNkadiCode** [comment] 2022-12-05 11:48
I have this exact issue as well
