### ISSUE TITLE
Amplify and preflight requests.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-js#3007] opened 2019-04-04 09:30 UTC
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
APIGW, Lambda
** Provide additional details e.g. code snippets **
AngularJS app. Using the API.get() method of amplify
Generated a function using the "CRUD function for Amazon DynamoDB table (Integration with Amazon API Gateway and Amazon DynamoDB)" option. (amplify function add)
Generated an API for that function. (amplify api add)

A preflight request is sent to get the OPTIONS. The problem is how to handle that request in the lambda function? I've added the following:
```
app.options("/*", function(req, res) {
  res.json({});
});
```
This works locally when I run the function using invoke. But I don't know how to simulate the APIGW. 
The error on the APIGW logs are:
```
Execution failed due to configuration error: statusCode should be an integer which defined in request template
Method completed with status: 500
```

What is weird is that the Lambda does not get invoked at all. There's no logs. I could be missing some configuration in the APIGW?

I've read every issue and none has help. Any help would be much appreciated. It must be a simple fix, because how would anyone else using Angular get around this? Thanks.

Regards.
Jarrett

**Comment by elorzafe** [comment] 2019-04-04 18:28
@jarrettj I suspect the problem is with the path of the api, the path is tightly coupled to the lambda function. I would create the function directly from `amplify api add` instead of creating the function first and then select it as you did.

just run `amplify api add` and then create the function from there.

Also make sure that the **path** you are specifying on `API.get('api-name', path)` is correct usually it would be like this `API.get('api-name','/items')`

**Comment by jarrettj** [comment] 2019-04-04 19:41
Hi

Good day.

Will give your method a try, maybe the CF configuration that’s created for APIGW is a bit different when done that way. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jarrettj** [comment] 2019-04-05 06:16
Hi,

Steps I took:
```
amplify add api
```

Instead of adding via an amplify function add and then amplify api add. 

Same result. Even tried Postman to test. To eliminate having to run the app, as it is tedious. The GET/POST/PUT requests all succeed. So it is not a typo. The difference is the header. 

I've gone to the APIGW and enabled CORS as well. The issue is not with the Lambda, or the angular code, like I said it is the APIGW. It is not even executing the Lambda function, it sees the OPTIONS header and breaks.

I then re-looked at what you said. And used just the path '/items' and bang it works. The OPTIONS call goes through, 200 OK. But the GET request fails. Which makes sense, because there's nothing catching the "/items" request path. The generated Lambda expects the path to be "/items/:id". I think the generated code for accessing a DynomoDB table and the integration with APIGW are not working well together. 

Before I completely rewrite the generated Lambda, is there something simple I am missing here? Will continue to look around for examples. Thanks.

Regards.

**Comment by jarrettj** [comment] 2019-04-05 12:39
I think I might have tracked it down a bit further. Created another API, but this time I choose not to use authentication. Without authentication, all requests are working. So I'm not too sure what it is about the authentication. 

I returned to debugging the API with authentication and made the CORS request work. The next request however after the preflight success gives a status code 403 with no content. When I copy that request to Postman it gives the below error:
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

I went through the issues with this error and they pointed me into the direction of url encoding my path parameters. That did not work.

Well, at least I have made some progress. Hope this sheds a bit more light. Thanks.

Regards.

**Comment by jarrettj** [comment] 2019-04-05 13:05
On closer inspection, https://github.com/aws-amplify/amplify-js/issues/718 is not my issue. As it fails from the S3 bucket in the same way.

**Comment by jarrettj** [comment] 2019-04-09 05:02
Found https://github.com/aws-amplify/amplify-js/issues/1857 and realised I should just create my own functions to deal with query parameters instead of path parameters. I added the following:
```
app.get(path, function (req, res) {
   let queryStringParameters = req.query;
   if (queryStringParameters.user_id === undefined) {
     var params = {
       TableName: tableName,
       Select: 'ALL_ATTRIBUTES',
     };
     dynamodb.scan(params, (err, data) => {
       if (err) {
         res.json({ error: 'Could not load items: ' + err.message });
       }

       res.json(data.Items)
     });
   }
   else {
     // Set request params to keep code similar
     req.params = req.query;
     var condition = {}
     condition[partitionKeyName] = {
       ComparisonOperator: 'EQ'
     }

     if (userIdPresent && req.apiGateway) {
       condition[partitionKeyName]['AttributeValueList'] = [req.apiGateway.event.requestContext.identity.cognitoIdentityId || UNAUTH ];
     } else {
       try {
         condition[partitionKeyName]['AttributeValueList'] = [ convertUrlType(req.params[partitionKeyName], partitionKeyType) ];
       } catch(err) {
         res.json({error: 'Wrong column type ' + err});
       }
     }

     let queryParams = {
       TableName: tableName,
       KeyConditions: condition
     }

     dynamodb.query(queryParams, (err, data) => {
       if (err) {
         res.json({error: 'Could not load items: ' + err});
       } else {
         res.json(data.Items);
       }
     });
   }
 });
```

It now handles getting the items by the partition key or getting all items. Hopefully this helps someone else. 

I've also disabled auth on my functions. As I now have no idea what is going on there. I do know that with auth all the routes seem to work differently. The requests do not even make it to APIGW. Since I'm doing a POC, authenticated APIs are not a must right now. Will continue to investigate. 

Regards.

**Comment by sammartinez** [comment] 2019-06-19 19:28
@jarrettj I did want to provide you a guide of setting up API GW with CORS and further [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html) in regards to this issue. This should give you a little more insight into configuring OPTIONS and other operations you're looking to use. In reading your response above, it seems that you have solved your issue. Im going to close this issue, please feel free to reopen it if there is something else with this issue your are looking to discuss

**Closed by sammartinez** 2019-06-19 19:28 UTC
Labels: API, pending-close-response-required, question, to-be-triaged

**Comment by jarrettj** [comment] 2019-06-20 08:12
Hi, good morning. 

I never solved it. Ended up leaving all my APIGW open and public. The only way I could get it to work. And it is not personal sensitive data, so not an issue. But would be nice to get the auth to work as well. 

When I have time, I'll follow your documentation and hopefully I have missed something very simple! Thanks.
