### ISSUE TITLE
Datastore timeout when internet drops intermittently and app in background for too long

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-js#6162] opened 2020-06-25 10:21 UTC
**Describe the bug**
Datastore loses realtime sync as soon as network disconnects and reconnect immediately. Few minutes later, Datastore shows up a bunch of warning errors.
`15:31:20.149	client_log	[WARN] 31:20.155 DataStore - Timeout disconnect`

**To Reproduce**
1. Open the React Native app on device A and B.
2. Starts the syncing process with `Datastore.start()`. (Client is connected with Server via Websocket)
3. Unplug the LAN cable from your router, reconnect it immediately.
4. Insert new record on device B with an active internet connection (different network).
5. Device A does not receive the record from Device B.
6. On device A, `[WARN] 31:20.155 DataStore - Timeout disconnect` shows up few minutes later.

**Environment**
iPad (iOS 13)
React Native

**Amplify version**
├─ @aws-amplify/analytics@3.2.1
├─ @aws-amplify/api-graphql@1.1.0
├─ @aws-amplify/api-rest@1.1.0
├─ @aws-amplify/api@3.1.17
├─ @aws-amplify/auth@3.2.14
├─ @aws-amplify/cache@3.1.17
├─ @aws-amplify/core@3.4.0
├─ @aws-amplify/datastore@2.2.4
├─ @aws-amplify/interactions@3.1.17
├─ @aws-amplify/predictions@3.1.17
├─ @aws-amplify/pubsub@3.0.18
├─ @aws-amplify/storage@3.2.7
├─ @aws-amplify/ui@2.0.2
├─ @aws-amplify/xr@2.1.17
├─ aws-amplify-react-native@4.2.1
└─ aws-amplify@3.0.18

**Additional context**
Based on my findings, NetInfo checks whether the internet is reachable every 60 seconds.
If the device is disconnected and reconnected to the Internet before NetInfo performs the check, AppSync & Datastore do not have any idea there was a connection drop. Therefore, AppSync does not re-establish the websocket connection even though it's already broken.

**My current workaround**
I have lowered down both `reachabilityLongTimeout` and `reachabilityRequestTimeout` to 5 seconds.
With this change, NetInfo is able to tell whether the WiFi has an active internet connection or not much quicker.
It kinda fixes this issue as Appsync can re-establish the Websocket connection much more responsively.

**Comment by elorzafe** [comment] 2020-06-26 20:08
@nubpro You see the warning but dont see the data?

**Comment by nubpro** [comment] 2020-06-26 20:17
> @nubpro You see the warning but dont see the data?

No data is received by the client, as stated in step 5.

**Comment by mdoesburg** [comment] 2020-06-27 00:00
I have also witnessed this timeout disconnect warning after closing my laptop while my app was still running on iOS Simulator. The only way to make the app/connectivity work again was a reload of the simulator or reboot of the app.

**Comment by nubpro** [comment] 2020-06-27 00:31
The main problem is that in our productiom environment, we could not tell based on just looking at the app. We would only know when no new records are getting received by the device and this is not great, imagine missing out all the orders placed by your customers. We are losing money here and it impacts the business.

Is there a way that we could monitor the healthiness of the websocket connection between the client and the server? If so, we could at least restart the app and reinitiate the websocket. Because at the moment, there is no indicator from datastore and we could not catch the datastore timeout error programatically.

This is huge to us, please provide a temporary solution to us.

**Comment by nubpro** [comment] 2020-06-27 06:10
I would also like to add, if the app is in background mode for too long, the subscription will fail - `Datastore - Timeout Disconnect`.

Listening to the Datastore's networkStatus from Hub listener, is not useful in detecting a socket failure. It still shows active network despite the timeout disconnection.

Diving into the source code, the exact warning is thrown at [line 360 @ subscription.ts](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/processors/subscription.ts#L360).

**Comment by nubpro** [comment] 2020-07-08 05:10
Can we at least get an acknowledgement from DataStore engineers on this?
@sammartinez

**Comment by sammartinez** [comment] 2020-07-08 15:15
Yes, @nubpro I can let them know. Apologizes on the delay!

**Comment by iartemiev** [comment] 2020-07-08 17:12
Thank you for the detailed reproduction instructions, @nubpro. I was able to reproduce. Took exactly 5 minutes for device A to show the error message you specified in step 6. We will start investigating and working on a fix for this.

**Comment by nubpro** [comment] 2020-07-17 04:08
Just wondering is there an update to this?

@iartemiev

**Comment by nubpro** [comment] 2020-07-20 03:47
By lowering `reachabilityLongTimeout` significantly at NetInfo configuration, NetInfo will have a better chance knowing that there's a connection drop.

However, there is still a tendency where the subscription has failed but DataStore didn't attempt to restart.
Hence, I've submitted a PR that fixes the built-in disconnection handler. I'm not sure why it wasn't called in the first place.

**Comment by nubpro** [comment] 2020-07-27 06:02
The current implementation does not allow subscriptions to reinitiate when PubSub returns `Subscription timeout {query: ..., variables: ...}` which is caused by poor network condition when initiating the subscription the first time.

Is it possible that we could do reconnection in this case?

**Comment by amhinson** [comment] 2020-12-14 22:56
This issue appears to be related to https://github.com/aws-amplify/amplify-js/issues/6488. Since the connected PR #6366 for this issue has been merged, I'm going to close this so any further discussion happens on the related issue.

**Closed by amhinson** 2020-12-14 22:56 UTC
Labels: DataStore, React Native, bug
