### ISSUE TITLE
Transcribe Streaming (Predictions) Support AudioStream data type

### ISSUE THREAD

**Issue by ranilian** [aws-amplify/amplify-js#4046] opened 2019-09-19 20:16 UTC
**Is your feature request related to a problem? Please describe.**
The Predictions API makes it easy to integrate with Transcribe Streaming by passing in the raw audio bytes. This feature request describes updating the API so that we can pass the raw audio stream into the Predictions.convert call so that audio is streamed in realtime without having to split the audio bytes into multiple calls. In other words, I would like the capability to call a function and pass it my audio stream and have it fire a callback every time I get a response back from Transcribe (with the transcription information). Behind the scenes, the WebSocket connection lifecycle is all managed and maintained by the library (including timeout and refreshing).

**Describe the solution you'd like**

Something like this:

```
Predictions.convert({
      transcription: {
        source: {
          inputAudioSource
        },
        // language: "en-US", // other options are "en-GB", "fr-FR", "fr-CA", "es-US"
      },
    }).then(({ transcription: { fullText } }) => console.log(fullText)) // this gets fired multiple times with the updated transcription in realtime.
      .catch(err => console.log(JSON.stringify(err, null, 2)))
  }
```

**Comment by aswin-github** [comment] 2020-04-06 06:52
Any updates on this? Is this working for react native app? I am trying this, and getting an empty string as response.

 How to test Prediction.Convert with a sample audio file as input?

**Comment by nadetastic** [comment] 2022-10-28 16:00
This is a duplicate of #6404 which is more recent and has more details. Closing this in order to track there.

**Closed by nadetastic** 2022-10-28 16:00 UTC
Labels: feature-request, Predictions
