### ISSUE TITLE
Unmet peer dependency react-native netinfo

### ISSUE THREAD

**Issue by Raynos** [aws-amplify/amplify-js#5255] opened 2020-04-01 10:44 UTC
**Describe the bug**

When install `@aws-amplify/auth` to do authentication in my website I get 

```
│ │ └── UNMET PEER DEPENDENCY @react-native-community/netinfo@^5.5.0
```

This is from
```
raynos at raynos-Precision-5530  
~/optoolco/optool.co on invoices-page*
$ npm ls
optool.co@1.0.0 /home/raynos/optoolco/optool.co
├─┬ @aws-amplify/auth@2.1.3
│ ├─┬ @aws-amplify/cache@2.1.8
│ │ ├─┬ @aws-amplify/core@2.3.0
```

The `@react-native-community/netinfo` is a dependency from `@aws-ampliyf/core@2.3.0` and my website does not use react native.

**To Reproduce**

Install `npm i @aws-amplify/auth -S`

**Expected behavior**

Installing and `npm ls` should not complain about unmet peer dependencies.

**Comment by Ashish-Nanda** [comment] 2020-04-02 18:59
Hi @Raynos 
Its a warning for React Native developers who need to install the peer dependency, so you can ignore it if you dont use React Native.

We are looking at how we can remove the dependency on `@react-native-community/netinfo` for `@aws-amplify/core`, but till then need it to be a peer dependency, which I dont believe can be platform specific. 

Let us know if you are seeing any bug because of this other than the warning, otherwise I can go ahead and close this issue.

**Comment by Raynos** [comment] 2020-04-03 08:34
One approach that I’ve taken for this in the past is to make optional dependencies a runtime exception instead of an Npm install or npm ls warning.

Basically remove it from peer dependencies and wrap the require in a try / catch and throw a friendly exception if the dependency is missing. 

Warning at runtime for react native users is more friendly / fail fast then warning at install time.

**Comment by Ashish-Nanda** [comment] 2020-04-24 23:59
Hi @Raynos, that would have been ideal, but as far as I know, the React Native packager does not support catching dependency exceptions at runtime. I had tried this initially.
Here is an issue similar to what you are pointing out https://github.com/facebook/react-native/issues/5079

For now I have removed the NetInfo dependency from Core and moved it to DataStore. So you should only get the peer dependency warning if you install `@aws-amplify/datastore` or all of amplify through `aws-amplify`. 

I'm going to go ahead and close the issue as this is not a bug and a developer not working with React Native can safely ignore the warning. 

If you have other suggestions besides the catching the dependency exception at runtime, still feel free to let us know in a comment below, and I'll take a look if the approach is viable and preferable.

**Closed by Ashish-Nanda** 2020-04-24 23:59 UTC
Labels: React Native, to-be-reproduced, version-2

**Comment by Raynos** [comment] 2020-04-25 07:19
Removing it from core is very helpful.

The only modules I need are core and auth

I don’t use any amplify features. I just want to sign in and sign up with cognito pools
