### ISSUE TITLE
Support for pool per tenant

### ISSUE THREAD

**Issue by s1mrankaur** [aws-amplify/amplify-js#7539] opened 2021-01-11 07:00 UTC
**Is your feature request related to a problem? Please describe.**
AWS suggests using pool per tenant in multi-tenant saas applications but amplify does not seem to support it

**Describe the solution you'd like**
Native support for pool per tenant for multi-tenant apps

**Comment by abdallahshaban557** [comment] 2022-09-09 12:58
Closing this issue as a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/452

**Closed by abdallahshaban557** 2022-09-09 12:58 UTC
Labels: feature-request, Auth
