### ISSUE TITLE
[Feedback]Breaking change warning error for crypto lib

### ISSUE THREAD

**Issue by rajinder-yadav** [aws-amplify/amplify-js#9005] opened 2021-07-02 05:47 UTC
I am getting the following error for Angular 12 app following the steps, I think this should be looked and fixed, or a work around provided.

```sh
Build at: 2021-07-02T05:39:19.626Z - Hash: a2b97afd082645cf4ed2 - Time: 514ms

./node_modules/crypto-js/core.js:43:22-39 - Warning: Module not found: Error: Can't resolve 'crypto' in '/home/yadav/dev/tmp/amplify-app/node_modules/crypto-js'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```

**Comment by tannerabread** [comment] 2022-10-12 18:38
Closing this as a duplicate of #8527

**Closed by tannerabread** 2022-10-12 18:38 UTC
Labels: Angular, dependencies, transferred, pending-triage
