### ISSUE TITLE
An unknown error has ocurred.

### ISSUE THREAD

**Issue by KenSosa95** [aws-amplify/amplify-js#13208] opened 2024-03-29 09:25 UTC
Hi, I am following the tutorial to implement authentication for my mobile app created with react native. It allows me to sign up and reset password but when I try to sign in it shows me this message: "An unknown error has occurred." 
I have installed everything how it says and I have done this multiple times starting from scratch and still getting the same issue.

**Comment by cwomack** [comment] 2024-04-02 18:57
Hello, @KenSosa95 👋 and thanks for the details you've already provided on this issue. We'll take a look at it and see if we can reproduce as well as follow up with any questions we have from the `amplify-js` side. 

Looks to be related to the #13200 I've linked above as well.

**Comment by KenSosa95** [comment] 2024-04-03 09:13
Hi, @cwomack, thanks for replying. 
Quickly update:
When I run **npx expo start** it does not allow me to sign in to a device or emulator.
When I run **npx expo run:android** it lets me log in to an Android emulator but it doesn't open the project in the device. 

I guess the problem is related with **Expo go**

**Comment by calebpollman** [comment] 2024-04-03 15:34
@KenSosa95 Was able to reproduce the issue in an expo project without using expo go and believe the root cause to be missing required React Native polyfill dependencies. Can you try adding both `react-native-get-random-values` and `react-native-url-polyfill` to your project and rebuild by running:
```sh
npx expo install react-native-get-random-values react-native-url-polyfill
```
then:

```sh
npx expo run:android
```

**Comment by cwomack** [comment] 2024-04-04 15:14
@KenSosa95, let us know when you get a chance to review @calebpollman's comment above and if it helps resolve the issue.  Thanks!

**Comment by KenSosa95** [comment] 2024-04-04 20:35
@calebpollman @cwomack react-native-get-random-values is already installed. 
As I said before
When I run npx expo start it does not allow me to sign in to a device or emulator.
When I run npx expo run:android it lets me log in to an Android emulator but it doesn't open the project in the device.
(must be a problem related with Expo go)
Now at least I can continue developing the app but I cannot test it in a physical device. I have to do it only in the emulator. 

Thanks for the help!

**Comment by cwomack** [comment] 2024-04-05 15:49
@KenSosa95, can see if passing the `USER_PASSWORD_AUTH` flow type within your `handleSignIn` of the services prop for the authenticator helps at all?

**Comment by bertoninicolas** [comment] 2024-04-07 03:06
> @calebpollman @cwomack react-native-get-random-values is already installed. As I said before When I run npx expo start it does not allow me to sign in to a device or emulator. When I run npx expo run:android it lets me log in to an Android emulator but it doesn't open the project in the device. (must be a problem related with Expo go) Now at least I can continue developing the app but I cannot test it in a physical device. I have to do it only in the emulator.
> 
> Thanks for the help!

Good night people! I hope everyone is well. Message from Brazil, thanking the strong community we have here.

I was experiencing the same problem reported above, finally after testing it on the web, I was able to log in.

Using the iOS device or Android emulator, it is not possible to log in, only register and recover.

Now we can continue with our projects.

**Comment by cwomack** [comment] 2024-04-09 18:59
Glad to hear you were able to get unblocked @bertoninicolas.

@KenSosa95, are you still experiencing this?

**Comment by KenSosa95** [comment] 2024-04-09 19:48
@cwomack When I run npx expo start I am still not able to log in. 
If I run npx expo run: android I am able to to log in. I will continue using only npx expo run: android.

**Comment by GlenTiki** [comment] 2024-05-01 12:38
@cwomack Hey, I've been doing something somewhat similar, that I think is related.

I'm essentially using the bare signIn function for a custom auth flow in my expo/react-native app with `import {signIn} from "aws-amplify/auth";`. I've been debugging it by adding logging in the installed dependency, and pinned it down to an error like the one discussed here: https://github.com/expo/expo/discussions/25586

**Comment by awshanks** [comment] 2024-05-06 21:49
Adding some more on this.  I just done the tutorial today and had the above issues.
Needed the polyfill `npx expo install react-native-get-random-values` or the add todo would not work (couldn't generate random values).

Also had to use `npm run ios` rather than `npm start` as the latter used expo go which is not supported.

**Comment by jewells07** [comment] 2024-06-26 16:16
Same issue
```javascript
 ERROR  [Unknown: An unknown error has occurred.]
 ERROR  [Error: The package '@aws-amplify/react-native' doesn't seem to be linked. Make sure:
 ```

**Comment by mazPrzemo89** [comment] 2024-09-08 18:42
You can always look at `underlyingError` property when you are working with aws-amplify `console.log((error as any).underlyingError);`

**Comment by cwomack** [comment] 2024-10-08 19:10
For anyone that comes across this issue or is still experiencing this, we've updated our docs within the [Quickstart](https://docs.amplify.aws/react-native/start/quickstart/) guide and other areas per [this PR in the docs repo](https://github.com/aws-amplify/docs/pull/7160) to clarify that we no longer have support for Expo Go.

There's also the helpful [comment](https://github.com/aws-amplify/amplify-js/issues/13208#issuecomment-2034941390) above from @calebpollman to help clarify how to resolve the missing polyfill for `react-native-get-random-values`.  

We'll close this issue as resolved at this point.

**Closed by cwomack** 2024-10-08 19:10 UTC
Labels: feature-request, documentation, Auth, React Native, transferred
