### ISSUE TITLE
auth w/ Google Federation - Access Token does not have required scopes

### ISSUE THREAD

**Issue by mtraynham** [aws-amplify/amplify-js#5921] opened 2020-05-27 14:24 UTC
**Describe the bug**
Upgraded from `"@aws-amplify/auth": "3.2.7"` to `"@aws-amplify/auth": "3.2.8"` and a federated login with Google stopped working with a 400 error from Cognito.

I initially upgraded to 3.2.8, and then downgraded back to 3.2.7, and downgrading has resolved the error.  None of the dependency versions for  `"@aws-amplify/auth"` were changed during the downgrade, so I believe the bug is specifically within the `auth` package.

Likely related to:
- @aws-amplify/auth: Fix OAuth multiple scopes (#5850) (f89e545)
- @aws-amplify/auth: Fix OAuth scopes (#5844) (e71fee5)

**To Reproduce**
Using `"@aws-amplify/auth": "3.2.8"`, login with a federated user and retrieve the session.

**Expected behavior**
It doesn't 400 and passes the scopes correctly.

**Code Snippet**

**Screenshots**
![CognitoError](https://user-images.githubusercontent.com/5741321/83032631-17eddf80-a004-11ea-94a4-8101689da6f8.jpg)

**What is Configured?**

**Smartphone (please complete the following information):**

- Device: Mac
- OS: OSX 10.15.4
- Browser: Chrome
- Version: 81.0.4044.138

**Additional context**

**Comment by elorzafe** [comment] 2020-05-28 19:50
@mtraynham as I mentioned on the issue #5935. Previous the change you mention the library was sending the query string param scopes instead of scope which is the correct param. The default behavior by Cognito when the scope param is missing is that it will return (as is mentioned on this [Authorization endpoint Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html)) all the scopes available.

Can you check if the scope you have configured are present on AllowedOAuthScopes on your App client (clientId) settings. You can check those on Cognito console under App Integration>App client settings or using aws cli aws cognito-idp describe-user-pool-client --user-pool-id us-west-2_xxxxxxxxx --client-id xxxxxxxxxxxxxxxx

**Comment by mtraynham** [comment] 2020-05-29 13:49
<img width="1194" alt="cognitoConfig" src="https://user-images.githubusercontent.com/5741321/83266777-4c42d680-a191-11ea-8694-60749dbff2b9.png">
<img width="1194" alt="cognitoConfig" src="https://user-images.githubusercontent.com/5741321/83266880-6da3c280-a191-11ea-8a4f-e052ac8fb799.png">
I believe I'm passing the `scope` param correctly...

**Comment by elorzafe** [comment] 2020-05-29 16:34
@mtraynham Can you check removing `phone` from authorized scopes, also check the settings for the App client like this
![Screen Shot 2020-05-29 at 9 31 40 AM](https://user-images.githubusercontent.com/28815678/83283147-962abd00-a18f-11ea-9360-ab182a7cb7bc.png)

**Comment by mtraynham** [comment] 2020-05-29 19:50
We have other providers that use phone, Google just doesn't provide that, so I can't really remove it ☹️

**Comment by pedramp20** [comment] 2020-07-28 04:37
I have the exact same problem, where users from external identity providers (federated) cannot update their attributes. Any updates on this?

**Comment by sammartinez** [comment] 2020-11-18 18:55
@mtraynham Can you let me know where you are at with this? We want to help you but I'm trying to understand if you were able to figure out a workaround for this issue? As @elorzafe [mentioned](https://github.com/aws-amplify/amplify-js/issues/5921#issuecomment-635560070), there were some changes that we made to fix the separation for string queries in order for not all scopes to be returned. Please let us know where you are at with this and where we can help. Thanks !

**Comment by camhart** [comment] 2020-11-21 08:49
I'm running into the same issue, attempting to use Google OAuth on a Vue SPA through AWS Amplify.  I can login using the direct api calls (Amplify.Auth.signIn), however I *can't* when I use `Amplify.Auth.federatedSignIn` whether I attempt to login user Google OAuth or Cognito User Pool credentials.  I get the same error:
```
{code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Access Token does not have required scopes"}
```

aws-exports oauth bit.
```
    oauth: {
      domain: 'xxxxx.auth.xx-xxxx-x.amazoncognito.com',
      scope: ['email', 'openid', 'profile'],
      redirectSignIn: 'http://localhost:8080/login/',
      redirectSignOut: 'https://localhost:8008/signout/',
      clientId: 'xxxxxxxxxx',
      responseType: 'token' //switch to code if you want a refresh token
    }
```

AppClient Scope settings:
![image](https://user-images.githubusercontent.com/3038809/99871832-61258300-2b92-11eb-82c1-7635dbfe6e05.png)


Identity Provider settings within my cognito user group
![image](https://user-images.githubusercontent.com/3038809/99871863-90d48b00-2b92-11eb-9307-44ad7c34238c.png)

Not sure if it matters, but I have some attributes mapped:
![image](https://user-images.githubusercontent.com/3038809/99871885-a944a580-2b92-11eb-80a8-1f01bee43ed6.png)

If you need anything else please let me know.

**Comment by nschneider-sommset** [comment] 2020-12-09 23:04
Im getting the same error whenever I attempt to even Read the user attributes of a cognito user. Any update on this?

**Comment by nite** [comment] 2021-01-21 17:31
How can Amazon, AWS and Cognito have a javascript client with 642 open issues, and a major issue like this that affects Cognito opened 8 months ago that hasn't had any activity in over a month?

**Comment by mtraynham** [comment] 2021-01-21 18:04
I'm stuck with `"@aws-amplify/auth": "3.2.7"` because of this bug.   Although, it has now piqued my interest again and following some of the links I provided 8 months ago, removal of `scope` from the `oauth` object may be the solution...

https://github.com/aws-amplify/amplify-js/issues/5935#issuecomment-635663704

**Comment by nite** [comment] 2021-01-22 12:00
This is not a bug with amplify per-se, it's an issue with Cognito & federated/SSO auth - if you look at the network tab when you call `await Auth.currentUserinfo()`, you can generate a curl command to replicate this outside of the js library 

```
curl 'https://cognito-idp.us-east-1.amazonaws.com/'  --data-raw '{"AccessToken":"<token>"}' ```  

which results in a 400 response with a response:  

```{"__type":"NotAuthorizedException","message":"Access Token does not have required scopes"}
```

**Comment by kylekirkby** [comment] 2021-02-10 13:29
Is there any update on this one?

I'm struggling to get a user's profile image (which was working around 9 months ago)... 

Something must have changed which has broken this?

I've attempted to call `await Auth.currentUserinfo();` but I'm also getting 
```{"__type":"NotAuthorizedException","message":"Access Token does not have required scopes"}```

Any ideas? @dabit3 @ericclemmons

**Comment by monty241** [comment] 2021-03-10 08:45
Same issue. Occurs on Cognito account that is still valid, but was already removed from the consuming application. We have disabled and then removed the user from Cognito.

**Comment by jonface** [comment] 2021-03-29 00:10
Same issue, what version of amplify doesn't have this issue?

**Comment by DeniferSantiago** [comment] 2021-04-29 20:15
Waiting for a miracle over here

**Comment by chrisbonifacio** [comment] 2021-04-30 22:16
Good evening, everyone 👋 Wanted to give an update on this issue before the weekend. 

We have have been trying to reproduce this issue this on `@aws-amplify/auth@3.2.8` and 3.2.7 as mentioned in the original comment. 

We have to yet to reproduce this issue with a Google OAuth flow but we will continue to look into it. Below are the current results of the attempts to reproduce.

In the meantime, here is the code and amplify config used during testing.
I highly encourage anyone to use this code, check out this Google OAuth test project from github: https://github.com/chrisbonifacio/amplify-issues/tree/main/5921-oauth-google,
or start up a fresh project and take those steps to reproduce the issue and share as many details as you can about how you got there or share the code.

Some follow up questions: 

- what other packages are you using alongside `@aws-amplify@3.2.8`?
- does this occur in both a dev and prod environment for you?

package.json

```js
{
  "name": "5921-oauth-google",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/auth": "3.2.8",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

aws-exports.js
```js
const awsmobile = {
    "aws_project_region": "XXXXX",
    "aws_cognito_identity_pool_id": "XXXXX",
    "aws_cognito_region": "XXXXX",
    "aws_user_pools_id": "XXXXX",
    "aws_user_pools_web_client_id": "XXXXX",
    "oauth": {
        "domain": "XXXXX.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
```

App.js
```js
import React, { useMemo } from "react";
import Amplify, { Auth } from "@aws-amplify/auth";
import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);

const App = () => {
  const initialState = useMemo(() => ({ user: null, customState: null }), []);
  const [state, setState] = React.useState(initialState);

  const handleSignIn = async () => {
    await Auth.federatedSignIn({ provider: "Google" });
  };

  const getUser = async () => {
    const user = await Auth.currentAuthenticatedUser();
    const userInfo = await Auth.currentUserInfo();
    const session = await Auth.currentSession();
    console.log({ session, user, userInfo });
    setState((prev) => ({ ...prev, user }));
  };

  React.useEffect(() => {
    getUser();
  }, []);

  const { user } = state;

  return (
    <div className="App">
      <button onClick={handleSignIn}>Open Google</button>
      <button onClick={getUser}>Get Current Session</button>
      <button onClick={() => Auth.federatedSignIn()}>Open Hosted UI</button>
      <button onClick={() => Auth.signOut()}>
        Sign Out {user?.getUsername()}
      </button>
    </div>
  );
};

export default App;

```

Results:

<img width="648" alt="Screen Shot 2021-04-30 at 6 10 51 PM" src="https://user-images.githubusercontent.com/16952986/116759070-69a2a500-a9df-11eb-8aac-f739e1f7ce4b.png">
<img width="1357" alt="Screen Shot 2021-04-30 at 6 12 40 PM" src="https://user-images.githubusercontent.com/16952986/116759145-a9698c80-a9df-11eb-988c-d44ce83ae226.png">

**Comment by menendezjaume** [comment] 2021-05-26 16:49
Hi there,

I was having the same problem and bumped into this thread. I was initially using "aws-amplify": "^4.0.2" fwiw.

I have tested your code (which btw is not the same the one from your comment than from your repo) and I still face the same issue:

<img width="1424" alt="Screenshot 2021-05-26 at 18 45 54" src="https://user-images.githubusercontent.com/15260858/119699635-a8970f80-be52-11eb-8860-ea6d854df636.png">

So I suspect the problem is not the library, but my cognito config.

In my aws-exports the oauth scopes are:

```
scope: ['email', 'openid', 'profile']
```

And, in case it helps, my Cognito client is configure as follows:

```tf
esource "aws_cognito_user_pool_client" "client" {
  name         = "demo_app"
  user_pool_id = aws_cognito_user_pool.pool.id

  allowed_oauth_flows = [
    "code",
  ]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes = [
    "email",
    "openid",
    "profile",
  ]
  callback_urls = local.callback_urls
  logout_urls   = local.logout_urls
  explicit_auth_flows = [
    "ALLOW_REFRESH_TOKEN_AUTH",
    "ALLOW_USER_SRP_AUTH",
  ]
  prevent_user_existence_errors = "ENABLED"
  read_attributes = [
    "address",
    "birthdate",
    "email",
    "email_verified",
    "family_name",
    "gender",
    "given_name",
    "locale",
    "middle_name",
    "name",
    "nickname",
    "phone_number",
    "phone_number_verified",
    "picture",
    "preferred_username",
    "profile",
    "updated_at",
    "website",
    "zoneinfo",
  ]
  supported_identity_providers = [
    "Google",
    "COGNITO",
  ]
  write_attributes = [
    "address",
    "birthdate",
    "email",
    "family_name",
    "gender",
    "given_name",
    "locale",
    "middle_name",
    "name",
    "nickname",
    "phone_number",
    "picture",
    "preferred_username",
    "profile",
    "updated_at",
    "website",
    "zoneinfo",
  ]
  access_token_validity  = 60
  id_token_validity      = 60
  refresh_token_validity = 30
  token_validity_units {
    access_token  = "minutes"
    id_token      = "minutes"
    refresh_token = "days"
  }
}
```

Interestingly enough, if I log in with a user that uses username and password, I can fetch the attributes. If I log in with a user that uses Google SSO, I can't.

Any ideas as to what's wrong in my cognito client? Thanks!

**Comment by menendezjaume** [comment] 2021-05-27 14:47
Small nit:

I have re-tried the whole thing and I've got two users (one using google SSO and one using email and password); and here are the results of some tests I've just made:

- Authenticating with email and password using **Auth.signIn(email, password)** returns a token that **works perfectly** and is capable of retrieving all user attributes.
- Authenticating with email and password using the **hosted UI** returns a token that gives me a **400** when attempting to retrieve the user attributes.
- Authenticating with **Auth.federatedSignIn({provider: 'Google'}) or the hosted UI using and using Google SSO** returns a token that gives me a **400** when attempting to retrieve the user attributes.

**Comment by menendezjaume** [comment] 2021-05-27 15:37
Last update from me:

I have been testing Allowed OAuth Scopes and I fixed my problem:
For some reason, the hosted UI for both email and password and SSO, as well as the `Auth.federatedSignIn({provider: 'Google'})` call require the `aws.cognito.signin.user.admin` scope to be enabled to fetch and update user attributed. However, a call to `Auth.signIn(email, password)` does not. I don't fully understand why though, as the [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html) doesn't seem to mention this.

**Comment by DeniferSantiago** [comment] 2021-05-27 15:48
I will leave here the solution I found to this problem: https://github.com/aws-amplify/amplify-js/issues/6444#issuecomment-841614409

**Comment by chrisbonifacio** [comment] 2021-05-27 19:42
@menendezjaume hmm, I did have the `aws.cognito.signin.user.admin` in my scopes but I didn't have to enter that manually, I believe it was generated by the CLI when I went through the auth setup and went down the OAuth route 🤔 

I will reach out to the team with this issue and update the docs to reflect this. Thank you for pointing that out!

**Comment by chrisbonifacio** [comment] 2021-05-27 19:51
Otherwise, closing this out as we have a working solution in the necessary step of making sure the `aws.cognito.signin.user.admin` scope is included, in addition to not having heard back from the original poster.

If you try the above and it still does not work for you, please open a separate issue with your particular auth configuration so we can better find the cause of the issue in your case. Thank you!

**Closed by chrisbonifacio** 2021-05-27 19:51 UTC
Labels: Auth, Can't reproduce, OAuth, needs-discussion
