### ISSUE TITLE
Credentials are not refreshed once expired

### ISSUE THREAD

**Issue by escar** [aws-amplify/amplify-js#4850] opened 2020-02-05 14:58 UTC
`(...) Amplify automatically signs requests with short term credentials from a Cognito Identity Pool which automatically expire, rotate, and refresh by the Amplify client libraries.(...)` - [amplify js docs](https://aws-amplify.github.io/docs/js/authentication)

After 1 hour, the default AWS credentials duration, we start getting 403's.
This is a single page app.. once we refresh the browser and Amplify is configured again, requests start working again.

This is the configuration:

```
Amplify.configure({
    Auth: {
        identityPoolId: identityPoolId,
        userPoolWebClientId: userPoolWebClientId,
        userPoolId: userPoolId,
        region: region,
        oauth: {
            redirectSignIn: redirectSignIn,
            redirectSignOut: redirectSignOut,
            domain: domain,
            scope: ['profile', 'openid'],
            responseType: 'code',
        },
    },
    API: {
        endpoints: [
            {
                name: 'api',
                endpoint: endpoint,
                region: region,
            },
        ],
    },
    correctClockSkew: true,
});
```
and a sample request:

```
let options = {
    response: false,
    queryStringParameters: data,
};
const response = await API.get('api', 'mydata', options);
```

Does it make sense to execute `Auth.currentSession()` every time before a request, so the credentials are updated if needed?

**Comment by WGriffing** [comment] 2020-04-22 14:33
I'm having the same problem in my application. At the moment, I'm leaning towards using a timeout to update the token every 3599 seconds. I was curious if you solved your issue.

**Comment by escar** [comment] 2020-04-22 14:35
Not really, we're actually refreshing the token manually too...

**Comment by elorzafe** [comment] 2020-07-03 04:45
@escar I just tried with Amplify latest version and it works after one hour.

It refreshed the token and got new credentials.

Is this for signed in users or also unauthenticated users?

The code snippet I tried was this. I tried with an authenticated user and I federated using Cognito Hosted UI with Google login.

```jsx
import React, { useEffect, useState } from "react";
import Amplify, { Auth, Hub, API } from "aws-amplify";
import { Credentials } from '@aws-amplify/core';
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);

function App() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    // @ts-ignore
    Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
        case "cognitoHostedUI":
          // @ts-ignore
          getUser().then((userData) => setUser(userData));
          break;
        case "signOut":
          setUser(null);
          break;
        case "signIn_failure":
        case "cognitoHostedUI_failure":
          console.log("Sign in failure", data);
          break;
      }
    });

    // @ts-ignore
    getUser().then((userData) => setUser(userData));
  }, []);

  function getUser() {
    return (
      Auth.currentAuthenticatedUser()
        // @ts-ignore
        .then((userData) => userData)
        .catch(() => console.log("Not signed in"))
    );
  }

  return (
    <div>
      <p>User: {user ? JSON.stringify(user) : "None"}</p>
      {user ? (
        <div>
          <button onClick={() => Auth.signOut()}>Sign Out</button>
          <button onClick={() => Auth.currentSession().then(console.log).catch(console.warn)}>Current user</button>
          <button onClick={() => Credentials.get().then(console.log).catch(console.warn)}>Current credentials</button>
          <button onClick={() => API.get("xxxxxx","/items", {}).then(console.log).catch(console.warn)}>Call API</button>
        </div>
      ) : (
        <button onClick={() => Auth.federatedSignIn()}>
          Federated Sign In
        </button>
      )}
    </div>
  );
}

export default App;
```

This is my `aws-exports.js` file

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:xxxxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxx",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxx",
    "oauth": {
        "domain": "xxxxxxxxxx-xxxxxxxx-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "xxxxxx",
            "endpoint": "https://xxxxxxx.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;

```

**Comment by sammartinez** [comment] 2020-11-11 23:33
As we are unable to reproduce this issue, we are resolving this as there has been no follow up after the above callout. Please let us know if you are still experiencing this issue. Thanks ahead of time.

**Closed by sammartinez** 2020-11-11 23:33 UTC
Labels: Auth, Can't reproduce

**Comment by shouze** [comment] 2020-11-12 00:07
@sammartinez I confirm that we experiment this issue too.
BTW we only use `@aws-amplify/auth` (version 3.4.7). We have mainly implemented 2 functions. `getUserDetails` is involved into a useEffect react hook where we rely on `isAuthenticated`.

```ts
import AmplifyAuth, { CognitoUser } from "@aws-amplify/auth";

  public async isAuthenticated(): Promise<boolean> {
    try {
      const currentSession = await AmplifyAuth.currentSession();
      if (!currentSession) {
        return false;
      }

      return true;
    } catch {
      return false;
    }
  }

  public async getUserDetails(): Promise<UserDetails> {
    let currentCognitoUser = this.currentCognitoUser;

    if (!currentCognitoUser) {
      currentCognitoUser = await AmplifyAuth.currentAuthenticatedUser();
      this.currentCognitoUser = currentCognitoUser;
    }

    if (!currentCognitoUser) {
      throw new Error("No user authenticated.");
    }

    const userAttributes = await AmplifyAuth.userAttributes(currentCognitoUser);

    const userAttributesMap = new Map();
    userAttributes.map((oneAttributeObject) =>
      userAttributesMap.set(
        oneAttributeObject.getName(),
        oneAttributeObject.getValue(),
      ),
    );

    return {
      userIdJwtToken: this.extractUserIdJwtToken(currentCognitoUser),
      email: userAttributesMap.get("email"),
      phoneNumber: userAttributesMap.get("phone_number"),
      fullName: userAttributesMap.get("name"),
      firstName: userAttributesMap.get("given_name"),
      lastName: userAttributesMap.get("family_name"),
    };
  }
```
