### ISSUE TITLE
Amplify auth signIn throws Cors error on Microsoft Edge

### ISSUE THREAD

**Issue by SidneyNiccolson** [aws-amplify/amplify-js#4346] opened 2019-11-05 16:36 UTC
**Describe the bug**
On Microsoft edge version v42.x to 44.x with Amplify v1.1.38 I seem to get the following error:

"The origin 'https://mydomain.com' used the maximum Access-Control-Max-Age value of '172800' as the provided value exceeded this for a cross-origin request to 'https://cognito-identity.eu-west-2.amazonaws.com/'."

The log-in afterwards seem to work, however with a latency of a few seconds. 

I was unable to reproduce this issue on the following browsers: Chrome (78.0.3904.87), Firefox (70.0.1), Safari v12 and Edge Beta. On these browsers the log-in functionality seem to be working fine.

**Expected behavior**
A clean login without latency.  This issue propagates to currentAuthenticatedUser.

**Sample code**

      await Auth.signIn(username, password).then(user => {
        if (user.challengeName === 'NEW_PASSWORD_REQUIRED') {
          // const { requiredAttributes } = user.challengeParam; // the array of required attributes, e.g ['email', 'phone_number']
          Auth.completeNewPassword(
            user,               // the Cognito User Object
            password,       // the new password
          ).then(user => {
            // at this time the user is logged in if no MFA required
            console.log("successfully logged in Cognito, with a new password.");
          }).catch(e => {
            console.log(e);
          });
        } else {
          // other situations
          console.log("successfully logged in Cognito.")
        }
      }).catch(e => {
        console.log(e);
      });
...

**Comment by SidneyNiccolson** [comment] 2019-11-06 14:09
I looked further in the OPTIONS request and response headers that throws the error. It seems that the request header doesn't send an access-control-max-age in which the cognito-idp does send an access-control-max-age of '172800'.

Moreover I'm using Nginx for my app. Additionally I tried using the Authenticator component, but this gives the same results.

**Comment by schimini** [comment] 2019-11-18 14:08
I think you can change the title back. It happens in angular too

**Comment by ericclemmons** [comment] 2019-12-30 23:25
@SidneyNiccolson @schimini Thanks for helping to narrow this down to Auth.

I was able to reproduce this bug using Edge (Stable):

- With a clear cache, my local app performs a call to `Auth.currentAuthenticatedUser()` on load.  During the series of calls, eventually the error comes back.
- On subsequent loads, calling `Auth.signIn('username', 'password').then(console.log).catch(console.error)` will cause the `OPTIONS` call to take place, triggering the unresponsive UI + warnings:

> <img width="1267" alt="Screen Shot 2019-12-30 at 2 53 10 PM" src="https://user-images.githubusercontent.com/15182/71603955-319e0000-2b14-11ea-8e55-292f2e7bd98f.png">

It does **not** occur in Edge Beta, as I believe that's when the rendering engine moved to Chromium:
> <img width="1278" alt="Screen Shot 2019-12-30 at 2 46 22 PM" src="https://user-images.githubusercontent.com/15182/71603990-601bdb00-2b14-11ea-9787-2ba6cc3ddf78.png">

This is a response header from the call to Cognito, so we may need to engage service teams for this, as this doesn't seem specific to Amplify, but Cognito:
> <img width="1258" alt="Screen Shot 2019-12-30 at 3 10 06 PM" src="https://user-images.githubusercontent.com/15182/71604438-d4f01480-2b16-11ea-864c-6ee8d8abfa43.png">

It's important to note that, at least in my testing, **the UI became unresponsive for several seconds despite the network timings indicating the request was much faster**:

> ![172800](https://user-images.githubusercontent.com/15182/71604669-7330aa00-2b18-11ea-9e53-091b92cca1cf.gif)

**Comment by ericclemmons** [comment] 2019-12-30 23:30
It's worth noting that several browsers have limitations on how long this request can be:
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age

**It's very likely that the value is too high, and Edge is warning/hanging was a result**.

There's a great article on the topic to attempt to avoid the preflight call entirely:
> https://m.alphasights.com/killing-cors-preflight-requests-on-a-react-spa-1f9b04aa5730

**Comment by ericclemmons** [comment] 2020-01-22 22:29
@SidneyNiccolson We're tracking this internally with the Cognito team. (Internal link for other maintainers: https://t.corp.amazon.com/P32497337)

Unfortunately, this is external to the Amplify JS library so there isn't any immediate action we can take as part of this project.

Thanks for bringing this to our attention, and we'll work with Cognito to get this important issue resolved!

**Comment by schimini** [comment] 2020-01-27 10:45
Will there be an external follow link for us to know when the issue is solved?

**Comment by ericclemmons** [comment] 2020-01-27 18:01
Not publicly, so I'm going to re-open this issue so we have can keep it tracked until resolution. 👍 

@schimini @SidneyNiccolson If this is affecting your _production_ application or preventing launching your project, we can get this escalated.  Let us know if that's the case!

**Comment by schimini** [comment] 2020-01-27 18:06
Tbh we haven't tested in edge for a while ( we have been kindly ignoring it because we've observed that only a few of our users use edge) but we had the issue in a production application that's still running.  
Nonetheless we look forward to see it solved. Thanks for re-opening the issue and for your amazing support on it.

**Comment by SidneyNiccolson** [comment] 2020-01-27 18:39
Same here. It is not breaking our application, although it is nice to keep track on any updates on this.

**Comment by atlowell-smpl** [comment] 2020-04-01 17:28
We are having this issue on Edge 44 Angular 8. Our Auth requests seem to hang until the edge console displays the error message:

"The origin 'http://localhost:4200' used the maximum Access-Control-Max-Age value of '172800' as the provided value exceeded this for a cross-origin request to 'https://cognito-idp.us-east-2.amazonaws.com/'."

At this point, the app fails to authenticate, preventing further use of the app.

This is affecting our production build, and seeing how it has been 5 months since it was reported, it would be lovely if it could be escalated.

**Comment by greimela** [comment] 2020-04-22 07:12
We noticed that as well.

After upgrading amplify from 2.x to 3.x the pre-Chromium Edge is not able to authenticate using Cognito.
Which means that our app is no longer usable by Edge users...

**Comment by ericclemmons** [comment] 2020-04-22 17:03
@greimela You experienced this issue _after_ upgrading Amplify and not before?  I was able to reproduce this in 2.x (https://github.com/aws-amplify/amplify-js/issues/4346#issuecomment-569825588), but if there was something in 2.x that was working & reproducible, I'd like to investigate it!

**Comment by greimela** [comment] 2020-04-23 07:48
@ericclemmons I looked into it again. The CORS warning was also present in 2.x.

However, after the upgrade to 3.x the pre-Chromium Edge is no longer able to authenticate. 
Downgrading to 2.x fixes this issue.

But it seems like it is not related to this issue here.
I will open a separate issue.

**Comment by WojtekSienczylo** [comment] 2020-04-28 15:31
Same issue here.
Aws-amplify version 3.0.8 stopped to authenticate users on Edge v 44.18362.449.0.
We're using Cognito federated sign in with Azure AD provider.

**Comment by rafaelaudy** [comment] 2020-04-29 08:45
Yes, we have the same issue with an app that we [just launched.](https://communities.localheroes.com/)
Sorry to bother you, but would it be possible to escalate this issue @ericclemmons?
Edge represents around 7% of our users.

**Comment by ericclemmons** [comment] 2020-04-30 17:44
@rafaelaudy I'm on it! I've escalated with Cognito yesterday and we're working through timelines for fixes.

**Comment by seankovacs** [comment] 2020-05-26 17:25
I had similar CORS issues that prevented the authentication routines from working. After I updated to the latest amplify library they went away; works now.

**Comment by BruceWheaton** [comment] 2020-05-26 18:03
Updated with npm and then amplify auth update? That’s good news.

**Comment by seankovacs** [comment] 2020-05-26 19:54
Yeah I was on version 3.1.9 - updasted to 3.1.11 and my CORS issues went away on Edge.

**Comment by ericclemmons** [comment] 2020-05-27 17:30
@seankovacs Can you share your `package.json` so I can compare which versions you're referencing? (`aws-amplify`'s latest version is `3.0.13`, so which package was updated from `3.1.9` to `3.1.11`?)

**Comment by seankovacs** [comment] 2020-05-27 17:51
Ah - you got me. I was looking at the analytics package - apologies. This is in my package.json: "aws-amplify": "^3.0.4". 
Looking at the lock file, I was on 3.0.10 and upgraded to 3.0.12 to solve my issue. There are tons of dependency packages that updated as well (such as amazon-cognito-idenity-js 4.2.3->4.3.0) that could have been what actually fixed the problem.

**Comment by BruceWheaton** [comment] 2020-05-27 22:38
As of this afternoon, the latest is 3.0.13. Updating to that is causing me problems (did update and then push) with the configuration object. Going back to 3.0.12 functions, but the CORS error still shows up.

**Comment by ericclemmons** [comment] 2020-05-28 18:11
@BruceWheaton Correct, it's a warning based on a response header from Cognito **but the delay is unrelated**.  Are you saying that you experience the delay with `aws-amplify@3.0.13`, but not `aws-amplify@3.0.12`?

**Comment by BruceWheaton** [comment] 2020-05-28 23:45
3.013 didn't work for me so I went back - something about missing configuration. I tried update auth but didn't really want to make a new project. The clue wasn't great, sorry.
Not sure what you mean about 'delay' - I get a CORS warning on edge but not an error now. Sorry - not going too much further, my React app on edge is a bomb site so I'm putting that on the backlog.

**Comment by rgilbert90** [comment] 2020-06-02 04:37
I was on `aws-amplify@3.0.11` before, and I could authenticate, but the API failed to fetch. I just updated to `aws-amplify@3.0.13` and that seemed to fix the Cognito auth issue. There is a significant delay when logging in, however. It can take up to 30s, but the rest of our app is working as expected now.

**Comment by sammartinez** [comment] 2020-10-01 15:28
Resolving as this issue based on above feedback that this was fixed in later versions of our repository. Please let us know if this issue is still present and we can dive deep.

**Closed by sammartinez** 2020-10-01 15:28 UTC
Labels: Browser Compatibly, Cognito, bug
