### ISSUE TITLE
DataStore not syncing unless all fields populated

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#7514] opened 2021-01-07 00:01 UTC
**Describe the bug**

Trying to get DataStore syncing with DynamoDB. One of the features of GraphQL and DynamoDB is that I can pick and choose what attributes to add/retrieve to a record. However, what we are seeing is that unless we have every field in the schema populated that it will not sync to DynamoDB and gives errors like "field is string type and finding the value undefined" unless every field is populated.

**To Reproduce**

Create a record without defining every possible record in the schema and it will not sync

**Expected behavior**

Should be able to create a record with only the mandatory fields and have it sync

**Comment by nubpro** [comment] 2021-01-07 04:50
Could you please provide your schema.graphql?

**Comment by sacrampton** [comment] 2021-01-07 10:04
Got some more on this. The issue is occurring with associations like this...
```
"association": {
    "connectionType": "BELONGS_TO",
   "targetName": "brandProductDivisionId"
 }``
```

In models where there is no association everything is working fine.

**Comment by amhinson** [comment] 2021-01-07 17:36
As @nubpro mentioned, could you share your `schema.graphql`? We just need a clear way to attempt to reproduce the issue that you are seeing.

**Comment by sacrampton** [comment] 2021-01-07 20:55
I can't give you the entire schema.graphql - but can provide models that work and don't work.

Here is the Photo model fails and the Bom model works

Also, I had to get rid of the @auth for it to work in any way - seems auth needs to be done in resolvers rather than in the model

```
type Photo
  @model
  @key (name: "gsi-PhotoImageName", fields: ["imageName"], queryField: "PhotoImageName")
  @key (name: "gsi-PhotoAssetVisitQueue", fields: ["assetVisitQueue"], queryField: "PhotoAssetVisitQueue")  
  @searchable 
#  @auth(rules: [
#      {allow: groups, groups: ["XXXXXX"], operations: [create,update,delete,read]},
#      {allow: groups, groups: ["CLIENTADMIN","CLIENT"], operations: [create,update,read]},      
 #     {allow: groups, groups: ["CROWD","CLIENTVIEWER","APPVIEWER"], operations: [read]}
  #  ])
{
  id: ID
  asset: Asset @connection (name: "AssetPhoto", sortField: "assetName")
  assetName: String #derived from asset
  assetStatus: String #derived from asset
  photoAssetId: ID!
  assetVisit: AssetVisit @connection (name: "AssetVisitPhoto") #default is most recent for current asset
  photoAssetVisitId: ID
  photoButton: PhotoButton @connection
  photoPhotoButtonId: ID!
  operatingUnit: OperatingUnit @connection (name: "OperatingUnitPhoto", sortField: "assetName") #derived from asset
  operatingUnitName: String #derived from operatingUnit
  photoOperatingUnitId: ID!
  package: Package @connection (name: "PackagePhoto", sortField: "assetName") #derived from asset
  packageName: String #derived from package
  photoPackageId: ID
  plant: Plant @connection (name: "PlantPhoto", sortField: "assetName" )#derived from asset
  plantName: String #derived from plant
  photoPlantId: ID!
  aiRawResult: AWSURL
  altitude: Float
  archived: Boolean #default = false
  assetVisitQueue: Int
  auditNotes: String
  customLabel1: String
  customLabel1LeftRatio: Float
  customLabel1TopRatio: Float
  customLabel1WidthRatio: Float
  customLabel1HeightRatio: Float
  customLabel1LeftPixels: Int
  customLabel1TopPixels: Int
  customLabel1WidthPixels: Int
  customLabel1HeightPixels: Int
  customLabel1Confidence: Float
  customLabel1Verified: Boolean
  customLabel2: String
  customLabel2LeftRatio: Float
  customLabel2TopRatio: Float
  customLabel2WidthRatio: Float
  customLabel2HeightRatio: Float
  customLabel2LeftPixels: Int
  customLabel2TopPixels: Int
  customLabel2WidthPixels: Int
  customLabel2HeightPixels: Int
  customLabel2Confidence: Float
  customLabel2Verified: Boolean
  customLabel3: String
  customLabel3LeftRatio: Float
  customLabel3TopRatio: Float
  customLabel3WidthRatio: Float
  customLabel3HeightRatio: Float
  customLabel3LeftPixels: Int
  customLabel3TopPixels: Int
  customLabel3WidthPixels: Int
  customLabel3HeightPixels: Int
  customLabel3Confidence: Float
  customLabel3Verified: Boolean
  customLabel4: String
  customLabel4LeftRatio: Float
  customLabel4TopRatio: Float
  customLabel4WidthRatio: Float
  customLabel4HeightRatio: Float
  customLabel4LeftPixels: Int
  customLabel4TopPixels: Int
  customLabel4WidthPixels: Int
  customLabel4HeightPixels: Int
  customLabel4Confidence: Float
  customLabel4Verified: Boolean
  imageWidth: Int
  imageHeight: Int
  imageOrientation: Int
  isDeleted: Boolean
  damagedPhoto: Boolean
  deviceUuid: String
  dzi: AWSURL
  fileName: String #original file name excluding extension
  fileSize: Int #in bytes
  geolocation: Geolocation
  imageName: String
  latestProcessingCycle: AWSDate
  longRekognitionResult: Boolean
  mapZoom: Int #default is 18
  photograph: AWSURL!
  photographTaken: AWSDateTime
  photoStatus: String
  photoType: String
  photoTypeMl: String
  photoTypeMlConfidence: Float
  rekognition: Boolean
  rekognitionResult: String
  rekognitionResultLine: String
  representative: Boolean
  staticMap: AWSURL
  thumbnail: AWSURL
  validatedDzi: Boolean
  validatedFile: Boolean
  validatedThumbnail: Boolean
  sfdc: Sfdc
  potentialResult: [PotentialResult] @connection (name: "PhotoPotentialResult")  
  created: AWSDateTime
  createdBy: String
  createdByIP : [String]
  createdById : ID
  lastModified : AWSDateTime
  lastModifiedBy : String
  lastModifiedByIP : [String]
  lastModifiedById : ID
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!  
}
```


```
type Bom
  @model
  @searchable 
#  @auth(rules: [
#      {allow: groups, groups: ["XXXXXX","CLIENTADMIN"], operations: [create, update, delete,read]},
#      {allow: groups, groups: ["CLIENT"], operations: [create, update,read]},
#      {allow: groups, groups: ["CLIENTVIEWER"], operations: [read]}    
 #   ])
{
  id: ID
  isDeleted: Boolean
  name: String
  longDescription: String
  shortDescription: String
  m2MConnection: [M2MConnection] @connection (name: "BomM2MConnection")
  created: AWSDateTime
  createdBy: String
  createdByIP : [String]
  createdById : ID
  lastModified : AWSDateTime
  lastModifiedBy : String
  lastModifiedByIP : [String]
  lastModifiedById : ID   
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!   
}  
```

**Comment by amhinson** [comment] 2021-01-08 17:31
Hmm that does sound like strange behavior @sacrampton! With DataStore, you should only need to pass in the required fields. I've got a few questions/comments:
- Did you use the Amplify CLI to create and manage your backend resources and/or AppSync Resolvers?
- Could you provide some code samples of your Amplify usage? This use-case seems relatively complex, so I just want to make sure we are understanding your issue completely.
- On that note ^ have you tried to reproduce this issue with a brand new Amplify app created with the CLI? If so, that would help us tremendously if you could share a functioning sample repo so we can reproduce the issue on our side. 
- The `@searchable` directive currently [isn't compatible](https://docs.amplify.aws/cli/graphql-transformer/searchable#known-limitations) with DataStore. I don't necessarily think this is causing the issue you are seeing, but it is worth experimenting with the behavior without it.

**Comment by sacrampton** [comment] 2021-01-10 22:53
Hi @amhinson - please see my comments below:

- Yes the Amplify CLI is used to manage backend resources
- I'll work on a getting this reproducible with a brand new Amplify App created from the Amplify CLI
- It is of course a major limitation that Searchable is not supported - however, working through issues like #4228 we have got it working with searchable. I also don't believe this issue is the problem.

**Comment by sacrampton** [comment] 2021-01-11 09:06
This sample app is created based on the datastore example (https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#prerequisites).

```
type Message @model{
  id: ID!
  title: String!
  color: String
  createdAt: String
  user: User @connection (name: "UserMessage")
}


type User @model{
  id: ID!
  name: String!
  createdAt: String
  messages: [Message] @connection (name: "UserMessage")
}
```

Now with the example app and the modified schema you see the error that is generated.

This is therefore reproducible.

![Example](https://user-images.githubusercontent.com/6362888/104162208-47911100-5448-11eb-827d-aa480d4b006e.png)

**Comment by amhinson** [comment] 2021-01-11 16:37
Thanks for looking deeper into that! Would you be able to share that sample repo? I mainly just want to see how you're interacting with DataStore from the app to make sure we are trying to reproduce the issue in the same way.

Also, one thing to note from the schema you provided is that `createdAt` is a field that is [automatically added by AppSync](https://docs.amplify.aws/cli/graphql-transformer/model#usage) when using the `@model` directive. If this field needs to be part of a mutation, it should have the type `AWSDateTime!` and be required.

**Comment by sacrampton** [comment] 2021-01-11 19:28
Hi @amhinson,

This example is simply the one from the AWS DataStore documentation verbatim. I know that createAt is created automatically, but it was defined separately in the example so I just copied it verbatim to get a working example EXACTLY as per the example shown in this video.

https://www.youtube.com/watch?v=wH-UnQy1ltM&feature=youtu.be

The code for the app is in this repo.
https://gist.github.com/dabit3/f4467e759325ea4b3d007b7117436031

We just updated DataStore version from ^2.2.8  to latest (^2.9.3) then the error changed a bit (see picture).

![Example2](https://user-images.githubusercontent.com/6362888/104228492-0d9f2980-549f-11eb-97ab-c6dbe0a0fb8b.png)

**Comment by amhinson** [comment] 2021-01-11 20:59
Ah ok. This seems to be due to how the `@connection` directive is being used here for the relationships. Depending on how you want your data models to work for the sample, you would likely need to it to either a [has one](https://docs.amplify.aws/cli/graphql-transformer/connection#has-one) or [has many](https://docs.amplify.aws/cli/graphql-transformer/connection#has-many).

Note that the `name` argument is now [deprecated](https://docs.amplify.aws/cli/graphql-transformer/connection#alternative-definition), whereas the current recommendation is to use `@connection` and `@key` along with `keyName` (if needed) as described [here](https://docs.amplify.aws/cli/graphql-transformer/connection).

For the sample, you could change your schema to something like one of these to get it to work or you could also combine the two if you want, depending on your use-case:
```graphql
# has many
type Message @model @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  userID: ID!
  title: String!
  color: String
}

type User @model {
  id: ID!
  name: String!
  messages: [Message] @connection(keyName: "byUser", fields: ["id"])
}

``` 
```graphql
# has one
type Message @model {
  id: ID!
  title: String!
  color: String
  user: User @connection
}

type User @model {
  id: ID!
  name: String!
}
```

**Comment by sacrampton** [comment] 2021-01-12 02:21
Thanks for this - I made the change as you suggested and it indeed worked.

Sadly its now going to take me days to make the changes into my database given I'll have to do a push to remove existing GSI and push again to add key GSI given limitations around GSI's:-( ... But at least I know what to do now :-)

**Comment by nubpro** [comment] 2021-01-12 05:21
> Thanks for this - I made the change as you suggested and it indeed worked.
> 
> Sadly its now going to take me days to make the changes into my database given I'll have to do a push to remove existing GSI and push again to add key GSI given limitations around GSI's:-( ... But at least I know what to do now :-)

You can enable "enableIterativeGsiUpdates" for you dev environment.
https://docs.amplify.aws/cli/reference/feature-flags#enableIterativeGsiUpdates

**Comment by amhinson** [comment] 2021-01-12 17:27
@sacrampton I'm glad that worked out for you! And I would also recommend the suggestion above regarding `enableIterativeGsiUpdates`. 

Closing, as this appears to be resolved.

**Closed by amhinson** 2021-01-12 17:27 UTC
Labels: DataStore, to-be-reproduced

**Comment by sacrampton** [comment] 2021-01-13 12:42
@amhinson  / @nubpro 

Thanks for your suggestion - I rebuilt my schema (took better part of the day - its big).

I do it in 2 parts - first step to compile and it does so successfully.

$ amplify api gql-compile --minify

Next step is the push

$ amplify push --no-gql-override --yes


Unfortunately it fails with the following error

✖ An error occurred when pushing the resources to the cloud

Rate exceeded
An error occurred during the push operation: Rate exceeded

**Comment by amhinson** [comment] 2021-01-13 22:38
Ah sorry for the trouble! I'd suggest creating an issue on the [CLI repo](https://github.com/aws-amplify/amplify-cli).
