### ISSUE TITLE
Auth with react native not working anymore, An unknown error has ocurred.

### ISSUE THREAD

**Issue by aleguern** [aws-amplify/amplify-js#12628] opened 2023-11-24 15:54 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
 System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - ~/homebrew/bin/node
    Yarn: 1.22.19 - ~/homebrew/bin/yarn
    npm: 9.6.7 - ~/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 17.1
  npmPackages:
    @aws-amplify/react-native: ^1.0.5 => 1.0.5 
    @aws-amplify/rtn-web-browser: 1.0.3 => 1.0.3 
    @aws-amplify/ui-react-native: ^2.0.3 => 2.0.3 
    @babel/core: ^7.20.0 => 7.23.3 
    @expo-google-fonts/inter: ^0.2.3 => 0.2.3 
    @expo/ngrok: ^4.1.3 => 4.1.3 
    @expo/vector-icons: ^13.0.0 => 13.0.0 
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2 
    @react-native-community/netinfo: 9.3.10 => 9.3.10 
    @react-navigation/native: ^6.0.2 => 6.1.9 
    @types/react: ~18.2.14 => 18.2.37 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.7 => 6.3.7 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^6.0.5 => 6.0.5 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    clsx: ^2.0.0 => 2.0.0 
    expo: ~49.0.15 => 49.0.19 
    expo-auth-session: ~5.0.2 => 5.0.2 
    expo-font: ~11.4.0 => 11.4.0 
    expo-image-picker: ~14.3.2 => 14.3.2 
    expo-linking: ~5.0.2 => 5.0.2 
    expo-router: ^2.0.0 => 2.0.13 
    expo-splash-screen: ~0.20.5 => 0.20.5 
    expo-status-bar: ~1.6.0 => 1.6.0 
    expo-system-ui: ~2.4.0 => 2.4.0 
    expo-updates: ~0.18.17 => 0.18.17 
    expo-web-browser: ~12.3.2 => 12.3.2 
    jest: ^29.2.1 => 29.7.0 
    jest-expo: ~49.0.0 => 49.0.0 
    nativewind: ^2.0.11 => 2.0.11 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.72.6 => 0.72.6 
    react-native-gesture-handler: ~2.12.0 => 2.12.1 
    react-native-get-random-values: ~1.9.0 => 1.9.0 
    react-native-safe-area-context: 4.6.3 => 4.6.3 
    react-native-screens: ~3.22.0 => 3.22.1 
    react-native-web: ~0.19.6 => 0.19.9 
    react-test-renderer: 18.2.0 => 18.2.0 
    tailwindcss: 3.3.2 => 3.3.2 
    typescript: ^5.1.3 => 5.2.2 
  npmGlobalPackages:
    @expo/ngrok: 4.1.3
    auth0-deploy-cli: 7.17.7
    eas-cli: 5.9.1
    gatsby: 5.12.5
    npm-check-updates: 16.14.6
    npm: 9.6.7


```

</details>

### Describe the bug

Using the signin method of amplify is not working anymore and throws `[Unknown: An unknown error has ocurred.]`

### Expected behavior

It should login the user

### Reproduction steps

1. Follow the steps from the tutorial 
2. Configure amplify 
3. the login does not work in react native but works in my web backoffice 

(4. I tried with the amplify UI as well and the same error occurs)

### Code Snippet

```javascript

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: '_',
      userPoolClientId: '_',
    },
  },
});

cognitoUserPoolsTokenProvider.setKeyValueStorage(defaultStorage);


export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  async function handleSignIn({ username, password }: SignInInput) {
    console.log(username, password);
    try {
      const { isSignedIn, nextStep } = await signIn({ username, password });
    } catch (error) {
      console.log('error signing in', error);
    }
  }

  return (
    <SafeAreaView>
      <View className='flex h-full w-full px-6 '>
        <View className='flex mt-4'>
          <Text className='text-3xl font-bold'>Se connecter</Text>
          <Text className='text-gray-600 mt-2 text-base'>
            Pour vous connecter, renseignez le mail et votre mot
            de passe.
          </Text>
        </View>
        <View className='w-full mt-4'>
          <Text className='text-gray-500 mb-1 text-base'>Email</Text>
          <TextInput
            className='lowercase w-full border border-gray-300 rounded p-2 placeholder:text-base'
            keyboardType='email-address'
            placeholder='test@test.com'
            onChange={(e) => setUsername(e.nativeEvent.text.toLowerCase())}
          />
        </View>
        <View className='w-full mt-4 mb-4'>
          <Text className='text-gray-500 mb-1 text-base'>Mot de passe</Text>
          <TextInput
            className='w-full border border-gray-300 rounded p-2 text-base placeholder:text-base'
            placeholder='Mot de passe'
            secureTextEntry={true}
            onChange={(e) => setPassword(e.nativeEvent.text)}
          />
        </View>

        {error && <Text className='text-red-500 text-sm mb-4'>{error}</Text>}

        <Button onPress={() => handleSignIn({ username, password })}>
          Se connecter
        </Button>
     
      </View>
    </SafeAreaView>

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: '_',
      userPoolClientId: '_',
    },
  },
});

### Mobile Device

iPhone15

**Comment by steve-calverley** [comment] 2023-11-24 21:05
@aleguern Try console logging the underlyingError (err.underlyingError) 
If set tokens cant be called due to undefined then look at the node_modules/@aws-amplify/auth/src/providers/cognito/tokenProvider/cacheTokens.ts an update the  import for tokenOrchestrator to import { tokenOrchestrator } from '../tokenProvider' 

I have this issue open that came from another similar issuer - https://github.com/aws-amplify/amplify-js/issues/12622

**Comment by aleguern** [comment] 2023-11-25 10:32
Hello @steve-calverley thank you for the secret underlying error ! 
I'm now getting the following output
```
[Error: The package '@aws-amplify/react-native' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo Go
]
```

Not quite sure what to do as I'm new to expo but I'll see what I can do.

**Comment by geekabhinavp** [comment] 2023-11-28 11:38
Any updates?

**Comment by aleguern** [comment] 2023-11-28 12:01
No it’s still not working

**Comment by nadetastic** [comment] 2023-11-28 15:47
Hi @aleguern to clarify, how are you launching the application?  are you using expo go or running on a real device etc?

**Comment by aleguern-azivko** [comment] 2023-11-28 15:53
Hey @nadetastic, I tried running with expo go or a real device but getting the same error.

**Comment by nadetastic** [comment] 2023-11-29 00:26
@aleguern thank you for clarifying. With V6 of `aws-amplify` Expo Go is unfortunately not supported. The recommendation is to run a build using `npx expo run:<android | ios>` instead. Could you give it a try and let me know if you still have issues?

- [Reference](https://docs.amplify.aws/react-native/start/getting-started/setup/)

**Comment by aleguern** [comment] 2023-11-29 10:45
I will test that, I’m curious as to why it won’t be supported anymore ? Is it permanent ?

**Comment by nadetastic** [comment] 2023-11-29 18:27
Sounds good @aleguern. The limitation is due to how Expo Go works - Specifically, Expo Go only uses [native modules built into the Expo SDK](https://docs.expo.dev/workflow/customizing/) and V6 now leverages native functionality that is not available in Expo SDK. The alternative is then to generate native projects with prebuild.

**Comment by geekabhinavp** [comment] 2023-11-30 02:10
Hi @nadetastic , I am still facing the same issue even after running the app via `npx expo run:ios`.

**Comment by nadetastic** [comment] 2023-11-30 16:01
@geekabhinavp can you share your package.json contents? I'd like to try and reproduce this.

**Comment by geekabhinavp** [comment] 2023-11-30 19:53
@nadetastic Here is the `package.json` file:
```
{
  "name": "brand",
  "version": "1.0.0",
  "main": "./index.js",
  "scripts": {
    "build": "expo export --platform all",
    "start": "expo start --dev-client",
    "start:android": "expo start --android",
    "start:ios": "expo start --ios",
    "lint": "eslint .",
    "test": "jest",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@aws-amplify/react-native": "^1.0.5",
    "@babel/plugin-proposal-private-methods": "^7.18.6",
    "@callstack/react-theme-provider": "^3.0.8",
    "@expo/vector-icons": "^13.0.0",
    "@hookform/resolvers": "^3.3.1",
    "@react-native-async-storage/async-storage": "^1.19.8",
    "@react-native-camera-roll/camera-roll": "^5.9.0",
    "@react-native-community/blur": "^4.3.2",
    "@react-native-community/netinfo": "^9.5.0",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/material-bottom-tabs": "^6.2.16",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "@reduxjs/toolkit": "^1.9.7",
    "@types/react-native": "~0.70.6",
    "aws-amplify": "^6.0.3",
    "expo": "~48.0.21",
    "expo-av": "^13.6.0",
    "expo-haptics": "~12.2.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-screen-orientation": "~5.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "^1.4.4",
    "expo-system-ui": "~2.2.1",
    "expo-web-browser": "~12.1.1",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.43.9",
    "react-native": "0.71.14",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-get-random-values": "^1.10.0",
    "react-native-international-phone-number": "0.5.3",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-modal": "^13.0.1",
    "react-native-paper": "^5.10.0",
    "react-native-pressable-opacity": "^1.0.10",
    "react-native-reanimated": "^2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-sensors": "^7.3.6",
    "react-native-static-safe-area-insets": "^2.2.0",
    "react-native-svg": "13.4.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-video": "^5.2.1",
    "react-native-vision-camera": "^2.15.2",
    "react-redux": "^8.1.3",
    "styled-components": "^5.3.10",
    "uuid": "^9.0.0",
    "yup": "^1.3.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.21.5",
    "@babel/core": "^7.21.4",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@babel/plugin-transform-flow-strip-types": "^7.22.5",
    "@babel/preset-env": "^7.21.5",
    "@babel/runtime": "^7.21.5",
    "@svgr/cli": "^8.1.0",
    "@types/react": "~18.0.33",
    "@types/react-native-vector-icons": "^6.4.14",
    "@types/react-native-video": "^5.0.15",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "babel-jest": "^29.5.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-preset-expo": "^9.3.2",
    "eslint": "^8.38.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-native": "^4.0.0",
    "prettier": "2.8.8",
    "typescript": "^4.9.5"
  },
  "private": true
}
```

**Comment by aleguern** [comment] 2023-12-01 12:50
I did nothing except for running with npx expo run:ios

**Comment by geekabhinavp** [comment] 2023-12-04 23:58
I tried to log the underlyingError, and got `[TypeError: Cannot read property 'setTokens' of undefined]`.
I can sign up, but not able to sign in or auto-sign in.
My current code with thunk:
```js
export const userSignIn = createAsyncThunk(
  "auth/signIn",
  async (credentials: SignInInput, thunkAPI) => {
    try {
      const response = await signIn({
        username: credentials.username,
        password: credentials.password,
      });
      return response;
    } catch (error: any) {
      const errorMessage = error.underlyingError ? error.underlyingError : error.message;
      return thunkAPI.rejectWithValue(errorMessage);
    }
  }
);
```

**Comment by geekabhinavp** [comment] 2023-12-05 00:08
@nadetastic, I'm wondering if the problem could be related to the file `packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts`. I noticed there's a TODO note for version 6 in it. Could you please confirm if this might be the cause? If so, is there any workaround available? My project is currently facing delays due to this issue.

**Comment by geekabhinavp** [comment] 2023-12-05 00:37
Finally!! Tried https://github.com/aws-amplify/amplify-js/issues/12622#issuecomment-1830789725 this version, and able to login. @aleguern you were also using this version?

**Comment by cwomack** [comment] 2023-12-05 21:42
As @geekabhinavp referenced above, this issue looks related of #12622.  The fix for this was released today in Amplify v6.0.6. I'll close this issue for now, but let us know if there are any further issues related to this bug!

**Closed by cwomack** 2023-12-05 21:42 UTC
Labels: bug, Auth, React Native

**Comment by sunchitanand** [comment] 2024-01-07 01:40
I'm still running into the same issue with v6.06 and above. 
```
  async function handleSignUpConfirmation() {
    try {
      const { isSignUpComplete, nextStep } = await confirmSignUp({
        username: email,
        confirmationCode: verificationCode,
      });
      console.log('nextStep: ', nextStep, typeof nextStep);
      console.log('isSignUpComplete:', isSignUpComplete);
      if (isSignUpComplete) {
        await handleAutoSignIn()
      }
    } catch (error: any) {
      console.log('error confirming sign up', error);
      if (error.name === 'CodeMismatchException') {
        // setErrorMessage
      }
    }
  }

  async function handleAutoSignIn() {
    try {
      const signInOutput = await autoSignIn();
      // handle sign-in steps
      console.log(signInOutput);
      navigation.navigate('Home');
    } catch (error: any) {
      console.log('Error auto sign in:', error);
    }
  }
```
I am able to signUp, confirmSignUp but unable to autoSignIn. Getting an unknown error status and the underlyingError suggestion did not work for me either. Anyone else still running into this?

**Comment by enzzoperez** [comment] 2024-01-19 13:57
> I'm still running into the same issue with v6.06 and above.
> 
> ```
>   async function handleSignUpConfirmation() {
>     try {
>       const { isSignUpComplete, nextStep } = await confirmSignUp({
>         username: email,
>         confirmationCode: verificationCode,
>       });
>       console.log('nextStep: ', nextStep, typeof nextStep);
>       console.log('isSignUpComplete:', isSignUpComplete);
>       if (isSignUpComplete) {
>         await handleAutoSignIn()
>       }
>     } catch (error: any) {
>       console.log('error confirming sign up', error);
>       if (error.name === 'CodeMismatchException') {
>         // setErrorMessage
>       }
>     }
>   }
> 
>   async function handleAutoSignIn() {
>     try {
>       const signInOutput = await autoSignIn();
>       // handle sign-in steps
>       console.log(signInOutput);
>       navigation.navigate('Home');
>     } catch (error: any) {
>       console.log('Error auto sign in:', error);
>     }
>   }
> ```
> 
> I am able to signUp, confirmSignUp but unable to autoSignIn. Getting an unknown error status and the underlyingError suggestion did not work for me either. Anyone else still running into this?

I had a similar issues with the same versions.. Enabling `autoSingIn` on `signUp` , my `confirmSignUp` stuck in a loading status.. When I turn off `autoSingIn` prop in `singnUp` then `confirmSignUp` works
