### ISSUE TITLE
Password managers don't seem to auto-fill login credentials in AmplifyAuthenticator -> AmplifySignIn

### ISSUE THREAD

**Issue by adampblack** [aws-amplify/amplify-js#8289] opened 2021-05-18 03:29 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
npx: installed 1 in 2.81s

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 61.16 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.0.3
  npmPackages:
    @aws-amplify/api: latest => 3.3.0 
    @aws-amplify/auth: latest => 3.4.31 
    @aws-amplify/core: latest => 3.8.23 
    @aws-amplify/ui-react: latest => 1.1.0 
    @mapbox/mapbox-gl-style-spec:  13.20.0-dev 
    aws-amplify: latest => 3.4.0 
    dompurify: latest => 2.2.8 
    eslint-config-airbnb: latest => 18.2.1 
    eslint-plugin-import: latest => 2.22.1 
    eslint-plugin-jsx-a11y: latest => 6.4.1 
    eslint-plugin-react: latest => 7.23.2 
    grommet: latest => 2.17.2 
    grommet-icons: latest => 4.5.0 
    i18next: latest => 20.2.2 
    i18next-browser-languagedetector: latest => 6.1.1 
    i18next-xhr-backend: latest => 3.2.2 
    mapbox-gl: latest => 2.2.0 
    material-icons-react: latest => 1.0.4 
    memo-parser:  0.2.1 
    prop-types: latest => 15.7.2 
    radium: latest => 0.26.1 
    react: latest => 17.0.2 (15.7.0)
    react-devtools: latest => 4.13.2 
    react-dom: latest => 17.0.2 (15.7.0)
    react-geolocated: latest => 3.2.0 
    react-i18next: latest => 11.8.15 
    react-intl: latest => 5.17.5 
    react-mapbox-gl: latest => 5.1.1 
    react-router-dom: latest => 5.2.0 
    react-scripts: latest => 4.0.3 
    react-tooltip: latest => 4.2.19 
    styled-components: latest => 5.3.0 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    subscriptions-transport-ws: latest => 0.9.18 
  npmGlobalPackages:
    @aws-amplify/cli: 1.7.6
    create-react-app: 3.0.1
    npm: 6.14.8

### Describe the bug

The Mac KeyChain password Manager and the LastPass password manager don't seem to prefill the login credentials.

Using the phone_number alias.

### Expected behavior

The password input field has type password so I would of expected the password manager to recognise it is a password field and ask to add or add when instructed.

`<input id="password" type="password" placeholder="Enter password here" name="password" class="input">`

Even when I try to add it does not work.

very cumbersome - especially using Safari on Iphone and Keychain.

This is very poor behaviour for an auth library.

### Reproduction steps

Try by adding your credentials to password manager and see if it prefills the form when you go to the page.

Will be curious if other password managers suffer the same fate.

Seems to affect Desktop and mobile.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by sammartinez** [comment] 2021-05-18 16:02
This seems to be a duplicate of https://github.com/aws-amplify/amplify-js/issues/5782. Please follow the other issue that is link regarding this. Resolving as a duplicate

**Closed by sammartinez** 2021-05-18 16:02 UTC
Labels: UI
