### ISSUE TITLE
Problem with Installing Amplify Libraries with React 18

### ISSUE THREAD

**Issue by ezekielharvey** [aws-amplify/amplify-js#10038] opened 2022-06-28 19:46 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker

### If applicable, what version of Node.js are you using?

18.4.0

### Amplify CLI Version

9.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

When I go to install `npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker` 

I get an error that says: 
![Screen Shot 2022-06-28 at 3 40 30 PM](https://user-images.githubusercontent.com/52931938/176270982-42465d6d-5467-4565-af9a-9c221971d271.png)

### Expected behavior

I expected to have installed the package. But it seems that it doesn't like to work with React 18.

### Reproduction steps

1. Install Amplify Libraries (`npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker`)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

52be70da1fcebf94b086507ff6fe323e

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jamesaucode** [comment] 2022-06-28 21:19
👋 hi @ezekielharvey, our recommendation for now is to downgrade to an older version of react native (see our [updated getting started guide](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/)). I will close this issue now as it's a duplicate of https://github.com/aws-amplify/amplify-js/issues/10017.

**Closed by jamesaucode** 2022-06-28 21:19 UTC
