### ISSUE TITLE
Updating DataStore from version 2.1.1 to 2.2.2 @connection issues

### ISSUE THREAD

**Issue by TheMoums** [aws-amplify/amplify-js#6022] opened 2020-06-05 15:09 UTC
**Describe the bug**
I have updated aws-amplify to the latest versions and this caused links issues between my `@model`. Everything was working fine with previous version, but now the entities linked are not populating with all the fields. There are, in fact, only populated by their id and _deleted. This happens no matter the connection type (`@connection`, `@connection(name:...)`, `@connection(keyName: ...)` ). 
Performing the queries in the Appsync console is working fine, so I believe this is related to DataStore.
**To Reproduce**
Update to the latest version of amplify and perform a query on linked entities.

**Expected behavior**
If I query House in the schema below 
```graphql
type House @model 
{
  id: ID!
  address: Address @connection
}
type Address @model
{
  id: ID!
  street: String
}
```

I expect to have a response like 

```javascript
house: {
id, 
address:
    {
     id, 
     street
    }
}
```
and not 
```javascript
house: {
id, 
address:
    {
     id
    }
}
```
(as expected by the Graphql queries) 
**What is Configured?**
Previous package versions (working):
│  ├─ @aws-amplify/analytics@3.1.11
│  ├─ @aws-amplify/api@3.1.11
│  ├─ @aws-amplify/auth@3.2.8
│  ├─ @aws-amplify/cache@3.1.11
│  ├─ @aws-amplify/datastore@2.1.1
│  ├─ @aws-amplify/interactions@3.1.11
│  ├─ @aws-amplify/predictions@3.1.11
│  ├─ @aws-amplify/storage@3.2.1
│  ├─ @aws-amplify/ui@2.0.2
│  ├─ @aws-amplify/xr@2.1.11
│  └─ aws-amplify@3.0.12

New packages versions:
│  ├─ @aws-amplify/analytics@3.1.15
│  ├─ @aws-amplify/api@3.1.15
│  ├─ @aws-amplify/auth@3.2.12
│  ├─ @aws-amplify/cache@3.1.15
│  ├─ @aws-amplify/datastore@2.2.2
│  ├─ @aws-amplify/interactions@3.1.15
│  ├─ @aws-amplify/predictions@3.1.15
│  ├─ @aws-amplify/storage@3.2.5
│  ├─ @aws-amplify/ui@2.0.2
│  ├─ @aws-amplify/xr@2.1.15
│  └─ aws-amplify@3.0.16

**Comment by ashika01** [comment] 2020-06-05 18:23
@TheMoums I dont know exactly what error you are seeing but I am using the same schema you posted and I dont have any error or get the expected output you have mentioned. 

This is my schema:
```
type House @model {
  id: ID!
  address: Address @connection
}
type Address @model {
  id: ID!
  street: String
}

```

This is the output on query after insert,
<img width="782" alt="Screen Shot 2020-06-05 at 11 20 11 AM" src="https://user-images.githubusercontent.com/35131273/83910064-c4c00f00-a71e-11ea-827b-fa528d42d1de.png">

I am closing this issue since this is not a bug. If you have any error, ping the error and I will reopen the issue. If you have questions, I suggest you also try asking [our community in discord](https://discord.gg/Px5YVfQ)

**Closed** 2020-06-05 18:23 UTC
Labels: Can't reproduce, DataStore

**Comment by TheMoums** [comment] 2020-06-08 15:55
@ashika01 
Thank you for your reply. One of the things we noticed is that the data is stored differently in the indexedDB.
Before the data was stored this way in the indexedDB
![before_1](https://user-images.githubusercontent.com/22890903/84052289-a8d39c00-a9b0-11ea-9e34-82180a2c267a.PNG)
With relations like this
![before_2](https://user-images.githubusercontent.com/22890903/84052294-aa04c900-a9b0-11ea-9cbc-a036515b3ef5.PNG)
And now it is stored this way (notice the difference for the address field)
![after_1](https://user-images.githubusercontent.com/22890903/84052379-c86ac480-a9b0-11ea-9c43-fdc53d49f351.PNG)
With no relations...
![ss](https://user-images.githubusercontent.com/22890903/84052487-eb957400-a9b0-11ea-9cd3-70b4435a66b6.PNG)

Do you know what would cause this problem?

**Comment by TheMoums** [comment] 2020-06-12 07:22
Upgrading to version 2.2.3 seems to have solved my problem!
