### ISSUE TITLE
Updating SMS & EMail Endpoints from Cognito along with Push Notifications using Cognito

### ISSUE THREAD

**Issue by prasadkesarkar** [aws-amplify/amplify-js#4529] opened 2019-12-07 06:51 UTC
**Issue:**
Cognito Integration with AWS Pinpoint allows only a single endpoint to be updated by using updateEndpoint Method. This is frustrating as if Cognito is integrated with Pinpoint, we expect that if the Cognito User has a mobile number and / or email address, it should create an Endpoint for SMS and Email automatically.

**Solution**
There has to be a way by which in the Analytics Integration there can be 2 check boxes in Cognito (similar to Share User Attributes) we should be allowed to automatically create SMS (mobile) and Email (email address) endpoints for Cognito Users. They could be named as Create SMS Endpoint Automatically, Create EMail Endpoint Automatically. Whenever the Email or Mobile number is created or updated in the Cognito userpool it should be updated in Pinpoint.

**Describe alternatives you've considered**
We are unable to do it now as we are looking to see if we can do some Post Authentication Lambda Trigger to do that. But that would create multiple endpoints for the same user again and again making the endpoint data not correct.

**Additional context**
If there is any other way of doing it since we want that a user be reached by Push Notification, SMS and Email all the 3 channels

**Comment by ricky-sb** [comment] 2020-08-09 04:22
How did you end up resolving this? Doesn't Cognito automatically register endpoints with Pinpoint when you sign in?  

* https://stackoverflow.com/questions/57810979/how-to-properly-configure-amplify-analytics  

* https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html

**Comment by cwomack** [comment] 2023-01-04 19:40
Closing this issue out as a duplicate of #6289 in an effort to consolidate the feature requests that suffer from the same root problem.  The limitation that the Pinpoint service will not permit more than a singular endpoint to be updated when the updateEndpoint method is called.

We are reviewing a solution to this and will update the other issue with any progress, as both would be resolved if multiple endpoints could be updated simultaneously.  Please follow #6289 for future updates and feel free to provide any further context, comments, or upvoting there for visibility.

**Closed by cwomack** 2023-01-04 19:40 UTC
Labels: feature-request, Analytics, Push Notifications
