### ISSUE TITLE
graphql @searchable returns empty results

### ISSUE THREAD

**Issue by rndgrin** [aws-amplify/amplify-js#6272] opened 2020-07-09 11:27 UTC
**Describe the bug**
We recently added the @searchable annotation to our graph scheme. unfortunalty every searchQuery is returning ampty results. Even ones with no filter.

**To Reproduce**

1. Add @searchable annotation to an entity.
2. amplify push.
3. add some resource to the entity by using createEntity mutation.
4. use the supposedly newly created elastic search resolver with a searchEntity query.

**Expected behavior**
to not get an empty result

**Code Snippet**

import { API, graphqlOperation } from 'aws-amplify'
import { searchEntities } from '../graphql/queries'

switchMap(([action, state]) => {
      return from(
        API.graphql(
          graphqlOperation(searchEntities, { filter: { username: { match: <username> } } })
        )
      ).pipe(
        mergeMap(x => console.log(x) || of(Actions.EntititesReceived({ x }))),
        catchError(error => console.log(error) || of(Actions.fetchRejected(error)))
      )
    })

**Screenshots**
<img width="186" alt="Screen Shot 2020-07-09 at 13 23 51" src="https://user-images.githubusercontent.com/53469917/87034008-74d5db80-c1e7-11ea-9e76-499dbcc4a164.png">

**Additional context**
I logged into the kibana through the ElasticSearch service on aws console, it seems like the indexes are there, and the total docs look like the total counts of out dynamoDB tables that contain the graphql entities, though each index pattern return a count of 0. I don't really know where to go and what more to check.

**Comment by aprilmintacpineda** [comment] 2020-11-28 07:16
I'm actually encountering this now.

**Comment by sammartinez** [comment] 2021-02-09 23:00
@rndgrin Are you still looking for support for this issue? Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by iartemiev** [comment] 2021-04-12 18:06
@rndgrin,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:06 UTC
Labels: GraphQL, pending-close-response-required
