### ISSUE TITLE
No Auth module registered in Amplify when try to use Storage.get

### ISSUE THREAD

**Issue by lisandrolan** [aws-amplify/amplify-js#1977] opened 2018-10-24 15:22 UTC
**Describe the bug**
Im getting the error 
No Auth module registered in Amplify
When Im doing the following call
 Storage.get( 'images/1540344600001.JPEG', { level: 'protected' })
        .then(result =>  resolve( result))
        .catch(err => console.log(err));
       ;
I am already logged in and when I verify with 
  await Amplify.Auth.currentAuthenticatedUser().then(response=>console.log(response))

I get the propper user information

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***
ConsoleLogger.js:84 [DEBUG] 18:00.886 Credentials - getting credentials
12:18:00.886 ConsoleLogger.js:84 [DEBUG] 18:00.886 Credentials - picking up credentials
12:18:00.887 ConsoleLogger.js:84 [DEBUG] 18:00.887 Credentials - getting new cred promise
12:18:00.888 ConsoleLogger.js:84 [DEBUG] 18:00.888 Credentials - checking if credentials exists and not expired
12:18:00.890 ConsoleLogger.js:84 [DEBUG] 18:00.890 Credentials - need to get a new credential or refresh the existing one

**Comment by powerful23** [comment] 2018-10-24 21:58
@lisandrolan can you provide the code snippet about how you are importing and using Amplify? The error usually happens when you are using modularized libraries and didn't import them in a correct order.

**Comment by mriccid** [comment] 2018-10-25 03:05
I've had similar problems caused by modular imports and managed to get around it by configuring the module then registering it with the Amplify singleton using [this](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Amplify.ts#L25) method.

**Comment by lisandrolan** [comment] 2018-10-25 13:59
The problem was related to AWS-SDK previous instalation. 
What I did was delete all the node_modules folders. and then npm install again

**Comment by nidsharm** [comment] 2018-10-25 22:33
Closing the issue, as the problem is resolved. Please feel free to re-open if the issue persists.

**Closed by nidsharm** 2018-10-25 22:33 UTC
Labels: Auth, Storage
