### ISSUE TITLE
Storage.put not using Cognito user's sub value in PUT header returns 403

### ISSUE THREAD

**Issue by Sir-Kibble** [aws-amplify/amplify-js#7958] opened 2021-03-18 04:26 UTC
**Which Category is your question related to?**
Storage, Auth

**Amplify CLI Version** 
4.45.2

**What AWS Services are you utilizing?**
Storage, Auth

**Description**
I rebuilt my project and Storage.put requests that were previously working now aren't.  The IAM policy looks good and I haven't touched the Amplify generated role
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::superniftybucket/protected/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
Looking through the headers of the requests, I noticed something odd.  The cognito user logged in has a sub of `d8b68592-e84f-459b-ade8-d761710c4068`, but the request header is `PUT https://superniftybucket.s3.us-east-2.amazonaws.com/protected/us-east-2%3A8d663b84-a924-4c67-89a9-e5b1bbf71540/theFileIWannaUpload?x-id=PutObject`

Where did `3A8d663b84-a924-4c67-89a9-e5b1bbf71540` come from?  Why is it not using the sub value of the current user?  I tried to specify it manually using `Storage.put('theFileIWannaUpload', data, {level: 'protected', identityId: 'd8b68592-e84f-459b-ade8-d761710c4068'})`, but it still uses the mystery value.  What's going on?

**Comment by Sir-Kibble** [comment] 2021-03-18 23:26
I've been poking at it more and the value changes when I'm logged in as different users, but still isn't the sub value.  It appears to be in the format of a sub.  Auth.currentCredentials().identiyId gives the proper identityId/sub for the current user.  Is there a way to over-ride the Storage generated header?

**Comment by Sir-Kibble** [comment] 2021-03-23 01:06
I was using `aws-amplify` 3.3.20 when things were working.  I updated to 3.3.24 after trying to fix a separate issue(https://github.com/aws-amplify/amplify-js/issues/7973) to no avail.  Downgrading back to 3.3.20 fixed neither issue.

**Comment by chrisbonifacio** [comment] 2021-03-29 21:14
Hello. I'm currently in the process of reproducing this issue and have had some progress. However, I might need a little more context around the issue itself.

You are correct in that the Storage.put requests are using Identity Pool IDs rather than User Pool IDs.
In my attempt to reproduce the issue, I was able to successfully upload and get a file uploaded by the same user (using the protected level).

May I ask how you rebuilt your project to get a better understanding of the configuration of your amplify project?

**Comment by chrisbonifacio** [comment] 2021-03-29 21:20
If you could, could you please provide the steps taken to configure the project as well? Storage and Auth in particular.

**Comment by chrisbonifacio** [comment] 2021-03-30 21:03
Dug into this a bit further and the usage of the Identity Pool ID seems to be the intended behavior.

From the docs:

"Some apps need to use AWS services which require signing requests. Examples of this would be storing images or videos on S3, or sending analytics to Pinpoint or Kinesis. Amplify automatically signs requests with short term credentials from a Cognito Identity Pool which automatically expire, rotate, and refresh by the Amplify client libraries."

[Accessing AWS Services](https://docs.amplify.aws/lib/auth/overview/q/platform/js#accessing-aws-services)

**Comment by Sir-Kibble** [comment] 2021-04-02 02:06
Using default Auth configuration works, but when I attempt to change Auth settings I get the issue.  I've since switched to using defaults, but before I was having this issue with using email addresses instead of usernames.  If there's a file that's useful, I can pull it out of my git history and post it here.  

Is there a reason the policy says it's uses sub but in actuality it's using identityIds?  Seems a bit of a misnomer.

**Comment by chrisbonifacio** [comment] 2021-04-02 16:42
Thanks for following up! It is a little confusing seeing "sub" in the policy and also in the user attributes if you're using cognito user pools. They are definitely not the same thing, though they could. I think in this case "sub" just means the subject trying to gain access and is not directly tied to one service. In the case of Storage, it has to be an Identity ID as explained in the docs I linked before.

sub: a globally unique identifier, set by AWS

> I was having this issue with using email addresses instead of usernames
Do you mean using email address to authenticate/sign in?
Was this a past issue or is it working for you now using emails and the default Auth/Storage configuration?

**Comment by Sir-Kibble** [comment] 2021-04-03 15:06
> Do you mean using email address to authenticate/sign in?

Yes.  It was a past issue as we're now using usernames and default Auth settings.

**Comment by chrisbonifacio** [comment] 2021-04-05 14:11
Okay, that's good to hear! Sounds like this might've just been a bit of a misunderstanding. Glad you've got it working. We will take steps to clarify in the documentation the intended behavior and requirements for the usage of the Storage category.

Closing this issue. Feel free to comment again if you need further assistance on this. Thank you!

**Closed by chrisbonifacio** 2021-04-05 14:11 UTC
Labels: Auth, Can't reproduce, Storage
