### ISSUE TITLE
Node version update for Lambdas

### ISSUE THREAD

**Issue by NiklasScholz1** [aws-amplify/amplify-js#10213] opened 2022-08-16 09:36 UTC
### Describe the feature you'd like to request

I got an email from AWS regarding Lamdas that are running on Node.js 12 - where the support ends this year. Starting November 14 with the end of security patches, and from December 14 you will be no longer able to update existing functions using Node.js 12 runtime.

It would be nice to get some instructions on how to update the lambdas that were generated by amplify; like [here](https://docs.amplify.aws/cli/migration/lambda-node-version-update/) , when there was an update necessary for lamdas using Node.js 8.10.

### Describe the solution you'd like

Update Instructions like [here](https://docs.amplify.aws/cli/migration/lambda-node-version-update/).

### Describe alternatives you've considered

Since those lambdas are generated by amlify, I can't hadle this by myself manually.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by chrisbonifacio** [comment] 2022-08-16 16:01
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/10894

**Closed by chrisbonifacio** 2022-08-16 16:01 UTC
Labels: feature-request
