### ISSUE TITLE
[aws-amplify/amplify-js] export 'default' (imported as 'Amplify') was not found in 'aws-amplify' 

### ISSUE THREAD

**Issue by akbarm** [aws-amplify/amplify-js#11107] opened 2023-03-20 19:47 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Amplify Categories

auth

### Environment information

<details> 

```
 System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 1.33 GB / 7.88 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @aws-amplify/ui-react: ^4.4.0 => 4.4.0
    @aws-amplify/ui-react-internal:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5
    @testing-library/react: ^13.4.0 => 13.4.0
    @testing-library/user-event: ^13.5.0 => 13.5.0
    aws-amplify: ^5.0.20 => 5.0.20
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-scripts: 5.0.1 => 5.0.1
    web-vitals: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.2
    yarn: 1.22.19
```

</details>

### Describe the bug

Running this on a Windows 10 environment. 

Following this tutorial -- > https://www.youtube.com/watch?v=Sk9HMuAaTmQ

Failed to compile.

```bash
Attempted import error: 'aws-amplify' does not contain a default export (imported as 'Amplify').
ERROR in ./src/index.js 12:0-14
export 'default' (imported as 'Amplify') was not found in 'aws-amplify' (possible exports: API, APIClass, AWSCloudWatchProvider, AWSKinesisFirehoseProvider, AWSKinesisProvider, AWSPinpointProvider, AmazonPersonalizeProvider, Amplify, Analytics, Auth, AuthModeStrategyType, Cache, ClientDevice, DataStore, Geo, Hub, I18n, Interactions, Logger, Notifications, Predicates, Predictions, PubSub, ServiceWorker, Signer, SortDirection, Storage, StorageClass, graphqlOperation, syncExpression, withSSRContext)
```

### Expected behavior

Expecting the Login Page to be rendered as per the tutorial I have followed. 

### Reproduction steps

 When i run the command "npm start" from the command line. 

### Code Snippet

```javascript
// Put your code below this line.

**App.js**

import logo from './logo.svg';
import './App.css';
import { Amplify } from 'aws-amplify'

import { withAuthenticator, signOut  } from '@aws-amplify/ui-react';

function App({ signOut }) {
  return (
    <div className="App">
      <header className="App-header">
      <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>


      </header>
      <signOut />
    </div>
  );
}

export default withAuthenticator(App);
```

### Additional configuration

package.json

```json
{
  "name": "react-cognito-api",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^4.4.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^5.0.20",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by nadetastic** [comment] 2023-03-20 19:58
Hi @akbarm, thanks for opening this issue.

Im seeing two different `package.json`
- one with `"name": "react-cognito-api"` that has `aws-amplify` 
- another with `"name": "cognito-pool",` without `aws-amplify`

Can you confirm which your React App is using?

**Comment by akbarm** [comment] 2023-03-21 00:36
Sorry about the confusion. Cleaned up the code. Hope this is comprehensible.

**Comment by nadetastic** [comment] 2023-03-21 16:20
Thanks for cleaning it up - looking at the code you shared, it looks like you are importing Amplify correctly as named. Also I used your samples to setup a copy on my end which [can be viewed here](https://github.com/nadetastic/cra-amplified/tree/11107) and I do not get the error.

The issue here looks to be importing Amplify as default ( `import Amplify from ...` instead of `import { Amplify } from ...` )in a different location - The error seems to be pointing at `index.js`

> ERROR in ./src/index.js 12:0-14

**Comment by nadetastic** [comment] 2023-03-21 16:21
Thanks for cleaning it up @akbarm - looking at the code you shared, it looks like you are importing Amplify correctly as named. Also I used your samples to setup a copy on my end which [can be viewed here](https://github.com/nadetastic/cra-amplified/tree/11107) and I do not get the error.

The issue here looks to be importing Amplify as default ( `import Amplify from ...` instead of `import { Amplify } from ...` )in a different location - The error seems to be pointing at `index.js`

> ERROR in ./src/index.js 12:0-14

**Comment by akbarm** [comment] 2023-03-21 16:41
Thanks. Just so I understand this correctly? The following code snippet in the index.js file.  Do i need to change it to "import {Amplify} from 'aws-amplify' in the code below? 


import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import Amplify from 'aws-amplify';
import config from './aws-exports';
Amplify.config(config);


const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

**Comment by nadetastic** [comment] 2023-03-21 16:45
@akbarm yep, that is correct - once you change the import it should resolve the problem

**Comment by akbarm** [comment] 2023-03-22 10:37
@nadetastic, it works the error went away. Now the problem is, i'm unable to render the java script and thus seeing a blank page. I am on chrome and did go back to the settings and confirmed under the chrome://settings/content/javascript that 'Site can use Javascript'. When I do view page source on : localhost:3000, it tells me : 

<html>
<body>


<title>React App</title>
--
  | <script defer src="/static/js/bundle.js"></script></head>
  | <body>
  | <noscript>You need to enable JavaScript to run this app.</noscript>
  | <div id="root"></div>
  | 
  | </body>
  | </html>


</body>
</html>
<title>React App</title>
  <script defer src="[/static/js/bundle.js](http://localhost:3000/static/js/bundle.js)"></script></head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
  </body>
</html>

**Comment by helgabalashova** [comment] 2023-03-22 23:15
@akbarm I noticed in your code that you call `Amplify.config(config)` instead of `Amplify.configure(config)`. Can you please fix it and let us know if it fixes the problem you have.

**Comment by akbarm** [comment] 2023-03-23 01:24
@helgabalashova 

the Index.js file look like this. 

The only option I have is to use : Amplify.default.config(config);

import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import {Amplify} from 'aws-amplify';
import config from './aws-exports';
Amplify.default.config(config);
//Amplify.config(config);


const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

**Comment by nadetastic** [comment] 2023-03-23 15:53
@akbarm the proper way to configure amplify is to use `Amplify.configure(config)` as @helgabalashova mentioned. I can confirm that using `Amplify.config()` or `Amplify.default.config()` will result in a blank page, and within the console, you will see the error `Uncaught TypeError: Amplify.config is not a function`

In order to resolve this issue you would need to use `Amplify.configure(config)` - https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#general-configuration

**Comment by akbarm** [comment] 2023-03-24 12:03
@nadetastic @helgabalashova 

Made the changes as suggested, still getting the same blank page. Code for index.js and app.js below. 


index.js looks like this: 

import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import {Amplify} from 'aws-amplify';
import config from './aws-exports';
Amplify.configure(config);

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

reportWebVitals();

App.js looks like this : 

import logo from './logo.svg';
import './App.css';
import {Amplify} from 'aws-amplify';

import { withAuthenticator, signOut  } from '@aws-amplify/ui-react';

function App({ signOut }) {
  return (
    <div className="App">
      <header className="App-header">
      <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
      <signOut />
    </div>
  );
}

export default withAuthenticator(App);

**Comment by nadetastic** [comment] 2023-03-24 14:57
Are yo uable to check the console log for any error messages? @akbarm

**Comment by nadetastic** [comment] 2023-03-24 21:33
@akbarm It was pointed out to me by @helgabalashova that the problem you are facing now is possibly related to your React syntax in your `index.js` file.

When using the index.js code you shared, we see the same blank screen and an error message in the console:
```
Uncaught TypeError: react_dom_client__WEBPACK_IMPORTED_MODULE_1__.render is not a function
```

I'm not sure what made you change your code, but it looks like you should be using `ReactDOM.createRoot()` instead of `ReactDOM.render()`

Try update you `index.js` to the following:

```js
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import {Amplify} from 'aws-amplify';
import config from './aws-exports';
Amplify.configure(config);

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

reportWebVitals();
```

**Comment by nadetastic** [comment] 2023-03-28 15:43
Hi @akbarm - let me know if you still need assistance on this. Otherwise, I'll go ahead and close it out. Thanks!

**Closed** 2023-03-29 14:37 UTC
Labels: Core, pending-response, pending-triage
