### ISSUE TITLE
Storage.get returns a presigned URL (rather than throws an error) for a non-exist key

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-js#2144] opened 2018-11-18 17:53 UTC
**Describe the bug**
`Storage.get(non_exist_key)` returns a pre-signed URL rather than throwing an error.

**To Reproduce**
Same behavior as in https://github.com/aws-amplify/amplify-js/issues/218#issuecomment-431738070. I want to be able to pick/upload/preview an image, so I use `<S3Image picker imgKey="example.png" />`. However, a "broken paper" is rendered atop the picker.

1. Include `<S3Image picker imgKey="example.png" />` in `render()` of a react component.
2. Refresh the page.
3. From chrome dev tool console, `GET <a very long pre-signed url> 404 (Not Found)`
3. `cmd + p`, search `Storage.js` to debug in chrome dev tools, the very long pre-signed url is exactly the same URL generated at [Storage.ts#L127](https://github.com/aws-amplify/amplify-js/blob/4644b432/packages/storage/src/Storage.ts#L127).

**Expected behavior**
`Storage.get` should be able to return an error on such "failure", i.e., key doesn't exist.

**Desktop (please complete the following information):**
 - OS: macOS (v10.13.5)
 - Browser: Chrome (v70)

**Additional context**
The root cause is [s3.getSignedUrl](https://github.com/aws-amplify/amplify-js/blob/4644b432/packages/storage/src/Storage.ts#L127) returns a pre-signed URL even if the key doesn't exist in S3. (You can find https://github.com/aws/aws-sdk-js/issues/1529 for more context).

If there exists (and it does, e.g., https://stackoverflow.com/a/26950546/7550592) a way to check whether a pre-signed URL really points to an existing resource, let name if `checkExistence: string => boolean`, a few solutions I can think of:
- Inside `Storage.js`, after receiving pre-signed URL from `s3.getSignedUrl`, then `checkExistence`. If false, throw an error.
- Provide a `onError` props to `<S3Image />` and call `checkExistence` inside the `onError` props.

Which approach is preferred? I prefer the 1st solution so that app developers
- Don't need to dive into the `aws-amplify-react` etc source code to understand what actually happens.
- Don't need to include `aws-sdk-js` dependency in their app.
- Benefit from framework-level-consistent error handling.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by powerful23** [comment] 2018-11-19 20:53
@YikSanChan thanks for your feedback. We will look into this issue.

**Comment by elorzafe** [comment] 2018-11-21 22:13
@YikSanChan  if you do `Storage.get(key, {...options, download: true})` that will try to download the data.

**Comment by YikSanChan** [comment] 2018-11-22 22:32
> @YikSanChan if you do `Storage.get(key, {...options, download: true})` that will try to download the data.

This definitely helps. Again, I hope `<S3Image />` handle this for users. How about this?
- In `<S3Image />`, add 2 more states: `previewError` and `uploadError`, and have 2 methods `onPreviewError` and `onUploadError` to dispose the 2 states to users. `previewError` is set by `getImageSource` while `uploadError` is set by `load`.
- In `getImageSource`, use `Storage.get(key, {...options, download: true})` as a check to whether the pre-signed URL points to a existing resource or not.

A downside of this proposal is that it increases service call cost to S3 (as I believe `s3.getObject` is more expensive than `s3.getSignedUrl`). But it guarantees that any `src` in `S3Image` state points to an existing resource, if not the [initSrc](https://github.com/aws-amplify/amplify-js/blob/7e07ebe66e9957c01c4d1fee190b48a2f33fff89/packages/aws-amplify-react/src/Storage/S3Image.js#L34).

Any concern/suggestion is welcomed.

**Comment by YikSanChan** [comment] 2018-12-03 06:31
Relates to https://github.com/aws-amplify/amplify-js/issues/1145

**Comment by abdallahshaban557** [comment] 2022-08-10 01:52
Closing this as a duplicate of #1145

**Closed by abdallahshaban557** 2022-08-10 01:52 UTC
Labels: feature-request, Storage
