### ISSUE TITLE
After updating @aws-amplify/auth to latest version(1.5.0) test cases is failing because of failed to mock Auth module.

### ISSUE THREAD

**Issue by anis-shaikh** [aws-amplify/amplify-js#4499] opened 2019-12-03 07:38 UTC
After updating @aws-amplify/auth to latest version(1.5.0) test cases is failing because of failed to mock Auth module.

1. Import Auth API by
import Auth from '@aws-amplify/auth';

2. mock it by jest
jest.mock('@aws-amplify/auth');

3. See error
Failed to get mock metadata: /Users/an***/Documents/s***/node_modules/@aws-amplify/auth/index.js

` Test suite failed to run

    Failed to get mock metadata: /Users/an***/Documents/s***/node_modules/@aws-amplify/auth/index.js

    See: https://jestjs.io/docs/manual-mocks.html#content

    > 1 | import Auth from '@aws-amplify/auth';`

**Comment by ericclemmons** [comment] 2019-12-03 18:35
@anis-shaikh Thanks for bringing this to your attention, and your clear steps to reproduce 👏!

I was able to reproduce this here:

> https://codesandbox.io/s/httpsgithubcomaws-amplifyamplify-jsissues4499-sr9l1

It looks like the regression was introduced in #4007 and the bump either in 233dd1c56cb637193e4b44437c38853359d0de59 or c0fa439b28672a02662bc160058e2a0fb2bf4c13.

We'll need to investigate the difference in what's being installed so that Jest is able to mock it successfully...

### `@aws-amplify/auth@1.3.3`

<img width="1327" alt="1 3 3" src="https://user-images.githubusercontent.com/15182/70078714-0fb66980-15b8-11ea-844e-4dec9ad9bcda.png">

### `@aws-amplify/auth@1.4.2`

<img width="1330" alt="1 4 2" src="https://user-images.githubusercontent.com/15182/70078716-104f0000-15b8-11ea-9aab-4398c8136650.png">

### `@aws-amplify/auth@1.4.3`

<img width="1331" alt="1 4 3" src="https://user-images.githubusercontent.com/15182/70078717-104f0000-15b8-11ea-8ccf-bceb7e95e661.png">

### `@aws-amplify/auth@1.5.0`
<img width="1327" alt="1 5 0" src="https://user-images.githubusercontent.com/15182/70078718-10e79680-15b8-11ea-94e0-d0ee33e5414f.png">

**Comment by ericclemmons** [comment] 2019-12-03 18:36
For an easy way to compare the differences between what's published, I've been using:

1. https://unpkg.com/browse/@aws-amplify/auth@1.4.2/
1. https://unpkg.com/browse/@aws-amplify/auth@1.4.3/

**Comment by ericclemmons** [comment] 2019-12-03 18:42
For comparison, `v1.4.2`'s entry-point is https://unpkg.com/browse/@aws-amplify/auth@1.4.2/lib/index.js, while `v1.4.3`'s entry is https://unpkg.com/browse/@aws-amplify/auth@1.4.3/index.js.

Related, `react-ga` had similar issues (https://github.com/react-ga/react-ga/issues/316) that was resolved via https://github.com/react-ga/react-ga/pull/317.

**Comment by ericclemmons** [comment] 2019-12-03 18:49
@Amplifiyer I'd appreciate some additional 👀 on this ☝️

**Comment by ericclemmons** [comment] 2019-12-03 18:51
There are consistent threads regarding Jest & mocking failing due to "meta-programming":
> https://github.com/facebook/jest/issues/471

As best I can tell, it's due to the dynamic `require` that happens, so Jest isn't aware of what the exports without using Proxies.

Still researching the solution to this...

**Comment by ifielder** [comment] 2019-12-10 17:32
I was having the same issue with `@aws-amplify/api`

After looking at @ericclemmons  comparisons it seems `v1.4.3's` conditional entry point is causing problems with jest's mocking mechanism. 

I was able to fix this issue by using 

`import API, { graphqlOperation } from '@aws-amplify/api/lib';`

instead of 

`import API, { graphqlOperation } from '@aws-amplify/api';`


This is how I mocked in my test 

```// myAPITestfile.js 

import API from '@aws-amplify/api/lib';


// arrange 
jest.mock('@aws-amplify/api/lib');


// act
API.graphql.mockResolvedValue({});```

**Comment by anywhereiromy** [comment] 2019-12-30 15:47
Did you find a fix for this? Tried the above workaround on a similar problem but to no avail.

**Comment by anis-shaikh** [comment] 2019-12-30 16:39
@anywhereiromy I tried by above solution and it works for me but for that I need to replace all the import statement to " import API from '@aws-amplify/api/lib' ".  

So I found another solution and that is by manually mocking Auth module.

`// __mocks__/auth.js
const Auth = jest.genMockFromModule('@aws-amplify/auth');
module.exports = Auth;

// __tests__/Test.js
import Auth from '@aws-amplify/auth';

describe('test', () => {
    it('should test signin functions', () => {
        Auth.signIn = jest.fn(() => {
            console.log('eep');
            return 'eep'
        });
        expect(Auth.signIn()).toBe('eep');
    });
});`

**Comment by Amplifiyer** [comment] 2020-01-08 00:36
@anis-shaikh @anywhereiromy @ifielder We have just merged in the fix. Can you please try with aws-amplify@unstable version and let us know if the issue is resolved for you?

**Closed** 2020-01-15 00:40 UTC
Labels: Auth, Tests, bug, pending-close-response-required
