### ISSUE TITLE
Storage does not work if withSSRContext have been called

### ISSUE THREAD

**Issue by MaximilianSchon** [aws-amplify/amplify-js#7207] opened 2020-11-16 19:11 UTC
**Describe the bug**
Storage does not work if you have used called the "withSSRContext()" function.

**To Reproduce**

1. Create a next app following this tutorial: https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js, no need to add hosting.
2. Add storage (an S3 bucket).
3. Call withSSRContext()
4. Try to use Storage

**Expected behavior**
To be able to use withSSRContext() and then use Storage on the client side.

**Code Snippet**
pages/index.js
```
import {useState} from 'react';
import {withAuthenticator} from '@aws-amplify/ui-react';
import {withSSRContext, Storage} from 'aws-amplify';

function Home() {
    withSSRContext();
    const [file,
        setFile] = useState();
    const upload = (f) => {
        f = f.files[0];
        Storage.put(`test` + f.name.substring(f.name.lastIndexOf('.') + 1), f, {contentType: f.type}).then(result => {

            if (result.key) {
                alert('Upload success!');
                console.log(result.key)
            }

        })
    }
    return <input ref={(ref) => setFile(ref)} onChange={() => upload(file)} type="file"/>
}
export default withAuthenticator(Home);
```
pages/app.js
```
import '../styles/globals.css'
import awsExports from '../aws-exports'
import Amplify from 'aws-amplify';

Amplify.configure({...awsExports, ssr: true});

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
```

**Comment by amhinson** [comment] 2020-11-18 17:55
@MaximilianSchon It looks like your usage of `withSSRContext` is incorrect. As mentioned in the [docs](https://docs.amplify.aws/lib/ssr/q/platform/js#withssrcontext), it should just be used for server side functions such as `getServerSideProps`. If you remove that, does your app function as expected?

One thing to note is that the only modules that have been thoroughly tested with Next.js right now are `Auth`, `API` and `DataStore`, so theres a chance something still might be off: 
https://github.com/aws-amplify/amplify-js/blob/e56aba642acc7eb3482f0e69454a530409d1b3ac/packages/aws-amplify/src/withSSRContext.ts#L16-L17

**Comment by MaximilianSchon** [comment] 2020-11-18 18:22
> @MaximilianSchon It looks like your usage of `withSSRContext` is incorrect. As mentioned in the [docs](https://docs.amplify.aws/lib/ssr/q/platform/js#withssrcontext), it should just be used for server side functions such as `getServerSideProps`. If you remove that, does your app function as expected?
> 
> One thing to note is that the only modules that have been thoroughly tested with Next.js right now are `Auth`, `API` and `DataStore`, so theres a chance something still might be off:
> https://github.com/aws-amplify/amplify-js/blob/e56aba642acc7eb3482f0e69454a530409d1b3ac/packages/aws-amplify/src/withSSRContext.ts#L16-L17

Yes, that checks out. My bad. 
I thought that the idea was that if you are going to use it on the server side, you would need the withSSRContext function call.

Thank you.

**Comment by ericclemmons** [comment] 2021-01-06 17:56
Sorry for re-opening.

I thought it was a duplicate of #7505, but the customer usage here is `Storage.put` **on the client**, which works without a need for `withSSRContext`.

**Closed by ericclemmons** 2021-01-06 17:56 UTC
Labels: SSR, Storage, to-be-reproduced
