### ISSUE TITLE
Can't import the named export 'Amplify' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by clintagossett** [aws-amplify/amplify-js#11158] opened 2023-03-30 13:37 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

Not applicable

### Environment information

<details>

```

  System:
    OS: macOS 12.3.1
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 32.80 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 15.4
  npmPackages:
    @aws-amplify/ui-react: ^4.4.3 => 4.4.3 
    @aws-amplify/ui-react-internal:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^5.0.22 => 5.0.22 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-scripts: ^2.1.3 => 2.1.3 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    create-next-app: 13.2.4
    create-react-app: 5.0.1
    firebase-tools: 11.24.0
    npm-check-updates: 16.7.10
    npm: 8.6.0


```

</details>

### Describe the bug

I'm following a basic tutorial for creating a react app with AWS Cognito Login.

The app fails to compile.  Here is the error I'm getting.

```JavaScript 
import { Amplify } from 'aws-amplify';
```

> ./node_modules/@aws-amplify/ui-react/dist/esm/components/Geo/MapView/index.mjs
> Can't import the named export 'Amplify' from non EcmaScript module (only default export is available)

If I change to a "default export"...I get the following error.

```JavaScript
import Amplify from 'aws-amplify';
```

> ./src/App.js
> Attempted import error: 'aws-amplify' does not contain a default export (imported as 'Amplify').

### Expected behavior

App should compile.

### Reproduction steps

1. Create new react app with `npx create-react-app {your app}`
2. Install aws-amplify and @aws-amplify/ui-react with `npm i --save aws-amplify @aws-amplify/ui-react`
3. Copy over aws-exports.js file 
4. Replace App.js contents with code provided below. 

### Code Snippet

App.js

```javascript
import React from 'react';
import './App.css';

import { Amplify } from 'aws-amplify';
import {AmplifySignOut, withAuthenticator} from '@aws-amplify/ui-react';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);


function App() {
  return (
    <div className="App">
      <header className="App-header">
      
       <h2>You're Logged In </h2>
      </header>
    </div>
  );
}

export default withAuthenticator(App);


```

package.json
```javascript
{
  "name": "af-psa",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^4.4.3",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^5.0.22",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^2.1.3",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment] 2023-03-30 13:53
Hi @clintagossett, I think the issue is that we no longer have the component `AmplifySignOut` exported from the UI package. It was [removed with v2.0](https://ui.docs.amplify.aws/react/getting-started/migration#update-and-usage-2)

For the same code you have there, now you would do:
```js
import { Amplify } from 'aws-amplify';
import {withAuthenticator} from '@aws-amplify/ui-react';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);

function App({ signOut }) {
  return (
    <div className="App">
      <header className="App-header">
      
       <h2>You're Logged In </h2>
      </header>
	  <button onClick={signOut}>Sign Out</button>
    </div>
  );
}

export default withAuthenticator(App);
```

Was that an official AWS Amplify tutorial you were following? We are constantly trying to improve the libraries and docs but sometimes we miss documentation and I would love to fix it if it's something from us

**Comment by clintgossett** [comment] 2023-03-30 14:50
The original tutorial I was following with the "AmplifySignOut" element was an outdated, unofficial YouTube video.  

Here's the AWS article that had my fix. 

https://ui.docs.amplify.aws/react/getting-started/troubleshooting

**Comment by tannerabread** [comment] 2023-03-30 15:00
Thank you for the update! Glad we had the troubleshooting guide in the UI docs. I've actually run into a problem with `react-scripts` before but it was a different error.

If you use `npx create-react-app <project_name>` it should always use the latest available version in the npm registry for that package so you wouldn't run into this problem again

I'll close this for now but feel free to open a new issue if you find any more problems with the library and check out our discord to join the community of Amplify developers

**Closed** 2023-03-30 15:00 UTC
Labels: Auth, UI, pending-triage

**Comment by clintgossett** [comment] 2023-03-30 15:26
AmplifySignOut is still listed in this tutorial. 

https://github.com/aws-amplify/amplify-ui/tree/legacy/legacy/amplify-ui-react

**Comment by tannerabread** [comment] 2023-03-30 15:29
that is the legacy UI package, we generally don't recommend customers install that package anymore and instead use the `@aws-amplify/ui-react` package, but thank you for pointing that out!

**Comment by clintgossett** [comment] 2023-03-30 15:30
> that is the legacy UI package, we generally don't recommend customers install that package anymore and instead use the `@aws-amplify/ui-react` package, but thank you for pointing that out!

Yea, I caught that late...deleted my comment, but it came too late.
