### ISSUE TITLE
Ability to modify MFA code timeout

### ISSUE THREAD

**Issue by s1mrankaur** [aws-amplify/amplify-js#8929] opened 2021-09-21 16:29 UTC
### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

Ability to modify timeout of MFA as 3 minutes seems petty short

### Describe the solution you'd like

Ability to modify timeout of MFA code

### Describe alternatives you've considered

No workarounds

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment] 2023-01-10 22:41
Hello @s1mrankaur 👋.  It looks like this issue is a duplicate of #3478 (as referenced by your comment above), but before closing it out as such... I wanted to see if you've been able to implement the workaround referenced/understand how it works first since it's been over a year.  

Were you able to get it implemented/working?

**Comment by cwomack** [comment] 2023-01-24 23:33
Closing this issue as a duplicate of #3478 which also provides ideas for a workaround and more context.  Please follow that issue for updates/progress regarding the feature request we are filing with the Cognito service team.

**Closed by cwomack** 2023-01-24 23:33 UTC
Labels: feature-request, Auth, Cognito, Service Team, pending-response
