### ISSUE TITLE
Angular 12 crypto polyfill warning error

### ISSUE THREAD

**Issue by rajinder-yadav** [aws-amplify/amplify-js#8527] opened 2021-07-02 05:59 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

```sh
System:
    OS: Linux 5.12 openSUSE Tumbleweed 20210628
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 1.48 GB / 31.29 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - ~/dev/node_modules/.bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    @angular-devkit/build-angular: ~12.1.0 => 12.1.1 
    @angular/animations: ~12.1.0 => 12.1.1 
    @angular/animations/browser:  undefined ()
    @angular/animations/browser/testing:  undefined ()
    @angular/cli: ~12.1.0 => 12.1.1 
    @angular/common: ~12.1.0 => 12.1.1 
    @angular/common/http:  undefined ()
    @angular/common/http/testing:  undefined ()
    @angular/common/testing:  undefined ()
    @angular/common/upgrade:  undefined ()
    @angular/compiler: ~12.1.0 => 12.1.1 
    @angular/compiler-cli: ~12.1.0 => 12.1.1 
    @angular/compiler/testing:  undefined ()
    @angular/core: ~12.1.0 => 12.1.1 
    @angular/core/testing:  undefined ()
    @angular/forms: ~12.1.0 => 12.1.1 
    @angular/platform-browser: ~12.1.0 => 12.1.1 
    @angular/platform-browser-dynamic: ~12.1.0 => 12.1.1 
    @angular/platform-browser-dynamic/testing:  undefined ()
    @angular/platform-browser/animations:  undefined ()
    @angular/platform-browser/testing:  undefined ()
    @angular/router: ~12.1.0 => 12.1.1 
    @angular/router/testing:  undefined ()
    @angular/router/upgrade:  undefined ()
    @aws-amplify/ui-angular: ^1.0.13 => 1.0.13 
    @types/jasmine: ~3.6.0 => 3.6.11 
    @types/node: ^12.11.1 => 12.20.15 (15.14.0)
    aws-amplify: ^4.1.2 => 4.1.2 
    jasmine-core: ~3.7.0 => 3.7.1 (3.8.0)
    karma: ~6.3.0 => 6.3.4 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage: ~2.0.3 => 2.0.3 
    karma-coverage-coffee-example:  1.0.0 
    karma-jasmine: ~4.0.0 => 4.0.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.6.0 
    lib:  0.0.1 
    rxjs: ~6.6.0 => 6.6.7 
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    tslib: ^2.2.0 => 2.3.0 (1.14.1)
    typescript: ~4.3.2 => 4.3.5 (4.3.4)
    zone-mix:  undefined ()
    zone-node:  undefined ()
    zone-testing:  undefined ()
    zone.js: ~0.11.4 => 0.11.4 
    zone.js/async-test:  undefined ()
    zone.js/async-test.min:  undefined ()
    zone.js/fake-async-test:  undefined ()
    zone.js/fake-async-test.min:  undefined ()
    zone.js/jasmine-patch:  undefined ()
    zone.js/jasmine-patch.min:  undefined ()
    zone.js/long-stack-trace-zone:  undefined ()
    zone.js/long-stack-trace-zone.min:  undefined ()
    zone.js/mocha-patch:  undefined ()
    zone.js/mocha-patch.min:  undefined ()
    zone.js/proxy:  undefined ()
    zone.js/proxy.min:  undefined ()
    zone.js/sync-test:  undefined ()
    zone.js/sync-test.min:  undefined ()
    zone.js/task-tracking:  undefined ()
    zone.js/task-tracking.min:  undefined ()
    zone.js/webapis-media-query:  undefined ()
    zone.js/webapis-media-query.min:  undefined ()
    zone.js/webapis-notification:  undefined ()
    zone.js/webapis-notification.min:  undefined ()
    zone.js/webapis-rtc-peer-connection:  undefined ()
    zone.js/webapis-rtc-peer-connection.min:  undefined ()
    zone.js/webapis-shadydom:  undefined ()
    zone.js/webapis-shadydom.min:  undefined ()
    zone.js/wtf:  undefined ()
    zone.js/wtf.min:  undefined ()
    zone.js/zone-bluebird:  undefined ()
    zone.js/zone-bluebird.min:  undefined ()
    zone.js/zone-error:  undefined ()
    zone.js/zone-error.min:  undefined ()
    zone.js/zone-legacy:  undefined ()
    zone.js/zone-legacy.min:  undefined ()
    zone.js/zone-patch-canvas:  undefined ()
    zone.js/zone-patch-canvas.min:  undefined ()
    zone.js/zone-patch-cordova:  undefined ()
    zone.js/zone-patch-cordova.min:  undefined ()
    zone.js/zone-patch-electron:  undefined ()
    zone.js/zone-patch-electron.min:  undefined ()
    zone.js/zone-patch-fetch:  undefined ()
    zone.js/zone-patch-fetch.min:  undefined ()
    zone.js/zone-patch-jsonp:  undefined ()
    zone.js/zone-patch-jsonp.min:  undefined ()
    zone.js/zone-patch-message-port:  undefined ()
    zone.js/zone-patch-message-port.min:  undefined ()
    zone.js/zone-patch-promise-test:  undefined ()
    zone.js/zone-patch-promise-test.min:  undefined ()
    zone.js/zone-patch-resize-observer:  undefined ()
    zone.js/zone-patch-resize-observer.min:  undefined ()
    zone.js/zone-patch-rxjs:  undefined ()
    zone.js/zone-patch-rxjs-fake-async:  undefined ()
    zone.js/zone-patch-rxjs-fake-async.min:  undefined ()
    zone.js/zone-patch-rxjs.min:  undefined ()
    zone.js/zone-patch-socket-io:  undefined ()
    zone.js/zone-patch-socket-io.min:  undefined ()
    zone.js/zone-patch-user-media:  undefined ()
    zone.js/zone-patch-user-media.min:  undefined ()
  npmGlobalPackages:
    npm: 7.19.0
    truffle: 5.3.11
    yarn: 1.22.10
```

### Describe the bug

Following the getting starter guild for Angular I am getting the following error. This should be fixed as I don't know if t he crypto lib is required or not by amplify

```sh
Build at: 2021-07-02T05:39:19.626Z - Hash: a2b97afd082645cf4ed2 - Time: 514ms

./node_modules/crypto-js/core.js:43:22-39 - Warning: Module not found: Error: Can't resolve 'crypto' in '/home/yadav/dev/tmp/amplify-app/node_modules/crypto-js'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```

### Expected behavior

Build with zero warnings.

### Reproduction steps

1. ng new demoapp
2. follow steps to setup amplify for angular (using version 12)
3. build app, see breaking change warning error.

### Code Snippet

```javascript
// Put your code below this line.

```

**Comment by hisham** [comment] 2021-07-02 23:20
+1. Upgrading existing angular 11 app to 12 and just ran into this issue. This is same issue as https://github.com/aws-amplify/amplify-js/issues/7185

**Comment by hisham** [comment] 2021-07-03 20:28
This warning seems benign btw. The app works just fine and we use this amplify lib for cognito + rest api (api gateway) + graphql + s3.

**Comment by FrapperColin** [comment] 2021-07-05 09:15
Got the same warning, even with angular 11, I have only two packages "@aws-amplify/auth" and "@aws-amplify/core", feels like it come from upgrading "@aws-amplify/auth" from 3.4.33 to 4.0.1 but there is no changes in CHANGLOG so it might come from dependencies update ;
with "@aws-amplify/auth" 3.4.33 
`  "dependencies": {
    "@aws-amplify/cache": "4.0.1",
    "@aws-amplify/core": "4.0.1",
    "amazon-cognito-identity-js": "5.0.1",
    "crypto-js": "^4.0.0"
  },
`
with "@aws-amplify/auth" 4.0.1 
`
  "dependencies": {
    "@aws-amplify/cache": "4.0.3",
    "@aws-amplify/core": "4.0.3",
    "amazon-cognito-identity-js": "5.0.2",
    "crypto-js": "^4.0.0"
  },`

Please don't tell me to put browser : {crypto: false} in my package.json to remove this warning.

**Comment by tannerabread** [comment] 2023-01-17 21:39
Hi @rajinder-yadav, this should be resolved with the library in its current state, can you confirm if you are still experiencing this issue?

**Comment by rajinder-yadav** [comment] 2023-01-18 13:50
@tannerabread  I found a work-around and decided to stop using amplify. 
Someone will need to follow the getting started guide and see if the can complete it without error.
The latest version for Angular is v15.

**Comment by tannerabread** [comment] 2023-01-18 14:28
@rajinder-yadav Sorry that we could not resolve this before you stopped using amplify. I will try to run through the guide with the latest version of Angular. Thank you for your response and time opening this issue.

**Comment by tannerabread** [comment] 2023-01-18 15:39
Closing this as the problem seems to be resolved.

 I was unable to reproduce both with new version of angular/amplify and the versions listed in the original post. As this is an old issue, there have most likely been documentation improvements and library improvements since this was written. 

If anyone else is experiencing this issue feel free to comment here so we can re-open and explore further.

Thank you!

**Closed by tannerabread** 2023-01-18 15:39 UTC
Labels: Angular, pending-triage
