### ISSUE TITLE
Datastore Uncaught (in promise) Error: Connection handshake error     at WebSocket.r.onclose

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7154] opened 2020-11-10 02:20 UTC
Hi

Whenever i use Datastore on a PC with spotty internet connection, i get this error pretty quickly. It's tough to use Datastore like this, i thought it was supposed to help with offline/ spotty connections?

2.4566a7d0.chunk.js:2 [WARN] 40:16.12 DataStore - Sync error Connection failed: Connection handshake error
e._log @ 2.4566a7d0.chunk.js:2
e.warn @ 2.4566a7d0.chunk.js:2
error @ 2.4566a7d0.chunk.js:2
w @ 2.4566a7d0.chunk.js:2
O @ 2.4566a7d0.chunk.js:2
value @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
s @ 2.4566a7d0.chunk.js:2
Promise.then (async)
c @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
Ge @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
w @ 2.4566a7d0.chunk.js:2
O @ 2.4566a7d0.chunk.js:2
value @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
setTimeout (async)
e.socketDisconnected @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
error @ 2.4566a7d0.chunk.js:2
w @ 2.4566a7d0.chunk.js:2
O @ 2.4566a7d0.chunk.js:2
value @ 2.4566a7d0.chunk.js:2
error @ 2.4566a7d0.chunk.js:2
w @ 2.4566a7d0.chunk.js:2
O @ 2.4566a7d0.chunk.js:2
value @ 2.4566a7d0.chunk.js:2
error @ 2.4566a7d0.chunk.js:2
w @ 2.4566a7d0.chunk.js:2
O @ 2.4566a7d0.chunk.js:2
value @ 2.4566a7d0.chunk.js:2
error @ 2.4566a7d0.chunk.js:2
w @ 2.4566a7d0.chunk.js:2
O @ 2.4566a7d0.chunk.js:2
value @ 2.4566a7d0.chunk.js:2
(anonymous) @ 2.4566a7d0.chunk.js:2
t._errorDisconnect @ 2.4566a7d0.chunk.js:2
o.awsRealTimeSocket.onclose @ 2.4566a7d0.chunk.js:2
2.4566a7d0.chunk.js:2 [DEBUG] 40:16.14 AWSAppSyncRealTimeProvider - Error while unsubscribing undefined
2.4566a7d0.chunk.js:2 [DEBUG] 40:16.15 AWSAppSyncRealTimeProvider - Error while unsubscribing undefined
2.4566a7d0.chunk.js:2 [DEBUG] 40:16.17 AWSAppSyncRealTimeProvider - Error while unsubscribing undefined
2.4566a7d0.chunk.js:2 Uncaught (in promise) Error: Connection handshake error
    at WebSocket.r.onclose (2.4566a7d0.chunk.js:2)

**Comment by rpostulart** [comment] 2020-11-10 04:40
I had the same, I believe I have removed the node modules and and .lock files and did a reinstall

**Comment by mchitson** [comment] 2020-11-10 11:39
i am already using the latest versions. i don't think that's the solution.

**Comment by amhinson** [comment] 2020-11-11 17:52
This appears to be a duplicate of https://github.com/aws-amplify/amplify-js/issues/6488, so I'll close this for now so we can focus on the other issue.

**Closed by amhinson** 2020-11-11 17:52 UTC
Labels: DataStore, to-be-reproduced
