### ISSUE TITLE
Angular Material input not behaving as expected

### ISSUE THREAD

**Issue by simonreitinger** [aws-amplify/amplify-js#6388] opened 2020-07-22 08:19 UTC
**Describe the bug**
I have an Angular 10 application. When I try to implement Amplify, `<input matInput>` is not behaving as expected anymore.

**To Reproduce**
1. `npm install @aws-amplify/ui-angular aws-amplify`
2. Configure Amplify (does not really matter for this problem)
2. Use this HTML file
```html
<amplify-authenticator *ngIf="authState !== 'signedin'" username-alias="email"></amplify-authenticator>
<mat-form-field>
    <mat-label>Value</mat-label>
    <input matInput type="text" [(ngModel)]="value">
</mat-form-field>
```
4. The inputs are not reactive anymore and the placeholder is overlapping with the content.

**Expected behavior**
The placeholders should behave normally and animate just like the default Angular material inputs.

**Screenshots**
Actual:
![Bildschirmfoto 2020-07-22 um 10 14 37](https://user-images.githubusercontent.com/26705426/88152434-4ce17180-cc04-11ea-9493-e6e2e1015d05.png)

Expected:
![Bildschirmfoto 2020-07-22 um 10 15 14](https://user-images.githubusercontent.com/26705426/88152443-4f43cb80-cc04-11ea-9aa5-15d618a069b8.png)

**Comment by jordanranz** [comment] 2020-07-22 18:13
Hi @simonreitinger, do you have a sample repository we could use to reproduce this?

**Comment by simonreitinger** [comment] 2020-07-22 20:49
Hey @jordanranz! I just created a dummy to reproduce it: https://github.com/simonreitinger/amplify-angular-dummy

**Comment by jordanranz** [comment] 2020-07-23 23:34
@simonreitinger, I was able to reproduce with your sample repo, thank you for finding this.

I am not 100% sure what is causing this though. It seems that the Material UI component when rendered inside of the `*ngIf` block does not detect changes on the `input` inside of the material form field. I'll keep investigating the root cause.

**Comment by simonreitinger** [comment] 2020-08-10 13:44
@jordanranz - Any updates on this?

**Comment by wlee221** [comment] 2020-12-22 03:13
Sorry for the late response. I was able to repro this with angular 10 (thanks for the repro!) and angular 11.

**Investigation**
Interestingly, this happens even when `*ngIf` condition does not depend on `authState` and `authData`:

*app.component.ts*
```ts
export class AppComponent {
  isAuthenticated: boolean = false;
  // ...
  ngOnInit(): void {
    const authStateChangeHandler = (authState, authData) => {
      this.isAuthenticated = true;
      this.ref.detectChanges();
    };
    onAuthUIStateChange(authStateChangeHandler);
  }
}
```
*app.component.html*
```html
<div *ngIf="isAuthenticated" class="App"> ... </div>
```
While `isAuthenticated` updates successfully and causes `<div *ngIf ='isAuthenticated'>` to render, `matInput` still fails to detect input / focus events. Because `authStateChangeHandler` body is called and updates `ref` as intended, I think this is a bug with `@angular/material` instead. It seems to have problem when it is conditionally rendered and component variable is updated by an external callback. I'll keep looking at this, but I am afraid there's not much we can do from Amplify side.

**Comment by wlee221** [comment] 2020-12-22 03:16
**Workaround**
I found that manually calling `this.ref.detectChanges()` fixes the behavior (at the cost of clean code):

*app.component.html*
```html
<input matInput type="text" (focus)="updateInput()" (input)="updateInput()" (blur)="updateInput()" [(ngModel)]="value" name="test">
```
*app.component.ts*
```ts
export class AppComponent{
  updateInput() {
    this.ref.detectChanges();
  }
}
```

**Comment by wlee221** [comment] 2021-01-06 00:05
Hi, I'll be closing this as workaround has been suggested and this is likely a bug with angular material.

**Closed by wlee221** 2021-01-06 00:05 UTC
Labels: Amplify UI Components, Angular, pending-close-response-required

**Comment by dudutwizer** [comment] 2021-02-22 21:48
Hi I'm facing the same bug but the workaround is not suitable , how can I manually call this.ref.detecChanges() from inside the container of the component ?

<img width="655" alt="image" src="https://user-images.githubusercontent.com/24310417/108774449-5c44e680-7568-11eb-8879-3a36408a3aae.png">

**Comment by wlee221** [comment] 2021-02-23 00:05
Hi @dudutwizer, have you tried to put the content inside `amplfiy-authenticator`:

```
<amplify-authenticator>
    <amplify-sign-out></amplify-sign-out>
    <app-instance-table></app-instance-table>
</amplify-authenticator>
```

Can you see if this resolves it?

**Comment by dudutwizer** [comment] 2021-02-23 09:29
Yes, the component is not showed at all.. I'm sure that what causing it is the *ngIf together with the new aws-amplify package .. I opened a new bug https://github.com/aws-amplify/amplify-js/issues/7794 with more details about the packages

**Comment by dudutwizer** [comment] 2021-02-24 09:00
(I meant yes, I can try it, but no it doesn't solve the issue)
