### ISSUE TITLE
React Native UI components do not look native on iOS and Android

### ISSUE THREAD

**Issue by vgribok** [aws-amplify/amplify-js#7896] opened 2021-03-06 23:58 UTC
**Is your feature request related to a problem? Please describe.**
AWS Auth React Native UI components have web-ish look & feel with AWS orange color schema used for buttons and other controls, instead of using native iOS and Android UI controls. This creates inconsistency with the rest of React Native app user experience.

**Describe the solution you'd like**
Either supply an additional theme (if applicable) that would ensure native rendering of UI components, or change default UI component implementation to use platform native controls (buttons, etc.)

**Describe alternatives you've considered**
1. Doing nothing and tolerating inconsistent UI experience with the rest of native controls.
2. Building two themes and write boilerplate logic applying appropriate theme at run time depending on the platform.

**Additional context**
N/A

**Comment by amhinson** [comment] 2021-03-08 20:57
Have you looked into supplying your own `theme` object as mentioned in the docs? The third example shows how you can do that with React Native: https://docs.amplify.aws/ui/customization/theming/q/framework/react-native#customize-ui-theme

**Comment by iartemiev** [comment] 2021-04-12 18:26
@vgribok,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:26 UTC
Labels: Amplify UI Components, React Native, feature-request, pending-close-response-required

**Comment by vgribok** [comment] 2021-04-12 19:30
The suggested solution was for a workaround. The idea of the original post was to prod the amplify maintainers to do native ui by default. It would be great if Amplify at least stated their design vision for having generic non-native ui in otherwise native ui apps.
