### ISSUE TITLE
Version dependency used in amplify: crypto-browserfy not safe according to snyk

### ISSUE THREAD

**Issue by stephannagel** [aws-amplify/amplify-js#1742] opened 2018-09-25 15:13 UTC
Version dependency used in amplify not deemed safe by snyk. Snyk claims that crypto-browserfy needs to be updated. See screenshot for more info.

![screen shot 2018-09-25 at 17 03 44](https://user-images.githubusercontent.com/11136860/46023863-df3a8c00-c0e5-11e8-942c-9701ebd6c7d9.png)

**Comment by mlabieniec** [comment] 2018-09-25 15:40
Duplicate of #1381

**Closed by mlabieniec** 2018-09-25 15:40 UTC

**Comment by stephannagel** [comment] 2018-09-25 17:15
Different version of amplify and a newer version of crypto-browserfy... Not sure if you can say it's a duplicate.
