### ISSUE TITLE
TypeScript improvements for the API module

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#3877] opened 2019-08-20 15:09 UTC
**Is your feature request related to a problem? Please describe.**
currently making graphql queries/mutations with the API module with TypeScript does not actually give you the benefit of TypeScript which is types and autocomplete

**Describe the solution you'd like**
Currently there is no return type (`any`) for `API.graphql()` so there is no autocomplete which is a bit annoying when working with a lot of data. So what I would like is to somehow involve the `API` file which is created by AppSync codegen and make the `graphql` function generic, so foe example it would like this - 
```
import API, { graphqlOperation } from 'aws-amplify'
import { getUserQuery } from 'src/API`

API.graphql<getUserQuery>(graphlOperation(query)).then(res => {
  // the res variable is automatically typed!
})
```

**Describe alternatives you've considered**
Currently setting all my results returned from `API.graphql()` to `any`

**Comment by elorzafe** [comment] 2019-08-20 18:50
@idanlo thanks for your feedback, I will label this as feature-request.

**Comment by buggy** [comment] 2019-08-21 01:36
@idanlo @elorzafe this is a duplicate of #3842

**Comment by rakannimer** [comment] 2019-08-21 04:52
I needed this too and implemented it in https://github.com/aws-amplify/amplify-js/pull/3748

**Comment by ericclemmons** [comment] 2020-10-16 23:51
When using `API.graphql` with TypeScript, this appears addressed:

```ts
import { listPosts } from "src/graphql/queries"

const { data } = (await API.graphql(
  graphqlOperation(listPosts)
)) as GraphQLResult<ListPostsQuery>;
```

**Comment by sw-yx** [comment] 2020-10-17 00:02
i dont know that we can call it a day just telling everybody to use assertions? per https://github.com/aws-amplify/amplify-js/issues/6369 @manueliglesias seemed interested in evolving the API further. this is a thing everybody wants and the less manual overhead the better.

**Comment by ericclemmons** [comment] 2020-10-19 18:50
@sw-yx I agree.

To state the ask another way:

> Not having to pass in the types at all would be amazing!
> – https://github.com/aws-amplify/amplify-js/issues/6369#issuecomment-668730982

There's an ask to export `GraphQLAPI` (instead of just `API`) for better tree-shaking.  We could expand that to support `GraphQLAPI.subscribe(...)`, with TypeScript knowing that'll return an observer.

**Comment by gruckionvit** [comment] 2020-11-24 18:19
This article has a nice wrapper for supporting typescript

https://dev.to/rmuhlfeldner/how-to-use-an-aws-amplify-graphql-api-with-a-react-typescript-frontend-2g79

**Comment by sw-yx** [comment] 2020-11-24 20:18
so ugly. we need to properly support typescript.

**Comment by gruckionvit** [comment] 2020-11-24 20:20
> so ugly. we need to properly support typescript.

100% agree.

**Comment by cwomack** [comment] 2023-11-16 22:05
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Closed by cwomack** 2023-11-16 22:05 UTC
Labels: feature-request, API
