### ISSUE TITLE
[ERROR] AWSPinpointProvider - record event failed.  NetworkingError: Network Failure

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#5336] opened 2020-04-08 19:55 UTC
I just received this error when reloading my react native app. No user in my user pool can sign in. 

`[ERROR] AWSPinpointProvider - record event failed. ", {"message":"Network Failure","code":"NetworkingError","time":"2020-04-08T10:07:43.349Z","region”:”us-west-1","hostname":"pinpoint.us-west-1.amazonaws.com","retryable":true}`

Under my role, this is the PinPoint policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:GetUserEndpoints"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:*:182376172983:apps/847f98933e564f14b8501c84758a2s73*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

Can someone please help ASAP!

**Comment by sammartinez** [comment] 2020-04-08 20:52
@chai86 Can you provide a code snippet along with versions of Amplify you are using? Thanks ahead of time.

**Comment by chai86** [comment] 2020-04-08 21:16
@sammartinez The below code is on my main `App.js` screen. The thing is is that i never reach it, because i'm on the login screen to sign in (the first page of my app) and this is where i'm get the error (without attempting even logging in!).

I'm using `"aws-amplify": "^1.1.29"`

When in App.js all i do is this:


```
import Amplify, { API, graphqlOperation, Auth, Analytics } from 'aws-amplify';

componentDidMount = async () => {
    AppState.addEventListener('change', this.onAppStateChange) 
}

 //Tracks when app is brought to fore
  onAppStateChange(appState) {    
    if(appState === 'active') {
      Analytics.record('User Foreground')
    }
  }
```

**Comment by sammartinez** [comment] 2020-04-09 16:24
@chai86 You are using a previous version of `aws-amplify`, we just released version 3 last week. Is there anyway you are able to upgrade to at least version 2 and see if you receive the same error message?

**Comment by chai86** [comment] 2020-04-09 17:09
@sammartinez this has been the most stable version i've tried, and i can't jeopardise a 1 year project and have it fail 😔. Is there any way to identify what the root of the problem is before we assume its Amplify version related?

**Comment by sammartinez** [comment] 2020-04-09 17:22
@chai86 Can you provide us more about the `package.json` you have? And what version of Amplify CLI you are using. For clarity on this, we are moving away from previous versions with them moving to maintenance mode so this is the reason for asking on the major version bump. If you have a gist you can provide that is your code we can take a look into it.

**Comment by chai86** [comment] 2020-04-09 17:32
Thanks @sammartinez, here's what i'm working with below:

```
{
  "name": "ProjectName",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "amazon-cognito-identity-js": "^3.0.15",
    "aws-amplify": "^1.1.29",
    "aws-amplify-react-native": "^2.1.13",
    "buffer": "^5.2.1",
    "link": "^0.1.5",
    "react": "16.8.3",
    "react-native": "^0.59.10",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-picker": "^0.27.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.2",
    "react-native-video-processing": "git+https://git@github.com/shahen94/react-native-video-processing.git",
    "react-navigation": "^3.0.7"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
```

I believe that i'm using `@aws-amplify/cli@4.11.0` in my terminal (if you know the command to check version i can double check, but i'm sure this is it). Any other info needed....i'm all ears 👂🏼

**Comment by amhinson** [comment] 2020-04-09 20:49
@chai86 I'm trying to reproduce the issue you're seeing with the same versions of `react-native`, `aws-amplify`, `aws-amplify-react-native`, and `amazon-cognito-identity-js` but no luck so far.

- Did this error happen all of a sudden without any other changes on your end?

-  Is that policy for auth or unauth users?

Also, this previous issue seems to be giving the same error you're seeing #2908, in case you wanted to explore some of the solutions users tried in there.

**Comment by chai86** [comment] 2020-04-09 21:08
@amhinson I tried to follow some simple steps in that case (#2908) yesterday, but it was of little use. The policy should be for only authorised users. I didn't get to the root of the issue but i did run an experiment. I tried my react native project on an older machine, and the project runs without this error. I believe that my current machine (a work machine) may have had put a block on outbound/inbound requests, which could explain the spawning of this error.

What i haven't figured out whether PinPoint is not allowed to reach my app or vice versa. Any ideas?

But for now please feel free to close the case. Thanks

**Comment by amhinson** [comment] 2020-04-09 21:11
Ah ok, well I'm glad you were able to get things working! 👍 

I'm not too sure on your Pinpoint question, but feel free to open another issue if you're seeing problems.

**Closed by amhinson** 2020-04-09 21:11 UTC
Labels: Analytics, React Native, to-be-reproduced
