### ISSUE TITLE
Multiple Subscriptions in Connect

### ISSUE THREAD

**Issue by visusnet** [aws-amplify/amplify-js#3912] opened 2019-08-25 11:58 UTC
**Is your feature request related to a problem? Please describe.**
AppSync currently supports having multiple root fields in subscriptions, e.g.:
```javascript
const onCreateOrUpdateOrDeleteTodo = `
subscription OnCreateOrUpdateOrDeleteTodo {
    onCreateTodo {
        id
        name
        description
    }
    onUpdateTodo {
        id
        name
        description
    }
    onDeleteTodo {
        id
        name
        description
    }
}
`;
```
This is great if you have a list of todos and want to get all updates:
```javascript
<Connect
    query={graphqlOperation(listTodos)}
    subscription={graphqlOperation(onCreateOrUpdateOrDeleteTodo)}
    onSubscriptionMsg={(prev, data) => {
        const todo = data.onCreateTodo || data.onUpdateTodo;
        if (todo) {
            prev.listTodos.items = updateOrPush(
                prev.listTodos.items,
                todo
            );
        } else if (data.onDeleteTodo) {
            prev.listTodos.items = prev.listTodos.items.filter(
                t => t.id !== data.onDeleteTodo.id
            );
        }
        return prev;
    }}>
    {({ data, loading, error }) => data.listTodos.items.map(todo => <Todo todo={todo} />)}
</Connect>
```
However, this is actually not supported by the GraphQL spec:
https://graphql.github.io/graphql-spec/June2018/#sec-Single-root-field
This might complicate things, e.g. the Amplify AppSync Simulator uses a GraphQL implementation that does follow this limitation. If you have previously used multiple root fields in subscriptions like in the example above, you cannot use `amplify mock`. This is not a problem with the AppSync simulator. It behaves as expected.

**Describe the solution you'd like**
In order to subscribe to multiple updates, the `Connect` component should accept multiple subscriptions.

**Describe alternatives you've considered**
- Nest multiple `Connect` components... This has serious implications that increase code complexity by multiple orders of magnitude.

**Additional context**
I have attached an untested backward-compatible patch which might help.
[Connect.patch.txt](https://github.com/aws-amplify/amplify-js/files/3538097/Connect.patch.txt)

**Comment by stdmn** [comment] 2019-10-31 22:03
I'm not sure if this is related, but I've noticed with multiple nested Connect components, I get inconsistent results from the child Connect subscriptions. The query is working but the subscription only receives a message intermittently.

A multiple-top-level subscription would be ideal (specifically for all mutations).

**Comment by visusnet** [comment] 2020-02-05 18:44
@stdmn I have posted the component that we are currently using here: https://github.com/aws-amplify/amplify-js/issues/4813#issuecomment-582106596

**Comment by stdmn** [comment] 2020-02-06 14:57
Thanks, @visusnet. I'll take a look

**Comment by sammartinez** [comment] 2020-03-17 19:09
@visusnet Are you fine if I mark this issue as a duplicate in favor of the above comment you linked?

**Comment by visusnet** [comment] 2020-03-17 19:23
@sammartinez Yes, sure. :)

**Comment by sammartinez** [comment] 2020-03-17 19:43
Marking this as a duplicate of the above comment in favor of #4813. Resolving

**Closed by sammartinez** 2020-03-17 19:43 UTC
Labels: AppSync, duplicate
