### ISSUE TITLE
Amplify GraphQL returns null while DynamoDB table has items 

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-js#11395] opened 2023-05-20 16:07 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d365ce6y79hx7o

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds

### Question

The bug
graphQL listItems subscriptions is triggered correctly by fail to return any data from dynamoDB because of null values for automatically created 'createAt' and 'updatedAt' fields.

Error message (in browser console): "Cannot return null for non-nullable type: 'AWSDateTime' within parent 'TourBooking' (/listTourBookings/items[0]/updatedAt"

Important note: this error only gets thrown when I create new items (TourBooking) from lambda function (using that flow: form gets submitted  to an api gateway endpoint which then invokes a lambda function that puts the new item to DynamoDB (using PutItem) and does other server-side stuff). The items get successfully submitted to dynamodb and all of the other logic in lambda gets processed successfully. however, when I try to fetch data (using GraphQL query: listTourBookings) it returns null for the items that are created using this flow while dynamodb table has items. 

if, instead, I create the new items directly through GraphQL query (createTourBooking) without passing the data to lambda, items get successfully submitted to dynamodb and get successfully returned when I fetch them using (listTourBookings) query.
 
in the attached screenshots of the error, you will see that two items were successfully returned and three items were returned as null. the two successfully returned items are the items that have been created directly using createItem without being passed to lambda. while the null returned  items are the ones that have been created through lambda. ALL THE FIVE ITEMS DO EXIST IN DYNAMODB.

one more thing: I noticed that in the items that are created via lambda don't have an "owner" record which is auto created in the items that have been created using createItem.

screenshots of the error attached.

<img width="1031" alt="Screenshot 2023-05-20 at 5 39 16 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/110037539/9d207ae4-d838-4ce0-acb6-599370f5fbfa">
<img width="1030" alt="Screenshot 2023-05-20 at 5 56 23 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/110037539/26a32d76-d922-404d-8403-c381a37beb05">

**Comment by chrisbonifacio** [comment] 2023-05-22 19:12
Hi @atef-abdellatif 👋 would you be able to share the Lambda code where you are creating the items?

Also, just so I understand what the issue is, the way the issue was worded was "graphQL listItems subscriptions is triggered correctly by fail to return any data ". Does this mean it is behaving as you expect? If the issue is that records are being returned as `null` because of missing required fields, have you tried simply setting a value for those fields where they are being created in the Lambda?

**Comment by atef-abdellatif** [comment] 2023-05-22 21:03
Hey Chris, 

Thank you for your reply!

To understand the issue, let me briefly walk you through the flow I’m using. I have a lambda function that when gets invoked, it processes payments using Square and if the payment is successful, it then creates a new booking in dynamodb (using PutItem), it then sends a success email to the user using AWS SES. This works perfectly fine and the function processes payments, creates new bookings in dynamodb and sends emails. 

The problem, which is the issue that I’m facing, is when I try to fetch the new created bookings using graphQL listItems subscription it returns null for each item (booking) in the Booking table. However, the bookings exist in dynamodb and their values are fully and correctly populated. For example, if the Booking table has 10 items (bookings), the listItems subscription returns an array of 10 nulls in stead of the actual objects that hold bookings data. I hope this makes sense.

On the other hand, If I use a different flow where I just use an API to create bookings in dynamoDB directly without having to pass the data to lambda to process payments and send emails, the new created bookings get successfully fetched when the graphQL listItems sub gets triggered. 


Let me know if there’s anything else I provide you with to better understand the issue.

Best,
Atef

**Comment by atef-abdellatif** [comment] 2023-05-23 15:26
Hi Chris,

Thanks for getting back to me!

Here is screenshot of the cod where the PutItem is triggered.

￼

**Comment by chrisbonifacio** [comment] 2023-05-24 01:51
@atef-abdellatif I think you might've replied via email, the uploaded screenshot doesn't show on your GitHub comment unfortunately.

**Comment by atef-abdellatif** [comment] 2023-05-24 01:56
sorry, here is the code:
*********************

const AWS = require('aws-sdk');
const ses = new AWS.SES();
const docClient = new AWS.DynamoDB.DocumentClient();
// Set the region 
AWS.config.update({region: 'REGION'});
// Create DynamoDB service object
var ddb = new AWS.DynamoDB({apiVersion: '2012-08-10'});


const { Client } = require('square');
const { randomUUID } = require('crypto');



// Set Square Connect credentials and environment
const {paymentsApi} = new Client({
    accessToken: "NY ACCESS TOKEN",
    environment: "sandbox",
}); 

exports.handler = async (event) => {
    let body = JSON.parse(event.body);
    const data = body.data;
    // ===== POST BOOKING ===== //
    const tourBooking = {
        TableName: "TABLE NAME",
        Item: {
            id: randomUUID(),
            createdAt: new Date().toISOString(),
            ...data
        }
    }
    async function putItem(paramsObj) {
        try {
            const booking = await docClient.put(paramsObj).promise()
            return booking 
        } catch (err) {
            return err
        }
    }
    const newBooking = await putItem(tourBooking);
    // ===== PROCESS PAYMENT ===== //
    const { result } = await paymentsApi.createPayment({
        // Payment processing logic goes here
    }) 
    // Update booking with payment data
    const updatedTourBooking = {
        TableName: "TABLE NAME",
        Item: {
            ...tourBooking.Item,
            paymentStatus: result.payment.status === "COMPLETED" ? "paid" : "unpaid",
            Payment: {
                amount: parseInt(result.payment.approvedMoney.amount),
            },
        }
    }
    const updatedBooking = await putItem(updatedTourBooking);
    // ===== SEND SMS ===== //
    // SEND EMAIL LOGIC GOES HERE
    return {
        statusCode: 200, 
        body: JSON.stringify(result),
    };
};

**Comment by atef-abdellatif** [comment] 2023-05-24 01:57
![Uploading Screenshot 2023-05-23 at 5.25.50 PM.png…]()

**Comment by atef-abdellatif** [comment] 2023-05-24 02:17
<img width="996" alt="Screenshot 2023-05-23 at 5 25 50 PM" src="https://github.com/aws-amplify/amplify-js/assets/110037539/2f098079-c655-47e1-84a5-288e7fe7e4e8">

**Comment by chrisbonifacio** [comment] 2023-05-24 17:48
Thank you @atef-abdellatif.

So, I see that you are manually setting the `createdAt` field but I don't see that you are also setting the `updatedAt` field. The error suggests that the records are specifically missing that field. Are you certain they have a timestamp for `updatedAt`?

If they do, then the issue might be with the request. You mentioned that there might be a subscription but you also said listTourBookings. Are you getting the data via a query or a real-time subscription?

**Comment by atef-abdellatif** [comment] 2023-05-25 18:11
Sorry about the confusion! I’m actually getting the data via listTourBookings query. I’ve no subscriptions set up on my app. On May 24, 2023, at 19:48, Chris Bonifacio ***@***.***> wrote:﻿
Thank you @atef-abdellatif.
So, I see that you are manually setting the createdAt field but I don't see that you are also setting the updatedAt field. The error suggests that the records are specifically missing that field. Are you certain they have a timestamp for updatedAt?
If they do, then the issue might be with the request. You mentioned that there might be a subscription but you also said listTourBookings. Are you getting the data via a query or a real-time subscription?

**Comment by atef-abdellatif** [comment] 2023-05-25 22:08
Hey Chris,

I added the updatedAt field and now everything is working as expected. Thank you so much!

**Comment by david-mcafee** [comment] 2023-06-12 22:46
Closing this ticket. @atef-abdellatif if you have any further questions or concerns, please let us know!

**Closed by david-mcafee** 2023-06-12 22:46 UTC
Labels: question, GraphQL, transferred, pending-response
