### ISSUE TITLE
PasswordResetRequiredException not handled in the amplify-authenticator component 

### ISSUE THREAD

**Issue by LBPlayer** [aws-amplify/amplify-js#4890] opened 2020-02-11 16:40 UTC
**Describe the bug**

PasswordResetRequiredException is thrown and not handled if a user is required to rest their password (account status - RESET_REQUIRED), causing multiple verification emails to be sent.

**To Reproduce**

1. Click the 'Reset password' for a Cognito user via the Cognito section of the AWS Console. This will send the user a verification pin via email
2. Use the amplify-authenticator component and enter the username password for the same Cognito user. A PasswordResetRequiredException is thrown. An error message does appear but in order to log in, they have to click the reset password link. This then sends another verification code via email. There is no way of getting to the part of the component that requires a user to enter the pin they received in the email.

**Expected behavior**

I would have expected the user to be shown a verification pin text box along with a new password box and not have to trigger another verification email instead of seeing the error message. See below 

![Screenshot 2020-02-11 at 16 02 49](https://user-images.githubusercontent.com/9657993/74254415-53c89780-4ce8-11ea-98b1-fca39cdaba5d.png)

The user only sees the 'Password reset required for the user' error message if they have provided the correct username/password.

Is there a way to handle this and show the reset password code and email screen without having to do a custom auth?

Here are some screenshots of the UI and error
![Screenshot 2020-02-13 at 16 03 58](https://user-images.githubusercontent.com/9657993/74429269-8d1d1680-4e52-11ea-861e-3da8f219b913.png)

![Screenshot 2020-02-11 at 16 03 58](https://user-images.githubusercontent.com/9657993/74254427-562af180-4ce8-11ea-8743-3ba7de342e45.png)

Thanks in advance for any help :)

**Comment by elorzafe** [comment] 2020-02-14 16:51
@LBPlayer which framework are you using?

**Comment by LBPlayer** [comment] 2020-02-14 17:19
Hi @elorzafe I am using Angular

**Comment by tofarr** [comment] 2021-03-16 23:22
Does anybody else get tired of that damn bot closing issues with cognito? I mean, there are so many issues that are still a problem - and have been going back years. The reporters inevitably eventually give up, time passes, and the bot closes the issue. Rinse and repeat. It doesn't inspire confidence in reporting a bug. What's the point? They'll just ignore it anyway until the bot closes it.

**Comment by theonlyway** [comment] 2021-04-16 02:34
I just encountered this and this isn't just limited to the Amplify authenticator component. In my particular case I've got a custom authentication UI and am just handling the entire process myself using the API so it's really just an issue with the `signIn` method.

Example:

```
await Auth.signIn(username, password)
            .then(user => handleAuthResponse(user))
            .catch(error => {
                switch (error.code) {
                    case "NotAuthorizedException":
                        break;
                    case 'PasswordResetRequiredException':
                        break;
                    default:
                }
            })
```

- Removed some lines in the above example for posterity

It doesn't generate the user object it just generates an exception which then falls to the catch method with the following object
```
{
  code: "PasswordResetRequiredException",
  name: "PasswordResetRequiredException",
  message: "Password reset required for the user",
}
```
Now the users password in this particular case was reset via the congito console and a token verification token was sent to the users email address to aid in resetting the password. Now looking over the API documentation [here](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#changepassword) there isn't any methods that support taking a verification code + a new password. In addition since the `signIn` method flat-out generates an exception we don't have the `CognitoUser` object that we would normally have but reading over the Cognito API for `ChangePassword` [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ChangePassword.html) we might not actually need it.

**Comment by sammartinez** [comment] 2021-05-18 20:22
@LBPlayer,

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 20:22 UTC
Labels: Amplify UI Components, Auth

**Comment by sharmilathirumalai** [comment] 2021-05-21 22:41
Hi,

I'm facing the same issue in Vue.  

**Description**

User ends up with two verification codes on trying to initiate password reset from admin side.


**Steps To Reproduce**
1.  In AWS Cognito console, click "Reset Password" for a user with verified email address. The account status now would change to RESET_REQUIRED. (Note: A verification code will be now sent to the registered email of this user)
2. Enter username and password of the same user in login screen built using amplify-authenticator component. Below is how the authenticator is structured in the code

``` 
<amplify-authenticator>
      <amplify-sign-in  slot="sign-in">
      </amplify-sign-in>
 </amplify-authenticator>
```
3.  Now the user is taken to reset screen where the email has to be entered as below. This in turn introduces the behaviour of generating verification code for the second time.
<img width="332" alt="Screen Shot 2021-05-21 at 3 24 08 PM" src="https://user-images.githubusercontent.com/17615189/119203721-9a0eb980-ba48-11eb-83a1-2ecd17d311b1.png">

**Package.json**

```{
  "name": "test-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/auth": "^3.4.22",
    "@aws-amplify/core": "^3.8.14",
    "@aws-amplify/interactions": "^3.3.22",
    "@aws-amplify/storage": "^3.3.22",
    "@aws-amplify/ui-components": "^1.0.1",
    "aws-sdk": "^2.788.0",
    "core-js": "^3.6.5",
    "primeicons": "^4.1.0",
    "primevue": "^3.1.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-beta.13"
  },
  "devDependencies": {
    "@vue/babel-plugin-jsx": "^1.0.4",
    "@vue/cli-plugin-babel": "~4.5.8",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "^4.5.13",
    "@vue/compiler-sfc": "^3.0.11",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/test-utils": "^2.0.0-beta.10",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.0",
    "sass": "^1.26.11",
    "sass-loader": "^10.0.3",
    "vue-jest": "^5.0.0-alpha.8",
    "vue-loader": "^16.1.2"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ],
  "resolutions": {
    "netmask": "2.0.1"
  }
}
```

Any help on this much appreciated!

**Comment by MattWlodarski** [comment] 2021-09-03 14:41
Can this be reopened? I'm having the same issue in which the user gets sent two verification emails instead of one.

**Comment by rabbitXIII** [comment] 2021-11-11 00:25
Can we get an update here?  I'm writing my own react login component using `aws-amplify` and see a similar issue.  

`FORCE_PASSWORD_CHANGE` account status does not throw an error when the user logs in, so we have a CognitoUser to continue with a password reset flow using `Auth.completeNewPassword`.  
`RESET_REQUIRED` account status from the Cognito console UI throws an error when the user logs in, so no CognitoUser is returned. 

How should we complete the password reset process in this case?

**Comment by chrisbonifacio** [comment] 2021-11-11 04:20
@rabbitXIII If you're not using the ui components, which have been moved to their own repo, please open a new issue in this repo with your environment information and steps to reproduce the issue.

For anyone experiencing this issue with the UI components, I'm going to transfer this issue over to the UI repo and re-open for visibility. I'll also reach out to the UI team tomorrow to get some feedback.

**Comment by discobean** [comment] 2022-02-13 11:12
Hi I believe this needs to be reopened.  This a problem with aws-amplify.

If I do request a password reset via the cognito UI in aws console.  Next time the user logs in I receive a "PasswordResetRequiredException".

So the next amplify API call should be Auth.changePassword, however it requires a CognitoUser object & valid session.  And there is none given with the login PasswordResetRequiredException error.

At this point the user cannot login.

**Comment by CarolineFrost** [comment] 2022-03-09 19:11
@discobean -- I agree they should revisit how this code is structured. According to https://github.com/aws-amplify/amplify-js/blob/1795d461a5b6d2daee31d4e609d2d27fb5d37018/packages/aws-amplify-react/src/Auth/SignIn.jsx, you should treat the PasswordResetRequiredException as a "Forgot password" situation.

Once you reset a user's password in the console, AWS sends the code to the email and all you need to do is prompt the user to create a new password via `Auth.forgotPasswordSubmit(email, code, newPassword);`. No need to send an additional code. Hope this helps.

**Comment by discobean** [comment] 2022-03-10 22:43
> Once you reset a user's password in the console, AWS sends the code to the email and all you need to do is prompt the user to create a new password via `Auth.forgotPasswordSubmit(email, code, newPassword);`. No need to send an additional code. Hope this helps.

Thank you @CarolineFrost indeed it is ``Auth.forgotPasswordSubmit()`` makes sense now!
