### ISSUE TITLE
GraphQLError: adapter is not a function Next.js getInitialProps

### ISSUE THREAD

**Issue by ryanmalesic** [aws-amplify/amplify-js#4311] opened 2019-10-31 18:51 UTC
**Describe the bug**
GraphQLError: adapter is not a function
      at APIClass.<anonymous> (/Users/ryanmalesic/Projects/tdee-online/node_modules/@aws-amplify/api/dist/aws-amplify-api.js:5565:24)
      at step (/Users/ryanmalesic/Projects/tdee-online/node_modules/@aws-amplify/api/dist/aws-amplify-api.js:4733:19)
      at Object.throw (/Users/ryanmalesic/Projects/tdee-online/node_modules/@aws-amplify/api/dist/aws-amplify-api.js:4663:14)
      at rejected (/Users/ryanmalesic/Projects/tdee-online/node_modules/@aws-amplify/api/dist/aws-amplify-api.js:4625:32)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (interna

**To Reproduce**

Query in getinitialProps of a nextjs app

**Expected behavior**
It should query, not throw

**Comment by ryanmalesic** [comment] 2019-10-31 22:14
Doing more stack tracing, this seems to be an axios issue. I have put a discussion in there. I will close this if an axios fix can correct the issue

**Comment by jordanranz** [comment] 2019-11-01 22:05
Hey @ryanmalesic, is there an issue open to track the axios discussion?

**Comment by ryanmalesic** [comment] 2019-11-01 22:24
#https://github.com/axios/axios/issues/2507

**Comment by weizliu** [comment] 2019-11-09 00:41
Any updates? I ran into this issue too

**Comment by weizliu** [comment] 2019-11-11 23:46
Is the change in 1.2.4 already? I ran into the same issue while using 1.2.4 today.

**Comment by aliankarali** [comment] 2019-12-06 09:53
Still having this issue with `@aws-amplify/api@2.1.1` on server side. Axios issue is closed, I don't know if it is related to amplify or axios.

**Comment by simpleshadow** [comment] 2019-12-07 00:14
Getting the same error when running an `aws-amplify/api` query with Next.js (not in `getInitialProps`).

**Comment by simpleshadow** [comment] 2019-12-07 01:41
I got rid of the error using what I needed from. https://github.com/aws-amplify/amplify-js/issues/4305#issuecomment-552193872

**Comment by aliankarali** [comment] 2019-12-10 10:14
@simpleshadow,  thanks for the tip, I got it working by locking down the versions with resolutions as well.

**Comment by lambda0xff** [comment] 2019-12-20 14:09
Getting the same error with a Nuxt.js application after trying to upgrade aws-amplify to the latest (^2.2.1)

Please Amplify-JS team, show a little more love for SSR frameworks, they shouldn't be treated like afterthoughts.

**Comment by aliankarali** [comment] 2019-12-20 18:15
Forgot to mention that I get this error with express.js. it's not related to a specific ssr framework.

**Comment by Amplifiyer** [comment] 2020-01-07 02:42
I think I know the root cause. NuxtJs/NextJs are consuming the amplify library using the `main` field and not the `modules` field. Currently `main` field points to a webpack umd build which obviously shims the process variable preventing axios to determine the right environment.

I'll look into changing the main field to point to a cjs modules entry point. 

Anyone knows if there is a way for Nuxt/NextJs apps to read the modules field in library's package.json instead of main?

**Comment by Amplifiyer** [comment] 2020-01-08 00:34
@ryanmalesic @weizliu @aliankarali @lambda0xff @simpleshadow We have just merged in the fix. Can you please try with aws-amplify@unstable version and let us know if it's fixing the issue?

**Comment by lambda0xff** [comment] 2020-01-08 08:16
Seems to fix the issue for me.
`aws-amplify": "^2.2.1-unstable.21`

**Comment by rehanbabertkxel** [comment] 2020-01-08 10:22
@Amplifiyer , yes installing the unstable version resolved the adapter issue but when I use the Mock Server and call my lambda function which is using the unstable amplify version, it gives the following error:
"connect ECONNREFUSED 127.0.0.1:80"

I have read about this in another github issue:
"https://github.com/aws-amplify/amplify-js/issues/3934"

But don't know if its related. 
Can you please assist on how I can resolve this?

**Comment by rehanbabertkxel** [comment] 2020-01-08 10:32
Yes, it seems to resolve the issue @Amplifiyer .

**Closed** 2020-01-10 00:27 UTC
Labels: GraphQL, SSR
