### ISSUE TITLE
Invalid challenge code of sendCustomChallengeAnswer results in session not longer valid

### ISSUE THREAD

**Issue by stephannagel** [aws-amplify/amplify-js#5834] opened 2020-05-19 14:24 UTC
**Describe the bug**
I'm using the custom auth flow to login a user. This works perfectly with sign-in and then a successful sendCustomChallengeAnswer. When the user is entering an invalid challenge code - amplify provides me with the right feedback: "Incorrect username or password". 

However when I enter the right challenge code on the second attempt, amplify won't accept it anymore as it comes back with an "Invalid session for the user." message. The same applies for two trying to enter an invalide code twice. 

**Expected behavior**
I was expecting to use the sendCustomChallengeAnswer function again for the second and third attempt without leading to an "Invalid session for the user." message.

**Code Snippet**
`try {
      const challenge = await this.amplifyService.auth().sendCustomChallengeAnswer(cognitoUser, challengeResponse);
      console.log(challenge);
      return challenge;
    } catch (err) {
      console.log('Apparently the user did not enter the right code');
      return throwError(err);
    }`

I'm developing in Angular 9 and using the latest amplify-js libraries. I just quickly want to double check if I'm using the standard function of sendCustomChallengeAnswer correctly or not. I haven't read anywhere that I need to do something with the session before I sent a second attempt.

I hope you guys have an answer. Otherwise a workaround is to send the user another fresh code for every attempt. :)

**Comment by hiBrett** [comment] 2020-07-28 23:09
I'm running into the same issue, except with React.JS. The first time a user enters a wrong challenge code the error is as it should be "Incorrect username or password." Then, submitting either a correct or incorrect challenge code then gives the error "Invalid session for the user".

**Comment by akhil-kulkarni** [comment] 2020-12-28 07:08
@stephannagel Did you find a solution to this?

**Comment by dylan-westbury** [comment] 2021-02-01 01:49
I get the same issue as mentioned by @hiBrett 

1. Enter invalid code
2. Enter valid code (error showing is "Invalid session for the user")

**Comment by dylan-westbury** [comment] 2021-02-01 03:18
I was facing the issue but it appeared to be an issue with my code. If a user enters the incorrect code, they need to be sent a new one.

Here is the code for defineAuthChallenge trigger that solved my issue:

```
exports.handler = (event, context, callback) => {
  console.log('event', JSON.stringify(event));
  if (event.request.session.length === 0) {
    // new request to log in
    event.response.issueTokens = false;
    event.response.failAuthentication = false;
    event.response.challengeName = 'CUSTOM_CHALLENGE';
  } else if (
    event.request.session.length >= 3 &&
    event.request.session[ event.request.session.length - 1 ].challengeResult === false) {
    // user has incorrectly entered OTP 3 times
    event.response.issueTokens = false;
    event.response.failAuthentication = true;
  } else if (
    event.request.session.length >= 1 &&
    event.request.session[ event.request.session.length - 1 ].challengeName === 'CUSTOM_CHALLENGE' &&
    event.request.session[ event.request.session.length - 1 ].challengeResult === true
  ) {
    // user correctly entered OTP
    event.response.issueTokens = true;
    event.response.failAuthentication = false;
  } else {
    // user incorrectly entered OTP - resend code
    event.response.issueTokens = false;
    event.response.failAuthentication = false;
    event.response.challengeName = 'CUSTOM_CHALLENGE';
  }

  console.log('Finalised event:', JSON.stringify(event));
  callback(null, event);
};

```

**Comment by adamlbailey** [comment] 2021-11-10 16:25
Confirming that this is still an issue using (v4.3.4). I understand Auth.sendCustomChallengeAnswer should resolve to a CognitoUser assuming the Define Auth Challenge Lambda handler responds with `response.failAuthentication` set to False. This would enable the client to retry a challenge in the same session by calling Auth.sendCustomChallengeAnswer again with the CognitoUser object returned from the first attempt. However, Auth.sendCustomChallengeAnswer is throwing an exception (`NotAuthorizedException: Incorrect username or password.`) which effectively ends the session and forces us to start over.

The desired behavior of this pattern is detailed in the following aws blog post: https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/

**Comment by hkjpotato** [comment] 2021-11-12 21:25
@adamlbailey 
Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages --duplicates
```

Thanks ahead of time!

**Comment by adamlbailey** [comment] 2021-11-12 21:55
@hkjpotato absolutely and thank you for taking a look!

environment: 
```  
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 95.18 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 14.0.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.29.7
    create-react-native-app: 2.0.2
    eas-cli: 0.13.0
    expo-cli: 4.0.15
    npm: 6.14.8
    serverless: 2.63.0
 ```

package.json

```
{
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
        "start": "expo start",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "web": "expo start --web",
        "eject": "expo eject",
        "test": "jest --watchAll",
        "env:demo": "node scripts/set-environment.js demo",
        "env:sandbox": "node scripts/set-environment.js sandbox",
        "env:staging": "node scripts/set-environment.js staging",
        "env:production": "node scripts/set-environment.js production"
    },
    "jest": {
        "preset": "jest-expo"
    },
    "dependencies": {
        "@expo-google-fonts/lato": "^0.2.0",
        "@expo-google-fonts/poppins": "^0.1.0",
        "@expo/vector-icons": "^10.0.0",
        "@react-native-community/masked-view": "0.1.10",
        "@react-native-community/netinfo": "5.9.6",
        "@react-native-picker/picker": "^1.9.0",
        "@react-navigation/drawer": "^5.11.4",
        "@react-navigation/native": "^5.7.3",
        "@react-navigation/stack": "^5.9.0",
        "@typeform/embed-react": "^1.1.2",
        "aws-amplify": "4.3.4",
        "aws-amplify-react-native": "5.0.5",
        "aws-appsync": "^4.0.1",
        "date-fns": "^2.16.1",
        "expo": "~39.0.2",
        "expo-asset": "~8.2.0",
        "expo-constants": "~9.2.0",
        "expo-font": "~8.3.0",
        "expo-linking": "^1.0.1",
        "expo-splash-screen": "~0.6.2",
        "expo-status-bar": "~1.0.2",
        "expo-web-browser": "~8.5.0",
        "fast-deep-equal": "^3.1.3",
        "firebase": "^9.1.3",
        "graphql-tag": "^2.11.0",
        "react": "16.13.1",
        "react-dom": "16.13.1",
        "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
        "react-native-chart-kit": "^6.11.0",
        "react-native-elements": "3.0.0-alpha.1",
        "react-native-gesture-handler": "~1.7.0",
        "react-native-markdown-display": "^7.0.0-alpha.2",
        "react-native-reanimated": "~1.13.0",
        "react-native-safe-area-context": "3.1.4",
        "react-native-screens": "~2.10.1",
        "react-native-svg": "^12.1.1",
        "react-native-web": "^0.17.1"
    },
    "devDependencies": {
        "@babel/core": "~7.9.0",
        "@types/react": "~16.9.35",
        "@types/react-native": "~0.63.2",
        "@typescript-eslint/eslint-plugin": "^4.7.0",
        "@typescript-eslint/parser": "^4.7.0",
        "babel-plugin-transform-inline-environment-variables": "^0.4.3",
        "eslint": "^7.13.0",
        "eslint-config-prettier": "^6.15.0",
        "eslint-plugin-prettier": "^3.1.4",
        "eslint-plugin-react": "^7.21.5",
        "eslint-plugin-unused-imports": "^1.0.0",
        "jest-expo": "~39.0.0",
        "prettier": "^2.1.2",
        "typescript": "^4.0.5"
    },
    "private": true
}
```

Also, I have an aws premium support case open on this topic (case id: 9177186151). I believe there is a line out to an amplify SDM who was able to recreate.

Let me know how else I can be helpful.

**Comment by hkjpotato** [comment] 2021-11-16 16:28
Yes, I am trying to reproduce the issue. I think in my case it works fine in happy path (if the I provide the correct secret code in the response), but sometimes fails and I cannot retry. I need to restart the whole initAuth.

I will look more into it.

**Comment by adamlbailey** [comment] 2021-11-16 16:48
Thanks @hkjpotato that is consistent with my findings.

**Comment by hkjpotato** [comment] 2021-11-17 15:53
@adamlbailey sharing what I have found so far. I use postman to send out the request, and check the cloudwatch log of the "retry" on "VerifyAuthChallenge" lambda, and notice that even I change the "ChallengeResponses" in request, that lambda call does not receive any input. I need to check more on the cognito/ambda side, will keep you updated.
![Screen Shot 2021-11-17 at 10 52 12 AM](https://user-images.githubusercontent.com/9324418/142234326-ca535b9e-5fdd-4eeb-afa3-d8c1a6100036.png)

**Comment by hkjpotato** [comment] 2021-11-17 18:27
I find out the mistake I made for the testing, I am using the template here https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/ first to create those lambdas, and in the "CreateAuthChallenge" lambda I use the sample code regex to extract the previous secretCode 
` secretLoginCode = previousChallenge.challengeMetadata!.match(/CODE-(\d*)/)![1];`

This regex will only match digital number. However, during my testing I use alphabet code "kj-secret" and thus it fails to capture it in retry. When I use numerical number for secret code, it works for me.

Not sure if you are experiencing the same issue? 

Below is a rough diagram to help reason about this lamda flow
![external](https://user-images.githubusercontent.com/9324418/142260275-ba3f905f-8450-4c0c-b7b8-f34086e5c983.png)

**Comment by adamlbailey** [comment] 2021-11-17 18:46
@hkjpotato 

No, the issue I am referencing has to do with the DefineAuthChallenge lambda responding back to the client not to fail authentication and not to issue tokens. In this case, my understanding is we should be able to retry the challenge without needing to initiate a new authentication session. 

More specifically here, when I call Auth.sendCustomChallengeAnswer with the wrong challenge answer the DefineAuthChallenge lambda responds back to the client with the following:

```
{'version': '1', 'region': 'us-west-2', 'userPoolId': 'us-west-2_a3mEuktAv', 'userName': '51575f68-2a23-479f-9882-c21c12eda766', 'callerContext': {'awsSdkVersion': 'aws-sdk-unknown-unknown', 'clientId': '5v6oqesojup4oneudb5oiaef75'}, 'triggerSource': 'DefineAuthChallenge_Authentication', 'request': {'userAttributes': {'sub': '58550762-7a46-4687-942d-c8b35d0cafd3', 'cognito:user_status': 'FORCE_CHANGE_PASSWORD', 'cognito:phone_number_alias': 'REDACTED', 'phone_number_verified': 'True', 'phone_number': 'REDACTED'}, 'session': [{'challengeName': 'CUSTOM_CHALLENGE', 'challengeResult': False, 'challengeMetadata': None}]}, 'response': {'challengeName': 'CUSTOM_CHALLENGE', 'issueTokens': False, 'failAuthentication': False}}
```

Note `response.failAuthentication` is False. Which should tell  Auth.sendCustomChallengeAnswer to resolve to a CognitoUser object that is not authenticated. With which, we would be able to call Auth.sendCustomChallengeAnswer again with another challenge answer attempt. However, Auth.sendCustomChallengeAnswer is not resolving to a CognitoUser object; it is throwing an exception (`NotAuthorizedException: Incorrect username or password.`) which ends the session and prevents the client from attempting to answer the challenge again within the same session.

**Comment by hkjpotato** [comment] 2021-11-17 19:02
@adamlbailey I see, I will play around with the Amplify Auth category this afternoon. At least from Postman, I can see the retry working, so if anything wrong it should be an issue in the frontend code itself. Will update you with my finding.

If helpful, maybe we can hop on a discord call to pair programming on this sometimes later.

**Comment by hkjpotato** [comment] 2021-11-17 19:22
@adamlbailey when I use the Auth js code to test in browser the retry still works. Below is the call I made.
![Screen Shot 2021-11-17 at 2 17 52 PM](https://user-images.githubusercontent.com/9324418/142267923-9fa37104-4e44-467f-8cf8-0f0504114626.png)

 I am not sure if it is because our lambda triggers setting is different, I setup them manually as follow
![Screen Shot 2021-11-17 at 2 21 22 PM](https://user-images.githubusercontent.com/9324418/142268340-0d0c9c41-f04d-421d-bff6-2636630aa68e.png)

**Comment by adamlbailey** [comment] 2021-11-17 20:27
@hkjpotato that's helpful. Yes, that's what I'm expecting but not experiencing. Would be great to hop on a call so we can look together. I joined the amplify discord and sent you a friend request. Let me know how best to connect there.

**Comment by hkjpotato** [comment] 2021-11-17 21:01
@adamlbailey I accept the request on discord but it seems you are offline now. We can also sync sometimes 12PM-6PM EST tomorrow if you want.

**Comment by adamlbailey** [comment] 2021-11-17 23:05
Huge thank you to @hkjpotato for helping me figure this out!

My issue was that the CreateAuthChallenge lambda was not returning the triggering event after setting `response.privateChallengeParameters` **every time**. I was making the incorrect assumption that setting `response.privateChallengeParameters` once was sufficient for the entire session.

Here is that lambda with the appropriate correction made:

```python
def create_auth_challenge_handler(event: Dict[str, Any], _) -> Dict[str, Any]:
    """Handles the Cognito create auth challenge response trigger."""

    phone_number = event["request"]["userAttributes"]["phone_number"]
    session = event["request"]["session"]

    if not session:
        # no previous attempts; generate and send code
        code = text_code(phone_number)
    else:
        # previous attempts; will rechallenge on cached code from latest session
        code = session[-1]["challengeMetadata"]

    event["response"]["privateChallengeParameters"] = {"code": code}
    event["response"]["challengeMetadata"] = code
    
    return event
```

You'll also notice above that as we are setting `response.privateChallengeParameters` for each cycle in the session we need to cache it somewhere. That is done by setting it in `response.challengeMetadata` and retrieving it from the latest cycle in `request.session`.


Here is that lambda before the correction was made:

```python
def create_auth_challenge_handler(event: Dict[str, Any], _) -> Dict[str, Any]:
    """Handles the Cognito create auth challenge response trigger."""

    phone_number = event["request"]["userAttributes"]["phone_number"]
    session = event["request"]["session"]

    if not session:  # no previous attempts; send code
        event["response"]["privateChallengeParameters"] = {
            "code": text_code(phone_number)
        }
        return event

    last_session = session[-1]
    if (
        last_session.get("challengeResult") is False
    ):  # challenge not completed; return same challenge
        return event
```
 

Additionally, I was incorrect in understanding that Auth.sendCustomChallenge answer was resolving based on the response from the DefineAuthChallenge lambda. It is instead the CreateAuthChallenge lambda response which is best detailed in the diagram in this comment: https://github.com/aws-amplify/amplify-js/issues/5834#issuecomment-971848693.

**Comment by hkjpotato** [comment] 2021-11-18 15:38
@adamlbailey glad to help :)

**Closed** 2021-11-18 18:53 UTC
Labels: question, Auth, Angular

**Comment by hkjpotato** [comment] 2021-11-18 18:54
Close since the issue is being addressed. 
We can use this for future reference when similar issues occur.
