### ISSUE TITLE
Hub listen not triggering auth events

### ISSUE THREAD

**Issue by StriderHND** [aws-amplify/amplify-js#7555] opened 2021-01-13 17:20 UTC
**Describe the bug**
Hub not triggering auth events when using 'cognitoHostedUI' using Auth.federatedSignIn method to sign-in with google
the Hub doesn't trigger any response.

**Expected behavior**
Hub auth listener should  send a response data of what kind of auth event happened.

**Code Snippet**
```
useEffect(() => {
    const getCurrentUser = async () => {
      //code
    };

    Hub.listen('auth', (data) => {
      switch (data.payload.event) {
        case 'signIn':
        case 'cognitoHostedUI':
          getCurrentUser();
          break;
        case 'signIn_failure':
        case 'cognitoHostedUI_failure':
          // console.log('Sign in failure', data);
          break;
        default:
          break;
      }
    });
    return () => {
      Hub.remove('auth');
    };
  }, [dispatch, navigation]);
```

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-x:xxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxxx",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxx",
    "oauth": {
        "domain": "xxxxxxxxxxxxxx.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "xxxxxxx://",
        "redirectSignOut": "xxxxxxx://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "xxx-xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aws_cloud_logic_custom": [
        {
            "name": "xxxxxAPI",
            "endpoint": "https://xxxxxxxxxx.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        },
        {
            "name": "xxxxxxQueries",
            "endpoint": "https://xxxxxxxxxx.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        },
        {
            "name": "xxxxxxxxxapi",
            "endpoint": "https://xxxxxxxxxx.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        },
        {
            "name": "xxxxxxAPI",
            "endpoint": "https://xxxxxxxxxx.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "xxxxxxxxxxx-staging",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_mobile_analytics_app_id": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "aws_mobile_analytics_app_region": "us-east-1"}
```  

System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 31.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nodenv/shims/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nodenv/shims/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
    Safari: 14.0.3
  npmPackages:
    @aws-amplify/pushnotification: ^3.2.10 => 3.2.10 
    @babel/core: ^7.11.6 => 7.11.6 
    @babel/runtime: ^7.11.2 => 7.11.2 
    @react-native-community/async-storage: ^1.12.0 => 1.12.0 
    @react-native-community/checkbox: ^0.4.2 => 0.4.2 
    @react-native-community/eslint-config: ^1.1.0 => 1.1.0 
    @react-native-community/geolocation: ^2.0.2 => 2.0.2 
    @react-native-community/masked-view: ^0.1.10 => 0.1.10 
    @react-native-community/netinfo: ^5.9.7 => 5.9.7 
    @react-native-community/picker: ^1.8.0 => 1.8.0 
    @react-native-community/push-notification-ios: ^1.7.3 => 1.7.3 
    @react-native-firebase/analytics: ^7.6.4 => 7.6.4 
    @react-native-firebase/app: ^8.4.3 => 8.4.3 
    @react-navigation/bottom-tabs: ^5.8.0 => 5.8.0 
    @react-navigation/drawer: ^5.9.0 => 5.9.0 
    @react-navigation/native: ^5.7.3 => 5.7.3 
    @react-navigation/stack: ^5.9.0 => 5.9.0 
    amazon-cognito-identity-js: 4.5.5 => 4.5.5 
    aws-amplify: ^3.3.14 => 3.3.14 
    aws-amplify-react-native: ^4.2.10 => 4.2.10 
    babel-jest: ^25.1.0 => 25.5.1 
    eslint: ^6.5.1 => 6.8.0 
    geolib: ^3.3.1 => 3.3.1 
    jest: ^25.1.0 => 25.5.4 
    metro-react-native-babel-preset: ^0.59.0 => 0.59.0 
    moment: ^2.28.0 => 2.28.0 
    query-string: ^6.13.2 => 6.13.2 
    ramda: ^0.27.1 => 0.27.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-base64: ^0.1.0 => 0.1.0 
    react-native-config: ^1.3.3 => 1.3.3 
    react-native-config-reader: ^4.1.1 => 4.1.1 
    react-native-gesture-handler: ^1.8.0 => 1.8.0 
    react-native-hyperlink: 0.0.19 => 0.0.19 
    react-native-image-zoom-viewer: ^3.0.1 => 3.0.1 
    react-native-in-app-review: ^2.1.2 => 2.1.2 
    react-native-inappbrowser-reborn: ^3.4.0 => 3.4.0 
    react-native-input-credit-card: ^0.5.5 => 0.5.5 
    react-native-maps: ^0.27.1 => 0.27.1 
    react-native-picker-select: ^8.0.0 => 8.0.0 
    react-native-read-more-text: ^1.1.2 => 1.1.2 
    react-native-reanimated: ^1.13.0 => 1.13.0 
    react-native-safe-area-context: ^3.1.8 => 3.1.8 
    react-native-screens: ^2.11.0 => 2.11.0 
    react-native-simple-toast: ^1.1.2 => 1.1.2 
    react-native-splash-screen: ^3.2.0 => 3.2.0 
    react-native-svg: ^12.1.0 => 12.1.0 
    react-native-table-component: ^1.2.1 => 1.2.1 
    react-phone-number-input: ^3.1.7 => 3.1.7 
    react-redux: ^7.2.1 => 7.2.1 
    react-test-renderer: 16.13.1 => 16.13.1 
    redux: ^4.0.5 => 4.0.5 
    redux-saga: ^1.1.3 => 1.1.3 
    rn-range-slider: ^1.3.3 => 1.3.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.41.0
    dynamodb-admin: 4.0.0
    npm: 6.14.8

**Comment by StriderHND** [comment] 2021-01-19 14:36
Any news about this?

**Comment by 24601** [comment] 2021-01-21 21:11
We are also experiencing this after trying to work around issues in #4315 - where we workaround the issue introduced in a recent update, but this then occurs.

**Comment by 24601** [comment] 2021-01-21 21:39
Exact same code with 
```
    "@aws-amplify/auth": "^3.4.7",
    "@aws-amplify/ui-react": "^0.2.24",
    ```
   works no problem, Hub auth messages, auth works, everything is great (verified that these are the versions in package-lock.json and actually in node_modules in their package.json, these are the version strings, it is not as if they resolved to different versions, it is actually 3.4.7 and 0.2.24 respectively.
   ```
       "@aws-amplify/auth": "^3.4.17",
    "@aws-amplify/ui-react": "^0.2.34",
    ```
  nothing works.

**Comment by 24601** [comment] 2021-01-25 16:35
FYI @sammartinez - we can confirm that this occurs in non-SSR environments, too.

**Comment by sammartinez** [comment] 2021-01-25 16:41
> FYI @sammartinez - we can confirm that this occurs in non-SSR environments, too (not sure if the SSR label indicated SSR-only or that SSR is also affected, just want to be sure).

Thanks for this feedback @24601, I am marking it as also related to SSR with the label indication.

**Comment by elorzafe** [comment] 2021-01-25 22:20
Can you move `Hub.listener` on the top of the code not inside `useEffect`?

`useEffect` is not recommend to add `Hub.listener`

Let me know how it goes

**Comment by StriderHND** [comment] 2021-01-25 22:54
@elorzafe I've moved the `Hub.listener` as suggested. Still event been triggered

**Comment by elorzafe** [comment] 2021-01-25 22:56
@StriderHND Is this code inside of the entry point of the App?

**Comment by elorzafe** [comment] 2021-01-25 22:59
I successfully see the events in this react app I've just created.

`App.js`
```jsx
import logo from './logo.svg';
import './App.css';
import awsconfig from './aws-exports';
import { Amplify, Auth, Hub } from "aws-amplify";

Amplify.configure(awsconfig);

const getCurrentUser = async (data) => {
  console.log('listenting to events', data)
};

Hub.listen('auth', (data) => {
  switch (data.payload.event) {
    case 'signIn':
    case 'cognitoHostedUI':
      getCurrentUser(data);
      break;
    case 'signIn_failure':
    case 'cognitoHostedUI_failure':
      console.log('Sign in failure', data);
      break;
    default:
      break;
  }
});
function App() {
  return (
    <div className="App">
      <button onClick={() => Auth.federatedSignIn()}>hostedui</button>
    </div>
  );
}

export default App;

```

**Comment by StriderHND** [comment] 2021-01-25 23:00
@elorzafe no, the login screen is optional to the user to navigate to the app, only when the user does an action that requires authentication the user is prompted the the login screen. that is where the `Hub.listener` code is added

**Comment by elorzafe** [comment] 2021-01-25 23:23
@StriderHND is redirect from HostedUI to that screen? 

From your `package.json` seems to be a react-native app, can you confirm that?

**Comment by StriderHND** [comment] 2021-01-25 23:33
> @StriderHND is redirect from HostedUI to that screen?
> 
> From your `package.json` seems to be a react-native app, can you confirm that?

@elorzafe 

Yes it's a react native app, as stated on the [docs](https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples)

The function that handles the HostedUI redirect is on the App.JS

**Comment by 24601** [comment] 2021-01-25 23:57
@elorzafe (& @StriderHND by association on this issue who is experiencing the same thing we are): we are *not* calling ```Hub.listen``` inside useEffect and are experiencing this issue as well as the problems we are experiencing in #4315 after updating libraries. Everything was working FINE with ```    "@aws-amplify/auth": "^3.4.7",
    "@aws-amplify/ui-react": "^0.2.24",```. 

Our AWS support ticket answer is saying "don't use useEffect", which is not the problem and is not a solution, it sounds like the service team is assuming we are @StriderHND, when we are in fact a distinct, different customer with a different environment even though we are having the same problem. I don't know if that response came from you or @sammartinez , and while we truly appreciate the help, we are beginning to get more than a little frustrated that something that has worked on many revisions of production code is now being blamed our tested, production ready code when the *ONLY* change has been bumping minor revs in the AWS libs. 

At *BEST* this is a "breaking change" which should NOT be in a 0.0.XXX release, and should be SPECIFICALLY called out in releases notes even in a 0.XX.000 release. 

No, this is a *BUG* in AWS-owned code: please own it and fix it and don't try to blame your customer.

**Comment by elorzafe** [comment] 2021-01-26 01:30
@24601 

I am very sorry for all the problems this is causing to you. I am assigned to this issue and I will go thru until I find the root cause of this problem.

Do you a small working example so I can reproduce the issue so I can figure out the solution.

Again I apologize for all the inconvenience

**Comment by StriderHND** [comment] 2021-01-26 20:36
Hello @elorzafe do you need something from my side for this issue?

**Comment by elorzafe** [comment] 2021-01-26 21:14
@StriderHND 

- Can you share the latest version of your `package.json`?
- Is the app closed when is redirected from Hosted UI?
- `Hub.listen` is on another screen any particular reason to do that?

**Comment by StriderHND** [comment] 2021-01-26 21:35
@elorzafe 

- The App is one the foreground because is using a [InAppBrowser](https://www.npmjs.com/package/react-native-inappbrowser-reborn)
- No `Hub.listen` is only located only at one screen.

# Package.json
```
{
  "name": "saverapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@aws-amplify/pushnotification": "^3.2.17",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/checkbox": "^0.4.2",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.10",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-firebase/analytics": "^7.6.10",
    "@react-native-firebase/app": "^8.4.7",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "amazon-cognito-identity-js": "4.5.5",
    "aws-amplify": "^3.3.14",
    "aws-amplify-react-native": "^4.3.0",
    "geolib": "^3.3.1",
    "moment": "^2.29.1",
    "query-string": "^6.13.8",
    "ramda": "^0.27.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-base64": "^0.1.1",
    "react-native-config": "^1.4.2",
    "react-native-config-reader": "^4.1.1",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-hyperlink": "0.0.19",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-in-app-review": "^2.1.8",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-input-credit-card": "^0.5.5",
    "react-native-maps": "^0.27.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-table-component": "^1.2.1",
    "react-phone-number-input": "^3.1.10",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "rn-range-slider": "^1.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by elorzafe** [comment] 2021-01-26 22:54
@StriderHND thanks for clarifying

I followed this [Full Sample](https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples)

This is `App.js`
```jsx
import React, { useEffect, useState } from 'react';
import { Button, Linking, Text, View } from 'react-native';
import Amplify, { Auth, Hub } from 'aws-amplify';
import InAppBrowser from 'react-native-inappbrowser-reborn';
import awsconfig from './aws-exports';

async function urlOpener(url, redirectUrl) {
  await InAppBrowser.isAvailable();
  const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
    showTitle: false,
    enableUrlBarHiding: true,
    enableDefaultShare: false,
    ephemeralWebSession: false,
  });

  if (type === 'success') {
    Linking.openURL(newUrl);
  }
}

Amplify.configure({
  ...awsconfig,
  oauth: {
    ...awsconfig.oauth,
    urlOpener,
  },
});

function App() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    Hub.listen('auth', ({ payload: { event, data } }) => {
      switch (event) {
        case 'signIn':
        case 'cognitoHostedUI':
          getUser().then(userData => setUser(userData));
          break;
        case 'signOut':
          setUser(null);
          break;
        case 'signIn_failure':
        case 'cognitoHostedUI_failure':
          console.log('Sign in failure', data);
          break;
      }
    });

    getUser().then(userData => setUser(userData));
  }, []);

  function getUser() {
    return Auth.currentAuthenticatedUser()
      .then(userData => userData)
      .catch(() => console.log('Not signed in'));
  }

  return (
    <View>
      <Text>User: {user ? JSON.stringify(user.attributes) : 'None'}</Text>
      {user ? (
        <Button title="Sign Out" onPress={() => Auth.signOut()} />
      ) : (
          <Button title="Federated Sign In" onPress={() => Auth.federatedSignIn()} />
        )}
    </View>
  );
}

export default App;
```

I was able to get the User information on the screen after login with Hosted UI

Can you help a little with the structure of your App?, so I can reproduce on my side

You mention you have multiple screens, how are you navigating between them and where and how are you handling the changes when the HostedUI redirect back to the App.

**Comment by 24601** [comment] 2021-01-26 23:41
Our issues here were related that some change in auth 3.4.7 -> 3.4.17 brought up an issue related to duplication with the aws-amplify library that existed from before modularization was used: removing the modularized auth library resolved the issue. Thank you @elorzafe

**Comment by StriderHND** [comment] 2021-01-27 17:59
> @StriderHND thanks for clarifying
> 
> I followed this [Full Sample](https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples)
> 
> This is `App.js`
> 
> ```js-jsx
> import React, { useEffect, useState } from 'react';
> import { Button, Linking, Text, View } from 'react-native';
> import Amplify, { Auth, Hub } from 'aws-amplify';
> import InAppBrowser from 'react-native-inappbrowser-reborn';
> import awsconfig from './aws-exports';
> 
> async function urlOpener(url, redirectUrl) {
>   await InAppBrowser.isAvailable();
>   const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
>     showTitle: false,
>     enableUrlBarHiding: true,
>     enableDefaultShare: false,
>     ephemeralWebSession: false,
>   });
> 
>   if (type === 'success') {
>     Linking.openURL(newUrl);
>   }
> }
> 
> Amplify.configure({
>   ...awsconfig,
>   oauth: {
>     ...awsconfig.oauth,
>     urlOpener,
>   },
> });
> 
> function App() {
>   const [user, setUser] = useState(null);
> 
>   useEffect(() => {
>     Hub.listen('auth', ({ payload: { event, data } }) => {
>       switch (event) {
>         case 'signIn':
>         case 'cognitoHostedUI':
>           getUser().then(userData => setUser(userData));
>           break;
>         case 'signOut':
>           setUser(null);
>           break;
>         case 'signIn_failure':
>         case 'cognitoHostedUI_failure':
>           console.log('Sign in failure', data);
>           break;
>       }
>     });
> 
>     getUser().then(userData => setUser(userData));
>   }, []);
> 
>   function getUser() {
>     return Auth.currentAuthenticatedUser()
>       .then(userData => userData)
>       .catch(() => console.log('Not signed in'));
>   }
> 
>   return (
>     <View>
>       <Text>User: {user ? JSON.stringify(user.attributes) : 'None'}</Text>
>       {user ? (
>         <Button title="Sign Out" onPress={() => Auth.signOut()} />
>       ) : (
>           <Button title="Federated Sign In" onPress={() => Auth.federatedSignIn()} />
>         )}
>     </View>
>   );
> }
> 
> export default App;
> ```
> 
> I was able to get the User information on the screen after login with Hosted UI
> 
> Can you help a little with the structure of your App?, so I can reproduce on my side
> 
> You mention you have multiple screens, how are you navigating between them and where and how are you handling the changes when the HostedUI redirect back to the App.

@elorzafe Sure give me a moment to get you all the information.

**Comment by StriderHND** [comment] 2021-02-01 17:29
Hello @elorzafe after looking at the `Package.json` I finally been able to trigger events but now I've another problem, when I try to login with Google I got this event error.

```
{"data": [ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-2.amazonaws.com/us-east-2_dRCA6QGbN=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]], "event": "cognitoHostedUI_failure", "message": "A failure occurred when returning to the Cognito Hosted UI"}
[Mon Feb 01 2021 11:27:06.848]  LOG      {"data": [ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-2.amazonaws.com/us-east-2_dRCA6QGbN=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]], "event": "customState_failure", "message": "A failure occurred when returning state"}
```

If I try again to login with google I got no problems....

**Comment by ajonp** [comment] 2021-02-03 04:48
I am having this exact same problem on a Nextjs project using Typescript.

It is like the Auth package no longer wants to take anything from the query string of the URL when "code" is returned.

I detailed everything on Discord looking for help...
https://discord.com/channels/705853757799399426/735987829292924978/806243378303860737

**Comment by ajonp** [comment] 2021-02-04 16:16
I can confirm that `    "aws-amplify": "3.3.17",` has fixed this issue 😄

**Comment by elorzafe** [comment] 2021-02-04 16:39
> Hello @elorzafe after looking at the `Package.json` I finally been able to trigger events but now I've another problem, when I try to login with Google I got this event error.
> 
> ```
> {"data": [ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-2.amazonaws.com/us-east-2_XXXXXXXXXXXXX =}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]], "event": "cognitoHostedUI_failure", "message": "A failure occurred when returning to the Cognito Hosted UI"}
> [Mon Feb 01 2021 11:27:06.848]  LOG      {"data": [ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-2.amazonaws.com/us-east-2_XXXXXXXXXXXXX=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]], "event": "customState_failure", "message": "A failure occurred when returning state"}
> ```
> 
> If I try again to login with google I got no problems....

@StriderHND can you create another issue on our repo related to the problem you are experiencing now? It seems not to be related this.

I will close this issue because it seems to be solved. Feel free to create another issue if you are experiencing this problem.

**Closed by elorzafe** 2021-02-04 16:39 UTC
Labels: Auth, Hub, SSR, pending-close-response-required

**Comment by mitchconquer** [comment] 2021-11-03 03:14
I had this issue and the source of the problem turned out to be that I was using a combination of `aws-amplify` and `@aws-amplify/auth`, `@aws-amplify/core`, etc. In addition, we have a yarn workspaces mono-repo and they were using different versions of the dependencies.

I used [syncpack](https://github.com/JamieMason/syncpack) to synchronize the various versions in the packages and then imported the main classes (Amplify, API, Auth, etc) from `aws-amplify` only. 

Now it works! 😅

**Comment by Samaritan1011001** [comment] 2022-08-04 01:39
If anyone is still facing this issue on iOS, make sure the [deep linking setup](https://reactnative.dev/docs/linking#enabling-deep-links) for RN is properly done. 

Especially when adding the code to `AppDelegate.m`

I had to make sure the import `#import <React/RCTLinkingManager.h>` was above `#if RCT_NEW_ARCH_ENABLED` 
and the rest of the code was inside `@implementation AppDelegate`

**Comment by LogTime1h** [comment] 2022-09-15 01:13
Hello everyone, has anyone logged in to facebook on react-native platform. But it's not working on ios environment?

**Comment by LogTime1h** [comment] 2022-09-15 01:33
![image](https://user-images.githubusercontent.com/113431759/190292509-49a5fa45-62d6-4664-aae1-735a3b169464.png)

**Comment by LogTime1h** [comment] 2022-09-15 03:12
![image](https://user-images.githubusercontent.com/113431759/190305205-1fa5157f-11df-4b2c-ba35-19835c902d2c.png)

**Comment by hiteshSavkare** [comment] 2022-09-19 06:26
Hub.listen not working for 'auth' when app first time installed and afterward random cases , any help here plz , stuck with this issue

**Comment by abdallahshaban557** [comment] 2022-09-19 21:10
@hiteshSavkare - can you please submit a new Github issue so that we can track this on our end?

**Comment by VanDinh18** [comment] 2022-09-23 01:45
> ![image](https://user-images.githubusercontent.com/113431759/190305205-1fa5157f-11df-4b2c-ba35-19835c902d2c.png)

The error is because you left the wrong deep link
![telegram-cloud-photo-size-5-6152000881961316724-y](https://user-images.githubusercontent.com/43102778/191878485-3a401f27-8a66-4cb0-b892-74b024618357.jpg)
![telegram-cloud-photo-size-5-6154448420614549312-y](https://user-images.githubusercontent.com/43102778/191878496-cacab689-d1b2-4d0f-bb77-a0135138ef40.jpg)

**Comment by hoseinfo** [comment] 2024-03-28 13:20
why it closed without any solution ?
