### ISSUE TITLE
DataStore.clear() fails in jest - "TypeError: callback is not a function"

### ISSUE THREAD

**Issue by duckbytes** [aws-amplify/amplify-js#9726] opened 2022-03-23 15:22 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: Linux 5.17 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 1.92 GB / 31.26 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Firefox: 98.0.2
  npmPackages:
    @peculiar/webcrypto: ^1.3.2 => 1.3.2
    @testing-library/jest-dom: ^5.16.2 => 5.16.2
    @testing-library/react: ^12.1.4 => 12.1.4
    @testing-library/user-event: ^13.5.0 => 13.5.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 5.0.0 => 5.0.0
    web-vitals: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.21
    corepack: 0.10.0
    npm: 8.1.2

```

</details>

### Describe the bug

When using DataStore.clear() with jest, an exception is thrown with the error "TypeError: callback is not a function".

Full output:

```
  console.warn
    [WARN] 12:02.272 DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget `Amplify.configure(awsconfig)`? { config: { authProviders: undefined } }

      at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (../node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:125:4)
      at ConsoleLogger.Object.<anonymous>.ConsoleLogger.warn (../node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:164:12)
      at DataStore.<anonymous> (../node_modules/@aws-amplify/datastore/src/datastore/datastore.ts:737:11)
      at step (../node_modules/@aws-amplify/datastore/lib/datastore/datastore.js:44:23)
      at Object.next (../node_modules/@aws-amplify/datastore/lib/datastore/datastore.js:25:53)
      at fulfilled (../node_modules/@aws-amplify/datastore/lib/datastore/datastore.js:16:58)


 RUNS  src/index.test.js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: callback is not a function".] {
  code: 'ERR_UNHANDLED_REJECTION'
```

Being able to clear DataStore between tests would be useful when writing unit tests that use DataStore offline.

### Expected behavior

I would expect DataStore.clear() to run without throwing an exception.

### Reproduction steps

```
npx create-react-app something
cd something
amplify init
amplify add api
```
- select graphql
- enable conflict detection
- Single object with fields

```
amplify codegen models
```
- create test file that contains DataStore.clear()
- npm test

### Code Snippet

```javascript

import * as models from "./models";
import { DataStore } from "aws-amplify";

describe("test", () => {
  afterEach(() => {
    DataStore.clear();
  });
  it("test", async () => {
    await DataStore.save(new models.Todo({ name: "test" }));
  });
});

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional configuration

in `src/setupTests.js`

```javascript
import { Crypto } from "@peculiar/webcrypto";
global.crypto = new Crypto();
```

**Comment by chrisbonifacio** [comment] 2022-03-25 13:49
Hi @duckbytes I was able to reproduce this issue consistently in my testing. Marking as a bug for the team to investigate further or provide feedback.

<img width="1179" alt="Screen Shot 2022-03-17 at 4 42 24 PM" src="https://user-images.githubusercontent.com/16952986/160133103-453dae7c-0fb5-489d-bd93-5edcdc834ad4.png">

**Comment by duckbytes** [comment] 2022-03-25 17:01
@chrisbonifacio sorry for missing that detail. It's a react app running in jsdom, using react testing library.

I'm unit testing components and user interactions, DataStore is just for setting things up. Previously I had mocked out DataStore calls but thought it would be easier and closer to real user experience to use DataStore directly.

**Comment by chrisbonifacio** [comment] 2022-03-28 18:48
Hi @duckbytes no worries! There might be something I'm missing with the way DataStore uses the `InMemoryStore` class (which seems to be implemented with a Map) but the typing here suggests that callback can be optional but the callback is called regardless of whether it is defined or not.

https://github.com/aws-amplify/amplify-js/blob/b535af2133b5460c6e8e2fcfd89e1fe235872c27/packages/datastore/src/storage/adapter/InMemoryStore.ts#L12

```js
multiRemove = async (keys: string[], callback?) => {
    keys.forEach(k => this.db.delete(k));

    callback();
};
```

**Comment by dpilch** [comment] 2022-07-07 19:35
This seems to have been resolved by https://github.com/aws-amplify/amplify-js/pull/9921. Please let us know if you are still seeing the issue.

**Closed by dpilch** 2022-07-07 19:35 UTC
Labels: bug, DataStore, p4
