### ISSUE TITLE
URL Encoding Issue

### ISSUE THREAD

**Issue by QuinnyPig** [aws-amplify/amplify-js#1800] opened 2018-10-01 17:15 UTC
When encoding an entire URL as a positional parameter, the generated canonical string for request singing has... challenges. 

Reproduction: Pass any given URL as a positional parameter to an API gateway call. Trailing slashes are encoded differently, and thus break this use case. It would appear https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Signer.ts#L98 may be the culprit, but I'm not up enough on Javascript to adequately state either way.

**Expected behavior**

To be clear, `https%3A%2F%2Farcentry.com%2Fblog%2Fan-introduction-to-medieval-cities-and-cloud-security%2F` is the expected string, and `https%253A%252F%252Farcentry.com%252Fblog%252Fan-introduction-to-medieval-cities-and-cloud-security%252F` is what is presented for signing in the use case of passing `https://arcentry.com/blog/an-introduction-to-medieval-cities-and-cloud-security/` as a parameter.

**Comment by elorzafe** [comment] 2018-10-02 17:22
@QuinnyPig thanks for your feedback I will try to reproduce your issue and find a solution for this.

**Comment by QuinnyPig** [comment] 2018-10-02 17:37
While likely a crappy answer, I've been able to work around this using https://github.com/commenthol/url-safe-base64. "Suboptimal" doesn't really do it justice, but it's working for the time being.

**Comment by elorzafe** [comment] 2018-10-02 23:48
@QuinnyPig how are you trying to call the api using Amplify?

**Comment by QuinnyPig** [comment] 2018-10-04 00:27
```
import { API, Storage } from "aws-amplify";
  getNote() {
    return API.get("links", `/links/${encodeURIComponent(this.props.match.params.id)}`);
  }
```

You can swap the `encodeURIComponent()` for a variety of things; url-safe-base64 is the only thing I've found so far that works reliably.

**Comment by undefobj** [comment] 2018-10-10 22:21
@QuinnyPig we have looked at this and we're not sure why you are trying to encode your query string parameters with `encodeURIComponent `. The point of `encodeURIComponent` is to cleanse input of characters with the friendly, human readable version. Could you let us know why you were trying to do it like this? Perhaps there is a use case we're missing that we can improve, or something that could be clarified in our docs.

To be clear the usage for passing the query string parameters in the above should be:

```
import { API, Storage } from "aws-amplify";
let myInit = {
    queryStringParameters: {
        id: this.props.match.params.id
    }
}
//This assumes your API name is "links" and the path is "/links"
  getNote() {
    return API.get("links", '/links', myInit);
  }
```

The reason we do it like the above in the API definition is so that your input can pass through cleanly to API Gateway and Lambda, hence it's accessible by either the mapping templates or execution context of your function.

This is outlined in our documentation:
https://aws-amplify.github.io/amplify-js/media/api_guide#get

**Comment by powerful23** [comment] 2019-05-09 22:00
Closing the issue. Please let me know if you still have this issue.

**Closed by powerful23** 2019-05-09 22:00 UTC
Labels: API, pending-close-response-required
