### ISSUE TITLE
Getting Error in ADD Amplify Pluggable

### ISSUE THREAD

**Issue by saharJ95** [aws-amplify/amplify-js#10422] opened 2022-09-15 21:24 UTC
![image](https://user-images.githubusercontent.com/113641921/190511161-7546857c-884b-4051-86ff-86aba3b31339.png)
![image](https://user-images.githubusercontent.com/113641921/190512074-46c461e2-99fd-4ec4-91b7-fe9d2ccadcac.png)

Hi There,
Issue : **amplify.addPluggable** throws error when deploy on Aws Amplify Project but works fine on **Localhost**

Node Version: v16.13.1
"aws-amplify": "^4.3.35",
"@aws-amplify/pubsub": "^4.5.3"

Locally everything is fine either its adding provider or creating mqtt connection but after deployment on amplify it throws above error

**Comment by tannerabread** [comment] 2022-10-04 20:46
Closing as a duplicate of #10331

All updates will be added to that issue instead of this one.

**Closed by tannerabread** 2022-10-04 20:46 UTC
