### ISSUE TITLE
Amplify Auth - React Native - Understanding the currentAuth user logs

### ISSUE THREAD

**Issue by bearsworth** [aws-amplify/amplify-js#10882] opened 2023-01-19 06:58 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.6.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 21.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmGlobalPackages:
    corepack: 0.14.1
    expo-cli: 6.0.8
    npm: 8.19.2

```

</details>

### Describe the bug

Everything so far works as expected, but am having an issue understanding the Auth.currentAuthenticatedUser(). Each request according to the logs I get:

 LOG  [DEBUG] 50:51.910 Credentials - removing aws-amplify-federatedInfo from storage
 LOG  [DEBUG] 50:52.653 Hub - Dispatching to auth with  {"data": undefined, "event": "tokenRefresh", "message": "New token retrieved"}
 LOG  [DEBUG] 51:02.986 AuthClass - getting current authenticated user
 LOG  [DEBUG] 51:02.991 AuthClass - cannot load federated user from auth storage
 LOG  [DEBUG] 51:02.992 AuthClass - get current authenticated userpool user

Is this normal behavior to show that the user cannot be loaded from auth storage?

Everything works, I get the user, and the token comes back identical as long as its still alive for the moment so it's not requesting a new token on each trigger.

I feel as though something might be having an error, but failing to understand what the issue is. It could potentially be my local storage class which is below (NOTE: I also modified only getItem. I used the default from the documentation and both have the same issue):

```javascript
import AsyncStorage from '@react-native-async-storage/async-storage';

const MYSTORAGE_KEY_PREFIX = '@MyStorage:';
let dataMemory = {};

class MyStorage {
  static syncPromise = null;

  static setItem(key, value) {
    AsyncStorage.setItem(MYSTORAGE_KEY_PREFIX + key, value);
    dataMemory[key] = value;
    return dataMemory[key];
  }

  static async getItem(key) {
    try {
      if (Object.prototype.hasOwnProperty.call(dataMemory, key)) {
        return dataMemory[key];
      }
      let currentItem = await AsyncStorage.getItem(MYSTORAGE_KEY_PREFIX + key);
      if (!currentItem) {
        currentItem = await AsyncStorage.getItem(key);
        if (!currentItem) return undefined;
        dataMemory[key] = currentItem;
        return dataMemory[key];
      }
      dataMemory[key] = currentItem;
      return dataMemory[key];
    } catch (error) {
      return undefined;
    }
  }
  static removeItem(key) {
    AsyncStorage.removeItem(MYSTORAGE_KEY_PREFIX + key);
    return delete dataMemory[key];
  }

  static clear() {
    dataMemory = {};
    return dataMemory;
  }

  static sync() {
    if (!MyStorage.syncPromise) {
      MyStorage.syncPromise = new Promise((res, rej) => {
        AsyncStorage.getAllKeys((errKeys, keys) => {
          if (errKeys) rej(errKeys);
          const memoryKeys = keys.filter((key) =>
            key.startsWith(MYSTORAGE_KEY_PREFIX)
          );
          AsyncStorage.multiGet(memoryKeys, (err, stores) => {
            if (err) rej(err);
            stores.map((result, index, store) => {
              const key = store[index][0];
              const value = store[index][1];
              const memoryKey = key.replace(MYSTORAGE_KEY_PREFIX, '');
              dataMemory[memoryKey] = value;
            });
            res();
          });
        });
      });
    }
    return MyStorage.syncPromise;
  }
}

export default MyStorage;
```

### Expected behavior

I expect the message not to show auth user cannot be fetched from auth storage.

### Reproduction steps

I am using a custom auth solution and not the hosted UI. I can log in, confirm sign in, all things work. Even fetching the user's data. The one thing which I did differently is that I am using Amazon Cognito Identity package to pass the user data to the confirm sign in step like so:

```javascript
       const pool = new CognitoUserPool({
        UserPoolId: cognitoUser.pool.userPoolId,
        ClientId: cognitoUser.pool.clientId,
        endpoint: cognitoUser.client.endpoint,
        Storage: MyStorage,
        AdvancedSecurityDataCollectionFlag: cognitoUser.advancedSecurityDataCollectionFlag,
      });
      const newCognitoUser = new CognitoUser({
        Username: cognitoUser.username,
        Pool: pool,
        Storage: MyStorage,
      });
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment] 2023-01-27 03:32
Hi @bearsworth, thank you for opening this issue.

After some deep investigation, it appears that this occurs with a react-native app - at least on iOS - as I am able to get the same logs generated, even when using a simple app with basic authentication and no custom Storage.

Interestingly, the logs for a web app (React and Expo/RN) are slightly different and do not have `AuthClass - cannot load federated user from auth storage` but contain the logs before and after:

```console
...
[DEBUG] 24:33.499 AuthClass - getting current authenticated user
[DEBUG] 24:33.500 AuthClass - get current authenticated userpool user
...
```

Im discussing this internally with the team to confirm the behavior and will get back to you. For now, it doesn't appear to be stemming from a misconfiguration on your end.

**Comment by bearsworth** [comment] 2023-01-27 09:44
> Hi @bearsworth, thank you for opening this issue.
> 
> After some deep investigation, it appears that this occurs with a react-native app - at least on iOS - as I am able to get the same logs generated, even when using a simple app with basic authentication and no custom Storage.
> 
> Interestingly, the logs for a web app (React and Expo/RN) are slightly different and do not have `AuthClass - cannot load federated user from auth storage` but contain the logs before and after:
> 
> ```
> ...
> [DEBUG] 24:33.499 AuthClass - getting current authenticated user
> [DEBUG] 24:33.500 AuthClass - get current authenticated userpool user
> ...
> ```
> 
> Im discussing this internally with the team to confirm the behavior and will get back to you. For now, it doesn't appear to be stemming from a misconfiguration on your end.

Thanks for looking into it. That is exactly the case for iOS for me. Interesting, hopefully nothing is wrong with it and its just additional language to suggest something internal. But if it does happen to be an issue, please let me know. I would like to fix whatever may be causing the issue.

**Comment by nadetastic** [comment] 2023-02-03 07:13
Hi @bearsworth - I'd like to get some clarity on what you meant by "I am using a custom auth solution and not the hosted UI."

I understood it as you are using `Auth.signIn()` and/or `Auth.federatedSignIn({ provider: 'ProviderName'})` instead of logging in on the Hosted UI, is this correct?

**Comment by bearsworth** [comment] 2023-02-03 07:19
> 

Yeah that is correct. Using the auth helper to provide additional functionality. Since I have multi factor I'm using Auth.confirmSignIn.

**Comment by nadetastic** [comment] 2023-05-31 20:45
Hi @bearsworth following up here. The current functionality works as intended and shouldn't cause any issues. That extra log message is the result of this line in the libraries Auth package

https://github.com/aws-amplify/amplify-js/blob/ffe65eaedc5f4629cf917926666a328aa6fbba9d/packages/auth/src/Auth.ts#L1786

I'll go ahead and close this issue out for now. Thanks!

**Closed by nadetastic** 2023-05-31 20:45 UTC
Labels: question, Auth
