### ISSUE TITLE
Datastore optional string array crashes the app

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#5427] opened 2020-04-16 10:52 UTC
**Describe the bug**
I have following schema
```
type Product @model {
  id: ID!
  name: String!
  complaints: [String]
}
```
the generated datastore model is `  readonly complaint?: string[];`

But when I save new product
```
 const result = await DataStore.save(new Product({
                name: 'Mobile'
            }))
```
then I get following error

`Field complaint should be of type string[], object received. null`

### This is not silent error. The app crashes

**Expected behavior**
I should be able to save null complaints and add complaints as needed

**Comment by mdoesburg** [comment] 2020-04-16 15:46
I've been trying to get a fix for this as well. I opened a similar issue a few days ago: [https://github.com/aws-amplify/amplify-js/issues/5292](https://github.com/aws-amplify/amplify-js/issues/5292)

**Comment by iartemiev** [comment] 2020-04-16 19:16
Closing, because this is a duplicate of https://github.com/aws-amplify/amplify-js/issues/5040. We're actively working on fixing this. Please track the progress via the linked issue.

**Closed by iartemiev** 2020-04-16 19:16 UTC
Labels: DataStore
