### ISSUE TITLE
Theme Inconsistencies for Auth Components

### ISSUE THREAD

**Issue by LoganArnett** [aws-amplify/amplify-js#2130] opened 2018-11-16 15:44 UTC
**Describe the bug**
I am currently trying to simplify my usage of the existing Auth components by utilizing the theme options instead of custom components. However, some of the style options do not seem to match up correctly. Currently I have a set style on the `FormContainer` and the style for the `FormContainer` is being applied to both the `FormContainer` and `FormSection`

**To Reproduce**
1. Create a basic React with Amplify project
2. Add Auth and create a theme with the boilerplate theme file
3. Add these styles:
```
export const FormContainer = {
  margin: 0,
  paddingTop: '10%'
};
export const FormSection = {};
```
4. You will see this:
![demo](http://cloud.loganarnett.com/b5f1ab7fe9c0/Screen%252520Recording%2525202018-11-16%252520at%25252010.36%252520AM.gif)

**Expected behavior**
It should look like this:
![image](https://user-images.githubusercontent.com/8780547/48631365-5d9c0780-e98c-11e8-9596-9d52ee8498ed.png)

**Desktop (please complete the following information):**
 - OS: OSX Mojave 10.14.2
 - Browser Chrome
 - Version 70.0.3538.77

**Comment by nerdbeere** [comment] 2018-11-18 21:05
The cause of this is located here: https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx#L33

It uses the wrong property. Should be `formSection` instead of `formContainer`

**Comment by LoganArnett** [comment] 2018-11-19 15:09
Good catch

**Comment by jordanranz** [comment] 2018-12-04 00:04
Good find and thank you for the PR! I'll go ahead and merge the fix.

Closing this in favor of the PR. Please reopen if you are still having related issues after trying with the update.

**Closed** 2018-12-04 00:03 UTC
Labels: Auth, feature-request
