### ISSUE TITLE
SSR Support for Storage library. Storage.get() fails if used with withSSRContext() throws Error: No credentials

### ISSUE THREAD

**Issue by diguini** [aws-amplify/amplify-js#8664] opened 2021-07-29 15:00 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 10 10.0.19043
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 20.50 GB / 31.90 GB
  Binaries:
    Node: 16.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core:  undefined ()
    @emotion/react: ^11.4.0 => 11.4.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: next => 5.0.0-beta.2
    @material-ui/icons: next => 5.0.0-beta.1
    @material-ui/styled-engine-sc: next => 5.0.0-beta.1
    @material-ui/system: next => 5.0.0-beta.2
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^4.2.2 => 4.2.2
    babel-plugin-styled-components: ^1.12.0 => 1.13.2
    bfj:  undefined ()
    cacache:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    eslint: 7.28.0 => 7.28.0
    eslint-config-next: 11.0.0 => 11.0.0
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: 11.0.0 => 11.0.0
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    react-is: 16.8 => 16.8.6 (17.0.2, 16.13.1)
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    styled-components: ^5.3.0 => 5.3.0
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    unistore:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.2
    flow-bin: 0.155.0
    npm: 7.18.1
    yarn: 1.22.10

```

</details>

### Describe the bug

import { withSSRContext, Storage } from 'aws-amplify';

Works :
```javascript
export async function getServerSideProps(context) {
    const img = await Storage.get('studios/462d5510-d5ed-4c8b-b695-2ac05c3cb645/logo.jpg');

    return {
      props: {}, // will be passed to the page component as props
    }
  }
```
Don't work, throws error AWSS3Provider - ensure credentials error No Cognito Identity pool provided for unauthenticated access Error: No credentials
```javascript
export async function getServerSideProps(context) {
    const SSR = withSSRContext(context);
    const _studios = await SSR.DataStore.query(Studio);
    const img = await Storage.get('studios/462d5510-d5ed-4c8b-b695-2ac05c3cb645/logo.jpg');

    return {
      props: {}, // will be passed to the page component as props
    }
  }
```
If withSSRContext is used, Storage stops working, and i need withSSRContext for server side rendering.

### Expected behavior
```javascript
export async function getServerSideProps(context) {
    const SSR = withSSRContext(context);
    const _studios = await SSR.DataStore.query(Studio);
    const img = await Storage.get('studios/462d5510-d5ed-4c8b-b695-2ac05c3cb645/logo.jpg');

    return {
      props: {}, // will be passed to the page component as props
    }
  }
```
Working without throws error.

### Reproduction steps

amplify init
amplify add storage
amplify add api
amplify add auth
amplify push

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
AWSS3Provider - ensure credentials error No Cognito Identity pool provided for unauthenticated access
Error: No credentials

```

</details>

### aws-exports.js

``` javascript
const awsconfig = {
  "aws_project_region": "sa-east-1",
  "aws_appsync_graphqlEndpoint": "xxxxx",
  "aws_appsync_region": "sa-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "xxxxxx",
  "aws_cognito_identity_pool_id": "sa-east-1:xxxxxxxx",
  "aws_cognito_region": "sa-east-1",
  "aws_user_pools_id": "sa-east-1_xxxxxx",
  "aws_user_pools_web_client_id": "xxxxxxxxxx",
  "oauth": {},
  "aws_user_files_s3_bucket": "xxxxxxxxxxxxx-dev",
  "aws_user_files_s3_bucket_region": "sa-east-1"
};
```

**Comment by chrisbonifacio** [comment] 2021-08-03 20:34
Hey @diguini I have been able to reproduce your issue consistently. However, I think this might actually be expected behavior until we add official support for Storage. Looking into the `withSSRContext` code, it seems that, at the moment, only `Auth`, `API`, and `DataStore` are officially supported and have been tested for use in SSR.

https://github.com/aws-amplify/amplify-js/blob/d4f8fe65fb6d54400f5bc1a6ee85a595f2fdf392/packages/aws-amplify/src/withSSRContext.ts#L17

**Comment by diguini** [comment] 2021-08-03 21:50
Hi @chrisbonifacio thanks for the reply.
I understand, but look at the code part:
"const img = await Storage.get('studios/462d5510-d5ed-4c8b-b695-2ac05c3cb645/logo.jpg');"
I'm not using withSSRContext here, but using in the line above:
"await SSR.DataStore.query(Studio);"
If i remove the line "await SSR.DataStore.query(Studio);", the code works, however with only one call of withSSRContext in other api such Datastore or Auth, throws the error.
And if i remove withSSRContext from Datastore query, i lose the sync.

**Comment by chrisbonifacio** [comment] 2021-08-03 23:25
I apologize, I'm not sure I understand what you mean. Are you saying that `Storage.get` is working for you within `getServerSideProps`?

In your code snippet, only `DataStore.query` will work because it's getting its credentials from `withSSRContext`.

**Comment by diguini** [comment] 2021-08-03 23:28
Yes, Storage.get works if i remove the DataStore.query.

**Comment by chrisbonifacio** [comment] 2021-08-03 23:59
@diguini Ahh okay, I see what you mean. Funny, I had a feeling your bucket was public and updated mine to be public as well but was still getting the `AWSS3Provider - ensure credentials error No Cognito Identity pool provided for unauthenticated access
Error: No credentials` error. 

Must have taken quite a while for my resources to update in the cloud.

So, yeah you're experiencing behavior like this, correct?

WITHOUT `withSSRContext`

<img width="975" alt="Screen Shot 2021-08-03 at 7 55 10 PM" src="https://user-images.githubusercontent.com/16952986/128100716-3523513b-3931-4af9-979d-7a7666f8be37.png">

WITH `withSSRContext` Part 1
<img width="975" alt="Screen Shot 2021-08-03 at 7 58 33 PM" src="https://user-images.githubusercontent.com/16952986/128100951-afb0dc8d-669a-4754-a2f3-98d22825c068.png">


WITH `withSSRContext` Part 2 (It worked???) Very strange and unpredictable behavior, sometimes it works sometimes it doesn't.
<img width="975" alt="Screen Shot 2021-08-03 at 7 55 53 PM" src="https://user-images.githubusercontent.com/16952986/128100773-d9050b3c-dcf4-4b0b-870f-47e1f8fa7dde.png">

**Comment by diguini** [comment] 2021-08-04 00:12
Yes @chrisbonifacio , exactly this what you described!

**Comment by chrisbonifacio** [comment] 2021-08-04 16:36
Spent quite a bit of time trying to figure out why the credentials are throwing an error and didn't learn much. This is where the error is being thrown though.

<img width="1408" alt="Screen Shot 2021-08-04 at 12 08 47 PM" src="https://user-images.githubusercontent.com/16952986/128215735-aa0cfdd9-a729-4954-821e-87fa07aabfde.png">

It's really strange, while the config for Storage seems to have persisted from the Amplify configuration on the client side, it seems like it's having issues getting a signed url for the resource and throwing an error instead. My best guess is `withSSRContext` creating a copy of Amplify is interfering with the Storage instance that was created on the client.

Honestly though, since you're trying to use `Storage` on the server and we don't really support it yet, I would advise against it for now and use it only on the client side until we do.

We are already working towards trying to support more of the libraries in SSR so I'll label this is as a feature request to track the work for SSR support for Storage and close when it's implemented.

**Comment by diguini** [comment] 2021-08-04 20:19
Okay, thanks for the attention.

**Comment by indiejoseph** [comment] 2022-03-27 23:19
Hi there any update? this issue has been while and mixed use of Storage and Datastore in backend is very common in web backend.

**Comment by asmajlovicmars** [comment] 2022-05-03 19:50
Will Storage be ever supported as SSR? 

`
const SSR = withSSRContext({ req });
await SSR.Storage.get(photo.key, { level: 'protected' });
`

**Comment by abdallahshaban557** [comment] 2022-06-03 18:27
We are investigating what it would take to enable support for SSR in all our categories for Amplify JS. We will provide updates once we have expected timelines.

**Comment by abdallahshaban557** [comment] 2022-08-10 04:09
Closing this issue as a duplicate of #7505

**Closed by abdallahshaban557** 2022-08-10 04:09 UTC
Labels: feature-request, Storage, SSR
