### ISSUE TITLE
Amplify CLI - issues switching to a local env

### ISSUE THREAD

**Issue by gkpty** [aws-amplify/amplify-js#4173] opened 2019-10-11 23:57 UTC
**Describe the bug**
Getting an error in the amplify CLI when trying to switch to another environment called test. i set up CD for the environment in the Amplify console and its working fine but i cannot switch to this environment locally.

i get the following error:
```
There was an error initializing your environment.
2019-10-11T23:35:35.367Z - error: uncaughtException: 1 validation error detected: Value '2019/08/26/[$LATEST]xxx' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]* date=Fri Oct 11 2019 18:35:35 GMT-0500 (Eastern Standard Time)
```

I have made sure that all the attributes in the team-provider-info.json are correct and i have deleted the enviornment and re-imported using `amplify env import` but i continue getting the same error.

**Comment by kaustavghosh06** [comment] 2019-10-12 00:06
Duplicate of https://github.com/aws-amplify/amplify-cli/issues/2572
Closing this issue in the JS repo.

**Closed by kaustavghosh06** 2019-10-12 00:06 UTC
