### ISSUE TITLE
Prediction Identify plain text requests failed when response lasts more than 10 seconds

### ISSUE THREAD

**Issue by mlafo** [aws-amplify/amplify-js#6093] opened 2020-06-15 14:55 UTC
Env : react native

"aws-amplify": "^3.0.8",
"aws-amplify-react-native": "^4.0.4",
"react": "16.11.0",
"react-native": "0.62.2",

Prediction Identify plain text Works fine with image stored in S3 with few texts.
But when I increase the number ok texts to be detected i get always a "Network request failed" with an "Unhandle Promise Rejection" after almost 10 seconds. Is there a way to get around this issue.

It doesn't depend on the size of the image. 
And it works fine when I test the same image on the textRact console. 

My code is very simple : 

```
 await Predictions.identify({
      text: {
        source: {
          key: "test.jpg",
          level: "public"
        },
        format: "PLAIN"
      }
    })
      .then((res) => setPrediction(JSON.stringify(res, null, 2)))
      .catch((err) =>
        setPrediction("Predictions error : " + JSON.stringify(err, null, 2))
   
```   );
  }

**Comment by cedricgrothues** [comment] 2020-06-17 14:08
Hi @mlafo, thank you for the report! I am able to reproduce the behavior you are seeing.

Using an image with just a few words works as expected, but when using an image that contains a few sentences (see example below) the response is `undefined` and an uncaught exception is thrown. 

```
fetch-http-handler.js:46 POST https://textract.eu-central-1.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED

AmazonAIIdentifyPredictionsProvider.js:201 Uncaught (in promise) TypeError: Failed to fetch
```

This is the image I used:
![text-long](https://user-images.githubusercontent.com/34948511/84908367-ab22ae00-b0b4-11ea-9e14-e512b6778b32.jpg)

**Comment by cedricgrothues** [comment] 2020-06-17 17:35
@mlafo – from what I can tell, this is an issue with `@aws-sdk/client-textract`.

Using `Predictions` with images containing fewer than fifty words works fine because for that `amplify-js` uses `rekognition` (see https://github.com/aws-amplify/amplify-js/blob/master/packages/predictions/src/Providers/AmazonAIIdentifyPredictionsProvider.ts#L178), but if an image contains fifty or more words `textract` is used in addition to `rekognition`.

Here is the `rekognition` endpoint (which works as expected):
```sh
curl -X POST https://rekognition.eu-central-1.amazonaws.com/

> Connected to rekognition.eu-central-1.amazonaws.com (3.124.237.132) port 443
```
And here the `textract` endpoint:
```sh
curl -X POST https://textract.eu-central-1.amazonaws.com/

> curl: (6) Could not resolve host: textract.eu-central-1.amazonaws.com
```
This happens because `textract` instances are currently only available on [eu-west-1, eu-west-2, ap-southeast-1, ap-southeast-2, us-east-1, us-east-2, us-west-1 and us-west-2](https://aws.amazon.com/textract/faqs/#:~:text=A%3A%20Amazon%20Textract%20is%20currently,and%20Asia%20Pacific%20(Sydney).), but the aws-sdk assumes that there are a lot more [valid regions](https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-textract/endpoints.ts#L11).

**Comment by ashika01** [comment] 2020-06-17 18:59
As @cedricgrothues has mentioned, this seems to be a limitation from the service itself. Not specific to Amplify. I will close this issue, if you have further comments or clarification that needs to answered. Feel free to ping and I can reopen the issue.

**Comment by Ashish-Nanda** [comment] 2020-06-17 23:44
@mlafo what region are you using in your config currently? Could you try making a request to one of the valid regions listed [here](https://aws.amazon.com/textract/faqs/#:~:text=A%3A%20Amazon%20Textract%20is%20currently,and%20Asia%20Pacific%20(Sydney).) to see if it works.

**Comment by ashika01** [comment] 2020-06-18 00:16
@cedricgrothues Could you comment on this too? How did you set it up?

**Comment by mlafo** [comment] 2020-06-18 10:10
@Ashish-Nanda  Region setting is an essential point.
Thanks to @cedricgrothues Despite an unvailable region, I clearly understrand the problem and the reason why it partially works because of the switch between rekognition and textract.
 
I actually use eu-central-1 but I can't try a valid region for my production application because of another issue between S3 and Prediction Region.
It seems Prediction use his own region setting to request S3 rather than the Amplify storage setting region (aws_user_files_s3_bucket_region). 
Has I reported here : https://github.com/aws-amplify/amplify-js/issues/5560#issue-606802156
prediction failed if the file to be analysed isn't in the same S3 region. (Another issue was identified into the unability to use the private storage) 
So it would be wonderful if this S3 / Prediction region issue could be resolved.

**Comment by cedricgrothues** [comment] 2020-06-18 11:36
@ashika01 @Ashish-Nanda I tried using `textract` in a supported region (`eu-west-1`) without enabling it in the cli, but that would have caused an `AccessDeniedException` not a network error.

**Comment by mlafo** [comment] 2020-06-18 12:03
@cedricgrothues Do you use Storage for you file ?
If yes, is eu-west-1 too ?

**Comment by ashika01** [comment] 2020-06-18 18:11
@cedricgrothues Thanks for checking it out. @mlafo I think cedric is looking at that issue you opened up.

**Comment by cedricgrothues** [comment] 2020-06-18 18:23
@mlafo – Both my S3 bucket and predictions are in `eu-west-1`.

**Closed** 2020-07-25 20:48 UTC
Labels: Predictions, React Native, pending-close-response-required
