### ISSUE TITLE
Redirect Mismatch in Expo + React Native + Social Sign In

### ISSUE THREAD

**Issue by bjakobson** [aws-amplify/amplify-js#10640] opened 2022-11-08 22:35 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
ystem:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 16.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 15.4
  npmPackages:
    @aws-amplify/core: ^4.5.1 => 4.5.9 
    @aws-amplify/ui-components: ^1.9.6 => 1.9.6 (1.7.2)
    @aws-amplify/ui-react: ^2.15.1 => 2.20.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/core: ^7.12.9 => 7.18.6 
    @fortawesome/fontawesome-svg-core: ^6.1.1 => 6.1.1 
    @fortawesome/free-brands-svg-icons: ^6.1.1 => 6.1.1 
    @fortawesome/react-native-fontawesome: ^0.3.0 => 0.3.0 
    @freakycoder/react-native-bounceable: ^0.2.5 => 0.2.5 (0.2.4)
    @gorhom/bottom-sheet: ^4.4.5 => 4.4.5 
    @react-native-async-storage/async-storage: ~1.15.0 => 1.15.17 
    @react-native-community/netinfo: 7.1.3 => 7.1.3 
    @react-native-masked-view/masked-view: 0.2.6 => 0.2.6 
    @react-native-picker/picker: 2.2.1 => 2.2.1 
    @react-navigation/bottom-tabs: ^6.3.1 => 6.3.2 
    @react-navigation/native: ^6.0.10 => 6.0.11 
    @react-navigation/stack: ^6.2.1 => 6.2.2 
    @testing-library/jest-native: ^4.0.2 => 4.0.5 
    @testing-library/react-hooks: ^7.0.2 => 7.0.2 
    @testing-library/react-native: ^8.0.0 => 8.0.0 
    @types/react: ~17.0.21 => 17.0.47 (18.0.15)
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.8 => 5.2.10 
    amplify-ui-components-loader:  undefined ()
    autoprefixer: ^10.4.4 => 10.4.7 
    aws-amplify: ^4.3.19 => 4.3.27 
    aws-amplify-react-native: ^6.0.4 => 6.0.5 
    axios: ^0.26.1 => 0.26.1 (0.26.0, 0.24.0)
    checkbox:  0.0.1 
    concurrently: ^7.1.0 => 7.2.2 
    date-fns: ^2.28.0 => 2.28.0 (1.30.1)
    eslint: ^7.24.0 => 7.32.0 
    eslint-config-handlebarlabs: ^0.0.6 => 0.0.6 
    eslint-config-prettier: ^8.2.0 => 8.5.0 (6.15.0)
    eslint-plugin-prettier: ^3.4.0 => 3.4.1 
    expo: ^44.0.0 => 44.0.6 
    expo-auth-session: ~3.5.0 => 3.5.0 
    expo-cached-image: ^44.1.7 => 44.2.1 
    expo-constants: ^13.2.4 => 13.2.4 (13.0.2)
    expo-dev-client: ~0.8.6 => 0.8.6 
    expo-device: ~4.1.0 => 4.1.1 
    expo-google-app-auth: ~8.3.0 => 8.3.0 
    expo-linear-gradient: ~11.0.3 => 11.0.3 
    expo-linking: ~3.0.0 => 3.0.0 
    expo-notifications: ~0.14.0 => 0.14.1 
    expo-random: ~12.1.2 => 12.1.2 
    expo-splash-screen: ~0.14.1 => 0.14.2 
    expo-status-bar: ~1.2.0 => 1.2.0 
    expo-updates: ~0.11.7 => 0.11.7 
    expo-web-browser: ~10.1.0 => 10.1.1 
    hermes-inspector-msggen:  1.0.0 
    instabug-reactnative: ^11.2.0 => 11.2.0 
    jest-expo: ^44.0.0 => 44.0.1 
    lodash.debounce: ^4.0.8 => 4.0.8 
    lottie-ios: ^3.2.3 => 3.2.3 
    lottie-react-native: 5.0.1 => 5.0.1 
    moment: ^2.29.3 => 2.29.4 
    native-notify: ^3.0.2 => 3.0.2 
    postcss: ^8.4.12 => 8.4.14 
    postcss-cli: ^9.1.0 => 9.1.0 
    prettier: ^2.6.2 => 2.7.1 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-hot-toast: ^2.3.0 => 2.3.0 
    react-native: 0.64.3 => 0.64.3 
    react-native-app-intro-slider: ^4.0.4 => 4.0.4 
    react-native-async-storage: 0.0.1 => 0.0.1 
    react-native-autocomplete-dropdown: ^2.0.7 => 2.0.7 
    react-native-body-highlighter: ^2.0.2 => 2.0.2 
    react-native-bouncy-checkbox: ^2.1.10 => 2.1.10 
    react-native-bouncy-touchable: ^1.0.0 => 1.0.0 
    react-native-calendars: ^1.1284.0 => 1.1285.0 
    react-native-chart-kit: ^6.12.0 => 6.12.0 
    react-native-confetti-cannon: ^1.5.2 => 1.5.2 
    react-native-dialog-input: ^1.0.8 => 1.0.8 
    react-native-dynamic-search-bar: ^2.0.2 => 2.0.2 
    react-native-elements: ^3.4.2 => 3.4.2 
    react-native-fast-image: ^8.5.11 => 8.5.11 
    react-native-gesture-handler: ~2.1.0 => 2.1.3 
    react-native-inappbrowser-reborn: ^3.7.0 => 3.7.0 
    react-native-keyboard-aware-scroll-view: ^0.9.5 => 0.9.5 
    react-native-linear-gradient: ^2.5.6 => 2.6.2 
    react-native-modal: ^13.0.1 => 13.0.1 
    react-native-modal-dropdown: ^1.0.2 => 1.0.2 
    react-native-modal-dropdown-demo:  0.6.2 
    react-native-optimized-flatlist: ^1.0.4 => 1.0.4 
    react-native-option-menu: ^1.1.3 => 1.1.3 
    react-native-paper: ^4.12.2 => 4.12.2 
    react-native-reanimated: ~2.3.1 => 2.3.3 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: ~3.10.1 => 3.10.2 
    react-native-scrollable-navigation-bar: ^3.0.5 => 3.0.5 
    react-native-segmented-control-tab: ^4.0.0 => 4.0.0 
    react-native-share: ^7.3.7 => 7.6.4 
    react-native-shimmer-placeholder: ^2.0.8 => 2.0.8 
    react-native-spinkit: ^1.5.1 => 1.5.1 
    react-native-svg-charts: ^5.4.0 => 5.4.0 
    react-native-svg-transformer: ^1.0.0 => 1.0.0 
    react-native-textinput-with-icons: ^1.0.18 => 1.0.18 
    react-native-toast-message: ^2.1.5 => 2.1.5 
    react-native-ux-cam: ^5.4.1 => 5.4.1 
    react-native-web: 0.17.1 => 0.17.1 
    react-native-webview: 11.15.0 => 11.15.0 
    react-native-youtube-iframe: ^2.2.2 => 2.2.2 
    react-test-renderer: ^17.0.2 => 17.0.2 
    rrule: ^2.7.0 => 2.7.0 
    setup-tailwind-rn: ^1.1.0 => 1.1.0 
    src:  undefined ()
    tailwind-rn: ^4.2.0 => 4.2.0 
    tailwindcss: ^3.0.23 => 3.1.5 
    typescript: ~4.3.5 => 4.3.5 
  npmGlobalPackages:
    @aws-amplify/cli: 8.5.0
    create-react-native-app: 3.8.0
    eas-cli: 0.54.1
    expo-cli: 6.0.5
    npm: 6.14.13

```

</details>

### Describe the bug

I try signing in with Google via. Cognito's Hosted UI, and suddenly, it stopped working, displaying an error saying "An error was encountered with the requested page". The weird behavior is that it worked perfectly (in app), I refreshed the app, and this error started appearing. No search result has been helpful. 

I VERIFIED that the Redirect URLS are the same!!!!
### Expected behavior

Sign in with Google or Apple should launch the respected platform and allow sign-up

### Reproduction steps

1. Import Auth (former user pool)
2. Set redirect URLS to: `exp://127.0.0.1:19000`
3. Test

### Code Snippet

```javascript
// Put your code below this line.
//URL Config

async function urlOpener(url, redirectUrl) {
  const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(
    url,
    redirectUrl,
  );

  if (type === 'success' && Platform.OS === 'ios') {
    WebBrowser.dismissBrowser();
    return Linking.openURL(newUrl);
  }
}

const amplifyConfig = {
  ...awsconfig,
  oauth: {
    ...awsconfig.oauth,
    urlOpener,
  },
  options: {
    // Indicates if the data collection is enabled to support Cognito advanced security features. By default, this flag is set to true.
    AdvancedSecurityDataCollectionFlag: true,
  },
};

const expoScheme = 'XXXXXX://';
// Technically you need to pass the correct redirectUrl to the web browser.
let redirectUrl = Linking.createURL();
if (redirectUrl.startsWith('exp://1')) {
  // handle simulator(localhost) and device(Lan)
  redirectUrl = redirectUrl + '/--/';
} else if (redirectUrl === expoScheme) {
  // dont do anything
} else {
  // handle the expo client
  redirectUrl = redirectUrl + '/';
}
amplifyConfig.oauth.redirectSignIn = redirectUrl;
amplifyConfig.oauth.redirectSignOut = redirectUrl;

Amplify.configure(amplifyConfig);



// sign in:

//cut relevant data

 onPress={() =>
                  Auth.federatedSignIn({
                    provider: CognitoHostedUIIdentityProvider.Apple,
                  })
                }
```

### Log output

<details>

```
// Put your logs below this line

An error was encountered with the requested page
```

</details>

### aws-exports.js

"oauth": {
        "domain": "XXXX.auth.us-west-2.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000",
        "redirectSignOut": "exp://127.0.0.1:19000",
        "responseType": "code"
    },

**Comment by tannerabread** [comment] 2022-11-08 23:50
hi @bjakobson
Could you try adding `exp://127.0.0.1:19000/--/`  to your redirect URIs in Cognito? Unless I'm missing something it looks like you are setting that as the redirect URI in the app code but it's not present in your aws-exports (and therefore not valid in Cognito and sending you to the error page). It is curious though that it worked briefly until you refreshed the app

Also do you mind posting your `package.json`? I'm curious about a bit of setup that I've been seeing lately that yours might be following

**Comment by bjakobson** [comment] 2022-11-09 01:56
@tannerabread is 'react-native-inappbrowser-reborn' possible using Expo?

**Comment by tannerabread** [comment] 2022-11-09 02:26
@bjakobson 
I'm not sure that the in-app-browser works in Expo, I just couldn't remember trying the WebBrowser before, but I found an old project though where I had tried this flow before. I tried to spin it up and it's not working properly for me either. I will look into this more tomorrow and try to find the cause and hopefully get passed your blocker as well.

**Comment by bjakobson** [comment] 2022-11-09 02:28
@tannerabread, no worries!! Removing `urlOpen` actually worked!! Is there a downside to having it removed?

**Comment by tannerabread** [comment] 2022-11-09 02:38
Oh I'm glad that worked! There must be something wrong with the urlOpener then that I will look deeper into

To answer your question about the downsides, the in app browser provides a smoother experience as it gets rid of the lingering browser window after the sign in is complete. The authentication should still work the same.

**Comment by bjakobson** [comment] 2022-11-09 02:40
Awesome, thank you so much!

As for pushing to development (i.e. testflight and appstore), using `myapp://` for `redirect_url` should work, correct?

**Comment by tannerabread** [comment] 2022-11-09 02:51
There might be a few more steps that could possibly already be done:
Follow [these steps about redirect URIs](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#configure-auth-category), particularly the changes to `info.plist`
And then also add myapp:// to your redirect URIs on cognito. You also might need to slightly modify your handler for setting the redirecturl that goes in to config

**Comment by tannerabread** [comment] 2022-11-09 15:53
@bjakobson 
I have been looking deeper into it, and it seems like for expo, the redirect URL can be just `exp://127.0.0.1:19000/` if you are not going to any specific page.
Currently my config for Amplify with urlOpener is as follows:
```js
const isLocalHost = Boolean(__DEV__);

const [
  localRedirectSignIn,
  productionRedirectSignIn,
] = awsconfig.oauth.redirectSignIn.split(",");

const [
  localRedirectSignOut,
  productionRedirectSignOut,
] = awsconfig.oauth.redirectSignOut.split(",");

async function urlOpener(url, redirectUrl) {
  const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(
    url,
    redirectUrl
  );

  if (type === "success" && Platform.OS === "ios") {
    WebBrowser.dismissBrowser();
    return Linking.openURL(newUrl);
  }
}

const updatedconfig = {
  ...awsconfig,
  oauth: {
    ...awsconfig.oauth,
    redirectSignIn: isLocalHost ? localRedirectSignIn : productionRedirectSignIn,
    redirectSignOut: isLocalHost ? localRedirectSignOut : productionRedirectSignOut,
    urlOpener,
  },
};
Amplify.configure(updatedconfig);
```
and my aws-exports redirect URIs are like this:
```js
"redirectSignIn": "exp://127.0.0.1:19000/,myapp://",
"redirectSignOut": "exp://127.0.0.1:19000/,myapp://",
```
This setup is working for me

I don't see any difference in your function `urlOpener`, but I modified the way `redirectSignIn` and `redirectSignOut` are set in the updatedConfig. I'm also don't believe that `options: { AdvancedSecurityDataCollectionFlag: true }` is currently supported in the Amplify config, but it does default to true

**Comment by tannerabread** [comment] 2022-11-11 20:01
Hi @bjakobson 👋 Closing this as resolved. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you. 

If you run in to any different issues while using Amplify, please open a new issue so we can track it there. Also join our [discord server](https://discord.com/invite/amplify) if you would like to speak with the Amplify developer community!

Thank you!

**Closed by tannerabread** 2022-11-11 20:01 UTC
Labels: Auth, React Native, pending-response
