### ISSUE TITLE
Native Crypto Module Error when Testing Amplify in Jest in a React App

### ISSUE THREAD

**Issue by amcgregor101** [aws-amplify/amplify-js#8257] opened 2021-05-11 16:43 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
I'm not sure if it's clear from the output below, but I'm running this on WSL.

npx: installed 1 in 1.868s

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 12.01 GB / 12.45 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    @aws-amplify/auth: ^3.4.31 => 3.4.31
    @testing-library/jest-dom: ^5.12.0 => 5.12.0
    @testing-library/react: ^11.2.6 => 11.2.6
    @testing-library/user-event: ^12.8.3 => 12.8.3
    @types/jest: ^26.0.23 => 26.0.23
    @types/node: ^12.20.12 => 12.20.12
    @types/react: ^17.0.5 => 17.0.5
    @types/react-dom: ^17.0.4 => 17.0.4
    aws-amplify: ^3.4.0 => 3.4.0
    crypto-js: ^4.0.0 => 4.0.0 (3.3.0)
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 4.0.3 => 4.0.3
    typescript: ^4.2.4 => 4.2.4
    web-vitals: ^1.1.2 => 1.1.2
  npmGlobalPackages:
    typescript: 4.2.4
```
</details>

### Describe the bug

"Native crypto module could not be used to get secure random number." error when trying to sign in to a newly created account in Jest in a newly created react app. 

I've looked at this issue for a solution: https://github.com/aws-amplify/amplify-js/issues/4886 and I've tried fixing this by putting `(global as any).crypto = require('crypto');` in my setupTests.ts file. I've also tried putting `(window as any).crypto = require('crypto');` in my setupTests.ts file. I've tried putting these both before and after the imports in setiptTests.ts. I've also tried reverting crypto-js to 3.3.0. None of these solutions have worked. 

### Expected behavior

No error. Sign in succeeds.

### Reproduction steps

1. create-react-app
2. Install @aws-amplify/auth, aws-amplify, and crypto-js
3. Add the amplify config
4. Add the test to the project
5. Add "(global as any).crypto = require('crypto'); Amplify.configure(amplifyAuthConfig)" to setupTests.ts
6. Run "npm test"

Here is a zip of a demo project that exposes this bug. If you start from this zip, just run "npm install; npm test":
[Amplify Jest Example.zip](https://github.com/aws-amplify/amplify-js/files/6460662/Amplify.Jest.Example.zip)

### Code Snippet

Test file:
```javascript
import {generatePassword, generateUsername} from "../TestUtilities";
import {Auth} from "aws-amplify";

test('create-delete-account', async () => {
    const username = generateUsername() // Generates a random valid username
    const password = generatePassword() // Generates a random valid password
    await Auth.signUp({username, password, attributes: {}});
    await new Promise(r => setTimeout(r, 1000)); // Don't know if this is necessary.
    const currentUser = await Auth.signIn(username, password);
    currentUser.deleteUser(function (err: Error, result: any) {
        if (err) {
            throw err
        }
    })
})
```
setupTests.ts:
```javascript
(window as any).crypto = require('crypto');
import {Amplify} from "aws-amplify";
import {amplifyAuthConfig} from "./AmplifyAuthConfig";

Amplify.configure(amplifyAuthConfig)
```

### Log output

<details>

```
  console.log
    [DEBUG] 35:56.513 AuthClass - signUp attrs: []

      at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:99:4)

  console.log
    [DEBUG] 35:57.381 AuthClass - signUp validation data: null

      at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:99:4)

  console.log
    [DEBUG] 35:58.98 Hub - Dispatching to auth with  { event: 'signUp',
      data:
       { user:
          CognitoUser {
            username: 'BMy3oICRr8hnhwe5SbPN5Dt4',
            pool: [CognitoUserPool],
            Session: null,
            client: [Client],
            signInUserSession: null,
            authenticationFlowType: 'USER_SRP_AUTH',
            storage: Storage {},
            keyPrefix: 'CognitoIdentityServiceProvider.5r9vt4shbf1afhrah5nmua6lt9',
            userDataKey:
             'CognitoIdentityServiceProvider.5r9vt4shbf1afhrah5nmua6lt9.BMy3oICRr8hnhwe5SbPN5Dt4.userData' },
         userConfirmed: false,
         userSub: 'f07463d1-9625-4ddf-8334-d5f8d313d7f5',
         codeDeliveryDetails: undefined },
      message: 'BMy3oICRr8hnhwe5SbPN5Dt4 has signed up successfully' }

      at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:99:4)
          at Array.forEach (<anonymous>)

  console.log
    [DEBUG] 35:58.112 Hub - Dispatching to auth with  { event: 'signUp',
      data:
       { user:
          CognitoUser {
            username: 'BMy3oICRr8hnhwe5SbPN5Dt4',
            pool: [CognitoUserPool],
            Session: null,
            client: [Client],
            signInUserSession: null,
            authenticationFlowType: 'USER_SRP_AUTH',
            storage: Storage {},
            keyPrefix: 'CognitoIdentityServiceProvider.5r9vt4shbf1afhrah5nmua6lt9',
            userDataKey:
             'CognitoIdentityServiceProvider.5r9vt4shbf1afhrah5nmua6lt9.BMy3oICRr8hnhwe5SbPN5Dt4.userData' },
         userConfirmed: false,
         userSub: 'f07463d1-9625-4ddf-8334-d5f8d313d7f5',
         codeDeliveryDetails: undefined },
      message: 'BMy3oICRr8hnhwe5SbPN5Dt4 has signed up successfully' }

      at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:99:4)
          at Array.forEach (<anonymous>)

  console.log
    [DEBUG] 35:58.113 AnalyticsClass - on hub capsule auth { event: 'signUp',
      data:
       { user:
          CognitoUser {
            username: 'BMy3oICRr8hnhwe5SbPN5Dt4',
            pool: [CognitoUserPool],
            Session: null,
            client: [Client],
            signInUserSession: null,
            authenticationFlowType: 'USER_SRP_AUTH',
            storage: Storage {},
            keyPrefix: 'CognitoIdentityServiceProvider.5r9vt4shbf1afhrah5nmua6lt9',
            userDataKey:
             'CognitoIdentityServiceProvider.5r9vt4shbf1afhrah5nmua6lt9.BMy3oICRr8hnhwe5SbPN5Dt4.userData' },
         userConfirmed: false,
         userSub: 'f07463d1-9625-4ddf-8334-d5f8d313d7f5',
         codeDeliveryDetails: undefined },
      message: 'BMy3oICRr8hnhwe5SbPN5Dt4 has signed up successfully' }

      at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:99:4)
          at Array.forEach (<anonymous>)

 FAIL  src/__tests__/test.test.ts (69.8 s)
  ✕ create-delete-account (2621 ms)

  ● create-delete-account

    Native crypto module could not be used to get secure random number.

       7 |     await Auth.signUp({username, password, attributes: {}});
       8 |     await new Promise(r => setTimeout(r, 1000)); // Don't know if this is necessary.
    >  9 |     await Auth.signIn(username, password);
         |                ^
      10 | })

      at cryptoSecureRandomInt (node_modules/amazon-cognito-identity-js/lib/utils/cryptoSecureRandomInt.web.js:38:9)
      at WordArray.random (node_modules/amazon-cognito-identity-js/lib/utils/WordArray.js:50:56)
      at randomBytes (node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:47:58)
      at AuthenticationHelper.generateRandomSmallA (node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:113:21)
      at new AuthenticationHelper (node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:67:29)
      at CognitoUser.authenticateUserDefaultAuth (node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:264:32)
      at CognitoUser.authenticateUser (node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:237:19)
      at node_modules/@aws-amplify/auth/src/Auth.ts:619:9
      at AuthClass.Object.<anonymous>.AuthClass.signInWithPassword (node_modules/@aws-amplify/auth/src/Auth.ts:618:24)
      at AuthClass.signIn (node_modules/@aws-amplify/auth/src/Auth.ts:504:16)
      at Object.<anonymous>.test (src/__tests__/test.test.ts:9:16)
```

</details>

### Manual configuration

```json
{
    Auth: {
        region: "us-east-1",
        userPoolId: "us-east-1_u0UzS0QUQ",
        userPoolWebClientId: "5r9vt4shbf1afhrah5nmua6lt9",
        mandatorySignIn: false,
    }
}
```

### Additional configuration

aws cognito-idp describe-user-pool --user-pool-id us-east-1_u0UzS0QUQ --region us-east-1:

<details>

```json
{
    "UserPool": {
        "Id": "us-east-1_u0UzS0QUQ",
        "Name": "test-8881-user-pool",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 2
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": 1620702511.27,
        "CreationDate": 1620702511.27,
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            }
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 8,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": false,
            "UnusedAccountValidityDays": 2
        },
        "Arn": "arn:aws:cognito-idp:us-east-1:005445751853:userpool/us-east-1_u0UzS0QUQ"
    }
}
```

</details>

**Comment by chrisbonifacio** [comment] 2021-05-13 16:04
Hmm, I didn't have to eject from my CRA to run jest in a node env. All I did was add a "jest" property to my package.json like this

```js
  "jest": {
    "testEnvironment": "node"
  },
```

I'm also able to simply change it to "jsdom" or remove it to go back to default (jsdom)

Here's a test project I made with both jest (node env) and cypress in CRA: https://github.com/chrisbonifacio/amplify-issues/tree/dev/6461-auth-mfa 

You should still be able to use both jest and cypress in the same CRA project. Unfortunately, it does look like you'd have to use jest for unit testing (no jsdom) if you're testing Auth specifically. That is pretty inconvenient for a react app though where you'd like to test your components as well unless you're also willing to use something like Storybook for single components and Cypress for e2e.

**Comment by chrisbonifacio** [comment] 2021-05-13 17:25
@amcgregor101 Oh, I see what you mean. I just tried in a new CRA project and got the warning about having to eject.

<img width="1158" alt="Screen Shot 2021-05-13 at 1 22 00 PM" src="https://user-images.githubusercontent.com/16952986/118161960-33f1b900-b3ee-11eb-9960-fcc043f5e84a.png">

Looks like the other thing I did was just replace the "test" script to use jest instead of "react-scripts"

```json
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "jest --watch",
    "eject": "react-scripts eject"
  },
```

**Comment by chrisbonifacio** [comment] 2021-05-13 18:26
Going to close this as it's not a bug, Auth just needs to be tested in a node environment. In a jsdom environment, probably better to test your ui components and how they render according to the changes in your auth state. 

Also, I'm not sure if you would be able to immediately sign in after signing up because the email has to be confirmed for the user to log in. So, might be better to split up signup and sign in as separate e2e tests. Seems kinda difficult to automate testing for an auth process that has several auth states/challenges, etc.

**Closed by chrisbonifacio** 2021-05-13 18:26 UTC
Labels: Auth, React

**Comment by chrisbonifacio** [comment] 2021-05-13 19:36
One more thing, since I just finished asking the team about this. We recommend mocking the Auth methods when writing unit tests. Otherwise, Cypress is definitely the goto for testing auth flows, we even include data-test-id attributes in our ui components if needed 😄

**Comment by LucienChu** [comment] 2021-12-31 02:20
@chrisbonifacio Hello, I am a newbie of  TDD, I understand mocking regular API with _msw,_ but have no idea how to mock the Auth from amplify, do you meaning running the _amplify mock_ in the terminal  so that all service would be mock locally and we do manual test, I found some video they mock the DB and test functionally of the defined queries? 

Or there is a way to use _msw_ , or something else, to mock the actual function of Auth in the test suits so that it could be automated. 

I am still googling about that, thanks.
