### ISSUE TITLE
IAM access to AppSync produces wrong signature when using custom domain

### ISSUE THREAD

**Issue by mwawrusch** [aws-amplify/amplify-js#8058] opened 2021-04-08 14:12 UTC
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 1.28 GB / 40.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.68
    Firefox: 72.0.2
    Safari: 14.0.3
  npmPackages:
    @angular-devkit/build-angular: ^0.1100.7 => 0.1100.7 
    @angular-eslint/builder: 1.0.0 => 1.0.0 
    @angular-eslint/eslint-plugin: 1.0.0 => 1.0.0 
    @angular-eslint/eslint-plugin-template: 1.0.0 => 1.0.0 
    @angular-eslint/schematics: 1.0.0 => 1.0.0 
    @angular-eslint/template-parser: 1.0.0 => 1.0.0 
    @angular/animations: 11.0.5 => 11.0.5 
    @angular/cdk: 11.0.3 => 11.0.3 
    @angular/cli: 11.0.5 => 11.0.5 
    @angular/common: 11.0.5 => 11.0.5 
    @angular/compiler: 11.0.5 => 11.0.5 
    @angular/compiler-cli: 11.0.5 => 11.0.5 
    @angular/core: 11.0.5 => 11.0.5 
    @angular/flex-layout: 11.0.0-beta.33 => 11.0.0-beta.33 
    @angular/forms: 11.0.5 => 11.0.5 
    @angular/language-service: 11.0.5 => 11.0.5 
    @angular/material: 11.0.3 => 11.0.3 
    @angular/platform-browser: 11.0.5 => 11.0.5 
    @angular/platform-browser-dynamic: 11.0.5 => 11.0.5 
    @angular/router: 11.0.5 => 11.0.5 
    @apollo/client: 3.2.5 => 3.2.5 
    @apollo/link-retry: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @babel/runtime: 7.12.1 => 7.12.1 
    @fortawesome/angular-fontawesome: 0.8.1 => 0.8.1 
    @fortawesome/fontawesome-free: 5.15.1 => 5.15.1 
    @fortawesome/fontawesome-svg-core: 1.2.32 => 1.2.32 
    @fortawesome/free-brands-svg-icons: 5.15.1 => 5.15.1 
    @fortawesome/free-solid-svg-icons: 5.15.1 => 5.15.1 
    @fortawesome/pro-light-svg-icons: 5.15.1 => 5.15.1 
    @fortawesome/pro-regular-svg-icons: 5.15.1 => 5.15.1 
    @fortawesome/pro-solid-svg-icons: 5.15.1 => 5.15.1 
    @ngrx/effects: 10.1.2 => 10.1.2 
    @ngrx/router-store: 10.1.2 => 10.1.2 
    @ngrx/store: 10.1.2 => 10.1.2 
    @ngrx/store-devtools: 10.1.2 => 10.1.2 
    @ramp-network/ramp-instant-sdk: ^2.4.1 => 2.4.1 
    @rojiio/roji-design-system: 0.12.0 => 0.12.0 
    @types/jasmine: 3.6.2 => 3.6.2 
    @types/jasminewd2: 2.0.8 => 2.0.8 
    @types/node: 14.14.17 => 14.14.17 
    @typescript-eslint/eslint-plugin: 4.3.0 => 4.3.0 
    @typescript-eslint/parser: 4.3.0 => 4.3.0 
    angular-code-input: 1.3.2 => 1.3.2 
    angular-svg-icon: 11.0.0 => 11.0.0 
    angulartics2: 10.0.0 => 10.0.0 
    angularx-qrcode: 10.0.11 => 10.0.11 
    aws-amplify: 3.3.26 => 3.3.26 
    aws-appsync: 4.0.3 => 4.0.3 
    bignumber.js: 9.0.1 => 9.0.1 
    bootstrap: ^5.0.0-beta3 => 5.0.0-beta3 
    branch-sdk: 2.56.2 => 2.56.2 
    browser-detect: 0.2.28 => 0.2.28 
    core-js: 2.6.5 => 2.6.5 
    eslint: ^7.23.0 => 7.23.0 
    eslint-plugin-import: 2.22.1 => 2.22.1 
    eslint-plugin-jsdoc: 30.7.6 => 30.7.6 
    eslint-plugin-prefer-arrow: 1.2.2 => 1.2.2 
    eslint-plugin-unused-imports: 1.0.1 => 1.0.1 
    ethers: ^5.1.0 => 5.1.0 
    graphql-tag: 2.11.0 => 2.11.0 
    immer: 7.0.14 => 7.0.14 
    jasmine-core: ~3.5.0 => 3.5.0 
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    jwt-decode: 3.1.2 => 3.1.2 
    karma: ~5.1.1 => 5.1.1 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~4.0.0 => 4.0.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4 
    lodash-es: 4.17.15 => 4.17.15 
    magic-sdk: 4.2.1 => 4.2.1 
    moment: 2.29.1 => 2.29.1 
    ng-intercom: 8.0.2 => 8.0.2 
    ngx-segment-analytics: 1.7.0 => 1.7.0 
    ngx-sharebuttons: 8.0.1 => 8.0.1 
    ngx-toastr: 13.1.0 => 13.1.0 
    opensea-js: ^1.1.11 => 1.1.11 
    protractor: ~7.0.0 => 7.0.0 
    pusher-js: 7.0.2 => 7.0.2 
    ramda: 0.27.1 => 0.27.1 
    rollbar: 2.19.4 => 2.19.4 
    rxjs: 6.6.3 => 6.6.3 
    sillyname: 0.1.0 => 0.1.0 
    smoothscroll-polyfill: ^0.4.4 => 0.4.4 
    ts-node: 8.0.3 => 8.0.3 
    tslib: ^2.2.0 => 2.2.0 
    typescript: 4.0.5 => 4.0.5 
    uppy: 1.24.0 => 1.24.0 
    uuid: 8.3.2 => 8.3.2 
    web-animations-js: ^2.3.2 => 2.3.2 
    webpack-bundle-analyzer: ^3.9.0 => 3.9.0 
    zone.js: ~0.10.2 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 11.0.5
    firebase-tools: 9.8.0
    npm: 6.14.11
    serverless: 2.28.0
    typescript: 4.2.3
    webpack: 5.4.0

```

</details>

### Describe the bug

IAM access to AppSync produces wrong signature when using custom domain

### Expected behavior

The signature should be correct. This might require resolving the final domain name before calculating the request, or might not be possible at all.

### Reproduction steps

Make any grqphql request using IAM

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2021-04-12 16:23
Hey 👋 Thanks for raising this issue! As I look into it, could you please provide me a few more details? 
For instance, are you getting any errors when attempting make the graphql request? Such as "Unhandled Rejection (Error): No credentials" or something similar?

**Comment by chrisbonifacio** [comment] 2021-04-12 17:02
If you don't mind, could you also provide us with a code example of how you're authenticating users, making the graphql request, as well as an example of the schema? Also, are you using different amplify environments other than the default dev environment?

You mentioned the signature being different on a custom domain. Which domain does it actually work on and which does it not?

**Comment by sammartinez** [comment] 2021-05-18 15:53
@mwawrusch,

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 15:53 UTC
Labels: API, Auth, Can't reproduce, GraphQL, pending-close-response-required
