### ISSUE TITLE
Datastore TypeScript linting Error

### ISSUE THREAD

**Issue by rush86999** [aws-amplify/amplify-js#7452] opened 2020-12-28 02:05 UTC
**Describe the bug**
I am getting typescript linting error from generated models for Datastore. 
```
Argument of type 'PersistentModelConstructor<any> | NonModelTypeConstructor<any>' is not assignable to parameter of type 'PersistentModelConstructor<any>'.
  Property 'copyOf' is missing in type 'NonModelTypeConstructor<any>' but required in type 'PersistentModelConstructor<any>'.
```
the copyOf came from copyOf code written to update Model
```
const goals = await DataStore.query(Goal, c => c.userId('eq', sub), {
          page: 0,
          limit: 1,
          sort: s => s.date(SortDirection.DESCENDING),
        })
```
schema:
```
type Goal
@model
@auth(rules: [
  ...
])
@key(name: "byUserByDate", fields: ["userId", "date"], queryField: "goalsByUserByDate")
{
  id: ID!
  userId: ID!
date: String!
...
  ttl: Int
}
```
**To Reproduce**
1. create new react native app
2. add typescript support by install necessary libraries
3. create graphql schema
4. update api and enable automerge 
5. amplify push and generate code
6. start using Datastore for query, save etc with generated models 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: MacOs
 - OS: 10.15
 - Atom IDE
 - 1.52.0

**Additional context**

**Comment by chrisbonifacio** [comment] 2023-02-06 18:17
Closing this as we have since changed the query and predicate syntax to a lazy loading model and I'm no longer able to reproduce this issue on the given schema.

**Closed by chrisbonifacio** 2023-02-06 18:17 UTC
Labels: TypeScript, needs-discussion, to-be-reproduced, DataStore, pending-triage, p3
