### ISSUE TITLE
DataStore failed to handle recursive models like tree

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-js#6736] opened 2020-09-07 08:22 UTC
Recursive object like in my case a tree causing DataStore to crash (infinite loop).

```gql
type TreeData {
  id: ID!
  [...]
}

type TreeNode {
  dataID: ID!
  # data: TreeData! @connection(fields: ["dataID"])
  children: [TreeNode!]!
}

type Tree
@model
{
  id: ID!
  name: String!
  rootDataID: ID!
  # rootData: TreeData! @connection(fields: ["dataID"])
  children: [TreeNode!]!
}
```

In my case I need to separate the tree data from the tree relation itself mostly because the same TreeData can be reused in different Trees.
```
Error saving comment InternalError: "too much recursion"
    isGraphQLScalarType types.ts:126
    result utils.ts:82
    getScalarFields utils.ts:80
    generateSelectionSet utils.ts:57
    getNonModelFields utils.ts:143
    getNonModelFields utils.ts:137
    getNonModelFields utils.ts:129
    generateSelectionSet utils.ts:58
    getNonModelFields utils.ts:143
    getNonModelFields utils.ts:137
    getNonModelFields utils.ts:129
    generateSelectionSet utils.ts:58
    [...]
```

**Comment by dpilch** [comment] 2023-03-22 21:43
Closing as duplicate of https://github.com/aws-amplify/amplify-js/issues/10058

**Closed by dpilch** 2023-03-22 21:43 UTC
Labels: feature-request, DataStore
