### ISSUE TITLE
In angular after configured aws-amplify. I can't open in IE browser facing issue of syntax error 

### ISSUE THREAD

**Issue by Ivelraj1997** [aws-amplify/amplify-js#6569] opened 2020-08-13 14:44 UTC
![image](https://user-images.githubusercontent.com/37973269/90148609-8152d400-dd51-11ea-89e3-c061cb529e40.png)

Angular version: 8
target: es5

Note: it is working fine in chrome and safari.

**Comment by amhinson** [comment] 2020-08-17 18:32
@Ivelraj1997 Could you share your package.json as well as any code snippets of your Amplify usage?

**Comment by Ivelraj1997** [comment] 2020-08-18 11:56
![image](https://user-images.githubusercontent.com/37973269/90509853-9bd4e500-e177-11ea-833b-a4699a4ac73a.png)

Package.json

![image](https://user-images.githubusercontent.com/37973269/90509912-b73ff000-e177-11ea-881b-8241dd27f68a.png)

tsconfig.json

![image](https://user-images.githubusercontent.com/37973269/90509980-d179ce00-e177-11ea-9077-20074455ec8e.png)
polyfills.ts

![image](https://user-images.githubusercontent.com/37973269/90510032-e5253480-e177-11ea-88fc-339f499045f4.png)

main.ts

**Comment by amhinson** [comment] 2020-08-19 15:40
One small note is that you shouldn't need to import `@aws-amplify/ui-components` because it is already a dependency of `@aws-amplify/ui-angular`. 

With that said, where else are you using Amplify in your project?

**Comment by Ivelraj1997** [comment] 2020-08-21 04:18
@amhinson  got it.   we used other places Auth Custom class like Auth.signIn and Auth.resetPassword

**Comment by Ivelraj1997** [comment] 2020-08-28 08:18
Angular Target version - es5 

build the project with ng build --prod

Deploy any hosting environment  then open hosted url in IE 11

**Comment by Ivelraj1997** [comment] 2021-01-19 04:56
do have any update in this issue?   it is happening in e5 target in angular.

**Comment by amhinson** [comment] 2021-01-19 18:16
Could you share a small sample repo that shows the issue you are seeing? It looks like you also might need to add a polyfill, but its tough to debug without being able to reproduce it on our side.

**Comment by iartemiev** [comment] 2021-04-12 18:11
@Ivelraj1997,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:11 UTC
Labels: Angular, pending-close-response-required
