### ISSUE TITLE
Why "unsubscribe" observer method is unsubscribing all observers for a topic and inclusive disconnecting the client in PubSub?

### ISSUE THREAD

**Issue by hectomg** [aws-amplify/amplify-js#4932] opened 2020-02-17 19:19 UTC
** Which Category is your question related to? **
PubSub
** What AWS Services are you utilizing? **
Cognito, IoT Core
** Provide additional details e.g. code snippets **
As you can see in the code below in your library when you unsubscribe an observer the library unsubscribe ALL observers related to the topics including observers tha are subscribed to other topics (including target topics) and inclusive is disconnecting the client. What if I want 2 or more observers for a topic but I want to unsubscribe each one in different moments?

`return function () {
                logger.debug('Unsubscribing from topic(s)', targetTopics.join(','));
                if (client) {
                    targetTopics.forEach(function (topic) {
                        if (client.isConnected()) {
                            client.unsubscribe(topic);
                        }
                        var observersForTopic = _this._topicObservers.get(topic) ||
                            new Set();
                        observersForTopic.forEach(function (observer) { return observer.complete(); });
                        observersForTopic.clear();
                    });
                    _this.disconnect(clientId);
                }
                return null;
            };`

**Comment by sammartinez** [comment] 2020-03-03 18:51
@hectomg This is by design that when we [unsubscribe a topic](https://aws-amplify.github.io/docs/js/pubsub#unsubscribe-from-a-topic), any listeners of said Topic will not receive messages anymore. Can you provide a little more detail into your use case? I can see this potentially being a feature request but wanted to get a little more insight on when you would want observers (2+) unsubscribing at different times from a single Topic

**Comment by hectomg** [comment] 2020-03-03 19:29
Maybe it is by design but in my experience it is wrong and this doesn't explain why unsubscribing from any topic is disconnecting the client at all, inclusive if it has more topics listening. To solve this you have to create different clients.

Anyway, this is the scenario:

I have an AngularApp where I have a dashboard composed of some widgets. Each widget is showing real-time data from equipment and that equipment is composed of various components that are monitored at the same time. We have the structure of a topic using deviceId, some like "my/topic/{deviceId}" and there we are sending all messages from all sensors as follow: { "S": <SensorId>, "V": <value> }. Each Widget is showing data for different sensors but using the same topic and every widget is independent so every widget needs his own Subscription to the topic and should unsubscribe independently of other widgets. The error as I told at the initial question is that when I unsubscribe any of the subscriptions it is unsubscribing all observers related to this topic and disconnecting the client. In my experience in MQTT, you should have independent observers and my scenario should be possible using only PubSub library.

It is a concept issue I thing. When you call "PubSub.subscribe(...).subscribe(..)" you are getting and Observer Subscription, not an instance of MQTTSubscription and when I call the unsubscribe method I want to unsubscribe from the observer not the topic.

What I did is a wrapper library when I'm creating a unique PubSubClient for each topic I want to subscribe, this way I can subscribe and unsubscribe dynamically at any time and avoiding client disconnection. when a topic has not clients (by unsubscriptions) the PubSubClient is unsubscribed and disconnected.

**Comment by sammartinez** [comment] 2020-11-16 21:48
@hectomg Thanks for this feedback. I am going to mark this as a feature request since this is not possible with the PubSub category as it currently stands. As chance you can share the Wrapper library you created to do this? It would help us as we think through on next steps for this. Thanks ahead of time

**Comment by stocaaro** [comment] 2022-10-04 22:38
Reconnection is now staged on the `next` tag in preparation for release in aws-amplify v5. To test against this update install the `next` tag version of the aws-amplify packages your project is using. eg `yarn add aws-amplify@next`.

With this change any disrupted connection will attempt to reconnect when possible. Reconnection can be expected to trigger 5 seconds after the resources to reconnect are available. If the network is disrupted in a way that can't be detected, reconnection will be attempted every minute until the connection is recovered.

Note that missed messages will not backfill on recovery. If you need to trigger behavior to catch up missed messaged on recovery, this should be possible to implement using the [connection state Hub messages](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#unsubscribe) released last month.

**Comment by stocaaro** [comment] 2023-02-15 22:29
I have confirmed that when multiple subscriptions are opened for the same topic in the same context (browser window), you can unsubscribe to one topic subscription without interrupting the other topic subscription.

Based on this, it appears to be working as the requestor expected. Based on this, I am resolving this issue.

Thanks,
Aaron

**Closed by stocaaro** 2023-02-15 22:29 UTC
Labels: feature-request, PubSub
