### ISSUE TITLE
Cognito authenticateUser OnFailure gets triggered with 200 status code and "Unknown Error" message

### ISSUE THREAD

**Issue by kickthedragon** [aws-amplify/amplify-js#707] opened 2018-04-23 14:33 UTC
Do you want to request a feature or report a bug?
bug
What is the current behavior?

OnFailure gets triggered with 200 status code (success).

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

```

 let userData = {
        Username: '<a username>',
        Pool: <a userPool>,
        Storage: new CookieStorage({
          domain: 'localhost', // for testing only
          secure: false ;// for testing only
     })
 };


let authenticationData = {
        Username: '<a username>',
        Password: '<a password>'
      };

cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function(result) {
        },
        onFailure: function(err) {
          console.log('failed to login.', err);
        }
}
```

What is the expected behavior?

OnSucess should be triggered instead.  The Cookie store works, since the device key, clock drift, access token, id token, and refresh token are added as cookies.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Google Chrome
amazon-cognito-identity-js@2.0.3

![image](https://user-images.githubusercontent.com/5422123/39133194-a33494a4-46e1-11e8-984a-8682d725ce17.png)

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by kickthedragon** [comment] 2018-04-24 14:34
This is a temporary work around i came up with.

Since it is successfully authenticates and its just incorrectly triggering onFailure, we can use cognitoUser to grab the session of the current user.


```
onFailure: function(err) {
          console.log('failed to login.', err);
          cognitoUser.getSession((sessErr, session) => {
            if (sessErr) {
              console.log(sessErr);
              d.reject(err);
              console.log('session validity', false);
            } else {
              console.log('session validity', session.isValid());
              cognitoUser.getUserAttributes((attrErr, attributes) => {
                if (attrErr) {
                  console.log('ERROR Get User Attributes', attrErr);
                }
                console.log('attribute list', attributes);
                for (let i = 0; i < attributes.length; i++) {
                  currentUser[attributes[i].toJSON()
                      .Name] = attributes[i].toJSON()
                    .Value;
                }
                currentUser.id = currentUser.sub;
                currentUser.username = session.idToken.payload['cognito:username'];
                console.log('current user', currentUser);

                $cookies.put(`${cookiePrefix}.${currentUser.username}.accessToken`, session.getAccessToken()
                  .getJwtToken(), {
                    expires: new Date(session.getAccessToken()
                      .getExpiration() * 1000),
                    secure: location.hostname !== 'localhost'
                  });

                console.log('refresh expiration', new Date(session.accessToken.payload.iat * 1000)
                  .addDays(30));

                $cookies.put(`${cookiePrefix}.${currentUser.username}.refreshToken`, session.getRefreshToken()
                  .getToken(), {
                    expires: new Date(session.accessToken.payload.iat * 1000)
                      .addDays(30),
                    secure: location.hostname !== 'localhost'
                  });

                console.log('id expiration', new Date(session.getIdToken()
                  .getExpiration() * 1000));

                $cookies.put(`${cookiePrefix}.${currentUser.username}.idToken`, session.getIdToken()
                  .getJwtToken(), {
                    expires: new Date(session.getIdToken()
                      .getExpiration() * 1000),
                    secure: location.hostname !== 'localhost'
                  });
                d.resolve(session);
              });
            }
          });
        }
```

**Comment by apanagos** [comment] 2018-04-27 23:38
I am getting the same issue. I get "Unknown" error  {"code":"UnknownError","message":"Unkown error"}
But if I do the same as @kickthedragon I am able to get a valid session and work with it.
To test I deleted the user and registered through my app successfully (along with confirm) but login is failing and it started about mid day.

**Comment by apanagos** [comment] 2018-04-28 18:25
Hi All,

I dug in a little deeper. Since the error message had a spelling mistake "Unkown" I was able to find it in the source. It is located at Line 6395 in the latest source as of yesterday. (amazon-cognito-identity.js version 2.0.3))

I put a log statement there and printed out the following information.

ERROR: (The err object at the catch) 
	TypeError: result.getIdToken(...).getPayLoad is not a function  
	
OPTIONS:  The options used for the fetch
{
	"headers":{
		"Content-Type":"application/x-amz-json-1.1",
		"X-Amz-Target":"AWSCognitoIdentityProviderService.RespondToAuthChallenge",
		"X-Amz-User-Agent":"aws-amplify/0.1.x js"
	},
	"method":"POST",
	"mode":"cors",
	"cache":"no-cache",
	"body":"{
		\"ChallengeName\":\"PASSWORD_VERIFIER\",
		\"ClientId\":\"XXXHiddenXXX\",
		\"ChallengeResponses\":{
			\"USERNAME\":\"b36129c8-39b9-4f2e-a478-a88a0992961d\",
			\"PASSWORD_CLAIM_SECRET_BLOCK\":\"XXXLots of CharactersXXX\",
			\"TIMESTAMP\":\"Sat Apr 28 18:11:14 UTC 2018\",
			\"PASSWORD_CLAIM_SIGNATURE\":\"XXXHiddenXXX"
		}
	}"
} 
			
HEADERS: (Headers used for the fetch)
{
	"Content-Type":"application/x-amz-json-1.1",
	"X-Amz-Target":"AWSCognitoIdentityProviderService.RespondToAuthChallenge",
	"X-Amz-User-Agent":"aws-amplify/0.1.x js"
}   

The response object.
RESP: {}

Hopefully that helps with debugging?
Am I doing something wrong? Is there a bug? Is there anything I can do to provide more information?

I can completely ignore the error and use the session but it is a bad work around.

**Comment by rzubrycki** [comment] 2018-06-12 09:36
Any fix for this error?

**Comment by anishsam** [comment] 2018-06-12 14:21
I came across this error today, and after some investigation, found that the issue was happening because I recently enabled 'organize imports' in my VS Code, and it was changing the order of imports, putting below imports before environment:
import * as STS from "aws-sdk/clients/sts";
import * as AWS from "aws-sdk/global";

this caused 'Unkown Error" issue for me. I disabled organize imports and imported above aws-sdk/* after all other imports, and it worked again!

**Comment by jaemsnrg** [comment] 2018-06-18 12:16
I was using this method on the client side without a problem, but switched to a node backend implementation for security sake. Is this something that is only happening when implemented in node?

**Comment by powerful23** [comment] 2018-06-26 17:51
@apanagos @kickthedragon Sorry for the late. Can you provide more details like what's your Cognito User Pool settings and the auth flow type when calling the function so that I can try to reproduce it.
@jaemsnrg for now I have no idea about this issue.

**Comment by adezeeuw** [comment] 2018-06-27 15:55
I had the same issue. Appears to be related to not implementing the optional "new password required" callback in my authenticate user call. 

https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-identity-user-pools-javascript-example-authenticating-admin-created-user.html

If that's the case, it would be great if you guys could give us a meaningful error (like "newPasswordRequired callback not found on authenticateUser call") :D. As much as "Unkown Error" brightened my day, it didn't give me a lot to work with.

**Comment by woodpav** [comment] 2018-07-31 18:38
I am using react-native for iOS. All else equal, my `.authenticateUser` call works with Build Configuration: Debug but not Release.

**Comment by jordanranz** [comment] 2018-08-07 19:40
@powerful23 merged a change to attach raw error messages to the response.

I am going to close this issue due to inactivity. Please reopen if you are still experiencing a related issue or have any more questions.

**Closed by jordanranz** 2018-08-07 19:40 UTC
Labels: Cognito, bug, investigating
