### ISSUE TITLE
ownerField not working on > 1001 elements string array

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-js#7343] opened 2020-12-04 11:07 UTC
**Describe the bug**
I store user more than 1000 ids on a field used by ownerField autorization. The ids that have index >1001 are not used by the auth rule and they won't have any access to the entity

**To Reproduce**

on Appsync UI

schema.graphql
```graphql
type MyEntity @model
 @auth (rules: [
   { allow: groups, ownerField: ["Admin"] }
   { allow: owner, ownerField: "users", operations: [read, update] }
 ]) {
   id: ID!
   users: [String]
 }
```

on Appsync queries ui

one admin (user in "Admin" Cognito group) create the entity with 1002 ids inside `users: [String]`
```graphql
 mutation AdminMutation {
   createMyEntity(input: {
     users: [
      <1001 other ids>
      "5bc5749b-e48b-4d12-875e-ee37e9f2c9ba",
      ]
   }) {
    id
  }
 }
```
then the user with id `5bc5749b-e48b-4d12-875e-ee37e9f2c9ba` tries to list all entities
```graphql
query UserMutation {
  listEvents {
    items {
      id
      users
    }
  }
}
```
this user won't see any entity while he should see the entity created by the Admin

**Comment by iartemiev** [comment] 2020-12-04 22:53
@AlessandroAnnini you're running into a [service limit](https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync) here (see the **Iterations in a foreach loop in mapping templates** row). 

You should be able to achieve the same result by using another group.

For example: 
```graphql
type MyEntity 
  @model
  @auth (rules: [
    { allow: owner }
    { allow: groups, groups: ["Editor"], operations: [read, update] }
    { allow: groups, groups: ["Admin"] }
  ]) {
    id: ID!
 }
```

**Comment by AlessandroAnnini** [comment] 2020-12-05 09:27
Thanks for the answer, but I cannot use groups because every group would represent an event and they could be a lot!
Do you know if i can increase the limit paying or do you have any advice? I cannot seem to find a workaround because of my customer needs in terms of db complexity and permissions

**Comment by iartemiev** [comment] 2020-12-05 16:56
I doubt this is a limit that can be increased, as there would be performance implications. 

Could you please explain your use case in detail?

**Comment by AlessandroAnnini** [comment] 2020-12-07 10:47
Thanks again @iartemiev, here is a brief explanation:

Imagine that `MyEntity` is Actually `Event` and I can have a LOT of events.
Every event can be attended by even more than 1000 users (online events) and this list is always different for every `Event`
So I cannot relay on Cognito Groups because it would be not dynamic enough for my use case (I need a different group for every new event).

**Comment by iartemiev** [comment] 2021-02-11 20:23
Apologies for the late response. You may be able to store these relationships in a M:M table (e.g., `MyEntityUsers` that references `MyEntity` and `User`) and then write custom authorization logic with AppSync resolvers, pipeline resolvers, or direct Lambda resolvers, as an alternative to using `owner` auth. This should allow you to circumvent any limitations.

**Comment by iartemiev** [comment] 2021-04-12 18:28
@AlessandroAnnini,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:28 UTC
Labels: API, GraphQL, pending-close-response-required
