### ISSUE TITLE
Type error in Cognito custom Number attribute update

### ISSUE THREAD

**Issue by mrcportillo** [aws-amplify/amplify-js#5978] opened 2020-06-02 22:19 UTC
The update process for authenticated user attributes on Cognito fails with a casting error for `Number` attributes.
 I created a user pool in Cognito using cloud formation with this schema:

```
        Schema:
          - Name: ackStatement
            AttributeDataType: Number
            Mutable: true
            NumberAttributeConstraints:
              MaxValue: 1
              MinValue: 0
          - Name: stealthMode
            AttributeDataType: Number
            Mutable: true
            NumberAttributeConstraints:
              MaxValue: 1
              MinValue: 0
          - Name: displayName
            AttributeDataType: String
            Mutable: true
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 3
          - Name: firstName
            AttributeDataType: String
            Mutable: true
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 3
          - Name: lastName
            AttributeDataType: String
            Mutable: true
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 3
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
```
When I try to update the user's attributes with: 

```
Auth.updateUserAttributes(user, {
        "custom:displayName": 'some string',
        "custom:stealthMode": 0
      })
```

it fails with the error:

```
{"__type":"SerializationException","Message":"class com.amazon.coral.value.json.numbers.TruncatingBigNumber can not be converted to an String"}
```
If a try to update just strings attributes it works.

I'm using version 3.0.11.

**Comment by ashika01** [comment] 2020-06-03 05:26
@mrcportillo Thanks for bringing up this issue. I was able to reproduce it. I will further investigate and keep you updated here.

**Comment by ashika01** [comment] 2020-06-03 07:03
@mrcportillo Hey after some investigation this is what I found. With respect to cognito, the [request syntax expects value as a string in user attributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html#API_AdminUpdateUserAttributes_RequestSyntax). You can see the attribute type [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AttributeType.html).

So you need to stringify your input number before making the call. Closing this issue since its how the service sdk is written.

**Closed by ashika01** 2020-06-03 07:03 UTC
Labels: Auth, investigating

**Comment by rbennell** [comment] 2020-07-30 10:08
The doc for attributeType is not great, it doesn't explain anything. Some examples would be nice.
