### ISSUE TITLE
`CognitoUser.authenticateUserDefaultAuth` does not respect the flow in which a credential sign in gets redirected to a `CUSTOM_CHALLENGE`

### ISSUE THREAD

**Issue by Itamaram** [aws-amplify/amplify-js#9287] opened 2021-11-27 09:26 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1.61 GB / 15.79 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
    Internet Explorer: 11.0.19041.1202
  npmGlobalPackages:
    @cloudflare/wrangler: 1.19.0
    azure-functions-core-tools: 3.0.3785
    dynamodb-admin: 4.0.1
    eslint-plugin-import: 2.23.4
    eslint: 7.32.0
    npm: 7.21.1
    serverless: 2.57.0
    typescript: 4.4.4

```

</details>

### Describe the bug

When calling `Auth.signIn(username, password)`, if the Cognito pool returns a custom challenge eg:
`{"ChallengeName":"CUSTOM_CHALLENGE","ChallengeParameters":{}}`, and not a `PASSWORD_VERIFIER` challenge of the form `{"ChallengeName":"PASSWORD_VERIFIER","ChallengeParameters":{}}`, then the framework throws an error:
```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (index.js:311)
    at from (index.js:137)
    at Function.push../node_modules/buffer/index.js.Buffer.from (index.js:149)
    at CognitoUser.js:299
    at AuthenticationHelper.js:280
    at AuthenticationHelper.js:306
    at BigInteger.bnModPow [as modPow] (BigInteger.js:838)
    at AuthenticationHelper.js:301
    at BigInteger.bnModPow [as modPow] (BigInteger.js:838)
    at AuthenticationHelper.calculateS (AuthenticationHelper.js:295)
    at AuthenticationHelper.getPasswordAuthenticationKey (AuthenticationHelper.js:273)
    at CognitoUser.js:292
    at Client.js:140
```
despite the flow being valid.

### Expected behavior

The framework should gracefully handle the case in which the password verification was not complete, and instead divert the flow to the custom authentication flow, transitioning to an internal state where the user can call `sendCustomChallengeAnswer` and continue on with the authentication.

### Reproduction steps

1. Configure a Cognito pool with a DefineAuthChallenge trigger that always returns a challenge name of `CUSTOM_CHALLENGE`.
2. Configure a similarly minimal CreateAuthChallenge and VerifyAuthChallenge triggers.
3. Invoke the `Auth.signIn(username, password)` function.'
4. Observe that while the http call to Cognito was successful, the amplify lib threw an error

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by Itamaram** [comment] 2021-12-09 01:00
I believe some of the comments in this thread are experiencing the same thing:
https://github.com/aws-amplify/amplify-js/issues/3159#issuecomment-871850868

**Comment by Itamaram** [comment] 2021-12-26 10:45
Is there any update on this?

**Comment by wduminy** [comment] 2022-05-26 14:42
I think this might help.

I had a similar problem and found [this doc](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js/#customauth-flow).  

The doc is a little misleading: it states:

> To initiate a custom authentication flow in your app, call signIn without a password.

But look at the code and you will see that it is called with a password:
```js
Auth.signIn(username, password)
```
Let's call that plan A.

So what's going on?

The thing is there are two ways to use `Auth.signIn`.  The other way looks like this.
```js
// plan B
Auth.signIn({username:username, password:password})
```

What I understand (after playing with the options) is this: If you want to do something on the lambda-side before the password is verified then you must follow plan A.  But if you want Cognito to invoke your lambda after the password is verified then you must use plan B on the client side.

Or put another way (using the terminology in the linked doc):

To initiate a custom authentication flow with a custom challenge in your app, call signIn using plan A.  
To initiate a custom authentication flow with an SRP challenge, call signIn using plan B.

**Comment by nadetastic** [comment] 2022-11-11 20:57
Duplicate of #3159

**Closed by nadetastic** 2022-11-11 20:57 UTC
Labels: Auth, pending-triage
