### ISSUE TITLE
User doesn't have permissions even though they are assigned to a group with permissions

### ISSUE THREAD

**Issue by Prefinem** [aws-amplify/amplify-js#146] opened 2018-01-11 01:29 UTC
So I have an admin group for my cognito pool with permissions granted to cognito-idp.  When I log into this user, I can't access the resources

Code:

    const currentCredentials = yield Auth.currentCredentials();
    const credentials = yield Auth.essentialCredentials(currentCredentials);

    AWS.config.credentials = new AWS.Credentials(credentials.accessKeyId, credentials.secretAccessKey, credentials.sessionToken);

    const cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
    const response = yield cognitoidentityserviceprovider.listUsers({ UserPoolId: awsExports.aws_user_pools_id }).promise();

    console.log(response);`

Error:
`
User: arn:aws:sts::<account_id>:assumed-role/<app_pool_name>/CognitoIdentityCredentials is not authorized to perform: cognito-idp:ListUsers on resource: arn:aws:cognito-idp:us-east-1:<account_id>:userpool/<pool_id>
`

Am I getting the wrong credentials?  Any help or tips would be greatly appreciated

**Comment by mlabieniec** [comment] 2018-01-12 22:04
@Prefinem it looks like your IAM role does not have persmissions for the cognito-idp:ListUsers method. I'm assuming you configured this manually (the backend), so did you add to the IAM policy this permission i.e something like:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "cognito-idp:ListUsers",
            "Resource": "arn:aws:cognito-idp:us-east-1:<account_id>:userpool/<pool_id>"
        }
    ]
}
```

This would need to be attached to the role you are trying to assume there. If you didn't create these resources manually and used Mobile Hub, then goto the IAM console -> Roles and search for your Mobile Hub project, click on the role and attach a policy that contains something like the above.

**Comment by Prefinem** [comment] 2018-01-12 22:18
Here is the permissions I gave to the group

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "VisualEditor0",
                "Effect": "Allow",
                "Action": "cognito-idp:*",
                "Resource": "*"
            }
        ]
    }

I made it incredibly broad to ensure that it had access to idp.

**Comment by mlabieniec** [comment] 2018-01-30 05:43
@Prefinem are you still seeing this issue or have you found a resolution?

**Comment by Prefinem** [comment] 2018-01-31 17:39
@mlabieniec I have not found a resolution.  I had to stop working on it as I was sinking to much time into it.  If you have any other suggestions, please let me know and I will give it a try

**Comment by hutch120** [comment] 2018-05-29 07:13
@Prefinem @mlabieniec Gents, I think this may be relevant to this discussion.

Check the role assigned to the user group has a `trust relationship`. It needs this so it can assume the role of the federated identity provider.

You can build an appropriate role for the User pool groups role by doing this:

- Open AWS console
- Get to IAM section
- Pick roles
- Pick web identity
- Choose Amazon Cognito
- Paste in your Identity pool id (the federated one)
- Click next
- Now add/create policies you need for the user group, like S3 access, or whatever.
- Give the role a name and save it.
- Go to your User Pool group, edit it and assign the role just created.
- Open the Federated Identity 
- Set the Authenticated role selection dropbox to `Choose role from token` 
- Optionally set `Role resolution` to `DENY`

References:

[Fine grained auth](https://aws.amazon.com/blogs/mobile/building-fine-grained-authorization-using-amazon-cognito-user-pools-groups/)

[Role based access control](https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html)

**Comment by yuntuowang** [comment] 2018-07-19 20:41
{
"Sid": "AdditionalPrivs",
"Effect": "Allow",
"Action": [
"cognito-idp:ListUsers"
],
"Resource": "arn:aws:cognito-idp:ap-southeast-2:xxx:userpool/poolId"
}
]
}

This should work.

**Comment by engharb** [comment] 2018-09-04 11:36
I have such problem and I opened an issue #1565

**Comment by zyzski** [comment] 2018-10-08 16:44
has anyone been able to resolve this? my user is in an admin group with a special arn, but when I call the credentials they are still using the default federated `Auth_Role` arn

**Comment by stripathix** [comment] 2018-10-26 15:54
@hutch120  Could you please explain second last step.
**Set the Authenticated role selection dropbox to Choose role from token**

Does this mean all of my users will get the access to execute IDP commands? 

Because doing second last step I started getting a list of users but I am concerned if this will cause any other issue with existing logged in users.

**Comment by hutch120** [comment] 2018-10-26 21:08
Hi @stripathix Sry, I should have been clearer with the setting location, I've updated my comment. The required setting is further down the page (from your screenshot) in `Federated Identity->Authentication providers->Authenticated role selection`. 

Once you set `Choose role from token`, then the role used will be the one from your user pool group instead of the federated one here which means you can do fine grained user management with userpool groups.

**Comment by stripathix** [comment] 2018-10-27 01:44
Thanks, @hutch120 I'll test that.

**Comment by undefobj** [comment] 2019-03-07 23:21
Can we close this issue? Per the discussion above it appears to be resolved.

**Closed** 2019-03-08 00:39 UTC
Labels: Cognito, documentation, pending-close-response-required

**Comment by sbussard** [comment] 2019-10-21 06:26
I tried
• manually create IAM role for use Cognito, and administrator access
• create user group called admin
• assigned a user to the admin group

This STILL gave a `AccessDeniedException` while trying to list users

**Comment by hutch120** [comment] 2019-10-21 08:14
@sbussard Consider asking this follow up question on SO as this issue actually has nothing to do with Amplify-JS.  I created an [answer](https://stackoverflow.com/questions/44002724/cognito-user-pool-groups-not-working-with-different-roles/50578381#50578381) in May 2018 that is the top answer and got some positive feedback. Maybe something has changed in Cognito, others there might be having similar issues.

`<rant>` IMO half the problems related to AWS SDK and SDK wrappers like this library would be non-issues if it was easier to configure permissions in AWS. `</rant>`

**Comment by DheerajArora5** [comment] 2019-12-26 09:47
### while creation of cloudformation stack - I got error like 
```
User:arn:aws::12345678:user/xyz is not authorized to perform:
cognito-idp:CreateUserPool on resource:*(Service:AWSCognitoIdentityProviderService;
Status Code: 400; Error Code: AccessDeniedException;Request ID: xxxxx)
```
### workaround : 
- went on to the Stack which is in Rollback state -> checked events and could see , (creation-failed) some Roles I don't have access , 
-  So , I checked IAM policy assigned to me - I was not having the access. 
- I created a new policy and assigned to myself as an Inline Policy by Importing it from AWS. 
> aws-cognito-idp 
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Cognito-IDP",
            "Effect": "Allow",
            "Action": [
                "lambda:InvokeFunction",
                "cognito-idp:*"
            ],
            "Resource": "*"
        }
    ]
}
```
>note: you can restrict the access on resource and cognito-idp user.

with this - I am successfully able to create and deploy cloudformation Stack for the module.

**Comment by vishalsaugat** [comment] 2021-03-26 15:20
Thanks @hutch120 Your solution worked.

**Comment by jakejcheng** [comment] 2022-02-07 07:30
> Hi @stripathix Sry, I should have been clearer with the setting location, I've updated my comment. The required setting is further down the page (from your screenshot) in `Federated Identity->Authentication providers->Authenticated role selection`.
> 
> Once you set `Choose role from token`, then the role used will be the one from your user pool group instead of the federated one here which means you can do fine grained user management with userpool groups.

@hutch120 I have played with this settings multiple times but the "Choose role from token" seems to still not work for me. At first, I thought the idToken is missing the assigned groups/roles but upon inspecting it, they are included in the token as expected.

Then, I tried using both Auth.currentCredentials() and AWS.config.credentials.get() to re-retrieve the aws creds with the seemingly correct idToken but no avail.
`
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
     IdentityPoolId: 'XXX',
     Logins: {
          'cognito-idp.us-east-1.amazonaws.com/us-east-1_XXX': authData.getIdToken().getJwtToken()
     }
});
 AWS.config.credentials.get(function(){...})
`

I've also followed your steps here to recreate the role (even though it looks exactly the same as my original) https://stackoverflow.com/questions/44002724/cognito-user-pool-groups-not-working-with-different-roles

With all these efforts, I'm still getting the `{default auth role} is not authorized to perform XXX` error.
(Side note, setting "Role resolution" to DENY doesn't seem to have any effect on the response error. Is this expected? Or maybe the "Authenticated role selection" settings is being overridden somewhere else)

Any ideas?

**Comment by hutch120** [comment] 2022-02-07 21:37
@jakejcheng Sry to hear of your troubles. I still have an old project that uses this library, but I haven't updated Amplify or changed Cognito configuration in years, so maybe the issue is due to some update in Amplify or change in the default Cognito setup.

For new projects I now use [serverless.com](https://www.serverless.com/) for configuring AWS and for Auth/Identity I've been using [PassportJS JWT strategy](https://www.passportjs.org/packages/passport-jwt/) for small projects with AWS API Gateway/Lambda/DynamoDB, and have looked into Auth0 for larger projects (but never had a need to use it yet).

Hope this helps.
