### ISSUE TITLE
{React Native} NotAuthorizedException is not exposed to user or app

### ISSUE THREAD

**Issue by adrianhall** [aws-amplify/amplify-js#2346] opened 2018-12-14 19:10 UTC
**Describe the bug**
I created a Cognito user pool backend and then generated a user pool client with "generateSecret" set to true.  When I run the withAuthenticator HOC and sign up, an error is generated:

```
[10:52:56] [DEBUG] 52:56.614 Analytics - on hub capsule auth Object {
[10:52:56]   "data": Object {
[10:52:56]     "code": "NotAuthorizedException",
[10:52:56]     "message": "Unable to verify secret hash for client fksb0u6ng7erviped3r33r56r",
[10:52:56]     "name": "NotAuthorizedException",
[10:52:56]   },
[10:52:56]   "event": "signUp_failure",
[10:52:56] }
```

(Gathered by setting window.LOGLEVEL = 'DEBUG'
However, this error is not shown to the user nor is it bubbled up to the app to take account of.  It is silently swallowed by the HOC.

**To Reproduce**
1. Create a cognito user pool and user pool client with 'generateSecret' set to true
2. Use withAuthenticator() to sign-up for an account

**Expected behavior**
I'd expect some sort of error - either via the console, or as a pop-up.

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Smartphone (please complete the following information):**
 - Device: iPhone X (Simulator)
 - OS: 11.0.1

**Comment by powerful23** [comment] 2019-04-05 22:17
@adrianhall I can't reproduce this issue in the IOS simulator. The error is shown up in the bottom. I am going to close the issue. Please let us know if you still have this issue.

**Closed by powerful23** 2019-04-05 22:17 UTC
Labels: Auth, React Native, bug, investigating
