### ISSUE TITLE
undefined error when trying to send mutation to graphql API

### ISSUE THREAD

**Issue by Ricool06** [aws-amplify/amplify-js#5893] opened 2020-05-25 17:32 UTC
**Describe the bug**
When trying to call `API.graphql(...)` with a mutation query, an undefined error is thrown.
The error itself appears to originate from a `parseUrl` function inside of the amplify library here: https://github.com/aws-amplify/amplify-js/blob/b4b40aa62644ea3688068e4e64f4573c568677a0/packages/analytics/src/vendor/dom-utils/parse-url.ts.
The API client does not even make a request before this failure occurs.
Non-mutation queries work fine.

**To Reproduce**
Set up an amplify react project with storage, auth, and api. Mutation queries may throw this error now.
If not, wait a few days, then they might start throwing this error.
I have no idea why this started happening.

**Expected behavior**
The API client makes a request, and it succeeds.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data):
Github repo + branch: https://github.com/Ricool06/erins-website/tree/amplifyissue

**Screenshots**
![Screenshot_20200525_182514](https://user-images.githubusercontent.com/14017085/82833130-19f55880-9eb5-11ea-94d1-74bdb0d980ea.png)

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.: API includes default auth as user pools, with API key as an additional auth type
* Which resources do you have configured?: storage, api, auth
  * If applicable, please provide your `aws-exports` file:
```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "erinswebsite-20200508222911-hostingbucket-devtwo",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://erinswebsite-20200508222911-hostingbucket-devtwo.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:a60ddaf0-3e00-445d-9a4c-4c95b49ac15c",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_kDKJSgJRF",
    "aws_user_pools_web_client_id": "60sk1knvmio9mnkm2a2abkcsp7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tqvy7ac2lrf53l2bsajznqmbui.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-pl746ystavagvje5ke3s5e44gm",
    "aws_user_files_s3_bucket": "erinswebsitea21867409ca146f7bf819b5d3b038ff2181027-devtwo",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
```
   
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 0.771s

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 19.02 GB / 31.22 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    @ant-design/icons: ^4.1.0 => 4.1.0 
    @aws-amplify/api: ^3.1.11 => 3.1.11 
    @aws-amplify/cli: ^4.20.0 => 4.20.0 
    @aws-amplify/ui-react: ^0.2.7 => 0.2.7 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    @types/enzyme: ^3.10.5 => 3.10.5 
    @types/enzyme-adapter-react-16: ^1.0.6 => 1.0.6 
    @types/jest: ^24.9.1 => 24.9.1 
    @types/node: ^12.12.42 => 12.12.42 
    @types/react: ^16.9.35 => 16.9.35 
    @types/react-dom: ^16.9.8 => 16.9.8 
    @types/react-redux: ^7.1.9 => 7.1.9 
    @types/react-responsive: ^8.0.2 => 8.0.2 
    @types/react-router-dom: ^5.1.5 => 5.1.5 
    @types/showdown: ^1.9.3 => 1.9.3 
    antd: ^4.2.5 => 4.2.5 
    aws-amplify: 3.0.10 => 3.0.10 
    aws-appsync: ^3.0.3 => 3.0.3 
    aws-sdk: ^2.683.0 => 2.683.0 
    enzyme: ^3.11.0 => 3.11.0 
    enzyme-adapter-react-16: ^1.15.2 => 1.15.2 
    graphql-tag: ^2.10.3 => 2.10.3 
    playwright: ^1.0.2 => 1.0.2 
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-markdown: ^4.3.1 => 4.3.1 
    react-mde: ^10.0.3 => 10.0.3 
    react-redux: ^7.2.0 => 7.2.0 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 3.4.1 => 3.4.1 
    redux: ^4.0.5 => 4.0.5 
    redux-devtools-extension: ^2.13.8 => 2.13.8 
    redux-saga: ^1.1.3 => 1.1.3 
    showdown: ^1.9.1 => 1.9.1 
    ts-jest: ^25.5.1 => 25.5.1 
    ts-node: ^8.10.1 => 8.10.1 
    typescript: ^3.9.3 => 3.9.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.19.0
    npm: 6.14.4

```

</details>

**Smartphone (please complete the following information):**

- Device: Laptop
- OS: Kubuntu 20.04
- Browser Chrome
- Version 81.0.4044.138

**Additional context**
Tried using aws-amplify 3.0.11 and 3.0.12 and this still occurse

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ashika01** [comment] 2020-06-01 23:20
@Ricool06 - You are facing this error when trying to send a mutation query using `amplify.graphql` right?

To simplify things, could you just post the code snippet of your model schema and the api.graphql call that causing this issue?

**Comment by Ricool06** [comment] 2020-06-02 10:57
Model snippet:
```typescript
export type CreatePostInput = {
  id?: string | null,
  title: string,
  content?: string | null,
  coverPhotoKey?: string | null,
  _version?: number | null,
};
```

This is how I am calling it in a redux saga:
```typescript
const response = yield call(
      [API, 'graphql'],
      graphqlOperation(mutations.createPost, { input }));
```

This is an example of the call it makes as a result:
```typescript
const input: CreatePostInput = {
  title: 'a title',
  content: 'some content',
  coverPhotoKey: 's3ObjectKey'
};


API.graphql(graphqlOperation(mutations.createPost, { input }));
```

**Comment by Ricool06** [comment] 2020-06-02 17:55
@ashika01 thanks! You rule

**Comment by ashika01** [comment] 2020-06-02 19:25
@Ricool06 something as simple as this works fine for me.

```
const input: CreatePostInput = {
  title: 'a title',
  content: 'some content',
  coverPhotoKey: 's3ObjectKey'
};


API.graphql(graphqlOperation(mutations.createPost, { input }));
```
Are you passing S3Object as object in your real code?

**Comment by Ricool06** [comment] 2020-06-02 19:27
@ashika01 that's strange. Can I see your package.json and package-lock.json so I can compare your version to mine?

**Comment by ashika01** [comment] 2020-06-02 19:33
I am not using auth or storage. I merely tested the core functionality of `API.graphql()`. 

I am using the latest amplify version `"aws-amplify": "^3.0.13"`


[yarnlock.txt](https://github.com/aws-amplify/amplify-js/files/4719258/yarnlock.txt)

**Comment by ashika01** [comment] 2020-06-02 19:33
My code is super simple 

```
import React from "react";
import "./App.css";
import Amplify, { API, graphqlOperation } from "aws-amplify";
import { createTodo, updateTodo, deleteTodo } from "./graphql/mutations";

import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);

function App() {
  const input = {
    title: "title1",
    content: "content1",
    coverPhotoKey: "photokey$123",
  };
  return (
    <div className="App">
      Hello world
      <button
        onClick={async () => {
          console.log(
            await API.graphql(graphqlOperation(createTodo, { input }))
          );
        }}
      >
        Create Todo
      </button>
    </div>
  );
}

export default App;

```

**Comment by ashika01** [comment] 2020-06-02 22:16
@Ricool06 I am closing this issue since I cant reproduce the issue. `API.graphql` is working with the provided schema. If you figure out the cause for the error and is tied to the JS api, feel free to ping me and I will reopen this issue.

**Closed by ashika01** 2020-06-02 22:16 UTC
Labels: API

**Comment by Ricool06** [comment] 2020-06-02 22:18
@ashika01 okay thanks for looking. I'll guide it another try.

**Comment by tobinbc** [comment] 2020-06-23 13:08
In case it helps anyone, I have run into this quite a few times and it's always when a project was started using Yarn, and then I clobbered it using `npm i` without a package-lock file.

**Comment by Ricool06** [comment] 2020-06-23 14:31
> In case it helps anyone, I have run into this quite a few times and it's always when a project was started using Yarn, and then I clobbered it using `npm i` without a package-lock file.

Sounds like you must have updated the package to a version that did not exhibit this issue.

**Comment by amlcodes** [comment] 2021-03-04 19:27
im getting this now with any package, after deleting node_modules and package-lock.json
