### ISSUE TITLE
DataStore not storing updated model when setting optional attribute as 'undefined'

### ISSUE THREAD

**Issue by mgm1313** [aws-amplify/amplify-js#7565] opened 2021-01-17 10:11 UTC
**Describe the bug**
When trying to update a DataStore instance, I'm unable to set a field as `undefined`. 

**To Reproduce**
```graphql
type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type Post @model {
  id: ID!
  title: String!
  featuredImage: S3Object
}
```

First create a new Post, populated with a featuredImage object:
```js
DataStore.save(new Post({
    title: 'My first post', 
    featuredImage: {
      bucket: 'myS3bucket',
      region: 'myS3region',
      key: 'MyS3ObjectKey',
    }
  }))
```

Then we update this created instance by it's id, and try setting `featuredImage` as `undefined` again:
```js
  const original = await DataStore.query(Post, id)

  DataStore.save(Post.copyOf(original, updated => {
    updated.featuredImage = undefined
  }))
```

**Expected behavior**
I would expect that after the update `featuredImage` would be `undefined` again both locally and in the cloud. 
Locally it works, I checked this by immediately logging the updated instance through:
```js
  DataStore.save(Post.copyOf(original, updated => {
    updated.featuredImage = undefined
  })).then(updated => console.log(updated))
```
But it doesn't upstream to the cloud, so the moment the local store is synced again the `featuredImage` field gets overwritten again with the old value. 

I tried setting the field as `null` instead of `undefined`, and this does work! But is giving me a TypeScript error since it doesn't expect `featuredImage` to be null: `Type 'null' is not assignable to type 'DeepWritable<S3Object> | undefined'.`. 

**Additional context**
Updating using `undefined`
```js
[DEBUG] 52:50.892 Util -  attempt #1 with this vars: ["Post","Update","{\"id\":\"d14d4b9a-ad6c-4b24-b0f7-c96dac3b8a8c\",\"title\":\"My first post\",\"_version\":1,\"_lastChangedAt\":1610876987931,\"_deleted\":null}","{}",null,null,{"data":"{\"id\":\"d14d4b9a-ad6c-4b24-b0f7-c96dac3b8a8c\",\"title\":\"My first post\",\"_version\":1,\"_lastChangedAt\":1610876987931,\"_deleted\":null}","modelId":"d14d4b9a-ad6c-4b24-b0f7-c96dac3b8a8c","model":"Post","operation":"Update","condition":"{}","id":"01EW7W04PXR875QCDKMBSS8B8R"}]
```

Updating using `null`
```js
[DEBUG] 53:22.918 Util -  attempt #1 with this vars: ["Post","Update","{\"id\":\"d14d4b9a-ad6c-4b24-b0f7-c96dac3b8a8c\",\"title\":\"My first post\",\"featuredImage\":null,\"_version\":2,\"_lastChangedAt\":1610877170998,\"_deleted\":null}","{}",null,null,{"data":"{\"id\":\"d14d4b9a-ad6c-4b24-b0f7-c96dac3b8a8c\",\"title\":\"My first post\",\"featuredImage\":null,\"_version\":2,\"_lastChangedAt\":1610877170998,\"_deleted\":null}","modelId":"d14d4b9a-ad6c-4b24-b0f7-c96dac3b8a8c","model":"Post","operation":"Update","condition":"{}","id":"01EW7W04PXR875QCDKMBSS8B8S"}]
```

**Comment by iartemiev** [comment] 2021-01-23 21:43
Thanks for opening the issue @mgm1313. I think we need to do 2 things in the library:
1. Coerce user-specified `undefined` to `null` (since `undefined` is not a supported type in DynamoDB)
2. Allow `null` as a value for optional fields in the TypeScript interface to allow passing `null` as a value explicitly.

**Comment by nickarocho** [comment] 2021-05-18 00:18
Hi @mgm1313, just a quick update: I was able to reproduce the issue in my own sample app and I'm currently working on a fix in the source code. Thanks for your patience while we get this resolved, I'll keep you updated here as we implement a fix for the issue.

**Comment by nickarocho** [comment] 2021-05-18 23:33
@mgm1313 I've merged a fix into `main` which will now allow you to explicitly set the value of any optional field in your model to `undefined`. Under the hood, we catch that declaration and coerce it into `null`, which (thanks to you!) we now know will let the value persist.

Thanks for your input and helping us make our library stronger 💪 Please feel free to reach out if you have any further questions or issues.

**Closed by nickarocho** 2021-05-18 23:33 UTC
Labels: DataStore, bug
