### ISSUE TITLE
Unable to re-login to android using react-native after logout in social signin(Google)

### ISSUE THREAD

**Issue by parasfusemachine** [aws-amplify/amplify-js#11168] opened 2023-03-31 11:37 UTC
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

Using the Google federatedSignIn, the app is able to login to aws at first.
But if signout and try to re-login the listen doesnot trigger resulting no further progress and need to completely close the app and reopen to again login to the social auth 

Login to Google with
```
Auth.federatedSignIn({
    provider: CognitoHostedUIIdentityProvider.Google
  });
```

Listening to logging action
```
 Hub.listen('auth', ({payload: {event}}) => {
      switch (event) {
        case 'signIn':
          break;
        case 'cognitoHostedUI':
          login();
          break;
        case 'signOut':
          break;
        case 'signIn_failure':
          break;
        case 'cognitoHostedUI_failure':      
          break;
        default:
          setIsLoading(false);
          break;
      }
    });
```

Signout with

```
Auth.signOut({global: true});
```

to reproduce:
1. Signin with Google 
2. Signout
3. Re-signin (Fails)
4. Close the app
5. Re-open the app
6. Signin with google (Success)

What found is
At step 1. 
Hub.listen is working 
At step 3
Hub.Listen isn't working
At step 6
Hub.listen works

</details>

### Describe the bug

The bug is described  on this issue but not worked for android solution

https://github.com/aws-amplify/amplify-js/issues/7555

This is Bug on **REACT-NATIVE**

This bug is faced after signout on the same session of the app and reopening the app doesnot face the problem

### Expected behavior

The code should be able to listen to sign at any number of signouts

### Reproduction steps

1. Login with Auth.federatedSignIn({
    provider: CognitoHostedUIIdentityProvider.Google
  })
  2. Signout with Auth.signout();
  3. ReLogin with Auth.federatedSignIn({
    provider: CognitoHostedUIIdentityProvider.Google
  })

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Operating System

Android

### Additional information and screenshots

Unable to re-login to android using react-native after logout in social signin(Google)

**Comment by fmujjwalmanandhar** [comment] 2023-03-31 11:46
yeah this is happening for us on android **following are the steps**

1: User open apps and logins via Google Signin (Auth.federatedSignIn({provider:  CognitoHostedUIIdentityProvider.Google}));
2: Hub listens and enters Home screen
3: User Signout using (Auth.signOut({global:true));
4: When he user tries to log in again Google Signin (Auth.federatedSignIn({provider:  CognitoHostedUIIdentityProvider.Google})), Hub.listen never triggers event without reloading the app.
5: If User closes app and open again it works, but when user signs out it breaks again and user must reload the app.

**Comment by nadetastic** [comment] 2023-03-31 16:37
Hi @parasfusemachine thank you for opening this issue.

I'm currently looking into this and was curious if you see it happening on both real device and/or simulator? cc. @fmujjwalmanandhar

**Comment by fmujjwalmanandhar** [comment] 2023-03-31 17:43
yeah we're facing the issue on both real device as well as emulator.

**Comment by parasfusemachine** [comment] 2023-04-03 05:28
Hi @nadetastic 
Is there any update regrading this issue?
We are having this issue and we are on the end of releasing schedule.

Thank you in advance!

**Comment by nadetastic** [comment] 2023-04-03 21:27
@parasfusemachine @fmujjwalmanandhar could you provide me with your `package.json`/dependency list? Im interested to know what versions you are using.

I working to reproduce this but haven't been able to so far, and both the re-sign in and Hub events work as expected on Android Simulator - there was a scenario where I thought I did after removing my urlOpener from `Amplify.configure()` but subsequent tests seem to be working fine.

Here are my dependencies:
```js
    "@react-native-async-storage/async-storage": "^1.18.1",
    "@react-native-community/netinfo": "^9.3.8",
    "amazon-cognito-identity-js": "^6.2.0",
    "aws-amplify": "^5.0.23",
    "core-js": "^3.29.1",
    "react": "18.2.0",
    "react-native": "0.71.5",
    "react-native-inappbrowser-reborn": "^3.7.0"
```

**Comment by parasfusemachine** [comment] 2023-04-04 04:53
@nadetastic 
Thank you for your response 

Here are my dependencies

  "dependencies": {
    "@aws-amplify/auth": "^4.6.14",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/netinfo": "^9.3.6",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/app": "^17.0.0",
    "@react-native-firebase/messaging": "^17.0.0",
    "@react-native-google-signin/google-signin": "^8.2.1",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.2",
    "@reduxjs/toolkit": "^1.8.6",
    "@shopify/flash-list": "^1.4.0",
    "@types/react": "^18.0.27",
    "@zoom/react-native-videosdk": "^1.6.2",
    "amazon-cognito-identity-js": "^5.2.12",
    "aws-amplify": "^4.3.43",
    "aws-amplify-react-native": "^6.0.8",
    "axios": "^1.2.0",
    "date-fns": "^2.29.3",
    "dayjs": "^1.11.6",
    "newrelic-react-native-agent": "^1.1.0",
    "react": "18.1.0",
    "react-native": "0.70.2",
    "react-native-calendars": "^1.1292.0",
    "react-native-config": "^1.5.0",
    "react-native-date-picker": "^4.2.6",
    "react-native-dotenv": "^3.4.7",
    "react-native-error-boundary": "^1.2.3",
    "react-native-fbsdk-next": "^11.0.1",
    "react-native-gesture-handler": "^2.7.1",
    "react-native-image-crop-picker": "^0.39.0",
    "react-native-image-picker": "^5.1.0",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-keep-awake": "^4.0.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-network-logger": "^1.14.0",
    "react-native-permissions": "^3.6.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^2.11.0",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.1",
    "react-native-svg": "^13.5.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vision-camera": "^2.15.4",
    "react-redux": "^8.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "use-debounce": "^9.0.2"
  }

**Comment by nadetastic** [comment] 2023-04-06 22:04
@parasfusemachine I wanted to share my repo where I got this working, so you can take a look at my setup and compare while i continue to investigate this - https://github.com/nadetastic/reactnative-amplified-android

**Comment by nambiarn** [comment] 2023-05-22 15:07
Hi @nadetastic, I can confirm this is an issue.

React Native Version:            0.70.8
AWS Amplify Version:           ^4.3.8
AWS Amplify React Native: ^6.0.1

**Comment by nadetastic** [comment] 2023-09-11 21:04
Hi @ardentcricket @parasfusemachine  following up here - were you all able to resolve this issue? From the sample repo that i shared, this error doesn't appear to happen on v5 of Amplify, since you are using v4, upgrading to v5 may resolve this for you.

Let me know if you have questions.

**Comment by nadetastic** [comment] 2023-09-25 23:21
Closing this issue out for now as it doesn't affect/is not reproducible with Amplify V5+

**Closed by nadetastic** 2023-09-25 23:21 UTC
Labels: investigating, Auth, pending-response

**Comment by SaadbinWaheed** [comment] 2023-10-18 17:40
Still facing the error on:

 "aws-amplify": "^5.2.4",
 "aws-amplify-react-native": "^7.0.2"

**Comment by SaadbinWaheed** [comment] 2023-10-24 07:34
@nadetastic it is still reproducible.

**Comment by SaadbinWaheed** [comment] 2023-10-24 07:36
@parasfusemachine , did any fix work for you?

**Comment by parasfusemachine** [comment] 2023-10-30 05:26
@SaadbinWaheed 
no solution yet, just clearing cache on browser such that use have to enter email and password everytime

**Comment by parasfusemachine** [comment] 2023-10-30 05:27
@SaadbinWaheed 
haven't faced this recently

**Comment by Maorshl** [comment] 2024-02-13 08:23
I am facing this issue with `"aws-amplify": "^5.3.5"` and the logs I am getting when trying to login on the second time are:
<img width="562" alt="Screenshot 2024-02-13 at 10 21 27" src="https://github.com/aws-amplify/amplify-js/assets/56290456/8f67a80f-216f-48c4-9b53-00bd1c7c99d4">
