### ISSUE TITLE
Next 13 redirectWithSIgnin

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#12589] opened 2023-11-20 04:50 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I've set up a Next 13 project per the directions on the new V6 documentation.  Everything is working fine except for using signinWithRedirect.  The login to the social provider (google) works just fine and the cookies are created but when it does the window.history.replaceState it causes a Client vs Server hydration error (I have a header that's matching the path to bold the menu items).

I tested it without anything in the file that would cause a Client/Server issue and it doesn't navigate.

If there are multiple Redirect URLs it will also throw an error if if the first item in the list for localhost isn't the localhost one.

### Expected behavior

After successful login cookies are added and page is navigated to the redirectUrl specified.

### Reproduction steps

Follow steps in documentation but use a Next 13 install instead of plain react.

**Comment by rogueturnip** [comment] 2023-11-20 15:38
I sorted out the styles issue.  I had to wrap the component in a "dynamic" to prevent it from being SSR'd, however, the lack of redirect is still an issue.  I solved that temporarily by adding into the Hub function to get the user a router.replace, but I think that's a bit of a hack.

**Comment by nadetastic** [comment] 2023-11-20 15:59
Hi @rogueturnip, thank you for opening this issue.

Can you clarify the issue that you are seeing? It sounds like when the authentication with google is successful and the user is redirect back to your app (and you see the session cookies), there's a second redirect that you have implemented with `window.history.replaceState` that fails?

**Comment by rogueturnip** [comment] 2023-11-20 17:36
Sure I'll give you a flow of what I'm seeing.  I'm using Next 14 with RSC and client side.
1. Press button to login with google
2. Google redirect happens, login successful
3. Returns to login page
4. Cookies are added
5. URL changes to redirect url but no navigation happens

My suspicion is that with Next the window.history.replaceState is not working to actually redirect the page (I looked this up and I think it doesn't cause a reload on the page).

What I had to do is in the example where the Hub listener is updating the user I will do a router.replace("/") to cause it to redirect, it has no relation to the uri in the redirect on the signin.

I think the window.history.replaceState will work on a React SPA just fine but not on Next 13/14 routing.

Is this a case where the signInWithRedirect might need a {ssr:true} or some option and have it return the redirect details so the handler in the app can handle the redirect.

**Comment by kicoo7** [comment] 2023-11-21 10:08
Can confirm, same thing happens to me.

**Comment by rogueturnip** [comment] 2023-11-21 17:09
My redirect logic I built didn't work correctly, was causing all sorts of issues so at this point social isn't really usable for any Next 13/14 projects.

**Comment by nadetastic** [comment] 2023-11-22 05:01
@rogueturnip Ok i think i understand, it sounds like you `redirectSignIn` parameter is in a subpath of the app (ie `/dashboard`) and when the sign in completes it remains at the root of the app instead of redirecting?

Confirming the same thing for you @kicoo7 ?

**Comment by kicoo7** [comment] 2023-11-22 16:13
@nadetastic I tried:
1. Redirecting to `/login-callback` (a route handler) that redirected to `/`
2. Redirecting directly to root `/`.

Both didn't work. So, now i'm redirecting to `/login-callback`, which then redirects to `/login`. And, I have a Hub.listener for `signIn` event which redirects to root.

**Comment by rogueturnip** [comment] 2023-11-22 16:22
The auth event works for signIn but won't work for redirectSignIn because no event seems to come from that.  If an event came from that we could use that for the redirect.

What I see when I'm testing is the URL is replaced with the redirectUrl (from the window.history.replaceState), with Next, if you have any logic in a client component it will throw a Client doesn't match Server error. Even if you don't have this the URL in the browser is replaced but no navigation happens.  I looked this up and window.history.replaceState doesn't cause a reload/refetch so with Next it just doesn't navigate.  I suspect with a React application no problem cause it's all client side.

I feel like the signInWithRedirect need to have an {ssr:true} option that skips the redirect internal to the code and returns the redirect URL that matches the requisition host (that's another problem I you have multiple redirect urls).  Let the Next application handle the redirect via a router.replace() or using Hub to watch for the event (be nice to see the event too).

**Comment by nadetastic** [comment] 2023-11-22 17:27
@kicoo7 @rogueturnip Can you confirm the following:
- What is the `redirectSignIn` defined in your `amplifyconfiguration.json`? (seems like /login-callback for @kicoo7 )
- Which routes are you calling `signInWithRedirect()` from?

**Comment by rogueturnip** [comment] 2023-11-23 00:31
In mine I have it defined to two routes
http://localhost:3000
https://<public domain>

I'm not sure what you mean "what route are you calling".  This is in my /signup route in my handler for oauth connection.  I pass in a provider to the handler.  It looks like this
```
  const handleOauthSignIn = async (provider) => {
    try {
      setGoogleLoading(true);
      await new Promise((resolve) => setTimeout(resolve, 500));
      await signInWithRedirect({ provider });
      // redirect is done by the oauth session using a window change but it breaks with server/client next
    } catch (error) {
      console.error("error signing in", error);
      setSignUpError("Unable to sign in");
      setGoogleLoading(false);
    } finally {
    }
  };
```
you can ignore the setGoogleLoading, that's there for a spinner and just temporary.

**Comment by kicoo7** [comment] 2023-11-23 08:08
> * redirectSignIn
@nadetastic
1. Yes. My redirectSignIn inside my config file is set to `/login-callback`.
2. The login and signup routes. (`/login` and `/signup`)

**Comment by kicoo7** [comment] 2023-11-23 08:10
FYI, I am signing in users via "custom providers" like GitHub. `await signInWithRedirect({ provider: { custom: "GitHub" } });`

**Comment by nadetastic** [comment] 2023-11-28 16:17
@kicoo7 can you try importing `signInWithRedirect` in the page that the user is redirected back to (/login-callback)?

**Comment by rogueturnip** [comment] 2023-11-29 17:52
I want to check if anyone has had suggest with Social and the new aws-amplify v6.

**Comment by nadetastic** [comment] 2023-11-29 22:22
@kicoo7 @rogueturnip thanks for your patience. I'm going to mark this as a bug as this is some unintended behavior.

In short, if your `redirectSignIn` path isn't the same as where you invoked `signInWithRedirect()` to authenticate the user, you will face this error. It's specific to NextJS, however there's a work around. You can create a function that wraps `signInWithRedirect()` (without calling it) on the same path as your `redirectSignIn` to get unblocked. We have identified a fix and are working through it, and will follow up soon, but let me know if you have any questions.

**Comment by itzcull** [comment] 2023-12-14 03:27
@nadetastic Are you able to explain this issue? I spent 3 days trying to figure out WTH was going on. Would it be possible to provide some utilities to handle the redirectURI on the server?

**Comment by Meags27** [comment] 2023-12-14 18:29
Oh wow I had no idea there was a temporary fix, I added it and it works. Hopefully in the future it can be integrated seamlessly so I don't need to leave a comment saying not to remove the random method lol

**Comment by nadetastic** [comment] 2023-12-20 20:50
@itzcull in short, `signInWithRedirect` has a sideEffect where if the redirect path doesn't have the chunk of code with signInWithRedirect, it will be tree shaken - this is for bundle size purposes - it's why this isn't an issue for SPAs but for SSR apps. Importing the function on the path that you are redirecting to makes sure that it is not tree shaken and allows the redirect to be processed/completed.

Please note that we are working on a fix for this and will follow up soon.

**Closed** 2024-02-01 16:47 UTC
Labels: bug, Auth, SSR, pending-response, V6

**Comment by Micheal-Winn** [comment] 2024-02-10 11:28
Hello @nadetastic 


> Hi all cc @rogueturnip @itzcull @Meags27,
> 
> Following up here - with the latest version of aws-amplify, this issue should now be resolved. For additional information on how to address this, please take alook at the documentation here - https://docs.amplify.aws/react/build-a-backend/auth/add-social-provider/#required-for-multi-page-applications-complete-social-sign-in-after-redirect
> 
> In short, you will need to import the oauth listener to the page that you are redirecting to if it is not the same page that `signInWithRedirect()` is invoke from.
> 
> ```js
> import 'aws-amplify/auth/enable-oauth-listener';
> ```
> 
> Let me know if you have any questions.

It does not work in Nextjs Page Directory.How can i fix those issue?

**Comment by AndresCi2** [comment] 2024-11-20 22:10
> ```js
> import 'aws-amplify/auth/enable-oauth-listener';
> ```

Have you found any answer about this error ?
