### ISSUE TITLE
Authed subscriptions not working

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#4683] opened 2020-01-08 16:58 UTC
I have been trying to get subscriptions working for a few days no to no avail.

I am using the most recent Angular and Amplify with the following model:

```
type Message @model
  @auth(rules: [
    { allow: owner },
    { allow: groups, groups: ["users"], operations: [read] },
    { allow: public, provider: iam, operations: [read] }
  ])
@key(name: "messageConvoKey", fields: ["messageConversationId", "createdAt"], queryField: "messagesByConvo") 
{
  id: ID!
  messageConversationId: ID!
  conversation: ConvoLink @connection(name: "ConvoMsgs")
  content: String!
  contentType: String
  author: ID!
  entity: ID!
  receiver: ID!
  status: String
  createdAt: Float!
  updatedAt: Float!
}
```

And am calling this method to subscribe, with nothing ever being returned:

```
 this.amplify.api().graphql(graphqlOperation(onCreateMessage))
      .subscribe((newMessage: any) => {
         console.log('NEW MESSAGE RECEIEVED');
         console.log(newMessage)
      }, 
      err => console.log(err))
```

I am passing the owner to the function (the cognito ID/username, and then creating a message with the owner field containing this ID and it never returns anything in the subscription.

If I then change the API and add '@model (subscriptions: { level: public })' to the model, the subscription works fine.

I need security on this, and given that the guide says to pass the owner ID to the subscription for successful subscription initiation, why is this not working?

**Comment by elorzafe** [comment] 2020-01-08 18:52
Thanks @oliverandersencox for your feedback. I am currently working on a fix for this in #4617 

Duplicate of #4602 so I will close but please look into the other issue when this is solved.

Thanks!

**Closed by elorzafe** 2020-01-08 18:52 UTC
Labels: Angular, DataStore, to-be-triaged
