### ISSUE TITLE
Documentation for ApolloClient with AMAZON_COGNITO_USER_POOLS 

### ISSUE THREAD

**Issue by rfdc** [aws-amplify/amplify-js#2231] opened 2018-12-02 09:33 UTC
Hi There,
My graphQL end point uses AMAZON_COGNITO_USER_POOLS. I had a look everywhere and cannot find the configuration for it w/ ApolloClient on amplify API, AWS or apollo.

I've successfully initialized my app with AWSAppSyncClient:
```
import awsmobile from '../aws-exports';
const client = new AWSAppSyncClient({
  url: awsmobile.aws_appsync_graphqlEndpoint,
  region: awsmobile.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    jwtToken: async () =>
      (await Auth.currentSession()).getIdToken().getJwtToken(),
  },
});
```

This is what I've tried for ApolloClient:
```
import awsmobile from '../aws-exports';
const client = new ApolloClient({
  uri: awsmobile.aws_appsync_graphqlEndpoint,
  header: {
    auth: {
      type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
      jwtToken: async () =>
        (await Auth.currentSession()).getIdToken().getJwtToken(),
    }
  }
});
```
But getting an error saying the header isn't correct.

Any doc/suggestion on how to config it?

Thanks

**Comment by manueliglesias** [comment] 2018-12-02 22:17
Hi @rfdc 

The `AWSAppSyncClient` initialization looks correct to me. What is the exact error message you are getting? Can you successfully query your API from the AppSync console (after login in)?

For apollo client, please take a look at their docs for [header-based auth](https://www.apollographql.com/docs/react/recipes/authentication.html#Header). The header you need to add is `"Authorization"` with the token as the value.

**Comment by manueliglesias** [comment] 2018-12-03 19:39
Duplicate of awslabs/aws-mobile-appsync-sdk-js#306

**Closed by manueliglesias** 2018-12-03 19:39 UTC
Labels: AppSync, question

**Comment by jkeys-ecg-nmsu** [comment] 2018-12-13 20:55
@manueliglesias maybe it's different using the AppSync SDK, but I just discovered that using Axios with user pool authorization, prepending "Bearer " to the access token results in a 401 unauthorized response from the AppSync endpoint. Once I removed that prepend out of frustration I started getting 200s back from AppSync.

Just FYI.
