### ISSUE TITLE
Does not appear notification icon in pinpoint sendmessages

### ISSUE THREAD

**Issue by koreahn** [aws-amplify/amplify-js#12853] opened 2024-01-17 08:52 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Version

v5

### Amplify Categories

notifications

### Backend

Amplify CLI

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 86.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
  npmPackages:
    @aws-amplify/rtn-push-notification: ^1.2.3 => 1.2.9 (1.1.9)
    @aws-amplify/ui-react-native: ^1.2.23 => 1.2.29 
    @azure/core-asynciterator-polyfill: ^1.0.2 => 1.0.2 
    @babel/core: ^7.20.0 => 7.23.6 
    @babel/preset-env: ^7.20.0 => 7.23.6 
    @babel/runtime: ^7.20.0 => 7.23.6 
    @lunalee/react-native-raw-bottom-sheet: ^2.2.4 => 2.2.4 
    @react-native-async-storage/async-storage: ^1.19.1 => 1.21.0 
    @react-native-community/netinfo: ^9.4.1 => 9.5.0 
    @react-native-firebase/analytics: ^18.7.3 => 18.7.3 
    @react-native-firebase/app: ^18.7.3 => 18.7.3 
    @react-native-firebase/crashlytics: ^18.7.3 => 18.7.3 
    @react-native/eslint-config: ^0.72.2 => 0.72.2 
    @react-native/metro-config: ^0.72.9 => 0.72.11 
    @react-navigation/material-bottom-tabs: ^6.2.16 => 6.2.19 
    @react-navigation/native: ^6.1.7 => 6.1.9 
    @react-navigation/native-stack: ^6.9.13 => 6.9.17 
    @tsconfig/react-native: ^3.0.0 => 3.0.2 
    @types/react: ^18.0.24 => 18.2.45 
    @types/react-test-renderer: ^18.0.0 => 18.0.7 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.1 => 6.3.8 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.6 => 5.3.13 
    aws-sdk: ^2.1450.0 => 2.1525.0 
    babel-jest: ^29.2.1 => 29.7.0 
    eslint: ^8.19.0 => 8.56.0 
    exampleapp:  0.0.1 
    jest: ^29.2.1 => 29.7.0 
    metro-react-native-babel-preset: 0.76.7 => 0.76.7 (0.76.8)
    prettier: ^2.4.1 => 2.8.8 
    react: 18.2.0 => 18.2.0 
    react-hook-form: ^7.45.4 => 7.49.2 
    react-native: 0.72.3 => 0.72.3 
    react-native-chart-kit: ^6.12.0 => 6.12.0 
    react-native-code-push: ^8.1.0 => 8.1.1 
    react-native-config: ^1.5.1 => 1.5.1 
    react-native-date-picker: ^4.3.3 => 4.3.5 
    react-native-geocoding: ^0.5.0 => 0.5.0 
    react-native-geolocation-service: ^5.3.1 => 5.3.1 
    react-native-get-random-values: ^1.9.0 => 1.10.0 
    react-native-image-picker: ^7.1.0 => 7.1.0 
    react-native-maps: ^1.7.1 => 1.8.4 
    react-native-maps-directions: ^1.9.0 => 1.9.0 
    react-native-safe-area-context: ^4.7.1 => 4.8.2 
    react-native-screens: ^3.24.0 => 3.29.0 
    react-native-sectioned-multi-select: ^0.10.0 => 0.10.0 
    react-native-select-dropdown: ^3.4.0 => 3.4.0 
    react-native-splash-screen: ^3.3.0 => 3.3.0 
    react-native-svg: ^13.13.0 => 13.14.0 
    react-native-upi-payment: ^1.0.5 => 1.0.5 
    react-native-url-polyfill: ^2.0.0 => 2.0.0 (1.3.0)
    react-native-vector-icons: ^10.0.0 => 10.0.3 
    react-test-renderer: 18.2.0 => 18.2.0 
    stream: ^0.0.2 => 0.0.2 
    typescript: 4.8.4 => 4.8.4 
  npmGlobalPackages:
    @aws-amplify/cli: 12.8.2
    appcenter-cli: 2.14.0
    corepack: 0.15.3
    create-expo-app: 2.0.3
    create-react-native-app: 3.8.0
    eas-cli: 3.12.1
    expo-cli: 6.3.10
    npm: 9.8.1

```

</details>

### Describe the bug

I can not display an icon in the push notification

### Expected behavior

Icons should be displayed normally in the notification window.

### Reproduction steps

1. Install react-native app
2. install AWS CLI and services
3. send push notification by AWS Pinpoint

### Code Snippet

```javascript
// Put your code below this line.
  const sendPushNotifications = (token, status, navi, userData) => {
    const messageRequest = CreateMessageRequest(token, status, navi, userData);

    AWS.config.update({
      region: region,
      apiVersion: 'latest',
      credentials: {
        accessKeyId: Config.AWS_ACCESS_KEY,
        secretAccessKey: Config.AWS_SECRET_KEY,
      },
    });

    const params = {
      ApplicationId: Config.PINPOINT_APP_ID,
      MessageRequest: messageRequest,
    };

    const pinpoint = new AWS.Pinpoint();

    pinpoint.sendMessages(params, function (err, data) {
      if (err) console.error(err);
      else {
      }
    });
  };

  const CreateMessageRequest = (token, status, navi, userData) => {
    const recipientPushToken = token;
    const title = 'title';
    const body = 'body';

    const messageRequest = {
      Addresses: {
        [recipientPushToken]: {
          ChannelType: 'GCM',
        },
      },
      MessageConfiguration: {
        GCMMessage: {
          Action: 'OPEN_APP',
          RawContent: JSON.stringify({
            notification: {
              title: title,
              body: body,
              ImageUrl:
                'https://domain/ic_notification.png',
              ImageIconUrl:
                'https://domain/ic_notification.png',
              SmallImageIconUrl:
                'https://domain/ic_notification.png',
            },
            data: {
              message: body,
              title: title,
              navi: navi,
              userData: userData,
              ImageUrl:
                'https://domain/ic_notification.png',
              ImageIconUrl:
                'https://domain/ic_notification.png',
              SmallImageIconUrl:
                'https://domain/ic_notification.png',
            },
          }),
          ImageUrl:
            'https://domain/ic_notification.png',
          ImageIconUrl:
            'https://domain/ic_notification.png',
          SmallImageIconUrl:
            'https://domain/ic_notification.png',
        },
      },
    };
    return messageRequest;
  };

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

I searched the Internet and saw that I should use ImageUrl, ImageIconUrl, and SmallImageIconUrl, but I didn't know where to place it, so I added all 3 places.(Even when I added one each, the icon doesn't appear the same.)

But even after adding ImageIconUrl, ImageSmallIconUrl, and ImageUrl, the icon is not appearing.

And what should be the size(width, height) of each of the three icons?

If anyone has any insights on this, please let me know. I would appreciate your help.

**Comment by cwomack** [comment] 2024-01-17 18:29
Hey there, @koreahn 👋.  It looks like this issue is a duplicate of the feature request captured in #12004.  To ensure we can consolidate the context and feedback for this, I'm going to close this one in favor of the older issue.  Feel free to add any comments or suggestions on #12004 as well, but I've linked them on our side as well to ensure any work done on this feature has both issues considered.  Thanks!

**Closed by cwomack** 2024-01-17 18:29 UTC
Labels: feature-request, investigating, Push Notifications, React Native
