### ISSUE TITLE
PreSignup lambda trigger error conditions no longer being passed to the front end

### ISSUE THREAD

**Issue by tcchau** [aws-amplify/amplify-js#3778] opened 2019-07-31 20:25 UTC
**Describe the bug**
We are using AWS Amplify with hosted UI to sign in users from social providers such as Google. 

In previous versions of AWS Amplify when we use CognitoAuth.parseCognitoWebResponse() to process the result from Cognito's hosted UI server, we would be able to pass back error conditions if they occur in the PreSignup lambda trigger. We use this to communicate back to the frontend, for example, that a user using Google to sign in for the first time, already has a Cognito account under the same email address. This way, we can inform the user and let them make a decision as to what to do next. This error message used to be encoded in the URL in the 'error_description' query parameter, and who reflect the object that we throw, in the object's "code" attribute. For example, the error_description parameter in the redirect URL would be something like, "PreSignUp failed with error [code]".

This is no longer the case when we use the latest version of AWS Amplify where we are using the Hub event processor. Instead we always get a generic, "Exception processing authorization code".

Can you please help us figure out how to get the necessary information we need? 

**To Reproduce**
1. Create a Cognito User Pool that allows login from Google Sign In.
2. Configure a PreSignUp Lambda trigger
3. Make the trigger return an error

**Expected behavior**
The callback URL from the hosted UI server will have the query parameter error_description say something like, "PreSignUp trigger failed with error message <our error message here>"

Instead we get "Exception processing authorization token"... which is kind of true -- we're saying there was an error when Cognito calls the PreSignUp Lambda trigger... but we need the actual error information.

We suspect this is a bug in the underlying Cognito service, rather than AWS Amplify, as AWS Amplify is just passing back what it receives.

***You can turn on the debug mode to provide more info for us by setting 
ConsoleLogger.js:111 [DEBUG] 23:41.31 AuthClass - Error in cognito hosted auth response Error: Exception+processing+authorization+code
    at OAuth.<anonymous> (OAuth.js:384)
    at step (OAuth.js:149)
    at Object.next (OAuth.js:79)
    at OAuth.js:51
    at new Promise (<anonymous>)
    at push../node_modules/@aws-amplify/auth/lib/OAuth/OAuth.js.__awaiter (OAuth.

**Comment by srinivasaravind5** [comment] 2019-10-15 12:14
Any updates on this ?

**Comment by tcchau** [comment] 2019-10-16 23:46
@srinivasaravind5 I never got a confirmation either way, but from my own use and testing of Cognito, they seemed to have restored the former behaviour, i.e. it's now possible to receive more specific error messages, other than just a general exception, from the Cognito backend. For example, I can return specific/custom error conditions from my PreTokenGeneration lambda.

To project maintainers: I'm not sure if it's appropriate to close this ticket out; please provide guidance if you have any. Thanks!

**Comment by Amplifiyer** [comment] 2019-10-23 21:32
@tcchau, if the issue is resolved for you, I'll close this ticket. If you are facing similar issue in the future, you can ask in cognito forums as well https://forums.aws.amazon.com/forum.jspa?forumID=173

**Closed by Amplifiyer** 2019-10-23 21:32 UTC
Labels: Auth, Cognito, Service Team, to-be-triaged
