### ISSUE TITLE
Getting "no current user" while i am navigating from a screen to another screen in aws-amplify-react-native

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6046] opened 2020-06-10 07:18 UTC
Getting "no current user" while i am navigating from a screen to another screen in aws-amplify-react-native.

I am using Auth.currentSession() from amplify and Authenticator from aws-amplify-react-native.

Here my package .json shows the version as 

```
"aws-amplify": "^3.0.11",
 "aws-amplify-react-native": "^4.1.2",
 "aws-sdk": "^2.681.0",
```

But the yarn list shows
```
//refer below

├─ aws-amplify-react-native@4.2.0
├─ aws-amplify@3.0.13
├─ aws-sdk@2.687.0
└─ aws-sign2@0.7.0
```

```
yarn list v1.22.4
├─ @aws-amplify/analytics@3.1.12
├─ @aws-amplify/api-graphql@1.0.14
├─ @aws-amplify/api-rest@1.0.14
├─ @aws-amplify/api@3.1.12
├─ @aws-amplify/auth@3.2.9
├─ @aws-amplify/cache@3.1.12
├─ @aws-amplify/core@3.2.9
├─ @aws-amplify/datastore@2.1.2
├─ @aws-amplify/interactions@3.1.12
├─ @aws-amplify/predictions@3.1.12
├─ @aws-amplify/pubsub@3.0.13
├─ @aws-amplify/storage@3.2.2
├─ @aws-amplify/ui@2.0.2
├─ @aws-amplify/xr@2.1.12
├─ @aws-crypto/crc32@1.0.0-alpha.0
├─ @aws-crypto/ie11-detection@1.0.0-alpha.0
├─ @aws-crypto/sha256-browser@1.0.0-alpha.0
├─ @aws-crypto/sha256-js@1.0.0-alpha.0
├─ @aws-crypto/supports-web-crypto@1.0.0-alpha.0
├─ @aws-sdk/abort-controller@1.0.0-gamma.1
├─ @aws-sdk/chunked-blob-reader-native@1.0.0-gamma.1
├─ @aws-sdk/chunked-blob-reader@1.0.0-gamma.1
├─ @aws-sdk/client-cognito-identity@1.0.0-gamma.2
├─ @aws-sdk/client-comprehend@1.0.0-gamma.2
├─ @aws-sdk/client-firehose@1.0.0-gamma.2
├─ @aws-sdk/client-kinesis@1.0.0-gamma.2
├─ @aws-sdk/client-lex-runtime-service@1.0.0-gamma.2
├─ @aws-sdk/client-personalize-events@1.0.0-gamma.2
├─ @aws-sdk/client-pinpoint@1.0.0-gamma.2
├─ @aws-sdk/client-polly@1.0.0-gamma.2
├─ @aws-sdk/client-rekognition@1.0.0-gamma.2
├─ @aws-sdk/client-s3@1.0.0-gamma.2
├─ @aws-sdk/client-textract@1.0.0-gamma.2
├─ @aws-sdk/client-translate@1.0.0-gamma.2
├─ @aws-sdk/config-resolver@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.2
├─ @aws-sdk/credential-provider-env@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-imds@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-ini@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-node@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-process@1.0.0-gamma.1
├─ @aws-sdk/eventstream-marshaller@1.0.0-gamma.1
├─ @aws-sdk/eventstream-serde-browser@1.0.0-gamma.1
├─ @aws-sdk/eventstream-serde-config-resolver@1.0.0-gamma.1
├─ @aws-sdk/eventstream-serde-node@1.0.0-gamma.1
├─ @aws-sdk/fetch-http-handler@1.0.0-gamma.2
├─ @aws-sdk/hash-blob-browser@1.0.0-gamma.1
├─ @aws-sdk/hash-node@1.0.0-gamma.1
├─ @aws-sdk/hash-stream-node@1.0.0-gamma.1
├─ @aws-sdk/invalid-dependency@1.0.0-gamma.1
├─ @aws-sdk/is-array-buffer@1.0.0-gamma.1
├─ @aws-sdk/md5-js@1.0.0-gamma.1
├─ @aws-sdk/middleware-apply-body-checksum@1.0.0-gamma.1
├─ @aws-sdk/middleware-bucket-endpoint@1.0.0-gamma.1
├─ @aws-sdk/middleware-content-length@1.0.0-gamma.1
├─ @aws-sdk/middleware-expect-continue@1.0.0-gamma.1
├─ @aws-sdk/middleware-header-default@1.0.0-gamma.1
├─ @aws-sdk/middleware-host-header@1.0.0-gamma.1
├─ @aws-sdk/middleware-location-constraint@1.0.0-gamma.1
├─ @aws-sdk/middleware-retry@1.0.0-gamma.1
├─ @aws-sdk/middleware-sdk-s3@1.0.0-gamma.1
├─ @aws-sdk/middleware-serde@1.0.0-gamma.1
├─ @aws-sdk/middleware-signing@1.0.0-gamma.1
├─ @aws-sdk/middleware-ssec@1.0.0-gamma.1
├─ @aws-sdk/middleware-stack@1.0.0-gamma.1
├─ @aws-sdk/middleware-user-agent@1.0.0-gamma.1
├─ @aws-sdk/node-http-handler@1.0.0-gamma.1
├─ @aws-sdk/property-provider@1.0.0-gamma.1
├─ @aws-sdk/protocol-http@1.0.0-gamma.1
├─ @aws-sdk/querystring-builder@1.0.0-gamma.1
├─ @aws-sdk/querystring-parser@1.0.0-gamma.1
├─ @aws-sdk/region-provider@1.0.0-gamma.1
├─ @aws-sdk/s3-request-presigner@1.0.0-gamma.1
├─ @aws-sdk/service-error-classification@1.0.0-gamma.1
├─ @aws-sdk/shared-ini-file-loader@1.0.0-gamma.1
├─ @aws-sdk/signature-v4@1.0.0-gamma.1
├─ @aws-sdk/smithy-client@1.0.0-gamma.1
├─ @aws-sdk/types@1.0.0-gamma.1
├─ @aws-sdk/url-parser-browser@1.0.0-gamma.1
├─ @aws-sdk/url-parser-node@1.0.0-gamma.1
├─ @aws-sdk/util-base64-browser@1.0.0-gamma.1
├─ @aws-sdk/util-base64-node@1.0.0-gamma.1
├─ @aws-sdk/util-body-length-browser@1.0.0-gamma.1
├─ @aws-sdk/util-body-length-node@1.0.0-gamma.1
├─ @aws-sdk/util-buffer-from@1.0.0-gamma.1
├─ @aws-sdk/util-create-request@1.0.0-gamma.1
├─ @aws-sdk/util-format-url@1.0.0-gamma.1
├─ @aws-sdk/util-hex-encoding@1.0.0-gamma.1
├─ @aws-sdk/util-locate-window@1.0.0-gamma.1
├─ @aws-sdk/util-uri-escape@1.0.0-gamma.1
├─ @aws-sdk/util-user-agent-browser@1.0.0-gamma.1
├─ @aws-sdk/util-user-agent-node@1.0.0-gamma.1
├─ @aws-sdk/util-utf8-browser@1.0.0-gamma.1
├─ @aws-sdk/util-utf8-node@1.0.0-gamma.1
├─ @aws-sdk/xml-builder@1.0.0-gamma.1
├─ aws-amplify-react-native@4.2.0
├─ aws-amplify@3.0.13
├─ aws-sdk@2.687.0
└─ aws-sign2@0.7.0
✨  Done in 1.48s.
```

**Comment by Ashish-Nanda** [comment] 2020-06-11 11:32
Closing this issue as its a duplicate of #6015 which is being tracked.

**Closed by Ashish-Nanda** 2020-06-11 11:32 UTC
Labels: React Native, to-be-reproduced
