### ISSUE TITLE
Auth.updateUserAttribute sends a verification code

### ISSUE THREAD

**Issue by chantlong** [aws-amplify/amplify-js#6755] opened 2020-09-09 03:05 UTC
I have trouble understanding the point of this method sending a verification code, when...
1. the method updates the attribute anyways regardless if you use the verification code or not.

Am I missing something?

This happens when I update the `email` attribute.

**Comment by harrysolovay** [comment] 2020-09-09 18:04
@chantlong `email` is a verifiable attribute (as is `phone_number`). This is the correct behavior––especially if email serves as the `username` for authenticating users (how is your user pool configured)?

**Comment by chantlong** [comment] 2020-09-10 03:49
@harrysolovay My `email` is used as a username. I understand it is verifiable attribute, but even if I do not verify the `email` attribute (ignoring the verification code), I was able to login my account with the new email with no problem.

This brings me to the question what `email_verified` being `false` prevents you from doing?

**Comment by harrysolovay** [comment] 2020-09-11 19:07
If you want Cognito to save user emails without the need for verification, my recommendation is that you configure a custom attribute `custom:email`. You can then use a `pre-sign-up` lambda trigger to set the initial value for this custom attribute, and then update it at your leisure, without the verification.

As for what `email_verified` prevents you from doing: depends on your own business logic. Usually, this has some bearing on how you configure notifications (assuming your service sends notifications).

Closing this out, as this is the intended behavior.

**Closed by harrysolovay** 2020-09-11 19:07 UTC
Labels: Auth, question, to-be-reproduced

**Comment by tatighm** [comment] 2020-11-18 22:41
@harrysolovay Hi there, do you know what Auth call I need to make to resend the verification code to the user after they successfully change their email address? I can't find the call anywhere. I do want my users to verify the new email address, but if the code expires, or they never received it, how do I resend this code? Calling resendSignUp does not apply since they are not signing-up, but changing their existing email address. Thanks.

**Comment by tatighm** [comment] 2020-11-18 22:52
@harrysolovay So sorry, I found it on my own. It is the Auth.verifyUserAttribute call.
