### ISSUE TITLE
Is there a forgot username method in the api?

### ISSUE THREAD

**Issue by appjitsu** [aws-amplify/amplify-js#3445] opened 2019-06-13 07:23 UTC
** Which Category is your question related to? **
no idea what this means

** What AWS Services are you utilizing? **
amplify/cognito

** Provide additional details e.g. code snippets **
none

I am really enjoying working with Amplify so far. I have my custom auth flow working including resetting passwords via the verification code. 

What happens when the user has forgotten their username? Is there a forgot username method in the api? I don't see one in the docs...

I could simply save the username in local storage, but what if they are logging in from another device or computer?

**Comment by haverchuck** [comment] 2019-06-13 15:11
@appjitsu I do not believe we have this capability, but I will be speaking with the service team about it.  This is a great feature request. Thanks!

**Comment by tannerabread** [comment] 2022-11-29 17:39
Closing as a duplicate of #5851. More context on that issue so we will track through that feature request instead

**Closed by tannerabread** 2022-11-29 17:39 UTC
Labels: feature-request, Auth, Cognito
