### ISSUE TITLE
DataStore update missing @auth property in generated graph QL update mutator inputs

### ISSUE THREAD

**Issue by juanlucky** [aws-amplify/amplify-js#7660] opened 2021-01-31 20:58 UTC
**Which Category is your question related to?**
Amplify CLI, DataStore, auth, GraphQL API

**Amplify CLI Version**
4.41.2

**What AWS Services are you utilizing?**
Amplify CLI, Datastore, AppSync, Cognito User Pools, Vue.js webapp

**Provide additional details**
Hello, I have the following GraphQL model :
`type Movie @model
    @auth(rules: [{ allow: owner }])  
    @key(fields: ["owner","id"]) {
  id: ID!
  owner:String!
  title: String!
  isNew: Boolean 
}`
I generated with `amplify add api` and `amplify push` a corresponding serverless graphQL API .

Then I use within a Vue.js app (using <amplify-authenticator>) the following javascript code :
`let newMovies = await DataStore.query(Movie,  m => m.isNew("eq", true) )
 for (let movie of newMovies){
     await DataStore.save(Movie.copyOf(movie, updated => {
          updated.isNew = false;}));
      }`

The local storage update is working fine but the cloud update synchronization fails with the following warning :
`[WARN] 23:37.623 DataStore {localModel: Model, message: "Variable 'input' has coerced Null value for NonNull type 'String!'", operation: "Update", …}`

Looking into the body of the update AppSync request API shows that the "owner" mandatory attribute (used in @auth directive) is not generated by the DataStore.save()  :
`{"query":"mutation operation($input: UpdateMovieInput!, $condition: ModelMovieConditionInput) {\n  updateMovie(input: $input, condition: $condition) {\n    id\n    owner\n    title\n    rating\n    gender\n    year\n    synopsis\n    director\n    actors\n    nationality\n    duration\n    imageUrl\n    sourceUrl\n    scrapingDate\n    lastDisplayDate\n    isNew\n    isToDownload\n    downloadStatus\n    downloadError\n    downloadedFilename\n    downloadedFileMoveStatus\n    downloadedFileMoveDest\n    versions\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n","variables":{"input":{"id":"41e2380a-df40-43f0-a281-42d527d636d7","isNew":false,"_version":3},"condition":null}}`

So the serverside corresponding DynamoDB is not updated.

**Comment by iartemiev** [comment] 2021-02-01 23:50
Hey @juanlucky, you should be able to fix this by making the `owner` field in your schema optional:
```gql
type Movie @model @auth(rules: [{ allow: owner }]) @key(fields: ["owner","id"]) 
{ 
  id: ID! 
  owner:String 
  title: String! 
  isNew: Boolean 
}
```
This way, the AppSync resolver will still set it correctly when you perform a mutation, however, the mutation input will not require you to pass it in.

**Comment by sammartinez** [comment] 2021-05-18 15:34
@juanlucky, 

We are going to close this issue since we have not heard from you. 

Please let us know if you are still needing support, provide steps to reproduce, and we can reopen the issue to investigate further.

Thanks

**Closed by sammartinez** 2021-05-18 15:34 UTC
Labels: DataStore, pending-close-response-required
