### ISSUE TITLE
value keyword for GraphQL and Angular

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-js#2532] opened 2019-01-14 08:29 UTC
Hi,

There is a property "value" in GraphQL JSON responses BUT "value" is an Angular keyword for data binding with hashtag TOO.

Rudy.

**Comment by haverchuck** [comment] 2019-01-14 16:39
@rudyhadoux Can you please post an example response?  Also - are you using the AppSync SDK or graphqlOperation in Amplify?

**Comment by rudyhadoux** [comment] 2019-01-14 16:54
I do not know if "value" is an Angular or Typescript keyword but it is duplicated with value of GraphQL response.

If you see this video :
https://www.youtube.com/watch?v=nAYikoFCN4k
At 8min01, "value" is underlined with Visual Studio Code.

This example is maybe not a good piece of code. But however, it is a duplicated keyword of two different technologies.

**Comment by haverchuck** [comment] 2019-01-14 17:04
@rudyhadoux Is this causing any errors or problems in your applicaiton?

**Comment by rudyhadoux** [comment] 2019-01-14 17:23
If we follow the code of the video, it generates an error yes.
But this code is not a good mapping practice.

**Comment by haverchuck** [comment] 2019-01-14 23:13
@rudyhadoux  -  It's tought to tell exactly what's going on in the video without access to their codebase, but I think the underlining in the youtube video might be caused by their typescript expecting a graphqlresult instead of a graphql result within value parameter in the subscription. I don't think there is much we can do for this issue on our end, because I think the value and provider keys are pretty standard.  If this causes a problem in the Angular's template, it should be possible to remove the value key it gets passed to the Angular template, which could be good in any case for readability.

I'm closing this issue for now, but please reopen if you disagree with this assessment.

**Closed by haverchuck** 2019-01-14 23:13 UTC
Labels: Angular, GraphQL, pending-close-response-required, question

**Comment by rudyhadoux** [comment] 2019-01-15 07:45
I think duplicated reserved key-word is bad but it is non-blocking. And no problem with good mapping practices. The code of the video's author is here :
https://github.com/mjzone/appsync-amplify
