### ISSUE TITLE
FromData request support

### ISSUE THREAD

**Issue by emad-ir** [aws-amplify/amplify-js#2846] opened 2019-03-12 09:31 UTC
**FormData requests**

Amplify API version 1.0.26 doesn't add the FormData on the request made with API.post()

**Additional context**
I am trying to post the files using the javascript FormData, but when inspect the Network tab the request goes throw without the form data.

**My frontend react code**

```javascript
var formData = new FormData();
formData.append("document", file)

const API_INIT = {
     content: formData,
      headers: {
         'Content-Type': 'multipart/form-data'
      }
} 
API.post('backend', 'uploadDocument', API_INIT).then(result => {
   console.log(result)
})
```

Is posting formData not supported on amplify-js?

**Comment by jordanranz** [comment] 2019-03-13 23:31
I believe this is currently not supported. 

Duplicate here: https://github.com/aws-amplify/amplify-js/issues/1437

**Comment by manueliglesias** [comment] 2019-03-22 19:58
Closing as duplicate of #1437

**Closed by manueliglesias** 2019-03-22 19:58 UTC
Labels: API, feature-request
