### ISSUE TITLE
Wrong schema? Type mismatch for Index Key

### ISSUE THREAD

**Issue by benjamin79** [aws-amplify/amplify-js#4634] opened 2019-12-24 13:58 UTC
When i use:

```
await DataStore.save(
          new User({
            firstname: "John",
            lastname: "Doe"
          })
        )
```
The request to the graphql api in appsync contains: userStatusId: null. I don´t want that field at the time of creating a user. So how do i get rid of it? A user can have one status. A status can be in many users. When i query with `DataStore.query(User)` I´d like to have all the relational fields like status in it. This parts works when using the schema below.

```
type User @model {
  id: ID!
  firstname: String
  lastname: String!
  status: Status @connection(name: "StatusUsers")
}

type Status @model {
  id: ID!
  users: [User] @connection(name: "StatusUsers")
  name: String
}
```
thanks

**Comment by Soek22** [comment] 2020-01-03 12:24
Hi! I have reported the same Ne API/Datastore plugins behaviour miss-alignment here: https://github.com/aws-amplify/amplify-cli/issues/3109

**Comment by ashika01** [comment] 2020-01-07 19:33
@benjamin79 Where are you getting the `Type mismatch index key error`? Do you have sample code or repo?

**Comment by benjamin79** [comment] 2020-01-09 08:57
I get the error in the browser console when i run Datastore.save... You just can add the models above from a project you already have and run the Datastore.save and you see the error. But i can make a repo next week if you still need it.

Don´t you think it might be the reason what Soek22 described?

**Comment by Soek22** [comment] 2020-01-09 11:49
@ashika01 I am getting exactly same error on Amplify-iOS plugin, as stated here: https://github.com/aws-amplify/amplify-ios/issues/284  (with references to the source code where the problem is located)

I think it is a behaviour miss-alignment that breaks previously deployed backends, making them unable to work with the new API/Datastore plugins. Because of that, I have opened a more "generic" issue on the amplify-cli repo: https://github.com/aws-amplify/amplify-cli/issues/3109

**Comment by manueliglesias** [comment] 2020-02-02 23:12
Thanks, we'll look into this together with the CLI to better support previously deployed backends

**Comment by ashika01** [comment] 2020-03-13 19:44
Closing this issue since it has to be tracked from **Amplify CLI**. https://github.com/aws-amplify/amplify-cli/issues/3109.

**Closed by ashika01** 2020-03-13 19:44 UTC
Labels: DataStore, bug
