### ISSUE TITLE
Possible unhandled promise rejection (): type error: object is not a function

### ISSUE THREAD

**Issue by elkee2003** [aws-amplify/amplify-js#11299] opened 2023-04-25 00:23 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1numcdmic2hvt

### AWS Region

eu-west-2

### Amplify Hosting feature

Access logs

### Describe the bug

P
![Screenshot (6)](https://user-images.githubusercontent.com/42178058/234143049-06353959-a0c9-40d2-9471-6fb08f1694ad.png)
Possible unhandled promise rejection (): typeerror: object is not a function

### Expected behavior

It was meant to pick the sub (which is a field in the User) of the user and it was going to be equal to sub

### Reproduction steps

1. I import DataStore from aws-amplify
2. I access my User object in my models
3. I use useEffect to try to query the sub (which is a field in the User) of User
4. I save
5. I get the error

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2023-04-25 18:51
Closing as a duplicate of https://github.com/aws-amplify/amplify-js/issues/11298

**Closed by chrisbonifacio** 2023-04-25 18:51 UTC
Labels: DataStore, pending-triage
