### ISSUE TITLE
Unknown error, the response body from fetch is: undefined when using withAuthenticator HOC on android

### ISSUE THREAD

**Issue by mateen-hussain** [aws-amplify/amplify-js#1406] opened 2018-08-07 14:19 UTC
Do you want to request a feature or report a bug?
Report Bug

What is the current behavior?
When I use withAuthenticator(app) out of the box on the android I get. This happens ONLY on android simulator and not iOS
```
Object {
15:04:52:   "code": "UnknownError",
15:04:52:   "message": "Unknown error, the response body from fetch is: undefined",
15:04:52: }
```

my App (App was built with `create-react-native-app` and run on emulators with `expo`)

```
import React from 'react';
import { Provider } from 'react-redux';
import { AppRegistry } from 'react-native';
import Amplify from 'aws-amplify';
import { withAuthenticator } from 'aws-amplify-react-native';
import store from './src/store/store';
import ReduxNavigation from './src/RootNavigation/index';
import awsmobile from './aws-exports';

Amplify.configure(awsmobile);

const Root = () => (
	<Provider store={store}>
		<ReduxNavigation />
	</Provider>
);

AppRegistry.registerComponent('Test-UI', () => Root);

export default withAuthenticator(Root);

export default Root;
```

I tried removing `withAuthenticator` and use `Auth.signIn` instead

```
<Button onPress={
  ()=>{
		Auth.signIn('email@gmail.com','Pass1234(ABcd')
			.then(user=> console.log(user))
			.catch(err => console.log(err));
	}}
  title='Sign in'
/>
```

and I still see the same behaviour.

my package dependencies

```
    "amazon-cognito-identity-js": "^2.0.20",
    "aws-amplify": "^1.0.5",
    "aws-amplify-react-native": "^1.0.5",
    "aws-sdk": "^2.287.0",
    "expo": "25.0.0",
    "prop-types": "15.6.0",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-datepicker": "1.6.0",
    "react-native-elements": "1.0.0-beta2",
    "react-native-scrollable-tab-view": "0.8.0",
    "react-navigation": "^1.0.0",
    "react-navigation-redux-helpers": "1.0.1",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0"
```

I installed `amazon-cognito-identity-js` and `aws-sdk` after searching for some forums, but still no effect. Some forums report to polyfill the inbuilt `fetch` with `node-fetch` package. And I am not sure how to do this. Quite new to mobile development.

**Comment by powerful23** [comment] 2018-08-07 19:00
@mateen-hussain maybe it's not related but can you remove the `aws-sdk` dependency in your `package.json`? Amplify has its own dependency on `aws-sdk`.

**Comment by mateen-hussain** [comment] 2018-08-07 19:34
@powerful23 when I first tried it, there was no referece to `aws-sdk` in the package.json and it still gave the same behaviour

**Comment by rogerioc** [comment] 2018-08-08 14:24
Hello, I could to do work using this libs inside android project 
implementation ('com.amazonaws:aws-android-sdk-cognitoauth:2.6.+@aar') { transitive = true }
implementation ('com.amazonaws:aws-android-sdk-auth-core:2.6.+@aar') { transitive = true }
implementation ('com.amazonaws:aws-android-sdk-auth-ui:2.6.+@aar') { transitive = true }
implementation ('com.amazonaws:aws-android-sdk-cognitoauth:2.6.+@aar') { transitive = true }
But now I have a problem with sdk version, I need use android min 19 and the last aws api use min 23.

**Comment by aaayushsingh** [comment] 2018-08-12 21:50
I usually see this error when the network connection on the device is unstable/not working. Can you verify if the network is fine?

**Comment by raghulXander** [comment] 2018-08-29 09:18
same issue here in Node 8.11 with aws-sdk and amazon-cognito-identity-js

**Comment by TheNew000** [comment] 2018-09-07 17:40
I'm getting this same error from a web app.  Has anyone discovered the solution to this?

**Comment by novellizator** [comment] 2018-10-25 13:19
had the same issue with `cognitoUser.getUserAttributes`. my hack: i found the data _was_ fetched in the internal structures, despite triggering the error. So I am accessing the internal properties (in my case user attributes) through good old dot notation

**Comment by giginkrishnan** [comment] 2018-11-09 22:16
Any help on this ?

**Comment by SaidTayebi** [comment] 2018-11-24 18:06
Hello,

Did anyone resolve this ? I have the same issue on Node.js

**Comment by jordanranz** [comment] 2019-04-26 18:00
The "Unknown Error" message has been changed to display the actual error message in this PR:
https://github.com/aws-amplify/amplify-js/pull/2181

This should help you understand what the issue is. I will close this issue for now. Please reopen if you have any further questions or concerns.

**Closed by jordanranz** 2019-04-26 18:00 UTC
Labels: Auth, React Native
