### ISSUE TITLE
Auth.currentAuthenticatedUser() fails to recognize an authenticated user that was signed using Auth.federatedSignIn({provider: 'Google'}) in a Next.js application

### ISSUE THREAD

**Issue by vishal-dms** [aws-amplify/amplify-js#9745] opened 2022-03-29 01:47 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 541.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox: 91.6.1
    Safari: 15.4
  npmPackages:
    @aws-amplify/ui-react: 2.11.0 => 2.11.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: 4.3.17 => 4.3.17 
    babel-loader:  undefined ()
    cache-loader:  undefined ()
    chalk:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    dotenv:  undefined ()
    dotenv-expand:  undefined ()
    emotion: 10.0.27 => 10.0.27 
    escape-string-regexp:  undefined ()
    etag:  undefined ()
    file-loader:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    nanoid:  undefined ()
    next: 9.5.3 => 9.5.3 
    node-fetch:  undefined ()
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    raw-body:  undefined ()
    react: 16.13.1 => 16.13.1 (17.0.2)
    react-dom: 16.13.1 => 16.13.1 
    recast:  undefined ()
    resolve:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    terser:  undefined ()
    terser-webpack-plugin:  undefined ()
    text-table:  undefined ()
    thread-loader:  undefined ()
    unistore:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.26
    corepack: 0.10.0
    firebase-tools: 10.2.2
    npm: 8.3.1

```

</details>

### Describe the bug

In a Next.js SSR application, when a user signs in to the application using `Auth.federatedSignIn({provider: 'Google'}`),  post a successful authentication, `Auth.currentAuthenticatedUser()` fails to recognise the same. The issue persists in both client as well as server-side routes

### Expected behavior

`Auth.currentAuthenticatedUser()` should work as expected for both a userpool user as well as a federated user in both client-side as well as server-side routes

### Reproduction steps

1. Follow the steps for creating a sample Next.js SSR application with authentication as mentioned [here](https://github.com/dabit3/next.js-authentication-aws) 
2. Replace the pages/profile.js (also replace existing username and password in the code for an existing user in the Cognito userpool) and pages/protected.js with the code mentioned in the snippet section below
3. Run the application on your local machine and try signing in using the "SignIn User" button and access both Protected SSR route as well as Protected Client route which should work as expected and should be able to see the User object attributes on the Profile page.
4. Now,  sign out and sign in using "Federate User" button and then access both Protected SSR route as well as Protected Client route and you should see that you are being redirected back to Profile with a 302 Redirection (can we checked in the browser dev-tools) as well as see the User object as None

### Code Snippet

Profile.js
```javascript
// pages/profile.js
import { useState, useEffect } from 'react';
import Amplify, { Auth } from 'aws-amplify'

Amplify.Logger.LOG_LEVEL = 'DEBUG'

function Profile() {
  const [user, setUser] = useState(null);
  useEffect(() => {
    Auth.currentAuthenticatedUser()
      .then(user => {
        console.log("User: ", user)
        setUser(user)
      })
      .catch((error) =>{
        console.log("Error: ", error) 
        setUser(null)})
  }, []);
  
  return (
    <div>
    <p>User: {user ? JSON.stringify(user.attributes) : 'None'}</p>
    {user ? (
      <button onClick={() => Auth.signOut()}>Sign Out</button>
    ) : (
      <div>
      <button onClick={() => {Auth.federatedSignIn({provider: 'Google'})}}>Federate User</button>
      <button onClick={() => {Auth.signIn("SampleUser", "TheirPassword")}}>SignIn User</button>
      <button onClick={() => {Auth.signOut()}}>Sign Out</button>
      </div>
    )}
  </div>
  )
}


export default Profile;
```
Protected.js
```javascript
// pages/protected.js
import { withSSRContext } from "aws-amplify";

function Protected({ username }) {
  if (!username) return null;
  return <h1>Hello {username} from SSR route!</h1>;
}

/*
A more secure way is using SSR and server side redirects.
*/
export async function getServerSideProps({ req, res }) {
  const { Auth } = withSSRContext({ req });
  try {
    const user = await Auth.currentAuthenticatedUser();
    return {
      props: {
        authenticated: true,
        username: user.username,
      },
    };
  } catch (err) {
    /* This creates an error */
    // res.writeHead(302, { Location: "/profile" });
    // res.end();
    /* This is workaround for above until fixed */
    res.setHeader("Location", "/profile");
    res.statusCode = 302;
  }
  return { props: {} };
}

export default Protected;
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxxx-xxxx-xxxx-xxxx-xxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XXXXX",
    "aws_user_pools_web_client_id": "xxxxxxxxxx",
    "oauth": {
        "domain": "nextauthenticationXXXXX-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/protected/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

```

### Additional configuration

package.json
```json
{
  "name": "next-authentication",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "2.11.0",
    "aws-amplify": "4.3.17",
    "emotion": "10.0.27",
    "next": "9.5.3",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
}

```

### Additional information and screenshots
The profile.js snippet when used in a sample React application where we copy the same aws-exports.js, works as expected

**Comment by chrisbonifacio** [comment] 2022-04-04 15:47
Closing this out as we were able to figure out the cause of the issue and provide a solution to the internal ticket.

Cause of the issue - redirect signin uri pointed to a page that was protected and had a server side redirect if the user was not already authenticated. The way the OAuth flow works for Amplify, the app needs to load and initialize Amplify on the client side to finalize the OAuth flow, storing tokens in localStorage and then cookies, which can then be sent to the server to prove authentication. The server side redirect was preventing Amplify from completing the OAuth flow on the client, making it impossible to authenticate on the server as a federated Cognito user.

Solution - change redirect signin uri to a page that does not redirect based on authentication. Instead, check on the client and redirect back to protected if user is authenticated.

**Closed by chrisbonifacio** 2022-04-04 15:47 UTC
Labels: investigating, Auth, SSR, OAuth, Next.js
