### ISSUE TITLE
IncompleteSignatureException

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-js#7906] opened 2021-03-09 03:03 UTC
**Describe the bug**

I followed the instructions to setup the AppSync client on [this page](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js#create-the-graphql-api), but I am getting this error:

```
{
  "errors" : [ {
    "errorType" : "IncompleteSignatureException",
    "message" : "Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=..."
  } ]
}
```

This is my code:

```js
import Amplify, { API, graphqlOperation } from 'aws-amplify';
import awsconfig from './aws-exports';
import * as queries from './graphql/queries';
Amplify.configure(awsconfig);


const res = API.graphql(graphqlOperation(queries.listElections));
```

Not sure what is going on here... I'm not adding any custom headers or modifying the request in any way. This code lives at the top of my app, and I am making the request as an authenticated user.

The AppSync client doesn't seem to be adding the headers.

**Comment by volkanunsal** [comment] 2021-03-09 13:31
As mentioned [here](https://github.com/aws-amplify/amplify-js/issues/7911#issuecomment-793897661), the root cause turned out to be a configuration error. 

On a side note, when I run 

```
amplify update api
amplify push
```

It does _not_ update this configuration setting.

**Comment by IsaacTrevino** [comment] 2021-03-09 16:28
This issue needs to be addressed by the Amplify team, in my case I used `@aws-amplify/api` in addition to the `aws-amplify` package and it seemed to work for now. 

I used most amplify libraries and would like to only use `aws-amplify`, this is very concerning.

**Comment by amhinson** [comment] 2021-03-09 20:31
@volkanunsal Glad you were able to figure out your issue! Also, feel free to open another issue on the [Amplify CLI repo](https://github.com/aws-amplify/amplify-cli) regarding the configuration not updating.

@IsaacTrevino Could you provide some additional details on your issue? What is the best way to reproduce it? Can you share your `package.json`?

**Comment by IsaacTrevino** [comment] 2021-03-09 23:54
I've been using npm package `aws-amplify 3.3.23`, Since I've reach the `3.3.xx` I've begun to notice breaking changes. For instance  [**stackoverFlow link**](https://stackoverflow.com/a/66461209/13728677) shows my API configuration is not registering. Fine I utilize a second configuration as per the issue example, then I utilize a cognitio authenticated API `POST` method returning a API Gateway error relating to authentication.

I finally decide to use the modular package `@aws-amplify/api` and `@aws-amplify/core` and it seems to have solved the issue. I just want to be sure there is an api gateway issue with `aws-amplify`.

**Comment by amhinson** [comment] 2021-03-10 17:16
Could you share your `package.json` and a code sample of any behavior that appears to be breaking? We'd really like to dig into this, but I want to make sure we're addressing the exact issue that you're having.

**Comment by IsaacTrevino** [comment] 2021-03-14 01:53
```json
{
  "dependencies": {
    "@apollo/client": "^3.3.11",
    "@aws-amplify/ui-react": "^0.2.38",
    "@date-io/core": "^2.10.7",
    "@date-io/dayjs": "1.3.13",
    "@date-io/moment": "^1.3.13",
    "@fortawesome/fontawesome-free": "^5.15.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/free-regular-svg-icons": "^5.15.2",
    "@fortawesome/free-solid-svg-icons": "^5.15.2",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@fullcalendar/core": "4.4.2",
    "@fullcalendar/daygrid": "4.4.2",
    "@fullcalendar/interaction": "4.4.2",
    "@fullcalendar/list": "4.4.2",
    "@fullcalendar/react": "4.4.2",
    "@fullcalendar/timegrid": "4.4.2",
    "@fullcalendar/timeline": "4.4.2",
    "@mapbox/mapbox-sdk": "^0.11.0",
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/pickers": "^3.2.10",
    "@material-ui/styles": "^4.11.3",
    "@mdx-js/react": "^1.6.21",
    "@react-pdf/renderer": "^1.6.13",
    "@stripe/react-stripe-js": "^1.4.0",
    "@stripe/stripe-js": "^1.13.1",
    "apexcharts": "^3.25.0",
    "apollo-cache-persist": "^0.1.1",
    "aws-amplify": "^3.3.21",
    "aws-amplify-react": "^4.2.25",
    "aws-appsync": "^4.0.3",
    "aws-appsync-auth-link": "^3.0.4",
    "aws-appsync-react": "^4.0.3",
    "aws-appsync-subscription-link": "^3.0.6",
    "axios": "^0.21.1",
    "axios-mock-adapter": "^1.19.0",
    "bootstrap": "^4.6.0",
    "change-case": "^4.1.1",
    "chart.js": "^2.9.4",
    "clsx": "^1.1.1",
    "dayjs": "^1.10.4",
    "deepmerge": "^4.2.2",
    "formik": "^2.2.5",
    "generate-password": "^1.6.0",
    "graphql": "^15.5.0",
    "graphql-tag": "^2.11.0",
    "history": "^5.0.0",
    "https": "^1.0.0",
    "immutable": "^4.0.0-rc.12",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "^8.5.1",
    "jss": "^10.5.1",
    "jss-rtl": "^0.3.0",
    "jwk-to-pem": "^2.0.4",
    "jwt-decode": "^3.1.2",
    "localforage": "^1.9.0",
    "lodash": "^4.17.21",
    "mapbox-gl": "^2.1.1",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "notistack": "^1.0.5",
    "nprogress": "^0.2.0",
    "omit-deep-lodash": "^1.1.5",
    "prismjs": "^1.23.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-apexcharts": "^1.3.7",
    "react-chartjs-2": "^2.11.1",
    "react-color": "^2.19.3",
    "react-dom": "^17.0.1",
    "react-dropzone": "^11.3.1",
    "react-feather": "^2.0.9",
    "react-helmet": "^6.1.0",
    "react-json-tree": "^0.13.0",
    "react-lottie": "^1.2.3",
    "react-markdown": "^5.0.3",
    "react-modal-image": "^2.5.0",
    "react-number-format": "^4.4.4",
    "react-perfect-scrollbar": "^1.5.8",
    "react-quill": "^1.3.5",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "react-text-mask": "^5.4.3",
    "smooth-scrollbar-react": "^1.0.1",
    "subscriptions-transport-ws": "^0.9.18",
    "url": "^0.11.0",
    "uuid": "^8.3.1",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "typescript": "^4.2.2"
  }
}
```

**Comment by brymartinez** [comment] 2021-06-30 16:13
Also encountering this, on a rest API. Receiving `IncompleteSignatureException` when trying to send `getIdToken().getJwtToken()` as `Authorization` , using both `axios` and `API`.

I suspect it's because my Cognito User Pool has both AWS_IAM and COGNITO_USER_POOL, which requires IAM-based API Gateway Authorizers to also be signed as per https://stackoverflow.com/questions/37303110/aws-api-gateway-authentication-error-incompletesignatureexception-using-jwt-with

**Comment by brymartinez** [comment] 2021-06-30 16:24
This might also be a related issue https://github.com/aws-amplify/amplify-cli/issues/2679#issuecomment-560497808

**Comment by chrisbonifacio** [comment] 2023-04-10 18:21
Hi 👋 apologies for the delay. If anyone is still experiencing this issue, please open a new issue and provide your env info, configuration details, and any relevant code snippets.

**Closed by chrisbonifacio** 2023-04-10 18:21 UTC
Labels: API, GraphQL, to-be-reproduced
