### ISSUE TITLE
Auth.signIn() promise takes more than 30 seconds to resolve on Android

### ISSUE THREAD

**Issue by jfaq89** [aws-amplify/amplify-js#5539] opened 2020-04-24 13:37 UTC
**Describe the bug**
Auth.signIn() promise can take more than 30 seconds to resolve on Android. On iOS and Web we could not reproduce the bug. 
It happens when we start the app and we click "Login" for the first time. It doesn't always happen, we have to try a few times to reproduce it.

**To Reproduce**

1. Close all apps on device.
2. Start React Native app using npx react-native run-android
3. Click on "Login"
4. See console to see how many miliseconds it took to complete the authentication. 

**Expected behavior**
It should always be complete under 3 seconds as it happens on the other platforms.

**Code Snippet**

App.tsx :

```js
import React from "react";
import { StyleSheet, Text, View, TouchableOpacity } from "react-native";
import Amplify, { Auth } from "aws-amplify";
import {awsmobileDev} from './aws-exports'
Amplify.configure(awsmobileDev);

export default class App extends React.Component<{}, {}> {
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          style={{ height: 50, width: 200 }}
          onPress={async () => {
            console.log("Signing in...");
            const timeStart = new Date().getTime();
            await Auth.signIn("username", "password");
            const timeEnd = new Date().getTime();
            console.log("Sign in successfull. ", timeEnd - timeStart);
          }}
        >
          <Text>Login</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Screenshots**
<img width="483" alt="Bildschirmfoto 2020-04-24 um 15 23 45" src="https://user-images.githubusercontent.com/39528995/80217263-b373e500-863f-11ea-88b5-b4e4e3909f9c.png">
Here for example, it lasted 128 seconds to login!

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```js
   const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_cognito_identity_pool_id:
    "eu-central-1:xxx",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_xxx",
  aws_user_pools_web_client_id: "xxx",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://xxx.appsync-api.eu-central-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-central-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_cloud_logic_custom: [
    {
      name: "xxx",
      endpoint: "https://xxx.execute-api.eu-central-1.amazonaws.com/dev",
      region: "eu-central-1",
    },
  ],
  aws_mobile_analytics_app_id: "xxx",
  aws_mobile_analytics_app_region: "eu-central-1",
  aws_user_files_s3_bucket: "xxx-dev",
  aws_user_files_s3_bucket_region: "eu-central-1",
};
   };
   ```
**Smartphone (please complete the following information):**

- Device: We can see it in all kinds of Android Devices

**Comment by amhinson** [comment] 2020-04-24 16:41
@jfaq89 I see that you're testing with a development React Native build. Could you also test with a production build on a physical device and verify that you're seeing the same behavior?

**Comment by jfaq89** [comment] 2020-04-25 11:41
> @jfaq89 I see that you're testing with a development React Native build. Could you also test with a production build on a physical device and verify that you're seeing the same behavior?
> 
> Also, what version of `aws-amplify` are you using?

Hi. We already saw the error in production. Many people from my team have tested using different physical devices and everyone managed to reproduce the error.

We tested using the latest version of AWS-amplify.

**Comment by jfaq89** [comment] 2020-04-27 13:15
We're still blocked. The error was seen using version 3.0.9

Any idea how we can fix this?

**Comment by amhinson** [comment] 2020-04-27 20:39
@jfaq89 A couple of questions/comments:

- What version of React Native are you using?
- What other Amplify categories are you using in your app?
- Could you try reproducing this behavior with a brand new basic app and share it here?

I've got a simple auth app for testing, but I haven't been able to duplicate the issue you're seeing after trying numerous times on an Android device.

**Comment by jfaq89** [comment] 2020-04-28 09:29
> @jfaq89 A couple of questions/comments:
> 
> * What version of React Native are you using?
> * What other Amplify categories are you using in your app?
> * Could you try reproducing this behavior with a brand new basic app and share it here?
> 
> I've got a simple auth app for testing, but I haven't been able to duplicate the issue you're seeing after trying numerous times on an Android device.

1) React Native version :  0.61.5
2) On this brand new basic app that I made to debug this problem, I only use "Auth".
3) Here is the code: (the awsmobileDev config is the one I posted above)

```
import React from "react";
import { StyleSheet, Text, View, TouchableOpacity } from "react-native";
import { Auth } from "aws-amplify";
import {awsmobileDev} from './aws-exports'

Auth.configure(awsmobileDev);

// Amplify.Logger.LOG_LEVEL = "DEBUG";
export default class App extends React.Component<{}, {}> {
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          style={{ height: 50, width: 200 }}
          onPress={async () => {
            console.log("Signing in...");
            const timeStart = new Date().getTime();
            await Auth.signIn("jq3@doublemail.de", "Start001!");
            const timeEnd = new Date().getTime();
            console.log("Sign in successfull. ", timeEnd - timeStart);
          }}
        >
          <Text style={{ textAlign: "center" }}>Login</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});


```
It is not very easy to reproduce the error. You have to try a few times. It is easier to reproduce on a physical device than on a simulator.

Thanks in advance. Looking forward to hear from you!

**Comment by jfaq89** [comment] 2020-04-28 10:51
New information : we managed to reproduce it on an iPhone device. The Auth.signIn promise lasted 31 seconds. So it is also possible to see in an iPhone, but much harder to reproduce the error.

**Comment by jfaq89** [comment] 2020-05-06 15:08
Anyone has any ideas? If we cannot solve it, then is there maybe a possible workaround?

**Comment by amhinson** [comment] 2020-05-06 15:40
Unfortunately we have had no luck trying to reproduce this issue on our end using multiple devices/simulators/emulators. However, we can still leave this issue open in case others might be experiencing it as well in the future.

**Comment by batical** [comment] 2020-06-02 15:27
one of my beta tester is facing this issue but worse.
I took more than 10 minutes on her android. She tried with 3 different android in the same network wifi, same version of app and 4 iOS device with no issue.

I will be able to to more test in debug mode with this phone Friday. Don't know exactly what to look

**Comment by Andyluchina** [comment] 2020-06-19 00:12
I am experiencing the same issue, but with ionic+angular on android devices.
    "@ionic/angular": "^4.11.10",
    "aws-amplify": "^3.0.10",
    "aws-amplify-angular": "^5.0.10"

The tester is reporting a long wait time for sign in, and it seems to me that amplify is calling the cognito server about 12 times for a single Auth.signin, and the accumulated time of all these requests took this long. I am suspecting this is both related to network and the implementation of the frontend code.

**Comment by Andyluchina** [comment] 2020-06-19 00:51
relevant npm package here

**Comment by Andyluchina** [comment] 2020-06-19 00:52
https://www.npmjs.com/package/@aws-sdk/stream-collector-browser

here this the specific package I am referring to

**Comment by batical** [comment] 2020-06-30 18:20
> one of my beta tester is facing this issue but worse.
> I took more than 10 minutes on her android. She tried with 3 different android in the same network wifi, same version of app and 4 iOS device with no issue.
> 
> I will be able to to more test in debug mode with this phone Friday. Don't know exactly what to look
> 
> Edit : I test to call the login in a thunk redux, in saga, or alone. Using promise or async. The result is the same. It is taking more than 10 minutes; Reactotron does not see any outgoing network request and I got no error in android studio log

When I wrote my previous message, I was getting amplify by package in react native 
@aws-amplify/auth api and storage. 

I switch to using aws-amplify full package (with latest version) and the issue seems to have disappear. (in release mode)

**Comment by standemchuk** [comment] 2020-07-23 18:39
Experiencing the same issue with latest expo and even clean RN. The call to SignIn can is steady at 40-60s on a clean app that just does `SignIn`, no other logic. Sometimes it can take up to 3 min 😮 
Anyone close to a solution or a workaround?

**Comment by amhinson** [comment] 2020-07-23 18:41
@standemchuk If you could provide a sample repo that consistently shows this behavior, that would be wonderful! So far, I've been unable to reproduce the issue described.

**Comment by standemchuk** [comment] 2020-07-23 19:27
@amhinson Hi and thanks for a quick reaction!
Here's a repo on which we're trying to find a fix for an issue: https://github.com/standemchuk/amplify-rn-long-response-repro
Please make sure you update the values for `userPoolId` and `userPoolWebClientId`, they're currently marked as `SUBSTITUTE_ME`.

**Comment by standemchuk** [comment] 2020-07-23 19:30
@amhinson sorry, just pushed a small updated to make sure the app launches, please pull the latest changes

**Comment by standemchuk** [comment] 2020-07-27 10:45
@amhinson were you able to reproduce the issue?

**Comment by rbrazhnyk** [comment] 2020-07-27 12:13
@amhinson the issue can be reproduced on android emulator and android phone only. No issues if testing in the browser (had rare issues in iOS though).

**Comment by amhinson** [comment] 2020-07-27 16:06
@standemchuk So far I have not been able to replicate it. Would you be able to share the steps you took after running `amplify add auth`? There could be a certain configuration that might be causing issues.

**Comment by rbrazhnyk** [comment] 2020-07-27 21:24
@amhinson, according to [the docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#create-authentication-service) we don't have to create authentication service from scratch by running `amplify add auth`, but rather we can [re-use existing authentication resources](https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource).
We [added amplify configuration](https://github.com/standemchuk/amplify-rn-long-response-repro/blob/master/SDKService.js#L7) and make a [single call Auth.SignIn](https://github.com/standemchuk/amplify-rn-long-response-repro/blob/master/SDKService.js#L24).

I am able to reproduce the issue now with [the codebase we provide](https://github.com/standemchuk/amplify-rn-long-response-repro) (please also see screenshots below). Sometimes we got the response within 0.5s (which is okay), but **usually, it is 10 seconds or worse** (81s in the second example).

<img width="331" alt="0 5s" src="https://user-images.githubusercontent.com/4462680/88593296-e93ac680-d091-11ea-8a05-677433beb6f5.png">

<img width="754" alt="81s" src="https://user-images.githubusercontent.com/4462680/88593307-ec35b700-d091-11ea-8f84-6f1708c73840.png">

**Comment by amhinson** [comment] 2020-07-27 22:48
Are you using any custom Lambda triggers, by chance?

**Comment by rbrazhnyk** [comment] 2020-07-28 01:14
@amhinson, yes we have custom triggers.
 
So for the sake of experiment, I've just created **a new Cognito UserPool with no custom triggers**.

<img width="334" alt="Screen Shot 2020-07-28 at 9 05 56 AM" src="https://user-images.githubusercontent.com/4462680/88607403-bc96a700-d0b1-11ea-852b-ccad733e7f98.png">

Here are the settings of the new pool:
<img width="764" alt="Screen Shot 2020-07-28 at 9 10 00 AM" src="https://user-images.githubusercontent.com/4462680/88607701-72fa8c00-d0b2-11ea-942a-5a6e3dd097d0.png">
<img width="760" alt="Screen Shot 2020-07-28 at 9 10 30 AM" src="https://user-images.githubusercontent.com/4462680/88607705-74c44f80-d0b2-11ea-8ea5-1841d7f79117.png">
<img width="931" alt="Screen Shot 2020-07-28 at 9 10 55 AM" src="https://user-images.githubusercontent.com/4462680/88607708-755ce600-d0b2-11ea-94a8-0420755c4686.png">
<img width="592" alt="Screen Shot 2020-07-28 at 9 11 29 AM" src="https://user-images.githubusercontent.com/4462680/88607710-75f57c80-d0b2-11ea-9ee6-a003417033e1.png">
<img width="599" alt="Screen Shot 2020-07-28 at 9 11 41 AM" src="https://user-images.githubusercontent.com/4462680/88607712-768e1300-d0b2-11ea-91df-fa530e172ffd.png">

**Comment by amhinson** [comment] 2020-07-28 16:36
@rbrazhnyk Would you be able to reach out to me on our [Discord](https://discord.gg/jWVbPfC)? I'm still not able to reproduce the issue, but it could be helpful for me to test directly against your new User Pool.

**Comment by rbrazhnyk** [comment] 2020-07-29 00:04
@amhinson what is your username in Discord? `amhinson` does not return anything in seach results. 
My username is `rbrazhnyk` there. Perhaps you can ping me.

**Comment by Shmublon** [comment] 2020-09-03 09:49
I have the same issue on android, it takes minutes to sign in. I can reproduce it only on android real device

**Comment by KristineTrona** [comment] 2020-11-02 07:42
I am experiencing the exact same issue only on Android.

**aws-amplify:** 3.0.23
**react-native:** 0.63.2
**custom lambda triggers for authentication:** yes

**Comment by Bigbrd** [comment] 2020-11-20 21:01
any solution or workaround come from that offline discord investigation in July @rbrazhnyk @amhinson ?

**Comment by amhinson** [comment] 2020-11-20 21:10
@Bigbrd We were unable to reproduce the behavior on our end, unfortunately. This is still something we are actively trying to gather more data on, but it is a difficult problem to solve without being able to replicate it consistently.

If you (or anyone else who has commented on this issue) happen to have the following data from when this occurs, it would greatly help debugging efforts:
- Amplify logs - `Amplify.Logger.LOG_LEVEL = 'DEBUG'`
- Network request data - from a tool such as [Flipper](https://fbflipper.com/docs/features/react-native/) or [Reactotron](https://github.com/infinitered/reactotron/blob/master/docs/plugin-networking.md)

**Comment by rbrazhnyk** [comment] 2020-11-21 04:45
@Bigbrd @amhinson I was able to reproduce the issue everytime. 
I stopped using aws-amplify, and switched to aws-sdk, which does not have this problem.

**Comment by jamesalester** [comment] 2020-11-23 17:09
Thanks @amhinson for the redirect, I hadn't seen this thread. My issue may be the same or similar. I'll try leaving it logging in and see if it eventually resolves like the instances in here.

It would be interesting to know if everyone's hanging at the same point. I put logs in `node_modules/amazon-cognito-identity-js/src/CognitoUser.js` and found that it was getting stuck at line 282 where it calls 
```
this.client.request('InitiateAuth', jsonReq, (err, data) => {
```
If I log inside the request method in `node_modules/amazon-cognito-identity-js/src/Client.js` then it looks like it's getting stuck fetching the cognito endpoint: "https://cognito-idp.eu-west-2.amazonaws.com/".

**Comment by amhinson** [comment] 2020-11-23 21:39
Thanks for the info and investgating @jamesalester! 🙏  The logs would be very helpful here as well as knowing if the request is actually being make or not. I'd also be interested to see if there are any discrepancies in what `jsonReq` looks like for successful & unsuccessful requests.

**Comment by jamesalester** [comment] 2020-11-24 11:21
Hi @amhinson. I left the Android simulator signing in but it never seemed to resolve (my laptop could have turned itself off before it could finish but I'm not sure). 

I ran the sign in request with both iOS (which works) and Android (which doesn't) but I can't see any differences in the jsonReq.

<details>
<summary>Android (Not Working)</summary>
<code>
{
    AuthFlow: "USER_SRP_AUTH",
    AuthParameters: {
     SRP_A: "a05e5144e203be3651612468570c5dfb63a20265e3261e82c862435282e57e6a0c367fd092b7931e2ee313dbd660e69bc58e60224f808cb94898e1bacd2d8958f25e251b7b7b12661c35321033f89e174e12c50eec967e974b9043a299dee6ba65bfff8bb1704614f6feb8fffd27b5deab20f97ccd04de7f32ec1e46452345046e40770a50c20bfb76271b797bac7a6134a360e9035117fa3031ed9c147ae6177f7d01e738a5384c8393b834a0fecd7324b3950833d27b3f982187f6a5c1c8cce7f836bb9dfc341797f49078bcb4fb8279f3e8a0f650f075f2b394d2ddcda74e7112b430762857c8cbcb39459395e2fa5eaa02118f87b8d203d99cf55b4d337733fb630e775cb086c951e91a7c3d4b626a5bc0655fca76923b3e79422eb0a01d251ba6d9d32cea290fda6d1662e83e843af2bcf8b8eb5db4ac94ed206b8d9e8bd7fb630a6d41f0e8327f03ef539846d348d77b21d30dd3033921025973e108c03da05154195eb2b02f48649ce062d18441e7940ddeb9273368f7a344ed6cf048",
        USERNAME: "James"
    },
    ClientId: "XXXXXXXXX", 
    ClientMetadata: {}
}
</code>
</details>

<details>
<summary>iOS (Working)</summary>
<code>
{
    AuthFlow: "USER_SRP_AUTH",
    AuthParameters: {
        SRP_A: "4fe5329948c8bb3f63afa9d3cc126faedc23d5ac3e3c6b804bc5d4aed7769fb41678345f116095c7f2647df496480d6945ed5d48b65dc905a56779e070a5781d68d28769e824691f9bfb80947b7dc921280325c461fefd9b7ce09b7130d6a73f3e867026f8af62e91ef4b12b548fc28d30559f7efdf4a346fcc3bbae1a0da87f29affb4b225a5a64b86dc82331919cc1e87a5fd0762ed673c6805318b2de6e1ca76bc46a156997466f1f47457578cf6722b2b5e59c4a5c22d0be355b53d0499fdbdee5076ba02b2ef964dec52adc4e1a9d2b99a182aaa510ac198daca216ee19bc6712324549330c37e3b421100b1a6f44d3a8ae0e669bbab900d6f57ccd7cee20e71c50480f5d8557c536543c06501ea567c04bee68224f66eb138a466e9bcafddd7a4d65e63db4463e43cfee42ed3e642c83aa2592398d16be2bbdcad95e94f69dea11a6f7df06dd95ac3c73e25681de6208da0763a326a5a57243fb0018dc0a34184e039613a73c4121c81515515d626deedeec598663961bb6d8fba3a9a9",
        USERNAME: "James"
    },
    ClientId: "XXXXXXXXX", 
    ClientMetadata: {}
}
</code>
</details>

I can confirm that the `ClientId` parameter is the same in both. The `SRP_A` is different but this is different every time it's run on either device. I'm not really familiar with what the `SRP_A` is but I assume it's a hashed version of the password. Is it possible that this is being generated wrong on Android for some reason? Other than that I can't seem to see any difference in the parameters passed into the fetch inside `client.request`.

**Comment by jamesalester** [comment] 2020-11-24 13:03
Now I'm wondering if it's an issue with how Android handles fetch requests. I stuck the above Android request into Postman and got a 200 response.

**Comment by amhinson** [comment] 2020-11-24 15:35
@jamesalester Ah ok, well its helpful to know that it at least generates the `SRP_A` value and makes the request. There is quite a bit that goes into generating that value, so I had an initial thought that it was hanging somewhere in the process of generating it, but I think we can rule that out now. Even if this value is generated incorrectly and makes it to `this.client.request(...)`, that shouldn't cause the request to hang.

I did come across this open React Native issue which seems similar: https://github.com/facebook/react-native/issues/28283

**Comment by jamesalester** [comment] 2020-11-25 17:22
So after a few days of debugging and going through all of the issues on the react native Github related to fetches on Android I found a solution that works for my problem... disconnecting the wifi on the emulator and reconnecting! 😑

My colleague was getting the same problem that I was so it could be a bug in the android emulator so if anyone is getting the same issue give that a try first.

It doesn't look like an issue with amplify, at least for me.

**Comment by MattyK14** [comment] 2021-02-15 14:29
We're getting complaints of it from users in production, as well as possibly `Auth.updateUserAttributes()` hanging. Unable to reproduce in house or in debug thus far 😞

**Comment by taranda** [comment] 2021-03-01 21:37
I am experiencing the same issue on Android.  The same react native app works fine on iOS:

Android: 10
Device Model: SM-A115U1
packages:
    "amazon-cognito-identity-js": "4.4.0",
    "aws-amplify": "3.0.11",
    "aws-amplify-react-native": "4.2.5",
    "react": "16.13.1",
    "react-native": "0.63.4",

**Comment by ODINA101** [comment] 2021-03-07 13:43
@turanda did you fix it :(

**Comment by taranda** [comment] 2021-03-08 02:26
@ODINA101 No.

**Comment by tars0x9752** [comment] 2021-07-07 11:10
I'm not sure if it's exactly the same as this issue, but I experienced extremely slow `Auth.signIn()` on both iOS and Android. (Only on the actual device, the problem does not occur on the emulator.) It takes at least 10 seconds to resolve `Auth.signIn()` each time on iOS. On android it takes even more seconds.

And somehow I fixed it, so I'll leave some workaround that **might** be worth trying.

- Remove `resolverMainFields` in `metro.config.js` if possible. If you can't remove `resolverMainFields` completely, at least get rid of `module` from `resolverMainFields`. 
- If you have `Hermes` enabled, try disabling it.

In my case, got rid of `'module'` from `resolverMainFields` fixed the problem. Hope this helps someone.

**Comment by mudrila** [comment] 2021-07-14 20:30
> I was having this issue after developing out my web version for a while and started testing on my mobile builds. I found my android build was working and navigating fine but amplify's `signIn()` method was taking forever. I went to check and see what was going on with my iOS build and it wouldn't navigate from my root view. It was throwing [this](https://github.com/react-navigation/react-navigation/issues/6154) error. Upon resetting my `babel.config.js` to the basic `module.exports = { presets: ['@expo/next-adapter/babel']};` and then starting expo cleanly via `expo start -c` the amplify sign in method now works like a charm on both OS's!

Was causing issues for me as well - I added `react-native-paper/babel` to my `babel.config.js` and after removing that - everything works like a charm!

**Comment by andreialecu** [comment] 2021-12-09 16:23
Suddenly started running into this issue as well on a physical Android device with React Native. On iOS everything is fine.

It appears that any `Auth` network calls are not even issued. I can't see anything in Flipper.

Notice how this `fetch` doesn't seem to get to its `then` below based on my logging (This is in `amazon-cognito-identity-js`):
<img width="717" alt="Screenshot 2021-12-09 at 18 21 24" src="https://user-images.githubusercontent.com/697707/145434837-8721719f-684c-4ee3-95bf-55334c718747.png">

Then after several minutes there's a burst of network calls and the issue seems to clear up for a bit:

<img width="872" alt="Screenshot 2021-12-09 at 18 15 53" src="https://user-images.githubusercontent.com/697707/145433897-be97b390-628b-451e-89ba-7734fbdea29a.png">

Other network calls the app makes seem to be fine, it's only Cognito that seems to have this problem. Very strange.

**Comment by andreialecu** [comment] 2021-12-09 17:04
It appears that this may be some sort of React Native issue with IPv6 on Android.

I've applied the workaround in: https://github.com/facebook/react-native/issues/29608#issuecomment-884521699 and now requests seem to go through. That entire thread is about requests getting stuck on Android.

Here's the second log line being logged correctly with the IPv4 DNS resolver from the link:

<img width="1065" alt="Screenshot 2021-12-09 at 19 03 36" src="https://user-images.githubusercontent.com/697707/145442286-f6e45060-04f8-4609-a010-ffa69f95146b.png">

**Comment by andreialecu** [comment] 2021-12-09 18:22
Opened https://github.com/facebook/react-native/issues/32730 for react-native.

**Comment by vankhoa01** [comment] 2022-05-17 04:02
Hi my friends,

I got same issue.
Is there anyone else have resolved this problem ?

This is aws version which I'm using in my application
<img width="403" alt="Screen Shot 2022-05-17 at 11 00 48" src="https://user-images.githubusercontent.com/8953129/168726163-36141a36-dbf7-49b7-a70e-e70702678ecd.png">

**Comment by msaraac** [comment] 2022-09-16 21:57
any suggestions here. I'm getting same problem here. There is no issue with ios device but in android when I call the auth.signIn application got stuck and fps drops to -2

**Comment by dzpincus** [comment] 2022-11-02 22:02
I'm facing the same issue. The sign in call was working perfectly fine until recently, now takes up to a minute or two.
Has anyone figured out the issue yet?

**Comment by HodayaGruz** [comment] 2023-01-10 14:30
is there solution for this? i have 2 application with one aws source code, on one works prefect and on the other the app stuck for 10 sec

**Comment by Sean-Kurian** [comment] 2023-08-21 22:36
I am also running into this issue on a new app, it worked instantaneously for a bit and now hangs as described above.

**Comment by JKKholmatov** [comment] 2023-08-30 12:44
@HodayaGruz  @Sean-Kurian Did you find any solution?

**Comment by HodayaGruz** [comment] 2023-08-30 12:53
@JKKholmatov  In my case, I was need to create new app and copy all the code (I guess the problem was relevant to react native version)

**Comment by cwomack** [comment] 2023-12-05 21:21
With the release of the latest major version of Amplify (aws-amplify@>6), we believe this issue should now be resolved.  Since we could not reproduce this issue on our side, would anyone be able to confirm after migrating to v6 if this is still an issue?

Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Comment by cwomack** [comment] 2023-12-21 20:47
We'll close this issue on our side as it seems to be awaiting fixes on Facebook's React Native repo as detailed in [#32730](https://github.com/facebook/react-native/issues/32730) on their repo.  If someone has an easy way to reproduce this on the Amplify JS library side, please feel free to respond with those details and we can reopen this issue.

**Closed by cwomack** 2023-12-21 20:47 UTC
Labels: Auth, React Native, not-reproducible, pending-response
