### ISSUE TITLE
I keep getting undefined is not an object (evaluating 'RNPushNotification.initialize')

### ISSUE THREAD

**Issue by oluomoniyi** [aws-amplify/amplify-js#790] opened 2018-05-04 15:39 UTC
Hi Guys,

I literally followed all the steps detailed in this guide -> https://aws.github.io/aws-amplify/media/push_notifications_setup#configure-your-app

However, when I try to include the push notifications in my React native project I get the following error. Not sure what I am doing wrong, I have done react-native link, uninstalled, re-linked, installed the amplify lib as a project dependency. 

![screenshot_1525448046](https://user-images.githubusercontent.com/1480266/39636848-4ba06a16-4fb9-11e8-8146-3057c232d744.png)

Still same error :(

Please see my package.json dependencies below

`  "dependencies": {
    "aws-amplify": "^0.3.3",
    "aws-amplify-react-native": "^0.2.9",
    "moment": "^2.22.1",
    "moment-timezone": "^0.5.16",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-elements": "^0.19.1",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11"
  },`

**Comment by powerful23** [comment] 2018-05-04 17:44
Can you make sure the push notification package is correctly linked into your app? You can check `android/app/src/main/.../MainApplication.java` to see if it is under `getPackages()`

**Comment by oluomoniyi** [comment] 2018-05-08 09:29
@powerful23 thanks for the reply. I had a look in the `android/app/src/main/.../MainApplication.java` file the only packages imported are React native packages. 

However when I run react native link it is always successful. I am guessing there is a bit of an issue with the linking process

Is there a way to manually add the package?

**Comment by powerful23** [comment] 2018-05-08 17:32
@oluomoniyi 
1. make your `android/settings.gradle` like:
```
rootProject.name = 'pushnotificationdemo'
include ':aws-amplify-react-native'
project(':aws-amplify-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/aws-amplify-react-native/android')

include ':app'
```
2. in your `android/app/build.gradle`:
```
dependencies {
    compile project(':aws-amplify-react-native')

   // ....
}
```

3. in your `android/app/main/..../MainApplication.java`:
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNPushNotificationPackage()
      );
    }
```

Also there was some changes merged in the doc yesterday so please check that again.

**Comment by oluomoniyi** [comment] 2018-05-12 21:54
@powerful23 followed the steps you suggested and like @nachocifu still getting the error.

**Comment by powerful23** [comment] 2018-05-14 17:43
I think the root cause of this issue is that the `aws-amplify-react-native` module is not correctly linked into your project. You may try out a new blank project and follow the [docs](https://aws.github.io/aws-amplify/media/push_notifications_setup) step by step and if it works, check out the `android` folder to see how it links the module.

**Comment by oluomoniyi** [comment] 2018-05-16 10:28
I think I got it probably an obvious one @nachocifu @powerful23 but after you put the java package you need to do a react-native run-android (not npm start) to rebuild and reinstall the app on the emulator.

For anyone else who finds this useful.
Quick way to test if you actually have access to push notifications in your react native project.
```
import { NativeModules} from 'react-native';
console.log("Should return RNPushNotification method",NativeModules.RNPushNotification);
```

Another thing to note before adding the below in your, `android/app/main/..../MainApplication.java:` make sure your import `import com.amazonaws.amplify.pushnotification.RNPushNotificationPackage;` at the top of the file.
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNPushNotificationPackage()
      );
    }
```

**Closed** 2019-01-04 02:19 UTC
Labels: documentation, good first issue, investigating
