### ISSUE TITLE
Amplify browser error - "Authentication Error"

### ISSUE THREAD

**Issue by vikasmca05** [aws-amplify/amplify-js#6930] opened 2020-10-07 00:56 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Authentication Error in the Browser signin / Sign up

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.29.4

**What AWS Services are you utilizing?**
AWS Cognito - User pool

**Provide additional details e.g. code snippets**
I am using Amplify React libraries for integration with user pool sign in and sign up. My integration was working fine till yesterday and i was able to signin and signup new users. However, while enhancing my code base to add more details i ran into few issues and i need to reinstall aws-amplify. Now with the same code base, i keep on getting "Authentication error" in the browser while signing in or after clicking submit on sign up. 
My aws-exports for configuration looks like this - 
```js
  const awsconfig = {
    Auth: {
      // Amazon Cognito Region
      region: "us-east-1",
  
      // Amazon Cognito User Pool ID
      userPoolId: "us-east-1_XXXXX",
  
      // Amazon Cognito Web Client ID (26-char alphanumeric string)
      userPoolWebClientId: "YYYYYYYYYYYYYY"
      
    }
  };
  
  export default awsconfig;
```
Same configurations were working fine previously.

**Comment by ashika01** [comment] 2020-10-07 21:08
While  upgrading to newer version of amplify. Please follow the instructions here - https://github.com/aws-amplify/amplify-js/discussions/5836#discussioncomment-92667

Can you mention which version of amplify js were you on previously and which version your are upgrading to?

**Comment by vikasmca05** [comment] 2020-10-09 03:07
I did it multiple times the steps as mentioned but still i am getting the same error. Here are the debug logs.
index.js:1 [ERROR] 04:49.341 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
        

I dont remember my previous version of Amplify. But the current version is 3.3.3.

**Comment by vikasmca05** [comment] 2020-10-09 03:07
> @vikasmca05 Does it work with an older version of amplify js?

How can i install the older version of amplify ?

**Comment by vikasmca05** [comment] 2020-10-09 03:17
npm list | grep "amplify"
npm list | grep "amplify"
├── UNMET DEPENDENCY @aws-amplify/ui-react@^0.2.23
├─┬ aws-amplify@3.3.3
│ ├─┬ @aws-amplify/analytics@3.3.6
│ │ ├── @aws-amplify/cache@3.1.31 deduped
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ ├─┬ @aws-amplify/api@3.2.6
│ │ ├─┬ @aws-amplify/api-graphql@1.2.6
│ │ │ ├── @aws-amplify/api-rest@1.2.6 deduped
│ │ │ ├── @aws-amplify/auth@3.4.6 deduped
│ │ │ ├── @aws-amplify/cache@3.1.31 deduped
│ │ │ ├── @aws-amplify/core@3.6.0 deduped
│ │ │ ├── @aws-amplify/pubsub@3.2.4 deduped
│ │ └─┬ @aws-amplify/api-rest@1.2.6
│ │   ├── @aws-amplify/core@3.6.0 deduped
│ ├─┬ @aws-amplify/auth@3.4.6
│ │ ├── @aws-amplify/cache@3.1.31 deduped
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ ├─┬ @aws-amplify/cache@3.1.31
│ │ └── @aws-amplify/core@3.6.0 deduped
│ ├─┬ @aws-amplify/core@3.6.0
│ ├─┬ @aws-amplify/datastore@2.6.0
│ │ ├── @aws-amplify/api@3.2.6 deduped
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ │ ├── @aws-amplify/pubsub@3.2.4 deduped
│ ├─┬ @aws-amplify/interactions@3.3.6
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ ├─┬ @aws-amplify/predictions@3.2.6
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ │ ├── @aws-amplify/storage@3.3.6 deduped
│ ├─┬ @aws-amplify/pubsub@3.2.4
│ │ ├── @aws-amplify/auth@3.4.6 deduped
│ │ ├── @aws-amplify/cache@3.1.31 deduped
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ ├─┬ @aws-amplify/storage@3.3.6
│ │ ├── @aws-amplify/core@3.6.0 deduped
│ ├── @aws-amplify/ui@2.0.2
│ ├─┬ @aws-amplify/xr@2.2.6
│ │ └── @aws-amplify/core@3.6.0 deduped
├─┬ aws-amplify-react@4.2.7
npm ERR! missing: @aws-amplify/ui-react@^0.2.23, required by client@0.1.0
npm ERR! missing: @testing-library/jest-dom@^4.2.4, required by client@0.1.0
npm ERR! missing: @testing-library/react@^9.5.0, required by client@0.1.0
npm ERR! missing: @testing-library/user-event@^7.2.1, required by client@0.1.0
npm ERR! missing: react@^16.13.1, required by client@0.1.0
npm ERR! missing: react-dom@^16.13.1, required by client@0.1.0
npm ERR! missing: react-scripts@3.4.3, required by client@0.1.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/datastore@2.6.0
npm ERR! peer dep missing: react-native@>=0.56, required by react-native-get-random-values@1.5.0
npm ERR! peer dep missing: react@^15.5.3 || ^16.0.0, required by qrcode.react@0.8.0

**Comment by ashika01** [comment] 2020-10-09 04:55
@vikas5914 I need a code sample to reproduce this. Since currently I am not able to reproduce the error you are getting.

**Comment by vikas5914** [comment] 2020-10-09 06:03
@ashika01 I think you have tag wrong person.

**Comment by ericclemmons** [comment] 2020-10-12 17:12
@vikasmca05 We're having trouble reproducing your exact issue on our end. Can you share a code sample or repository so we can see a few things?

1. How are you importing `aws-amplify` and `Auth`?'
1. How are you calling `Amplify.configure(awsExports)`?
1. Are you seeing any console warnings when the page loads _before_ you attempt to sign-in?  (Please screenshot these, if so)

**Comment by ryanhinojosa** [comment] 2020-10-14 04:46
@ashika01 @ericclemmons  - Hi, we've been running into this issue for the last three upgrades.

aws-amplify:
3.3.3
3.3.2
3.3.1

@aws-amplify/ui-react
0.2.23
0.2.22
0.2.21

It's always eventually solved for us by following [these steps here](https://github.com/aws-amplify/amplify-js/discussions/5836#discussioncomment-92667) which is convenient for me because I wrote those steps 😆 . 

However if you're using Netlify that adds another wrinkle in here since they typically cache dependencies, forcing us to then do a manual deploy without the cache after doing all of the above steps. I love Amplify, it saves us a ton of time, but every time there's an update available it makes me nervous. And, it typically means I need to wait to update until after business hours to prevent breaking our logins. Which is why I'm now here 😄 .

Ideally these updates wouldn't require these steps at all, and I'm sure your team is doing what they can. But the other part of this is the error message which makes it seem like the problem is with the config when 90% of the time it's with package-lock.json and node_modules.

![Screen Shot 2020-10-13 at 8 32 45 PM](https://user-images.githubusercontent.com/14813548/95944544-45fa7300-0d9d-11eb-9d4e-1ffed01bb0ca.png)

**Comment by wei** [comment] 2020-11-08 03:15
It is mostly likely caused by mismatching versions between the ui-components and `aws-amplify` package.

Please install the latest using
```
yarn add aws-amplify@latest
yarn add @aws-amplify/ui-react@latest  # or any other amplify ui component library
```
and it should work fine. @vikasmca05 please let us know if this resolves your issue. Thank you!

**Comment by wei** [comment] 2020-11-09 20:50
@vikasmca05 replied at https://github.com/aws-amplify/amplify-js/discussions/5836#discussioncomment-125281 stating it's now working fine with a fresh install. Please close the issue.

**Comment by ericclemmons** [comment] 2020-11-09 21:34
Thanks for the updates @wei!  Closing...

**Closed by ericclemmons** 2020-11-09 21:34 UTC
Labels: Auth, Can't reproduce, React
