### ISSUE TITLE
PreSignup error custom response text in amplify-authenticator not working.

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-js#5908] opened 2020-05-26 20:59 UTC
**Describe the bug**

**To Reproduce**

1. With amplify-cli add auth with a PreSignup trigger
2. In the function/myPreSignup/src/index.js file:
```
// change const modules = process.env.MODULES.split(','); to:
const modules = ['custom']
````
3. Change function/myPreSignup/src/custom.js to:
```
exports.handler = (event, context, callback) => {
const allowed = false
 if (!allowed) {
   callback("My error message", null);
  } else {
    callback(null, event);
  }
};
```
4. See error:
When I run: ```mock function myPreSignup```

Output is:

```
myPreSignup failed with the following error:
{ '0': 'M',
  '1': 'y',
  '2': ' ',
  '3': 'e',
  '4': 'r',
  '5': 'r',
  '6': 'o',
  '7': 'r',
  '8': ' ',
  '9': 'm',
  '10': 'e',
  '11': 's',
  '12': 's',
  '13': 'a',
  '14': 'g',
  '15': 'e' }
```

**Expected behavior**
The error text should be a string

However in the browser the following is displayed in the amplify-toast:
> myPreSignup failed with the following error: My error message

Which seems fine, but I would like to remove or translate "myPreSignup failed with the following error:"

But when I try to customize the error text as per [Customize Error Messages](https://docs.amplify.aws/lib/auth/customui/q/platform/js#customize-error-messagesl)

It's not working.

**To Reproduce**
1.
In the App.vue template set the validation-errors property according to: 
[Authenticator, Sign Up properties](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#sign-up)

```
<amplify-authenticator>
  <amplify-sign-up
      :validation-errors="map"
  >
  </amplify-sign-up>
</amplify-authenticator>
```
and in methods:
```
methods: {
     map(message) {
     message = "My error message"
      return message
    }
}
```
2. ```Amplify push``` and ```Yarn serve```
3. Go to the signup form and enter info that will make auth fail and click create account.

**Actual behaviour***
The amplify-toast displays what ever error I induce, for example:
> Password cannot be empty

if I don't enter password.

**Expected behavior**
Regardless of error induced I expect only to see "My error message" in the amplify-toast.
But the code: ```validation-errors="map"``` seems to have no effect.

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 3.052s

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
    Memory: 248.30 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v10.17.0/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @aws-amplify/ui-vue: ^0.2.5 => 0.2.5 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    aws-amplify: ^3.0.11 => 3.0.11 
    axios: ^0.19.2 => 0.19.2 
    babel-eslint: ^10.1.0 => 10.1.0 
    core-js: ^3.6.4 => 3.6.5 
    eslint: ^6.7.2 => 6.8.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    gql: ^1.1.2 => 1.1.2 
    graphql: ^15.0.0 => 15.0.0 
    vue: ^2.6.11 => 2.6.11 
    vue-template-compiler: ^2.6.11 => 2.6.11 
  npmGlobalPackages:
    @aws-amplify/cli: 4.20.0
    npm: 6.11.3
    yarn: 1.19.1
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ashika01** [comment] 2020-05-31 16:59
Closing this issue as duplicate of https://github.com/aws-amplify/amplify-js/issues/5911

**Closed by ashika01** 2020-05-31 16:59 UTC
Labels: to-be-reproduced
