### ISSUE TITLE
Cannot find variable 'process' due to older graphQL version

### ISSUE THREAD

**Issue by selipso** [aws-amplify/amplify-js#4028] opened 2019-09-17 05:16 UTC
**Describe the bug**
This is using ionic 4 and angular 8. 'aws-amplify' version 1.1.40.

**Expected behavior**
Should not throw error

The fix is to upgrade the graphQL version in `@aws-amplify/api` to `^14`

Below is the error log

<img width="702" alt="Screen Shot 2019-09-16 at 10 16 05 PM" src="https://user-images.githubusercontent.com/5407481/65013327-45797980-d90a-11e9-9491-97600e01dda0.png">

**Comment by benshell** [comment] 2019-09-18 00:26
This appears to be a duplicate of https://github.com/aws-amplify/amplify-js/issues/3190
(I would like to see this updated too!)

**Comment by selipso** [comment] 2019-09-18 01:27
Thanks for referencing the other one. While the other issue is phrased as an enhancement, this is a breaking bug preventing ionic and Angular projects from losing unless you manually add peer dependency resolutions to the package.json. I’d like to keep this open to remind the devs of the severity.

**Comment by jkeczan** [comment] 2019-09-26 13:33
We are seeing the same. @selipso do you have a workaround already in place?

**Comment by selipso** [comment] 2019-10-01 18:06
@jkeczan I switched to yarn and used the [Selective dependency resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature

```
"resolutions": {
    "aws-amplify/**/graphql": "^14"
  }
```

**Comment by sammartinez** [comment] 2019-11-22 16:37
@selipso GraphQL version is upgraded to version 14.0.0. Resolving this issue as complete since this is in our stable version.

**Closed by sammartinez** 2019-11-22 16:37 UTC
Labels: Angular, GraphQL, to-be-triaged
