### ISSUE TITLE
Support for Multiple APIs

### ISSUE THREAD

**Issue by mk0a1a** [aws-amplify/amplify-js#5186] opened 2020-03-25 07:34 UTC
**Is your feature request related to a problem? Please describe.**
We currently have **two AppSync APIs** from **two different AWS accounts**. The APIs are made by different teams and we would like to use APIs from the first account to the other. The second API is secured using Cognito User Pools while the other is secured using IAM which delegates access to the other account (We made a role and attached it to a Cognito group that allows the authenticated user to access the API from the other account). Currently, Amplify doesn't support multiple GraphQL endpoints and we need it for code generation.

**Describe the solution you'd like**
Allow configuration for multiple AppSync endpoints.

```javascript
const amplifyConfig: {
    API: [
        {
            aws_appsync_graphqlEndpoint: "endpoint1",
            aws_appsync_region: "us-east-1",
            aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
        },
        {
            aws_appsync_graphqlEndpoint: "endpoint2",
            aws_appsync_region: "us-east-1",
            aws_appsync_authenticationType: "AWS_IAM"
        }
    ]
}
```

**Comment by esteban-uo** [comment] 2020-12-10 18:04
hi @mk0a1a! how did you manage to workaround this limitation in the meantime? thanks

**Comment by mk0a1a** [comment] 2020-12-10 23:52
Hey, @esteban-uo. We didn't use Amplify's API module for this, instead we used Apollo client. For the auth, it's just a matter of fetching the token from Cognito and passing it along with the request. So basically we fetch 2 tokens from 2 Cognito endpoints and then pass them to their respective APIs.

**Comment by esteban-uo** [comment] 2020-12-11 10:18
makes sense. Thanks a lot for your answer @mk0a1a

**Comment by chrisbonifacio** [comment] 2022-10-21 15:50
Closing this as a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/225

**Closed by chrisbonifacio** 2022-10-21 15:50 UTC
Labels: feature-request, API
