### ISSUE TITLE
aws-amplify-cognito

### ISSUE THREAD

**Issue by bharathkinto** [aws-amplify/amplify-js#6004] opened 2020-06-04 05:26 UTC
I just am trying to achieve the demo given in AWS cognito demo. But i end up with 

    at next (C:\Bharath\src\web\Kinto Projects\cognito3\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Bharath\src\web\Kinto Projects\cognito3\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Bharath\src\web\Kinto Projects\cognito3\node_modules\express\lib\router\layer.js:95:5) {
  constructor: [Function: NoUserPoolError],
  log: '\n' +
    '            Error: Amplify has not been configured correctly. \n' +
    '            The configuration object is missing required auth properties. \n' +
    '            Did you run `amplify push` after adding auth via `amplify add auth`?\n' +
    '            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information\n' +

It is a very simple program which just signs up a new user with Auth.signUp

**Comment by ashika01** [comment] 2020-06-04 17:53
@bharathkinto how did you configure your app? Follow this doc to setup amplify based on the framework you are using - https://docs.amplify.aws/start/getting-started/setup/q/integration/react

To add auth to your project, follow this - https://docs.amplify.aws/lib/auth/getting-started/q/platform/js

I am closing this issue because this is not a bug on Amplify. It is configuration mismatch. Please look at those docs get proper setup going. Feel free use [our discord group](https://discord.com/invite/Px5YVfQ) or discussion tab for getting more info.

If you run into any bug, please ping here and I will reopen the issue.

**Closed by ashika01** 2020-06-04 17:53 UTC
