### ISSUE TITLE
[Auth] resendSignIn

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#2550] opened 2019-01-15 23:59 UTC
**Is your feature request related to a problem? Please describe.**
How do you resend the MFA code when there's an error?

**Describe the solution you'd like**
A version of `Auth.resendSignUp` that works for resending the MFA code.

**Describe alternatives you've considered**
Using `Auth.resendSignUp` might work, but it's a bad name and future developers on the project will likely get confused even if it does work

**Comment by kaushik-raina** [comment] 2019-09-17 06:13
@sammartinez  @haverchuck ,
Could you please confirm if there is any plan to add this feature.
This seems to be pretty crucial.

Example workflow

1. MFA is set to required in cognito.( through SMS )
2. User enters Login username and password
3. user is redirected to Verify MFA code page
4. Now comes the edge case where user doesn't receives code on phone due to network issues
5. Hence we need to provide user with option to resend MFA code

**Comment by goatandsheep** [comment] 2019-09-17 15:10
I think the issue is that it's not even in the [Cognito SDK](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html). We need to advocate for Cognito too even have this as a feature before this library can utilize it. @dabit3 how can we suggest features to the Cognito team?

**Comment by samuelcastro** [comment] 2022-04-19 22:11
Any idea on how to resend the MFA SMS code during signIn?

**Comment by abdallahshaban557** [comment] 2022-11-10 15:18
Closing this as a duplicate of #2010

**Closed by abdallahshaban557** 2022-11-10 15:18 UTC
Labels: feature-request, Auth, Cognito, Service Team
