### ISSUE TITLE
Auth.currentCredentials sometimes does not return identityId

### ISSUE THREAD

**Issue by maxflores** [aws-amplify/amplify-js#6535] opened 2020-08-07 20:28 UTC
**Describe the bug**
For federated login, Auth.currentCredentials returns null identityId. Similar issues have been closed in the past but this is not fixed yet. 

**Expected behavior**
identityId should be returned

System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 AMD EPYC 7571
    Memory: 2.05 GB / 3.81 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.5.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  npmGlobalPackages:
    npm: 6.14.5
    yarn: 1.22.4

**Comment by maxflores** [comment] 2020-08-11 14:50
This is a major issue and I don't see a workaround. For those that depend on credentials with identityId, the entire amplify javascript library is rendered useless until this is fixed.

**Comment by amhinson** [comment] 2020-08-17 17:16
Would you be able to provide some reproduction steps to show this behavior?

**Comment by maxflores** [comment] 2020-08-18 03:57
I used the Authenticator object from the aws-amplify-react library

After signing in with Facebook or Google using federated sign in (Cognito Identity Pool only), I see that the identity is created in my identity pool.

Then I call Auth.currentCredentials using Auth from the aws-amplify library

This works perfectly using aws-amplify@2.3.0 and aws-amplify-react@3.1.9. However, using the current versions gives me only partial credentials. In the case of email and password login (i.e. Cognito User Pool + Cognito Identity Pool) there is no issue.

**Comment by mrowles** [comment] 2020-08-31 22:18
I am also seeing this over the last 24 hours. It happened in an app that had no updates in the last fortnight, so it seems to be a Cognito issue.

**Comment by mrowles** [comment] 2020-09-01 21:38
This was solved by reverting from `aws-amplify@3x` to `aws-amplify@2x`. We were live with 3x for a little while, so I'm not sure how the break came about, nevertheless reverting back to 2x fixes this. Thanks @maxflores

**Comment by randalb1991** [comment] 2020-09-29 13:56
The version issue with the version 3.0.24

**Comment by rdsedmundo** [comment] 2020-10-02 20:22
Also seeing this on v3.3.3, got the AWS credentials normally but no identityId anywhere. I can see in the network tab that the Cognito response returned the identityId (which I can also see in the AWS Console), so something is wrong while saving/retrieving it.

**Comment by mllrmat** [comment] 2020-10-23 13:03
The identityId is lost when the token is refreshed. Looking at the code the identityId is not passed to the refresh function:

See: https://github.com/aws-amplify/amplify-js/blob/abb5e3605e21685c98959af67115fa6a37bf22f2/packages/core/src/Credentials.ts#L148

**Comment by syang** [comment] 2021-03-08 04:41
> Also seeing this on v3.3.3, got the AWS credentials normally but no identityId anywhere. I can see in the network tab that the Cognito response returned the identityId (which I can also see in the AWS Console), so something is wrong while saving/retrieving it.

I can confirm that IdentityID could not be properly returned, please cross-reference at https://github.com/aws-amplify/amplify-js/issues/7769

**Comment by amhinson** [comment] 2021-03-08 23:06
@maxflores Could you share your `package.json`?

**Comment by amhinson** [comment] 2021-03-08 23:42
A [similar issue](https://github.com/aws-amplify/amplify-js/issues/7769#issuecomment-793152214) seemed to be resolved by using `aws-amplify` instead of any individual Amplify packages. Let me know if that works for anyone still having problems on this issue.

**Comment by iartemiev** [comment] 2021-04-12 18:10
@maxflores,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:10 UTC
Labels: Auth, pending-close-response-required
