### ISSUE TITLE
UI Components: Vue 3 support

### ISSUE THREAD

**Issue by Xenonym** [aws-amplify/amplify-js#7456] opened 2020-12-29 09:25 UTC
**Is your feature request related to a problem? Please describe.**
Since [Vue 3 is now officially stable][1], I would like to be able to use AWS Amplify UI Components with a Vue 3 project.

**Describe the solution you'd like**
Support for Vue 3 in `@aws-amplify/ui-vue`.

**Additional resources**:
- [Migration Guide][2]
- [Vue Demi for universal libraries compatible with both Vue 2 and 3][3]

[1]: https://github.com/vuejs/vue-next/releases/tag/v3.0.0
[2]: https://v3.vuejs.org/guide/migration/introduction.html
[3]: https://github.com/antfu/vue-demi

**Comment by amhinson** [comment] 2021-01-04 23:12
This appears to be a duplicate of https://github.com/aws-amplify/amplify-js/issues/6756#issuecomment-739062266, so I'll close this one so we can focus efforts on the other.

**Closed by amhinson** 2021-01-04 23:12 UTC
Labels: feature-request
