### ISSUE TITLE
[Bug] DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by arelaxend** [aws-amplify/amplify-js#7108] opened 2020-11-03 16:43 UTC
Hi there,

**Describe the bug**

When you disable cookies on a Chrome browser (latest version), then you get
```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

**To Reproduce**

1. Create an Amplify project
2. Disable cookies for the project on your browser (e.g. chrome)

**Expected behavior**
What is the expected way of handling this scenario ?

Best,
A.

**Comment by arelaxend** [comment] 2020-12-22 11:14
Update: What is the expected way of handling this ?

**Comment by arelaxend** [comment] 2020-12-22 14:43
Up! We cannot move to production because of this!

**Comment by sammartinez** [comment] 2021-03-23 21:53
Hello @arelaxend, thanks for reaching out on this. Do look to this [comment](https://github.com/aws-amplify/amplify-js/issues/6318#issuecomment-698618406) on how to resolve this. Please let us know if there is any other issue you have.

**Comment by iartemiev** [comment] 2021-04-12 18:18
@arelaxend,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:18 UTC
Labels: PubSub, pending-close-response-required
