### ISSUE TITLE
AWS Amplify customized Auth sign-in gets stock (pending) randomly on android, but works perfectly on ios and both simulators

### ISSUE THREAD

**Issue by zandvakiliramin** [aws-amplify/amplify-js#9241] opened 2021-11-17 21:28 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 2.52 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Safari: 15.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.16.0 
    @expo-google-fonts/inter: ^0.2.0 => 0.2.0 
    @expo/vector-icons: ^12.0.0 => 12.0.5 
    @react-native-async-storage/async-storage: ^1.15.11 => 1.15.11 
    @react-native-community/netinfo: 6.0.2 => 6.0.2 
    @react-navigation/bottom-tabs: ^6.0.5 => 6.0.9 
    @react-navigation/material-top-tabs: ^6.0.6 => 6.0.6 
    @react-navigation/native: ^6.0.6 => 6.0.6 
    @react-navigation/native-stack: ^6.1.0 => 6.2.5 
    @react-navigation/stack: ^6.0.11 => 6.0.11 
    @types/react: ~17.0.21 => 17.0.35 
    @types/react-native: ~0.64.12 => 0.64.19 
    HelloWorld:  0.0.1 
    aws-amplify: ^4.3.7 => 4.3.7 
    expo: ~43.0.0 => 43.0.3 
    expo-asset: ~8.4.3 => 8.4.3 
    expo-checkbox: ~2.0.0 => 2.0.0 
    expo-constants: ~12.1.2 => 12.1.3 
    expo-font: ~10.0.3 => 10.0.3 
    expo-image-picker: ~11.0.3 => 11.0.3 
    expo-linking: ~2.4.2 => 2.4.2 
    expo-splash-screen: ~0.13.3 => 0.13.5 
    expo-status-bar: ~1.1.0 => 1.1.0 
    expo-web-browser: ~10.0.3 => 10.0.3 
    hermes-inspector-msggen:  1.0.0 
    jest-expo: ~43.0.0 => 43.0.1 
    moment: ^2.29.1 => 2.29.1 
    react: 17.0.1 => 17.0.1 (17.0.2)
    react-dom: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-pager-view: 5.4.6 => 5.4.6 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: ~3.8.0 => 3.8.0 
    react-native-tab-view: ^3.1.1 => 3.1.1 
    react-native-web: 0.17.1 => 0.17.1 
    typescript: ~4.3.5 => 4.3.5 
  npmGlobalPackages:
    @expo/ngrok: 4.1.0
    expo-cli: 4.13.0
    npm: 8.1.0

```

</details>

### Describe the bug

I am developing an App with expo and Amazon Amplify as backend. I am trying to make my customized authentication process. The app works perfectly fine with both Android and ios simulators, also when I test it on my phone, (by scanning the QR code) it works on ios perfectly fine, but for Android, I get the following message in the console. The funny thing is that last night it worked fine with my wife's 3a pixel and did not work with my phone (I also have a 3a pixel), and now it works fine with my phone and does not work with hers (Sometimes it works but takes 10 minutes to log in, and then the logout() function does not work again). I have upgraded the Amplify packages as explained here, but it did not help.
p.s. I have an assets folder, and I require() images using <Image > component, and resize them in the App.  Images are a little bit larger than what I need, but not much larger. This is the only out-of-the-norm thing that I do).

### Expected behavior

The expected behavior is to have a smooth sign in all platforms and both dev and production settings.

### Reproduction steps

1. run the app
2. scan the barcode with an android phone
3. try the login button

### Code Snippet

```javascript
// Put your code below this line.
  const signInHandler = async () => {
    try {
      const user = await Auth.signIn(email, password);
      navigation.dispatch(StackActions.replace("OnBoarding"));
    } catch (e) {
      console.log(e);
    }
  };

// get and set email and password as state variables.

// on clicking the sign in button the above function is called.
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by sabarikobagapau** [comment] 2022-09-13 05:52
Hi @chrisbonifacio i am also facing same issue please help

**Comment by tannerabread** [comment] 2022-11-01 02:28
Closing this as duplicate of #5539, #10521

Please let me know if I closed this in error and those are not the same issue and I can re-open to better assist you

**Closed by tannerabread** 2022-11-01 02:28 UTC
Labels: Auth, React Native, pending-triage
