### ISSUE TITLE
Error compiling React application

### ISSUE THREAD

**Issue by itaisteinherz** [aws-amplify/amplify-js#3181] opened 2019-04-28 08:59 UTC
**Describe the bug**

While following the [get started guide](https://aws-amplify.github.io/docs/js/start?platform=react), when trying to compile the app at the end of step 4 using `npm start` I get the following error:

```
Failed to compile.

./node_modules/@aws-amplify/auth/lib/index.js
Module not found: Can't resolve '.../node_modules/babel-loader/lib/index.js' in '...'
```

**To Reproduce**

1. Go through step 1-4 in the guide likes above
2. Run `npm start`
3. See error

**Expected behavior**

The app should get compiled without any issues. Note that I could also to `npm install -D babel-loader` on my end to fix this issue, but this doesn't originate from the app, but rather from the library itself.

**Desktop (please complete the following information):**

 - OS: macOS 10.14 (Mojave)
 - Browser: Safari (not that it's relevant here, since the issues happens in the command line)
 - Version: 12.0 (14606.1.36.1.9)

**Comment by manueliglesias** [comment] 2019-04-30 00:08
Thanks @itaisteinherz 

This seems to be a duplicate of #2460 

Let me know if it is not to re-open this issue

**Closed by manueliglesias** 2019-04-30 00:08 UTC

**Comment by itaisteinherz** [comment] 2019-05-08 08:55
@manueliglesias I don't think this is a duplicate of #2460 since the issue here doesn't seem to be related to the library's declaration files, but to it's Babel configuration (and it's `package.json`).
