### ISSUE TITLE
Could not compile library when strict mode is enabled in typescript

### ISSUE THREAD

**Issue by dmytro-afonin** [aws-amplify/amplify-js#7188] opened 2020-11-13 14:42 UTC
**Describe the bug**
Could not compile library when strict mode is enabled in typescript.
There is a lack of return-type annotation in AuthCache interface
**To Reproduce**

1. Go to 'tsconfig.json'
2. set "strict": true in "compilerOptions" section
3. try to compile application
ERROR in node_modules/@aws-amplify/auth/src/types/Auth.ts:32:2 - error TS7010: 'setItem', which lacks return-type annotation, implicitly has an 'any' return type.

32  setItem();
    ~~~~~~~~~~
node_modules/@aws-amplify/auth/src/types/Auth.ts:33:2 - error TS7010: 'getItem', which lacks return-type annotation, implicitly has an 'any' return type.

33  getItem();
    ~~~~~~~~~~
node_modules/@aws-amplify/auth/src/types/Auth.ts:34:2 - error TS7010: 'removeItem', which lacks return-type annotation, implicitly has an 'any' return type.

34  removeItem();
    ~~~~~~~~~~~~~


**Expected behavior**
Should set up return type for all AuthCache functions

**Comment by harrysolovay** [comment] 2020-11-17 15:53
@dmitri-afonin thank you for your patience as we resolve this.

@elorzafe should [the aforementioned cache signature](https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/cache/src/types/Cache.ts#L17-L25) be the same as [that of the `Cache` package](https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/cache/src/types/Cache.ts#L17-L25)? If so, we should re-use the type.

My only concern is... it's odd that we'd include the current definition (missing parameters). Is there a reason we didn't re-use that of the `Cache` package to begin with?

Please let me know if that signature ^ is correct & I'll get this fixed ASAP.

**Comment by dmitri-afonin** [comment] 2020-11-23 15:08
@harrysolovay @elorzafe any updates on this issue?
I saw there was a new release recently, but the issue is still unchanged.
Just hope it is not lost)

**Comment by alexfromapex** [comment] 2020-12-01 15:36
I see this has the label `to-be-reproduced` so I'll confirm this is happening for me as well

**Comment by alexfromapex** [comment] 2020-12-01 23:37
@harrysolovay @elorzafe I believe this is causing anyone who uses this library with the `strict` type checking compiler option enabled to have a TypeScript error.  I have been trying to find a good workaround for hours, I think a simple stopgap code change [here](https://github.com/aws-amplify/amplify-js/blob/a047ce73/packages/auth/src/types/Auth.ts#L32) would fix it:

```
export interface AuthCache {
	setItem(): any;
	getItem(): any;
	removeItem(): any;
}
```

It already looks like [the documentation](https://aws-amplify.github.io/amplify-js/api/interfaces/authcache.html) has the explicit type definition so maybe it was changed in error.

**Comment by mathiasmoeller** [comment] 2021-01-12 10:34
Any updates on this?

**Comment by jonasduever** [comment] 2021-05-10 08:27
Still an issue. Did not find a workaround yet.

**Comment by sammartinez** [comment] 2021-05-19 15:57
This would be a feature request for us to have Typescript work in strict mode. Thanks for this feedback!

**Comment by jonasduever** [comment] 2021-06-02 12:36
In the meantime, I created this npm `postinstall` script.
```
/**
 * Patches the missing type declaration for Auth.js in Amplify.
 *
 * "Could not compile library when strict mode is enabled in typescript"
 * https://github.com/aws-amplify/amplify-js/issues/7188
 */

const fs = require('fs');

const amplifyTypesFile = './node_modules/@aws-amplify/auth/src/types/Auth.ts';

fs.readFile(amplifyTypesFile, (err, content) => {
  if (err) throw err;

  content = String(content)
    .replace('	setItem();', '	setItem(): any;')
    .replace('	getItem();', '	getItem(): any;')
    .replace('	removeItem();', '	removeItem(): any;');

  fs.writeFile(amplifyTypesFile, content, (err) => {
    if (err) throw err;
    console.log('postinstall.patchamplify.js: Done');
  });
});
```

**Comment by moltar** [comment] 2021-12-18 09:51
There are a ton more errors from the UI libs too now:

```
node_modules/@aws-amplify/auth/src/types/Auth.ts:31:2 - error TS7010: 'setItem', which lacks return-type annotation, implicitly has an 'any' return type.

31  setItem();
    ~~~~~~~~~~

node_modules/@aws-amplify/auth/src/types/Auth.ts:32:2 - error TS7010: 'getItem', which lacks return-type annotation, implicitly has an 'any' return type.

32  getItem();
    ~~~~~~~~~~

node_modules/@aws-amplify/auth/src/types/Auth.ts:33:2 - error TS7010: 'removeItem', which lacks return-type annotation, implicitly has an 'any' return type.

33  removeItem();
    ~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:29:9 - error TS2502: 'FormFields' is referenced directly or indirectly in its own type annotation.

29     var FormFields: typeof FormFields;
           ~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:224:9 - error TS2502: 'SignIn' is referenced directly or indirectly in its own type annotation.

224     var SignIn: typeof SignIn;
            ~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:225:9 - error TS2502: 'SignUp' is referenced directly or indirectly in its own type annotation.

225     var SignUp: typeof SignUp;
            ~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5775:48 - error TS2693: 'DataStoreItemProps' only refers to a type, but is being used as a value here.

5775 declare const index_DataStoreItemProps: typeof DataStoreItemProps;
                                                    ~~~~~~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5776:54 - error TS2693: 'DataStoreCollectionProps' only refers to a type, but is being used as a value here.

5776 declare const index_DataStoreCollectionProps: typeof DataStoreCollectionProps;
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5777:49 - error TS2693: 'DataStoreItemResult' only refers to a type, but is being used as a value here.

5777 declare const index_DataStoreItemResult: typeof DataStoreItemResult;
                                                     ~~~~~~~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5778:55 - error TS2693: 'DataStoreCollectionResult' only refers to a type, but is being used as a value here.

5778 declare const index_DataStoreCollectionResult: typeof DataStoreCollectionResult;
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5779:51 - error TS2693: 'DataStoreBindingProps' only refers to a type, but is being used as a value here.

5779 declare const index_DataStoreBindingProps: typeof DataStoreBindingProps;
                                                       ~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5780:54 - error TS2693: 'DataStorePredicateObject' only refers to a type, but is being used as a value here.

5780 declare const index_DataStorePredicateObject: typeof DataStorePredicateObject;
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5872:48 - error TS2344: Type '_0' does not satisfy the constraint 'boolean'.

5872 type index_TextFieldProps<_0> = TextFieldProps<_0>;
                                                    ~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5876:50 - error TS2344: Type '_0' does not satisfy the constraint 'ElementType'.
  Type '_0' is not assignable to type 'FC<any>'.

5876 type index_HTMLElementType<_0> = HTMLElementType<_0>;
                                                      ~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5877:44 - error TS2344: Type '_0' does not satisfy the constraint 'ElementType'.
  Type '_0' is not assignable to type 'FC<any>'.

5877 type index_ElementProps<_0> = ElementProps<_0>;
                                                ~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5878:56 - error TS2344: Type '_1' does not satisfy the constraint 'ElementType'.
  Type '_1' is not assignable to type 'FC<any>'.

5878 type index_PrimitiveProps<_0, _1> = PrimitiveProps<_0, _1>;
                                                            ~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5879:70 - error TS2344: Type '_1' does not satisfy the constraint 'ElementType'.
  Type '_1' is not assignable to type 'FC<any>'.

5879 type index_PrimitivePropsWithRef<_0, _1> = PrimitivePropsWithRef<_0, _1>;
                                                                          ~~

node_modules/@aws-amplify/ui-react/dist/index.d.ts:5880:46 - error TS2344: Type '_1' does not satisfy the constraint 'ElementType'.
  Type '_1' is not assignable to type 'FC<any>'.

5880 type index_Primitive<_0, _1> = Primitive<_0, _1>;
                                                  ~~


Found 18 errors.
```

**Comment by moltar** [comment] 2022-08-12 11:40
Can also use https://www.npmjs.com/package/patch-package

```patch
diff --git a/node_modules/@aws-amplify/auth/src/types/Auth.ts b/node_modules/@aws-amplify/auth/src/types/Auth.ts
index cbc668a..35f9893 100644
--- a/node_modules/@aws-amplify/auth/src/types/Auth.ts
+++ b/node_modules/@aws-amplify/auth/src/types/Auth.ts
@@ -29,9 +29,9 @@ export interface SignUpParams {
 }
 
 export interface AuthCache {
-	setItem();
-	getItem();
-	removeItem();
+	setItem(): any;
+	getItem(): any;
+	removeItem(): any;
 }
 
 /**

```

**Comment by moltar** [comment] 2022-08-12 11:40
It looks like the main problem is that the source files for some reason are packed?

Why?

```
node_modules/@aws-amplify/auth/
├── CHANGELOG.md
├── LICENSE
├── build.js
├── dist
│   ├── aws-amplify-auth.js
│   ├── aws-amplify-auth.js.map
│   ├── aws-amplify-auth.min.js
│   └── aws-amplify-auth.min.js.map
├── index.js
├── lib
│   ├── Auth.d.ts
│   ├── Auth.js
│   ├── Auth.js.map
│   ├── Errors.d.ts
│   ├── Errors.js
│   ├── Errors.js.map
│   ├── OAuth
│   │   ├── OAuth.d.ts
│   │   ├── OAuth.js
│   │   ├── OAuth.js.map
│   │   ├── oauthStorage.d.ts
│   │   ├── oauthStorage.js
│   │   ├── oauthStorage.js.map
│   │   ├── oauthStorage.native.d.ts
│   │   ├── oauthStorage.native.js
│   │   ├── oauthStorage.native.js.map
│   │   ├── urlOpener.d.ts
│   │   ├── urlOpener.js
│   │   ├── urlOpener.js.map
│   │   ├── urlOpener.native.d.ts
│   │   ├── urlOpener.native.js
│   │   └── urlOpener.native.js.map
│   ├── common
│   │   ├── AuthErrorStrings.d.ts
│   │   ├── AuthErrorStrings.js
│   │   └── AuthErrorStrings.js.map
│   ├── index.d.ts
│   ├── index.js
│   ├── index.js.map
│   ├── types
│   │   ├── Auth.d.ts
│   │   ├── Auth.js
│   │   ├── Auth.js.map
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   └── index.js.map
│   ├── urlListener.d.ts
│   ├── urlListener.js
│   ├── urlListener.js.map
│   ├── urlListener.native.d.ts
│   ├── urlListener.native.js
│   └── urlListener.native.js.map
├── lib-esm
│   ├── Auth.d.ts
│   ├── Auth.js
│   ├── Auth.js.map
│   ├── Errors.d.ts
│   ├── Errors.js
│   ├── Errors.js.map
│   ├── OAuth
│   │   ├── OAuth.d.ts
│   │   ├── OAuth.js
│   │   ├── OAuth.js.map
│   │   ├── oauthStorage.d.ts
│   │   ├── oauthStorage.js
│   │   ├── oauthStorage.js.map
│   │   ├── oauthStorage.native.d.ts
│   │   ├── oauthStorage.native.js
│   │   ├── oauthStorage.native.js.map
│   │   ├── urlOpener.d.ts
│   │   ├── urlOpener.js
│   │   ├── urlOpener.js.map
│   │   ├── urlOpener.native.d.ts
│   │   ├── urlOpener.native.js
│   │   └── urlOpener.native.js.map
│   ├── common
│   │   ├── AuthErrorStrings.d.ts
│   │   ├── AuthErrorStrings.js
│   │   └── AuthErrorStrings.js.map
│   ├── index.d.ts
│   ├── index.js
│   ├── index.js.map
│   ├── types
│   │   ├── Auth.d.ts
│   │   ├── Auth.js
│   │   ├── Auth.js.map
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   └── index.js.map
│   ├── urlListener.d.ts
│   ├── urlListener.js
│   ├── urlListener.js.map
│   ├── urlListener.native.d.ts
│   ├── urlListener.native.js
│   └── urlListener.native.js.map
├── package.json
├── src
│   ├── Auth.ts
│   ├── Errors.ts
│   ├── OAuth
│   │   ├── OAuth.ts
│   │   ├── oauthStorage.native.ts
│   │   ├── oauthStorage.ts
│   │   ├── urlOpener.native.ts
│   │   └── urlOpener.ts
│   ├── common
│   │   └── AuthErrorStrings.ts
│   ├── index.ts
│   ├── types
│   │   ├── Auth.ts
│   │   └── index.ts
│   ├── urlListener.native.ts
│   └── urlListener.ts
├── testSequencer.js
└── webpack.config.dev.js

13 directories, 102 files

```

**Comment by moltar** [comment] 2022-11-17 13:46
Why is this here? https://github.com/aws-amplify/amplify-js/blob/b3c507f78089dac3e329ff3c748284f642fcc3de/packages/auth/package.json#L44

**Comment by AllanZhengYP** [comment] 2022-11-17 18:20
Hi @moltar @alexfromapex 

Thank you for the investigation! I noticed in the TS stack trace shared here https://github.com/aws-amplify/amplify-js/issues/7188#issuecomment-997178301 shows the error was raised from `Auth.ts` instead of expected `Auth.d.ts`. It indicates your build script was trying to compile the dependency source code instead of checking the TS definitions from the Auth package. The definition files we shipped to NPM does include the `any` return type: https://unpkg.com/@aws-amplify/auth@5.0.2/lib-esm/types/Auth.d.ts

Can you share more info of your setup? e.g. tsconfig.json, source code snippet. A reproduction repo would be great.

Regarding the `src` directory in the `package.json`, so far it is required when debugging Apps with source maps.

**Comment by moltar** [comment] 2022-11-17 19:39
> Regarding the src directory in the package.json, so far it is required when debugging Apps with source maps.

Don't think that is correct. Source maps and sources are two different things. You can publish source maps alongside the transpiled source, and definition files. Which is what is commonly done. You can even publish the source maps inline.

**Comment by AllanZhengYP** [comment] 2022-11-17 20:08
Yes. There are 2 ways to configure the sourcemap regarding where source files live(see [inlineSources](https://www.typescriptlang.org/tsconfig#inlineSources)). You can either 

(1) ship the source map with only `mappings` info to map from generated to a separate source file,
(2) or ship the source map containing "inline source" which is a copy of the ts source code, so users don't need to ship the `src/`

Both of the solution(1)(2) supports "inline source maps"([inlineSourceMap](https://www.typescriptlang.org/tsconfig#inlineSourceMap)) or source map files in separate `.map` files([sourceMap](https://www.typescriptlang.org/tsconfig#sourceMap)).  In Amplify packages, we use (1) and separate `.map` file, so we need to ship `src` along with `.map` files. 

Either solution works and I don't think it's the root cause. The compiler trying to compile `Auth.ts` is more suspicous to me. Can share more info of your setup?

**Comment by moltar** [comment] 2022-11-18 14:19
@AllanZhengYP I found the source of the problem on our end, we were erroneously importing from the `src/` dir, because we needed some type that was not exported. So that fixes our immediate problem.

However, I still disagree with the analysis of needing to ship the `.ts` source files for the source maps to function.

I have created a repro case that demonstrates that source maps continue to function, even after the `src` dir removal.

Please see here:

https://github.com/moltar/aws-amplify-7188-repro

**Comment by AllanZhengYP** [comment] 2022-11-18 18:21
@moltar Thank you for the repro, it helps a lot! Sorry I skipped some details in my previous comments. Without the `src` folder, the stack trace will work because the `.map` files contain the mapping information from `.js` to `.ts`. With help of the `ts-jest`, the thrown error stack trace will be mapped to `.ts` code. 

The reason we need `src` is for debugging(like using Chrome devtools). Just so you can view the full source `.ts` code and set break points, and inspect local variables.

Glad to hear your original issue is resolved!

**Comment by s-debnath** [comment] 2022-12-08 21:26
Also ran into this issue. The class I was importing was AuthOptions, so I could get typing for what was necessary for the eventual Amplify.configure. 

```
import { AuthOptions } from "@aws-amplify/auth/src/types/Auth";

const authOptions: AuthOptions = {
    userPoolId: "",
    userPoolWebClientId: "",
    region: "",
   ...
}
```

**Comment by moltar** [comment] 2022-12-08 21:43
@s-debnath this is how I did it in the end:

```ts
import type { Auth } from '@aws-amplify/auth'

type AuthOptions = ReturnType<typeof Auth['configure']>
```

**Comment by s-debnath** [comment] 2022-12-08 21:48
Thanks @moltar! Typescript always manages to surprise me on what its capable of!

**Comment by jimblanc** [comment] 2023-03-23 15:26
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by cwomack** [comment] 2023-10-03 20:58
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment] 2023-11-16 21:57
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Closed by cwomack** 2023-11-16 21:57 UTC
Labels: feature-request, TypeScript, fixed-in-dev-preview
