### ISSUE TITLE
Login facebook not working react native (ios)

### ISSUE THREAD

**Issue by LogTime1h** [aws-amplify/amplify-js#10325] opened 2022-09-15 06:59 UTC
### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

I have done your suggestion but the result is not as expected. Login facebook on ios still not working. Hope you help.
I check deeplink :xcrun simctl openurl booted "myApp://" it works properly. But when I log in on aws, it returns to the app, but there is still no data. And this error occurs on ios
![image](https://user-images.githubusercontent.com/113431759/190338459-cdf11898-8454-45d4-8a3c-fe6a94ffa0e1.png)
![image](https://user-images.githubusercontent.com/113431759/190338572-1f957d66-8b54-4e14-b118-672ef94940fb.png)
![image](https://user-images.githubusercontent.com/113431759/190338641-fab9b0f2-6c74-448b-9444-53462f0278ae.png)

**Comment by tannerabread** [comment] 2022-09-15 13:26
Hi :wave:, closing this as a duplicate of #10315. Any updates will be added to that issue

**Closed by tannerabread** 2022-09-15 13:26 UTC
