### ISSUE TITLE
AWS-Amplify does not work with Rollup for Svelte.

### ISSUE THREAD

**Issue by majortom64** [aws-amplify/amplify-js#6826] opened 2020-09-18 15:12 UTC
**Describe the bug**
Installing AWS Amplify fails for Svelte with Rollup.

**To Reproduce**

Install svelte using Rollup.
Follow instructions from https://www.swyx.io/writing/making-aws-amplify-work-with-rollup-2d9m

**Expected behavior**
Not failing.

**Code Snippet**
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@aws-amplify/auth/lib-esm/Auth.js
11:  * and limitations under the License.
12:  */
13: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                     ^
14:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
15:     return new (P || (P = Promise))(function (resolve, reject) {
...and 5 other occurrences
node_modules/@aws-amplify/core/lib-esm/Amplify.js
1: var __read = (this && this.__read) || function (o, n) {
                 ^
2:     var m = typeof Symbol === "function" && o[Symbol.iterator];
3:     if (!m) return o;
...and 1 other occurrence
node_modules/@aws-amplify/core/lib-esm/Hub.js
11:  * and limitations under the License.
12:  */
13: var __assign = (this && this.__assign) || function () {
                    ^
14:     __assign = Object.assign || function(t) {
15:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 5 other occurrences

...and 34 other files
(!) Circular dependencies
node_modules/@aws-amplify/core/lib-esm/index.js -> node_modules/@aws-amplify/core/lib-esm/Signer.js -> node_modules/@aws-amplify/core/lib-esm/Util/index.js -> node_modules/@aws-amplify/core/lib-esm/Util/Reachability.js -> node_modules/@aws-amplify/core/lib-esm/index.js
node_modules/@aws-amplify/datastore/lib-esm/util.js -> node_modules/@aws-amplify/datastore/lib-esm/types.js -> node_modules/@aws-amplify/datastore/lib-esm/util.js
node_modules/@aws-amplify/pubsub/lib-esm/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> node_modules/@aws-amplify/pubsub/lib-esm/index.js

**Screenshots**
See error above.

Does not matter, never gets that far.
<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 2.93 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Firefox: 78.0.2
  npmPackages:
    @aws-amplify/auth: ^3.4.4 => 3.4.4 
    @aws-amplify/core: ^3.5.4 => 3.5.4 
    @rollup/plugin-commonjs: ^14.0.0 => 14.0.0 
    @rollup/plugin-json: ^4.1.0 => 4.1.0 
    @rollup/plugin-node-resolve: ^8.0.0 => 8.4.0 
    autoprefixer: ^10.0.0 => 10.0.0 
    aws-amplify: ^3.3.1 => 3.3.1 
    ini: ^1.3.5 => 1.3.5 
    inquirer: ^6.5.1 => 6.5.2 
    postcss: ^8.0.5 => 8.0.5 
    postcss-nesting: ^7.0.1 => 7.0.1 
    rollup: ^2.3.4 => 2.27.1 
    rollup-plugin-livereload: ^2.0.0 => 2.0.0 
    rollup-plugin-svelte: ^6.0.0 => 6.0.1 
    rollup-plugin-terser: ^7.0.0 => 7.0.2 
    sirv-cli: ^1.0.0 => 1.0.6 
    svelte: ^3.0.0 => 3.25.1 
    svelte-preprocess: ^4.3.0 => 4.3.0 
    tailwindcss: ^1.8.10 => 1.8.10 
  npmGlobalPackages:
    @aws-amplify/cli: 4.29.1
    npm: 6.14.4
```

</details>

**Comment by wlee221** [comment] 2020-09-18 17:57
Hello @majortom64, thanks for reporting the issue! 
I have confirmed bundling issues with rollup, in particular with our dependency on `@aws-amplify/core`. But I was still able to build the app (with the warnings you have above) and have runtime errors shown on `console.log`. Just to confirm that we are not overlooking your issue -- are you able to build the app, and if so can you post a screenshot of console?

**Comment by majortom64** [comment] 2020-09-18 20:18
![ScreenShot1](https://user-images.githubusercontent.com/5418629/93641495-3449c980-f9b1-11ea-9b9a-28dce1908cfa.png)

It does not run, just gives a white screen and that message.

**Comment by wlee221** [comment] 2020-09-18 20:26
@majortom64 Thanks for your quick reply; that looks just like what I'm seeing too. We identified the root cause (our `universal-cookie` dependency has require syntax in its es distribution). We're working on a fix, and we'll keep you updated. Thanks!

**Comment by sammartinez** [comment] 2020-09-18 21:33
@majortom64 I do want to call out that we don't officially support Svelte at this time. However we will continue to work on the fix and provide an update once we have one

**Comment by wlee221** [comment] 2020-09-23 02:57
Hi @majortom64, please try a fresh install of your `node_modules` (`rm -rf node_modules && npm install`). This should install the latest `universal-cookie: 4.0.4` that resolves this issue. 

We will also be bumping the version in `core` with the pr above. Please tell us if you still see the problem. Thanks!

**Comment by majortom64** [comment] 2020-09-23 16:23
Still get these errors: 

https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@aws-amplify/core/lib-esm/Hub.js
11:  * and limitations under the License.
12:  */
13: var __assign = (this && this.__assign) || function () {
                    ^
14:     __assign = Object.assign || function(t) {
15:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 5 other occurrences
node_modules/@aws-amplify/core/lib-esm/Amplify.js
1: var __read = (this && this.__read) || function (o, n) {
                 ^
2:     var m = typeof Symbol === "function" && o[Symbol.iterator];
3:     if (!m) return o;
...and 1 other occurrence
node_modules/@aws-amplify/core/lib-esm/Credentials.js
1: var __assign = (this && this.__assign) || function () {
                   ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 5 other occurrences

...and 35 other files
(!) Circular dependencies
node_modules/@aws-amplify/core/lib-esm/index.js -> node_modules/@aws-amplify/core/lib-esm/Signer.js -> node_modules/@aws-amplify/core/lib-esm/Util/index.js -> node_modules/@aws-amplify/core/lib-esm/Util/Reachability.js -> node_modules/@aws-amplify/core/lib-esm/index.js
node_modules/@aws-amplify/datastore/lib-esm/util.js -> node_modules/@aws-amplify/datastore/lib-esm/types.js -> node_modules/@aws-amplify/datastore/lib-esm/util.js
node_modules/@aws-amplify/pubsub/lib-esm/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> node_modules/@aws-amplify/pubsub/lib-esm/index.js

![Amplfiy-error-2](https://user-images.githubusercontent.com/5418629/94040932-67f46d00-fd7e-11ea-983e-0cc1b0a67080.png)

**Comment by majortom64** [comment] 2020-09-23 16:24
BTW, thanks for your quick reply and work on this issue. It is much appreciated. :-)

**Comment by wlee221** [comment] 2020-09-23 23:00
Rollup with Amplify always bothered me too, so I'm happy to work on this :D Thanks for keeping us updated!

I could not reproduce your error however, following swyx's guide ([blog](https://www.swyx.io/writing/making-aws-amplify-work-with-rollup-2d9m/) and [youtube](https://youtu.be/hCoRYc_FzK0)). I could get it built and running in my repo with latest amplify ([app repo](https://github.com/wlee221/amplify-svelte)); perhaps you can look at [`rollup.config.js` ](https://github.com/wlee221/amplify-svelte/blob/master/rollup.config.js) and see if my configuration can resolve yours. 

If you're using other categories from amplify, it's possible that my app tree-shook that away because I'm only using `Amplify.API`. Can you send us a sample code if that's the case?

**Comment by wlee221** [comment] 2020-09-23 23:06
It looks like [this](https://github.com/rollup/rollup-plugin-commonjs/issues/183#issuecomment-287046393) is a possible solution.

**Comment by sammartinez** [comment] 2020-10-01 16:44
Resolving as the above link that @wlee221 has provided is the solution to this issue.

**Closed by sammartinez** 2020-10-01 16:44 UTC
Labels: dependencies, pending-close-response-required
