### ISSUE TITLE
amplify vue starter template fails on extract-text-webpack-plugin

### ISSUE THREAD

**Issue by estyh** [aws-amplify/amplify-js#2165] opened 2018-11-21 11:07 UTC
**Describe the bug**
npm start gives me a compile error

```
 ERROR  Failed to compile with 1 errors                                                       12:57:03
 error  in ./src/App.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (C:\Users\esty.heller\Documents\Dev\aws-amplify-vue\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

 @ ./src/App.vue 2:2-358
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**To Reproduce**
1. follow the getting started steps in the vue amplify guide - everything except creating the storage for media - I skipped that step because it was giving me errors with cloudformation, don't know why, there was no reason, no access denied, it just failed, but I don't think it's relevant here.

2. amplify push

3. npm start

**Expected behavior**
no compile errors...

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by haverchuck** [comment] 2018-11-21 20:04
@estyh I am unable to reproduce this error.  Can you try setting your node env as described [here](https://github.com/vuejs/vue/issues/5030#issuecomment-289336871)?  

I'm not saying this ^^ is the solution, but it would be helpful in diagnosing the issue absent a reproduction.

**Comment by haverchuck** [comment] 2018-11-21 20:29
@estyh  I updated the package.json in this file set the node env.  I think this is sufficient given that this is just a starter app.  To make it production ready, I think we'd just need additional npm scripts that would use the appropriate environmental webpack config files.

Closing issue for now, but feel free to reopen.

**Closed by haverchuck** 2018-11-21 20:29 UTC
Labels: investigating, starter:vue
