### ISSUE TITLE
Mock Graphql is not using local data storee.

### ISSUE THREAD

**Issue by jinnkhan88** [aws-amplify/amplify-js#7954] opened 2021-03-17 16:22 UTC
**Describe the bug**
Local graphql client is not getting data from DataStore

**To Reproduce**
- Create a new model.
- After codegen use the DataStore to create a new model by using DataStore.save(new Model(input)). Models created successfully and can be read by DataStore.query(Model,Predicate.ALL) and are also synced to DynamoDB live.
- Create mock env by using amplify mock.
- Try the list method auto generated by amplify to list the added model. 
- Response is empty. 
- If I use the same approach on AppSync console. it gives the data stored in the model.
- DataStore is enabled for entire API

**Expected behavior**
- Local grahql client should return the data created by DataStore. 

- Device:[Macbook pro]
- OS: [Mac OS Bigsur 11.2.3]
- Browser [Chrome]
- Amplify Version : 4.45.1

**Comment by jinnkhan88** [comment] 2021-03-25 18:36
bump

**Comment by iartemiev** [comment] 2021-04-05 14:05
Closing, as this issue is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/4155 and is a feature request being tracked by the Amplify CLI team.

**Closed by iartemiev** 2021-04-05 14:05 UTC
Labels: DataStore, feature-request
