### ISSUE TITLE
Social Federation Not Working with Custom Domains

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5565] opened 2020-04-26 01:53 UTC
**Describe the bug**
I am unable to get the signIn method of the hub listener to fire upon signin via Auth.federatedSignin().

**Expected behavior**
When a user signs in via Google or Facebook (i.e. Auth.federatedSignin({provider: 'facebook/google'})) they should be redirected back to my app (e.g. customdomain.com) and the signIn method of the hub listener should fire.

**Screenshots **
Here is a log that shows what happens when I log in Auth.federatedSignin({provider: 'google'}):

![Screen Shot 2020-04-25 at 8 51 24 PM](https://user-images.githubusercontent.com/31458115/80295228-bc93ad80-8736-11ea-9112-21f918f6aeca.png)
![Screen Shot 2020-04-25 at 8 51 33 PM](https://user-images.githubusercontent.com/31458115/80295230-bef60780-8736-11ea-9007-16f1254d8802.png)

As you can see, there are only two instances when an auth event is being dispatched, and it is only during initialization (on event parsingCallbackUrl). A subsequent auth event 'signIn' should be fired, but it is not.

**What is Configured?**
I have oauth configured using @dabit3 's wonderful tutorial on [social federation with amplify](https://dev.to/dabit3/the-complete-guide-to-user-authentication-with-the-amplify-framework-2inh). I am using Cognito User Pools for authentication which allows social federation via Amazon, Google, and Facebook. I have a custom domain set up with route 53 and it has a hosted zone.

My exports file looks like the following:
```
const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:xxx,
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_2MMItODxV",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {
        "domain": "xxx-master.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://mydomain.net/",
        "redirectSignOut": "https://mydomain.net/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://xxx.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "xxx-master",
    "aws_user_files_s3_bucket_region": "us-west-2"
};
```

**Additional context**
When I was following the aforementioned tutorial it worked like a charm in my dev environment. However, now that I have changed the redirect urls (via the amplify cli and on the google/facebook oauth accounts) the feature does not work. In face when I sign in, the google oauth redirects to `mydomain.com/#`, as opposed to the expected redirect: `mydomain.com/`. Facebook also redirects in a strange way by forwarding to `mydomain.com/#_=_`, as opposed to `mydomain.com/`. I'm not sure if this is significant or not. As far as I can tell, the oauth providers have been set up properly (on the facebook/google dev sites). I have pasted the oauth endpoints (e.g. xxx-master.auth.com) in the correct places and I am really frustrated that I can't get this thing to work :/

I should also mention that this feature was working before I tried setting up my custom domain.

edit: After doing some testing I found that this feature works on my dev environment which is hosted with the amplify console. With this setup my auth resources and storage (hosting) resources match up nicely (e.g. xxx-amplifydev.auth.com & xxx-amplifydev.com). However, on my master environment the resources do not match up (e.g. mydomain.com & xxx-amplifymaster.auth.com). I have a feeling that the error lies in this discrepancy. Is there anything special I have to setup when using a custom domain and social federation?

**Comment by VTSingle** [comment] 2020-04-28 08:35
same error

**Comment by mauerbac** [comment] 2020-05-15 19:43
Hi @karrettgelley / @VTSingle - sorry for the delay here. I was able to replicate this issue. I then did some digging and found this [issue](https://github.com/aws-amplify/amplify-js/issues/5127). It looks like when it's hosted with a custom domain via Amplify Console `Amplify.configure(config);` doesn't have the redirect variables, so in the proposed solution the dev manually overrides them. This [solution](https://github.com/aws-amplify/amplify-js/issues/5127#issuecomment-524629101). This works but isn't a good developer experience and this needs to be fixed. I agree the docs should reflect this as well. I've marked this as a bug and will have this prioritized.

**Comment by karrettgelley** [comment] 2020-05-16 01:42
@mauerbac Can you confirm that this is a custom domain bug and not merely a multi-env issue? I've ran across #5127 before when I was trying to set up multi-env auth, but that is _not_ my problem at the moment. Surely I'm missing something trivial like a configuration step unless everyone is just using the amplify default url (i.e. xxx-amplifymaster.com) for social federation

**Comment by mrichman** [comment] 2020-05-17 18:54
I am experiencing the same behavior, and had to implement the hack in [this issue](https://github.com/aws-amplify/amplify-js/issues/5127).

**Comment by mauerbac** [comment] 2020-05-18 14:29
hi @karrettgelley - The issue seems to be a multiple URL problem - not necessarily an issue with custom domains itself. Amplify initially gives you a pre-generated URL, so adding the custom domain causes you to have two URLs, which triggers this. The SDK doesn't support multiple URLs today. When I used the "hack" it essentially overrides which URL i want to use in the Config allowing redirects to work. A fix would allow for the dev to specify which URL they want to use per env. Does this make sense?

**Comment by karrettgelley** [comment] 2020-05-19 04:41
@mauerbac Makes sense. I'll see if the hack works for me. Like I said I've used to hack before to get around multiple environments, but I haven't tried to use it for a custom domain. I never would have thought that using a custom domain would trigger the same issue. I'll report back on the update

**Comment by jonathanbravecredit** [comment] 2021-09-14 17:08
@karrettgelley I know you opened this a while back, but wondering if you ever found a solution. I am experiencing this exact same issue. Even down to the redirect urls showing ```mydomain.com/#``` and ```mydomain.com/#_=_```. Oddly everything works on local and up until a couple of days ago was working fine on a dev environment.

**Comment by tannerabread** [comment] 2023-03-03 21:19
I'm not sure if this is just an old issue that was fixed along the way and never closed but I am not seeing this behavior with current versions of amplify and hosting with custom domains.

With a barebones app, I followed [this step](https://docs.amplify.aws/cli/hosting/hosting/#custom-domain-redirects-and-more) to configure hosting through the CLI and then [this guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html) for setting up the custom hosting. I then set up an auth provider following [this guide](https://docs.amplify.aws/lib/auth/social/q/platform/js/#setup-your-auth-provider) and made sure that my [redirect was configured correctly](https://docs.amplify.aws/lib/auth/social/q/platform/js/#full-sample).

I will close this for now as I do not see the problem being mentioned in the original post but if anyone is still experiencing this please comment here so I can re-open and investigate further, or leave steps that might help me reproduce it that are different than what is in the original post.

Thank you!

**Closed by tannerabread** 2023-03-03 21:19 UTC
Labels: feature-request, Auth, Federation
