### ISSUE TITLE
Using S3 image as CSS mask-image triggers CORs error

### ISSUE THREAD

**Issue by rhythmone** [aws-amplify/amplify-js#7870] opened 2021-03-03 20:04 UTC
**Describe the bug**
Trying to use an image already retrieved (and able to be displayed)using a SignedURL as a CSS mask-image, will generate a new CORs error. So, an image already successfully loaded via Storage.get() will disappear.
Apparently using an image in this manner has a different security requirement as noted here:
https://drafts.fxtf.org/css-masking-1/#priv-sec
"User agents must use the potentially CORS-enabled fetch method defined by the [FETCH] specification for all <mask-source>"

**To Reproduce**

1. Display an image using a signedURL
2. Use the same image as a DIV CSS style 'mask-image'
3. The image no longer is available, and the console displays "Access to image at 'https://......' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." **PLEASE NOTE this also happens when running live**, it has nothing to do w/ localhost

**Expected behavior**
Storage.get() should be able to handle this use case so that all URL generation/fetching is going through the same function.

**Code Snippet**
Within Vue component this works:
<div style="width: 500px; height: 500px; background-image: url( signedURL_to_.jpg );"></div>
This will not work (using same image already loaded)
<div style="width: 500px; height: 500px; -webkit-mask-image: url( signedURL_to_.jpg );"></div>

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
 - Storage
 - API
 - Auth
... following all the standard Amplify CLI prompts.

**Is this a production issue?**
Yes, reproducible in PROD as well as LOCALHOST

- [x] (check box if yes)

**Comment by svidgen** [comment] 2021-03-16 19:45
I set up a quick sample to test with and had no issues. I was able to fetch an uploaded image URL and use it for both an image tag and CSS mask. Here are the most pertinent bits:

```
  const [myImage, setMyImage] = useState(undefined);

  useEffect(() => {
    if (myImage === undefined) {
      Storage.get(imageName, { level: "protected" })
        .then(setMyImage)
        .catch(err => console.error('could not generate image URL', err))
      ;
    } else {
      console.log("image loaded", myImage);
    }
  }, [status]);

  return (
    <div className="App">
      <img src={myImage} />
      <div style={{
        width: "200px",
        height: "200px",
        WebkitMaskImage: "url('" + myImage + "')"
      }}></div>
    </div>
  );
```

With this, I'm seeing two image requests go out. The request for the `img` tag is issued with a `no-cors` fetch mode, whereas the one for the css mask is correctly issued in `cors` mode, and it receives `Access-Control-Allow-Origin: *` in the response headers and succeeds.

For reference, my test bucket was created like so:

```
$ amplify add storage
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? You need to add auth (Amazon Cognito) to your project in order to add storage for user files.
Do you want to add auth now? Yes
 Do you want to use the default authentication and security configuration? Default configuration
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
? Please provide a friendly name for your resource that will be used to label this category in th
e project: files
? Please provide bucket name: <<redacted>>
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read, delete
? What kind of access do you want for Guest users? read
? Do you want to add a Lambda Trigger for your S3 Bucket? No
$ amplify push
```

Please confirm your bucket was created similarly and/or has [CORS enabled](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html).

I'm marking this as "Can't Reproduce" for now. Please confirm your bucket's CORS policy and let me know if have more detailed steps to repro with.

**Comment by iartemiev** [comment] 2021-04-12 18:26
@rhythmone,

We are going to close this issue since we have not heard from you. 

Please let us know if you still need support and provide current steps to reproduce if you haven't already. We can reopen the issue to investigate further.

Thanks

**Closed by iartemiev** 2021-04-12 18:26 UTC
Labels: Can't reproduce, Storage, pending-close-response-required
