### ISSUE TITLE
Amplify JS displays blank screen in 11.630.19041.0 when used.

### ISSUE THREAD

**Issue by mathewpadley** [aws-amplify/amplify-js#7303] opened 2020-11-30 16:29 UTC
**Describe the bug**

Vue.js app displays a blank screen after importing the 'aws-amplify' for IE version 11, 11.630.19041.0 (Update Version 11.0.220 KB4586768).

Within vue.config.js the following has also been added:
```
  transpileDependencies: [
    /node_modules\/@aws-amplify/,
    /node_modules\/@aws-crypto/
  ]
```
The app displays correctly in IE 11.0.9600.19867 (Update Version 11.0.220 KB4586768).

In the failing version it throws an error:

* SCRIPT438: Object doesn't support property or method 'from'
* index.js (38,1)

The error is on line:
* var lookupTable = Uint32Array.from([....

This is happening on a larger application but I have replicated with a basic Vue.Js application.

**To Reproduce**

1. Create a Vue.js application on the command-line (Vue.js 2, Typescript).
2. Install aws-amplify from npm (npm install aws-amplify).
3. Add vue.config.js with the following content:
```
module.exports = {
  transpileDependencies: [
    /node_modules\/@aws-amplify/,
    /node_modules\/@aws-crypto/
  ]
};
```
4. Add aws-export.ts to the src route with the following content:
```
import { Auth } from "aws-amplify";

export default {
  Auth: {
    mandatorySignIn: true
  }
};
```
5. Add the following to main.ts
```
import Amplify from 'aws-amplify';

import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
```
6. Run the app (npm run serve).
7. Open IE, and the Developer tools and ensure the Console is the active tab.
8. Navigate to the Vue app url
7. The browser in blank and the console has an error.

I have tried various polyfills that were recommended from the same error on earlier versions of IE11, but none of these did the trick.

**Expected behavior**
The Vue.js boilerplate text appears on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/72504469/100635933-0aa20c80-3329-11eb-9e4c-f7adccf616d4.png)
![image](https://user-images.githubusercontent.com/72504469/100635984-1c83af80-3329-11eb-90b4-cdd758804e7e.png)

**What is Configured?**

* Vue.js - 2.6.11
* aws-amplify - 3.3.10

**Comment by wlee221** [comment] 2020-12-02 06:18
Hi @mathewpadley, with IE11 you would need to add polyfills to your app. Can you try adding polyfills as suggested [here](https://github.com/aws-amplify/amplify-js/issues/4515#issuecomment-671087115), or try other suggestions mentioned in #4515? I will be closing this as this is a duplicate of #4515, but please let us know if this issue persists and we can reopen this issue accordingly.

**Closed** 2020-12-02 06:19 UTC
Labels: Browser Compatibly, to-be-reproduced

**Comment by mathewpadley** [comment] 2020-12-02 11:03
In the end it needed the transpire options in The Vue.config.js changing slightly, no polyfills needed:

`transpileDependencies: ['@aws-amplify', '@aws-crypto']`

not 

`transpileDependencies: [
    /node_modules\/@aws-amplify/,
    /node_modules\/@aws-crypto/
  ]`

**Comment by wlee221** [comment] 2020-12-02 17:50
I see, thanks for letting us know! We'll keep a note of that.
