### ISSUE TITLE
Authentication with Amazon Cognito

### ISSUE THREAD

**Issue by afonsecac** [aws-amplify/amplify-js#8116] opened 2021-04-18 22:43 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.15.1

### Amplify CLI Version

4.48.0

### What operating system are you using?

Ubuntu

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

(0, _getRandomBase.default) is not a function. (In '(0, _getRandomBase.default)(array.byteLength)', '(0, _getRandomBase.default)' is undefined)

### Expected behavior

User Cognito when Auth.signIn(username, password)

### Reproduction steps

1. amplify add api
2. amplify push
3. Configure Amazon Cognito by username
4. Enable MFA
5. Register User
6. Confirm User
7. Error when auth.signIn(username, password)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

**Comment by Antoine-C** [comment] 2021-04-19 08:09
It seems like a duplicate of #8113

**Closed** 2021-05-10 16:11 UTC
Labels: Auth
