### ISSUE TITLE
Android sync - datastore - sync error error database or disk is full (code 13 sqlite_full)

### ISSUE THREAD

**Issue by ajayGadhiya** [aws-amplify/amplify-js#8764] opened 2021-08-16 06:33 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 523.75 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.14.6 
    @babel/runtime: ^7.12.5 => 7.14.6 
    @gorhom/bottom-sheet: ^3.6.6 => 3.6.6 
    @react-native-async-storage/async-storage: ^1.15.5 => 1.15.5 
    @react-native-community/checkbox: ^0.5.8 => 0.5.8 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @react-native-community/masked-view: ^0.1.11 => 0.1.11 
    @react-native-community/netinfo: ^6.0.0 => 6.0.0 
    @types/react-native-extra-dimensions-android: ^1.2.0 => 1.2.0 
    @types/react-native-i18n: ^2.0.0 => 2.0.0 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.0.4 => 5.0.4 
    aws-amplify: ^4.1.3 => 4.1.3 
    aws-amplify-react-native: ^5.0.3 => 5.0.3 
    axios: ^0.21.1 => 0.21.1 
    axios-mock-adapter: ^1.19.0 => 1.19.0 
    babel-jest: ^26.6.3 => 26.6.3 
    date-fns: ^2.22.1 => 2.22.1 
    eslint: 7.14.0 => 7.14.0 
    fbemitter: ^3.0.0 => 3.0.0 
    hermes-inspector-msggen:  1.0.0 
    jest: ^26.6.3 => 26.6.3 
    metro-react-native-babel-preset: ^0.64.0 => 0.64.0 
    moment: ^2.29.1 => 2.29.1 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-extra-dimensions-android: ^1.2.5 => 1.2.5 
    react-native-gesture-handler: ^1.10.3 => 1.10.3 
    react-native-i18n: ^2.0.15 => 2.0.15 
    react-native-interactable: ^2.0.1 => 2.0.1 
    react-native-keyboard-aware-scroll-view: ^0.9.4 => 0.9.4 
    react-native-keyboard-aware-view: ^0.0.14 => 0.0.14 
    react-native-reanimated: ^1.13.3 => 1.13.3 
    react-native-router-flux: ^4.3.1 => 4.3.1 
    react-native-router-flux-cli:  0.0.1 
    react-native-safe-area-context: ^3.2.0 => 3.2.0 
    react-native-screens: ^3.4.0 => 3.4.0 
    react-native-sensitive-info: ^5.5.8 => 5.5.8 
    react-native-snap-carousel: ^3.9.1 => 3.9.1 
    react-native-splash-screen: ^3.2.0 => 3.2.0 
    react-native-svg: ^12.1.1 => 12.1.1 
    react-test-renderer: 17.0.1 => 17.0.1 
    reanimated-bottom-sheet: ^1.0.0-alpha.22 => 1.0.0-alpha.22 
  npmGlobalPackages:
    npm: 6.14.13

```

</details>

### Describe the bug

After start sync expression and sync data to the device, iOS functionality is working properly and smooth but while executing in Android, I got this error “[WARN] 39:56.141 DataStore - Sync error [Error: database or disk is full (code 13 SQLITE_FULL)]” and trap into continuing loading process.

### Expected behavior

We need to sync data in Android device also the same as iOS.
Means data sync is not done even for the first time so I didn’t get data to show/display on the Android side.

### Reproduction steps

1. Auth Login
2. Start sync expression by calling datastore configure
3. Getting error

### Code Snippet

```javascript
// Put your code below this line.
DataStore.configure({
      syncExpressions: [
      syncExpression(OrderVerTwo, () => {
	      const from = addHours(
		      new Date(),
		      ConstantElements.constElements.syncExpressionTime
	      ).toISOString();					
	      return (order) => order.createdAt("ge", from);
      }),
      syncExpression(Transporter, () => {
	      return transporter => transporter.id('eq', userTransporterId);
      }),
      syncExpression(TransporterEvents, () => {
	      return transporterEvent => transporterEvent.transporterID('eq', userTransporterId);
      }),
      syncExpression(Order, () => {
	      return (order) => order.id("eq", null);
      }),
      syncExpression(Patient, () => {
	      return (patient) => patient.id("eq", null);
      }),
      syncExpression(OrderEvent, () => {
	      return (orderEvent) => orderEvent.id("eq", null);
      }),
      syncExpression(BuildingTransitionCosts, () => {
	      return (buildingTransitionCosts) =>
		      buildingTransitionCosts.id("eq", null);
      }),
      syncExpression(OrderNotification, () => {
	      return (orderNotification) => orderNotification.id("eq", null);
      }),
      syncExpression(User, () => {
	      return (user) => user.id("eq", null);
      }),
      syncExpression(UserEvent, () => {
	      return (userEvent) => userEvent.id("eq", null);
      }),
   ],
});
```

### Log output

<details>

```
// Put your logs below this line
WARN  [WARN] 39:56.141 DataStore - Sync error [Error: database or disk is full (code 13 SQLITE_FULL)]
WARN  Possible Unhandled Promise Rejection (id: 0):

```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-XXXXXXXXXX",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-XXXXXXXXXX",
    "aws_user_pools_web_client_id": "XXXXXXXXXX",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "XXXXXXXXXXXXXXX",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "XXXXXXXXXXXXXXX"
};

### Mobile Device

Android-All

### Additional information and screenshots

Log with continue loading with the 
![Screen Shot 2021-08-16 at 11 42 35 AM](https://user-images.githubusercontent.com/70691615/129520711-48e7810c-a4f5-4b2e-8265-e54708a37f91.png)
android device.

**Comment by iartemiev** [comment] 2021-08-19 13:58
Closing, as this is a duplicate of https://github.com/aws-amplify/amplify-js/issues/8640. Please see the comments on that issue.

**Closed by iartemiev** 2021-08-19 13:58 UTC
Labels: React Native, DataStore, pending-triage
