### ISSUE TITLE
Customizable channel name for android

### ISSUE THREAD

**Issue by maxlordks** [aws-amplify/amplify-js#5203] opened 2020-03-26 19:09 UTC
Could you please add ability to change notification channel name from default package name to something custom for android? This value is visible for user at system [notification settings](https://developer.android.com/training/notify-user/channels) screen. 

It will be ok for me when we can pass custom NOTIFICATION_CHANNEL_NAME with PushNotifications configuration. 

There are no other ways to do this because this value is just hardcoded in sources.
Please check [initializing](https://github.com/aws-amplify/amplify-js/blob/7e298bc9f85e2d488163224e9c1c1215227b55b3/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java#L184)
And then [usage](https://github.com/aws-amplify/amplify-js/blob/7e298bc9f85e2d488163224e9c1c1215227b55b3/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java#L297)

**Comment by tannerabread** [comment] 2023-04-18 19:12
Closing this as a duplicate of #8980 and keeping that one open because of screenshots. We prefer to consolidate identical feature-requests into one issue for better tracking.

I have copied over the original post from this one into a [comment](https://github.com/aws-amplify/amplify-js/issues/8980#issuecomment-1513667948) to keep the context

Thank you!

**Closed by tannerabread** 2023-04-18 19:12 UTC
Labels: feature-request, Push Notifications
