### ISSUE TITLE
No userPool error while trying to create a new user

### ISSUE THREAD

**Issue by jahirfiquitiva** [aws-amplify/amplify-js#2690] opened 2019-02-12 05:13 UTC
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
auth

** Provide additional details e.g. code snippets **

Hello

I am trying to setup amplify for authentication, following [this tutorial/guide](https://aws-amplify.github.io/docs/js/authentication) but for some reason, I am getting an error saying `No userPool` when trying to create a new user.

Here's my `app.js` file content:
```javascript
import { Analytics, Auth } from 'aws-amplify';
import awsconfig from './aws-exports';

// retrieve temporary AWS credentials and sign requests
Auth.configure(awsconfig);
// send analytics events to Amazon Pinpoint
Analytics.configure(awsconfig);

const AnalyticsResult = document.getElementById('AnalyticsResult');
const AnalyticsEventButton = document.getElementById('AnalyticsEventButton');
let EventsSent = 0;
AnalyticsEventButton.addEventListener('click', (evt) => {
  Analytics.record('AWS Amplify Tutorial Event')
    .then((evt) => {
      const url = 'https://' + awsconfig.aws_project_region
        + '.console.aws.amazon.com/pinpoint/home/?region=' + awsconfig.aws_project_region
        + '#/apps/' + awsconfig.aws_mobile_analytics_app_id + '/analytics/events';
      AnalyticsResult.innerHTML = '<p>Event Submitted.</p>';
      AnalyticsResult.innerHTML += '<p>Events sent: ' + (++EventsSent) + '</p>';
      AnalyticsResult.innerHTML +=
        '<a href="' + url + '" target="_blank">View Events on the Amazon Pinpoint Console</a>';
    });
});

const username = 'testeo';
const password = 'Testeo213';
const email = 'testeo@test.co';
const phone_number = '+232342342';

Auth.signUp({
  username,
  password,
  attributes: {
    email,          // optional
    phone_number,   // optional - E.164 number convention
    // other custom attributes
  }
})
  .then(data => console.log(data))
  .catch(err => console.log(err));
```

Additionally I have other issues/questions I'd like to do:
1. The url shown in the website, takes me to a 404 error site.
2. I'm unable to find the `aws_cognito_identity_pool_id` value for an already created users group. Where can I find it?
3. I'm unable to setup an already existing identity pool using `amplify add auth`. It always create a completely new pool. How can I setup the existing one?

Thanks in advance!

**Comment by powerful23** [comment] 2019-05-06 23:36
@jahirfiquitiva sorry for the late response. This error is usually caused by duplicated packages under `node_modules`. If you are still having this issue, please check if there are duplicated `@aws-amplify/auth` or `@aws-amplify/core`. You can also paste the `dependencies` of your package.json here

**Comment by powerful23** [comment] 2019-05-09 21:56
Closing the issue. Please let me know if you still have this issue.

**Closed by powerful23** 2019-05-09 21:56 UTC
Labels: Auth, pending-close-response-required, question
