### ISSUE TITLE
Graphql's custom-auth lambda function is not invoked.

### ISSUE THREAD

**Issue by thegoliathgeek** [aws-amplify/amplify-js#9513] opened 2022-01-25 15:43 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 135.39 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.2
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.9
    corepack: 0.10.0
    npm: 8.1.2
    yarn: 1.22.17


```

</details>

### Describe the bug

i have setup the custom authentication with amplify on a model
```graphql
type Module
  @model
  @auth(
    rules: [{ allow: custom }]
  ) {
  id: ID!
  name: String
}
```

I have also setup a lambda for this ,for verification of the token.

Am getting my jwt from cognito.
It seems lambda (custom auth) is not trigged.
When the header is (this is the default auth header from amplify)

`Authorization: {jwt}`

But when i change header

`Authorization: Bearer {jwt}`

Lambda is triggered when auth header used as above with Bearer.

Why is not getting trigged in the first pattern?
Amplify lib is using this `Authorization: {jwt}` by default for network calls.

This is a problem when we are using different types of auths like
1. [Signed-in user data access](https://docs.amplify.aws/cli/graphql/authorization-rules/#signed-in-user-data-access)
2. [User group-based data access](https://docs.amplify.aws/cli/graphql/authorization-rules/#user-group-based-data-access)

This auth only work when auth header is `Authorization: {jwt}`

### Expected behavior

Custom auth lambda should be invoked for  `Authorization: {jwt}` header type.
It's only invoked for `Authorization: Bearer {jwt}`.

### Reproduction steps

1. Add auth with cognito
2. Create a schema as below
```graphql
type Module
  @model
  @auth(
    rules: [{ allow: custom }]
  ) {
  id: ID!
  name: String
}
```
2. Follow these [steps](https://docs.amplify.aws/cli/graphql/authorization-rules/#custom-authorization-rule) to add a custom auth function.
3. Making a graphql call to the respective model.

### Code Snippet

```graphql
query{
  listModules{
    items{
      id
      name
    }
  }
}
```

### Log output

<details>

```json

{
  "data": {
    "listModules": null
  },
  "errors": [
    {
      "path": [
        "listModules"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access listModules on type ModelModuleConnection"
    }
  ]
}

```

</details>

**Comment by chrisbonifacio** [comment] 2022-01-26 15:21
Hi @imdhanush 👋 can you try setting the authMode of your graphql query to "AWS_LAMBDA"?

example:

```js
const modules = await API.graphql({
  query: listModules,
  authMode: "AWS_LAMBDA"
})
```

Let me know if this helps

**Comment by imdhanush** [comment] 2022-01-26 15:54
Hi @chrisbonifacio 
I tried the method you suggested above. 
With both appsync console and library.
Still facing the same issue.

According to this [doc](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#aws-lambda-authorization). The auth token size must not exceed 2048 characters. 
I checked my token size it's 1066.

**Comment by chrisbonifacio** [comment] 2022-01-26 16:17
You mentioned it only works if the authorization header is set to `Bearer {jwt}`, correct? What does your lambda response logic look like?

**Comment by chrisbonifacio** [comment] 2022-01-26 16:49
I just tried hardcoding a string on my custom lambda, didn't include `Bearer` on the client and was able to make the call.

Unauthorized
```js
    API.graphql({
      query: listTodos,
      authMode: "AWS_LAMBDA",
      authToken: "Bearer test123",
    })
```
<img width="893" alt="Screen Shot 2022-01-26 at 11 45 48 AM" src="https://user-images.githubusercontent.com/16952986/151207769-626a15d2-dfd8-4eaf-a5b3-6eb8eaacd97c.png">

Authorized

```js
    API.graphql({
      query: listTodos,
      authMode: "AWS_LAMBDA",
      authToken: "test123",
    })
```

<img width="893" alt="Screen Shot 2022-01-26 at 11 46 39 AM" src="https://user-images.githubusercontent.com/16952986/151207939-d7eadc35-ae7a-45be-9144-31d1d8df621a.png">

Are you sure that the logic that verifies the jwt in your lambda is correct?

**Comment by imdhanush** [comment] 2022-01-26 16:56
Yes it only works when authorization header is set to `Bearer {jwt}`.

The response looks like this 
```json
{
    "isAuthorized": true,
    "deniedFields": [],
    "ttlOverride": 2,
    "resolverContext": {
        "app": "name"
    }
}

```

**Comment by chrisbonifacio** [comment] 2022-01-26 18:26
what is the logic that returned `true` for `isAuthorized` in the lambda function?

**Comment by imdhanush** [comment] 2022-01-27 04:02
Am passing the token which i get from cognito after login and verify it using the keys from
`https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json`
if jwt is verify i return `true` for a `isAuthorized ` else return `false`

**Comment by imdhanush** [comment] 2022-01-27 04:43
This one is triggering lambda for `Authorization: 123456` and i can see the logs in lambda.
<img width="665" alt="Screenshot 2022-01-27 at 10 08 43 AM" src="https://user-images.githubusercontent.com/37190602/151293141-fbdd46f1-e136-4ae8-a60d-1c7a8118e96d.png">

This one is not triggering lambda for `Authorization: {jwt}` and i can't see the logs in lambda.
<img width="670" alt="Screenshot 2022-01-27 at 10 09 58 AM" src="https://user-images.githubusercontent.com/37190602/151293140-6807aee7-d359-4f41-a38f-a3aaeba14673.png">

**Comment by chrisbonifacio** [comment] 2022-01-27 18:40
So, the 401 "You are not authorized to make this call" error is normal for when the lambda returns `isAuthorized` as `false`. The lambda is being invoked and you should be able to see that in your cloudwatch logs.

However, the graphql error saying you're not authorized to access the `listModules` seems off. I was able to reproduce this and while the call seems to be making it far enough to get the appsync/graphql error, `isAuthorized` is still being returned as `false` in my logs with a valid access token and I'm not sure why yet.

This is the logic in my lambda authorizer for comparison

```js
// This is sample code. Please update this to suite your schema
const { CognitoJwtVerifier } = require("aws-jwt-verify");

exports.handler = async (event) => {
  console.log(`event >`, JSON.stringify(event, null, 2));
  const {
    authorizationToken,
    requestContext: { apiId, accountId },
  } = event;

  let isAuthorized = false;

  const verifier = CognitoJwtVerifier.create({
    userPoolId: "us-east-1_UrraAvHrw",
    tokenUse: "access",
    clientId: "7gb622j3ir3oatedu8fodci6ev",
  });

  try {
    const payload = await verifier.verify(authorizationToken);
    console.log("Token is valid. Payload: ", payload);
    isAuthorized = true;
  } catch (error) {
    console.log("Token not valid");
  }

  const response = {
    isAuthorized,
    resolverContext: {
      userid: "test user",
      info: "contextual information A",
      more_info: "contextual information B",
    },
    deniedFields: [
      `arn:aws:appsync:${process.env.AWS_REGION}:${accountId}:apis/${apiId}/types/Event/fields/comments`,
      `Mutation.createEvent`,
    ],
    ttlOverride: 300,
  };

  console.log(`response >`, JSON.stringify(response, null, 2));
  return response;
};
```

Cloudwatch logs

<img width="1369" alt="Screen Shot 2022-01-27 at 1 20 25 PM" src="https://user-images.githubusercontent.com/16952986/151422754-4acee868-d02b-45ba-878c-c5cf70878a14.png">

I've reached out to the team to investigate this further. Might be something I'm just missing or unaware of here.

**Comment by chrisbonifacio** [comment] 2022-01-27 20:20
So, after digging into this further. It seems like the requests without `Bearer` in the auth header are being auto-rejected by AppSync. Had to turn on my AppSync logs too see that (which I don't recommend, as it can have unexpected increases on your bill).

So, I'm not quite sure why a jwt without `Bearer` gets auto-rejected when a regular string like `"test12345"` doesn't - still trying to figure that out.

But, I also found that not including an auth token in your `API.graphql` call with an authMode of `AWS_LAMBDA` will result in an error anyway. So, Amplify wouldn't have automatically made the request with its usual auth header anyway. So, I don't think this is an issue or bug, at least not with the JS library.

You'll have to adjust your lambda to remove the `Bearer` part of the auth header before verifying it but once you do that, just include it in your call and the lambda should work like you'd expect.

My lambda logic

```js
const { CognitoJwtVerifier } = require("aws-jwt-verify");

exports.handler = async (event) => {
  console.log(`event >`, JSON.stringify(event, null, 2));
  const {
    authorizationToken,
    requestContext: { apiId, accountId },
  } = event;

  let isAuthorized = false;

  const verifier = CognitoJwtVerifier.create({
    userPoolId: "us-east-1_UrraAvHrw",
    tokenUse: "access",
    clientId: "7gb622j3ir3oatedu8fodci6ev",
  });

  // have to include "Bearer" in the auth header for the lambda to be invoked, but we'll remove it here to verify the token
  const jwt = authorizationToken.replace(/^Bearer\s/, ""); 

  try {
    const payload = await verifier.verify(jwt);
    console.log("Token is valid. Payload: ", payload);
    isAuthorized = true;
  } catch (error) {
    console.log("Token not valid");
  }

  const response = {
    isAuthorized,
    resolverContext: {
      userid: "test user",
      info: "contextual information A",
      more_info: "contextual information B",
    },
    deniedFields: [
      `arn:aws:appsync:${process.env.AWS_REGION}:${accountId}:apis/${apiId}/types/Event/fields/comments`,
      `Mutation.createEvent`,
    ],
    ttlOverride: 300,
  };

  console.log(`response >`, JSON.stringify(response, null, 2));
  return response;
};
```

Client-side API GraphQL query
```js
const res = await API.graphql({
  query: listTodos,
  authMode: "AWS_LAMBDA",
  authToken: `Bearer ${(await Auth.currentSession())
    .getAccessToken()
    .getJwtToken()}`,
});
```

Result:
<img width="1451" alt="Screen Shot 2022-01-27 at 3 20 11 PM" src="https://user-images.githubusercontent.com/16952986/151437342-5ed2ad0d-6144-4452-94e7-bc5a1b406fff.png">

🙌

**Comment by imdhanush** [comment] 2022-01-28 02:53
Hey @chrisbonifacio 
Thank you for this. 
But can this be fixed? So that we don't have to use `Bearer` in the auth header for custom-auth.
```graphql
type Module @model @auth(rules: [{ allow: custom }]) {
  id: ID!
  name: String
}

type Permission
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["enterprise-admins"] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  name: String
  module: Module @hasOne
  create: Boolean
  read: Boolean
  update: Boolean
  delete: Boolean
}
```

For the above schema i'll make a nested query like this
```graphql
query{
 listPermissions{
  items{
    id
    name
    module{
      id
      name
    }
  }
}
}
```
As both models have different authorization rules.
`Permission` model requires `Authorization: {jwt}`
`Module` model (custom-auth) requires `Authorization: Bearer {jwt}`

<img width="641" alt="Screenshot 2022-01-28 at 8 15 26 AM" src="https://user-images.githubusercontent.com/37190602/151478656-37bb14f9-8b4e-4dac-b083-fc1c7e5b9e49.png">

<details>
<summary>output </summary>

```json
{
  "data": {
    "listPermissions": {
      "items": [
        {
          "id": "d7cb9f3b-eb62-4fc6-a0a7-80426142c4cd",
          "name": "editors_permission",
          "module": null
        }
      ]
    }
  },
  "errors": [
    {
      "path": [
        "listPermissions",
        "items",
        0,
        "module"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 5,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access module on type Module"
    }
  ]
}
```
</details>

Now only `Permission` module is accessible. 
If we use pass auth header with `Bearer {jwt}`
<img width="669" alt="Screenshot 2022-01-28 at 8 20 28 AM" src="https://user-images.githubusercontent.com/37190602/151478958-ef2e8262-2aa1-41a6-8dc1-495c01b39975.png">

The whole query fails.

**Comment by chrisbonifacio** [comment] 2022-02-03 15:27
Hey @imdhanush apologies for the delay. So, I spoke to the AppSync team and while this is not exactly a bug, because the service is working as intended, it is something that we should document better.

When the service is authorizing credentials, all it knows is the auth types configured for an API and the credentials provided. It’ll check what the credentials look like against what an auth type expects to try to infer what auth type is in use. Because a cognito token is what was provided and a cognito provider is associated with the api, cognito auth is what was inferred.

We are currently looking to update the documentation to clear this up.

**Comment by imdhanush** [comment] 2022-02-04 05:15
Hey, @chrisbonifacio thank you for this.
Nested query with different auth modes is a much-needed requirement for me. 
So are there any alternatives to this?

**Comment by chrisbonifacio** [comment] 2022-02-09 00:53
Hey @imdhanush sorry for the delay. Just to want to make sure I understand your use case.

Is there a reason why you're using a Lambda to verify Cognito tokens instead of utilizing the `private` or `group` auth rules instead for both models?

**Comment by imdhanush** [comment] 2022-02-10 15:52
Hey @chrisbonifacio ,
Yes I'll move all model to `custom` auth. 
Thank you :).

**Comment by chrisbonifacio** [comment] 2022-04-07 19:30
Hey! @imdhanush 👋 wanted to follow up with you on this issue, AppSync is working on a fix but there is a workaround until it gets implemented which should allow you to use any other auth directives you needed before.

https://github.com/aws-amplify/amplify-cli/issues/10047

> @jevakallio - AppSync confirmed that this is a bug and working on a fix.
> 
> To mitigate the issue, send `resolverContext` as empty object or any value on the authorizer lambda response. If the `resolverContext` is passed, then AppSync detects the authType as expected. https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#aws-lambda-authorization

**Comment by chrisbonifacio** [comment] 2022-04-08 14:04
@imdhanush scratch that, this workaround is actually for a separate issue, I confused the issue that was opened on the CLI to be the same as this one. The workaround for this particular is still the same as I mentioned - adding `Bearer` or a prefix/suffix to the token and removing it in the lambda.

I opened an internal service ticket for the AppSync team and they are going to add this to their documentation.

Apologies for the confusion!

**Comment by arundna** [comment] 2022-07-12 15:14
@thegoliathgeek Apologies for the delayed response on this one. @chrisbonifacio worked with our AppSync team and we’ve made changes to our AppSync documentation to clarify the scenario and also added the workaround section - **Circumventing SigV4 and OIDC token authorization limitations**

https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#aws-lambda-authorization

I'll go ahead and close this out, but feel free to open a new issue if you have further questions.

**Closed by arundna** 2022-07-12 15:14 UTC
Labels: bug, GraphQL, Service Team, p3

**Comment by JoshuaWarejko** [comment] 2022-07-15 00:00
@arundna Just a heads up: we had "Bearer" in front of our OIDC tokens for lambda auth for the last 2 months as a workaround but it randomly stopped working today and started to return the error "Not authorized to perform x on type Query". Changing the prefix to anything else caused it to start working again. Is "Bearer" a reserved word for something else now in AppSync? I don't see this documented anywhere but Bearer no longer works for us.

**Comment by mewtlu** [comment] 2022-07-20 10:23
We've suddenly been having the same issue as JoshuaWarejko as of the last week, spent significant time trying to diagnose the cause of the problem across each of our environments and it has turned out to be this problem, seemingly due to something being silently changed within AppSync/Amplify?
Very agonized to have wasted so much time diagnosing such a problem, but it seems like we now have a workaround by using a separate authorization prefix than Bearer in the request and in our custom authorizer function.

**Comment by chrisbonifacio** [comment] 2022-07-26 04:03
@JoshuaWarejko @mewtlu Hello and apologies for the delay. The AppSync reached out to me to confirm that "Bearer" is indeed a reserved word for OIDC now as defined by the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html).

**Comment by JoshuaWarejko** [comment] 2022-07-26 17:22
@chrisbonifacio Thanks for the update, good to know.
