### ISSUE TITLE
API does not exist. 

### ISSUE THREAD

**Issue by my-name-is-nheo** [aws-amplify/amplify-js#8277] opened 2021-05-14 18:00 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports). (found similar issues, but different approach or irrelevant to my issue)
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

REST API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

npm install
npm run android

```

</details>

### Describe the bug

Recently made some accidental changes to my main branch and had to revert. Once I recloned my repo,  I'm getting this error (API ___ does not exist). These were all existing APIs, storages, etc, I did not use the CLI, only CLI command I used was amplify configure to add my IAM information.  It was working great till today. the app in production is working great, and I see in the logger that cognito is working with no issues. But I dont see anything regarding APIs..
Help appreciated...

This is how it looks... 
![Screen Shot 2021-05-14 at 1 37 10 PM](https://user-images.githubusercontent.com/58013260/118309601-7c2add00-b4bb-11eb-87c3-1cbc7428c8d2.png)

### Expected behavior

NO API ERRORS

### Reproduction steps

1. git clone repo
2. npm install
3. npm run android
4. Tried loggin in, cognito is working great
5. API ___ does not exist error. 

### Code Snippet

```javascript
const awsconfig = {
  Auth: {
    identityPoolId: '**********2',
    region: '******',
    userPoolId: '******',
    userPoolWebClientId: '*****',
  },
  Storage: {
    bucket: '****',
    region: '*****',
  },
  Analytics: {
    AWSPinpoint: {
      appId: '****',
      region: '****',
      requestIOSPermissions: true,
    },
  },
  API: {
    endpoints: [
      {
        name: '*****',
        endpoint: '****',
      },
    ],
  },
};

Amplify.configure(awsconfig);

```

### Log output

<details>

```
// Put your logs below this line
     Error API ******* does not exist
[Fri May 14 2021 13:47:53.000]  LOG      ::ERROR:: null

```

</details>

### Manual configuration

```javascript
const awsconfig = {
  Auth: {
    identityPoolId: '**********2',
    region: '******',
    userPoolId: '******',
    userPoolWebClientId: '*****',
  },
  Storage: {
    bucket: '****',
    region: '*****',
  },
  Analytics: {
    AWSPinpoint: {
      appId: '****',
      region: '****',
      requestIOSPermissions: true,
    },
  },
  API: {
    endpoints: [
      {
        name: '*****',
        endpoint: '****',
      },
    ],
  },
};

Amplify.configure(awsconfig);

```

**Comment by xnf** [comment] 2021-05-14 21:14
Have you tried restoring env from the cloud? 
`amplify env pull --restore`

**Comment by my-name-is-nheo** [comment] 2021-05-15 03:21
I did but it didn't work. My only solution was to start new a project and copy the files over. Do you know why it's causing this issue?

**Comment by chrisbonifacio** [comment] 2021-05-15 03:53
Would you mind sharing your package.json? Just would like to see which amplify packages and versions you might be using.

If you have some code snippets of how you're using API? In the error you shared it looks like it's saying the endpoint you're trying to make requests to doesn't exist.

**Comment by my-name-is-nheo** [comment] 2021-05-15 05:02
```
    "@aws-amplify/analytics": "^4.0.9",
    "@aws-amplify/pushnotification": "^3.2.21",
    "@aws-amplify/ui-react": "^0.2.33",
    "amazon-cognito-identity-js": "^4.5.6",
    "aws-amplify": "^3.3.18",
    "aws-amplify-react-native": `"^4.2.10",
//These are all the relevant packages
```

```

export const saveAttributes = (data) => (dispatch, getState) => {
  try {
    return new Promise<void>(async (resolve, reject) => {
      const {
        reducer: {apiPath},
      } = getState();
 
  
      let apiName = '';
      let path = `/${apiPath}/x/y`;
      let options = {}
API.post(apiName, path, options)
        .then((res) => { ...
```

**Comment by chrisbonifacio** [comment] 2021-05-15 18:43
Can you also share the error you're getting either from the console and/or network tab?

**Comment by jazu-dev** [comment] 2021-05-16 08:32
Hello, I'm facing the exact same issue but for web, getting `API apib3ff6150 does not exist` with no API request being sent when using `API.get('apib3ff6150' ... )` and no errors (using latest amplify libraries and CLI)

[This SO thread](https://stackoverflow.com/questions/65196042/aws-amplify-rest-api-cannot-find-the-api) suggests trying to separately configure API with `Auth.configure(awsconfig)`, which is weird as I would expect `Amplify.configure(awsconfig)` to take care of that as well. Nevertheless,  I tried that and I no longer got the original issue with API not existing. But now amplify JS indeed tries to reach the API but doesn't automatically generate an Authorization header at all (even though I can verify Auth.currentUserCredentials() returns proper access keys and session token) so it ends up failing with 403 naturally.

Any ideas why this happens? 

Btw, @chrisbonifacio let me know if you think its different from the native issue and a separate GH issue is preferable to track for the web

**Comment by chrisbonifacio** [comment] 2021-05-17 13:17
I would try to follow the instructions here to check for duplicate packages.
https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js

 It might help to either make sure all the packages are up to date or remove any of the scoped packages if you have `aws-amplify` installed. You can still use the scoped packages by importing them from there instead.

**Comment by jazu-dev** [comment] 2021-05-17 16:58
Indeed I was using both scoped and non scoped versions of aws-amplify with discrepancies in the versions. After addressing that API requests are working correctly for the web, thanks! 🙏

**Comment by chrisbonifacio** [comment] 2021-05-17 17:32
@jazu-dev Awsome! Happy to hear that 😄 

@my-name-is-nheo Please let me know if this works for you as well. I don't want to close this issue until we find out if it works for you in case the cause might be different.

**Comment by my-name-is-nheo** [comment] 2021-05-17 17:33
@chrisbonifacio Yup that helped a lot thanks!

**Closed** 2021-05-17 17:36 UTC
Labels: API, investigating

**Comment by chrisbonifacio** [comment] 2021-05-17 17:37
Thanks for the quick reply! And anytime 😃 Have a great week!
