### ISSUE TITLE
Method updateEndpoint in Analytics/PushNotification not work receive 403 forever

### ISSUE THREAD

**Issue by padil** [aws-amplify/amplify-js#7131] opened 2020-11-06 17:01 UTC
**PushNotification method updateEndpoint**
updateEndpoint received 403 and I already fixed the aws policy and still giving this error

**To Reproduce**
To reproduce just start the application that the app will try to update the AddressEndpoint of Address and will give error.

**Expected behavior**
To be able to do the updateEndpoint and after that to be able to fire Push to the application

**Code Snippet**

```

const awsConfig = {
  aws_cognito_identity_pool_id: Config.AWS_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: Config.AWS_COGNITO_REGION,
  aws_mobile_analytics_app_id: Config.AWS_MOBILE_ANALYTICS_APP_ID,
  aws_mobile_analytics_app_region: Config.AWS_MOBILE_ANALYTICS_APP_REGION,
  aws_project_region: Config.AWS_PROJECT_REGION,
  oauth: {},
};

async configure() {
    this.amplifyConfigure();
    PushNotification.configure(awsConfig);
    PushNotification.onRegister(async (token: string) => {
      await this.updateEndpoint({
        address: token,
      });
    });
}

amplifyConfigure() {
    const channelType = isAndroid() ? 'GCM' : 'APNS';
    Amplify.configure({
      Analytics: {
        AWSPinpoint: {
          appId: awsConfig.aws_mobile_analytics_app_id,
          endpoint: {
            channelType,
          },
          endpointId: DeviceInfo.getUniqueId(),
          region: awsConfig.aws_mobile_analytics_app_region,
        },
      },
      Auth: {
        identityPoolId: awsConfig.aws_cognito_identity_pool_id,
        region: awsConfig.aws_cognito_region,
      },
      PushNotification: {
        appId: awsConfig.aws_mobile_analytics_app_id,
      },
    });
  }
```

**Screenshots**
<img width="1094" alt="Screenshot 2020-11-05 at 10 35 36" src="https://user-images.githubusercontent.com/12433703/98393236-c5dfca00-2037-11eb-8b02-ad9ebb91ac92.png">
 

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 609.45 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 87.0.4280.47
    Safari: 14.0
  npmPackages:
    @aws-amplify/pushnotification: ^3.2.10 => 3.2.10
    @babel/core: 7.8.7 => 7.8.7
    @babel/runtime: ^7.8.7 => 7.8.7
    @dynatrace/react-native-plugin: ^1.192.2 => 1.198.0
    @react-native-community/async-storage: ^1.8.1 => 1.8.1
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5
    @react-native-community/masked-view: ^0.1.7 => 0.1.7
    @react-native-community/netinfo: ^5.5.1 => 5.6.2
    @react-native-community/push-notification-ios: ^1.7.1 => 1.7.1
    @react-native-firebase/analytics: ^6.3.4 => 6.3.4
    @react-native-firebase/app: ^6.3.4 => 6.3.4
    @react-native-firebase/messaging: ^6.3.4 => 6.3.4
    @react-native-firebase/remote-config: ^6.3.4 => 6.3.4
    @redux-saga/testing-utils: ^1.1.3 => 1.1.3
    @storybook/addon-actions: ^5.3.14 => 5.3.17
    @storybook/addon-knobs: ^5.3.14 => 5.3.17
    @storybook/addon-links: ^5.3.14 => 5.3.17
    @storybook/addon-ondevice-knobs: ^5.3.14 => 5.3.17
    @storybook/addon-ondevice-notes: ^5.3.14 => 5.3.17
    @storybook/addons: ^5.3.14 => 5.3.17
    @storybook/react-native: ^5.3.14 => 5.3.17
    @storybook/react-native-server: ^5.3.14 => 5.3.17
    @testing-library/react-hooks: ^3.2.1 => 3.2.1
    @types/graphql: ^14.5.0 => 14.5.0
    @types/jest: ^25.1.4 => 25.1.4
    @types/lodash: ^4.14.149 => 4.14.149
    @types/numeral: ^0.0.26 => 0.0.26
    @types/react-native: ^0.60.25 => 0.60.31
    @types/react-native-keychain: ^3.1.0 => 3.1.0
    @types/react-native-share: ^3.0.0 => 3.1.0
    @types/react-navigation: ^3.4.0 => 3.4.0
    @types/react-redux: ^7.1.9 => 7.1.9
    @types/react-test-renderer: 16.9.1 => 16.9.1
    @types/redux: ^3.6.0 => 3.6.0
    @types/redux-saga: ^0.10.5 => 0.10.5
    @types/sinon: ^7.5.2 => 7.5.2
    @typescript-eslint/eslint-plugin: ^2.12.0 => 2.24.0
    @typescript-eslint/parser: ^2.12.0 => 2.24.0
    android-notification-settings: ^1.0.3 => 1.0.3
    apollo-boost: ^0.4.9 => 0.4.9
    apollo-cache-inmemory: ^1.6.6 => 1.6.6
    apollo-client: ^2.6.8 => 2.6.8
    apollo-link: ^1.2.14 => 1.2.14
    apollo-link-batch-http: ^1.2.14 => 1.2.14
    apollo-link-context: ^1.0.20 => 1.0.20
    apollo-link-error: ^1.1.13 => 1.1.13
    apollo-link-timeout: ^1.4.1 => 1.4.1
    apollo-link-ws: ^1.0.20 => 1.0.20
    apollo-utilities: ^1.3.4 => 1.3.4
    aws-amplify: ^3.3.7 => 3.3.7
    babel-jest: ^25.1.0 => 25.1.0
    babel-loader: ^8.0.6 => 8.0.6
    babel-plugin-module-resolver: ^4.0.0 => 4.0.0
    eslint: ^6.5.1 => 6.8.0
    husky: ^4.2.3 => 4.2.3
    jail-monkey: ^2.3.2 => 2.3.2
    jest: ^25.1.0 => 25.1.0
    jetifier: ^1.6.5 => 1.6.5
    lodash: ^4.17.13 => 4.17.15
    lottie-ios: 3.1.3 => 3.1.3
    lottie-react-native: ^3.3.2 => 3.3.2
    metro-react-native-babel-preset: ^0.56.0 => 0.56.4
    mocha: ^5.2.0 => 5.2.0
    moment: ^2.24.0 => 2.24.0
    numeral: ^2.0.6 => 2.0.6
    react: 16.9.0 => 16.9.0
    react-apollo: 2.3.2 => 2.3.2
    react-dom: ^16.13.0 => 16.13.0
    react-hook-hooked: ^1.0.3 => 1.0.3
    react-native: 0.61.5 => 0.61.5
    react-native-android-wifi: ^0.0.41 => 0.0.41
    react-native-biometrics: ^2.1.4 => 2.1.4
    react-native-config: ^0.12.0 => 0.12.0
    react-native-device-info: ^5.5.3 => 5.5.3
    react-native-exit-app: ^1.1.0 => 1.1.0
    react-native-gesture-handler: ^1.7.0 => 1.7.0
    react-native-keychain: ^5.0.1 => 5.0.1
    react-native-markdown-renderer: ^3.2.8 => 3.2.8
    react-native-permissions: ^2.1.5 => 2.1.5
    react-native-rate: ^1.1.10 => 1.1.10
    react-native-reanimated: ^1.7.0 => 1.7.0
    react-native-restart: ^0.0.14 => 0.0.14
    react-native-safe-area-context: ^0.7.3 => 0.7.3
    react-native-screens: ^2.2.0 => 2.3.0
    react-native-share: ^3.0.0 => 3.1.1
    react-native-svg: ^12.0.3 => 12.0.3
    react-native-svg-renderer: ^0.2.0 => 0.2.0
    react-native-swipe-gestures: ^1.0.5 => 1.0.5
    react-native-view-pdf: ^0.10.1 => 0.10.1
    react-native-webview: ^9.0.2 => 9.0.2
    react-navigation: 4.2.2 => 4.2.2
    react-navigation-stack: ^2.2.3 => 2.3.2
    react-navigation-tabs: ^2.8.2 => 2.8.5
    react-redux: ^7.2.0 => 7.2.0
    react-test-renderer: ^16.13.0 => 16.13.0
    redux: ^4.0.5 => 4.0.5
    redux-devtools-extension: ^2.13.8 => 2.13.8
    redux-saga: ^1.1.3 => 1.1.3
    rn-fetch-blob: ^0.12.0 => 0.12.0
    sinon: ^9.0.1 => 9.0.1
    sonarqube-scanner: ^2.6.0 => 2.6.0
    ts-jest: ^25.2.1 => 25.2.1
    tslint: ^6.1.0 => 6.1.0
    tslint-config-prettier: ^1.18.0 => 1.18.0
    tslint-jest-rules: ^1.0.2 => 1.0.2
    tslint-plugin-prettier: ^2.2.0 => 2.2.0
    tslint-react: ^4.2.0 => 4.2.0
    tslint-react-a11y: ^1.1.0 => 1.1.0
    typescript: ^3.7.3 => 3.8.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.29.6
    bower: 1.8.8
    dynamodb-admin: 4.0.0
    eslint: 7.4.0
    expo-cli: 3.28.5
    grunt-cli: 1.3.2
    jest: 26.0.1
    json-server: 0.16.1
    npm: 6.13.4
    prettier: 2.0.5
    react-native-cli: 2.0.1
    react-native: 0.62.2
    stryker-cli: 1.0.0
    yarn: 1.22.0
```

</details>

**Smartphone (please complete the following information):**

- Device: [Android Xiomi]
- OS: [Android]
- Version [e.g. 29]

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**
<img width="1114" alt="Screenshot 2020-11-05 at 15 25 45" src="https://user-images.githubusercontent.com/12433703/98393665-5f0ee080-2038-11eb-8aec-a7583714979e.png">

**Comment by CryogenicPlanet** [comment] 2020-11-09 17:38
@padil Can you please attach your full enviornment, you just attached the command without adding the result of that command

**Comment by padil** [comment] 2020-11-09 17:43
udpate ;)

**Comment by CryogenicPlanet** [comment] 2020-11-09 17:45
@padil It would also be great if you could just drop a link to a minimum reproducible example like a full repo instead of just the code snippet

**Comment by padil** [comment] 2020-11-09 17:48
@CryogenicPlanet unfortunately it is not possible to reproduce so simple, it has to be simulated on a physical device

**Comment by CryogenicPlanet** [comment] 2020-11-09 17:52
@padil Yeah that is okay, but it would be easier for us to verify the bug if you could give us the code sample and we can simulate it on a physical device or even just steps for reproduction. Like right now I am not even sure if you are building using `expo` or not so our enviornment might cause other issues

**Comment by padil** [comment] 2020-11-09 17:54
I'm not an expo, go up the environments

**Comment by CryogenicPlanet** [comment] 2020-11-09 18:52
@padil I think there is a bug in the code

```javascript
const channelType = isAndroid() ? 'GCM' : 'APNS';
```
where the channel type should be `'FCM'`, this may not be the single issue because I have still not been able to fully reproduce the bug but would recommend trying it out from your end

**Comment by padil** [comment] 2020-11-10 13:15
tested here and continue the same thing :/

**Comment by CryogenicPlanet** [comment] 2020-11-10 13:24
@padil That's unfortunate. There is something you can help me out with which wasn't clear on the docs which I'll be sure to update for this was where did you get the Firebase API Key to setup amplify notifications. I couldn't find that api key anywhere on the firebase console

**Comment by padil** [comment] 2020-11-10 13:31
generated the token via aws-amplify-cli, follow link:

https://docs.amplify.aws/cli/start/install

**Comment by CryogenicPlanet** [comment] 2020-11-10 14:38
Oh I meant where I could get the FCM api key but I found it.

For the issue to be replicated, you'd also need to provide the actually 
```javascript
Analytics.updateEndpoint() 
```
call and what you are passing inside that. That wasn't there in the code snippet @padil

**Comment by padil** [comment] 2020-11-10 14:55
the one who executes the updateEndpoint method is the lib itself that does this, so I understand from the library who does this is the onRegister itself. But I also perform this function inside, follow below:

```
async updateEndpoint(endpointData: Endpoint) {
    try {
      const response = await Analytics.updateEndpoint(endpointData);
      console.log('response', response)
    } catch (e) {
      // tslint:disable-next-line:no-console
      console.warn(
        'Unable to update Amplify endpoint for user:',
        endpointData.userId,
        e,
      );
    }
  }

this.updateEndpoint({
        demographic: {
          appVersion: 1.2.3,
          locale: '',
          model: 'model',
          modelVersion: '',
          platform: 'Platform',
          platformVersion: getPlatformVersion(),
          timezone: '',
        },
        metrics: { dueDate },
        userAttributes: {
            type: 'type'
        },
        userId: 12345,
      });
```

**Comment by CryogenicPlanet** [comment] 2020-11-10 19:34
@padil I am still trying to get my environment working having some troubles because of wsl but I found another typo that could be causing an error; surprised typescript didn't yell about this.
```javascript
this.updateEndpoint({
        demographic: {
          appVersion: 1.2.3, // this is not a valid type, it isn't a number or a string

```
I would recommend **changing that regardless to a string** as that is what is shown in the docs.
 Also would like to known where `dueDate` is coming from and what type that object is, it would be much easier if you could paste the whole file or most of the file so I don't need to keep getting back to you.

**Comment by padil** [comment] 2020-11-10 19:41
appVersion is a string, I just pasted it wrong and changed the variables only, dueDate also a string in date format @CryogenicPlanet

**Comment by mauerbac** [comment] 2020-12-16 20:17
Will close this issue as we don't have an enough information. Please let us know if you are still experiencing this issue.

**Closed by mauerbac** 2020-12-16 20:17 UTC
Labels: Analytics, Push Notifications
