### ISSUE TITLE
Auth.currentAuthenticatedUser should return error if user is signed out globally from backend (may be with aws cli).

### ISSUE THREAD

**Issue by mmritesh** [aws-amplify/amplify-js#2638] opened 2019-01-31 06:57 UTC
**Describe the bug**
Auth.currentAuthenticatedUser returns CognitoUser evenif the access token for the user is invalidated from backend (i.e. signed out globally with aws cli which invalidated all the tokens including refresh token: https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/global-sign-out.html)
 

**To Reproduce**
0. Have react application having basic functionality for signin/ signout/ home page etc..
1. Signin using amplify sign in api
2. U have the access, id, refresh token in ur configured storage.
3. on componentDidMount call 
```
Auth.currentAuthenticatedUser()
        .then((session) => {
            console.log("In then block");
               
        })
        .catch((error) => {
            console.log("In catch block")
            this.setState({validSession: false});
        })   
 ```
4. get the access token from you configured storage use aws cli to signout globally. this will invalidate all your token.
5. Refresh the page

**Expected behavior**
Actually we want to automatically sign out the user from the application. so we are checking 
Auth.currentAuthenticatedUser() should return error but it still returns CognitoUser object.

Is there any other way to automatically signout in such case?

**Comment by mmritesh** [comment] 2019-02-01 06:01
Already tried. No luck.

**Comment by drphelps** [comment] 2019-03-06 19:21
The `CognitoUser` object returned by `Auth.currentAuthenticatedUser({ bypassCache: true })` after global sign-out has no `attributes`. Additionally, `user.signInUserSession.isValid()` returns `true`. This is pretty counter-intuitive.

The call to the Cognito IdP throws a 404 with the following debug info and no clear way to recover gracefully from this state.
```
[DEBUG] 15:56.207 AuthClass - getting user data failed {code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Access Token has been revoked"}
```

**Comment by powerful23** [comment] 2019-04-08 18:15
The issue is Auth is not throwing an error or do something if the tokens are revoked when calling `Auth.currentAuthenticatedUser({bypassCache: true})`

**Comment by kouak** [comment] 2019-06-20 15:56
Is there any workaround ?

**Comment by sammartinez** [comment] 2019-11-01 18:01
@mmritesh Are you still having this issue with the latest version of Amplify? Please let us know.

**Comment by ericclemmons** [comment] 2020-05-11 20:53
This appears to be a duplicate of https://github.com/aws-amplify/amplify-js/issues/3435#issuecomment-597851340, where we're awaiting support for revoking unexpired tokens from Cognito.

If so, I can mark this as a duplicate and we can track/update in #3435...

**Comment by sammartinez** [comment] 2020-06-09 15:48
marking this as a duplicate from the above comment and resolving issue

**Closed by sammartinez** 2020-06-09 15:48 UTC
Labels: Cognito, Service Team, bug
