### ISSUE TITLE
code: 'UnknownError', message: 'Unkown error'

### ISSUE THREAD

**Issue by wzup** [aws-amplify/amplify-js#1078] opened 2018-06-21 10:27 UTC
### Do you want to request a feature or report a bug?

Bug

### What is the current behavior?

Lib throws
> code: 'UnknownError', message: 'Unkown error'

### The steps to reproduce

```javascript
global.fetch = require('node-fetch');
const Amplify = require( 'aws-amplify' ).default;
const Auth = Amplify.Auth;

Amplify.configure( {
    Auth: {
        // REQUIRED - Amazon Cognito Identity Pool ID
        identityPoolId: 'us-east-2:...',
        // REQUIRED - Amazon Cognito Region
        region: 'us-east-2',
        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'us-east-2_', // email & password
        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: '', // email & password
        // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
        mandatorySignIn: true,
    }
} );

     Auth.signIn( e, password )
        .then(user => console.log(user))
        .catch(err => console.error('[ERR]', err));
```

ANd error
> { code: 'UnknownError', message: 'Unkown error' }

### What is the expected behavior?

User is signed in

Same error https://github.com/aws/aws-amplify/issues/990
Solution doesn't work for me

**Comment by wzup** [comment] 2018-06-21 10:39
https://github.com/aws/aws-amplify/issues/487#issuecomment-377360591

**Comment by haverchuck** [comment] 2018-06-22 17:04
Hi @wzup 

I am having trouble reproducing this.  What type of application are you running this in?

**Comment by guycassidy** [comment] 2018-06-23 20:41
I'm having the same issue. Using a web app:

If I try to log in as a user that doesn't exist, it fails and reports that the user doesn't exist.
If I dry to log in with the wrong password, it fails and reports that the password or user are incorrect
If I log in with the right credentials, it returns:
{
  code: "UnknownError"
  message: "Unkown error"  <- typo?
}

My code:

`document.getElementById("signup-submit-button").addEventListener("click", (e) => {
  e.preventDefault();

  var email = document.getElementById("email-input").value
  var password = document.getElementById("password-input").value


  var authenticationData = {
    Username: email,
    Password: password,
  };
  var authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails(authenticationData);

  var userData = {
    Username: email,
    Pool: userPool
  };

  var cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
  cognitoUser.authenticateUser(authenticationDetails, {
    onSuccess: function (result) {
      var accessToken = result.getAccessToken().getJwtToken();

      //POTENTIAL: Region needs to be set if not already set previously elsewhere.
      AWS.config.region = region;

      AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: poolData.UserPoolId, // your identity pool id here
        Logins: {
          // Change the key below according to the specific region your user pool is in.
          'cognito-idp.<REGION>.amazonaws.com/<POOL ID>': result.getIdToken().getJwtToken()
        }
      });

      //refreshes credentials using AWS.CognitoIdentity.getCredentialsForIdentity()
      AWS.config.credentials.refresh((error) => {
        if (error) {
          console.error(error);
        } else {
          // Instantiate aws sdk service objects now that the credentials have been updated.
          // example: var s3 = new AWS.S3();
          console.log('Successfully logged!');
        }
      });
    },

    onFailure: function (err) {
      console.log(err.message || JSON.stringify(err));
    },

  });

})`

**Comment by DMor1** [comment] 2018-07-14 22:46
I was able to reproduce this using the following CloudFormation template. I manually created a user in the user pool and attempted to login by using the example code provided + Client App ID + Generated User Pool ID.

Create file named `reproduce_error.yml` with the template code below and execute
`aws cloudformation deploy --stack-name ReproduceUnknownError --template-file reproduce_error.yml`

`AWSTemplateFormatVersion: 2010-09-09

Description: Reproduce Cognito UnknownError

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        InviteMessageTemplate:
          EmailMessage: "Your username is {username} and temporary password is {####}."
          EmailSubject: "Your temporary password"
          SMSMessage: "Your username is {username} and temporary password is {####}."
        UnusedAccountValidityDays: 1
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: true
      EmailVerificationMessage: "Your verification code is {####}."
      EmailVerificationSubject: "Your verification code"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      UserPoolName: TestUserPool
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: email
          Required: true
      SmsAuthenticationMessage: "Your authentication message code is {####}."
      SmsVerificationMessage: "Your verification code is {####}."

  CognitoClientAppTest:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: UserPoolAppClientTest
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      GenerateSecret: false
      ReadAttributes:
        - email
      RefreshTokenValidity: 1
      UserPoolId:
         Ref: CognitoUserPool
`

**Comment by jordanranz** [comment] 2019-04-26 19:54
The "Unknown Error" has been changed to return the actual error message. This will help determine the root cause of your issue. 

Closing this for now. Please reopen if there are any further questions or concerns.

**Closed by jordanranz** 2019-04-26 19:54 UTC
Labels: Auth, investigating
