### ISSUE TITLE
Bundling amplify is not working with rollup/typescript  

### ISSUE THREAD

**Issue by shox-harri** [aws-amplify/amplify-js#6698] opened 2020-09-01 11:44 UTC
**Describe the bug**
Bundling amplify is not working with rollup/typescript, some packages are considered as external dependencies and rollup is not able resolve it.

To explain more check the following example:
One of the dependencies is middleware-retry (from aws sdk v3):
node_modules/@aws-sdk/middleware-retry -> package.json:
```{
  "name": "@aws-sdk/middleware-retry",
  "version": "1.0.0-gamma.3",
 ...
  "main": "./dist/cjs/index.js",
  "module": "./dist/es/index.js",
  "types": "./dist/cjs/index.d.ts",
 ...
}
```
This package doesn't contain `./dist/es` files while it's specified in `module` field, check the following screenshot:
<img width="235" alt="Screen Shot 2020-09-01 at 2 38 50 PM" src="https://user-images.githubusercontent.com/47078853/91844879-e323a100-ec60-11ea-8880-801190fbca82.png">
As a result, Rollup will not be able to bundle this dependency as the file doesn't exists! while this issue is fixed in later versions `1.0.0-gamma.6`, but amplify still rely on 1.0.0-gamma.3 version.

**To Reproduce**
From this repo https://github.com/shox-harri/aws-amplify-bug

```
yarn 
rollup -c
```

**Expected behavior**
I should be able to bundle the app with no external dependencies 
**Code Snippet**
https://github.com/shox-harri/aws-amplify-bug

**Screenshots**

 <img width="1440" alt="Screen Shot 2020-09-01 at 2 14 16 PM" src="https://user-images.githubusercontent.com/47078853/91842977-a1452b80-ec5d-11ea-9ebe-742660750a30.png">

<img width="1430" alt="Screen Shot 2020-09-01 at 2 14 06 PM" src="https://user-images.githubusercontent.com/47078853/91843051-bfab2700-ec5d-11ea-8560-59cd8ef2047c.png">
 
<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 186.86 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/opt/nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/opt/nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.12.0 - /usr/local/opt/nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Brave Browser: 75.0.65.121
    Chrome: 85.0.4183.83
    Firefox: 72.0.2
    Safari: 13.1.1
  npmPackages:
    @rollup/plugin-json: ^4.1.0 => 4.1.0 
    @types/angular: ^1.6.51 => 1.7.2 
    @types/angular-strap: ^2.3.1 => 2.3.1 
    @types/angular-ui-router: ^1.1.40 => 1.1.40 
    @types/jquery: ^3.3.29 => 3.5.1 
    @types/nunjucks: ^3.1.0 => 3.1.3 
    @types/systemjs: ^0.20.6 => 0.20.7 
    @types/underscore: ^1.8.9 => 1.10.22 
    aws-amplify: 3.0.25 => 3.0.25 
    cli-progress: ^3.5.0 => 3.8.2 
    rollup: 2.12.0 => 2.12.0 
    rollup-plugin-alias: ^1.5.1 => 1.5.2 
    rollup-plugin-angular: ^0.5.3 => 0.5.3 
    rollup-plugin-commonjs: ^10.1.0 => 10.1.0 
    rollup-plugin-multi-entry: ^2.1.0 => 2.1.0 
    rollup-plugin-node-resolve: ^5.2.0 => 5.2.0 
    rollup-plugin-progress: ^1.0.0 => 1.1.2 
    rollup-plugin-re: ^1.0.7 => 1.0.7 
    rollup-plugin-typescript2: ^0.27.1 => 0.27.2 
    rollup-plugin-uglify: ^6.0.4 => 6.0.4 
    typescript: 3.8.2 => 3.8.2 
  npmGlobalPackages:
    grunt-cli: 1.3.2
    gulp-cli: 2.2.0
    n: 6.1.3
    npm: 6.12.0
    rollup: 1.26.3
    typescript: 3.7.2
    verdaccio: 4.4.2
    yarn: 1.19.1
```

</details>

**Comment by wlee221** [comment] 2020-09-02 20:32
Hello @shox-harri, thanks for reporting the issue. This seems to be duplicate of #6685, so we will be closing this issue in favor of #6685. We are testing the latest `aws-sdk-js@gamma.v8` in order to validate non-breaking changes and will provide you with an update. Thank you!

**Closed by wlee221** 2020-09-02 20:32 UTC
Labels: Build, to-be-reproduced
