### ISSUE TITLE
Storage.put 403 with federated identities

### ISSUE THREAD

**Issue by chadfaurie** [aws-amplify/amplify-js#5801] opened 2020-05-16 05:19 UTC
**Describe the bug**
Uploading a file using Storage.put to private S3 from using aws-amplify: 3.0.11 I get a 403, using google federated logins, normal cognito users work fine

The Amplify logs report that that that identityId: undefined and the url generated to upload contains undefined where the identityId should be
https://XXX.XXX.s3.eu-west-1.amazonaws.com/private/undefined/file.csv

**To Reproduce**

Note: I am not using the Hosted UI

1. Sign in with a Google Account
2. Run a Storage.put that is private
3. See error 403 in network request

**Expected behavior**
File to be uploaded to private S3 folder with a 200 status code

**Code Snippet**
Storage.put(name, file, {
      level: "private",
      serverSideEncryption: "AES256"
    })

**Screenshots**
-

**What is Configured?**
  * `aws-exports` file:
   ```
   const awsmobile = {
  aws_app_analytics: "enable",
  aws_cloud_logic: "enable",
  aws_cloud_logic_custom: [
    {
      id: "",
      name: "",
      description: "",
      endpoint: "",
      region: "eu-west-1",
      paths: ["/123"],
    },
  ],

  aws_cognito_identity_pool_id:
    "",
  aws_cognito_region: "eu-west-1",
  aws_custom_domains: [{ domain: "", apiId: "" }],
  aws_google_app_permissions: "email,profile,openid",
  aws_google_web_app_id:
    "",
  aws_mandatory_sign_in: "enable",
  aws_mobile_analytics_app_id: "422b0264aed94eaaa0ab84a997ed54ad",
  aws_mobile_analytics_app_region: "us-east-1",
  aws_project_id: "",
  aws_project_name: "",
  aws_project_region: "eu-west-1",
  aws_resource_name_prefix: "",
  aws_sign_in_enabled: "enable",
  aws_user_pools: "enable",
  aws_user_pools_id: "",
  aws_user_pools_mfa_type: "OFF",
  aws_user_pools_web_client_id: "",
  aws_user_files_s3_bucket: "",
  aws_user_files_s3_bucket_region: "eu-west-1",
}
   ```
   
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.19 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @aws-amplify/ui-react: ^0.2.5 => 0.2.5 
    @cubejs-client/core: ^0.19.13 => 0.19.14 
    @cubejs-client/react: ^0.19.13 => 0.19.13 
    @date-io/date-fns: 1.3.13 => 1.3.13 
    @material-ui/core: ^4.9.13 => 4.9.13 
    @material-ui/icons: ^4.5.1 => 4.9.1 
    @material-ui/lab: ^4.0.0-alpha.52 => 4.0.0-alpha.52 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles: ^4.9.13 => 4.9.13 
    @mdi/js: ^5.1.45 => 5.1.45 
    @mdi/react: ^1.4.0 => 1.4.0 
    @nivo/bar: ^0.61.1 => 0.61.1 
    @nivo/bullet: ^0.61.1 => 0.61.1 
    @nivo/calendar: ^0.61.1 => 0.61.1 
    @nivo/heatmap: ^0.61.0 => 0.61.0 
    @types/node: ^13.13.2 => 13.13.4 
    @types/react: ^16.9.34 => 16.9.34 
    @types/react-dom: ^16.9.6 => 16.9.7 
    @types/yup: ^0.28.0 => 0.28.0 
    @xstate/react: ^0.8.1 => 0.8.1 
    autosuggest-highlight: ^3.1.1 => 3.1.1 
    aws-amplify: ^3.0.11 => 3.0.11 
    chart.js: ^2.9.3 => 2.9.3 
    date-fns: ^2.12.0 => 2.12.0 
    eslint: ^6.8.0 => 6.8.0 
    eslint-config-prettier: ^6.11.0 => 6.11.0 
    firebase: ^7.14.2 => 7.14.2 
    formik: ^2.0.6 => 2.1.4 
    gatsby: ^2.21.10 => 2.21.10 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.3.5 => 2.4.0 
    gatsby-plugin-canonical-urls: ^2.2.0 => 2.3.0 
    gatsby-plugin-firebase: ^0.2.0-beta.4 => 0.2.0-beta.4 
    gatsby-plugin-firebase-messaging: ^1.0.2 => 1.0.2 
    gatsby-plugin-google-tagmanager: ^2.2.4 => 2.3.0 
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.8 
    gatsby-plugin-offline: ^3.1.4 => 3.2.0 
    gatsby-plugin-react-helmet: ^3.2.5 => 3.3.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.5.6 => 2.6.0 
    gatsby-plugin-sitemap: ^2.3.5 => 2.4.0 
    gatsby-plugin-typescript: ^2.3.5 => 2.4.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.2.4 => 2.3.0 
    gatsby-source-prismic-graphql: ^3.5.0 => 3.5.0 
    gatsby-transformer-sharp: ^2.4.6 => 2.5.0 
    isomorphic-fetch: ^2.2.1 => 2.2.1 
    lodash: ^4.17.15 => 4.17.15 
    logrocket: ^1.0.7 => 1.0.7 
    notistack: ^0.9.11 => 0.9.11 
    numeral: ^2.0.6 => 2.0.6 
    prismic-reactjs: ^1.3.0 => 1.3.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^16.13.1 => 16.13.1 
    react-big-calendar: ^0.24.5 => 0.24.5 
    react-chartjs-2: ^2.9.0 => 2.9.0 
    react-dom: ^16.13.1 => 16.13.1 
    react-dropzone: ^11.0.1 => 11.0.1 
    react-google-button: ^0.7.1 => 0.7.1 
    react-grid-layout: ^0.18.3 => 0.18.3 
    react-helmet: ^6.0.0 => 6.0.0 
    react-joyride: ^2.2.1 => 2.2.1 
    react-virtualized: ^9.21.2 => 9.21.2 
    recharts: ^1.8.5 => 1.8.5 
    yup: ^0.28.5 => 0.28.5 
  npmGlobalPackages:
    @aws-amplify/cli: 4.19.0
    @timezor/timezor-core: 0.0.0-development
    atlas-connect: 0.6.6
    bluetrino-pay-core: 1.0.9
    create-openapi-repo: 2.0.0-rc.7
    eslint: 6.8.0
    expo-cli: 3.18.6
    gatsby-cli: 2.12.8
    jsdoc: 3.6.3
    nodemon: 2.0.3
    npm-check: 5.9.2
    npm: 6.14.2
    redoc-cli: 0.9.4
    rimraf: 3.0.2
    semantic-release-cli: 5.2.3
    sequelize-cli: 5.4.0
    serverless: 1.67.0
    swagger-jsdoc: 3.5.0
    tslint: 5.16.0
    typedoc: 0.15.0
    typescript: 3.7.5
    yarn: 1.16.0
```

</details>

DEBUG] 18:00.603 AWSS3Provider - set credentials for storage 
Object { accessKeyId: "", sessionToken: "", secretAccessKey: "", identityId: undefined, authenticated: true }

**Comment by chad-codeworkshop** [comment] 2020-05-16 05:39
Duplicate of #5440?

**Comment by chad-codeworkshop** [comment] 2020-05-16 05:47
I am using the Authenticator like this:

```
export default withAuthenticator(App, {
  federated: {
    googleClientId: googleClientId,
  },
})
```

**Comment by chad-codeworkshop** [comment] 2020-05-17 08:51
Having a look at the oAuth flow without the Hosted UI, it seems that identity_id is not returned from the google auth button and that's what is causing my issues

**Comment by LordParsley** [comment] 2020-05-28 14:15
I have a similar issue with federated identities affecting my `Auth0` sign-in flow.

The credentials returned are missing an `identityId`:

```
{
  "accessKeyId": "xxx",
  "secretAccessKey": "xxx",
  "sessionToken": "xxx",
  "expiration": Thu May 28 2020 17:12:05 GMT+0200 (SAST)
}
```

I am using

```
    "@aws-amplify/api": "^3.1.12",
    "@aws-amplify/auth": "^3.2.9",
    "@aws-amplify/core": "^3.2.9",
    "@aws-amplify/storage": "^3.2.2",
```

This was previously working under

```
    "aws-amplify": "^1.3.3",
```

**Comment by chad-codeworkshop** [comment] 2020-05-30 08:23
@LordParsley luckily I was fetching the identityId and storing it in DynamoDb with user settings etc so I was able to fetch this with startup and then enabled me to do the upload to the private folder on the bucket

**Comment by ashika01** [comment] 2020-07-29 23:09
@chadfaurie I just tested this with google federation and I am able to put the object properly. I can see 200 status code on my network tab also the file uploaded in my s3.

My code is pretty simple, 
```
import React, { useEffect, useState } from "react";
import Amplify, { Auth, Hub, Storage } from "aws-amplify";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);

function App() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
        case "cognitoHostedUI":
          getUser().then((userData) => setUser(userData));
          break;
        case "signOut":
          setUser(null);
          break;
        case "signIn_failure":
        case "cognitoHostedUI_failure":
          console.log("Sign in failure", data);
          break;
      }
    });

    getUser().then((userData) => setUser(userData));
  }, []);

  function getUser() {
    return Auth.currentAuthenticatedUser()
      .then((userData) => userData)
      .catch(() => console.log("Not signed in"));
  }

  return (
    <div>
      <p>User: {user ? "Howdy user" : "No user"}</p>
      {user ? (
        <>
          <button
            onClick={async () => {
              const response = await Storage.put(
                "text.txt",
                JSON.stringify("awsconfig"),
                {
                  contentType: "application/json",
                  level: "private",
                }
              );
              console.log(response);
            }}
          >
            Storage put
          </button>
          <button onClick={() => Auth.signOut()}>Sign Out</button>
        </>
      ) : (
        <button onClick={() => Auth.federatedSignIn()}>
          Federated Sign In
        </button>
      )}
    </div>
  );
}

export default App;

```
**Before login:**
<img width="597" alt="Screen Shot 2020-07-29 at 5 05 07 PM" src="https://user-images.githubusercontent.com/35131273/88862598-f1902000-d1bd-11ea-8c27-fddc6b281c19.png">


**After login:**
<img width="1086" alt="Screen Shot 2020-07-29 at 5 05 33 PM" src="https://user-images.githubusercontent.com/35131273/88862623-ffde3c00-d1bd-11ea-9804-7b2e4b2f8559.png">


Versions I am using:
```
├─ @aws-amplify/analytics@3.2.5
├─ @aws-amplify/api-graphql@1.1.4
├─ @aws-amplify/api-rest@1.1.4
├─ @aws-amplify/api@3.1.21
├─ @aws-amplify/auth@3.3.3
├─ @aws-amplify/cache@3.1.21
├─ @aws-amplify/core@3.4.4
├─ @aws-amplify/datastore@2.2.8
├─ @aws-amplify/interactions@3.1.21
├─ @aws-amplify/predictions@3.1.21
├─ @aws-amplify/pubsub@3.0.22
├─ @aws-amplify/storage@3.2.11
├─ @aws-amplify/ui@2.0.2
├─ @aws-amplify/xr@2.1.21
└─ aws-amplify@3.0.22
```


I am closing this issue, because I wasn't able to reproduce this using the steps to reproduce here. Ping me if the issue still exists and I can reopen this issue for you.

**Closed by ashika01** 2020-07-29 23:09 UTC
Labels: Auth, Federation, Storage, to-be-reproduced
