### ISSUE TITLE
HubPayload is not accessible for package consumers

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-js#4817] opened 2020-01-31 17:23 UTC
**Describe the bug**
In a TypeScript project I wanted to use ```Hub.listen``` for ```auth``` events and when I defined my callback function I wanted to use the ```HubPayload``` type as the [documentation](https://aws-amplify.github.io/docs/js/hub#sending-messages.) suggests, but I did not find it exported from ```@aws-amplify/core``` where ```Hub``` lives.

**Expected behavior**
```HubPayload``` type accessible to package consumers, exported together with ```Hub``` from the core package.

I used the latest version of ```aws-amplify``` packages.

**Comment by elorzafe** [comment] 2020-01-31 19:23
Thanks @attilah for your feedback I will mark this as a feature-request, IMO is not a bug but definitely is something we should include

**Comment by tannerabread** [comment] 2022-11-18 20:29
Closing as duplicate of #5997 which has more context

**Closed by tannerabread** 2022-11-18 20:29 UTC
Labels: feature-request, Hub, TypeScript
