### ISSUE TITLE
Storage.put of multipart file returns successfully upon failure

### ISSUE THREAD

**Issue by andriworld** [aws-amplify/amplify-js#8781] opened 2021-08-20 16:48 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Storage

### Amplify Categories

Not applicable

### Environment information

<details>

```
 aws-amplify: ^4.2.4 => 4.2.4
```

</details>

### Describe the bug

When Storage.put fails at the end of a multipart upload (CompleteMultipartUpload), the call returns successfully and no error is thrown.

### Expected behavior

An error should be thrown or returned to the caller, indicating that the upload failed.

### Reproduction steps

1. Misconfigure your S3 bucket so that it will fail at the end of a multipart upload. For instance, as long as the CORS settings are not exposing the ETag header, files larger than 5MB will fail to upload. See https://github.com/aws-amplify/amplify-js/issues/61#issuecomment-445436658
2. Invoke Storage.put with a file that will cause the multipart upload to fail at the end. For instance, upload a file larger than 5MB to a bucket misconfigured as in step 1.
3. OBSERVATION: an error is correctly logged:
"AWSS3ProviderManagedUpload - error happened while finishing the upload. Cancelling the multipart upload Error: Request failed with status code 400"
However, the call returns successfully, and no error is thrown.

### Code Snippet

```javascript
const object = await Storage.put(uploadPath, file, {
      level: 'private',
      contentType: file.type
  })
  console.log('object: ' + JSON.stringify(object))
```

### Log output

<details>

```
18:36.583 axios-http-handler - Request failed with status code 400
18:36.584 AWSS3ProviderManagedUpload - error happened while finishing the upload. Cancelling the multipart upload Error: Request failed with status code 400
  | push../node_modules/@aws-amplify/core/lib-esm/Logger/ConsoleLogger.js.ConsoleLogger._log | @ | ConsoleLogger.js:139
-- | -- | -- | --
  | push../node_modules/@aws-amplify/core/lib-esm/Logger/ConsoleLogger.js.ConsoleLogger.error | @ | ConsoleLogger.js:210
  | (anonymous) | @ | AWSS3ProviderManagedUpload.js:274
  | step | @ | AWSS3ProviderManagedUpload.js:55
  | (anonymous) | @ | AWSS3ProviderManagedUpload.js:36
  | rejected | @ | AWSS3ProviderManagedUpload.js:28
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | fulfilled | @ | AWSS3ProviderManagedUpload.js:27
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | (anonymous) | @ | AWSS3ProviderManagedUpload.js:30
  | push../node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3ProviderManagedUpload.js.__awaiter | @ | AWSS3ProviderManagedUpload.js:26
  | push../node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3ProviderManagedUpload.js.AWSS3ProviderManagedUpload.finishMultiPartUpload | @ | AWSS3ProviderManagedUpload.js:250
  | (anonymous) | @ | AWSS3ProviderManagedUpload.js:146
  | step | @ | AWSS3ProviderManagedUpload.js:55
  | (anonymous) | @ | AWSS3ProviderManagedUpload.js:36
  | fulfilled | @ | AWSS3ProviderManagedUpload.js:27
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | fulfilled | @ | AWSS3ProviderManagedUpload.js:27
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | fulfilled | @ | AWSS3ProviderManagedUpload.js:27
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | fulfilled | @ | AWSS3ProviderManagedUpload.js:27
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | fulfilled | @ | AWSS3ProviderManagedUpload.js:27
  | Promise.then (async) |   |  
  | step | @ | AWSS3ProviderManagedUpload.js:29
  | (anonymous) | @ | AWSS3ProviderManagedUpload.js:30
  | push../node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3ProviderManagedUpload.js.__awaiter | @ | AWSS3ProviderManagedUpload.js:26
  | push../node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3ProviderManagedUpload.js.AWSS3ProviderManagedUpload.upload | @ | AWSS3ProviderManagedUpload.js:87
  | (anonymous) | @ | AWSS3Provider.js:401
  | step | @ | AWSS3Provider.js:43
  | (anonymous) | @ | AWSS3Provider.js:24
  | fulfilled | @ | AWSS3Provider.js:15
  | Promise.then (async) |   |  
  | step | @ | AWSS3Provider.js:17
  | (anonymous) | @ | AWSS3Provider.js:18
  | push../node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3Provider.js.__awaiter | @ | AWSS3Provider.js:14
  | push../node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3Provider.js.AWSS3Provider.put | @ | AWSS3Provider.js:326
  | push../node_modules/@aws-amplify/storage/lib-esm/Storage.js.Storage.put | @ | Storage.js:270

```

</details>

**Comment by mkrn** [comment] 2021-11-02 15:02
Please test this with `resumable: true` as well as with `useAccelerateEndpoint`.
It would resolve the Storage.put even if you go Offline mid-upload.
It will also call onComplete and would not invoke onError  of the resumable callbacks.

**Comment by jamesaucode** [comment] 2021-11-02 18:02
Hi @mkrn , I merged in https://github.com/aws-amplify/amplify-js/pull/9144 which should solve the `useAccelerateEndpoint` issue.

Can you elaborate a little bit on the last 2 points? Will be nice if you can open a new issue with more details. Thank you! 😄 

> It would resolve the Storage.put even if you go Offline mid-upload.
It will also call onComplete and would not invoke onError of the resumable callbacks.

**Comment by mkrn** [comment] 2021-11-03 13:58
@jamesaucode I'm sorry, what I meant is: 

Since "resumable" uses different callbacks, both variants should be tested when fixing this issue:

Non-resumable:

```
await Storage.put(key, file, {
      bucket: "bucketname",
      region: "us-east-1",
      progressCallback: onUploadProgress,
    });
```


Resumable:

```
await new Promise((resolve, reject) => {
    Storage.put(key, file, {
      resumable: true,
      useAccelerateEndpoint: true, 
      bucket: "bucketname",
      region: "us-east-1",
      progressCallback: onUploadProgress,
      completeCallback: (event) => {
        resolve(event);
      },
      errorCallback: (err) => {
        reject(err);
      },
    });
  })
```

The simple way to reproduce the bug is to switch to "Offline" in Dev Tools "Network" panel. I expect that non-resumable await would throw. And resumable version `errorCallback` and promise `reject` would be called in Promise.

Currently, both promises resolve when the network is turned "Offline", and there's No way of knowing that the upload failed.

I've also noticed that there's an uncaught error logged: "File size does not match between local file and file on s3"  even after successful uploads.

**Comment by mkrn** [comment] 2022-01-04 14:58
Any updates? This seems very important and could be raised in priority,  as it's the storage service, upload functionality, the bread and butter of AWS... Literally can't tell apart a failed upload from a successful one. The workarounds bloat the build size considerably or require 1+ days of engineering time.

**Comment by danielvouch** [comment] 2022-03-18 06:48
Any update on this?

**Comment by chrisbonifacio** [comment] 2022-04-12 17:29
Closing as a duplicate of https://github.com/aws-amplify/amplify-js/issues/9703

**Closed by chrisbonifacio** 2022-04-12 17:29 UTC
Labels: bug, Storage
