### ISSUE TITLE
LexV2 support

### ISSUE THREAD

**Issue by ramit21** [aws-amplify/amplify-js#9504] opened 2022-01-23 11:12 UTC
### Is this related to a new or existing framework?

Angular, React

### Is this related to another service?

Lex

### Describe the feature you'd like to request

Ability to connect to V2 Lex chatbot.

### Describe the solution you'd like

Want to render AWS lex chatbot response cards on angular app. Lex v1 response cards are not rendered by exsitng plugin. So please support Lex V2, or make it work with V1 itself.

### Describe alternatives you've considered

Want to render AWS lex chatbot response cards on angular app. Lex v1 response cards are not rendered by exsitng plugin. So please support Lex V2, or make it work with V1 itself.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by abdallahshaban557** [comment] 2022-08-09 22:55
Closing this issue since it is a duplicate of #7662

**Closed by abdallahshaban557** 2022-08-09 22:55 UTC
Labels: feature-request, Interactions
